### ISSUE TITLE
Crash: JitsiMeet Android is getting crashed when mixed with Qt/QML 

### ISSUE THREAD

**Issue by xdr-kzh** [jitsi/jitsi-meet#10180]
### Description:

Hey everyone, in my Qt/QML app calling JitsiMeetActivity or using JitsiMeetView in own activity leading to crash. But if I'm changing the main activity from QtActivity (which runs QML part) to empty Java activity, there is no crash and the videoconference works well.

### Steps to reproduce:

1. Set QtActivity-based activity as launcher / main activity in AndroidManifest.xml
2. Run Intent with JitsiMeetActivity from C++/Java code (doesn't matter, if you're doing from Android UI thread).
3. During loading, the activity is getting crashed. 

### Expected behavior:

Running conference.

### Actual behavior:

During loading, the activity is getting crashed.

```
D ReactNative: Initializing React Xplat Bridge.
D ReactNative: Initializing React Xplat Bridge before initializeBridge
D ReactNative: Initializing React Xplat Bridge after initializeBridge
D ReactNative: CatalystInstanceImpl.runJSBundle()
W libc    : malloc(474321993073) failed: returning null pointer
E AndroidRuntime: FATAL EXCEPTION: create_react_context
E AndroidRuntime: Process: com.somepackage, PID: 26421
E AndroidRuntime: java.lang.OutOfMemoryError: std::bad_alloc
E AndroidRuntime: 	at com.facebook.react.bridge.CatalystInstanceImpl.jniLoadScriptFromAssets(Native Method)
E AndroidRuntime: 	at com.facebook.react.bridge.CatalystInstanceImpl.loadScriptFromAssets(CatalystInstanceImpl.java:227)
E AndroidRuntime: 	at com.facebook.react.bridge.JSBundleLoader$1.loadScript(JSBundleLoader.java:28)
E AndroidRuntime: 	at com.facebook.react.bridge.CatalystInstanceImpl.runJSBundle(CatalystInstanceImpl.java:261)
E AndroidRuntime: 	at com.facebook.react.ReactInstanceManager.createReactContext(ReactInstanceManager.java:1175)
E AndroidRuntime: 	at com.facebook.react.ReactInstanceManager.access$1000(ReactInstanceManager.java:125)
E AndroidRuntime: 	at com.facebook.react.ReactInstanceManager$5.run(ReactInstanceManager.java:951)
E AndroidRuntime: 	at java.lang.Thread.run(Thread.java:923)
```

### Server information:

Standart server: https://meet.jit.si

### Client information:

- Browser / app version: Latest SDK version 
- Operating System: Android 10

**Comment by xdr-kzh** [comment]
PS: the issue was because of incompatibility with EGL.so, which I had added to the APK file (that caused some problems with memory allocation). Deleting it solved the issue.
