### ISSUE TITLE
Jitsi Sdk on Android 6.0.1

### ISSUE THREAD

**Issue by nghuyy** [jitsi/jitsi-meet#10182]
Give error:

java.lang.NoClassDefFoundError: Failed resolution of: Landroid/graphics/ColorSpace; 
Didn't find class "android.graphics.ColorSpace"

Stack trace:
```
App: app.iotabot.meet/1.0.25(Android:6.0.1-MiBOX4)(3497652224/5594595328)
java.lang.NoClassDefFoundError: Failed resolution of: Landroid/graphics/ColorSpace; 
at z3.d.l(EncodedImage.java:34) at d4.c0$a.d(LocalFetchProducer.java:3) at d4.w0.run(StatefulProducerRunnable.java:2) at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113) at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588) at u3.l$a.run(PriorityThreadFactory.java:4) at java.lang.Thread.run(Thread.java:818) Caused by: java.lang.ClassNotFoundException: Didn't find class "android.graphics.ColorSpace" on path: DexPathList[[zip file "/data/app/app.iotabot.meet-1/base.apk"],nativeLibraryDirectories=[/data/app/app.iotabot.meet-1/lib/arm, /data/app/app.iotabot.meet-1/base.apk!/lib/armeabi-v7a, /vendor/lib, /system/lib]] at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56) at java.lang.ClassLoader.loadClass(ClassLoader.java:511) at java.lang.ClassLoader.loadClass(ClassLoader
```
Any high version of Android, like Android 10 or 11 work perfect

**Comment by saghul** [comment]
Can you please paste the full stack trace?

**Comment by nghuyy** [comment]
Tha

**Comment by nghuyy** [comment]
"E/ACRA: ACRA caught a NoClassDefFoundError"
Thank for help, this is bug of ACRA libs, not jitsi, i'm sorry  about that!

**Comment by nghuyy** [comment]
```
--------- beginning of crash
2021-10-16 02:49:46.331 5213-5351/app.iotabot.meet E/AndroidRuntime: FATAL EXCEPTION: FrescoIoBoundExecutor-1
    Process: app.iotabot.meet, PID: 5213
    java.lang.NoClassDefFoundError: Failed resolution of: Landroid/graphics/ColorSpace;
        at z3.d.l(EncodedImage.java:34)
        at d4.c0$a.d(LocalFetchProducer.java:3)
        at d4.w0.run(StatefulProducerRunnable.java:2)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
        at u3.l$a.run(PriorityThreadFactory.java:4)
        at java.lang.Thread.run(Thread.java:818)
     Caused by: java.lang.ClassNotFoundException: Didn't find class "android.graphics.ColorSpace" on path: DexPathList[[zip file "/data/app/app.iotabot.meet-2/base.apk"],nativeLibraryDirectories=[/data/app/app.iotabot.meet-2/lib/x86, /data/app/app.iotabot.meet-2/base.apk!/lib/x86, /vendor/lib, /system/lib]]
        at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:511)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:469)
        at z3.d.l(EncodedImage.java:34) 
        at d4.c0$a.d(LocalFetchProducer.java:3) 
        at d4.w0.run(StatefulProducerRunnable.java:2) 
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113) 
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588) 
        at u3.l$a.run(PriorityThreadFactory.java:4) 
        at java.lang.Thread.run(Thread.java:818) 
    	Suppressed: java.lang.ClassNotFoundException: android.graphics.ColorSpace
        at java.lang.Class.classForName(Native Method)
        at java.lang.BootClassLoader.findClass(ClassLoader.java:781)
        at java.lang.BootClassLoader.loadClass(ClassLoader.java:841)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:504)
        		... 8 more
     Caused by: java.lang.NoClassDefFoundError: Class not found using the boot class loader; no stack trace available
     
``
     Only crash when minifyEnabled true. 
     
``` proguard
-keep,allowobfuscation @interface com.facebook.proguard.annotations.DoNotStrip
-keep,allowobfuscation @interface com.facebook.proguard.annotations.KeepGettersAndSetters
-keep,allowobfuscation @interface com.facebook.common.internal.DoNotStrip

# Do not strip any method/class that is annotated with @DoNotStrip
-keep @com.facebook.proguard.annotations.DoNotStrip class *
-keep @com.facebook.common.internal.DoNotStrip class *
-keepclassmembers class * {
    @com.facebook.proguard.annotations.DoNotStrip *;
    @com.facebook.common.internal.DoNotStrip *;
}

-keepclassmembers @com.facebook.proguard.annotations.KeepGettersAndSetters class * {
  void set*(***);
  *** get*();
}

-keep class * extends com.facebook.react.bridge.JavaScriptModule { *; }
-keep class * extends com.facebook.react.bridge.NativeModule { *; }
-keepclassmembers,includedescriptorclasses class * { native <methods>; }
-keepclassmembers class *  { @com.facebook.react.uimanager.UIProp <fields>; }
-keepclassmembers class *  { @com.facebook.react.uimanager.annotations.ReactProp <methods>; }
-keepclassmembers class *  { @com.facebook.react.uimanager.annotations.ReactPropGroup <methods>; }

-dontwarn com.facebook.react.**
-keep,includedescriptorclasses class com.facebook.react.bridge.** { *; }

# okhttp

-keepattributes Signature
-keepattributes *Annotation*
-keep class okhttp3.** { *; }
-keep interface okhttp3.** { *; }
-dontwarn okhttp3.**

# okio

-keep class sun.misc.Unsafe { *; }
-dontwarn java.nio.file.*
-dontwarn org.codehaus.mojo.animal_sniffer.IgnoreJRERequirement
-keep class okio.** { *; }
-dontwarn okio.**

# WebRTC

-keep class org.webrtc.** { *; }
-dontwarn org.chromium.build.BuildHooksAndroid

# Jisti Meet SDK

-keep class org.jitsi.meet.sdk.** { *; }

# We added the following when we switched minifyEnabled on. Probably because we
# ran the app and hit problems...

-keep class com.facebook.react.bridge.CatalystInstanceImpl { *; }
-keep class com.facebook.react.bridge.ExecutorToken { *; }
-keep class com.facebook.react.bridge.JavaScriptExecutor { *; }
-keep class com.facebook.react.bridge.ModuleRegistryHolder { *; }
-keep class com.facebook.react.bridge.ReadableType { *; }
-keep class com.facebook.react.bridge.queue.NativeRunnable { *; }
-keep class com.facebook.react.devsupport.** { *; }

-dontwarn com.facebook.react.devsupport.**
-dontwarn com.google.appengine.**
-dontwarn com.squareup.okhttp.**
-dontwarn javax.servlet.**

# ^^^ We added the above when we switched minifyEnabled on.

# Rule to avoid build errors related to SVGs.
-keep public class com.horcrux.svg.** {*;}

# Hermes
-keep class com.facebook.hermes.unicode.** { *; }

# This app
-keep class app.iotabot.meet.** { *; }

-keep class huynguyen.hlibs.** { *; }
-keep class org.conscrypt.** { *; }
-keep class android.graphics.** { *; }

# Backward compatibility code.
-dontnote libcore.io.Libcore
-dontnote org.apache.harmony.xnet.provider.jsse.OpenSSLRSAPrivateKey
-dontnote org.apache.harmony.security.utils.AlgNameMapper
-dontnote sun.security.x509.AlgorithmId

-dontwarn android.util.StatsEvent
-dontwarn dalvik.system.BlockGuard
-dontwarn dalvik.system.BlockGuard$Policy
-dontwarn dalvik.system.CloseGuard
-dontwarn com.android.org.conscrypt.AbstractConscryptSocket
-dontwarn com.android.org.conscrypt.ConscryptFileDescriptorSocket
-dontwarn com.android.org.conscrypt.OpenSSLSocketImpl
-dontwarn org.apache.harmony.xnet.provider.jsse.OpenSSLSocketImpl
     
```

**Comment by ouchadam** [comment]
upstream issue https://github.com/facebook/fresco/issues/2638
