### ISSUE TITLE
Jitsi Meet Translation

### ISSUE THREAD

**Issue by ali-alhaidary** [jitsi/jitsi-meet#10360]
### Description:
update-translation.js generates an error

### Steps to reproduce:
cd lang
node update-translation.js main-es.json

### Expected behavior:
language file updated with missing keys

### Actual behavior:
error generated:

module.js:549
    throw err;
    ^

Error: Cannot find module 'traverse'
    at Function.Module._resolveFilename (module.js:547:15)
    at Function.Module._load (module.js:474:25)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/usr/share/jitsi-meet/lang/update-translation.js:5:18)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)

### Server information:

- Jitsi Meet version:2.0.6433
- Operating System:ubuntu 18.04 LTS

### Client information:

- Browser / app version: terminal
- Operating System:ubuntu 18.04 LTS

**Comment by ali-alhaidary** [comment]
It seems that nodejs and node-traverse must be installed first...

**Comment by ali-alhaidary** [comment]
sudo apt install node-traverse
