### ISSUE TITLE
Unmarshalling Exception - Android App is throwing exception

### ISSUE THREAD

**Issue by dakshay-devstree** [jitsi/jitsi-meet#10442]
Due to unnecessary parcel unbinding in JitsiMeetConferenceOptions class app is crashing.  It is throwing below exception. (Screenshot for reference)

```
Caused by: java.lang.RuntimeException: Parcel android.os.Parcel@e56e082: Unmarshalling unknown type code 7143535 at offset 1604
        at android.os.Parcel.readValue(Parcel.java:2945)
        at android.os.Parcel.readArrayMapInternal(Parcel.java:3244)
        at android.os.BaseBundle.initializeFromParcelLocked(BaseBundle.java:292)
        at android.os.BaseBundle.unparcel(BaseBundle.java:236)
        at android.os.Bundle.getBundle(Bundle.java:924)
        at com.google.firebase.messaging.FcmLifecycleCallbacks.onActivityCreated(com.google.firebase:firebase-messaging@@23.0.0:4)
        at android.app.Application.dispatchActivityCreated(Application.java:373)
        at android.app.Activity.dispatchActivityCreated(Activity.java:1202)
        at android.app.Activity.onCreate(Activity.java:1475)
        at androidx.core.app.ComponentActivity.onCreate(ComponentActivity.java:85)
        at androidx.activity.ComponentActivity.onCreate(ComponentActivity.java:323)
        at androidx.fragment.app.FragmentActivity.onCreate(FragmentActivity.java:273)
        at org.jitsi.meet.sdk.JitsiMeetActivity.onCreate(JitsiMeetActivity.java:79)
.
```

Just try to start normal intent with JitsiMeetAactivity, It will lead to a crash.

```
 val intent = Intent(context, JitsiActivity::class.java)
            intent.action = ACTION_CONFERENCE
            intent.putExtra(KEY_CONFERENCE,
                JitsiManager.getJitsiOption(item.roomIditem.isVoiceCall())
            )
            context?.startActivity(intent)
```

# byte tmpAudioMuted = in.readByte();   ## This line seems unnecessary, Because we never bind this values in parcel which lead to exception in our case.

```
 private JitsiMeetConferenceOptions(Parcel in) {
        this.serverURL = (URL)in.readSerializable();
        this.room = in.readString();
        this.token = in.readString();
        this.colorScheme = in.readBundle();
        this.config = in.readBundle();
        this.featureFlags = in.readBundle();
        this.userInfo = new JitsiMeetUserInfo(in.readBundle());
 >     byte tmpAudioMuted = in.readByte(); 
}
````
#Screenshot
![image](https://user-images.githubusercontent.com/53896356/143408801-1eecbafe-1767-4754-bb15-897b78c72a2f.png)

#System Information:
- Jitsi Meet version: 3.10.2
- Operating System: Android 
-  Devices - On Pixel 2 and Pixel 3 Devices
- Operating System: Android 11, 12

**Comment by saghul** [comment]
What SDK version is that?

**Comment by dakshay-devstree** [comment]
Jitsi Meet SDK version: 10.4.2

**Comment by saghul** [comment]
I don't see it on master, so I guess we gave fixed it...

**Comment by dakshay-devstree** [comment]
Yes, It will be really nice of you to get us a fix SOON in the Dependency. Thanks
