### ISSUE TITLE
Crash with android SDK 3.10.1 and 3.10.2

### ISSUE THREAD

**Issue by EbelloImbox** [jitsi/jitsi-meet#10476]
If I upgrade my Jitsi SDK to 3.10.1 or 3.10.2 from 3.10.0 I´ve got a crash when I start Jitsi:

```
2021-11-29 16:58:48.538 22817-23094/com.spotbros.defense E/AndroidRuntime: FATAL EXCEPTION: mqt_js
    Process: com.spotbros.defense, PID: 22817
    com.facebook.jni.CppException: Can't find variable: window
    
    index.android.bundle:810:59
    v@index.android.bundle:2:1474
    index.android.bundle:19:2984
    index.android.bundle:19:3676
    v@index.android.bundle:2:1474
    index.android.bundle:17:38
    v@index.android.bundle:2:1474
    index.android.bundle:7:109
    v@index.android.bundle:2:1474
    index.android.bundle:6:30
    v@index.android.bundle:2:1474
    d@index.android.bundle:2:876
    global code@index.android.bundle:2638:4
        at com.facebook.react.bridge.queue.NativeRunnable.run(Native Method)
        at android.os.Handler.handleCallback(Handler.java:883)
        at android.os.Handler.dispatchMessage(Handler.java:100)
        at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:26)
        at android.os.Looper.loop(Looper.java:214)
        at com.facebook.react.bridge.queue.MessageQueueThreadImpl$4.run(MessageQueueThreadImpl.java:225)
        at java.lang.Thread.run(Thread.java:919)
2021-11-29 16:58:48.539 22817-23094/com.spotbros.defense E/JitsiMeetSDK: JitsiMeetUncaughtExceptionHandler FATAL ERROR
    com.facebook.jni.CppException: Can't find variable: window
    
    index.android.bundle:810:59
    v@index.android.bundle:2:1474
    index.android.bundle:19:2984
    index.android.bundle:19:3676
    v@index.android.bundle:2:1474
    index.android.bundle:17:38
    v@index.android.bundle:2:1474
    index.android.bundle:7:109
    v@index.android.bundle:2:1474
    index.android.bundle:6:30
    v@index.android.bundle:2:1474
    d@index.android.bundle:2:876
    global code@index.android.bundle:2638:4
        at com.facebook.react.bridge.queue.NativeRunnable.run(Native Method)
        at android.os.Handler.handleCallback(Handler.java:883)
        at android.os.Handler.dispatchMessage(Handler.java:100)
        at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:26)
        at android.os.Looper.loop(Looper.java:214)
        at com.facebook.react.bridge.queue.MessageQueueThreadImpl$4.run(MessageQueueThreadImpl.java:225)
        at java.lang.Thread.run(Thread.java:919)
    
    com.facebook.jni.CppException: Can't find variable: window
    
    index.android.bundle:810:59
    v@index.android.bundle:2:1474
    index.android.bundle:19:2984
    index.android.bundle:19:3676
    v@index.android.bundle:2:1474
    index.android.bundle:17:38
    v@index.android.bundle:2:1474
    index.android.bundle:7:109
    v@index.android.bundle:2:1474
    index.android.bundle:6:30
    v@index.android.bundle:2:1474
    d@index.android.bundle:2:876
    global code@index.android.bundle:2638:4
        at com.facebook.react.bridge.queue.NativeRunnable.run(Native Method)
        at android.os.Handler.handleCallback(Handler.java:883)
        at android.os.Handler.dispatchMessage(Handler.java:100)
        at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:26)
        at android.os.Looper.loop(Looper.java:214)
        at com.facebook.react.bridge.queue.MessageQueueThreadImpl$4.run(MessageQueueThreadImpl.java:225)
        at java.lang.Thread.run(Thread.java:919)
```

If I use the same code with SDK version 3.10.0 it works fine. 

I am using JitsiMeetActivity and JitsiMeetFragment in different context to launch Jitsi Meet with the same result, any advise?

**Comment by saghul** [comment]
Did you build the SDK yourself or did you make changes?

**Comment by EbelloImbox** [comment]
I have cloned your oficial repository and I make a checkout to your commit from 29 Sept 2021 with android-sdk-3.10.1 TAG. I follow your guide to compile (npm upgrade, install, and I always use --force), if I make checkout on this commit I will get this error but If I make checkout to 3.10.0 version commit all works fine.

**Comment by saghul** [comment]
> (npm upgrade, install, and I always use --force),

Don't upgrade, and don't use `--force`. Do you see any errors otherwise?

**Comment by EbelloImbox** [comment]
ok I am going to clone repo again and I will try with your tips.
