### ISSUE TITLE
java.lang.UnsatisfiedLinkError: couldn't find DSO to load: libjscexecutor.so crash app on android 11 and above (jitsi android sdk)

### ISSUE THREAD

**Issue by TinNguyen22** [jitsi/jitsi-meet#10728]
### Description:
Hi Guys, I have integrate jitsi mobile sdk to my app and it's work fine on android 10.0 and below. But on android 11 and 12, it's crashed.
crash log
 ```
 2022-01-06 10:23:26.723 3725-3817/xxx E/AndroidRuntime: FATAL EXCEPTION: create_react_context
    Process: xxx, PID: 3725
    java.lang.UnsatisfiedLinkError: couldn't find DSO to load: libjscexecutor.so caused by: couldn't find DSO to load: libjsc.so caused by: dlopen failed: cannot locate symbol "__cxa_bad_typeid" referenced by "/data/data/xxx/lib-main/libjsc.so"...
        at com.facebook.soloader.SoLoader.doLoadLibraryBySoName(SoLoader.java:738)
        at com.facebook.soloader.SoLoader.loadLibraryBySoName(SoLoader.java:591)
        at com.facebook.soloader.SoLoader.loadLibrary(SoLoader.java:529)
        at com.facebook.soloader.SoLoader.loadLibrary(SoLoader.java:484)
        at com.facebook.react.jscexecutor.JSCExecutor.<clinit>(JSCExecutor.java:18)
        at com.facebook.react.jscexecutor.JSCExecutorFactory.create(JSCExecutorFactory.java:29)
        at com.facebook.react.ReactInstanceManager$5.run(ReactInstanceManager.java:952)
        at java.lang.Thread.run(Thread.java:923)
2022-01-06 10:23:26.730 3725-3817/xxx E/JitsiMeetLogger: JitsiMeetUncaughtExceptionHandler FATAL ERROR
    java.lang.UnsatisfiedLinkError: couldn't find DSO to load: libjscexecutor.so caused by: couldn't find DSO to load: libjsc.so caused by: dlopen failed: cannot locate symbol "__cxa_bad_typeid" referenced by "/data/data/xxx/lib-main/libjsc.so"...
        at com.facebook.soloader.SoLoader.doLoadLibraryBySoName(SoLoader.java:738)
        at com.facebook.soloader.SoLoader.loadLibraryBySoName(SoLoader.java:591)
        at com.facebook.soloader.SoLoader.loadLibrary(SoLoader.java:529)
        at com.facebook.soloader.SoLoader.loadLibrary(SoLoader.java:484)
        at com.facebook.react.jscexecutor.JSCExecutor.<clinit>(JSCExecutor.java:18)
        at com.facebook.react.jscexecutor.JSCExecutorFactory.create(JSCExecutorFactory.java:29)
        at com.facebook.react.ReactInstanceManager$5.run(ReactInstanceManager.java:952)
        at java.lang.Thread.run(Thread.java:923)
2022-01-06 10:23:26.733 3725-3817/xxx E/JitsiMeetSDK: JitsiMeetUncaughtExceptionHandler FATAL ERROR
    java.lang.UnsatisfiedLinkError: couldn't find DSO to load: libjscexecutor.so caused by: couldn't find DSO to load: libjsc.so caused by: dlopen failed: cannot locate symbol "__cxa_bad_typeid" referenced by "/data/data/xxx/lib-main/libjsc.so"...
        at com.facebook.soloader.SoLoader.doLoadLibraryBySoName(SoLoader.java:738)
        at com.facebook.soloader.SoLoader.loadLibraryBySoName(SoLoader.java:591)
        at com.facebook.soloader.SoLoader.loadLibrary(SoLoader.java:529)
        at com.facebook.soloader.SoLoader.loadLibrary(SoLoader.java:484)
        at com.facebook.react.jscexecutor.JSCExecutor.<clinit>(JSCExecutor.java:18)
        at com.facebook.react.jscexecutor.JSCExecutorFactory.create(JSCExecutorFactory.java:29)
        at com.facebook.react.ReactInstanceManager$5.run(ReactInstanceManager.java:952)
        at java.lang.Thread.run(Thread.java:923)
    
    java.lang.UnsatisfiedLinkError: couldn't find DSO to load: libjscexecutor.so caused by: couldn't find DSO to load: libjsc.so caused by: dlopen failed: cannot locate symbol "__cxa_bad_typeid" referenced by "/data/data/xxx/lib-main/libjsc.so"...
        at com.facebook.soloader.SoLoader.doLoadLibraryBySoName(SoLoader.java:738)
        at com.facebook.soloader.SoLoader.loadLibraryBySoName(SoLoader.java:591)
        at com.facebook.soloader.SoLoader.loadLibrary(SoLoader.java:529)
        at com.facebook.soloader.SoLoader.loadLibrary(SoLoader.java:484)
        at com.facebook.react.jscexecutor.JSCExecutor.<clinit>(JSCExecutor.java:18)
        at com.facebook.react.jscexecutor.JSCExecutorFactory.create(JSCExecutorFactory.java:29)
        at com.facebook.react.ReactInstanceManager$5.run(ReactInstanceManager.java:952)
        at java.lang.Thread.run(Thread.java:923)
 ```
### Client information:
- Jitsi Meet version: 4.1.0 (android sdk)
- Operating System: android 11 and android 12

**Comment by saghul** [comment]
Did you build the SDK yourself or are you using our binaries?

**Comment by TinNguyen22** [comment]
I'm using pre-build SDK binaries
`https://github.com/jitsi/jitsi-maven-repository/raw/master/releases`
`implementation ('org.jitsi.react:jitsi-meet-sdk:4.1.0')`

**Comment by saghul** [comment]
Are you using progruard?

**Comment by saghul** [comment]
Can you create a small project which demonstrates the issue? I'm unable to reproduce it.

**Comment by TinNguyen22** [comment]
Sorry to trouble you, I have created new project and integrated jitsi, it's work fine and no problem on android 11 and 12, it's only crashed on my old project. Thank you for your time and i'll close this issue now.
