### ISSUE TITLE
Getting console error when recording stopped.

### ISSUE THREAD

**Issue by ashiqhassan95** [jitsi/jitsi-meet#10811]
### Description:

Getting console error when stopped recording, but recording was successful.

### Steps to reproduce:

1. Join meeting.
2. Open console.
3. Start recording.
4. Stop recording after a few moments (recording started succesfully)
5. See the console error

### Server information:

- Jitsi Meet version: [meet.jitsi.si](https://meet.jit.si/)
- Operating System:

### Client information:

- Browser / app version: Chrome (97.0.4692.71)
- Operating System: Ubuntu 18.04

### Additional information:

![ksnip_20220119-170005](https://user-images.githubusercontent.com/2870845/150121618-6d7cbffe-9045-418b-94c8-1bf86a4fea44.png)

```log
react_devtools_backend.js:4045 @atlaskit/modal-dialog: Deprecation warning - Use of the footer prop in ModalDialog is deprecated. Please compose your ModalDialog using the 'components' prop instead
overrideMethod @ react_devtools_backend.js:4045
value @ Content.js:160
ss @ react-dom.production.min.js:212
bl @ react-dom.production.min.js:255
t.unstable_runWithPriority @ scheduler.production.min.js:19
Vr @ react-dom.production.min.js:122
gl @ react-dom.production.min.js:248
al @ react-dom.production.min.js:239
(anonymous) @ react-dom.production.min.js:123
t.unstable_runWithPriority @ scheduler.production.min.js:19
Vr @ react-dom.production.min.js:122
Kr @ react-dom.production.min.js:123
Gr @ react-dom.production.min.js:122
rl @ react-dom.production.min.js:240
notify @ Subscription.js:23
t.notifyNestedSubs @ Subscription.js:65
n.notifySubscribers @ Provider.js:59
t.handleChangeWrapper @ Subscription.js:70
p @ redux.js:220
(anonymous) @ index.js:14
(anonymous) @ middleware.js:30
(anonymous) @ middleware.js:33
(anonymous) @ middleware.js:19
(anonymous) @ middleware.web.js:30
(anonymous) @ middleware.any.js:44
(anonymous) @ middleware.js:67
(anonymous) @ middleware.js:45
(anonymous) @ middleware.js:61
(anonymous) @ middleware.js:19
(anonymous) @ middleware.js:121
(anonymous) @ middleware.js:71
(anonymous) @ middleware.js:79
(anonymous) @ middleware.js:39
(anonymous) @ middleware.js:221
(anonymous) @ middleware.js:11
(anonymous) @ middleware.js:60
(anonymous) @ middleware.js:31
(anonymous) @ middleware.web.js:46
(anonymous) @ middleware.web.js:24
(anonymous) @ middleware.any.js:94
(anonymous) @ middleware.js:77
(anonymous) @ middleware.web.js:34
(anonymous) @ middleware.js:32
(anonymous) @ middleware.js:25
(anonymous) @ middleware.js:16
(anonymous) @ middleware.js:21
(anonymous) @ middleware.js:23
(anonymous) @ middleware.js:20
(anonymous) @ middleware.js:167
(anonymous) @ middleware.js:59
(anonymous) @ middleware.js:39
(anonymous) @ middleware.js:33
(anonymous) @ middleware.js:209
(anonymous) @ middleware.js:39
(anonymous) @ middleware.js:24
(anonymous) @ middleware.js:28
(anonymous) @ middleware.web.js:20
(anonymous) @ middleware.js:42
(anonymous) @ middleware.js:208
(anonymous) @ middleware.js:21
(anonymous) @ middleware.js:130
(anonymous) @ middleware.js:44
(anonymous) @ middleware.js:49
(anonymous) @ middleware.js:90
(anonymous) @ middleware.js:12
(anonymous) @ middleware.js:39
(anonymous) @ middleware.js:35
(anonymous) @ middleware.web.js:30
(anonymous) @ middleware.any.js:105
(anonymous) @ middleware.js:203
(anonymous) @ middleware.js:106
(anonymous) @ middleware.js:29
(anonymous) @ middleware.js:27
(anonymous) @ middleware.js:23
(anonymous) @ middleware.web.js:11
(anonymous) @ middleware.any.js:78
(anonymous) @ middleware.js:16
(anonymous) @ middleware.js:91
(anonymous) @ middleware.js:75
(anonymous) @ middleware.js:24
(anonymous) @ middleware.js:20
(anonymous) @ middleware.js:15
(anonymous) @ middleware.js:101
(anonymous) @ middleware.js:23
(anonymous) @ middleware.js:21
(anonymous) @ middleware.js:25
(anonymous) @ middleware.js:76
(anonymous) @ middleware.js:236
(anonymous) @ middleware.web.js:26
(anonymous) @ middleware.js:201
(anonymous) @ middleware.js:38
(anonymous) @ middleware.web.js:107
_handleClick @ AbstractRecordButton.js:93
await in _handleClick (async)
_onClick @ AbstractButton.js:302
s @ react-dom.production.min.js:14
h @ react-dom.production.min.js:14
(anonymous) @ react-dom.production.min.js:14
b @ react-dom.production.min.js:15
it @ react-dom.production.min.js:52
at @ react-dom.production.min.js:51
ot @ react-dom.production.min.js:52
pt @ react-dom.production.min.js:56
z @ react-dom.production.min.js:287
B @ react-dom.production.min.js:19
Zt @ react-dom.production.min.js:70
Jt @ react-dom.production.min.js:69
t.unstable_runWithPriority @ scheduler.production.min.js:19
Vr @ react-dom.production.min.js:122
O @ react-dom.production.min.js:287
Kt @ react-dom.production.min.js:68
Show 63 more frames
actions.js:39 Uncaught (in promise) TypeError: Cannot destructure property 'jitsiTrack' of 'ip(...)' as it is undefined.
    at actions.js:39:21
    at index.js:11:18
    at middleware.js:30:12
    at middleware.js:33:20
    at middleware.js:19:20
    at middleware.web.js:30:20
    at middleware.any.js:44:20
    at middleware.js:67:12
    at middleware.js:45:12
    at middleware.js:61:12
    at middleware.js:19:20
    at middleware.js:121:12
    at middleware.js:71:12
    at middleware.js:79:20
    at middleware.js:39:12
    at middleware.js:221:12
    at middleware.js:11:20
    at middleware.js:60:12
    at middleware.js:31:20
    at middleware.web.js:46:12
    at middleware.web.js:24:12
    at middleware.any.js:94:20
    at middleware.js:77:12
    at middleware.web.js:34:20
    at middleware.js:32:12
    at middleware.js:25:12
    at middleware.js:16:20
    at middleware.js:21:12
    at middleware.js:23:12
    at middleware.js:20:20
    at middleware.js:167:12
    at middleware.js:59:12
    at middleware.js:39:20
    at middleware.js:33:12
    at middleware.js:209:12
    at middleware.js:39:12
    at middleware.js:24:12
    at middleware.js:28:20
    at middleware.web.js:20:20
    at middleware.js:42:20
    at middleware.js:208:12
    at middleware.js:21:20
    at middleware.js:130:12
    at middleware.js:44:12
    at middleware.js:49:12
    at middleware.js:90:20
    at middleware.js:12:20
    at middleware.js:39:12
    at middleware.js:35:12
    at middleware.web.js:30:12
    at middleware.any.js:105:12
    at middleware.js:203:12
    at middleware.js:106:20
    at middleware.js:29:16
    at middleware.js:27:12
    at middleware.js:23:20
    at middleware.web.js:11:20
    at middleware.any.js:78:12
    at middleware.js:16:20
    at middleware.js:91:12
    at middleware.js:75:12
    at middleware.js:24:20
    at middleware.js:20:12
    at middleware.js:15:20
    at middleware.js:101:12
    at middleware.js:23:20
    at middleware.js:21:20
    at middleware.js:25:12
    at middleware.js:76:20
    at middleware.js:236:12
    at middleware.web.js:26:12
    at middleware.js:201:12
    at middleware.js:38:12
    at Object.dispatch (middleware.web.js:107:12)
    at wK._toggleScreenshotCapture (StopRecordingDialog.js:49:20)
    at wK._onSubmit (AbstractStopRecordingDialog.js:75:18)
    at FN._onSubmit (AbstractDialog.js:117:36)
    at rL._onSubmit (StatelessDialog.js:286:21)
    at usePlatformLeafEventHandler.js:60:11
    at Object.s (react-dom.production.min.js:14:84)
    at h (react-dom.production.min.js:14:238)
    at react-dom.production.min.js:14:292
    at b (react-dom.production.min.js:15:72)
    at it (react-dom.production.min.js:52:170)
    at at (react-dom.production.min.js:51:255)
    at ot (react-dom.production.min.js:52:334)
    at pt (react-dom.production.min.js:56:10)
    at z (react-dom.production.min.js:287:189)
    at B (react-dom.production.min.js:19:57)
    at Zt (react-dom.production.min.js:70:279)
    at Jt (react-dom.production.min.js:69:102)
    at t.unstable_runWithPriority (scheduler.production.min.js:19:467)
    at Vr (react-dom.production.min.js:122:325)
    at O (react-dom.production.min.js:287:48)
    at Kt (react-dom.production.min.js:68:371)
(anonymous) @ actions.js:39
(anonymous) @ index.js:11
(anonymous) @ middleware.js:30
(anonymous) @ middleware.js:33
(anonymous) @ middleware.js:19
(anonymous) @ middleware.web.js:30
(anonymous) @ middleware.any.js:44
(anonymous) @ middleware.js:67
(anonymous) @ middleware.js:45
(anonymous) @ middleware.js:61
(anonymous) @ middleware.js:19
(anonymous) @ middleware.js:121
(anonymous) @ middleware.js:71
(anonymous) @ middleware.js:79
(anonymous) @ middleware.js:39
(anonymous) @ middleware.js:221
(anonymous) @ middleware.js:11
(anonymous) @ middleware.js:60
(anonymous) @ middleware.js:31
(anonymous) @ middleware.web.js:46
(anonymous) @ middleware.web.js:24
(anonymous) @ middleware.any.js:94
(anonymous) @ middleware.js:77
(anonymous) @ middleware.web.js:34
(anonymous) @ middleware.js:32
(anonymous) @ middleware.js:25
(anonymous) @ middleware.js:16
(anonymous) @ middleware.js:21
(anonymous) @ middleware.js:23
(anonymous) @ middleware.js:20
(anonymous) @ middleware.js:167
(anonymous) @ middleware.js:59
(anonymous) @ middleware.js:39
(anonymous) @ middleware.js:33
(anonymous) @ middleware.js:209
(anonymous) @ middleware.js:39
(anonymous) @ middleware.js:24
(anonymous) @ middleware.js:28
(anonymous) @ middleware.web.js:20
(anonymous) @ middleware.js:42
(anonymous) @ middleware.js:208
(anonymous) @ middleware.js:21
(anonymous) @ middleware.js:130
(anonymous) @ middleware.js:44
(anonymous) @ middleware.js:49
(anonymous) @ middleware.js:90
(anonymous) @ middleware.js:12
(anonymous) @ middleware.js:39
(anonymous) @ middleware.js:35
(anonymous) @ middleware.web.js:30
(anonymous) @ middleware.any.js:105
(anonymous) @ middleware.js:203
(anonymous) @ middleware.js:106
(anonymous) @ middleware.js:29
(anonymous) @ middleware.js:27
(anonymous) @ middleware.js:23
(anonymous) @ middleware.web.js:11
(anonymous) @ middleware.any.js:78
(anonymous) @ middleware.js:16
(anonymous) @ middleware.js:91
(anonymous) @ middleware.js:75
(anonymous) @ middleware.js:24
(anonymous) @ middleware.js:20
(anonymous) @ middleware.js:15
(anonymous) @ middleware.js:101
(anonymous) @ middleware.js:23
(anonymous) @ middleware.js:21
(anonymous) @ middleware.js:25
(anonymous) @ middleware.js:76
(anonymous) @ middleware.js:236
(anonymous) @ middleware.web.js:26
(anonymous) @ middleware.js:201
(anonymous) @ middleware.js:38
(anonymous) @ middleware.web.js:107
_toggleScreenshotCapture @ StopRecordingDialog.js:49
_onSubmit @ AbstractStopRecordingDialog.js:75
_onSubmit @ AbstractDialog.js:117
_onSubmit @ StatelessDialog.js:286
(anonymous) @ usePlatformLeafEventHandler.js:60
s @ react-dom.production.min.js:14
h @ react-dom.production.min.js:14
(anonymous) @ react-dom.production.min.js:14
b @ react-dom.production.min.js:15
it @ react-dom.production.min.js:52
at @ react-dom.production.min.js:51
ot @ react-dom.production.min.js:52
pt @ react-dom.production.min.js:56
z @ react-dom.production.min.js:287
B @ react-dom.production.min.js:19
Zt @ react-dom.production.min.js:70
Jt @ react-dom.production.min.js:69
t.unstable_runWithPriority @ scheduler.production.min.js:19
Vr @ react-dom.production.min.js:122
O @ react-dom.production.min.js:287
Kt @ react-dom.production.min.js:68
Show 65 more frames
Logger.js:154 2022-01-19T11:24:44.683Z [modules/xmpp/JingleSessionPC.js] <br.removeRemoteStreamsOnLeave>:  JingleSessionPC[session=JVB,initiator=false,sid=f0nsvi6rj832g] Queued removeRemoteStreamsOnLeave task for participant a246d57b
Logger.js:154 2022-01-19T11:24:44.687Z [modules/e2ee/OlmAdapter.js] <$i._onParticipantLeft>:  Participant a246d57b left
Logger.js:154 2022-01-19T11:24:44.691Z [JitsiConference.js] <jc._shouldBeInP2PMode>:  P2P? peerCount: 0, hasBotPeer: false => false
Logger.js:154 2022-01-19T11:24:44.699Z [modules/xmpp/JingleSessionPC.js] <Object.callback>:  JingleSessionPC[session=JVB,initiator=false,sid=f0nsvi6rj832g] removeRemoteStreamsOnLeave done!
Logger.js:154 2022-01-19T11:25:04.771Z [modules/RTC/BridgeChannel.js] <WebSocket.e.onclose>:  Channel closed by server
react_devtools_backend.js:4045 2022-01-19T11:25:04.771Z [modules/RTC/BridgeChannel.js] <WebSocket.e.onclose>:  Channel closed: 1006 
overrideMethod @ react_devtools_backend.js:4045
r @ Logger.js:154
e.onclose @ BridgeChannel.js:399
Logger.js:154 2022-01-19T11:25:04.775Z [modules/xmpp/strophe.jingle.js] <Rr.onJingle>:  terminating... f0nsvi6rj832g
Logger.js:154 2022-01-19T11:25:04.778Z [modules/xmpp/strophe.jingle.js] <Rr.onJingle>:  Received session-terminate from spokenvideosinterferebriskly@conference.meet.jit.si/focus disconnect reason=Idle session timeout
Logger.js:154 2022-01-19T11:25:04.779Z [modules/xmpp/JingleSessionPC.js] <br.onTerminated>:  JingleSessionPC[session=JVB,initiator=false,sid=f0nsvi6rj832g] Session terminated expired Idle session timeout
Logger.js:154 2022-01-19T11:25:04.780Z [modules/xmpp/JingleSessionPC.js] <br.close>:  JingleSessionPC[session=JVB,initiator=false,sid=f0nsvi6rj832g] Clearing modificationQueue
Logger.js:154 2022-01-19T11:25:04.781Z [modules/xmpp/JingleSessionPC.js] <br.close>:  JingleSessionPC[session=JVB,initiator=false,sid=f0nsvi6rj832g] Queued PC close task
Logger.js:154 2022-01-19T11:25:04.782Z [modules/xmpp/JingleSessionPC.js] <br.close>:  JingleSessionPC[session=JVB,initiator=false,sid=f0nsvi6rj832g] Shutdown modificationQueue!
Logger.js:154 2022-01-19T11:25:04.783Z [JitsiConference.js] <jc.onCallEnded>:  Call ended: expired - Idle session timeout P2P ?false
Logger.js:154 2022-01-19T11:25:04.784Z [JitsiConference.js] <jc.onCallEnded>:  Stopping JVB CallStats
Logger.js:154 2022-01-19T11:25:04.825Z [modules/RTC/TraceablePeerConnection.js] <ha.close>:  TPC[id=1,type=JVB] Closing peerconnection
Logger.js:154 2022-01-19T11:25:04.831Z [modules/xmpp/JingleSessionPC.js] JingleSessionPC[session=JVB,initiator=false,sid=f0nsvi6rj832g] PC close task done!

```

**Comment by saghul** [comment]
Can you reproduce this with the latest stable release?

**Comment by ashiqhassan95** [comment]
> Can you reproduce this with the latest stable release?

Sure. I will update soon
