### ISSUE TITLE
Etherpad not open in breakoutroom

### ISSUE THREAD

**Issue by aancelFR** [jitsi/jitsi-meet#10866]
### Description:
In the latest stable version (2.0.6826), the fileshare with etherpad  in breakoutroom not work

### Steps to reproduce:
- Open a room.
- Open sharefile
- switch in breakoutroom
- test to open share file (not work)
- return in main room
- test to open share file (not work)

### Expected behavior:

File share open and close correctly in breakoutroom and main room

### Actual behavior:

In the first openning etherpad work, after etherpad launch error:

```
LargeVideoManager.js:567 Uncaught Error: container of type etherpad doesn't exist
    at see.getContainer (LargeVideoManager.js:567:19)
    at see.getCurrentContainer (LargeVideoManager.js:582:21)
    at see.onHoverIn (LargeVideoManager.js:155:32)
    at HTMLDivElement.<anonymous> (LargeVideoManager.js:117:23)
    at HTMLDivElement.handle (jquery.js:5909:1)
    at HTMLDivElement.dispatch (jquery.js:5429:1)
    at HTMLDivElement.g.handle (jquery.js:5233:1)
```

```
Logger.js:154 2022-01-27T14:53:52.943Z [JitsiMeetJS.js] <Object.getGlobalOnErrorHandler>:  UnhandledError: Uncaught Error: container of type etherpad doesn't exist Script: https://x.x.io/libs/app.bundle.min.js?v=5764 Line: 138 Column: 473200 StackTrace:  Error: container of type etherpad doesn't exist
    at see.getContainer (https://x.x.io/libs/app.bundle.min.js?v=5764:138:473200)
    at see.getCurrentContainer (https://x.x.io/libs/app.bundle.min.js?v=5764:138:473293)
    at see.onHoverIn (https://x.x.io/libs/app.bundle.min.js?v=5764:138:469142)
    at HTMLDivElement.<anonymous> (https://x.x.io/libs/app.bundle.min.js?v=5764:138:468627)
    at HTMLDivElement.handle (https://x.x.io/libs/app.bundle.min.js?v=5764:138:2619694)
    at HTMLDivElement.dispatch (https://x.x.io/libs/app.bundle.min.js?v=5764:138:2616120)
    at HTMLDivElement.g.handle (https://x.x.io/libs/app.bundle.min.js?v=5764:138:2614115)
```

```
Logger.js:154 2022-01-27T14:53:52.561Z [JitsiMeetJS.js] <Object.getGlobalOnErrorHandler>:  UnhandledError: Cannot read properties of undefined (reading 'hide') Script: null Line: null Column: null StackTrace:  TypeError: Cannot read properties of undefined (reading 'hide')
    at see.showContainer (https://x.x.io/libs/app.bundle.min.js?v=5764:138:473687)
    at Object.showLargeVideoContainer (https://x.x.io/libs/app.bundle.min.js?v=5764:138:476483)
    at ene.toggleEtherpad (https://x.x.io/libs/app.bundle.min.js?v=5764:138:578368)
    at i.<anonymous> (https://x.x.io/libs/app.bundle.min.js?v=5764:138:579009)
    at i.emit (https://x.x.io/libs/app.bundle.min.js?v=5764:138:1055998)
    at Object.nne.emitEvent (https://x.x.io/libs/app.bundle.min.js?v=5764:138:581486)
    at https://x.x.io/libs/app.bundle.min.js?v=5764:138:663721
```

### Server information:

- Jitsi Meet version: 2.0.6826
- Operating System: Docker :)

### Client information:

- Browser / app version: Last Chrome version
- Operating System: Windows 10

**Comment by saghul** [comment]
Thanks for the report and the tracebacks.

**Comment by saghul** [comment]
.

**Comment by luzpaz** [comment]
@aancelFR can you still reproduce ?

**Comment by saghul** [comment]
THis is foxed, we no longer bubble events into the etherpad frame.
