### ISSUE TITLE
Jitsi meeting crashes as soon as a second user joins in

### ISSUE THREAD

**Issue by ibveecnk** [jitsi/jitsi-meet#10903]
### Description:

When I start a meeting, everything is running fine but as soon as another peer joins in, both sessions disconnect and try to reconnect.

### Steps to reproduce:

1. open jitsi on two seperate tabs/devices
2. create a new conference room on one device
3. join the room on the second device

The meeting should go on with two participants.

### Actual behavior:

The session crashes. 

### Server information:

- Jitsi Meet version: 2.0.6865-2
- Operating System: Debian 4.19.208-1 (2021-09-29) x86_64 GNU/Linux

### Client information:

- Browser / app version: Chrome, Brave, Firefox
- Operating System: Mac, Linux, Android

### Additional information:

jvb.log
```
Caused by: sun.security.validator.ValidatorException: PKIX path validation failed: java.security.cert.CertPathValidatorException: signature check failed
	at java.base/sun.security.validator.PKIXValidator.doValidate(PKIXValidator.java:369)
	at java.base/sun.security.validator.PKIXValidator.engineValidate(PKIXValidator.java:275)
	at java.base/sun.security.validator.Validator.validate(Validator.java:264)
	at java.base/sun.security.ssl.X509TrustManagerImpl.validate(X509TrustManagerImpl.java:313)
	at java.base/sun.security.ssl.X509TrustManagerImpl.checkTrusted(X509TrustManagerImpl.java:222)
	at java.base/sun.security.ssl.X509TrustManagerImpl.checkServerTrusted(X509TrustManagerImpl.java:129)
	at java.base/sun.security.ssl.CertificateMessage$T13CertificateConsumer.checkServerCerts(CertificateMessage.java:1341)
	... 17 more
Caused by: java.security.cert.CertPathValidatorException: signature check failed
	at java.base/sun.security.provider.certpath.PKIXMasterCertPathValidator.validate(PKIXMasterCertPathValidator.java:135)
	at java.base/sun.security.provider.certpath.PKIXCertPathValidator.validate(PKIXCertPathValidator.java:224)
	at java.base/sun.security.provider.certpath.PKIXCertPathValidator.validate(PKIXCertPathValidator.java:144)
	at java.base/sun.security.provider.certpath.PKIXCertPathValidator.engineValidate(PKIXCertPathValidator.java:83)
	at java.base/java.security.cert.CertPathValidator.validate(CertPathValidator.java:309)
	at java.base/sun.security.validator.PKIXValidator.doValidate(PKIXValidator.java:364)
	... 23 more
Caused by: java.security.SignatureException: Signature does not match.
	at java.base/sun.security.x509.X509CertImpl.verify(X509CertImpl.java:422)
	at java.base/sun.security.provider.certpath.BasicChecker.verifySignature(BasicChecker.java:166)
	at java.base/sun.security.provider.certpath.BasicChecker.check(BasicChecker.java:147)
	at java.base/sun.security.provider.certpath.PKIXMasterCertPathValidator.validate(PKIXMasterCertPathValidator.java:125)
	... 28 more
JVB 2022-02-03 11:22:16.663 WARNING: [528] [hostname=localhost id=shard] MucClient$2.connectionClosedOnError#323: Closed on error:
javax.net.ssl.SSLHandshakeException: PKIX path validation failed: java.security.cert.CertPathValidatorException: signature check failed
	at java.base/sun.security.ssl.Alert.createSSLException(Alert.java:131)
	at java.base/sun.security.ssl.TransportContext.fatal(TransportContext.java:352)
	at java.base/sun.security.ssl.TransportContext.fatal(TransportContext.java:295)
	at java.base/sun.security.ssl.TransportContext.fatal(TransportContext.java:290)
	at java.base/sun.security.ssl.CertificateMessage$T13CertificateConsumer.checkServerCerts(CertificateMessage.java:1357)
	at java.base/sun.security.ssl.CertificateMessage$T13CertificateConsumer.onConsumeCertificate(CertificateMessage.java:1232)
	at java.base/sun.security.ssl.CertificateMessage$T13CertificateConsumer.consume(CertificateMessage.java:1175)
	at java.base/sun.security.ssl.SSLHandshake.consume(SSLHandshake.java:392)
	at java.base/sun.security.ssl.HandshakeContext.dispatch(HandshakeContext.java:443)
	at java.base/sun.security.ssl.HandshakeContext.dispatch(HandshakeContext.java:421)
	at java.base/sun.security.ssl.TransportContext.dispatch(TransportContext.java:182)
	at java.base/sun.security.ssl.SSLTransport.decode(SSLTransport.java:172)
	at java.base/sun.security.ssl.SSLSocketImpl.decode(SSLSocketImpl.java:1501)
	at java.base/sun.security.ssl.SSLSocketImpl.readHandshakeRecord(SSLSocketImpl.java:1411)
	at java.base/sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:451)
	at java.base/sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:422)
	at org.jivesoftware.smack.tcp.XMPPTCPConnection.proceedTLSReceived(XMPPTCPConnection.java:730)
	at org.jivesoftware.smack.tcp.XMPPTCPConnection.access$1400(XMPPTCPConnection.java:130)
	at org.jivesoftware.smack.tcp.XMPPTCPConnection$PacketReader.parsePackets(XMPPTCPConnection.java:987)
	at org.jivesoftware.smack.tcp.XMPPTCPConnection$PacketReader.access$700(XMPPTCPConnection.java:913)
	at org.jivesoftware.smack.tcp.XMPPTCPConnection$PacketReader$1.run(XMPPTCPConnection.java:936)
	at java.base/java.lang.Thread.run(Thread.java:829)
Caused by: sun.security.validator.ValidatorException: PKIX path validation failed: java.security.cert.CertPathValidatorException: signature check failed
	at java.base/sun.security.validator.PKIXValidator.doValidate(PKIXValidator.java:369)
	at java.base/sun.security.validator.PKIXValidator.engineValidate(PKIXValidator.java:275)
	at java.base/sun.security.validator.Validator.validate(Validator.java:264)
	at java.base/sun.security.ssl.X509TrustManagerImpl.validate(X509TrustManagerImpl.java:313)
	at java.base/sun.security.ssl.X509TrustManagerImpl.checkTrusted(X509TrustManagerImpl.java:222)
	at java.base/sun.security.ssl.X509TrustManagerImpl.checkServerTrusted(X509TrustManagerImpl.java:129)
	at java.base/sun.security.ssl.CertificateMessage$T13CertificateConsumer.checkServerCerts(CertificateMessage.java:1341)
	... 17 more
Caused by: java.security.cert.CertPathValidatorException: signature check failed
	at java.base/sun.security.provider.certpath.PKIXMasterCertPathValidator.validate(PKIXMasterCertPathValidator.java:135)
	at java.base/sun.security.provider.certpath.PKIXCertPathValidator.validate(PKIXCertPathValidator.java:224)
	at java.base/sun.security.provider.certpath.PKIXCertPathValidator.validate(PKIXCertPathValidator.java:144)
	at java.base/sun.security.provider.certpath.PKIXCertPathValidator.engineValidate(PKIXCertPathValidator.java:83)
	at java.base/java.security.cert.CertPathValidator.validate(CertPathValidator.java:309)
	at java.base/sun.security.validator.PKIXValidator.doValidate(PKIXValidator.java:364)
	... 23 more
Caused by: java.security.SignatureException: Signature does not match.
	at java.base/sun.security.x509.X509CertImpl.verify(X509CertImpl.java:422)
	at java.base/sun.security.provider.certpath.BasicChecker.verifySignature(BasicChecker.java:166)
	at java.base/sun.security.provider.certpath.BasicChecker.check(BasicChecker.java:147)
	at java.base/sun.security.provider.certpath.PKIXMasterCertPathValidator.validate(PKIXMasterCertPathValidator.java:125)
	... 28 more
```

jicofo.log
```
Jicofo 2022-02-03 11:15:46.830 INFO: [41] [room=test@conference.meet.ivbeck.de meeting_id=9a503645-f2b3-40a1-adc5-3b074f9d3761] JitsiMeetConferenceImpl.rescheduleSingleParticipantTimeout#1869: Scheduled single person timeout.
Jicofo 2022-02-03 11:15:46.891 INFO: [41] [room=test@conference.meet.ivbeck.de meeting_id=9a503645-f2b3-40a1-adc5-3b074f9d3761] JitsiMeetConferenceImpl.onMemberLeft#795: Member left:dd39b7cc
Jicofo 2022-02-03 11:15:46.891 INFO: [41] [room=test@conference.meet.ivbeck.de meeting_id=9a503645-f2b3-40a1-adc5-3b074f9d3761] JitsiMeetConferenceImpl.terminateParticipant#837: Terminating dd39b7cc, reason: gone, send session-terminate: false
Jicofo 2022-02-03 11:15:46.891 INFO: [41] [room=test@conference.meet.ivbeck.de meeting_id=9a503645-f2b3-40a1-adc5-3b074f9d3761] JitsiMeetConferenceImpl.terminateParticipant#860: Removed participant dd39b7cc removed=true
Jicofo 2022-02-03 11:15:46.892 INFO: [41] [room=test@conference.meet.ivbeck.de meeting_id=9a503645-f2b3-40a1-adc5-3b074f9d3761] JitsiMeetConferenceImpl.stop#436: Stopped.
Jicofo 2022-02-03 11:16:11.055 INFO: [44] ConferenceIqHandler.handleConferenceIq#63: Focus request for room: test@conference.meet.ivbeck.de
Jicofo 2022-02-03 11:16:11.056 INFO: [44] [room=test@conference.meet.ivbeck.de] JitsiMeetConferenceImpl.<init>#275: Created new conference.
Jicofo 2022-02-03 11:16:11.056 INFO: [44] [room=test@conference.meet.ivbeck.de] JitsiMeetConferenceImpl.joinTheRoom#459: Joining test@conference.meet.ivbeck.de
Jicofo 2022-02-03 11:16:11.244 INFO: [46] [room=test@conference.meet.ivbeck.de meeting_id=381caf5f-1cf0-4e0c-ae51-7c8a8b2ae71e] JitsiMeetConferenceImpl.onMemberJoined#609: Member joined:f3049d3b
Jicofo 2022-02-03 11:16:11.245 INFO: [46] AutoOwnerRoleManager.electNewOwner#106: Electing new owner: ChatMember[test@conference.meet.ivbeck.de/f3049d3b, jid: null]@1707437725
```

**Comment by ibveecnk** [comment]
I have found what my mistake was. I forgot to add the record for my server ip to /etc/hosts. Now everything is working fine.
