### ISSUE TITLE
SoLoader: couldn't find DSO to load: libjsc.so 

### ISSUE THREAD

**Issue by hafiz013** [jitsi/jitsi-meet#10978]
1. Init meeting
2. crash appear

### Expected behavior:

can call
 

- Jitsi Meet version: 4.`1.0
- Operating System: android 11, 12

SoLoader: couldn't find DSO to load: libjsc.so caused by: dlopen failed: cannot locate symbol "__cxa_bad_typeid" referenced by "/data/data/com.nibmeetings.android/lib-main/libjsc.so"... result: 0
2022-02-17 19:06:26.850 29242-29425/com.nibmeetings.android E/SoLoader: couldn't find DSO to load: libjscexecutor.so caused by: couldn't find DSO to load: libjsc.so caused by: dlopen failed: cannot locate symbol "__cxa_bad_typeid" referenced by "/data/data/com.nibmeetings.android/lib-main/libjsc.so"... result: 0 result: 0
2022-02-17 19:06:26.854 29242-29425/com.nibmeetings.android E/AndroidRuntime: FATAL EXCEPTION: create_react_context
    Process: com.nibmeetings.android, PID: 29242
    java.lang.UnsatisfiedLinkError: couldn't find DSO to load: libjscexecutor.so caused by: couldn't find DSO to load: libjsc.so caused by: dlopen failed: cannot locate symbol "__cxa_bad_typeid" referenced by "/data/data/com.nibmeetings.android/lib-main/libjsc.so"... result: 0 result: 0
        at com.facebook.soloader.SoLoader.doLoadLibraryBySoName(SoLoader.java:896)
        at com.facebook.soloader.SoLoader.loadLibraryBySoNameImpl(SoLoader.java:725)
        at com.facebook.soloader.SoLoader.loadLibraryBySoName(SoLoader.java:649)
        at com.facebook.soloader.SoLoader.loadLibrary(SoLoader.java:629)
        at com.facebook.soloader.SoLoader.loadLibrary(SoLoader.java:577)
        at com.facebook.react.jscexecutor.JSCExecutor.<clinit>(JSCExecutor.java:18)
        at com.facebook.react.jscexecutor.JSCExecutorFactory.create(JSCExecutorFactory.java:29)
        at com.facebook.react.ReactInstanceManager$5.run(ReactInstanceManager.java:952)
        at java.lang.Thread.run(Thread.java:923)
2022-02-17 19:06:26.855 29242-29425/com.nibmeetings.android E/JitsiMeetLogger: JitsiMeetUncaughtExceptionHandler FATAL ERROR
    java.lang.UnsatisfiedLinkError: couldn't find DSO to load: libjscexecutor.so caused by: couldn't find DSO to load: libjsc.so caused by: dlopen failed: cannot locate symbol "__cxa_bad_typeid" referenced by "/data/data/com.nibmeetings.android/lib-main/libjsc.so"... result: 0 result: 0
        at com.facebook.soloader.SoLoader.doLoadLibraryBySoName(SoLoader.java:896)
        at com.facebook.soloader.SoLoader.loadLibraryBySoNameImpl(SoLoader.java:725)
        at com.facebook.soloader.SoLoader.loadLibraryBySoName(SoLoader.java:649)
        at com.facebook.soloader.SoLoader.loadLibrary(SoLoader.java:629)
        at com.facebook.soloader.SoLoader.loadLibrary(SoLoader.java:577)
        at com.facebook.react.jscexecutor.JSCExecutor.<clinit>(JSCExecutor.java:18)
        at com.facebook.react.jscexecutor.JSCExecutorFactory.create(JSCExecutorFactory.java:29)
        at com.facebook.react.ReactInstanceManager$5.run(ReactInstanceManager.java:952)
        at java.lang.Thread.run(Thread.java:923)
2022-02-17 19:06:26.855 29242-29425/com.nibmeetings.android E/JitsiMeetSDK: JitsiMeetUncaughtExceptionHandler FATAL ERROR
    java.lang.UnsatisfiedLinkError: couldn't find DSO to load: libjscexecutor.so caused by: couldn't find DSO to load: libjsc.so caused by: dlopen failed: cannot locate symbol "__cxa_bad_typeid" referenced by "/data/data/com.nibmeetings.android/lib-main/libjsc.so"... result: 0 result: 0
        at com.facebook.soloader.SoLoader.doLoadLibraryBySoName(SoLoader.java:896)
        at com.facebook.soloader.SoLoader.loadLibraryBySoNameImpl(SoLoader.java:725)
        at com.facebook.soloader.SoLoader.loadLibraryBySoName(SoLoader.java:649)
        at com.facebook.soloader.SoLoader.loadLibrary(SoLoader.java:629)
        at com.facebook.soloader.SoLoader.loadLibrary(SoLoader.java:577)
        at com.facebook.react.jscexecutor.JSCExecutor.<clinit>(JSCExecutor.java:18)
        at com.facebook.react.jscexecutor.JSCExecutorFactory.create(JSCExecutorFactory.java:29)
        at com.facebook.react.ReactInstanceManager$5.run(ReactInstanceManager.java:952)
        at java.lang.Thread.run(Thread.java:923)
    
    java.lang.UnsatisfiedLinkError: couldn't find DSO to load: libjscexecutor.so caused by: couldn't find DSO to load: libjsc.so caused by: dlopen failed: cannot locate symbol "__cxa_bad_typeid" referenced by "/data/data/com.nibmeetings.android/lib-main/libjsc.so"... result: 0 result: 0
        at com.facebook.soloader.SoLoader.doLoadLibraryBySoName(SoLoader.java:896)
        at com.facebook.soloader.SoLoader.loadLibraryBySoNameImpl(SoLoader.java:725)
        at com.facebook.soloader.SoLoader.loadLibraryBySoName(SoLoader.java:649)
        at com.facebook.soloader.SoLoader.loadLibrary(SoLoader.java:629)
        at com.facebook.soloader.SoLoader.loadLibrary(SoLoader.java:577)
        at com.facebook.react.jscexecutor.JSCExecutor.<clinit>(JSCExecutor.java:18)
        at com.facebook.react.jscexecutor.JSCExecutorFactory.create(JSCExecutorFactory.java:29)
        at com.facebook.react.ReactInstanceManager$5.run(ReactInstanceManager.java:952)
        at java.lang.Thread.run(Thread.java:923)

sample code:
android{
......
 packagingOptions {
        pickFirst '**/armeabi-v7a/libc++_shared.so'
        pickFirst '**/x86/libc++_shared.so'
        pickFirst '**/arm64-v8a/libc++_shared.so'
        pickFirst '**/x86_64/libc++_shared.so'
        pickFirst '**/x86/libjsc.so'
        pickFirst '**/armeabi-v7a/libjsc.so'
    }
}

dependencies {
-----
implementation ('org.jitsi.react:jitsi-meet-sdk:4.1.0') { transitive = true }  //jitsi
implementation project(':commonlib') // zoom
    implementation project(':mobilertc') //zoom
}

buildscript {
    ext.kotlin_version = '1.5.30'
    ext.kotlin_coroutines_version = "1.3.9"
    ext {
        archLifecycleVersion = '2.2.0'
        coreTestingVersion = '2.1.0'
        roomVersion = '2.2.1'
    }
    repositories {
        google()
        jcenter()
        mavenCentral()
        maven {
            url "https://plugins.gradle.org/m2/"
        }
        maven { url 'https://oss.sonatype.org/content/repositories/snapshots/' }

    }
    dependencies {
        classpath 'com.android.tools.build:gradle:4.2.2'
        classpath 'org.jetbrains.kotlin:kotlin-gradle-plugin:1.5.31'
        classpath "org.jetbrains.kotlin:kotlin-serialization:$kotlin_version"
        classpath 'com.google.gms:google-services:4.3.10'
        classpath 'com.amazonaws:aws-android-sdk-appsync-gradle-plugin:3.2.0'
//        classpath 'com.apollographql.apollo3:apollo-gradle-plugin:3.0.0-dev13'
        classpath 'com.google.firebase:firebase-crashlytics-gradle:2.8.1'
       // classpath "org.jetbrains.kotlin:kotlin-gradle-plugin:1.3.61"
        // NOTE: Do not place your application dependencies here; they belong
        // in the individual module build.gradle files

        classpath 'com.github.dcendents:android-maven-gradle-plugin:2.1'
    }
}
//build
allprojects {
    repositories {
        google()
        jcenter()
        maven {
            url "https://github.com/jitsi/jitsi-maven-repository/raw/master/releases"
        }
        maven { url 'https://oss.sonatype.org/content/repositories/snapshots/' }
        maven { url 'https://github.com/leonardocardoso/mvn-repo/raw/master/maven-deploy' }
        maven { url 'https://jitpack.io' }
        /*maven {
            // This is necessary for now, will be removed soon
            url "https://github.com/vector-im/jitsi_libre_maven/raw/master/android-sdk-2.9.3"
        }*/

        // For olm library.
        maven {
            url 'https://gitlab.matrix.org/api/v4/projects/27/packages/maven'
        }
    }
}

task clean(type: Delete) {
    delete rootProject.buildDir
}

**Comment by saghul** [comment]
You have 2 URLs which provide the Jitsi Meet SDK, the matrix one and ours. I'd suggest you start by picking one.

**Comment by hafiz013** [comment]
"sorry i don't understand". Which one should code?

**Comment by saghul** [comment]
You have the Jitsi maven repo and the Jitsi libre maven repo from matrix.

**Comment by hafiz013** [comment]
UnsatisfiedLinkError:  Thrown if the Java Virtual Machine cannot find an appropriate 
native-language definition of a method declared native. Seem like it couldn't find library or this method __cxa_bad_typeid . I have question why jitsi need facebook react native library?

**Comment by saghul** [comment]
Jitsi Meet is built with React Native, which is a library created by Facebook.

As for your issue, I have no idea sorry, I cannot reproduce it with our sample apps.
