### ISSUE TITLE
Android Crashes React Native Version 0.67.1

### ISSUE THREAD

**Issue by CharlieJ213** [jitsi/jitsi-meet#11053]
### Description:

Android Crashes React Native Version 0.67.1 with Fatal Exception. From looking at the stack trace it looks like an issue related to React-Native-Reanimated as well (as I have asked [here](https://github.com/software-mansion/react-native-reanimated/issues/604#issuecomment-1055435637))

### Steps to reproduce:

1. Create New React Native App
2. Install and integrate one of the React Native packages mentioned below ([bortolilucas/react-native-jitsimeet](https://github.com/bortolilucas/react-native-jitsimeet) uses latest version of Android Jitsi Meet SDK)
3. Run on Android device & check logcat

### Expected behavior:

New activity should launch and join Jitsi meeting

### Actual behavior:

Crashes with fatal exception (stack trace below)

### Server information:

https://meet.jit.si

### Client information:

- Jitsi Meet version: 4.1.0
- Operating System: Android (Tested on v9 actual device, v11 Pixel 5 simulator)
- React Native Version: 0.67.1
- React Native Package tested: [bortolilucas/react-native-jitsimeet](https://github.com/bortolilucas/react-native-jitsimeet) [skrafft/react-native-jitsi-meet](https://github.com/skrafft/react-native-jitsi-meet)

### Additional information:

```
E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.jitsitesting, PID: 8332
    java.lang.IncompatibleClassChangeError: Found interface com.facebook.react.uimanager.events.EventDispatcher, but class was expected (declaration of 'com.facebook.react.uimanager.events.EventDispatcher' appears in /data/app/~~W8jlH1sETpdxE6DCzcBEeQ==/com.jitsitesting-KiRtJu2u391XcJtskkaV8w==/base.apk!classes10.dex)
        at com.swmansion.reanimated.NodesManager.<init>(NodesManager.java:116)
        at com.swmansion.reanimated.ReanimatedModule.getNodesManager(ReanimatedModule.java:95)
        at com.swmansion.reanimated.ReanimatedModule.access$000(ReanimatedModule.java:24)
        at com.swmansion.reanimated.ReanimatedModule$1.execute(ReanimatedModule.java:80)
        at com.facebook.react.uimanager.UIViewOperationQueue$UIBlockOperation.execute(UIViewOperationQueue.java:579)
        at com.facebook.react.uimanager.UIViewOperationQueue$1.run(UIViewOperationQueue.java:915)
        at com.facebook.react.uimanager.UIViewOperationQueue.flushPendingBatches(UIViewOperationQueue.java:1026)
        at com.facebook.react.uimanager.UIViewOperationQueue.access$2600(UIViewOperationQueue.java:47)
        at com.facebook.react.uimanager.UIViewOperationQueue$DispatchUIFrameCallback.doFrameGuarded(UIViewOperationQueue.java:1086)
        at com.facebook.react.uimanager.GuardedFrameCallback.doFrame(GuardedFrameCallback.java:29)
        at com.facebook.react.modules.core.ReactChoreographer$ReactChoreographerDispatcher.doFrame(ReactChoreographer.java:175)
        at com.facebook.react.modules.core.ChoreographerCompat$FrameCallback$1.doFrame(ChoreographerCompat.java:85)
        at android.view.Choreographer$CallbackRecord.run(Choreographer.java:970)
        at android.view.Choreographer.doCallbacks(Choreographer.java:796)
        at android.view.Choreographer.doFrame(Choreographer.java:727)
        at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:957)
        at android.os.Handler.handleCallback(Handler.java:938)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:223)
        at android.app.ActivityThread.main(ActivityThread.java:7656)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)
E/JitsiMeetSDK: JitsiMeetUncaughtExceptionHandler FATAL ERROR
    java.lang.IncompatibleClassChangeError: Found interface com.facebook.react.uimanager.events.EventDispatcher, but class was expected (declaration of 'com.facebook.react.uimanager.events.EventDispatcher' appears in /data/app/~~W8jlH1sETpdxE6DCzcBEeQ==/com.jitsitesting-KiRtJu2u391XcJtskkaV8w==/base.apk!classes10.dex)
        at com.swmansion.reanimated.NodesManager.<init>(NodesManager.java:116)
        at com.swmansion.reanimated.ReanimatedModule.getNodesManager(ReanimatedModule.java:95)
        at com.swmansion.reanimated.ReanimatedModule.access$000(ReanimatedModule.java:24)
        at com.swmansion.reanimated.ReanimatedModule$1.execute(ReanimatedModule.java:80)
        at com.facebook.react.uimanager.UIViewOperationQueue$UIBlockOperation.execute(UIViewOperationQueue.java:579)
        at com.facebook.react.uimanager.UIViewOperationQueue$1.run(UIViewOperationQueue.java:915)
        at com.facebook.react.uimanager.UIViewOperationQueue.flushPendingBatches(UIViewOperationQueue.java:1026)
        at com.facebook.react.uimanager.UIViewOperationQueue.access$2600(UIViewOperationQueue.java:47)
        at com.facebook.react.uimanager.UIViewOperationQueue$DispatchUIFrameCallback.doFrameGuarded(UIViewOperationQueue.java:1086)
        at com.facebook.react.uimanager.GuardedFrameCallback.doFrame(GuardedFrameCallback.java:29)
        at com.facebook.react.modules.core.ReactChoreographer$ReactChoreographerDispatcher.doFrame(ReactChoreographer.java:175)
        at com.facebook.react.modules.core.ChoreographerCompat$FrameCallback$1.doFrame(ChoreographerCompat.java:85)
        at android.view.Choreographer$CallbackRecord.run(Choreographer.java:970)
        at android.view.Choreographer.doCallbacks(Choreographer.java:796)
        at android.view.Choreographer.doFrame(Choreographer.java:727)
        at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:957)
        at android.os.Handler.handleCallback(Handler.java:938)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:223)
        at android.app.ActivityThread.main(ActivityThread.java:7656)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)
    
    java.lang.IncompatibleClassChangeError: Found interface com.facebook.react.uimanager.events.EventDispatcher, but class was expected (declaration of 'com.facebook.react.uimanager.events.EventDispatcher' appears in /data/app/~~W8jlH1sETpdxE6DCzcBEeQ==/com.jitsitesting-KiRtJu2u391XcJtskkaV8w==/base.apk!classes10.dex)
        at com.swmansion.reanimated.NodesManager.<init>(NodesManager.java:116)
        at com.swmansion.reanimated.ReanimatedModule.getNodesManager(ReanimatedModule.java:95)
        at com.swmansion.reanimated.ReanimatedModule.access$000(ReanimatedModule.java:24)
        at com.swmansion.reanimated.ReanimatedModule$1.execute(ReanimatedModule.java:80)
        at com.facebook.react.uimanager.UIViewOperationQueue$UIBlockOperation.execute(UIViewOperationQueue.java:579)
        at com.facebook.react.uimanager.UIViewOperationQueue$1.run(UIViewOperationQueue.java:915)
        at com.facebook.react.uimanager.UIViewOperationQueue.flushPendingBatches(UIViewOperationQueue.java:1026)
        at com.facebook.react.uimanager.UIViewOperationQueue.access$2600(UIViewOperationQueue.java:47)
        at com.facebook.react.uimanager.UIViewOperationQueue$DispatchUIFrameCallback.doFrameGuarded(UIViewOperationQueue.java:1086)
        at com.facebook.react.uimanager.GuardedFrameCallback.doFrame(GuardedFrameCallback.java:29)
        at com.facebook.react.modules.core.ReactChoreographer$ReactChoreographerDispatcher.doFrame(ReactChoreographer.java:175)
        at com.facebook.react.modules.core.ChoreographerCompat$FrameCallback$1.doFrame(ChoreographerCompat.java:85)
        at android.view.Choreographer$CallbackRecord.run(Choreographer.java:970)
        at android.view.Choreographer.doCallbacks(Choreographer.java:796)
        at android.view.Choreographer.doFrame(Choreographer.java:727)
E/JitsiMeetSDK:     at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:957)
        at android.os.Handler.handleCallback(Handler.java:938)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:223)
        at android.app.ActivityThread.main(ActivityThread.java:7656)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)

```

**Comment by saghul** [comment]
We don't support RN versions other than the one the SDK itself depends on, sorry.

**Comment by saghul** [comment]
We are not the maintainers of react-native-jitsi-meet, please ask the maintainer.

**Comment by skumarcm** [comment]
The app works fine with jitsi-meet SDK 3.7.0.
The above error occurs when the SDK is upgraded to 4.1.0 for android.
I was wondering if there is anything that conflicts due to the use of BroadcastReceiver for event management.

**Comment by skumarcm** [comment]
The error is produced from react-native-reanimated package which was introduced into jitsi-meet from the tag 6689 (dec 2, 2021) onwards.
