### ISSUE TITLE
Audio/Video Connection lost status

### ISSUE THREAD

**Issue by beejuspal** [jitsi/jitsi-meet#11082]
I am getting this error. can anyone please help me?

2022-03-07T14:02:02.974Z [JitsiMeetJS.js] <Object.getGlobalOnErrorHandler>:  UnhandledError: null Script: null Line: null Column: null StackTrace:  DOMException: Failed to construct 'RTCPeerConnection': Plan B SDP semantics is a legacy version of the Session Description Protocol that has severe compatibility issues on modern browsers and is no longer supported. See https://www.chromestatus.com/feature/5823036655665152 for more details, including the possibility of registering for a Deprecation Trial in order to extend the Plan B deprecation deadline for a limited amount of time.

2022-03-07T14:02:02.977Z [JitsiMeetJS.js] <Object.getGlobalOnErrorHandler>:  UnhandledError: null Script: null Line: null Column: null StackTrace:  TypeError: Cannot read properties of undefined (reading 'id')
    at b.stopRemoteStats (statistics.js:408:31)
    at b.startRemoteStats (statistics.js:219:10)
    at re._acceptJvbIncomingCall (JitsiConference.js:1976:25)
    at re.onIncomingCall (JitsiConference.js:1886:14)
    at a.emit (events.js:153:5)
    at g.onJingle (strophe.jingle.js:171:31)
    at I.Handler.run (strophe.umd.js:1875:33)
    at strophe.umd.js:3157:35
    at Object.forEachChild (strophe.umd.js:830:21)
    at I.Connection._dataRecv (strophe.umd.js:3146:25)
    at O.Bosh._onRequestStateChange (strophe.umd.js:5012:19)

Logger.js:154 2022-03-07T14:02:02.978Z [JitsiConference.js] <re._acceptJvbIncomingCall>:  TypeError: Cannot read properties of undefined (reading 'id')
    at b.stopRemoteStats (statistics.js:408:31)
    at b.startRemoteStats (statistics.js:219:10)
    at re._acceptJvbIncomingCall (JitsiConference.js:1976:25)
    at re.onIncomingCall (JitsiConference.js:1886:14)
    at a.emit (events.js:153:5)
    at g.onJingle (strophe.jingle.js:171:31)
    at I.Handler.run (strophe.umd.js:1875:33)
    at strophe.umd.js:3157:35
    at Object.forEachChild (strophe.umd.js:830:21)
    at I.Connection._dataRecv (strophe.umd.js:3146:25)
    at O.Bosh._onRequestStateChange (strophe.umd.js:5012:19)

**Comment by damencho** [comment]
Please, when you have questions or problems use the community forum before opening new issues, thank you.

Which version of jitsi-meet do you use?

**Comment by beejuspal** [comment]
![Screenshot 2022-03-07 195442](https://user-images.githubusercontent.com/36005233/157050302-e4ff42b4-4fe7-4c92-a365-174984d944d1.png)

**Comment by damencho** [comment]
This is too old and does not support latest google chrome versions. You need to update jitsi-meet.

**Comment by damencho** [comment]
And then your only path going forward is updating.
