### ISSUE TITLE
Chrome users stuck when starting meeting with prejoin page enabled

### ISSUE THREAD

**Issue by Lineflyer** [jitsi/jitsi-meet#11126]
### Description:

I recently upgraded my dockerized Jitsi installation (running on a Synology NAS, which works great by the way) to the latest stable version. I do now have the problem, that Chrome users are kind of stuck will trying to join a meeting (Firefox works normal).

I am using the following (potenially) relevant custom options:
```
config.prejoinPageEnabled = true;
config.requireDisplayName = true;
```

While debugging I noticed, that the problem is gone once I disable the prejoin page. As soon as I disable the prejoin page it works for Chrome users as expected.

### Steps to reproduce:

1. Run jitsi server with the custom options mentioned above
2. Use Google Chrome to access the landing page
3. Type in desired meeting room name
4. Click "Start Meeting"

### Expected behavior:

Prejoin page should be shown allowing the user to enter his name and configure desired audio/video config and afterwards continue to the meeting room.

### Actual behavior:

For a split second the prejoin page is shown but then changes into a full screen own video with an (incomplete?) control panel shown below. Note e.g. the missing hangup button:
![image](https://user-images.githubusercontent.com/949669/158172092-0e00441d-97df-46d2-afc5-cc0a27e0955f.png)

In this state I am no participant of that meeting but just stuck in this state.

Once I deactivate the prejoin page (```config.prejoinPageEnabled = false;```) it works as expected in such case.
I enter the room, an overlay to enter the name is shown:
![image](https://user-images.githubusercontent.com/949669/158172453-76e480a2-f1ed-40e4-8ad7-dc41f2c1be6a.png)

Once I provided the name I am in the meeting and see the correct control panel:
![image](https://user-images.githubusercontent.com/949669/158172526-9facb0ec-6625-45ce-9d88-715afb04c936.png)

### Server information:

- Jitsi Meet version: 1.0.5913-1 (dockerized version: stable-7001)
- Operating System: Docker version on Synology NAS DS218+

### Client information:

- Browser / app version: Google Chrome Version 99.0.4844.51 (Offizieller Build) (64-Bit)
- Operating System: Windows 10

**Comment by Lineflyer** [comment]
That's what I see in my browser (after this split second of the prejoin page):
![image](https://user-images.githubusercontent.com/949669/158176184-a5b8c580-cb81-48aa-ba1f-9edf06d1f3c8.png)


The console shows this error:
```
Logger.js:154 2022-03-14T12:55:22.079Z [modules/xmpp/xmpp.js] <go._initStrophePlugins>:  P2P STUN servers:  [{…}]
Logger.js:154 2022-03-14T12:55:22.097Z [modules/xmpp/xmpp.js] <go.connectionHandler>:  (TIME) Strophe connecting:	 1721.0999999642372
Logger.js:154 2022-03-14T12:55:22.103Z [features/prejoin] Failed to execute pre call test -  Error: Callstats is disabled
    at Object.init (PrecallTest.js:85:15)
    at actions.js:314:43
    at index.js:11:18
    at middleware.js:30:12
    at middleware.js:33:20
    at middleware.js:19:20
    at middleware.web.js:29:20
    at middleware.any.js:44:20
    at middleware.js:67:12
    at middleware.js:45:12
    at middleware.js:61:12
    at middleware.js:20:20
    at middleware.js:121:12
    at middleware.js:71:12
    at middleware.js:79:20
    at middleware.js:39:12
    at middleware.js:221:12
    at middleware.js:11:20
    at middleware.js:77:12
    at middleware.js:31:20
    at middleware.web.js:46:12
    at middleware.web.js:24:12
    at middleware.any.js:94:20
    at middleware.js:77:12
    at middleware.web.js:38:20
    at middleware.js:32:12
    at middleware.js:25:12
    at middleware.js:16:20
    at middleware.js:21:12
    at middleware.js:23:12
    at middleware.js:20:20
    at middleware.js:167:12
    at middleware.js:16:16
    at middleware.js:39:20
    at middleware.js:33:12
    at middleware.js:209:12
    at middleware.js:39:12
    at middleware.js:24:12
    at middleware.js:28:20
    at middleware.web.js:20:20
    at middleware.js:42:20
    at middleware.js:227:12
    at middleware.js:21:20
    at middleware.js:130:12
    at middleware.js:44:12
    at middleware.js:49:12
    at middleware.js:90:20
    at middleware.js:12:20
    at middleware.js:39:12
    at middleware.js:35:12
    at middleware.web.js:30:12
    at middleware.any.js:105:12
    at middleware.js:203:12
    at middleware.js:106:20
    at middleware.js:29:16
    at middleware.js:27:12
    at middleware.js:23:20
    at middleware.web.js:11:20
    at middleware.any.js:78:12
    at middleware.js:16:20
    at middleware.js:91:12
    at middleware.js:75:12
    at middleware.js:24:20
    at middleware.js:20:12
    at middleware.js:15:20
    at middleware.js:188:12
    at middleware.js:23:20
    at middleware.js:21:20
    at middleware.js:25:12
    at middleware.js:76:20
    at middleware.js:236:12
    at middleware.web.js:26:12
    at middleware.js:201:12
    at middleware.js:38:12
    at Object.dispatch (middleware.web.js:124:12)
    at Object.init (conference.js:827:23)
```

In Firefox it looks as expected:
![image](https://user-images.githubusercontent.com/949669/158178005-22633816-144b-4e6c-9c0d-9da0e8fd5103.png)

**Comment by Lineflyer** [comment]
> That's very odd! Don't you have any more logs than those?

I will save a log from Chrome console, clean my personal data from it and provide it asap.
I am not so familiar with the console, so I just provide the raw data to you.

**Comment by Lineflyer** [comment]
I managed to do a screenshot of the join page which is shown for a split second. It looks kind of broken in Chrome.

![image](https://user-images.githubusercontent.com/949669/158180387-7876a455-3218-45dd-8987-22a9eacb6c87.png)

**Comment by Lineflyer** [comment]
Incognito shows same results.

But wait a bit please. It could be I messed up something in the CSS or interface-config.js.
Let me reset to a default config with just the prejoin page enabled to get a clear starting point for testing.

I don't potentially want to bother you with something I managed to break...will report back.

**Comment by Lineflyer** [comment]
I located the problem.
In fact one of my scripts copied a customized `all.css` to adjust coloring to my needs.
Seems the content of the CSS changed meanwhile, thus something was missing/wrong causing the window to break.

Using the default `all.css` everything shows up perfect.

Sorry for this. I should have checked that upfront.

BTW:
Ayn advise or best practice how to patch/customize colors of the landing page other than modify the `all.css`?
