### ISSUE TITLE
Failed to grant owner status: Bare JID expected, got full JID

### ISSUE THREAD

**Issue by denzill** [jitsi/jitsi-meet#11169]
### Description:
I install Jitsi-meet by this doc: https://jitsi.github.io/handbook/docs/devops-guide/devops-guide-quickstar.
Then enable authentication by this: https://jitsi.github.io/handbook/docs/devops-guide/secure-domain.
And now after create conference i get an error in jicofo.log:

`Jicofo 2022-03-18 16:13:23.094 SEVERE: [118] ChatRoomRoleManager.grantOwner#46: Failed to grant owner status to mpyze6sgt1f5rgcabavcgo5j@guest.jitsi.minsk.isida.by/JayE684PsEBe
java.lang.RuntimeException: Failed to grant owner: <iq xmlns='jabber:client' to='focus@auth.jitsi.minsk.isida.by/focus' from='crowdedphilosopherslistenresponsibly@conference.jitsi.minsk.isida.by' id='BQN8J-179' type='error'><error type='modify'><jid-malformed xmlns='urn:ietf:params:xml:ns:xmpp-stanzas'/><text xmlns='urn:ietf:params:xml:ns:xmpp-stanzas'>Bare JID expected, got full JID</text></error></iq>
	at org.jitsi.impl.protocol.xmpp.ChatRoomImpl.grantOwnership(ChatRoomImpl.java:482)
	at org.jitsi.jicofo.xmpp.muc.ChatRoomRoleManager.grantOwner(ChatRoomRoleManager.kt:43)
	at org.jitsi.jicofo.xmpp.muc.AuthenticationRoleManager.authenticationListener$lambda-2(ChatRoomRoleManager.kt:127)
	at org.jitsi.jicofo.auth.AbstractAuthAuthority.notifyUserAuthenticated(AbstractAuthAuthority.java:343)
	at org.jitsi.jicofo.auth.AbstractAuthAuthority.authenticateJidWithSession(AbstractAuthAuthority.java:433)
	at org.jitsi.jicofo.auth.XMPPDomainAuthAuthority.processAuthLocked(XMPPDomainAuthAuthority.java:100)
	at org.jitsi.jicofo.auth.AbstractAuthAuthority.processAuthentication(AbstractAuthAuthority.java:356)
	at org.jitsi.jicofo.xmpp.ConferenceIqHandler.processExtensions(ConferenceIqHandler.kt:118)
	at org.jitsi.jicofo.xmpp.ConferenceIqHandler.handleConferenceIq(ConferenceIqHandler.kt:67)
	at org.jitsi.jicofo.xmpp.ConferenceIqHandler.handleIQRequest$lambda-4(ConferenceIqHandler.kt:156)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)
`

### Expected behavior:
I need moderator rights in conference

### Server information:

- Jitsi Meet version: 0.12
- Operating System: Debian 11

### Client information:

- Browser / app version: Chrome Version 99.0.4844.51 (Official Build) (64-bit)
- Operating System: Ubuntu/Windows

**Comment by saghul** [comment]
Please downgrade to Prosody 0.11, we have not updated yet to 0.12.
