### ISSUE TITLE
jitsi-meet : failed to install under centos 6.x

### ISSUE THREAD

**Issue by jiangjianping** [jitsi/jitsi-meet#1127]
> git-validate@2.2.2 install /var/www/xmpp.myvmr.cn/node_modules/git-validate
> node bin/install

fs.js:640
  return binding.open(pathModule._makeLong(path), stringToFlags(flags), mode);
                 ^

Error: EACCES: permission denied, open '/var/www/xmpp.myvmr.cn/.git/hooks/pre-commit'
    at Error (native)
    at Object.fs.openSync (fs.js:640:18)
    at Object.fs.writeFileSync (fs.js:1333:33)
    at Object.exports.installHooks (/var/www/xmpp.myvmr.cn/node_modules/git-validate/lib/utils.js:248:12)
    at Object.<anonymous> (/var/www/xmpp.myvmr.cn/node_modules/git-validate/bin/install.js:3:7)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
npm WARN eslint-plugin-mocha@2.0.0 requires a peer of eslint@^2.0.0 but none was installed.
npm ERR! Linux 2.6.32-504.30.3.el6.x86_64
npm ERR! argv "/root/videobridge/node-v6.9.1-linux-x64/bin/node" "/usr/bin/npm" "install"
npm ERR! node v6.9.1
npm ERR! npm  v3.10.8
npm ERR! code ELIFECYCLE

npm ERR! git-validate@2.2.2 install: `node bin/install`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the git-validate@2.2.2 install script 'node bin/install'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the git-validate package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node bin/install
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs git-validate
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls git-validate
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /var/www/xmpp.myvmr.cn/npm-debug.log

**Comment by jiangjianping** [comment]
I change the permission of directory node_modules to 777, the problem disappeared
