### ISSUE TITLE
track.getSettings() is not implemented in React Native

### ISSUE THREAD

**Issue by vkiranmaniya** [jitsi/jitsi-meet#11295]
### Description:

I'm using the latest lib-jitsi-meet and getting the error given below. Looks like a compatibility issue. Same behavior in android and ios.
```
Error: Not implemented.
    at MediaStreamTrack.getSettings (MediaStreamTrack.js:106:11)
    at lib-jitsi-meet.min.js:2:573345
    at Array.map (<anonymous>)
    at Ia (lib-jitsi-meet.min.js:2:573236)
    at lib-jitsi-meet.min.js:2:574648
    at tryCallOne (core.js:37:12)
    at core.js:123:15
    at JSTimers.js:289:18
    at _callTimer (JSTimers.js:146:7)
    at _callImmediatesPass (JSTimers.js:194:7)
    at Object.callImmediates (JSTimers.js:458:12)
    at MessageQueue.__callImmediates (MessageQueue.js:407:12)
    at MessageQueue.js:143:12
    at MessageQueue.__guard (MessageQueue.js:384:9)
    at MessageQueue.flushedQueue (MessageQueue.js:142:10)
    at MessageQueue.invokeCallbackAndReturnFlushedQueue (MessageQueue.js:138:17)
    at debuggerWorker.js:69:58
```

### Steps to reproduce:

1. Build the app
2. Connect the debugger
3. Join the conference
4. Check console logs

**Comment by saghul** [comment]
You must be using an old version, this was implemented a while ago: https://github.com/react-native-webrtc/react-native-webrtc/blob/df266447e909f4162ba9e791586ed63e20654d30/src/MediaStreamTrack.ts#L97
