### ISSUE TITLE
Reanimated throw err app getting crashed while using latest

### ISSUE THREAD

**Issue by riyas145** [jitsi/jitsi-meet#11368]
2022-04-12 09:47:20.650 24577-24714/com.i2global E/AndroidRuntime: FATAL EXCEPTION: mqt_native_modules
    Process: com.i2global, PID: 24577
    com.facebook.react.bridge.NativeArgumentsParseException: RNGestureHandlerModule.attachGestureHandler got 3 arguments, expected 2
        at com.facebook.react.bridge.JavaMethodWrapper.invoke(JavaMethodWrapper.java:349)
        at com.facebook.react.bridge.JavaModuleWrapper.invoke(JavaModuleWrapper.java:188)
        at com.facebook.react.bridge.queue.NativeRunnable.run(Native Method)
        at android.os.Handler.handleCallback(Handler.java:938)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:27)
        at android.os.Looper.loop(Looper.java:236)
        at com.facebook.react.bridge.queue.MessageQueueThreadImpl$4.run(MessageQueueThreadImpl.java:226)
        at java.lang.Thread.run(Thread.java:923)
2022-04-12 09:47:20.653 24577-24714/com.i2global D/OOMEventManagerFK: checkEventAndDumpForJE: 0
2022-04-12 09:47:20.660 24577-24714/com.i2global E/JitsiMeetSDK: JitsiMeetUncaughtExceptionHandler FATAL ERROR
    com.facebook.react.bridge.NativeArgumentsParseException: RNGestureHandlerModule.attachGestureHandler got 3 arguments, expected 2
        at com.facebook.react.bridge.JavaMethodWrapper.invoke(JavaMethodWrapper.java:349)
        at com.facebook.react.bridge.JavaModuleWrapper.invoke(JavaModuleWrapper.java:188)
        at com.facebook.react.bridge.queue.NativeRunnable.run(Native Method)
        at android.os.Handler.handleCallback(Handler.java:938)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:27)
        at android.os.Looper.loop(Looper.java:236)
        at com.facebook.react.bridge.queue.MessageQueueThreadImpl$4.run(MessageQueueThreadImpl.java:226)
        at java.lang.Thread.run(Thread.java:923)
    
    com.facebook.react.bridge.NativeArgumentsParseException: RNGestureHandlerModule.attachGestureHandler got 3 arguments, expected 2
        at com.facebook.react.bridge.JavaMethodWrapper.invoke(JavaMethodWrapper.java:349)
        at com.facebook.react.bridge.JavaModuleWrapper.invoke(JavaModuleWrapper.java:188)
        at com.facebook.react.bridge.queue.NativeRunnable.run(Native Method)
        at android.os.Handler.handleCallback(Handler.java:938)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:27)
        at android.os.Looper.loop(Looper.java:236)
        at com.facebook.react.bridge.queue.MessageQueueThreadImpl$4.run(MessageQueueThreadImpl.java:226)
        at java.lang.Thread.run(Thread.java:923)
2022-04-12 09:47:20.690 24577-24714/com.i2global I/Process: Sending signal. PID: 24577 SIG: 9

**Comment by saghul** [comment]
Can you reproduce this reliably? What are the steps? Can you repro with Jitsi Meet?

**Comment by socialcode-rob1** [comment]
I can reproduce reliable...

package.json
```
...
 "dependencies": {
    "@bortolilucas/react-native-jitsimeet": "^2.1.2",  // tried with react-native-jitsi-meet as well
     ...
    "@react-native-community/masked-view": "0.1.11",
    "@react-navigation/drawer": "^5.x",
    "@react-navigation/native": "5.9.4",
    "@react-navigation/stack": "^5.x",
    "react": "16.13.1",
    "react-native": "0.63.4",
    "react-native-gesture-handler": "1.10.3",
    "react-native-reanimated": "1.13.1",
    "react-native-screens": "2.18.1",
    ...
  },
...
```

build.gradle
```
buildscript {
    ext {
        buildToolsVersion = "30.0.3"
        minSdkVersion = 24
        compileSdkVersion = 30
        targetSdkVersion = 30
        kotlinVersion = "1.3.72"
        ndkVersion = "21.4.7075529"
    }
...
```

**Comment by riyas145** [comment]
@socialcode-rob1 u also getting same issue ?

**Comment by socialcode-rob1** [comment]
@riyas145 looking closer to the error... I actually get the opposite..

`com.facebook.react.bridge.NativeArgumentsParseException: RNGestureHandlerModule.attachGestureHandler got 2 arguments, expected 3`

hopefully it provides some clues.
It looks like you may need to upgrade your `react-native-gesture-handler`.  v2+ has a different signature

**Comment by saghul** [comment]
> I can reproduce reliably...
> 
> 
> 
> package.json
> 
> ```json
> 
> ...
> 
>  "dependencies": {
> 
>     "@bortolilucas/react-native-jitsimeet": "^2.1.2",  // tried with react-native-jitsi-meet as well
> 
>      ...
> 
>     "@react-native-community/masked-view": "0.1.11",
> 
>     "@react-navigation/drawer": "^5.x",
> 
>     "@react-navigation/native": "5.9.4",
> 
>     "@react-navigation/stack": "^5.x",
> 
>     "react": "16.13.1",
> 
>     "react-native": "0.63.4",
> 
>     "react-native-gesture-handler": "1.10.3",
> 
>     "react-native-reanimated": "1.13.1",
> 
>     "react-native-screens": "2.18.1",
> 
>     ...
> 
>   },
> 
> ...
> 
> ```
> 
> 
> 
> build.gradle
> 
> ```
> 
> buildscript {
> 
>     ext {
> 
>         buildToolsVersion = "30.0.3"
> 
>         minSdkVersion = 24
> 
>         compileSdkVersion = 30
> 
>         targetSdkVersion = 30
> 
>         kotlinVersion = "1.3.72"
> 
>         ndkVersion = "21.4.7075529"
> 
>     }
> 
> ...
> 
> ```

We are not the maintainers of react-native-jitsimeet and don't support that effort. The SDK itself does not exhibit this issue.

**Comment by socialcode-rob1** [comment]
@saghul I didn't open the bug.  I don't think you should close based on my response.
you may want to follow up with @riyas145
