### ISSUE TITLE
DNS lookup exception for {{ .env.xmpp_server }}

### ISSUE THREAD

**Issue by sathish36** [jitsi/jitsi-meet#11456]
### Description:

while running jitsi in K8s JVB is throwing this error for DNS lookup

org.jivesoftware.smack.SmackException$EndpointConnectionException: Could not lookup the following endpoints: RemoteConnectionEndpointLookupFailure(description='DNS lookup exception for {{ .env.xmpp_server }}' exception='java.net.UnknownHostException: {{ .env.xmpp_server }}: Name or service not known')
	at org.jivesoftware.smack.SmackException$EndpointConnectionException.from(SmackException.java:334)
	at org.jivesoftware.smack.tcp.XMPPTCPConnection.connectUsingConfiguration(XMPPTCPConnection.java:663)
	at org.jivesoftware.smack.tcp.XMPPTCPConnection.connectInternal(XMPPTCPConnection.java:846)
	at org.jivesoftware.smack.AbstractXMPPConnection.connect(AbstractXMPPConnection.java:529)
	at org.jitsi.xmpp.mucclient.MucClient.lambda$getConnectAndLoginCallable$7(MucClient.java:613)
	at org.jitsi.retry.RetryStrategy$TaskRunner.run(RetryStrategy.java:167)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)

XMPP_SERVER was set to `localhost` in environment variables. This is happing for the latest stable version stable-7210-2, and I tried it on stable-6826 (which was mentioned in jitsi-kuberneties repo), same issue in all of these versions.

**Comment by saghul** [comment]
> XMPP_SERVER was set to `localhost` in environment variables.

That's your answer. Set it to a correct value.

**Comment by sathish36** [comment]
all containers are deployed in single pod setup. so we are using localhost for it. this was working for version stable-5963 with XMPP_SERVER=localhost

**Comment by saghul** [comment]
I am not familiar enough to comment oon a k8s setup. Please ask here: https://github.com/jitsi-contrib/jitsi-kubernetes
