### ISSUE TITLE
Error when opening jitsi sdk

### ISSUE THREAD

**Issue by ldm0330** [jitsi/jitsi-meet#11540]
The following error occurred when opening jitsi sdk, I checked that the file exists

2022-05-16 17:48:35.878 11464-11464/com.hello.chattest E/AndroidRuntime: --->onUncaughtExceptionHappened:Thread[main,5,main]<---
    java.lang.RuntimeException: Unable to start activity ComponentInfo{com.hello.chattest/org.jitsi.meet.sdk.JitsiMeetActivity}: android.view.InflateException: Binary XML file line #9 in com.hello.chattest:layout/activity_jitsi_meet: Binary XML file line #9 in com.hello.chattest:layout/activity_jitsi_meet: Error inflating class org.jitsi.meet.sdk.JitsiMeetView
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3501)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3661)
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:85)
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2108)
        at com.wanjian.cockroach.Cockroach$2.handleMessage(Cockroach.java:116)
        at android.os.Handler.dispatchMessage(Handler.java:102)
        at android.os.Looper.loop(Looper.java:236)
        at android.app.ActivityThread.main(ActivityThread.java:7876)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:656)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:967)
     Caused by: android.view.InflateException: Binary XML file line #9 in com.hello.chattest:layout/activity_jitsi_meet: Binary XML file line #9 in com.hello.chattest:layout/activity_jitsi_meet: Error inflating class org.jitsi.meet.sdk.JitsiMeetView
     Caused by: android.view.InflateException: Binary XML file line #9 in com.hello.chattest:layout/activity_jitsi_meet: Error inflating class org.jitsi.meet.sdk.JitsiMeetView
     Caused by: java.lang.reflect.InvocationTargetException
        at java.lang.reflect.Constructor.newInstance0(Native Method)
        at java.lang.reflect.Constructor.newInstance(Constructor.java:343)
        at android.view.LayoutInflater.createView(LayoutInflater.java:856)
        at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:1008)
        at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:963)
        at android.view.LayoutInflater.rInflate(LayoutInflater.java:1125)
        at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:1086)
        at android.view.LayoutInflater.inflate(LayoutInflater.java:684)
        at android.view.LayoutInflater.inflate(LayoutInflater.java:536)
        at android.view.LayoutInflater.inflate(LayoutInflater.java:479)
        at androidx.appcompat.app.AppCompatDelegateImpl.setContentView(AppCompatDelegateImpl.java:555)
        at androidx.appcompat.app.AppCompatActivity.setContentView(AppCompatActivity.java:161)
        at org.jitsi.meet.sdk.JitsiMeetActivity.onCreate(JitsiMeetActivity.java:93)
        at android.app.Activity.performCreate(Activity.java:8109)
        at android.app.Activity.performCreate(Activity.java:8083)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1310)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3474)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3661)
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:85)
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2108)
        at com.wanjian.cockroach.Cockroach$2.handleMessage(Cockroach.java:116)
        at android.os.Handler.dispatchMessage(Handler.java:102)
        at android.os.Looper.loop(Looper.java:236)
        at android.app.ActivityThread.main(ActivityThread.java:7876)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:656)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:967)

**Comment by saghul** [comment]
What SDK version are you using?

**Comment by ldm0330** [comment]
> 

Please forgive me for not knowing how to read the version, I got it from github git yesterday. I compiled it today and put this error in Android. Android version is 10

> What SDK version are you using?

SDK

**Comment by saghul** [comment]
Please try a released version first. The last release was just published. It's version 5.1.0.

**Comment by ldm0330** [comment]
> Please try a released version first. The last release was just published. It's version 5.1.0.
I used the latest version and the error became the following error. Do I need to import any package?


 Caused by: java.lang.ClassNotFoundException: Didn't find class "com.calendarevents.RNCalendarEventsPackage" on path: DexPathList[[dex file "InMemoryDexFile[cookie=[0, 3588432192]]", zip file "/data/app/~~WILTItbLNzXBJhz7IlxWiw==/com.hello.chattest-pZa4VND_bTXf8ueTHKTU1w==/base.apk"],nativeLibraryDirectories=[/data/app/~~WILTItbLNzXBJhz7IlxWiw==/com.hello.chattest-pZa4VND_bTXf8ueTHKTU1w==/lib/arm, /data/app/~~WILTItbLNzXBJhz7IlxWiw==/com.hello.chattest-pZa4VND_bTXf8ueTHKTU1w==/base.apk!/lib/armeabi-v7a, /system/lib, /system_ext/lib]]
        at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:207)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
        	... 34 more

**Comment by saghul** [comment]
How did you test it? Did you add our Maven repo?

**Comment by ldm0330** [comment]
We are using the example of this address
https://github.com/jitsi/jitsi-meet-sdk-samples/
Use https://github.com/jitsi/jitsi-meet to package it into an aar package and then reference it, compile it into an apk package and use it and throw this exception

**Comment by saghul** [comment]
You shouldn't be getting that. Let me update the samples.

**Comment by omkar273** [comment]
i am using latest jitsi sdk 6.2.2 but after 2 sec of joining app crashes and this error occured

E/AndroidRuntime: FATAL EXCEPTION: main
    Process: desno.hackathon.omkar.myapplication, PID: 8485
    java.lang.RuntimeException: Unable to start service org.jitsi.meet.sdk.JitsiMeetOngoingConferenceService@2765cb7 with Intent { cmp=desno.hackathon.omkar.myapplication/org.jitsi.meet.sdk.JitsiMeetOngoingConferenceService (has extras) }: java.lang.IllegalArgumentException: Invalid notification (no valid small icon): Notification(channel=JitsiOngoingConferenceChannel shortcut=null contentView=null vibrate=null sound=null defaults=0x0 flags=0xa color=0x00000000 category=call actions=2 vis=PUBLIC)
        at android.app.ActivityThread.handleServiceArgs(ActivityThread.java:4703)
        at android.app.ActivityThread.-$$Nest$mhandleServiceArgs(Unknown Source:0)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2181)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loopOnce(Looper.java:201)
        at android.os.Looper.loop(Looper.java:288)
        at android.app.ActivityThread.main(ActivityThread.java:7898)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:936)
     Caused by: java.lang.IllegalArgumentException: Invalid notification (no valid small icon): Notification(channel=JitsiOngoingConferenceChannel shortcut=null contentView=null vibrate=null sound=null defaults=0x0 flags=0xa color=0x00000000 category=call actions=2 vis=PUBLIC)
        at android.app.NotificationManager.fixNotification(NotificationManager.java:700)
        at android.app.NotificationManager.notifyAsUser(NotificationManager.java:679)
        at android.app.NotificationManager.notify(NotificationManager.java:628)
        at android.app.NotificationManager.notify(NotificationManager.java:604)
        at org.jitsi.meet.sdk.JitsiMeetOngoingConferenceService.onStartCommand(JitsiMeetOngoingConferenceService.java:135)
        at android.app.ActivityThread.handleServiceArgs(ActivityThread.java:4685)
        at android.app.ActivityThread.-$$Nest$mhandleServiceArgs(Unknown Source:0) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2181) 
        at android.os.Handler.dispatchMessage(Handler.java:106) 
        at android.os.Looper.loopOnce(Looper.java:201) 
        at android.os.Looper.loop(Looper.java:288) 
        at android.app.ActivityThread.main(ActivityThread.java:7898) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:936) 
E/JitsiMeetSDK: JitsiMeetUncaughtExceptionHandler FATAL ERROR
    java.lang.RuntimeException: Unable to start service org.jitsi.meet.sdk.JitsiMeetOngoingConferenceService@2765cb7 with Intent { cmp=desno.hackathon.omkar.myapplication/org.jitsi.meet.sdk.JitsiMeetOngoingConferenceService (has extras) }: java.lang.IllegalArgumentException: Invalid notification (no valid small icon): Notification(channel=JitsiOngoingConferenceChannel shortcut=null contentView=null vibrate=null sound=null defaults=0x0 flags=0xa color=0x00000000 category=call actions=2 vis=PUBLIC)
        at android.app.ActivityThread.handleServiceArgs(ActivityThread.java:4703)
        at android.app.ActivityThread.-$$Nest$mhandleServiceArgs(Unknown Source:0)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2181)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loopOnce(Looper.java:201)
        at android.os.Looper.loop(Looper.java:288)
        at android.app.ActivityThread.main(ActivityThread.java:7898)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:936)
     Caused by: java.lang.IllegalArgumentException: Invalid notification (no valid small icon): Notification(channel=JitsiOngoingConferenceChannel shortcut=null contentView=null vibrate=null sound=null defaults=0x0 flags=0xa color=0x00000000 category=call actions=2 vis=PUBLIC)
        at android.app.NotificationManager.fixNotification(NotificationManager.java:700)
        at android.app.NotificationManager.notifyAsUser(NotificationManager.java:679)
        at android.app.NotificationManager.notify(NotificationManager.java:628)
        at android.app.NotificationManager.notify(NotificationManager.java:604)
        at org.jitsi.meet.sdk.JitsiMeetOngoingConferenceService.onStartCommand(JitsiMeetOngoingConferenceService.java:135)
        at android.app.ActivityThread.handleServiceArgs(ActivityThread.java:4685)
        at android.app.ActivityThread.-$$Nest$mhandleServiceArgs(Unknown Source:0) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2181) 
        at android.os.Handler.dispatchMessage(Handler.java:106) 
        at android.os.Looper.loopOnce(Looper.java:201) 
        at android.os.Looper.loop(Looper.java:288) 
        at android.app.ActivityThread.main(ActivityThread.java:7898) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:936) 
    
    java.lang.RuntimeException: Unable to start service org.jitsi.meet.sdk.JitsiMeetOngoingConferenceService@2765cb7 with Intent { cmp=desno.hackathon.omkar.myapplication/org.jitsi.meet.sdk.JitsiMeetOngoingConferenceService (has extras) }: java.lang.IllegalArgumentException: Invalid notification (no valid small icon): Notification(channel=JitsiOngoingConferenceChannel shortcut=null contentView=null vibrate=null sound=null defaults=0x0 flags=0xa color=0x00000000 category=call actions=2 vis=PUBLIC)
        at android.app.ActivityThread.handleServiceArgs(ActivityThread.java:4703)
        at android.app.ActivityThread.-$$Nest$mhandleServiceArgs(Unknown Source:0)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2181)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loopOnce(Looper.java:201)
        at android.os.Looper.loop(Looper.java:288)
        at android.app.ActivityThread.main(ActivityThread.java:7898)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:936)
     Caused by: java.lang.IllegalArgumentException: Invalid notification (no valid small icon): Notification(channel=JitsiOngoingConferenceChannel shortcut=null contentView=null vibrate=null sound=null defaults=0x0 flags=0xa color=0x00000000 category=call actions=2 vis=PUBLIC)
        at android.app.NotificationManager.fixNotification(NotificationManager.java:700)
        at android.app.NotificationManager.notifyAsUser(NotificationManager.java:679)
        at android.app.NotificationManager.notify(NotificationManager.java:628)
        at android.app.NotificationManager.notify(NotificationManager.java:604)
        at org.jitsi.meet.sdk.JitsiMeetOngoingConferenceService.onStartCommand(JitsiMeetOngoingConferenceService.java:135)
        at android.app.ActivityThread.handleServiceArgs(ActivityThread.java:4685)
        at android.app.ActivityThread.-$$Nest$mhandleServiceArgs(Unknown Source:0) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2181) 
        at android.os.Handler.dispatchMessage(Handler.java:106) 
        at android.os.Looper.loopOnce(Looper.java:201) 
        at android.os.Looper.loop(Looper.java:288) 
        at android.app.ActivityThread.main(ActivityThread.java:7898) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:936) 
I/JitsiMeetSDK: JitsiConnectionService onAbort 8BA0100A-2AC4-4AA5-A20A-507A4503E757
I/JitsiMeetSDK: [features/app] appNavigate to undefined
D/JitsiMeetSDK: JitsiConnectionService onStateChanged: DISCONNECTED 8BA0100A-2AC4-4AA5-A20A-507A4503E757
I/Process: Sending signal. PID: 8485 SIG: 9

**Comment by saghul** [comment]
Please read the error message. You are missing the ic_notification icon. Your appo needs to supply one.

**Comment by itachi-05** [comment]
I am trying to use JitsiMeetView in my xml file as following but the app crashes saying:
Error inflating class org.jitsi.meet.sdk.JitsiMeetView
XML:

<?xml version="1.0" encoding="utf-8"?>
<androidx.constraintlayout.widget.ConstraintLayout xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:app="http://schemas.android.com/apk/res-auto"
    xmlns:tools="http://schemas.android.com/tools"
    android:layout_width="match_parent"
    android:layout_height="match_parent"
    tools:context=".MeetActivity">

    <org.jitsi.meet.sdk.JitsiMeetView
        android:id="@+id/jitsi_view"
        android:layout_width="match_parent"
        android:layout_height="match_parent"
        app:layout_constraintBottom_toBottomOf="parent"
        app:layout_constraintEnd_toEndOf="parent"
        app:layout_constraintStart_toStartOf="parent"
        app:layout_constraintTop_toTopOf="parent" />

</androidx.constraintlayout.widget.ConstraintLayout>

Gradle Build : Dependency added
implementation ('org.jitsi.react:jitsi-meet-sdk:7.0.1') { transitive = true }

How to resolve this problem ?
@saghul

**Comment by saghul** [comment]
Can you please paste the full crash log?

**Comment by dinpran** [comment]
I am facing a issue so , my problem is that , I am using jitsi meet wrapper class cause jitsi meet is not available now so when create a new meeting but in some time a pop up appears of full screen then after it it shows white screen and it leaves the new meeting page, how can i solve this , if anyone knows please help i am solving it from 2-3 days and i have also contact other flutter developers but it is not solved yet  so sir if you can help me i will be thankfull and if anyone knows please reply me.
I/JitsiMeetSDK( 2872): JitsiConnectionService onAbort C20535AD-B08E-4F27-9B3C-4C2C5719DE18
D/JitsiMeetSDK( 2872): JitsiConnectionService onStateChanged: HOLDING C20535AD-B08E-4F27-9B3C-4C2C5719DE18
D/JitsiMeetSDK( 2872): JitsiConnectionService onStateChanged: DISCONNECTED C20535AD-B08E-4F27-9B3C-4C2C5719DE18
I/Process ( 2872): Sending signal. PID: 2872 SIG: 9
Lost connection to device.
