### ISSUE TITLE
pack. AAR error reporting

### ISSUE THREAD

**Issue by 337077418** [jitsi/jitsi-meet#11542]
However, due to project reasons, local must be used AAR SDK, error reporting when upgrading from 2.4.0 to 5.1.0

java.lang.RuntimeException: Unable to start activity ComponentInfo{net.jitsi.sdktest/org.jitsi.meet.sdk.JitsiMeetActivity}: android.view.InflateException: Binary XML file line https://github.com/jitsi/jitsi-meet-sdk-samples/issues/12 in net.jitsi.sdktest:layout/activity_jitsi_meet: Binary XML file line https://github.com/jitsi/jitsi-meet-sdk-samples/issues/12 in net.jitsi.sdktest:layout/activity_jitsi_meet: Error inflating class org.jitsi.meet.sdk.JitsiMeetView
at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:4060)
at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:4247)
at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:91)
at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:149)
at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:103)
at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2613)
at android.os.Handler.dispatchMessage(Handler.java:110)
at android.os.Looper.loop(Looper.java:219)
at android.app.ActivityThread.main(ActivityThread.java:8668)
at java.lang.reflect.Method.invoke(Native Method)
at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:513)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1109)
Caused by: android.view.InflateException: Binary XML file line https://github.com/jitsi/jitsi-meet-sdk-samples/issues/12 in net.jitsi.sdktest:layout/activity_jitsi_meet: Binary XML file line https://github.com/jitsi/jitsi-meet-sdk-samples/issues/12 in net.jitsi.sdktest:layout/activity_jitsi_meet: Error inflating class org.jitsi.meet.sdk.JitsiMeetView
Caused by: android.view.InflateException: Binary XML file line https://github.com/jitsi/jitsi-meet-sdk-samples/issues/12 in net.jitsi.sdktest:layout/activity_jitsi_meet: Error inflating class org.jitsi.meet.sdk.JitsiMeetView
Caused by: java.lang.reflect.InvocationTargetException
at java.lang.reflect.Constructor.newInstance0(Native Method)
at java.lang.reflect.Constructor.newInstance(Constructor.java:343)
at android.view.LayoutInflater.createView(LayoutInflater.java:864)
at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:1016)
at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:971)
at android.view.LayoutInflater.rInflate(LayoutInflater.java:1133)
at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:1094)
at android.view.LayoutInflater.inflate(LayoutInflater.java:692)
at android.view.LayoutInflater.inflate(LayoutInflater.java:536)
at com.android.internal.policy.HwPhoneLayoutInflater.inflate(HwPhoneLayoutInflater.java:138)
at android.view.LayoutInflater.inflate(LayoutInflater.java:483)
at androidx.appcompat.app.AppCompatDelegateImpl.setContentView(AppCompatDelegateImpl.java:706)
at androidx.appcompat.app.AppCompatActivity.setContentView(AppCompatActivity.java:195)
at org.jitsi.meet.sdk.JitsiMeetActivity.onCreate(JitsiMeetActivity.java:93)
at android.app.Activity.performCreate(Activity.java:8214)
at android.app.Activity.performCreate(Activity.java:8202)
at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1320)
at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:4033)
at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:4247)
at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:91)
at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:149)
at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:103)
at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2613)
at android.os.Handler.dispatchMessage(Handler.java:110)
at android.os.Looper.loop(Looper.java:219)
at android.app.ActivityThread.main(ActivityThread.java:8668)
at java.lang.reflect.Method.invoke(Native Method)
at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:513)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1109)
Caused by: java.lang.NoClassDefFoundError: Failed resolution of: Lcom/calendarevents/RNCalendarEventsPackage;
2022-05-17 16:37:36.109 13299-13299/net.jitsi.sdktest E/AndroidRuntime: at org.jitsi.meet.sdk.ReactInstanceManagerHolder.getReactNativePackages(ReactInstanceManagerHolder.java:105)
at org.jitsi.meet.sdk.ReactInstanceManagerHolder.initReactInstanceManager(ReactInstanceManagerHolder.java:279)
at org.jitsi.meet.sdk.BaseReactView.initialize(BaseReactView.java:232)
at org.jitsi.meet.sdk.BaseReactView.(BaseReactView.java:118)
at org.jitsi.meet.sdk.JitsiMeetView.(JitsiMeetView.java:103)
... 29 more
Caused by: java.lang.ClassNotFoundException: Didn't find class "com.calendarevents.RNCalendarEventsPackage" on path: DexPathList[[zip file "/data/app/net.jitsi.sdktest-YeZeVf9rMORdR9RDRQ_Vlg==/base.apk"],nativeLibraryDirectories=[/data/app/net.jitsi.sdktest-YeZeVf9rMORdR9RDRQ_Vlg==/lib/arm64, /data/app/net.jitsi.sdktest-YeZeVf9rMORdR9RDRQ_Vlg==/base.apk!/lib/arm64-v8a, /system/lib64, /hw_product/lib64, /system/product/lib64]]
at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:209)
at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
... 34 more
2022-05-17 16:37:36.112 13299-13299/net.jitsi.sdktest E/JitsiMeetSDK: JitsiMeetUncaughtExceptionHandler FATAL ERROR
java.lang.RuntimeException: Unable to start activity ComponentInfo{net.jitsi.sdktest/org.jitsi.meet.sdk.JitsiMeetActivity}: android.view.InflateException: Binary XML file line https://github.com/jitsi/jitsi-meet-sdk-samples/issues/12 in net.jitsi.sdktest:layout/activity_jitsi_meet: Binary XML file line https://github.com/jitsi/jitsi-meet-sdk-samples/issues/12 in net.jitsi.sdktest:layout/activity_jitsi_meet: Error inflating class org.jitsi.meet.sdk.JitsiMeetView
at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:4060)
at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:4247)
at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:91)
at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:149)
at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:103)
at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2613)
at android.os.Handler.dispatchMessage(Handler.java:110)
at android.os.Looper.loop(Looper.java:219)
at android.app.ActivityThread.main(ActivityThread.java:8668)
at java.lang.reflect.Method.invoke(Native Method)
at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:513)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1109)
Caused by: android.view.InflateException: Binary XML file line https://github.com/jitsi/jitsi-meet-sdk-samples/issues/12 in net.jitsi.sdktest:layout/activity_jitsi_meet: Binary XML file line https://github.com/jitsi/jitsi-meet-sdk-samples/issues/12 in net.jitsi.sdktest:layout/activity_jitsi_meet: Error inflating class org.jitsi.meet.sdk.JitsiMeetView
Caused by: android.view.InflateException: Binary XML file line https://github.com/jitsi/jitsi-meet-sdk-samples/issues/12 in net.jitsi.sdktest:layout/activity_jitsi_meet: Error inflating class org.jitsi.meet.sdk.JitsiMeetView
Caused by: java.lang.reflect.InvocationTargetException
at java.lang.reflect.Constructor.newInstance0(Native Method)
at java.lang.reflect.Constructor.newInstance(Constructor.java:343)
at android.view.LayoutInflater.createView(LayoutInflater.java:864)
at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:1016)
at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:971)
at android.view.LayoutInflater.rInflate(LayoutInflater.java:1133)
at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:1094)
at android.view.LayoutInflater.inflate(LayoutInflater.java:692)
at android.view.LayoutInflater.inflate(LayoutInflater.java:536)
at com.android.internal.policy.HwPhoneLayoutInflater.inflate(HwPhoneLayoutInflater.java:138)
at android.view.LayoutInflater.inflate(LayoutInflater.java:483)
at androidx.appcompat.app.AppCompatDelegateImpl.setContentView(AppCompatDelegateImpl.java:706)
at androidx.appcompat.app.AppCompatActivity.setContentView(AppCompatActivity.java:195)
at org.jitsi.meet.sdk.JitsiMeetActivity.onCreate(JitsiMeetActivity.java:93)
at android.app.Activity.performCreate(Activity.java:8214)
at android.app.Activity.performCreate(Activity.java:8202)
at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1320)
at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:4033)
at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:4247)
at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:91)
at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:149)
at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:103)
at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2613)
at android.os.Handler.dispatchMessage(Handler.java:110)
at android.os.Looper.loop(Looper.java:219)
at android.app.ActivityThread.main(ActivityThread.java:8668)
at java.lang.reflect.Method.invoke(Native Method)
at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:513)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1109)
Caused by: java.lang.NoClassDefFoundError: Failed resolution of: Lcom/calendarevents/RNCalendarEventsPackage;
at org.jitsi.meet.sdk.ReactInstanceManagerHolder.getReactNativePackages(

**Comment by saghul** [comment]
I think I understand. Do you need the aar to be local? Our SDK has numerous dependencies. All of that is taken care of if you use maven, if you don't you need to track them yourself. The error is caused by a missing dependency.

I'd suggest you use a local maven repo with the SDK: https://jitsi.github.io/handbook/docs/dev-guide/dev-guide-android-sdk#build-and-use-your-own-sdk-artifactsbinaries if you can't use our repo.
