### ISSUE TITLE
App Crashes Unexpectedly after joining a call in Android

### ISSUE THREAD

**Issue by khushi491** [jitsi/jitsi-meet#11736]
### Description:

- I am implementing the jitsi-meet android SDK into my react-native app using native bridge and getting error.
- my requirement is make a video call using jitsi in my RN app.
- I made a native bridge to the RN and tried to make a video call using jitsi.
- In IOS it's working Fine. but in Android it's not working 

### Additional information:

- Jitsi Meet sdk: 5.1.0
- RN version :- 0.68.1

### logcat output : 

```
`2022-06-23 14:55:07.679 26765-27466/com..* E/AndroidRuntime: FATAL EXCEPTION: create_react_context
Process: com.., PID: 26765
java.lang.NoClassDefFoundError: com.facebook.react.jscexecutor.JSCExecutor
at com.facebook.react.jscexecutor.JSCExecutorFactory.create(JSCExecutorFactory.java:29)
at com.facebook.react.ReactInstanceManager$5.run(ReactInstanceManager.java:1112)
at java.lang.Thread.run(Thread.java:929)
Caused by: java.lang.UnsatisfiedLinkError: couldn't find DSO to load: libjscexecutor.so
SoSource 0: com.facebook.soloader.DirectorySoSource[root = /data/app/com..-dmhqxncifxjbXOcK7o_chQ==/lib/arm64 flags = 0]
SoSource 1: com.facebook.soloader.DirectApkSoSource[root = /data/app/com..-dmhqxncifxjbXOcK7o_chQ==/base.apk!/lib/arm64-v8a]
SoSource 2: com.facebook.soloader.DirectorySoSource[root = /system/lib64 flags = 2]
SoSource 3: com.facebook.soloader.DirectorySoSource[root = /vendor/lib64 flags = 2]
Native lib dir: /data/app/com..-dmhqxncifxjbXOcK7o_chQ==/lib/arm64
result: 0
at com.facebook.soloader.SoLoader.doLoadLibraryBySoName(SoLoader.java:1098)
at com.facebook.soloader.SoLoader.loadLibraryBySoNameImpl(SoLoader.java:914)
at com.facebook.soloader.SoLoader.loadLibraryBySoName(SoLoader.java:826)
at com.facebook.soloader.SoLoader.loadLibrary(SoLoader.java:773)
at com.facebook.soloader.SoLoader.loadLibrary(SoLoader.java:743)
at com.facebook.react.jscexecutor.JSCExecutor.loadLibrary(JSCExecutor.java:24)
at com.facebook.react.jscexecutor.JSCExecutor.(JSCExecutor.java:20)
at com.facebook.react.jscexecutor.JSCExecutor.loadLibrary(JSCExecutor.java:24)
at com.facebook.react.ReactInstanceManagerBuilder.getDefaultJSExecutorFactory(ReactInstanceManagerBuilder.java:351)
at com.facebook.react.ReactInstanceManagerBuilder.build(ReactInstanceManagerBuilder.java:318)
at com.facebook.react.ReactNativeHost.createReactInstanceManager(ReactNativeHost.java:95)
at com.facebook.react.ReactNativeHost.getReactInstanceManager(ReactNativeHost.java:42)
at com...MainApplication.onCreate(MainApplication.java:59)
at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1195)
at android.app.ActivityThread.handleBindApplication(ActivityThread.java:7202)
at android.app.ActivityThread.access$2200(ActivityThread.java:296)
at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2208)
at android.os.Handler.dispatchMessage(Handler.java:107)
at android.os.Looper.loop(Looper.java:213)
at android.app.ActivityThread.main(ActivityThread.java:8178)
at java.lang.reflect.Method.invoke(Native Method)
at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:513)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1101)
2022-06-23 14:55:07.691 26765-27466/com..****** E/JitsiMeetSDK: JitsiMeetUncaughtExceptionHandler FATAL ERROR
java.lang.NoClassDefFoundError: com.facebook.react.jscexecutor.JSCExecutor
at com.facebook.react.jscexecutor.JSCExecutorFactory.create(JSCExecutorFactory.java:29)
at com.facebook.react.ReactInstanceManager$5.run(ReactInstanceManager.java:1112)
at java.lang.Thread.run(Thread.java:929)
Caused by: java.lang.UnsatisfiedLinkError: couldn't find DSO to load: libjscexecutor.so
SoSource 0: com.facebook.soloader.DirectorySoSource[root = /data/app/com..-dmhqxncifxjbXOcK7o_chQ==/lib/arm64 flags = 0]
SoSource 1: com.facebook.soloader.DirectApkSoSource[root = /data/app/com..-dmhqxncifxjbXOcK7o_chQ==/base.apk!/lib/arm64-v8a]
SoSource 2: com.facebook.soloader.DirectorySoSource[root = /system/lib64 flags = 2]
SoSource 3: com.facebook.soloader.DirectorySoSource[root = /vendor/lib64 flags = 2]
Native lib dir: /data/app/com..-dmhqxncifxjbXOcK7o_chQ==/lib/arm64
result: 0
at com.facebook.soloader.SoLoader.doLoadLibraryBySoName(SoLoader.java:1098)
at com.facebook.soloader.SoLoader.loadLibraryBySoNameImpl(SoLoader.java:914)
at com.facebook.soloader.SoLoader.loadLibraryBySoName(SoLoader.java:826)
at com.facebook.soloader.SoLoader.loadLibrary(SoLoader.java:773)
at com.facebook.soloader.SoLoader.loadLibrary(SoLoader.java:743)
at com.facebook.react.jscexecutor.JSCExecutor.loadLibrary(JSCExecutor.java:24)
at com.facebook.react.jscexecutor.JSCExecutor.(JSCExecutor.java:20)
at com.facebook.react.jscexecutor.JSCExecutor.loadLibrary(JSCExecutor.java:24)
at com.facebook.react.ReactInstanceManagerBuilder.getDefaultJSExecutorFactory(ReactInstanceManagerBuilder.java:351)
at com.facebook.react.ReactInstanceManagerBuilder.build(ReactInstanceManagerBuilder.java:318)
at com.facebook.react.ReactNativeHost.createReactInstanceManager(ReactNativeHost.java:95)
at com.facebook.react.ReactNativeHost.getReactInstanceManager(ReactNativeHost.java:42)
at com..****.MainApplication.onCreate(MainApplication.java:59)
at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1195)
at android.app.ActivityThread.handleBindApplication(ActivityThread.java:7202)
at android.app.ActivityThread.access$2200(ActivityThread.java:296)
at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2208)
at android.os.Handler.dispatchMessage(Handler.java:107)
at android.os.Looper.loop(Looper.java:213)
at android.app.ActivityThread.main(ActivityThread.java:8178)
at java.lang.reflect.Method.invoke(Native Method)
at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:513)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1101)

java.lang.NoClassDefFoundError: com.facebook.react.jscexecutor.JSCExecutor
    at com.facebook.react.jscexecutor.JSCExecutorFactory.create(JSCExecutorFactory.java:29)
    at com.facebook.react.ReactInstanceManager$5.run(ReactInstanceManager.java:1112)
    at java.lang.Thread.run(Thread.java:929)
 Caused by: java.lang.UnsatisfiedLinkError: couldn't find DSO to load: libjscexecutor.so
	SoSource 0: com.facebook.soloader.DirectorySoSource[root = /data/app/com.*****.******-dmhqxncifxjbXOcK7o_chQ==/lib/arm64 flags = 0]
	SoSource 1: com.facebook.soloader.DirectApkSoSource[root = /data/app/com.*****.******-dmhqxncifxjbXOcK7o_chQ==/base.apk!/lib/arm64-v8a]
	SoSource 2: com.facebook.soloader.DirectorySoSource[root = /system/lib64 flags = 2]
	SoSource 3: com.facebook.soloader.DirectorySoSource[root = /vendor/lib64 flags = 2]
	Native lib dir: /data/app/com.*****.******-dmhqxncifxjbXOcK7o_chQ==/lib/arm64
 result: 0
    at com.facebook.soloader.SoLoader.doLoadLibraryBySoName(SoLoader.java:1098)
    at com.facebook.soloader.SoLoader.loadLibraryBySoNameImpl(SoLoader.java:914)
    at com.facebook.soloader.SoLoader.loadLibraryBySoName(SoLoader.java:826)
    at com.facebook.soloader.SoLoader.loadLibrary(SoLoader.java:773)
    at com.facebook.soloader.SoLoader.loadLibrary(SoLoader.java:743)
	at com.facebook.react.jsce` 
```

**Comment by saghul** [comment]
Does your app use Hermes? Our SDK doesn't, you'll need to match the runtime.

**Comment by khushi491** [comment]
project.ext.react = [
    entryFile: "index.js",
    enableHermes: false, 
]

i did this enableHermes: false
now i'm getting black screen after joining a call in Android

**Comment by saghul** [comment]
Please share the logs.

**Comment by khushi491** [comment]
@saghul 

```
2022-06-27 11:57:09.652 2869-2869/? E/bookings_afric: Unknown bits set in runtime_flags: 0x8000
2022-06-27 11:57:09.674 2869-2869/? E/libc: Access denied finding property "runtime.mmitest.isrunning"
2022-06-27 11:57:11.445 2869-2912/com.unicorn.bookings_africa E/AwareLog: AtomicFileUtils: readFileLines file not exist: android.util.AtomicFile@d393a91
2022-06-27 11:57:12.546 2869-3005/com.unicorn.bookings_africa E/: APS:IFLoad:importExternalFunctions, search function createNewHwApsUtils failed, dlsym err:undefined symbol: createNewHwApsUtils
2022-06-27 11:57:15.268 2869-3066/com.unicorn.bookings_africa E/bookings_afric: Invalid ID 0x00000000.
```

**Comment by khushi491** [comment]
still i'm getting black screen.
what should i do ?

**Comment by saghul** [comment]
I don't know, sorry.

**Comment by EDible-Dev** [comment]
Hi @khushi491 , may I ask if you have tried the following steps after getting the black screen?

1. Click the device 'Back' button.
2. Then click the device 'Overview' button.
3. Then try to join the call again.

The "black screen on Android" reminded me of an issue I encountered in the react-native-jitsi-meet wrapper.  And the above steps will take me in the call the second time on but none of the control buttons responds to my press (that means I couldn't end the call or do anything).  

This is not a fix but I wonder if you have the same behavior.  If you do, the underlying problem might be the same.

**Comment by khushi491** [comment]
Hey @EDible-Dev 

I have the Exact same behavior.
and yes, i have tried all this step but didn't work for me.

**Comment by EDible-Dev** [comment]
@khushi491 - Thanks for your response!  Like I mentioned, I have been using the react-native-jitsi-meet when I encountered that issue (and no solution yet).  But I am going to try the actual jitsi-meet SDK directly to see if I will have the same (or similar) issue on Android.

**Comment by vivekMss** [comment]
i'm getting

2022-09-09 15:58:44.950 11469-11732/org.jitsi.meet E/JavaBinder: !!! FAILED BINDER TRANSACTION !!!  (parcel size = 152)
and 
2022-09-09 15:58:45.006 11469-11707/org.jitsi.meet A/libc: Fatal signal 4 (SIGILL), code 1 (ILL_ILLOPC), fault addr 0x7108681220 in tid 11707 (mqt_js), pid 11469 (org.jitsi.meet)

error on android before crash

**Comment by saghul** [comment]
Paste the full log so we can see the whole picture.

**Comment by vivekMss** [comment]
is it enough..? should i post more

**Comment by saghul** [comment]
That doesn't show the crash. Please paste the entirety of it in a gist and link it here.

**Comment by vivekMss** [comment]
ok the senerio is when simulator of ios tries to get in room and android emulator user is already in 
in that case it got crashed n does'n open

**Comment by saghul** [comment]
We need logs.

**Comment by vivekMss** [comment]
> We need logs.

this is all the log happend in that senerio





022-09-09 17:12:57.582 18114-18221/org.jitsi.meet I/JitsiMeetSDK: [modules/xmpp/xmpp.js] My Jabber ID: b6f285d4-1cd4-4750-b013-e24ed8049c04@meet.jit.si/My2Kw8qa6kgN
2022-09-09 17:12:57.582 18114-18221/org.jitsi.meet D/JitsiMeetSDK: [modules/RTC/CodecSelection.js] Codec preferences for the conference are JVB: vp9,
                P2P: h264
2022-09-09 17:12:57.591 18114-18221/org.jitsi.meet I/JitsiMeetSDK: [modules/xmpp/xmpp.js] JID b6f285d4-1cd4-4750-b013-e24ed8049c04@meet.jit.si/My2Kw8qa6kgN using MUC nickname b6f285d4
2022-09-09 17:12:57.591 18114-18221/org.jitsi.meet D/JitsiMeetSDK: [modules/qualitycontrol/ReceiveVideoController.js] Updating ReceiverVideoConstraints lastN(25)
2022-09-09 17:12:57.591 18114-18221/org.jitsi.meet I/JitsiMeetSDK: [modules/statistics/AvgRTPStatsReporter.js] Avg RTP stats will be calculated every 15 samples
2022-09-09 17:12:57.591 18114-18221/org.jitsi.meet I/JitsiMeetSDK: [JitsiConference.js] backToP2PDelay: 5
2022-09-09 17:12:57.591 18114-18221/org.jitsi.meet D/JitsiMeetSDK: [modules/videosipgw/VideoSIPGW.js] creating VideoSIPGW
2022-09-09 17:12:57.591 18114-18221/org.jitsi.meet I/JitsiMeetSDK: [JitsiConference.js] _doReplaceTrack - no JVB JingleSession
2022-09-09 17:12:57.591 18114-18221/org.jitsi.meet I/JitsiMeetSDK: [JitsiConference.js] _doReplaceTrack - no P2P JingleSession
2022-09-09 17:12:57.591 18114-18221/org.jitsi.meet I/JitsiMeetSDK: [JitsiConference.js] _doReplaceTrack - no JVB JingleSession
2022-09-09 17:12:57.591 18114-18221/org.jitsi.meet I/JitsiMeetSDK: [JitsiConference.js] _doReplaceTrack - no P2P JingleSession
2022-09-09 17:12:57.609 18114-18221/org.jitsi.meet I/JitsiMeetSDK: [modules/xmpp/moderator.js] Focus jid set to:  undefined
2022-09-09 17:12:57.609 18114-18221/org.jitsi.meet I/JitsiMeetSDK: [modules/xmpp/moderator.js] Session ID: null machine UID: e367838f8e6d0c7652f3fc4dfae5a27c
2022-09-09 17:12:57.654 18114-18114/org.jitsi.meet I/org.webrtc.Logging: SurfaceEglRenderer: : surfaceChanged: format: 4 size: 1433x3033
2022-09-09 17:12:57.655 18114-18114/org.jitsi.meet I/org.webrtc.Logging: EglRenderer: setLayoutAspectRatio: 0.4724695
2022-09-09 17:12:57.656 18114-18221/org.jitsi.meet W/JitsiMeetSDK: [modules/xmpp/XmppConnection.js] Stream resume enabled, but WebSockets are not enabled
2022-09-09 17:12:57.656 18114-18221/org.jitsi.meet I/JitsiMeetSDK: [modules/xmpp/strophe.ping.js] XMPP pings will be sent every 10000 ms
2022-09-09 17:12:57.656 18114-18221/org.jitsi.meet I/JitsiMeetSDK: [modules/xmpp/xmpp.js] (TIME) Strophe connected:	 1662723777652
2022-09-09 17:12:57.656 18114-18221/org.jitsi.meet I/JitsiMeetSDK: [modules/xmpp/xmpp.js] My Jabber ID: e4af2601-fbce-42b9-9751-e1c3f88caee9@meet.jit.si/8S9EI-3PEuj4
2022-09-09 17:12:57.656 18114-18221/org.jitsi.meet D/JitsiMeetSDK: [modules/RTC/CodecSelection.js] Codec preferences for the conference are JVB: vp9,
                P2P: h264
2022-09-09 17:12:57.661 18114-18221/org.jitsi.meet I/JitsiMeetSDK: [modules/xmpp/xmpp.js] JID e4af2601-fbce-42b9-9751-e1c3f88caee9@meet.jit.si/8S9EI-3PEuj4 using MUC nickname e4af2601
2022-09-09 17:12:57.661 18114-18221/org.jitsi.meet D/JitsiMeetSDK: [modules/qualitycontrol/ReceiveVideoController.js] Updating ReceiverVideoConstraints lastN(25)
2022-09-09 17:12:57.662 18114-18221/org.jitsi.meet I/JitsiMeetSDK: [modules/statistics/AvgRTPStatsReporter.js] Avg RTP stats will be calculated every 15 samples
2022-09-09 17:12:57.662 18114-18221/org.jitsi.meet I/JitsiMeetSDK: [JitsiConference.js] backToP2PDelay: 5
2022-09-09 17:12:57.662 18114-18221/org.jitsi.meet D/JitsiMeetSDK: [modules/videosipgw/VideoSIPGW.js] creating VideoSIPGW
2022-09-09 17:12:57.662 18114-18221/org.jitsi.meet I/JitsiMeetSDK: [JitsiConference.js] _doReplaceTrack - no JVB JingleSession
2022-09-09 17:12:57.662 18114-18221/org.jitsi.meet I/JitsiMeetSDK: [JitsiConference.js] _doReplaceTrack - no P2P JingleSession
2022-09-09 17:12:57.662 18114-18221/org.jitsi.meet I/JitsiMeetSDK: [JitsiConference.js] _doReplaceTrack - no JVB JingleSession
2022-09-09 17:12:57.662 18114-18221/org.jitsi.meet I/JitsiMeetSDK: [JitsiConference.js] _doReplaceTrack - no P2P JingleSession
2022-09-09 17:12:57.678 18114-18221/org.jitsi.meet I/JitsiMeetSDK: [modules/xmpp/moderator.js] Focus jid set to:  undefined
2022-09-09 17:12:57.679 18114-18221/org.jitsi.meet I/JitsiMeetSDK: [modules/xmpp/moderator.js] Session ID: null machine UID: e367838f8e6d0c7652f3fc4dfae5a27c
2022-09-09 17:12:57.729 18114-18221/org.jitsi.meet I/JitsiMeetSDK: [modules/xmpp/moderator.js] Focus jid set to:  focus@auth.meet.jit.si
2022-09-09 17:12:57.729 18114-18221/org.jitsi.meet I/JitsiMeetSDK: [modules/xmpp/moderator.js] Authentication enabled: false
2022-09-09 17:12:57.729 18114-18221/org.jitsi.meet I/JitsiMeetSDK: [modules/xmpp/moderator.js] External authentication enabled: false
2022-09-09 17:12:57.729 18114-18221/org.jitsi.meet I/JitsiMeetSDK: [modules/xmpp/moderator.js] Sip gateway enabled:  false
2022-09-09 17:12:57.733 18114-18221/org.jitsi.meet I/JitsiMeetSDK: [modules/xmpp/moderator.js] Focus jid set to:  focus@auth.meet.jit.si
2022-09-09 17:12:57.734 18114-18221/org.jitsi.meet I/JitsiMeetSDK: [modules/xmpp/moderator.js] Authentication enabled: false
2022-09-09 17:12:57.734 18114-18221/org.jitsi.meet I/JitsiMeetSDK: [modules/xmpp/moderator.js] External authentication enabled: false
2022-09-09 17:12:57.734 18114-18221/org.jitsi.meet I/JitsiMeetSDK: [modules/xmpp/moderator.js] Sip gateway enabled:  false
2022-09-09 17:12:57.807 18114-18140/org.jitsi.meet D/EGL_emulation: app_time_stats: avg=14.98ms min=1.28ms max=23.18ms count=61
2022-09-09 17:12:57.820 18114-18114/org.jitsi.meet E/org.jitsi.meet: No package ID ff found for ID 0xffffffff.
2022-09-09 17:12:57.821 18114-18114/org.jitsi.meet I/org.webrtc.Logging: EglRenderer: setMirrorHorizontally: true
2022-09-09 17:12:57.824 18114-18114/org.jitsi.meet W/org.jitsi.meet: Accessing hidden field Landroid/widget/HorizontalScrollView;->mScroller:Landroid/widget/OverScroller; (unsupported, reflection, allowed)
2022-09-09 17:12:57.862 18114-18221/org.jitsi.meet I/JitsiMeetSDK: [modules/version/ComponentsVersions.js] Got focus version: 1.0.915
2022-09-09 17:12:57.867 18114-18221/org.jitsi.meet I/JitsiMeetSDK: [JitsiConference.js] Audio unmute permissions set by Jicofo to false
2022-09-09 17:12:57.867 18114-18221/org.jitsi.meet I/JitsiMeetSDK: [JitsiConference.js] Video unmute permissions set by Jicofo to false
2022-09-09 17:12:57.904 18114-18221/org.jitsi.meet I/JitsiMeetSDK: [features/video-quality] Setting sender resolution to 360
2022-09-09 17:12:57.905 18114-18221/org.jitsi.meet I/JitsiMeetSDK: [features/video-quality] Configured preferred receiver video frame height to: 360
2022-09-09 17:12:57.916 18114-18221/org.jitsi.meet D/JitsiMeetSDK: ExternalAPI Sending event: CONFERENCE_JOINED with data: { NativeMap: {"url":"https://meet.jit.si/gegge","isAudioMuted":false} }
2022-09-09 17:12:57.916 18114-18114/org.jitsi.meet I/JitsiMeetSDK: Conference joined: {isAudioMuted=false, url=https://meet.jit.si/gegge}
2022-09-09 17:12:57.924 18114-18114/org.jitsi.meet D/CompatibilityChangeReporter: Compat change id reported: 160794467; UID 10160; state: ENABLED
2022-09-09 17:12:57.928 18114-18221/org.jitsi.meet D/JitsiMeetSDK: [JitsiConference.js] P2P? peerCount: 1, hasBotPeer: false => true
2022-09-09 17:12:57.928 18114-18221/org.jitsi.meet D/JitsiMeetSDK: [JitsiConference.js] I'm the bigger peersId - the other peer should start P2P e4af2601 e0aa8dad
2022-09-09 17:12:57.928 18114-18251/org.jitsi.meet I/JitsiMeetSDK: AudioMode Update audio route for mode: 2
2022-09-09 17:12:57.931 18114-18114/org.jitsi.meet I/JitsiMeetSDK: JitsiMeetOngoingConferenceService Service started
2022-09-09 17:12:57.934 18114-18251/org.jitsi.meet I/JitsiMeetSDK: AudioMode Selected audio device: SPEAKER
2022-09-09 17:12:57.959 18114-18221/org.jitsi.meet D/JitsiMeetSDK: [modules/event/Jvb121EventGenerator.js] JVB121 status true => false
2022-09-09 17:12:57.959 18114-18114/org.jitsi.meet I/org.webrtc.Logging: EglRenderer: Releasing.
2022-09-09 17:12:57.959 18114-18439/org.jitsi.meet E/libEGL: call to OpenGL ES API with no current context (logged once per thread)
2022-09-09 17:12:57.959 18114-18439/org.jitsi.meet I/org.webrtc.Logging: GlShader: Deleting shader.
2022-09-09 17:12:57.959 18114-18439/org.jitsi.meet I/org.webrtc.Logging: EglRenderer: eglBase detach and release.
2022-09-09 17:12:57.962 18114-18439/org.jitsi.meet I/org.webrtc.Logging: EglRenderer: Quitting render thread.
2022-09-09 17:12:57.963 18114-18114/org.jitsi.meet I/org.webrtc.Logging: EglRenderer: Releasing done.
2022-09-09 17:12:57.964 18114-18221/org.jitsi.meet I/JitsiMeetSDK: [modules/version/ComponentsVersions.js] Got focus version: 1.0.915
2022-09-09 17:12:57.964 18114-18221/org.jitsi.meet I/JitsiMeetSDK: [JitsiConference.js] Audio unmute permissions set by Jicofo to false
2022-09-09 17:12:57.965 18114-18114/org.jitsi.meet I/org.webrtc.Logging: EglRenderer: setLayoutAspectRatio: 1.0
2022-09-09 17:12:57.966 18114-18114/org.jitsi.meet I/org.webrtc.Logging: EglRenderer: Initializing EglRenderer
2022-09-09 17:12:57.966 18114-18453/org.jitsi.meet I/org.webrtc.Logging: EglRenderer: EglBase.create shared context
2022-09-09 17:12:57.966 18114-18453/org.jitsi.meet D/HostConnection: createUnique: call
2022-09-09 17:12:57.967 18114-18453/org.jitsi.meet D/HostConnection: HostConnection::get() New Host Connection established 0xb400007253a35ed0, tid 18453
2022-09-09 17:12:57.968 18114-18453/org.jitsi.meet D/HostConnection: HostComposition ext ANDROID_EMU_CHECKSUM_HELPER_v1 ANDROID_EMU_native_sync_v2 ANDROID_EMU_native_sync_v3 ANDROID_EMU_native_sync_v4 ANDROID_EMU_dma_v1 ANDROID_EMU_direct_mem ANDROID_EMU_host_composition_v1 ANDROID_EMU_host_composition_v2 ANDROID_EMU_vulkan ANDROID_EMU_deferred_vulkan_commands ANDROID_EMU_vulkan_null_optional_strings ANDROID_EMU_vulkan_create_resources_with_requirements ANDROID_EMU_YUV_Cache ANDROID_EMU_vulkan_ignored_handles ANDROID_EMU_has_shared_slots_host_memory_allocator ANDROID_EMU_vulkan_free_memory_sync ANDROID_EMU_vulkan_shader_float16_int8 ANDROID_EMU_vulkan_async_queue_submit ANDROID_EMU_vulkan_queue_submit_with_commands ANDROID_EMU_sync_buffer_data ANDROID_EMU_read_color_buffer_dma ANDROID_EMU_hwc_multi_configs GL_OES_EGL_image_external_essl3 GL_OES_vertex_array_object GL_KHR_texture_compression_astc_ldr ANDROID_EMU_host_side_tracing ANDROID_EMU_gles_max_version_3_0 
2022-09-09 17:12:57.968 18114-18453/org.jitsi.meet I/org.webrtc.Logging: EglBase14Impl: Using OpenGL ES version 2
2022-09-09 17:12:57.969 18114-18453/org.jitsi.meet D/EGL_emulation: eglCreateContext: 0xb400007253a36ad0: maj 3 min 0 rcv 3
2022-09-09 17:12:57.972 18114-18221/org.jitsi.meet I/JitsiMeetSDK: [JitsiConference.js] Video unmute permissions set by Jicofo to false
2022-09-09 17:12:57.975 18114-18114/org.jitsi.meet I/org.webrtc.Logging: SurfaceEglRenderer: : surfaceChanged: format: 4 size: 273x273
2022-09-09 17:12:57.977 18114-18453/org.jitsi.meet D/EGL_emulation: eglMakeCurrent: 0xb400007253a36ad0: ver 3 0 (tinfo 0x746dbff280) (first time)
2022-09-09 17:12:57.985 18114-18221/org.jitsi.meet E/JitsiMeetSDK: [modules/statistics/AnalyticsAdapter.js] Required field missing (containerId, containerType, objectId or objectType)
2022-09-09 17:12:57.985 18114-18221/org.jitsi.meet E/JitsiMeetSDK: [modules/statistics/AnalyticsAdapter.js] Dropping a mis-formatted event: {"type":"track","action":"unpinned","actionSubject":"participant","objectType":"participant","attributes":{"participant_count":3},"source":"unpinned","containerType":"conference","containerId":"gegge"}
2022-09-09 17:12:57.991 18114-18221/org.jitsi.meet D/JitsiMeetSDK: ExternalAPI Sending event: PARTICIPANT_LEFT with data: { NativeMap: {"participantId":"e0aa8dad"} }
2022-09-09 17:12:57.997 18114-18114/org.jitsi.meet I/JitsiMeetSDK: Participant left: 
2022-09-09 17:12:58.001 18114-18418/org.jitsi.meet I/org.webrtc.Logging: SurfaceEglRenderer: : Reporting first rendered frame.
2022-09-09 17:12:58.001 18114-18418/org.jitsi.meet I/org.webrtc.Logging: SurfaceEglRenderer: : Reporting frame resolution changed to 640x360 with rotation 270
2022-09-09 17:12:58.003 18114-18114/org.jitsi.meet D/com.oney.WebRTCModule.WebRTCModule: First frame rendered.
2022-09-09 17:12:58.006 18114-18114/org.jitsi.meet E/org.jitsi.meet: No package ID ff found for ID 0xffffffff.
2022-09-09 17:12:58.007 18114-18114/org.jitsi.meet I/org.webrtc.Logging: EglRenderer: setMirrorHorizontally: true
2022-09-09 17:12:58.035 18114-18220/org.jitsi.meet A/libc: Fatal signal 4 (SIGILL), code 1 (ILL_ILLOPC), fault addr 0x710e778a40 in tid 18220 (mqt_js), pid 18114 (org.jitsi.meet)
2022-09-09 17:12:58.045 18114-18114/org.jitsi.meet E/org.jitsi.meet: No package ID ff found for ID 0xffffffff.
2022-09-09 17:12:58.046 18114-18114/org.jitsi.meet I/org.webrtc.Logging: EglRenderer: setMirrorHorizontally: true
2022-09-09 17:12:58.173 18114-18251/org.jitsi.meet I/JitsiMeetSDK: AudioMode Updating audio device list

**Comment by vivekMss** [comment]
![Screenshot 2022-09-09 at 5 14 36 PM](https://user-images.githubusercontent.com/112181946/189342694-346533ae-fc2e-4486-9cd5-1d2e46bb5618.png)

**Comment by saghul** [comment]
I have no idea what kills the app with SIGKILL :-/

**Comment by vivekMss** [comment]
ok Thanks but does it have anything to do with the emulator because apk is working n only effect of crash are in ios n android simulators

**Comment by saghul** [comment]
Could be, but that's not something we can fix.

**Comment by MohitGupta913** [comment]
Do we have a solution for this issue? I am facing the exact same issue.
- With hermes enable -> `java.lang.NoClassDefFoundError: com.facebook.react.jscexecutor.JSCExecutor`
- With hermes disabled -> Black screen

@saghul  Here's the logcat output when I am seeing the black screen: https://gist.github.com/MohitGupta913/b8da877cd76fb08a934a976e85a52039

**Comment by MohitGupta913** [comment]
**Update**: I was able to get rid of the crash (with Hermes enabled) by disabling JSC in jitsi sdk as mentioned here https://github.com/jitsi/jitsi-meet/issues/4971. But still, I am getting a black screen.

**Comment by saghul** [comment]
Unfortunately the logcat doesn't show anything :-/ There are no errors, some Jitsi Meet SDK initialization messages and nothing else...

**Comment by MohitGupta913** [comment]
@saghul Thanks for checking!
So, as suggested in this comment https://github.com/skrafft/react-native-jitsi-meet/issues/117#issuecomment-619988469, I removed `setTimeout` from my RN app . Now, the meet screen proceeded further and asked for permissions (camera, mic, etc) which were not happening before. But after that black screen is still there.

Here's the logcat dump: https://gist.github.com/MohitGupta913/13693631545aadcd18a04836b29c1fa1

Can you please check again, @saghul?
Thanks!

**Comment by saghul** [comment]
> 2023-01-13 15:02:29.492 22602-22700 unknown:ReactNative     com.bravia                           E  TypeError: Cannot read property 'ACTIVE' of undefined

I have no idea where that comes from, sorry. We don't maintain that RN package nor we recommend its use because it wraps our native SDK which also uses RN, resulting in lots of weird stuff.

**Comment by MohitGupta913** [comment]
Understood, no issues! Thanks for reverting.
