### ISSUE TITLE
Stuck on loading screen while leaving the meeting

### ISSUE THREAD

**Issue by vinayseasia** [jitsi/jitsi-meet#11781]
**our app using :**

Jitsi Meet version: 5.1.0
jdk 11
minSdk 26
compileSdk 32

Connecting the call successfully. 
However, when attempting to leave the call, the screen went stuck with the message "**Connecting you to meeting...**"

**Logcat trace:**

2022-07-04 15:25:14.921 11354-11817/com.elevensight.elevensight.debug I/ReactNativeJS: Running "App
2022-07-04 15:25:14.949 11354-11818/com.elevensight.elevensight.debug I/JitsiMeetSDK: [features/app] appNavigate to https://meet.jit.si
2022-07-04 15:25:14.949 11354-11818/com.elevensight.elevensight.debug I/JitsiMeetSDK: [features/base/connection] No connection found while disconnecting.
2022-07-04 15:25:14.954 11354-11818/com.elevensight.elevensight.debug I/JitsiMeetSDK: [FeatureFlags] Source name signaling: false, Send multiple video streams: false, SSRC rewriting supported: false, uses Unified plan: false
2022-07-04 15:25:14.959 11354-11818/com.elevensight.elevensight.debug D/JitsiMeetSDK: [modules/connectivity/NetworkInfo.js] updateNetworkInfo { isOnline: true }
2022-07-04 15:25:14.966 11354-11818/com.elevensight.elevensight.debug I/JitsiMeetSDK: [features/analytics] Initialized 1 analytics handlers
2022-07-04 15:25:14.966 11354-11818/com.elevensight.elevensight.debug I/JitsiMeetSDK: [features/base/media] Start muted: 
2022-07-04 15:25:14.966 11354-11818/com.elevensight.elevensight.debug D/JitsiMeetSDK: ExternalAPI Sending event: VIDEO_MUTED_CHANGED with data: { NativeMap: {"muted":0} }
2022-07-04 15:25:14.970 11354-11818/com.elevensight.elevensight.debug I/JitsiMeetSDK: [features/base/media] Start audio only set to false
2022-07-04 15:25:14.973 11354-11817/com.elevensight.elevensight.debug W/ReactNativeJS: EventEmitter.removeListener('appStateDidChange', ...): Method has been deprecated. Please instead use `remove()` on the subscription returned by `EventEmitter.addListener`.
2022-07-04 15:25:14.976 11354-11817/com.elevensight.elevensight.debug W/ReactNativeJS: EventEmitter.removeListener('@@IMMERSIVE_STATE_CHANGED', ...): Method has been deprecated. Please instead use `remove()` on the subscription returned by `EventEmitter.addListener`.
2022-07-04 15:25:15.013 11354-11818/com.elevensight.elevensight.debug W/JitsiMeetSDK: [features/base/sounds] PLAY_SOUND: no sound found for id: PARTICIPANT_LEFT_SOUND
2022-07-04 15:25:15.031 11354-11818/com.elevensight.elevensight.debug V/MediaPlayer: resetDrmState:  mDrmInfo=null mDrmProvisioningThread=null mPrepareDrmInProgress=false mActiveDrmScheme=false
2022-07-04 15:25:15.031 11354-11818/com.elevensight.elevensight.debug V/MediaPlayer: cleanDrmObj: mDrmObj=null mDrmSessionId=null
2022-07-04 15:25:15.032 11354-11818/com.elevensight.elevensight.debug V/MediaPlayer: resetDrmState:  mDrmInfo=null mDrmProvisioningThread=null mPrepareDrmInProgress=false mActiveDrmScheme=false
2022-07-04 15:25:15.032 11354-11818/com.elevensight.elevensight.debug V/MediaPlayer: cleanDrmObj: mDrmObj=null mDrmSessionId=null
2022-07-04 15:25:15.032 11354-11818/com.elevensight.elevensight.debug W/JitsiMeetSDK: [features/base/sounds] _REMOVE_AUDIO_ELEMENT: no sound for id: ASKED_TO_UNMUTE_SOUND
2022-07-04 15:25:15.036 11354-11818/com.elevensight.elevensight.debug V/MediaPlayer: resetDrmState:  mDrmInfo=null mDrmProvisioningThread=null mPrepareDrmInProgress=false mActiveDrmScheme=false
2022-07-04 15:25:15.036 11354-11818/com.elevensight.elevensight.debug V/MediaPlayer: cleanDrmObj: mDrmObj=null mDrmSessionId=null
2022-07-04 15:25:15.036 11354-11818/com.elevensight.elevensight.debug V/MediaPlayer: resetDrmState:  mDrmInfo=null mDrmProvisioningThread=null mPrepareDrmInProgress=false mActiveDrmScheme=false
2022-07-04 15:25:15.036 11354-11818/com.elevensight.elevensight.debug V/MediaPlayer: cleanDrmObj: mDrmObj=null mDrmSessionId=null
2022-07-04 15:25:15.036 11354-11818/com.elevensight.elevensight.debug W/JitsiMeetSDK: [features/base/sounds] _REMOVE_AUDIO_ELEMENT: no sound for id: PARTICIPANT_JOINED_SOUND
2022-07-04 15:25:15.040 11354-11818/com.elevensight.elevensight.debug V/MediaPlayer: resetDrmState:  mDrmInfo=null mDrmProvisioningThread=null mPrepareDrmInProgress=false mActiveDrmScheme=false
2022-07-04 15:25:15.040 11354-11818/com.elevensight.elevensight.debug V/MediaPlayer: cleanDrmObj: mDrmObj=null mDrmSessionId=null
2022-07-04 15:25:15.040 11354-11818/com.elevensight.elevensight.debug V/MediaPlayer: resetDrmState:  mDrmInfo=null mDrmProvisioningThread=null mPrepareDrmInProgress=false mActiveDrmScheme=false
2022-07-04 15:25:15.040 11354-11818/com.elevensight.elevensight.debug V/MediaPlayer: cleanDrmObj: mDrmObj=null mDrmSessionId=null
2022-07-04 15:25:15.040 11354-11818/com.elevensight.elevensight.debug W/JitsiMeetSDK: [features/base/sounds] _REMOVE_AUDIO_ELEMENT: no sound for id: PARTICIPANT_LEFT_SOUND
2022-07-04 15:25:15.041 11354-11818/com.elevensight.elevensight.debug V/MediaPlayer: resetDrmState:  mDrmInfo=null mDrmProvisioningThread=null mPrepareDrmInProgress=false mActiveDrmScheme=false
2022-07-04 15:25:15.041 11354-11818/com.elevensight.elevensight.debug V/MediaPlayer: cleanDrmObj: mDrmObj=null mDrmSessionId=null
2022-07-04 15:25:15.041 11354-11818/com.elevensight.elevensight.debug V/MediaPlayer: resetDrmState:  mDrmInfo=null mDrmProvisioningThread=null mPrepareDrmInProgress=false mActiveDrmScheme=false
2022-07-04 15:25:15.041 11354-11818/com.elevensight.elevensight.debug V/MediaPlayer: cleanDrmObj: mDrmObj=null mDrmSessionId=null
2022-07-04 15:25:15.042 11354-11818/com.elevensight.elevensight.debug W/JitsiMeetSDK: [features/base/sounds] _REMOVE_AUDIO_ELEMENT: no sound for id: INCOMING_MSG_SOUND
2022-07-04 15:25:15.043 11354-11818/com.elevensight.elevensight.debug V/MediaPlayer: resetDrmState:  mDrmInfo=null mDrmProvisioningThread=null mPrepareDrmInProgress=false mActiveDrmScheme=false
2022-07-04 15:25:15.043 11354-11818/com.elevensight.elevensight.debug V/MediaPlayer: cleanDrmObj: mDrmObj=null mDrmSessionId=null
2022-07-04 15:25:15.043 11354-11818/com.elevensight.elevensight.debug V/MediaPlayer: resetDrmState:  mDrmInfo=null mDrmProvisioningThread=null mPrepareDrmInProgress=false mActiveDrmScheme=false
2022-07-04 15:25:15.043 11354-11818/com.elevensight.elevensight.debug V/MediaPlayer: cleanDrmObj: mDrmObj=null mDrmSessionId=null
2022-07-04 15:25:15.043 11354-11818/com.elevensight.elevensight.debug W/JitsiMeetSDK: [features/base/sounds] _REMOVE_AUDIO_ELEMENT: no sound for id: KNOCKING_PARTICIPANT_SOUND
2022-07-04 15:25:15.044 11354-11818/com.elevensight.elevensight.debug V/MediaPlayer: resetDrmState:  mDrmInfo=null mDrmProvisioningThread=null mPrepareDrmInProgress=false mActiveDrmScheme=false
2022-07-04 15:25:15.044 11354-11818/com.elevensight.elevensight.debug V/MediaPlayer: cleanDrmObj: mDrmObj=null mDrmSessionId=null
2022-07-04 15:25:15.044 11354-11818/com.elevensight.elevensight.debug V/MediaPlayer: resetDrmState:  mDrmInfo=null mDrmProvisioningThread=null mPrepareDrmInProgress=false mActiveDrmScheme=false
2022-07-04 15:25:15.044 11354-11818/com.elevensight.elevensight.debug V/MediaPlayer: cleanDrmObj: mDrmObj=null mDrmSessionId=null
2022-07-04 15:25:15.045 11354-11818/com.elevensight.elevensight.debug W/JitsiMeetSDK: [features/base/sounds] _REMOVE_AUDIO_ELEMENT: no sound for id: REACTION_SOUND_LIKE_1
2022-07-04 15:25:15.046 11354-11818/com.elevensight.elevensight.debug V/MediaPlayer: resetDrmState:  mDrmInfo=null 
2022-07-04 15:25:15.073 11354-11818/com.elevensight.elevensight.debug W/JitsiMeetSDK: [features/base/sounds] _REMOVE_AUDIO_ELEMENT: no sound for id: RECORDING_ON_SOUND
2022-07-04 15:25:15.074 11354-11818/com.elevensight.elevensight.debug W/JitsiMeetSDK: [features/calendar-sync] Calendar access not granted.
2022-07-04 15:25:15.075 11354-11818/com.elevensight.elevensight.debug D/JitsiMeetSDK: [modules/RTC/RTCUtils.js] Available devices:  [ { kind: 'videoinput',
        label: '0',
        deviceId: '0',
        groupId: '',
        facing: 'environment' },
      { kind: 'videoinput',
        label: '1',
        deviceId: '1',
        groupId: '',
        facing: 'front' },
      { kind: 'audioinput',
        label: 'Audio',
        groupId: '',
        deviceId: 'audio-1' } ]
2022-07-04 15:25:15.075 11354-11354/com.elevensight.elevensight.debug I/ReactNative: [GESTURE HANDLER] Tearing down gesture handler registered for root view com.facebook.react.ReactRootView{b0403a2 V.E...... ......ID 0,0-1080,2190 #1f}
2022-07-04 15:25:15.226 11354-11818/com.elevensight.elevensight.debug I/JitsiMeetSDK: [features/base/redux] redux state persisted. ed2fffb6c516cad622f0663656e55f84 -> 9f4bdb2e0f56ac159eb9edd0aa56226c
2022-07-04 15:25:15.276 11354-11818/com.elevensight.elevensight.debug I/JitsiMeetSDK: [features/base/lib-jitsi-meet] Config loaded from https://room-daily.11sight.com/elevensighttestorg/mewishk//elevensighttestorg/config.js?room=mewishk

2022-07-04 15:25:15.276 11354-11818/com.elevensight.elevensight.debug `E/JitsiMeetSDK: [features/base/jwt] Error(InvalidTokenError){"message":"Invalid token specified: undefined is not an object (evaluating 'n.replace')","stack":"index.android.bundle:2273:93\nh@index.android.bundle:2:1586\nindex.android.bundle:2278:83\nh@index.android.bundle:2:1586\nindex.android.bundle:2260:62\nh@index.android.bundle:2:1586\nindex.android.bundle:822:146\nh@index.android.bundle:2:1586\nindex.android.bundle:789:564\nh@index.android.bundle:2:1586\nindex.android.bundle:788:91\nh@index.android.bundle:2:1586\nd@index.android.bundle:2:959\nvalue@index.android.bundle:7:1451\nol@index.android.bundle:65:56468\nFa@index.android.bundle:65:81678\nUa@index.android.bundle:65:81580\nLa@index.android.bundle:65:81345\nEa@index.android.bundle:65:78308\nEa@[native code]\nft@index.android.bundle:65:26100\n_a@index.android.bundle:65:75397\nli@index.android.bundle:65:89644\nindex.android.bundle:65:96394\nindex.android.bundle:354:647\nrun@index.android.bundle:351:761\nrunApplication@index.android.bundle:351:1832\nvalue@index.android.bundle:45:3557\nindex.android.bundle:45:674\nvalue@index.android.bundle:45:2504\nvalue@index.android.bundle:45:646\nvalue@[native code]"}`

2022-07-04 15:25:15.280 11354-11818/com.elevensight.elevensight.debug I/JitsiMeetSDK: [FeatureFlags] Source name signaling: false, Send multiple video streams: false, SSRC rewriting supported: false, uses Unified plan: false
2022-07-04 15:25:15.285 11354-11818/com.elevensight.elevensight.debug D/JitsiMeetSDK: [modules/connectivity/NetworkInfo.js] updateNetworkInfo { isOnline: true }

2022-07-04 15:25:15.285 11354-11818/com.elevensight.elevensight.debug `**E/JitsiMeetSDK: [features/base/jwt] Error(InvalidTokenError){"message":"Invalid token specified: undefined is not an object (evaluating 'n.replace')","stack":"index.android.bundle:2273:93\nh@index.android.bundle:2:1586\nindex.android.bundle:2278:83\nh@index.android.bundle:2:1586\nindex.android.bundle:2260:62\nh@index.android.bundle:2:1586\nindex.android.bundle:822:146\nh@index.android.bundle:2:1586\nindex.android.bundle:789:564\nh@index.android.bundle:2:1586\nindex.android.bundle:788:91\nh@index.android.bundle:2:1586\nd@index.android.bundle:2:959\nvalue@index.android.bundle:7:1451\nol@index.android.bundle:65:56468\nFa@index.android.bundle:65:81678\nUa@index.android.bundle:65:81580\nLa@index.android.bundle:65:81345\nEa@index.android.bundle:65:78308\nEa@[native code]\nft@index.android.bundle:65:26100\n_a@index.android.bundle:65:75397\nli@index.android.bundle:65:89644\nindex.android.bundle:65:96394\nindex.android.bundle:354:647\nrun@index.android.bundle:351:761\nrunApplication@index.android.bundle:351:1832\nvalue@index.android.bundle:45:3557\nindex.android.bundle:45:674\nvalue@index.android.bundle:45:2504\nvalue@index.android.bundle:45:646\nvalue@[native code]"}**`

**This screen has not moved.**

![Screenshot_2022-07-04-14-15-08-063_com elevensight elevensight debug](https://user-images.githubusercontent.com/1655033/177133300-ee510aec-7cb3-44ca-be4e-e4f7bdd5463a.jpg)

**Comment by vinayseasia** [comment]
### same issue with version 5.2.0-rc.3 

E/JitsiMeetSDK: Error running onHostPause, ignoring
    java.lang.AssertionError: Pausing an activity that is not the current activity, this is incorrect! Current activity: JitsiMeetActivity Paused activity: JitsiMeetActivity
        at com.facebook.infer.annotation.Assertions.assertCondition(Assertions.java:88)
        at com.facebook.react.ReactInstanceManager.onHostPause(ReactInstanceManager.java:603)
        at org.jitsi.meet.sdk.JitsiMeetActivityDelegate.onHostPause(JitsiMeetActivityDelegate.java:120)
        at org.jitsi.meet.sdk.JitsiMeetActivity.onStop(JitsiMeetActivity.java:111)
        at android.app.Instrumentation.callActivityOnStop(Instrumentation.java:1477)
        at android.app.Activity.performStop(Activity.java:8408)
        at android.app.ActivityThread.callActivityOnStop(ActivityThread.java:4987)
        at android.app.ActivityThread.performStopActivityInner(ActivityThread.java:4966)
        at android.app.ActivityThread.handleStopActivity(ActivityThread.java:5040)
        at android.app.servertransaction.TransactionExecutor.performLifecycleSequence(TransactionExecutor.java:233)
        at android.app.servertransaction.TransactionExecutor.cycleToPath(TransactionExecutor.java:201)
        at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:173)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:97)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2135)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:236)
        at android.app.ActivityThread.main(ActivityThread.java:8056)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:656)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:967)
    
    java.lang.AssertionError: Pausing an activity that is not the current activity, this is incorrect! Current activity: JitsiMeetActivity Paused activity: JitsiMeetActivity
        at com.facebook.infer.annotation.Assertions.assertCondition(Assertions.java:88)
        at com.facebook.react.ReactInstanceManager.onHostPause(ReactInstanceManager.java:603)
        at org.jitsi.meet.sdk.JitsiMeetActivityDelegate.onHostPause(JitsiMeetActivityDelegate.java:120)
        at org.jitsi.meet.sdk.JitsiMeetActivity.onStop(JitsiMeetActivity.java:111)
        at android.app.Instrumentation.callActivityOnStop(Instrumentation.java:1477)
        at android.app.Activity.performStop(Activity.java:8408)
        at android.app.ActivityThread.callActivityOnStop(ActivityThread.java:4987)
        at android.app.ActivityThread.performStopActivityInner(ActivityThread.java:4966)
        at android.app.ActivityThread.handleStopActivity(ActivityThread.java:5040)
        at android.app.servertransaction.TransactionExecutor.performLifecycleSequence(TransactionExecutor.java:233)
        at android.app.servertransaction.TransactionExecutor.cycleToPath(TransactionExecutor.java:201)
        at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:173)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:97)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2135)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:236)
        at android.app.ActivityThread.main(ActivityThread.java:8056)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:656)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:967)


 E/JitsiMeetSDK: [features/base/jwt] Error(InvalidTokenError){"message":"Invalid token specified: undefined is not an object (evaluating 'n.replace')","stack":"index.android.bundle:2402:93\nh@index.android.bundle:2:1586\nindex.android.bundle:2407:83\nh@index.android.bundle:2:1586\nindex.android.bundle:2389:62\nh@index.android.bundle:2:1586\nindex.android.bundle:852:155\nh@index.android.bundle:2:1586\nindex.android.bundle:789:595\nh@index.android.bundle:2:1586\nindex.android.bundle:788:91\nh@index.android.bundle:2:1586\nd@index.android.bundle:2:959\nvalue@index.android.bundle:7:1451\nol@index.android.bundle:65:56468\nFa@index.android.bundle:65:81678\nUa@index.android.bundle:65:81580\nLa@index.android.bundle:65:81345\nEa@index.android.bundle:65:78308\nEa@[native code]\nft@index.android.bundle:65:26100\n_a@index.android.bundle:65:75397\nli@index.android.bundle:65:89644\nindex.android.bundle:65:96394\nindex.android.bundle:354:647\nrun@index.android.bundle:351:761\nrunApplication@index.android.bundle:351:1832\nvalue@index.android.bundle:45:3557\nindex.android.bundle:45:674\nvalue@index.android.bundle:45:2504\nvalue@index.android.bundle:45:646\nvalue@[native code]"}

**Comment by saghul** [comment]
Can you please provide a small sample project to reproduce this?

**Comment by vinayseasia** [comment]
Fix, problem was on our end. Calls to the Jitsi SDK were made twice. thank you
