### ISSUE TITLE
Crash on android 12 devices when user trying to join the room

### ISSUE THREAD

**Issue by vinayseasia** [jitsi/jitsi-meet#11857]
**our app using :**

**Jitsi Meet version: 5.1.0
jdk 11
minSdk 26
compileSdk 32**

**application crashing on android 12 devices when user trying to join the room.**

**crash logs**

2022-07-13 13:10:05.479 30189-30189/com.elevensight.elevensight.debug E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.elevensight.elevensight.debug, PID: 30189
    java.lang.RuntimeException: Unable to start service org.jitsi.meet.sdk.JitsiMeetOngoingConferenceService@e6fc925 with Intent { act=JitsiMeetOngoingConferenceService:START cmp=com.elevensight.elevensight.debug/org.jitsi.meet.sdk.JitsiMeetOngoingConferenceService }: java.lang.IllegalArgumentException: com.elevensight.elevensight.debug: Targeting S+ (version 31 and above) requires that one of FLAG_IMMUTABLE or FLAG_MUTABLE be specified when creating a PendingIntent.
    Strongly consider using FLAG_IMMUTABLE, only use FLAG_MUTABLE if some functionality depends on the PendingIntent being mutable, e.g. if it needs to be used with inline replies or bubbles.
        at android.app.ActivityThread.handleServiceArgs(ActivityThread.java:5110)
        at android.app.ActivityThread.access$2200(ActivityThread.java:310)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2319)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loopOnce(Looper.java:226)
        at android.os.Looper.loop(Looper.java:313)
        at android.app.ActivityThread.main(ActivityThread.java:8663)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:567)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1135)
     Caused by: java.lang.IllegalArgumentException: com.elevensight.elevensight.debug: Targeting S+ (version 31 and above) requires that one of FLAG_IMMUTABLE or FLAG_MUTABLE be specified when creating a PendingIntent.
    Strongly consider using FLAG_IMMUTABLE, only use FLAG_MUTABLE if some functionality depends on the PendingIntent being mutable, e.g. if it needs to be used with inline replies or bubbles.
        at android.app.PendingIntent.checkFlags(PendingIntent.java:382)
        at android.app.PendingIntent.getActivityAsUser(PendingIntent.java:465)
        at android.app.PendingIntent.getActivity(PendingIntent.java:451)
        at android.app.PendingIntent.getActivity(PendingIntent.java:415)
        at org.jitsi.meet.sdk.OngoingNotification.buildOngoingConferenceNotification(OngoingNotification.java:84)
        at org.jitsi.meet.sdk.JitsiMeetOngoingConferenceService.onStartCommand(JitsiMeetOngoingConferenceService.java:91)
        at android.app.ActivityThread.handleServiceArgs(ActivityThread.java:5092)
        	... 9 more
2022-07-13 13:10:05.480 30189-30189/com.elevensight.elevensight.debug E/JitsiMeetSDK: JitsiMeetUncaughtExceptionHandler FATAL ERROR
    java.lang.RuntimeException: Unable to start service org.jitsi.meet.sdk.JitsiMeetOngoingConferenceService@e6fc925 with Intent { act=JitsiMeetOngoingConferenceService:START cmp=com.elevensight.elevensight.debug/org.jitsi.meet.sdk.JitsiMeetOngoingConferenceService }: java.lang.IllegalArgumentException: com.elevensight.elevensight.debug: Targeting S+ (version 31 and above) requires that one of FLAG_IMMUTABLE or FLAG_MUTABLE be specified when creating a PendingIntent.
    Strongly consider using FLAG_IMMUTABLE, only use FLAG_MUTABLE if some functionality depends on the PendingIntent being mutable, e.g. if it needs to be used with inline replies or bubbles.
        at android.app.ActivityThread.handleServiceArgs(ActivityThread.java:5110)
        at android.app.ActivityThread.access$2200(ActivityThread.java:310)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2319)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loopOnce(Looper.java:226)
        at android.os.Looper.loop(Looper.java:313)
        at android.app.ActivityThread.main(ActivityThread.java:8663)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:567)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1135)
     Caused by: java.lang.IllegalArgumentException: com.elevensight.elevensight.debug: Targeting S+ (version 31 and above) requires that one of FLAG_IMMUTABLE or FLAG_MUTABLE be specified when creating a PendingIntent.
    Strongly consider using FLAG_IMMUTABLE, only use FLAG_MUTABLE if some functionality depends on the PendingIntent being mutable, e.g. if it needs to be used with inline replies or bubbles.
        at android.app.PendingIntent.checkFlags(PendingIntent.java:382)
        at android.app.PendingIntent.getActivityAsUser(PendingIntent.java:465)
        at android.app.PendingIntent.getActivity(PendingIntent.java:451)
        at android.app.PendingIntent.getActivity(PendingIntent.java:415)
        at org.jitsi.meet.sdk.OngoingNotification.buildOngoingConferenceNotification(OngoingNotification.java:84)
        at org.jitsi.meet.sdk.JitsiMeetOngoingConferenceService.onStartCommand(JitsiMeetOngoingConferenceService.java:91)
        at android.app.ActivityThread.handleServiceArgs(ActivityThread.java:5092)
        	... 9 more
    
    java.lang.RuntimeException: Unable to start service org.jitsi.meet.sdk.JitsiMeetOngoingConferenceService@e6fc925 with Intent { act=JitsiMeetOngoingConferenceService:START cmp=com.elevensight.elevensight.debug/org.jitsi.meet.sdk.JitsiMeetOngoingConferenceService }: java.lang.IllegalArgumentException: com.elevensight.elevensight.debug: Targeting S+ (version 31 and above) requires that one of FLAG_IMMUTABLE or FLAG_MUTABLE be specified when creating a PendingIntent.
    Strongly consider using FLAG_IMMUTABLE, only use FLAG_MUTABLE if some functionality depends on the PendingIntent being mutable, e.g. if it needs to be used with inline replies or bubbles.
        at android.app.ActivityThread.handleServiceArgs(ActivityThread.java:5110)
        at android.app.ActivityThread.access$2200(ActivityThread.java:310)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2319)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loopOnce(Looper.java:226)
        at android.os.Looper.loop(Looper.java:313)
        at android.app.ActivityThread.main(ActivityThread.java:8663)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:567)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1135)
     Caused by: java.lang.IllegalArgumentException: com.elevensight.elevensight.debug: Targeting S+ (version 31 and above) requires that one of FLAG_IMMUTABLE or FLAG_MUTABLE be specified when creating a PendingIntent.
    Strongly consider using FLAG_IMMUTABLE, only use FLAG_MUTABLE if some functionality depends on the PendingIntent being mutable, e.g. if it needs to be used with inline replies or bubbles.
2022-07-13 13:10:05.480 30189-30189/com.elevensight.elevensight.debug E/JitsiMeetSDK:     at android.app.PendingIntent.checkFlags(PendingIntent.java:382)
        at android.app.PendingIntent.getActivityAsUser(PendingIntent.java:465)
        at android.app.PendingIntent.getActivity(PendingIntent.java:451)
        at android.app.PendingIntent.getActivity(PendingIntent.java:415)
        at org.jitsi.meet.sdk.OngoingNotification.buildOngoingConferenceNotification(OngoingNotification.java:84)
        at org.jitsi.meet.sdk.JitsiMeetOngoingConferenceService.onStartCommand(JitsiMeetOngoingConferenceService.java:91)
        at android.app.ActivityThread.handleServiceArgs(ActivityThread.java:5092)
        	... 9 more

**Comment by saghul** [comment]
This is fixed in SDK 6.0.0 I belieeve. Can you please give it a try?

**Comment by MansibR360** [comment]
> belieeve

Bro same crashing on my android 11, it start fine but after join just crash..

**Comment by saghul** [comment]
Paste the crash.

**Comment by Swapnilsimplecrm** [comment]
For Android SDK v 6.0.0

java.lang.RuntimeException: Unable to start service org.jitsi.meet.sdk.JitsiMeetOngoingConferenceService@8895689 with Intent { cmp=com.simplecrm.maisarahbank_test/org.jitsi.meet.sdk.JitsiMeetOngoingConferenceService (has extras) }: java.lang.IllegalArgumentException: Invalid notification (no valid small icon): Notification(channel=JitsiOngoingConferenceChannel pri=0 contentView=null vibrate=null sound=null defaults=0x0 flags=0xa color=0x00000000 category=call actions=2 vis=PUBLIC)



How to fix this? please let me know

**Comment by ramisalem** [comment]
for me, the crash is only in signed APK however it works fine in debug

**Comment by saghul** [comment]
Did you test SDK 6?
