### ISSUE TITLE
App crash while launching JItsiMeetActivity using sdk in native android - t.languages

### ISSUE THREAD

**Issue by abnormalbbk** [jitsi/jitsi-meet#12023]
Getting this specific crash in my only one app 

The sample application provided worked and also creating new todo project worked with both 5 and 6 jitsi android sdk versions
I am not unable to identify what is wroing with my only one app that gives the following crash

  minSdk 23
  targetSdk 32
  compileSdk 32

```
2022-08-15 18:26:05.908 21379-21630/com.mysecondteacher.nepal.mock E/ReactNativeJS: null is not an object (evaluating 't.languages')
2022-08-15 18:26:05.912 21379-21630/com.mysecondteacher.nepal.mock E/ReactNativeJS: Module AppRegistry is not a registered callable module (calling runApplication)
2022-08-15 18:26:05.917 21379-21631/com.mysecondteacher.nepal.mock E/AndroidRuntime: FATAL EXCEPTION: mqt_native_modules
    Process: com.mysecondteacher.nepal.mock, PID: 21379
    com.facebook.react.common.JavascriptException: null is not an object (evaluating 't.languages'), stack:
    <unknown>@775:191
    v@2:1474
    <unknown>@774:151
    v@2:1474
    <unknown>@772:241
    v@2:1474
    <unknown>@755:340
    v@2:1474
    <unknown>@754:133
    v@2:1474
    <unknown>@509:187
    v@2:1474
    <unknown>@372:126
    v@2:1474
    <unknown>@371:206
    v@2:1474
    <unknown>@340:226
    v@2:1474
    <unknown>@6:58
    v@2:1474
    d@2:876
    global code@1194:4
    
        at com.facebook.react.modules.core.ExceptionsManagerModule.reportException(ExceptionsManagerModule.java:72)
        at com.facebook.react.modules.core.ExceptionsManagerModule.reportFatalException(ExceptionsManagerModule.java:49)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.facebook.react.bridge.JavaMethodWrapper.invoke(JavaMethodWrapper.java:372)
        at com.facebook.react.bridge.JavaModuleWrapper.invoke(JavaModuleWrapper.java:188)
        at com.facebook.react.bridge.queue.NativeRunnable.run(Native Method)
        at android.os.Handler.handleCallback(Handler.java:938)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:27)
        at android.os.Looper.loopOnce(Looper.java:201)
        at android.os.Looper.loop(Looper.java:288)
        at com.facebook.react.bridge.queue.MessageQueueThreadImpl$4.run(MessageQueueThreadImpl.java:228)
        at java.lang.Thread.run(Thread.java:920)
```

- Jitsi Meet version: Tested with both version 6 and 5 jitsi sdk

**Comment by abnormalbbk** [comment]
Fixed this issue
deleting index.android.bundle in the main assets folder resolved this issue :)
