### ISSUE TITLE
Android App crash when meeting starts 

### ISSUE THREAD

**Issue by Ashish-100-tiwari** [jitsi/jitsi-meet#12156]
### Description:
I have build and android app in java(16.0.2) with  minSdk 23 , compileSdk 32 and  run on the vivo model number 1814 android version 8.1.0 ROM funtouch OS_4.5 . It get crashed within a few minutes 

###Code 
public class DashboardActivity extends AppCompatActivity {
    EditText secreteCodebox;
    Button joinBtn, shareBtn;

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_dashboard);

        secreteCodebox =findViewById(R.id.codeBox);
        joinBtn=findViewById(R.id.joinBtn);
        shareBtn = findViewById(R.id.shareBtn);

        URL serverURL;

        try {
            serverURL = new URL("https://meet.jit.si");
            JitsiMeetConferenceOptions defaultOptions =
                    new JitsiMeetConferenceOptions.Builder()
                            .setServerURL(serverURL)
                            .setWelcomePageEnabled(false)
                            .build();
            JitsiMeet.setDefaultConferenceOptions(defaultOptions);
        } catch (MalformedURLException e) {
            e.printStackTrace();
        }

        joinBtn.setOnClickListener(new View.OnClickListener() {
            @Override
            public void onClick(View v) {
                JitsiMeetConferenceOptions options = new JitsiMeetConferenceOptions.Builder()
                        .setRoom(secreteCodebox.getText().toString())
                        .setWelcomePageEnabled(false)
                        .build();

                JitsiMeetActivity.launch(DashboardActivity.this, options);
            }
        });

    }
}

### Steps to reproduce:

1.  After clicking on Join meeting 
2. shown progress bar 
3.  get closed and return to the main activity

### Expected behavior:

Start the app with full efficiency 
.setWelcomePageEnabled(false) is also not supporting 
### Server information:

- Jitsi Meet version: implementation ('org.jitsi.react:jitsi-meet-sdk:+') { transitive = true }
- Operating System:

### Client information:

- Browser / app version: android version 8.1.0
- Operating System: Funtouch OS_4.5

**Comment by saghul** [comment]
Can you paste the crash log? Also please pin your depende y instead of using +, that is a bad idea. The latest version as of today is 6.1.0.

**Comment by Ashish-100-tiwari** [comment]
In the log section : 2022-09-12 02:08:27.948 15363-15363/com.example.videocall E/: nFreeSize: 35069898752
I found just 1 error , that is actually not useful . 
I have add the dependence according to the documentation : https://jitsi.github.io/handbook/docs/dev-guide/dev-guide-android-sdk/ 
And .setWelcomePageEnabled(false) is also not working showing error 
@saghul

**Comment by saghul** [comment]
That guide also says "Make sure you pin your dependency by checking the releases page."

So did you set it to 6.1.0?

Please paste the entire log on a gist and link it here.

**Comment by Ashish-100-tiwari** [comment]
dependency changed 
log :
2022-09-12 09:38:46.615 9131-9131/com.example.videocall I/zygote64: The ClassLoaderContext is a special shared library.
2022-09-12 09:38:46.619 9131-9131/com.example.videocall I/zygote64: The ClassLoaderContext is a special shared library.
2022-09-12 09:38:46.455 9131-9131/? I/zygote64: Late-enabling -Xcheck:jni
2022-09-12 09:38:46.744 9131-9131/com.example.videocall I/FirebaseApp: Device unlocked: initializing all Firebase APIs for app [DEFAULT]
2022-09-12 09:38:46.790 9131-9163/com.example.videocall W/zygote64: Unsupported class loader
2022-09-12 09:38:46.794 9131-9163/com.example.videocall W/zygote64: Skipping duplicate class check due to unsupported classloader
2022-09-12 09:38:46.799 9131-9163/com.example.videocall I/DynamiteModule: Considering local module com.google.android.gms.measurement.dynamite:83 and remote module com.google.android.gms.measurement.dynamite:75
2022-09-12 09:38:46.799 9131-9163/com.example.videocall I/DynamiteModule: Selected local version of com.google.android.gms.measurement.dynamite
2022-09-12 09:38:46.856 9131-9131/com.example.videocall D/FirebaseAuth: Notifying id token listeners about user ( fwiftAwywQa0mtldTPOmmVApMVO2 ).
2022-09-12 09:38:46.866 9131-9131/com.example.videocall I/FirebaseInitProvider: FirebaseApp initialization successful
2022-09-12 09:38:46.884 9131-9131/com.example.videocall D/org.jitsi.meet.sdk.JitsiInitializer: create
2022-09-12 09:38:46.959 9131-9166/com.example.videocall V/FA: App measurement collection enabled
2022-09-12 09:38:46.961 9131-9166/com.example.videocall V/FA: App measurement enabled for app package, google app id: com.example.videocall, 1:528125936345:android:73425429fff8d59737f4c8
2022-09-12 09:38:46.964 9131-9166/com.example.videocall I/FA: App measurement initialized, version: 73000
2022-09-12 09:38:46.964 9131-9166/com.example.videocall I/FA: To enable debug logging run: adb shell setprop log.tag.FA VERBOSE
2022-09-12 09:38:46.965 9131-9166/com.example.videocall I/FA: To enable faster debug mode event logging run:
      adb shell setprop debug.firebase.analytics.app com.example.videocall
2022-09-12 09:38:46.965 9131-9166/com.example.videocall D/FA: Debug-level message logging enabled
2022-09-12 09:38:46.966 9131-9136/com.example.videocall I/zygote64: Do partial code cache collection, code=30KB, data=20KB
2022-09-12 09:38:46.966 9131-9136/com.example.videocall I/zygote64: After code cache collection, code=29KB, data=20KB
2022-09-12 09:38:46.966 9131-9136/com.example.videocall I/zygote64: Increasing code cache capacity to 128KB
2022-09-12 09:38:47.044 9131-9131/com.example.videocall I/FtBuild: getRomVersion mRomVer=4.5
2022-09-12 09:38:47.071 9131-9166/com.example.videocall V/FA: Connecting to remote service
2022-09-12 09:38:47.085 9131-9163/com.example.videocall V/FA: onActivityCreated
2022-09-12 09:38:47.104 9131-9166/com.example.videocall V/FA: Connection attempt already in progress
2022-09-12 09:38:47.106 9131-9131/com.example.videocall D/PhoneWindow: DEBUG_ALIENSCREEN:getRotation mRotation=0
2022-09-12 09:38:47.121 9131-9131/com.example.videocall I/DecorView: setWindowBackground mBackgroundPadding = Rect(0, 0 - 0, 0), mFramePadding = Rect(0, 0 - 0, 0), pkg = com.example.videocall
2022-09-12 09:38:47.121 9131-9166/com.example.videocall V/FA: Connection attempt already in progress
2022-09-12 09:38:47.444 9131-9131/com.example.videocall D/skia_mt: canRunInCoworker = true
2022-09-12 09:38:47.572 9131-9136/com.example.videocall I/zygote64: Do partial code cache collection, code=57KB, data=50KB
2022-09-12 09:38:47.573 9131-9136/com.example.videocall I/zygote64: After code cache collection, code=57KB, data=50KB
2022-09-12 09:38:47.573 9131-9136/com.example.videocall I/zygote64: Increasing code cache capacity to 256KB
2022-09-12 09:38:47.574 9131-9136/com.example.videocall I/zygote64: Compiler allocated 8MB to compile void android.widget.TextView.<init>(android.content.Context, android.util.AttributeSet, int, int)
2022-09-12 09:38:47.587 9131-9166/com.example.videocall V/FA: Activity resumed, time: 1529703053
2022-09-12 09:38:47.596 9131-9131/com.example.videocall I/SurfaceFactory: [static] sSurfaceFactory = com.mediatek.view.impl.SurfaceFactoryImpl@da27e6d
2022-09-12 09:38:47.597 9131-9166/com.example.videocall I/FA: Tag Manager is not found and thus will not be used
2022-09-12 09:38:47.606 9131-9131/com.example.videocall D/WindowClient: Add to mViews: DecorView@af896f0[DashboardActivity], this = android.view.WindowManagerGlobal@7759469
2022-09-12 09:38:47.608 9131-9131/com.example.videocall D/OpenGLRenderer: Dumper init 4 threads <0x6f84ab7a80>
2022-09-12 09:38:47.608 9131-9131/com.example.videocall D/OpenGLRenderer: <com.example.videocall> is running.
2022-09-12 09:38:47.610 9131-9188/com.example.videocall D/OpenGLRenderer: HWUI GL Pipeline
2022-09-12 09:38:47.614 9131-9131/com.example.videocall D/ViewRootImpl[DashboardActivity]: hardware acceleration = true , fakeHwAccelerated = false, sRendererDisabled = false, forceHwAccelerated = false, sSystemRendererDisabled = false
2022-09-12 09:38:47.628 9131-9131/com.example.videocall V/PhoneWindow: DecorView setVisiblity: visibility = 0, Parent = ViewRoot{d68321c com.example.videocall/com.example.videocall.DashboardActivity,ident = 0}, this = DecorView@af896f0[DashboardActivity]
2022-09-12 09:38:47.648 9131-9166/com.example.videocall V/FA: Connection attempt already in progress
2022-09-12 09:38:47.648 9131-9166/com.example.videocall V/FA: Connection attempt already in progress
2022-09-12 09:38:47.660 9131-9131/com.example.videocall I/TouchMotionHandler: handler onAttached
2022-09-12 09:38:47.690 9131-9178/com.example.videocall E/: nFreeSize: 35114459136
2022-09-12 09:38:47.776 9131-9131/com.example.videocall D/Surface: Surface::allocateBuffers(this=0x6f73bef000)
2022-09-12 09:38:47.777 9131-9131/com.example.videocall W/RenderThread: type=1400 audit(0.0:645612): avc: denied { search } for name="clients" dev="debugfs" ino=6298 scontext=u:r:untrusted_app:s0:c512,c768 tcontext=u:object_r:debugfs_ion:s0 tclass=dir permissive=0
2022-09-12 09:38:47.786 9131-9188/com.example.videocall I/zygote64: android::hardware::configstore::V1_0::ISurfaceFlingerConfigs::hasWideColorDisplay retrieved: 0
2022-09-12 09:38:47.787 9131-9188/com.example.videocall I/OpenGLRenderer: Initialized EGL, version 1.4
2022-09-12 09:38:47.787 9131-9188/com.example.videocall D/OpenGLRenderer: Swap behavior 2
2022-09-12 09:38:47.805 9131-9188/com.example.videocall D/OpenGLRenderer: [init] completed
2022-09-12 09:38:47.805 9131-9188/com.example.videocall D/HWUIExtension: MTKProgramCache.init: enable enhancement 1
2022-09-12 09:38:47.805 9131-9188/com.example.videocall I/HWUIExtension: Get disable program binary service property (0)
2022-09-12 09:38:47.805 9131-9188/com.example.videocall I/HWUIExtension: Initializing program atlas...
2022-09-12 09:38:47.806 9131-9188/com.example.videocall I/ProgramBinary/Service: ProgramBinaryService client side disable debugging.
2022-09-12 09:38:47.806 9131-9188/com.example.videocall I/ProgramBinary/Service: ProgramBinaryService client side disable binary content debugging.
2022-09-12 09:38:47.806 9131-9188/com.example.videocall D/ProgramBinary/Service: BpProgramBinaryService.getReady
2022-09-12 09:38:47.806 9131-9188/com.example.videocall D/ProgramBinary/Service: zhiyin- 1 BpProgramBinaryService::getReady()
2022-09-12 09:38:47.807 9131-9188/com.example.videocall D/ProgramBinary/Service: zhiyin- 2 BpProgramBinaryService::getReady()
2022-09-12 09:38:47.807 9131-9188/com.example.videocall D/ProgramBinary/Service: BpProgramBinaryService.getProgramBinaryData
2022-09-12 09:38:47.807 9131-9188/com.example.videocall I/HWUIExtension: Program binary detail: Binary length is 314156, program map length is 104.
2022-09-12 09:38:47.807 9131-9188/com.example.videocall I/HWUIExtension: Succeeded to mmap program binaries. File descriptor is 68, and path is /dev/ashmem.
2022-09-12 09:38:47.807 9131-9188/com.example.videocall I/HWUIExtension: No need to use file discriptor anymore, close fd(68).
2022-09-12 09:38:47.808 9131-9188/com.example.videocall D/HWUIExtension: Dumper init 4 threads <0x6f73be8300>
2022-09-12 09:38:47.808 9131-9188/com.example.videocall D/HWUIExtension: <com.example.videocall> is running.
2022-09-12 09:38:47.808 9131-9188/com.example.videocall D/HWUIExtension: Initializing program cache from 0x0, size = -1
2022-09-12 09:38:47.809 9131-9188/com.example.videocall D/Surface: Surface::connect(this=0x6f73bef000,api=1)
2022-09-12 09:38:47.893 9131-9188/com.example.videocall D/GraphicBuffer: register, handle(0x6f84a84bc0) (w:720 h:1520 s:736 f:0x1 u:b00)
2022-09-12 09:38:47.911 9131-9188/com.example.videocall D/HWUIExtension: MTKProgramCache.generateProgram: 0
2022-09-12 09:38:47.913 9131-9188/com.example.videocall D/HWUIExtension: createProgram 0x0000000000000000, binary 0x6f73c56000, length 10736, format 37168 within 1449ns
2022-09-12 09:38:47.914 9131-9188/com.example.videocall D/HWUIExtension: MTKProgramCache.generateProgram: 240518168576
2022-09-12 09:38:47.915 9131-9188/com.example.videocall D/HWUIExtension: createProgram 0x0000003800000000, binary 0x6f73c5b661, length 11450, format 37168 within 498ns
2022-09-12 09:38:47.916 9131-9188/com.example.videocall D/HWUIExtension: MTKProgramCache.generateProgram: 8864812498944
2022-09-12 09:38:47.916 9131-9188/com.example.videocall D/HWUIExtension: createProgram 0x0000081000000000, binary 0x6f73c7e4f2, length 12999, format 37168 within 434ns
2022-09-12 09:38:47.918 9131-9188/com.example.videocall D/HWUIExtension: MTKProgramCache.generateProgram: 8796098265152
2022-09-12 09:38:47.920 9131-9188/com.example.videocall D/HWUIExtension: MTKProgramCache.generateProgram: 571746046443521
2022-09-12 09:38:47.921 9131-9188/com.example.videocall D/HWUIExtension: MTKProgramCache.generateProgram: 571780406181891
2022-09-12 09:38:47.922 9131-9188/com.example.videocall D/HWUIExtension: createProgram 0x0002080800000003, binary 0x6f73c8b871, length 13341, format 37168 within 421ns
2022-09-12 09:38:47.924 9131-9188/com.example.videocall D/HWUIExtension: MTKProgramCache.generateProgram: 9036611190784
2022-09-12 09:38:47.926 9131-9188/com.example.videocall D/HWUIExtension: MTKProgramCache.generateProgram: 8864817741888
2022-09-12 09:38:47.928 9131-9188/com.example.videocall D/HWUIExtension: MTKProgramCache.generateProgram: 1064327255687169
2022-09-12 09:38:47.931 9131-9188/com.example.videocall D/HWUIExtension: MTKProgramCache.generateProgram: 562949958664257
2022-09-12 09:38:47.931 9131-9188/com.example.videocall D/HWUIExtension: createProgram 0x0002000000500041, binary 0x6f73c63be3, length 11847, format 37168 within 431ns
2022-09-12 09:38:47.932 9131-9188/com.example.videocall D/HWUIExtension: MTKProgramCache.generateProgram: 562984313159683
2022-09-12 09:38:47.933 9131-9188/com.example.videocall D/HWUIExtension: createProgram 0x0002000800000003, binary 0x6f73c6958b, length 11447, format 37168 within 379ns
2022-09-12 09:38:47.940 9131-9131/com.example.videocall D/SurfaceExt: callingApp: com.example.videocall
2022-09-12 09:38:47.940 9131-9131/com.example.videocall D/SurfaceExt: ENABLE_WHITE_LIST: false,isInWhiteList: false
2022-09-12 09:38:47.941 9131-9131/com.example.videocall D/Surface: lockCanvas
2022-09-12 09:38:47.941 9131-9131/com.example.videocall D/Surface: Surface::connect(this=0x6f73a82000,api=2)
2022-09-12 09:38:47.943 9131-9131/com.example.videocall D/GraphicBuffer: register, handle(0x6f84a848c0) (w:1 h:1 s:32 f:0x1 u:933)
2022-09-12 09:38:47.946 9131-9131/com.example.videocall D/SurfaceExt: callingApp: com.example.videocall
2022-09-12 09:38:47.946 9131-9131/com.example.videocall D/SurfaceExt: ENABLE_WHITE_LIST: false,isInWhiteList: false
2022-09-12 09:38:47.946 9131-9131/com.example.videocall D/Surface: lockCanvas
2022-09-12 09:38:47.946 9131-9131/com.example.videocall D/Surface: Surface::connect(this=0x6f73a83000,api=2)
2022-09-12 09:38:47.949 9131-9131/com.example.videocall D/GraphicBuffer: register, handle(0x6f84a848c0) (w:1 h:1 s:32 f:0x1 u:933)
2022-09-12 09:38:47.979 9131-9166/com.example.videocall D/FA: Connected to remote service
2022-09-12 09:38:47.982 9131-9166/com.example.videocall V/FA: Processing queued up service tasks: 5
2022-09-12 09:38:47.992 9131-9136/com.example.videocall I/zygote64: Do full code cache collection, code=123KB, data=89KB
2022-09-12 09:38:47.993 9131-9136/com.example.videocall I/zygote64: After code cache collection, code=105KB, data=60KB
2022-09-12 09:38:48.003 9131-9188/com.example.videocall D/GraphicBuffer: register, handle(0x6f84a85dc0) (w:720 h:1520 s:736 f:0x1 u:b00)
2022-09-12 09:38:48.011 9131-9131/com.example.videocall D/SurfaceExt: callingApp: com.example.videocall
2022-09-12 09:38:48.011 9131-9131/com.example.videocall D/SurfaceExt: ENABLE_WHITE_LIST: false,isInWhiteList: false
2022-09-12 09:38:48.011 9131-9131/com.example.videocall D/Surface: lockCanvas
2022-09-12 09:38:48.013 9131-9131/com.example.videocall D/GraphicBuffer: register, handle(0x6f84a848c0) (w:1 h:1 s:32 f:0x1 u:933)
2022-09-12 09:38:48.014 9131-9131/com.example.videocall D/SurfaceExt: callingApp: com.example.videocall
2022-09-12 09:38:48.014 9131-9131/com.example.videocall D/SurfaceExt: ENABLE_WHITE_LIST: false,isInWhiteList: false
2022-09-12 09:38:48.014 9131-9131/com.example.videocall D/Surface: lockCanvas
2022-09-12 09:38:48.471 9131-9188/com.example.videocall D/GraphicBuffer: register, handle(0x6f84a85dc0) (w:720 h:1520 s:736 f:0x1 u:b00)
2022-09-12 09:38:51.484 9131-9136/com.example.videocall I/zygote64: Do partial code cache collection, code=124KB, data=76KB
2022-09-12 09:38:51.484 9131-9136/com.example.videocall I/zygote64: After code cache collection, code=124KB, data=76KB
2022-09-12 09:38:51.484 9131-9136/com.example.videocall I/zygote64: Increasing code cache capacity to 512KB
2022-09-12 09:38:53.100 9131-9166/com.example.videocall V/FA: Inactivity, disconnecting from the service

**Comment by saghul** [comment]
I see no crash there. How does the problem manifest?

**Comment by Ashish-100-tiwari** [comment]
https://user-images.githubusercontent.com/80841006/189582397-42a25070-dbaa-4874-a6e2-6ff60436f07a.mp4

I have also updated the libraries but still same issue .  here is the source code : https://github.com/Ashish-100-tiwari/Video-Calling-App-
This is the simple login activity ,sign up activity and one dashboard

**Comment by saghul** [comment]
Can you get the full log? That's not what you sent earlier, there not a single log line coming from the SDK.

**Comment by 09Arul** [comment]
I am also facing  this issues  with regards to Vivo phones with regards to Android 10 when I update the os version  it works  for me

**Comment by 09Arul** [comment]
AudioDeviceHandlerConnectionService Failed to unmute the microphone java.lang.RuntimeException: android.os.DeadSystemException



In logcat it is showing  this things only

**Comment by saghul** [comment]
Please show us the full logcat. That exception happens when Android itself dies: https://developer.android.com/reference/android/os/DeadSystemException looks like an Android bug, apps should not kill the system.

**Comment by 09Arul** [comment]
@saghul 

2022-09-30 10:09:09.518 17178-17208/com.example.myjitsimeet E/OpenGLRenderer: JankTracker::calculateLegacyJank expectedDequeueDuration > 0 expectedDequeueDuration=348526, DequeueBufferDuration=4621354, forgiveAmount=348526, totalDuration=11002531
2022-09-30 10:09:09.568 17178-17208/com.example.myjitsimeet E/OpenGLRenderer: JankTracker::calculateLegacyJank expectedDequeueDuration > 0 expectedDequeueDuration=973459, DequeueBufferDuration=3356928, forgiveAmount=973459, totalDuration=7758395
2022-09-30 10:09:09.586 17178-17208/com.example.myjitsimeet E/OpenGLRenderer: JankTracker::calculateLegacyJank expectedDequeueDuration > 0 expectedDequeueDuration=942066, DequeueBufferDuration=3484062, forgiveAmount=942066, totalDuration=8003316
2022-09-30 10:09:09.603 17178-17208/com.example.myjitsimeet E/OpenGLRenderer: JankTracker::calculateLegacyJank expectedDequeueDuration > 0 expectedDequeueDuration=632610, DequeueBufferDuration=3581771, forgiveAmount=632610, totalDuration=8781081
2022-09-30 10:09:20.451 17178-17211/com.example.myjitsimeet E/OpenGLRenderer: JankTracker::calculateLegacyJank expectedDequeueDuration > 0 expectedDequeueDuration=1037484, DequeueBufferDuration=1085573, forgiveAmount=1037484, totalDuration=5896543
2022-09-30 10:09:20.466 17178-17211/com.example.myjitsimeet E/OpenGLRenderer: JankTracker::calculateLegacyJank expectedDequeueDuration > 0 expectedDequeueDuration=783188, DequeueBufferDuration=1795313, forgiveAmount=783188, totalDuration=7083884
2022-09-30 10:09:20.499 17178-17211/com.example.myjitsimeet E/OpenGLRenderer: JankTracker::calculateLegacyJank expectedDequeueDuration > 0 expectedDequeueDuration=464404, DequeueBufferDuration=1046719, forgiveAmount=464404, totalDuration=7803015
2022-09-30 10:09:22.417 17178-17207/com.example.myjitsimeet E/OpenGLRenderer: JankTracker::calculateLegacyJank expectedDequeueDuration > 0 expectedDequeueDuration=2091276, DequeueBufferDuration=3690990, forgiveAmount=2091276, totalDuration=23377551
2022-09-30 10:09:22.855 17178-17178/com.example.myjitsimeet E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.example.myjitsimeet, PID: 17178
    java.lang.RuntimeException: Unable to start service org.jitsi.meet.sdk.JitsiMeetOngoingConferenceService@4ed623b with Intent { cmp=com.example.myjitsimeet/org.jitsi.meet.sdk.JitsiMeetOngoingConferenceService (has extras) }: java.lang.IllegalArgumentException: Invalid notification (no valid small icon): Notification(channel=JitsiOngoingConferenceChannel shortcut=null contentView=null vibrate=null sound=null defaults=0x0 flags=0xa color=0x00000000 category=call actions=2 vis=PUBLIC internalType=0 internalPriority=0 internalGroupPriority=0 internalFlag=0)
        at android.app.ActivityThread.handleServiceArgs(ActivityThread.java:4989)
        at android.app.ActivityThread.access$2300(ActivityThread.java:284)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2322)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loopOnce(Looper.java:233)
        at android.os.Looper.loop(Looper.java:334)
        at android.app.ActivityThread.main(ActivityThread.java:8399)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:582)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1068)
     Caused by: java.lang.IllegalArgumentException: Invalid notification (no valid small icon): Notification(channel=JitsiOngoingConferenceChannel shortcut=null contentView=null vibrate=null sound=null defaults=0x0 flags=0xa color=0x00000000 category=call actions=2 vis=PUBLIC internalType=0 internalPriority=0 internalGroupPriority=0 internalFlag=0)
        at android.app.NotificationManager.fixNotification(NotificationManager.java:724)
        at android.app.NotificationManager.notifyAsUser(NotificationManager.java:703)
        at android.app.NotificationManager.notify(NotificationManager.java:652)
        at android.app.NotificationManager.notify(NotificationManager.java:628)
        at org.jitsi.meet.sdk.JitsiMeetOngoingConferenceService.onStartCommand(JitsiMeetOngoingConferenceService.java:135)
        at android.app.ActivityThread.handleServiceArgs(ActivityThread.java:4971)
        at android.app.ActivityThread.access$2300(ActivityThread.java:284) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2322) 
        at android.os.Handler.dispatchMessage(Handler.java:106) 
        at android.os.Looper.loopOnce(Looper.java:233) 
        at android.os.Looper.loop(Looper.java:334) 
        at android.app.ActivityThread.main(ActivityThread.java:8399) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:582) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1068) 
2022-09-30 10:09:22.869 17178-17178/com.example.myjitsimeet E/JitsiMeetSDK: JitsiMeetUncaughtExceptionHandler FATAL ERROR
    java.lang.RuntimeException: Unable to start service org.jitsi.meet.sdk.JitsiMeetOngoingConferenceService@4ed623b with Intent { cmp=com.example.myjitsimeet/org.jitsi.meet.sdk.JitsiMeetOngoingConferenceService (has extras) }: java.lang.IllegalArgumentException: Invalid notification (no valid small icon): Notification(channel=JitsiOngoingConferenceChannel shortcut=null contentView=null vibrate=null sound=null defaults=0x0 flags=0xa color=0x00000000 category=call actions=2 vis=PUBLIC internalType=0 internalPriority=0 internalGroupPriority=0 internalFlag=0)
        at android.app.ActivityThread.handleServiceArgs(ActivityThread.java:4989)
        at android.app.ActivityThread.access$2300(ActivityThread.java:284)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2322)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loopOnce(Looper.java:233)
        at android.os.Looper.loop(Looper.java:334)
        at android.app.ActivityThread.main(ActivityThread.java:8399)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:582)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1068)
     Caused by: java.lang.IllegalArgumentException: Invalid notification (no valid small icon): Notification(channel=JitsiOngoingConferenceChannel shortcut=null contentView=null vibrate=null sound=null defaults=0x0 flags=0xa color=0x00000000 category=call actions=2 vis=PUBLIC internalType=0 internalPriority=0 internalGroupPriority=0 internalFlag=0)
        at android.app.NotificationManager.fixNotification(NotificationManager.java:724)
        at android.app.NotificationManager.notifyAsUser(NotificationManager.java:703)
        at android.app.NotificationManager.notify(NotificationManager.java:652)
        at android.app.NotificationManager.notify(NotificationManager.java:628)
        at org.jitsi.meet.sdk.JitsiMeetOngoingConferenceService.onStartCommand(JitsiMeetOngoingConferenceService.java:135)
        at android.app.ActivityThread.handleServiceArgs(ActivityThread.java:4971)
        at android.app.ActivityThread.access$2300(ActivityThread.java:284) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2322) 
        at android.os.Handler.dispatchMessage(Handler.java:106) 
        at android.os.Looper.loopOnce(Looper.java:233) 
        at android.os.Looper.loop(Looper.java:334) 
        at android.app.ActivityThread.main(ActivityThread.java:8399) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:582) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1068) 
    
    java.lang.RuntimeException: Unable to start service org.jitsi.meet.sdk.JitsiMeetOngoingConferenceService@4ed623b with Intent { cmp=com.example.myjitsimeet/org.jitsi.meet.sdk.JitsiMeetOngoingConferenceService (has extras) }: java.lang.IllegalArgumentException: Invalid notification (no valid small icon): Notification(channel=JitsiOngoingConferenceChannel shortcut=null contentView=null vibrate=null sound=null defaults=0x0 flags=0xa color=0x00000000 category=call actions=2 vis=PUBLIC internalType=0 internalPriority=0 internalGroupPriority=0 internalFlag=0)
        at android.app.ActivityThread.handleServiceArgs(ActivityThread.java:4989)
        at android.app.ActivityThread.access$2300(ActivityThread.java:284)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2322)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loopOnce(Looper.java:233)
        at android.os.Looper.loop(Looper.java:334)
        at android.app.ActivityThread.main(ActivityThread.java:8399)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:582)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1068)
     Caused by: java.lang.IllegalArgumentException: Invalid notification (no valid small icon): Notification(channel=JitsiOngoingConferenceChannel shortcut=null contentView=null vibrate=null sound=null defaults=0x0 flags=0xa color=0x00000000 category=call actions=2 vis=PUBLIC internalType=0 internalPriority=0 internalGroupPriority=0 internalFlag=0)
        at android.app.NotificationManager.fixNotification(NotificationManager.java:724)
        at android.app.NotificationManager.notifyAsUser(NotificationManager.java:703)
        at android.app.NotificationManager.notify(NotificationManager.java:652)
        at android.app.NotificationManager.notify(NotificationManager.java:628)
2022-09-30 10:09:22.869 17178-17178/com.example.myjitsimeet E/JitsiMeetSDK:     at org.jitsi.meet.sdk.JitsiMeetOngoingConferenceService.onStartCommand(JitsiMeetOngoingConferenceService.java:135)
        at android.app.ActivityThread.handleServiceArgs(ActivityThread.java:4971)
        	... 9 more

**Comment by saghul** [comment]
> Caused by: java.lang.IllegalArgumentException: Invalid notification (no valid small icon): 

You need to set the small notification icon.

**Comment by 09Arul** [comment]
How to do that can you please help me out on this thanks in advance

**Comment by saghul** [comment]
Add an `ic_notification` drawable like this one: https://github.com/jitsi/jitsi-meet/blob/master/android/app/src/main/res/drawable-xxxhdpi/ic_notification.png Android Studio has an icon generator.

**Comment by AmitrajitDas** [comment]
> I have also updated the libraries but still same issue . here is the source code : https://github.com/Ashish-100-tiwari/Video-Calling-App- This is the simple login activity ,sign up activity and one dashboard

Facing the same issue in my Ionic-React application with minSdk 23 and compileSdk 31. Were you able to fix this?

**Comment by Shadows7010** [comment]
same problem help me bros 
@AmitrajitDas 
@saghul 
@09Arul

**Comment by saghul** [comment]
See my comment above.

**Comment by Shadows7010** [comment]
> Can you paste the crash log? Also please pin your depende y instead of using +, that is a bad idea. The latest version as of today is 6.1.0.

i am using 7.0.1 (y means bro)

**Comment by Shadows7010** [comment]
> Add an `ic_notification` drawable like this one: https://github.com/jitsi/jitsi-meet/blob/master/android/app/src/main/res/drawable-xxxhdpi/ic_notification.png Android Studio has an icon generator.

this msg i dont understand bro

**Comment by Shadows7010** [comment]
> See my comment above.

all cmt see bro  
i have no idea?
