### ISSUE TITLE
dpkg on debian buster fails due to zstd compressed files in lua-basexx and lua-cjson

### ISSUE THREAD

**Issue by WhoAmI0501** [jitsi/jitsi-meet#12208]
### Description:

I recently updated my Jitsi Meet installation on a debian buster system, where the packages lua-basexx and lua-cjson (which are coming out of the jitsi repository) returned some apt failures. Those are triggered due a incompatibiliy - the mentioned packages are shipping zstd compressed files, which are from my knownledge are currently only supported on the dpkg of Ubuntu - but not on debians dpkg.

### Steps to reproduce:

1. Install Jitsi Meet on a debian buster based system

### Expected behavior:

dpkg should be able to decompress the delivered deb packages

### Actual behavior:

dpkg fails to decompress the zstd compressed files in the packages lua-basexx_0.4.1-jitsi1_all.deb and lua-cjson_2.1.0.10-jitsi1_amd64.deb

### Server information:

- Jitsi Meet version: 2.0.7648-1
- Operating System: Debian 10 (buster)

### Client information:

- Browser / app version: -
- Operating System: -

### Additional information:

```bash
root@jitsi:~# apt upgrade
Paketlisten werden gelesen... Fertig
Abhängigkeitsbaum wird aufgebaut.       
Statusinformationen werden eingelesen.... Fertig
Paketaktualisierung (Upgrade) wird berechnet... Fertig
Die folgenden Pakete werden aktualisiert (Upgrade):
  lua-basexx lua-cjson
2 aktualisiert, 0 neu installiert, 0 zu entfernen und 0 nicht aktualisiert.
Es müssen 26,8 kB an Archiven heruntergeladen werden.
Nach dieser Operation werden 105 kB Plattenplatz zusätzlich benutzt.
Möchten Sie fortfahren? [J/n] y
Holen:1 https://download.jitsi.org stable/ lua-basexx 0.4.1-jitsi1 [4.284 B]  
Holen:2 https://download.jitsi.org stable/ lua-cjson 2.1.0.10-jitsi1 [22,5 kB]
Es wurden 26,8 kB in 1 s geholt (24,7 kB/s).
dpkg-deb: Fehler: Archiv »/var/cache/apt/archives/lua-basexx_0.4.1-jitsi1_all.deb« verwendet unbekannte Komprimierung für Element »control.tar.zst«, Abbruch
Traceback (most recent call last):
  File "/usr/share/apt-listchanges/DebianFiles.py", line 124, in readdeb
    output = subprocess.check_output(command)
  File "/usr/lib/python3.7/subprocess.py", line 395, in check_output
    **kwargs).stdout
  File "/usr/lib/python3.7/subprocess.py", line 487, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '['dpkg-deb', '-f', '/var/cache/apt/archives/lua-basexx_0.4.1-jitsi1_all.deb', 'Package', 'Source', 'Version', 'Architecture', 'Status']' returned non-zero exit status 2.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/bin/apt-listchanges", line 281, in <module>
    main(config)
  File "/usr/bin/apt-listchanges", line 96, in main
    pkg = DebianFiles.Package(deb)
  File "/usr/share/apt-listchanges/DebianFiles.py", line 215, in __init__
    parser.readdeb(self.path)
  File "/usr/share/apt-listchanges/DebianFiles.py", line 128, in readdeb
    {'what': file, 'errmsg': str(ex)}) from ex
NameError: name 'file' is not defined
dpkg-deb: Fehler: Archiv »/var/cache/apt/archives/lua-basexx_0.4.1-jitsi1_all.deb« verwendet unbekannte Komprimierung für Element »control.tar.zst«, Abbruch
dpkg: Fehler beim Bearbeiten des Archivs /var/cache/apt/archives/lua-basexx_0.4.1-jitsi1_all.deb (--unpack):
 »dpkg-deb --control«-Unterprozess gab den Fehlerwert 2 zurück
dpkg-deb: Fehler: Archiv »/var/cache/apt/archives/lua-cjson_2.1.0.10-jitsi1_amd64.deb« verwendet unbekannte Komprimierung für Element »control.tar.zst«, Abbruch
dpkg: Fehler beim Bearbeiten des Archivs /var/cache/apt/archives/lua-cjson_2.1.0.10-jitsi1_amd64.deb (--unpack):
 »dpkg-deb --control«-Unterprozess gab den Fehlerwert 2 zurück
Fehler traten auf beim Bearbeiten von:
 /var/cache/apt/archives/lua-basexx_0.4.1-jitsi1_all.deb
 /var/cache/apt/archives/lua-cjson_2.1.0.10-jitsi1_amd64.deb
E: Sub-process /usr/bin/dpkg returned an error code (1)
root@jitsi:~# apt install -y zstd
Paketlisten werden gelesen... Fertig
Abhängigkeitsbaum wird aufgebaut.       
Statusinformationen werden eingelesen.... Fertig
zstd ist schon die neueste Version (1.3.8+dfsg-3+deb10u2).
0 aktualisiert, 0 neu installiert, 0 zu entfernen und 2 nicht aktualisiert.
root@jitsi:~# 
```

**Comment by brknkfr** [comment]
And apparently there is no zstd support for dpkg in debian yet.

**Comment by ldidry** [comment]
Same problem on Debian 11 (bullseye).

**Comment by saghul** [comment]
Ping @damencho

**Comment by damencho** [comment]
Looking into it.

**Comment by damencho** [comment]
This is fixed in stable. We will work on updating unstable with the correct packages later today.

**Comment by damencho** [comment]
Thank you for the report.

**Comment by MaStr** [comment]
Thank you for fixing. Can confirm, installation/update is working again.

**Comment by damencho** [comment]
Packages are back in stable and unstable and should be fine installing those. 
The updates are that those support now lua 5.3 and 5.4.

**Comment by Artoria2e5** [comment]
For what is worth, upstream dpkg 1.21.18 (Jan 2023), i.e. the Debian one, now has zstd support. See the previously linked Debian bug report.
