### ISSUE TITLE
Android: Crash when launching JitsiMeetActivity

### ISSUE THREAD

**Issue by embashbaz** [jitsi/jitsi-meet#12464]
### Description:

I am using Jitsi in an Android app, together with Feature module, and I have put Jitsi in its own feature module to avoid the huge download size for users downloading the app for the first time, when we start the after calling  JitsiMeetActivity.launch(this, options), I am getting an crash that I have pasted bellow

### Actual behavior:

The code for joining the metting, I am passing a valid url and a valid roomId

 val options: JitsiMeetConferenceOptions = JitsiMeetConferenceOptions.Builder()
                .setServerURL(URL(url))
                .setRoom(roomId)
                .setFeatureFlag("invite.enabled", false)
                .setFeatureFlag("live-streaming.enabled", false)
                .setFeatureFlag("chat.enabled", false)
                .setFeatureFlag("recording.enabled",false)
                .setFeatureFlag("welcomepage.enabled", false)
                .setFeatureFlag("video-share.enabled",false )
                .build()

   JitsiMeetActivity.launch(this, options)

This is the log for the error.

E/example.baseapp: Invalid ID 0x00000000.
E/AndroidRuntime: FATAL EXCEPTION: create_react_context
    Process: com.example.baseapp, PID: 7890
    android.content.res.Resources$NotFoundException: String resource ID #0x0
        at android.content.res.Resources.getText(Resources.java:453)
        at android.content.res.Resources.getString(Resources.java:546)
        at android.content.Context.getString(Context.java:762)
        at org.jitsi.meet.sdk.DropboxModule.<init>(DropboxModule.java:54)
        at org.jitsi.meet.sdk.ReactInstanceManagerHolder.createNativeModules(ReactInstanceManagerHolder.java:63)
        at org.jitsi.meet.sdk.ReactInstanceManagerHolder.access$000(ReactInstanceManagerHolder.java:48)
        at org.jitsi.meet.sdk.ReactInstanceManagerHolder$1.createNativeModules(ReactInstanceManagerHolder.java:138)
        at com.facebook.react.ReactPackageHelper.getNativeModuleIterator(ReactPackageHelper.java:42)
        at com.facebook.react.NativeModuleRegistryBuilder.processPackage(NativeModuleRegistryBuilder.java:42)
        at com.facebook.react.ReactInstanceManager.processPackage(ReactInstanceManager.java:1476)
        at com.facebook.react.ReactInstanceManager.processPackages(ReactInstanceManager.java:1447)
        at com.facebook.react.ReactInstanceManager.createReactContext(ReactInstanceManager.java:1341)
        at com.facebook.react.ReactInstanceManager.access$1200(ReactInstanceManager.java:138)
        at com.facebook.react.ReactInstanceManager$5.run(ReactInstanceManager.java:1111)
        at java.lang.Thread.run(Thread.java:1012)
E/JitsiMeetSDK: JitsiMeetUncaughtExceptionHandler FATAL ERROR
    android.content.res.Resources$NotFoundException: String resource ID #0x0
        at android.content.res.Resources.getText(Resources.java:453)
        at android.content.res.Resources.getString(Resources.java:546)
        at android.content.Context.getString(Context.java:762)
        at org.jitsi.meet.sdk.DropboxModule.<init>(DropboxModule.java:54)
        at org.jitsi.meet.sdk.ReactInstanceManagerHolder.createNativeModules(ReactInstanceManagerHolder.java:63)
        at org.jitsi.meet.sdk.ReactInstanceManagerHolder.access$000(ReactInstanceManagerHolder.java:48)
        at org.jitsi.meet.sdk.ReactInstanceManagerHolder$1.createNativeModules(ReactInstanceManagerHolder.java:138)
        at com.facebook.react.ReactPackageHelper.getNativeModuleIterator(ReactPackageHelper.java:42)
        at com.facebook.react.NativeModuleRegistryBuilder.processPackage(NativeModuleRegistryBuilder.java:42)
        at com.facebook.react.ReactInstanceManager.processPackage(ReactInstanceManager.java:1476)
        at com.facebook.react.ReactInstanceManager.processPackages(ReactInstanceManager.java:1447)
        at com.facebook.react.ReactInstanceManager.createReactContext(ReactInstanceManager.java:1341)
        at com.facebook.react.ReactInstanceManager.access$1200(ReactInstanceManager.java:138)
        at com.facebook.react.ReactInstanceManager$5.run(ReactInstanceManager.java:1111)
        at java.lang.Thread.run(Thread.java:1012)
    
 android.content.res.Resources$NotFoundException: String resource ID #0x0
        at android.content.res.Resources.getText(Resources.java:453)
        at android.content.res.Resources.getString(Resources.java:546)
        at android.content.Context.getString(Context.java:762)
        at org.jitsi.meet.sdk.DropboxModule.<init>(DropboxModule.java:54)
        at org.jitsi.meet.sdk.ReactInstanceManagerHolder.createNativeModules(ReactInstanceManagerHolder.java:63)
        at org.jitsi.meet.sdk.ReactInstanceManagerHolder.access$000(ReactInstanceManagerHolder.java:48)
        at org.jitsi.meet.sdk.ReactInstanceManagerHolder$1.createNativeModules(ReactInstanceManagerHolder.java:138)
        at com.facebook.react.ReactPackageHelper.getNativeModuleIterator(ReactPackageHelper.java:42)
        at com.facebook.react.NativeModuleRegistryBuilder.processPackage(NativeModuleRegistryBuilder.java:42)
        at com.facebook.react.ReactInstanceManager.processPackage(ReactInstanceManager.java:1476)
        at com.facebook.react.ReactInstanceManager.processPackages(ReactInstanceManager.java:1447)
        at com.facebook.react.ReactInstanceManager.createReactContext(ReactInstanceManager.java:1341)
        at com.facebook.react.ReactInstanceManager.access$1200(ReactInstanceManager.java:138)
        at com.facebook.react.ReactInstanceManager$5.run(ReactInstanceManager.java:1111)
        at java.lang.Thread.run(Thread.java:1012)

### Server information:

- Jitsi Meet version:  6.2.2 and 5.0.0

### Client information:

- app version: Android app
- android version: 13

**Comment by saghul** [comment]
Do you have a sample project which reproduces the issue?
