### ISSUE TITLE
Can't run JitsiMeet app

### ISSUE THREAD

**Issue by zhouhao27** [jitsi/jitsi-meet#12482]
### Description:

I cloned the latest source code. Add follow the [guide](https://jitsi.github.io/handbook/docs/dev-guide/dev-guide-mobile-jitsi-meet/). When I run the project in Xcode 14.0.1, I got the following error

![Simulator_Screen_Shot_-_iPhone_14_Pro_Max_-_2022-11-01_at_17_52_24](https://user-images.githubusercontent.com/8099731/199209087-974577f9-7505-4c4c-9cb8-af0310f4fc02.png)

> error: Error: Unable to resolve module ./Switch from /jitsi-meet/react/features/base/react/components/native/index.js: 

None of these files exist:
  * react/features/base/react/components/native/Switch(.native|.ios.js|.native.js|.js|.ios.json|.native.json|.json|.ios.ts|.native.ts|.ts|.ios.tsx|.native.tsx|.tsx|.ios.svg|.native.svg|.svg)
  * react/features/base/react/components/native/Switch/index(.native|.ios.js|.native.js|.js|.ios.json|.native.json|.json|.ios.ts|.native.ts|.ts|.ios.tsx|.native.tsx|.tsx|.ios.svg|.native.svg|.svg)
  18 | export { default as SectionList } from './SectionList';
  19 | export { default as SlidingView } from './SlidingView';
> 20 | export { default as Switch } from './Switch';
     |                                    ^
  21 | export { default as Text } from './Text';
  22 | export { default as TintedView } from './TintedView';
  23 |
    at ModuleResolver.resolveDependency (/jitsi-meet/node_modules/metro/src/node-haste/DependencyGraph/ModuleResolution.js:136:15)
    at DependencyGraph.resolveDependency (/jitsi-meet/node_modules/metro/src/node-haste/DependencyGraph.js:231:43)
    at Object.resolve (/jitsi-meet/node_modules/metro/src/lib/transformHelpers.js:129:24)
    at resolve (/jitsi-meet/node_modules/metro/src/DeltaBundler/traverseDependencies.js:396:33)
    at /jitsi-meet/node_modules/metro/src/DeltaBundler/traverseDependencies.js:412:26
    at Array.reduce (<anonymous>)
    at resolveDependencies (/jitsi-meet/node_modules/metro/src/DeltaBundler/traverseDependencies.js:411:33)
    at processModule (/jitsi-meet/node_modules/metro/src/DeltaBundler/traverseDependencies.js:140:31)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
 BUNDLE  ./index.ios.js 

### Steps to reproduce:

1. 
2. 
3. 

### Server information:

- Jitsi Meet version: Don't know how to check the version.
- Operating System: macOS Ventura

### Client information:

- Browser / app version:
- Operating System: macOS Ventura

**Comment by saghul** [comment]
This was fixed just a little while ago 😅
