### ISSUE TITLE
Screen share issue in Android 12 and 13 

### ISSUE THREAD

**Issue by shubham7111999** [jitsi/jitsi-meet#12920]
* I am using Jitsi SDK 6.1.0 but Screen sharing is not working also my app crashes when i join Second time on jitsiview.

* Here is your patch which i use here in Android --> JitsiMeetOngoingConferenceService.launch(this@MainActivity,extraData);

* Here is the code how i manage jitsiview -->   

 protected fun getJitsiView(): JitsiMeetView? {

        view =  JitsiMeetView(this);
       view = findViewById(R.id.test_JitsiMeetView) as JitsiMeetView
       return view
                                                                         }

fun join(options: JitsiMeetConferenceOptions?) {

    val view = getJitsiView()

    if (view != null) {
            view!!.join(options)
                             } 

                                                                         }

fun leave() {

    if (view != null) { 
        view.dispose();
        view = null;
        JitsiMeetActivityDelegate.onHostDestroy(this);
                       }

                  }

* Here is app Crash  Error --> Caused by: android.app.StackTrace: Last startServiceCommon() call for this service was made here
at android.app.ContextImpl.startServiceCommon(ContextImpl.java:1988)
at android.app.ContextImpl.startForegroundService(ContextImpl.java:1933)
at android.content.ContextWrapper.startForegroundService(ContextWrapper.java:839)
at android.content.ContextWrapper.startForegroundService(ContextWrapper.java:839)
at org.jitsi.meet.sdk.JitsiMeetOngoingConferenceService.launch(JitsiMeetOngoingConferenceService.java:67)
at com.cbc.views.MainActivity.onConferenceWillJoin(MainActivity.kt:3314)
at com.cbc.views.MainActivity.onBroadcastReceived(MainActivity.kt:3227)
at com.cbc.views.MainActivity.access$onBroadcastReceived(MainActivity.kt:92)
at com.cbc.views.MainActivity$broadcastReceiver$1.onReceive(MainActivity.kt:3215)
2023-02-16 15:33:08.565 31451-31451/com.cbc E/JitsiMeetSDK: at androidx.localbroadcastmanager.content.LocalBroadcastManager.executePendingBroadcasts(LocalBroadcastManager.java:313)
at androidx.localbroadcastmanager.content.LocalBroadcastManager$1.handleMessage(LocalBroadcastManager.java:121)

**Comment by saghul** [comment]
Any reason why you are not using the Activity instead of using the view directly? Also, have you tested SDK 7.0.1? That is the latest version.

**Comment by shubham7111999** [comment]
I am using JitsiMeetView because I do customization on screen.I also tested SDK 7.0.1 but issue remain same because of  the Forground service use in the patch which is restricted by the google in android 11 & 12 .

**Comment by saghul** [comment]
If you use your own Activity then you need to wire the view to the Activity yourself. Specifically, you need to start the foreground service like we do: https://github.com/jitsi/jitsi-meet/blob/00ed794c50b24a909b965c1e597687fd8b8b820b/android/sdk/src/main/java/org/jitsi/meet/sdk/JitsiMeetActivity.java#L222

**Comment by shubham7111999** [comment]
i also tried this pattern but issue remain same

**Comment by saghul** [comment]
Are you trying to use 2 views at the same time/

**Comment by shubham7111999** [comment]
only Single Jitsiview i am using

**Comment by shubham7111999** [comment]
Only main issue is  Forground Service which is restricted by google in android 11 & 12 . also use in --> JitsiMeetOngoingConferenceService.launch(this, extraData);

**Comment by saghul** [comment]
Restricted how? We are using it just fine. Do you have this permission set? `<uses-permission android:name="android.permission.FOREGROUND_SERVICE" />` The SDK has it in the manifest.

**Comment by shubham7111999** [comment]
yes I provided all the Permissions but when i Upgraded the Compile  and Targeting SDK of my project from 28 to 31 This issues started to arise 

Logcat -->  android.app.RemoteServiceException$ForegroundServiceDidNotStartInTimeException: Context.startForegroundService() did not then call Service.startForeground(): ServiceRecord{e3185e u0 com.cbc/org.jitsi.meet.sdk.JitsiMeetOngoingConferenceService}
        at android.app.ActivityThread.generateForegroundServiceDidNotStartInTimeException(ActivityThread.java:2006)
        at android.app.ActivityThread.throwRemoteServiceException(ActivityThread.java:1977)
        at android.app.ActivityThread.-$$Nest$mthrowRemoteServiceException(Unknown Source:0)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2242)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loopOnce(Looper.java:201)
        at android.os.Looper.loop(Looper.java:288)
        at android.app.ActivityThread.main(ActivityThread.java:7898)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:936)
     Caused by: android.app.StackTrace: Last startServiceCommon() call for this service was made here
        at android.app.ContextImpl.startServiceCommon(ContextImpl.java:1915)
        at android.app.ContextImpl.startForegroundService(ContextImpl.java:1870)
        at android.content.ContextWrapper.startForegroundService(ContextWrapper.java:822)
        at android.content.ContextWrapper.startForegroundService(ContextWrapper.java:822)
        at org.jitsi.meet.sdk.JitsiMeetOngoingConferenceService.launch(JitsiMeetOngoingConferenceService.java:67)
        at com.cbc.views.MainActivity.onConferenceWillJoin(MainActivity.kt:3317)
        at com.cbc.views.MainActivity.onBroadcastReceived(MainActivity.kt:3225)
        at com.cbc.views.MainActivity.access$onBroadcastReceived(MainActivity.kt:92)
        at com.cbc.views.MainActivity$broadcastReceiver$1.onReceive(MainActivity.kt:3213)
2023-02-20 16:44:16.782 5004-5004/com.cbc E/JitsiMeetSDK:     at androidx.localbroadcastmanager.content.LocalBroadcastManager.executePendingBroadcasts(LocalBroadcastManager.java:313)
        at androidx.localbroadcastmanager.content.LocalBroadcastManager$1.handleMessage(LocalBroadcastManager.java:121)

**Comment by saghul** [comment]
Are you starting your activity in the background?

**Comment by saghul** [comment]
Can you reproduce this with the Jitsi Meet app?

**Comment by shubham7111999** [comment]
> Are you starting your activity in the background?

no,we are start a Simple activity with the use of  Jitsiview

**Comment by shubham7111999** [comment]
> Can you reproduce this with the Jitsi Meet app?

we are facing this issue with custom jitsi view then why we are test it with jitsi App

**Comment by saghul** [comment]
Because the app uses the SDK.

**Comment by shubham7111999** [comment]
We face this issue when we shift our compile and target SDK of App from 28 to 31. But when our app was have Sdk of 28 it was fine.so please check by shift your Complile and target SDK 31 of jitsiApp on jitsview

**Comment by saghul** [comment]
This how we build the app:

```
    buildToolsVersion = "31.0.0"
    compileSdkVersion = 32
    minSdkVersion    = 23
    targetSdkVersion = 32
    supportLibVersion = "28.0.0"
```

**Comment by shubham7111999** [comment]
* mainly I using this jitsi view for calling purpose on FIRST CALL when I use -->   JitsiMeetOngoingConferenceService.launch(this, extraData) and on leaving call I use --> JitsiMeetOngoingConferenceService.abort(this@MainActivity);

* But when I  am try to call second time on open application --> jitsiMeetOngoingConferenceService.launch(this, extraData) throw me error 

* Logcat -->  android.app.RemoteServiceException$ForegroundServiceDidNotStartInTimeException: Context.startForegroundService() did not then call Service.startForeground(): ServiceRecord{e3185e u0 com.cbc/org.jitsi.meet.sdk.JitsiMeetOngoingConferenceService}
at android.app.ActivityThread.generateForegroundServiceDidNotStartInTimeException(ActivityThread.java:2006)
at android.app.ActivityThread.throwRemoteServiceException(ActivityThread.java:1977)
at android.app.ActivityThread.-$$Nest$mthrowRemoteServiceException(Unknown Source:0)
at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2242)
at android.os.Handler.dispatchMessage(Handler.java:106)
at android.os.Looper.loopOnce(Looper.java:201)
at android.os.Looper.loop(Looper.java:288)
at android.app.ActivityThread.main(ActivityThread.java:7898)
at java.lang.reflect.Method.invoke(Native Method)
at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:936)
Caused by: android.app.StackTrace: Last startServiceCommon() call for this service was made here
at android.app.ContextImpl.startServiceCommon(ContextImpl.java:1915)
at android.app.ContextImpl.startForegroundService(ContextImpl.java:1870)
at android.content.ContextWrapper.startForegroundService(ContextWrapper.java:822)
at android.content.ContextWrapper.startForegroundService(ContextWrapper.java:822)
at org.jitsi.meet.sdk.JitsiMeetOngoingConferenceService.launch(JitsiMeetOngoingConferenceService.java:67)
at com.cbc.views.MainActivity.onConferenceWillJoin(MainActivity.kt:3317)
at com.cbc.views.MainActivity.onBroadcastReceived(MainActivity.kt:3225)
at com.cbc.views.MainActivity.access$onBroadcastReceived(MainActivity.kt:92)
at com.cbc.views.MainActivity$broadcastReceiver$1.onReceive(MainActivity.kt:3213)
2023-02-20 16:44:16.782 5004-5004/com.cbc E/JitsiMeetSDK: at androidx.localbroadcastmanager.content.LocalBroadcastManager.executePendingBroadcasts(LocalBroadcastManager.java:313)
at androidx.localbroadcastmanager.content.LocalBroadcastManager$1.handleMessage(LocalBroadcastManager.java:121)

**Comment by saghul** [comment]
Do you try to start the foreground service after the conference was joined?

**Comment by shubham7111999** [comment]
yes i did but issue remain same

while on CONFERENCE_TERMINATED is use -->  
{
 view!!.dispose(); // JitsiView
JitsiMeetOngoingConferenceService.abort(this@MainActivity); 
}

Logcat -->android.app.ForegroundServiceDidNotStartInTimeException: Context.startForegroundService() did not then call Service.startForeground(): ServiceRecord{bb028c4 u0 com.cbc/org.jitsi.meet.sdk.JitsiMeetOngoingConferenceService}
        at android.app.ActivityThread.throwRemoteServiceException(ActivityThread.java:2131)
        at android.app.ActivityThread.access$3000(ActivityThread.java:284)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2379)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loopOnce(Looper.java:233)
        at android.os.Looper.loop(Looper.java:334)
        at android.app.ActivityThread.main(ActivityThread.java:8396)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:582)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1068)

**Comment by saghul** [comment]
You need to do that in the readyToClose event, not conference_terminated. As I mentioned before, please model your activity after ours.
