### ISSUE TITLE
Jitsi meet join meeting suddenly restart 

### ISSUE THREAD

**Issue by Shadows7010** [jitsi/jitsi-meet#13079]
### Steps to reproduce:

1. 
2. 
3. 

### Server information:

- Jitsi Meet version:7.01
- Operating System:minimum 7 max 12

### Client information:

- Browser / app version:
- Operating System:

### Additional information:

error logs:
E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.mediocre.mscasvideocallingapp, PID: 10453
    java.lang.RuntimeException: Unable to start service org.jitsi.meet.sdk.JitsiMeetOngoingConferenceService@416d006 with Intent { cmp=com.mediocre.mscasvideocallingapp/org.jitsi.meet.sdk.JitsiMeetOngoingConferenceService (has extras) }: java.lang.IllegalArgumentException: Invalid notification (no valid small icon): Notification(channel=JitsiOngoingConferenceChannel shortcut=null contentView=null vibrate=null sound=null defaults=0x0 flags=0xa color=0x00000000 category=call actions=2 vis=PUBLIC)
        at android.app.ActivityThread.handleServiceArgs(ActivityThread.java:4344)
        at android.app.ActivityThread.access$1800(ActivityThread.java:237)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1951)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:223)
        at android.app.ActivityThread.main(ActivityThread.java:7656)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)
     Caused by: java.lang.IllegalArgumentException: Invalid notification (no valid small icon): Notification(channel=JitsiOngoingConferenceChannel shortcut=null contentView=null vibrate=null sound=null defaults=0x0 flags=0xa color=0x00000000 category=call actions=2 vis=PUBLIC)
        at android.app.NotificationManager.fixNotification(NotificationManager.java:603)
        at android.app.NotificationManager.notifyAsUser(NotificationManager.java:582)
        at android.app.NotificationManager.notify(NotificationManager.java:531)
        at android.app.NotificationManager.notify(NotificationManager.java:507)
        at org.jitsi.meet.sdk.JitsiMeetOngoingConferenceService.onStartCommand(JitsiMeetOngoingConferenceService.java:135)
        at android.app.ActivityThread.handleServiceArgs(ActivityThread.java:4326)
        at android.app.ActivityThread.access$1800(ActivityThread.java:237) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1951) 
        at android.os.Handler.dispatchMessage(Handler.java:106) 
        at android.os.Looper.loop(Looper.java:223) 
        at android.app.ActivityThread.main(ActivityThread.java:7656) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947) 
E/JitsiMeetSDK: JitsiMeetUncaughtExceptionHandler FATAL ERROR
    java.lang.RuntimeException: Unable to start service org.jitsi.meet.sdk.JitsiMeetOngoingConferenceService@416d006 with Intent { cmp=com.mediocre.mscasvideocallingapp/org.jitsi.meet.sdk.JitsiMeetOngoingConferenceService (has extras) }: java.lang.IllegalArgumentException: Invalid notification (no valid small icon): Notification(channel=JitsiOngoingConferenceChannel shortcut=null contentView=null vibrate=null sound=null defaults=0x0 flags=0xa color=0x00000000 category=call actions=2 vis=PUBLIC)
        at android.app.ActivityThread.handleServiceArgs(ActivityThread.java:4344)
        at android.app.ActivityThread.access$1800(ActivityThread.java:237)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1951)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:223)
        at android.app.ActivityThread.main(ActivityThread.java:7656)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)
     Caused by: java.lang.IllegalArgumentException: Invalid notification (no valid small icon): Notification(channel=JitsiOngoingConferenceChannel shortcut=null contentView=null vibrate=null sound=null defaults=0x0 flags=0xa color=0x00000000 category=call actions=2 vis=PUBLIC)
        at android.app.NotificationManager.fixNotification(NotificationManager.java:603)
        at android.app.NotificationManager.notifyAsUser(NotificationManager.java:582)
        at android.app.NotificationManager.notify(NotificationManager.java:531)
        at android.app.NotificationManager.notify(NotificationManager.java:507)
        at org.jitsi.meet.sdk.JitsiMeetOngoingConferenceService.onStartCommand(JitsiMeetOngoingConferenceService.java:135)
        at android.app.ActivityThread.handleServiceArgs(ActivityThread.java:4326)
        at android.app.ActivityThread.access$1800(ActivityThread.java:237) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1951) 
        at android.os.Handler.dispatchMessage(Handler.java:106) 
        at android.os.Looper.loop(Looper.java:223) 
        at android.app.ActivityThread.main(ActivityThread.java:7656) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947) 
    
    java.lang.RuntimeException: Unable to start service org.jitsi.meet.sdk.JitsiMeetOngoingConferenceService@416d006 with Intent { cmp=com.mediocre.mscasvideocallingapp/org.jitsi.meet.sdk.JitsiMeetOngoingConferenceService (has extras) }: java.lang.IllegalArgumentException: Invalid notification (no valid small icon): Notification(channel=JitsiOngoingConferenceChannel shortcut=null contentView=null vibrate=null sound=null defaults=0x0 flags=0xa color=0x00000000 category=call actions=2 vis=PUBLIC)
        at android.app.ActivityThread.handleServiceArgs(ActivityThread.java:4344)
        at android.app.ActivityThread.access$1800(ActivityThread.java:237)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1951)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:223)
        at android.app.ActivityThread.main(ActivityThread.java:7656)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)
     Caused by: java.lang.IllegalArgumentException: Invalid notification (no valid small icon): Notification(channel=JitsiOngoingConferenceChannel shortcut=null contentView=null vibrate=null sound=null defaults=0x0 flags=0xa color=0x00000000 category=call actions=2 vis=PUBLIC)
        at android.app.NotificationManager.fixNotification(NotificationManager.java:603)
        at android.app.NotificationManager.notifyAsUser(NotificationManager.java:582)
        at android.app.NotificationManager.notify(NotificationManager.java:531)
        at android.app.NotificationManager.notify(NotificationManager.java:507)
        at org.jitsi.meet.sdk.JitsiMeetOngoingConferenceService.onStartCommand(JitsiMeetOngoingConferenceService.java:135)
        at android.app.ActivityThread.handleServiceArgs(ActivityThread.java:4326)
        at android.app.ActivityThread.access$1800(ActivityThread.java:237) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1951) 
        at android.os.Handler.dispatchMessage(Handler.java:106) 
        at android.os.Looper.loop(Looper.java:223) 
        at android.app.ActivityThread.main(ActivityThread.java:7656) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947) 
I/JitsiMeetSDK: JitsiConnectionService onAbort 0C8B3AB3-6349-4AC9-99C1-38AAC303AEC8
D/JitsiMeetSDK: JitsiConnectionService onStateChanged: DISCONNECTED 0C8B3AB3-6349-4AC9-99C1-38AAC303AEC8
I/Process: Sending signal. PID: 10453 SIG: 9

@saghul
@aaronkvanmeerten 
@damencho 
@csett86 
@emcho
@fippo
@zbettenbuk 
@yanas  
@wernerd
@tomdee
@sawall 
@s-vincent
@jallamsetty1 

help me brosss....

**Comment by Shadows7010** [comment]
I'm facing issues bro
@saghul  
Help me bro
https://user-images.githubusercontent.com/128147629/226083250-c3bc8015-85b1-40c3-9ff5-219a67c7adc1.mp4

**Comment by saghul** [comment]
Please stop mentioning pelo e or I will have to block you.

Your question has been a answered already.

You need to supply an icon asset named ic_notification. It's literally in the error message.

Android Studio is able to generate this icon for you, search for the option.

**Comment by Shadows7010** [comment]
> Please stop mentioning pelo e or I will have to block you.
> 
> Your question has been a answered already.
> 
> You need to supply an icon asset named ic_notification. It's literally in the error message.
> 
> Android Studio is able to generate this icon for you, search for the option.

Okay bro
