### ISSUE TITLE
Unable to start service org.jitsi.meet.sdk.JitsiMeetOngoingConferenceService@10dc0b1 with Intent FLAG_IMMUTABLE in Android SDK_33

### ISSUE THREAD

**Issue by YashSharmaas** [jitsi/jitsi-meet#13147]
I'm trying to building video call application by using jitsimeet dependency but it throws issue 

FATAL EXCEPTION: main
                                                                                                    Process: com.example.firebaseauth, PID: 26411
                                                                                                    java.lang.RuntimeException: Unable to start service org.jitsi.meet.sdk.JitsiMeetOngoingConferenceService@10dc0b1 with Intent { act=JitsiMeetOngoingConferenceService:START cmp=com.example.firebaseauth/org.jitsi.meet.sdk.JitsiMeetOngoingConferenceService }: java.lang.IllegalArgumentException: com.example.firebaseauth: Targeting S+ (version 31 and above) requires that one of FLAG_IMMUTABLE or FLAG_MUTABLE be specified when creating a PendingIntent.
                                                                                                    Strongly consider using FLAG_IMMUTABLE, only use FLAG_MUTABLE if some functionality depends on the PendingIntent being mutable, e.g. if it needs to be used with inline replies or bubbles.
                                                                                                    	at android.app.ActivityThread.handleServiceArgs(ActivityThread.java:5192)
                                                                                                    	at android.app.ActivityThread.access$2100(ActivityThread.java:315)
                                                                                                    	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2324)
                                                                                                    	at android.os.Handler.dispatchMessage(Handler.java:106)
                                                                                                    	at android.os.Looper.loopOnce(Looper.java:226)
                                                                                                    	at android.os.Looper.loop(Looper.java:313)
                                                                                                    	at android.app.ActivityThread.main(ActivityThread.java:8751)
                                                                                                    	at java.lang.reflect.Method.invoke(Native Method)
                                                                                                    	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:571)
                                                                                                    	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1135)
                                                                                                    Caused by: java.lang.IllegalArgumentException: com.example.firebaseauth: Targeting S+ (version 31 and above) requires that one of FLAG_IMMUTABLE or FLAG_MUTABLE be specified when creating a PendingIntent.
                                                                                                    Strongly consider using FLAG_IMMUTABLE, only use FLAG_MUTABLE if some functionality depends on the PendingIntent being mutable, e.g. if it needs to be used with inline replies or bubbles.
                                                                                                    	at android.app.PendingIntent.checkFlags(PendingIntent.java:382)
                                                                                                    	at android.app.PendingIntent.getActivityAsUser(PendingIntent.java:465)
                                                                                                    	at android.app.PendingIntent.getActivity(PendingIntent.java:451)
                                                                                                    	at android.app.PendingIntent.getActivity(PendingIntent.java:415)
                                                                                                    	at org.jitsi.meet.sdk.OngoingNotification.buildOngoingConferenceNotification(OngoingNotification.java:84)
                                                                                                    	at org.jitsi.meet.sdk.JitsiMeetOngoingConferenceService.onStartCommand(JitsiMeetOngoingConferenceService.java:91)
                                                                                                    	at android.app.ActivityThread.handleServiceArgs(ActivityThread.java:5174)
                                                                                                    	... 9 more

and 

FATAL EXCEPTION: main
                                                                                                    Process: com.example.firebaseauth, PID: 26848
                                                                                                    android.app.ForegroundServiceDidNotStartInTimeException: Context.startForegroundService() did not then call Service.startForeground(): ServiceRecord{7641834 u0 com.example.firebaseauth/org.jitsi.meet.sdk.JitsiMeetOngoingConferenceService}
                                                                                                    	at android.app.ActivityThread.throwRemoteServiceException(ActivityThread.java:2152)
                                                                                                    	at android.app.ActivityThread.access$2800(ActivityThread.java:315)
                                                                                                    	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2381)
                                                                                                    	at android.os.Handler.dispatchMessage(Handler.java:106)
                                                                                                    	at android.os.Looper.loopOnce(Looper.java:226)
                                                                                                    	at android.os.Looper.loop(Looper.java:313)
                                                                                                    	at android.app.ActivityThread.main(ActivityThread.java:8751)
                                                                                                    	at java.lang.reflect.Method.invoke(Native Method)
                                                                                                    	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:571)
                                                                                                    	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1135)
2023-04-01 12:28:12.749  1203-5635  WindowManager           system_server                        E  win=Window{39ed771 u0 Splash Screen com.example.firebaseauth EXITING} destroySurfaces: appStopped=false win.mWindowRemovalAllowed=true win.mRemoveOnExit=true win.mViewVisibility=0 caller=com.android.server.wm.ActivityRecord.destroySurfaces:5867 com.android.server.wm.ActivityRecord.destroySurfaces:5848 com.android.server.wm.WindowState.onExitAnimationDone:5992 com.android.server.wm.ActivityRecord$$ExternalSyntheticLambda13.accept:2 java.util.ArrayList.forEach:1262 com.android.server.wm.ActivityRecord.onAnimationFinished:7940 com.android.server.wm.ActivityRecord.postApplyAnimation:5598 
---------------------------- PROCESS ENDED (26848) for package com.example.firebaseauth ----------------------------

To avoid this issue i also updated my SDKs and also add a dependency  implementation 'androidx.work:work-runtime:2.8.1'
App working fine below Android 12 but when it runs above 12 it throws error.
Please try to solve this error.

**Comment by saghul** [comment]
What Jitsi Meet SDK version did you use?
