### ISSUE TITLE
Javascript error when trying to change virtual background

### ISSUE THREAD

**Issue by adamsko** [jitsi/jitsi-meet#13461]
Using stable-8719

At the prejoin screen or in a meeting click the small arrow on the camera icon and select Virtual backgrounds. Result is Javascript error in console and thrown out to the close page.
The exact same configuration with stable-8615 does not have this issue.

From pre-join screen:
-  js error as shown below
- blank screen, does not appear to try to render close page

From meeting:
- no js error
- sent to close page

Should this me a jitsi-meet issue instead?

```
react-dom.production.min.js:185 TypeError: Cannot read properties of undefined (reading 'selectedVideoInputId')
    at Object.propsUpdateFunction (SettingsDialog.tsx:126:53)
    at x (DialogWithTabs.tsx:192:37)
    at DialogWithTabs.tsx:217:129
    at Object.useMemo (react-dom.production.min.js:180:276)
    at t.useMemo (scheduler.production.min.js:10:354)
    at tN (DialogWithTabs.tsx:213:42)
    at So (react-dom.production.min.js:165:250)
    at xl (aliases.js:50:3)
    at vc (react-dom.production.min.js:284:190)
    at bc (react-dom.production.min.js:284:114)
    at gc (react-dom.production.min.js:283:138)
    at lc (react-dom.production.min.js:265:350)
    at qa (react-dom.production.min.js:126:22)
    at cc (react-dom.production.min.js:275:266)
    at Pe (react-dom.production.min.js:51:15)
    at Vr (react-dom.production.min.js:109:24)
    at Yt (react-dom.production.min.js:71:183)
    at Wt (react-dom.production.min.js:69:484)
```

**Comment by saghul** [comment]
Can you repro on meet.jit.si? I cannot. We might have fixed it after the stable release :-/ FYI @damencho

**Comment by adamsko** [comment]
I cannot reproduce it on meet.jit.si
We are running with most things disabled in jitsi gui. For example we do not have a settings button on the main bar.

**Comment by saghul** [comment]
Can you reproduce it without those customizations?

**Comment by adamsko** [comment]
We have this
```
interfaceConfig.SETTINGS_SECTIONS = [ 'virtual-background' ];
```
in our custom-interface_config.js
if I comment that row out it works, but I also get all of the other options in the settings screen showing.

**Comment by saghul** [comment]
Fixed in https://github.com/jitsi/jitsi-meet/pull/13464

**Comment by adamsko** [comment]
Great thanks!
