### ISSUE TITLE
Screen sharing is broken on Android

### ISSUE THREAD

**Issue by eKaramihov** [jitsi/jitsi-meet#13513]
### Description:

Android app from Google Play store.
When screen sharing with Jitsi meet app, the app doesn't allow user to move the Jitsi Meet app in the background using android system navigation.

### Steps to reproduce:

Open app, and join a room.
Click more options and start screen sharing
Use android bottom system navigation bar to move app in background.

### Expected behavior:

Users must be able to browse through phone without limitations. 
Meaning users must be able to share Android Launcher and other apps screens

### Actual behavior:

The user cannot share his Android Launcher screen. Therefore is limited to stay only in the Jitsi Meet app.
Sometimes it is possible to move the app in the background, but it crashes.

### Server information:

- Jitsi Meet version: Latest version in Google Play Store
- Operating System: Android

**Comment by saghul** [comment]
I can certainly do that. Can you please record a video of what happens in your case? What prevents you from navigating?

**Comment by eKaramihov** [comment]
Here it is:
The phone is Samsung s21, Android 13

https://github.com/jitsi/jitsi-meet/assets/91118187/18eb9060-55ff-4c68-a2e0-4cf097d64901

**Comment by saghul** [comment]
I noticerd a simular thing on a Pixel 6. It does go into the background but you need to try a number of times. Looks like some Android 13 change, we'll take a look. Thanks for the report!

**Comment by eKaramihov** [comment]
Tbh, I managed to move the app in the background on an older device, don't really remember the version (Android 9 or 10 can't recall for sure). But the app crashed a few seconds after use. 

I was just moving the app from back to fore-ground and browsing the launcher.

I am not certain for sure, but I believe that the problem is not in the Android version.

**Comment by saghul** [comment]
> Tbh, I managed to move the app in the background on an older device, don't really remember the version (Android 9 or 10 can't recall for sure). But the app crashed a few seconds after use.

Getting the logcat of that would be essential to fixing it.



> I am not certain for sure, but I believe that the problem is not in the Android version.

I mean the behavior with the dragging. Although after trying again I didn't manage to get the same behavior, oh well...

**Comment by eKaramihov** [comment]
Log cat

2023-06-30 17:09:04.825  1362-1456  WindowManager           system_server                        W  Exception thrown during dispatchAppVisibility Window{a3cf0c4 u0 org.jitsi.meet/org.jitsi.meet.MainActivity EXITING}
                                                                                                    android.os.DeadObjectException
                                                                                                    	at android.os.BinderProxy.transactNative(Native Method)
                                                                                                    	at android.os.BinderProxy.transact(BinderProxy.java:662)
                                                                                                    	at android.view.IWindow$Stub$Proxy.dispatchAppVisibility(IWindow.java:658)
                                                                                                    	at com.android.server.wm.WindowState.sendAppVisibilityToClients(WindowState.java:4200)
                                                                                                    	at com.android.server.wm.WindowContainer.sendAppVisibilityToClients(WindowContainer.java:1246)
                                                                                                    	at com.android.server.wm.WindowToken.setClientVisible(WindowToken.java:431)
                                                                                                    	at com.android.server.wm.ActivityRecord.setClientVisible(ActivityRecord.java:7685)
                                                                                                    	at com.android.server.wm.ActivityRecord.onAnimationFinished(ActivityRecord.java:8584)
                                                                                                    	at com.android.server.wm.ActivityRecord.postApplyAnimation(ActivityRecord.java:6246)
                                                                                                    	at com.android.server.wm.ActivityRecord.commitVisibility(ActivityRecord.java:6218)
                                                                                                    	at com.android.server.wm.ActivityRecord.commitVisibility(ActivityRecord.java:6222)
                                                                                                    	at com.android.server.wm.AppTransitionController.handleClosingApps(AppTransitionController.java:1279)
                                                                                                    	at com.android.server.wm.AppTransitionController.handleAppTransitionReady(AppTransitionController.java:304)
                                                                                                    	at com.android.server.wm.RootWindowContainer.checkAppTransitionReady(RootWindowContainer.java:1182)
                                                                                                    	at com.android.server.wm.RootWindowContainer.performSurfacePlacementNoTrace(RootWindowContainer.java:1022)
                                                                                                    	at com.android.server.wm.RootWindowContainer.performSurfacePlacement(RootWindowContainer.java:950)
                                                                                                    	at com.android.server.wm.WindowSurfacePlacer.performSurfacePlacementLoop(WindowSurfacePlacer.java:185)
                                                                                                    	at com.android.server.wm.WindowSurfacePlacer.performSurfacePlacement(WindowSurfacePlacer.java:134)
                                                                                                    	at com.android.server.wm.WindowSurfacePlacer.performSurfacePlacement(WindowSurfacePlacer.java:123)
                                                                                                    	at com.android.server.wm.WindowSurfacePlacer$Traverser.run(WindowSurfacePlacer.java:65)
                                                                                                    	at android.os.Handler.handleCallback(Handler.java:942)
                                                                                                    	at android.os.Handler.dispatchMessage(Handler.java:99)
                                                                                                    	at android.os.Looper.loopOnce(Looper.java:226)
                                                                                                    	at android.os.Looper.loop(Looper.java:313)
                                                                                                    	at android.os.HandlerThread.run(HandlerThread.java:67)
                                                                                                    	at com.android.server.ServiceThread.run(ServiceThread.java:44)
2023-06-30 17:09:04.825  1362-1456  WindowManager           system_server                        E  win=Window{a3cf0c4 u0 org.jitsi.meet/org.jitsi.meet.MainActivity EXITING} destroySurfaces: appStopped=false cleanupOnResume=false win.mWindowRemovalAllowed=true win.mRemoveOnExit=true win.mViewVisibility=0 caller=com.android.server.wm.ActivityRecord.destroySurfaces:6533 com.android.server.wm.ActivityRecord.destroySurfaces:6514 com.android.server.wm.WindowState.onExitAnimationDone:5981 com.android.server.wm.ActivityRecord$$ExternalSyntheticLambda10.accept:2 java.util.ArrayList.forEach:1262 com.android.server.wm.ActivityRecord.onAnimationFinished:8601 com.android.server.wm.ActivityRecord.postApplyAnimation:6246 
2023-06-30 17:09:04.826  1362-1456  WindowManager           system_server                        I  Destroying surface Surface(name=org.jitsi.meet/org.jitsi.meet.MainActivity$_22059)/@0x7c66252 called by com.android.server.wm.WindowStateAnimator.destroySurface:942 com.android.server.wm.WindowStateAnimator.destroySurfaceLocked:536 com.android.server.wm.WindowState.destroySurfaceUnchecked:4306 com.android.server.wm.WindowState.destroySurface:4280 com.android.server.wm.ActivityRecord.destroySurfaces:6533 com.android.server.wm.ActivityRecord.destroySurfaces:6514 com.android.server.wm.WindowState.onExitAnimationDone:5981 com.android.server.wm.ActivityRecord$$ExternalSyntheticLambda10.accept:2

**Comment by saghul** [comment]
Is that everything? No other errors?
