### ISSUE TITLE
Android Jetpack Compose JitsiMeetView crash

### ISSUE THREAD

**Issue by andreas-umbricht** [jitsi/jitsi-meet#14226]
### Description:

I tried to use the JitsiMeetView in a Jetpack Compose app, but it seems that the JitsiMeetView is not compatible with ComponentActivity.

### Steps to reproduce:
```
    AndroidView(
        factory = { context ->
            val jitsiView = JitsiMeetView(context)

            val options = JitsiMeetConferenceOptions.Builder()
                .setRoom("Test") // Settings for audio and video
                .setAudioOnly(true)
                .setConfigOverride("requireDisplayName", false)
                .build()

            jitsiView.join(options)

            jitsiView
        },
        modifier = Modifier
            .fillMaxSize()
    )
```

### Expected behavior:

The JitsiMeetView should be displayed as usual. I really do not understand this error, since I am not using React-Native.

### Actual behavior:

```
java.lang.IllegalStateException: In order to use RNScreens components your app's activity need to extend ReactActivity
		at com.swmansion.rnscreens.ScreenContainer.findFragmentManagerForReactRootView(ScreenContainer.kt:139)
		at com.swmansion.rnscreens.ScreenContainer.setupFragmentManager(ScreenContainer.kt:190)
		at com.swmansion.rnscreens.ScreenContainer.onAttachedToWindow(ScreenContainer.kt:217)
		at android.view.View.dispatchAttachedToWindow(View.java:21976)
		at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:4293)
		at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:4302)
		at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:4302)
		at android.view.ViewGroup.addViewInner(ViewGroup.java:6127)
		at android.view.ViewGroup.addView(ViewGroup.java:5903)
		at com.facebook.react.views.view.ReactViewGroup.addView(ReactViewGroup.java:466)
		at android.view.ViewGroup.addView(ViewGroup.java:5843)
		at com.facebook.react.views.view.ReactClippingViewManager.addView(ReactClippingViewManager.java:38)
		at com.facebook.react.views.view.ReactClippingViewManager.addView(ReactClippingViewManager.java:19)
		at com.facebook.react.uimanager.NativeViewHierarchyManager.manageChildren(NativeViewHierarchyManager.java:533)
		at com.facebook.react.uimanager.UIViewOperationQueue$ManageChildrenOperation.execute(UIViewOperationQueue.java:217)
		at com.facebook.react.uimanager.UIViewOperationQueue$1.run(UIViewOperationQueue.java:915)
		at com.facebook.react.uimanager.UIViewOperationQueue.flushPendingBatches(UIViewOperationQueue.java:1026)
		at com.facebook.react.uimanager.UIViewOperationQueue.access$2600(UIViewOperationQueue.java:47)
		at com.facebook.react.uimanager.UIViewOperationQueue$DispatchUIFrameCallback.doFrameGuarded(UIViewOperationQueue.java:1086)
		at com.facebook.react.uimanager.GuardedFrameCallback.doFrame(GuardedFrameCallback.java:29)
		at com.facebook.react.modules.core.ReactChoreographer$ReactChoreographerDispatcher.doFrame(ReactChoreographer.java:175)
		at com.facebook.react.modules.core.ChoreographerCompat$FrameCallback$1.doFrame(ChoreographerCompat.java:85)
		at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1106)
		at android.view.Choreographer.doCallbacks(Choreographer.java:866)
		at android.view.Choreographer.doFrame(Choreographer.java:792)
		at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1092)
		at android.os.Handler.handleCallback(Handler.java:938)
		at android.os.Handler.dispatchMessage(Handler.java:99)
		at android.os.Looper.loopOnce(Looper.java:226)
		at android.os.Looper.loop(Looper.java:313)
		at android.app.ActivityThread.main(ActivityThread.java:8751)
		at java.lang.reflect.Method.invoke(Native Method)
		at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:571)
		at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1135)
```
Because of this error I simply tried exchanging ComponentActivity() with ReactActivity(), but that crashed as well.

### Client information:

- Browser / app version: 8.6.0
- Operating System: Android

**Comment by saghul** [comment]
You need some supporting code to run, the view alone is not enough. Have a look at JitsiMeetActivity.

**Comment by serifkazan** [comment]
Could you please share what code should we add?
