### ISSUE TITLE
react-native-asset not working for custom font linking

### ISSUE THREAD

**Issue by GoliathLabs** [jitsi/jitsi-meet#14277]
### Description:

I'm currently playing around with jitsi-meet. It's quite an impressive project and I've successfully set it up for my local non-profit organisation.

In addition, I would like to use a custom theme with non-standard fonts.
### Steps to reproduce:
As suggested, I added them to the assets/fonts folder and added `assets: ['./assets/fonts'],` to the react-native.config.js file.
1.  Clone repository
2.  Execute `npx react-native-asset`
3.  Watch it fail

### Expected behavior:
Running `npx react-native-asset` should link the new assets with both android and ios subfolders.

### Actual behavior:

Instead I get the following error. This error can also be seen by just cloning the unmodified jitsi-meet repository and executing  `npx react-native-asset` 
```
node:internal/validators:162
    throw new ERR_INVALID_ARG_TYPE(name, 'string', value);
    ^

TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received undefined
    at new NodeError (node:internal/errors:387:5)
    at validateString (node:internal/validators:162:11)
    at Object.resolve (node:path:1098:7)
    at module.exports (/Users/myuser/.npm/_npx/545c366a5ae830a2/node_modules/react-native-asset/lib/get-config.js:13:12)
    at module.exports (/Users/myuser/.npm/_npx/545c366a5ae830a2/node_modules/react-native-asset/lib/index.js:188:18)
    at Object.<anonymous> (/Users/myuser/.npm/_npx/545c366a5ae830a2/node_modules/react-native-asset/lib/cli.js:56:1)
    at Module._compile (node:internal/modules/cjs/loader:1198:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1252:10)
    at Module.load (node:internal/modules/cjs/loader:1076:32)
    at Function.Module._load (node:internal/modules/cjs/loader:911:12) {
  code: 'ERR_INVALID_ARG_TYPE'
}
```
### Server information:

- Jitsi Meet version: latest master commit
- Operating System: tested on windows and macos.

### Client information:

- Browser / app version: Irrelevant --> most recent Firefox version
- Operating System: Windows/macOS

**Comment by saghul** [comment]
Our project does not follow the "traditional" RN app layout so I'm afraid you're going to have to add it manually to the build.
