### ISSUE TITLE
 2.0.9220 - Fresh installation . Dont create room

### ISSUE THREAD

**Issue by LiloBzH** [jitsi/jitsi-meet#14289]
### Description:

Fresh install on Debian 10

### Steps to reproduce:

Create room. Choose name and go !
Button stay grey and no reaction

### Server information:

- Jitsi Meet version:  2.0.9220
- Operating System: Debian 10
- Nginx
- Own certificat in /etc/lectsencrypt

### Client information:

- Browser / app version: Firefox and Chrome => Same
- Operating System: Android or Windows

### Additional information:

No specific config for now.

Firefox Log :

```
2024-01-29T13:24:07.175Z [features/base/connection] <Xw/</i<>:  Using service URL https://jitsi.monsite.com/http-bind Logger.js:155:26
2024-01-29T13:24:07.176Z [modules/xmpp/moderator.js] <Jo>:  Using xmpp for conference requests. Logger.js:155:26
2024-01-29T13:24:07.176Z [modules/xmpp/xmpp.js] <_initStrophePlugins>:  P2P STUN servers:  
Array [ {…} ]
Logger.js:155:26
2024-01-29T13:24:07.180Z [modules/xmpp/xmpp.js] <initFeaturesList>:  Source-name signaling is enabled Logger.js:155:26
2024-01-29T13:24:07.180Z [modules/xmpp/xmpp.js] <initFeaturesList>:  Receiving multiple video streams is enabled Logger.js:155:26
2024-01-29T13:24:07.182Z [modules/xmpp/xmpp.js] <connectionHandler>:  (TIME) Strophe connecting:	 27359 Logger.js:155:26
XHRPOST
https://jitsi.monsite.com/http-bind?room=test
[HTTP/2 200  17ms]

2024-01-29T13:24:07.237Z [modules/xmpp/strophe.util.js] <4794/Ra/yt.Strophe.log>:  Strophe: Server did not yet offer a supported authentication mechanism. Sending a blank poll request. Logger.js:155:26
XHRPOST
https://jitsi.monsite.com/http-bind?room=test
```

**Comment by saghul** [comment]
What do you see in the Prosody logs?

**Comment by LiloBzH** [comment]
In prosody directory, no file ...

ll /var/log/prosody/
total 0

-----------------

In /var/log/jitsi/jicofo.log

```
Jicofo 2024-01-29 14:30:19.139 GRAVE: [18] [xmpp_connection=client] XmppProvider.doConnect#181: Failed to connect/login: undefined-condition You can read more about the meaning of this stream error at http://xmpp.org/rfcs/rfc6120.html#streams-error-conditions
<stream:error><undefined-condition xmlns='urn:ietf:params:xml:ns:xmpp-streams'/><text>No stream features to proceed with</text></stream:error>
org.jivesoftware.smack.XMPPException$StreamErrorException: undefined-condition You can read more about the meaning of this stream error at http://xmpp.org/rfcs/rfc6120.html#streams-error-conditions
<stream:error><undefined-condition xmlns='urn:ietf:params:xml:ns:xmpp-streams'/><text>No stream features to proceed with</text></stream:error>
        at org.jivesoftware.smack.tcp.XMPPTCPConnection$PacketReader.parsePackets(XMPPTCPConnection.java:984)
        at org.jivesoftware.smack.tcp.XMPPTCPConnection$PacketReader.access$700(XMPPTCPConnection.java:916)
        at org.jivesoftware.smack.tcp.XMPPTCPConnection$PacketReader$1.run(XMPPTCPConnection.java:939)
        at java.base/java.lang.Thread.run(Thread.java:829)
Jicofo 2024-01-29 14:30:19.141 AVERTISSEMENT: [661] org.jivesoftware.smack.AbstractXMPPConnection.callConnectionClosedOnErrorListener: Connection XMPPTCPConnection[not-authenticated] (0) closed with error
org.jivesoftware.smack.XMPPException$StreamErrorException: undefined-condition You can read more about the meaning of this stream error at http://xmpp.org/rfcs/rfc6120.html#streams-error-conditions
<stream:error><undefined-condition xmlns='urn:ietf:params:xml:ns:xmpp-streams'/><text>No stream features to proceed with</text></stream:error>
        at org.jivesoftware.smack.tcp.XMPPTCPConnection$PacketReader.parsePackets(XMPPTCPConnection.java:984)
        at org.jivesoftware.smack.tcp.XMPPTCPConnection$PacketReader.access$700(XMPPTCPConnection.java:916)
        at org.jivesoftware.smack.tcp.XMPPTCPConnection$PacketReader$1.run(XMPPTCPConnection.java:939)
        at java.base/java.lang.Thread.run(Thread.java:829)
Jicofo 2024-01-29 14:30:24.148 GRAVE: [18] [xmpp_connection=client] XmppProvider.doConnect#181: Failed to connect/login: undefined-condition You can read more about the meaning of this stream error at http://xmpp.org/rfcs/rfc6120.html#streams-error-conditions
<stream:error><undefined-condition xmlns='urn:ietf:params:xml:ns:xmpp-streams'/><text>No stream features to proceed with</text></stream:error>
org.jivesoftware.smack.XMPPException$StreamErrorException: undefined-condition You can read more about the meaning of this stream error at http://xmpp.org/rfcs/rfc6120.html#streams-error-conditions
<stream:error><undefined-condition xmlns='urn:ietf:params:xml:ns:xmpp-streams'/><text>No stream features to proceed with</text></stream:error>
        at org.jivesoftware.smack.tcp.XMPPTCPConnection$PacketReader.parsePackets(XMPPTCPConnection.java:984)
        at org.jivesoftware.smack.tcp.XMPPTCPConnection$PacketReader.access$700(XMPPTCPConnection.java:916)
        at org.jivesoftware.smack.tcp.XMPPTCPConnection$PacketReader$1.run(XMPPTCPConnection.java:939)
        at java.base/java.lang.Thread.run(Thread.java:829)
Jicofo 2024-01-29 14:30:24.150 AVERTISSEMENT: [664] org.jivesoftware.smack.AbstractXMPPConnection.callConnectionClosedOnErrorListener: Connection XMPPTCPConnection[not-authenticated] (0) closed with error
org.jivesoftware.smack.XMPPException$StreamErrorException: undefined-condition You can read more about the meaning of this stream error at http://xmpp.org/rfcs/rfc6120.html#streams-error-conditions
<stream:error><undefined-condition xmlns='urn:ietf:params:xml:ns:xmpp-streams'/><text>No stream features to proceed with</text></stream:error>
        at org.jivesoftware.smack.tcp.XMPPTCPConnection$PacketReader.parsePackets(XMPPTCPConnection.java:984)
        at org.jivesoftware.smack.tcp.XMPPTCPConnection$PacketReader.access$700(XMPPTCPConnection.java:916)
        at org.jivesoftware.smack.tcp.XMPPTCPConnection$PacketReader$1.run(XMPPTCPConnection.java:939)
        at java.base/java.lang.Thread.run(Thread.java:829)

```

**Comment by saghul** [comment]
Is prosody actually running?

**Comment by LiloBzH** [comment]
yes

```
root@debian:/etc# service prosody status
● prosody.service - Prosody XMPP Server
     Loaded: loaded (/lib/systemd/system/prosody.service; enabled; vendor preset: enabled)
     Active: active (running) since Mon 2024-01-29 14:15:52 CET; 45min ago
       Docs: https://prosody.im/doc
   Main PID: 43991 (lua5.2)
      Tasks: 1 (limit: 65000)
     Memory: 7.8M
        CPU: 3.285s
     CGroup: /system.slice/prosody.service
             └─43991 lua5.2 /usr/bin/prosody -F

janv. 29 15:01:42 debian prosody[43991]: c2s55f3f76efa50                                                 info        Client disconnected: connection closed
janv. 29 15:01:42 debian prosody[43991]: c2s55f3f7632ac0                                                 info        Client connected
janv. 29 15:01:42 debian prosody[43991]: c2s55f3f7632ac0                                                 warn        No stream features to offer
janv. 29 15:01:42 debian prosody[43991]: c2s55f3f7632ac0                                                 info        Client disconnected: connection closed
janv. 29 15:01:47 debian prosody[43991]: c2s55f3f76cc660                                                 info        Client connected
janv. 29 15:01:47 debian prosody[43991]: c2s55f3f76cc660                                                 warn        No stream features to offer
janv. 29 15:01:47 debian prosody[43991]: c2s55f3f76cc660                                                 info        Client disconnected: connection closed
janv. 29 15:01:47 debian prosody[43991]: c2s55f3f7577fe0                                                 info        Client connected
janv. 29 15:01:47 debian prosody[43991]: c2s55f3f7577fe0                                                 warn        No stream features to offer
janv. 29 15:01:47 debian prosody[43991]: c2s55f3f7577fe0                                                 info        Client disconnected: connection closed
```

**Comment by LiloBzH** [comment]
When i click on Join room, 


```
2024-01-29T14:37:28.890Z [modules/xmpp/xmpp.js] <connectionHandler>:  (TIME) Strophe connecting:	 2713 Logger.js:155:26
XHRPOST
https://jitsi.monsite.com/http-bind?room=coucou
[HTTP/2 200  17ms]

2024-01-29T14:37:28.919Z [modules/xmpp/strophe.util.js] <4794/Ra/yt.Strophe.log>:  Strophe: Server did not yet offer a supported authentication mechanism. Sending a blank poll request. Logger.js:155:26
XHRPOST
https://jitsi.monsite.com/http-bind?room=coucou
[HTTP/2 502  27693ms]

Erreur d’analyse XML : balise ne correspondant pas. Attendu : </hr>.
Emplacement : https://jitsi.monsite.com/http-bind?room=coucou
Numéro de ligne 6, Colonne 3 : http-bind:6:3
2024-01-29T14:37:56.624Z [modules/xmpp/strophe.util.js] <4794/Ra/yt.Strophe.log>:  Strophe: request id 2.1 error 502 happened request id 2.1 error 502 happened Logger.js:155:26
2024-01-29T14:37:56.625Z [modules/xmpp/strophe.util.js] <4794/Ra/yt.Strophe.log>:  Strophe: request errored, status: 502, number of errors: 1 Logger.js:155:26
XHRPOST
https://jitsi.monsite.com/http-bind?room=coucou
[HTTP/2 502  16ms]

Erreur d’analyse XML : balise ne correspondant pas. Attendu : </hr>.
Emplacement : https://jitsi.monsite.com/http-bind?room=coucou
Numéro de ligne 6, Colonne 3 : http-bind:6:3
2024-01-29T14:37:56.668Z [modules/xmpp/strophe.util.js] <4794/Ra/yt.Strophe.log>:  Strophe: request id 3.2 error 502 happened request id 3.2 error 502 happened Logger.js:155:26
2024-01-29T14:37:56.668Z [modules/xmpp/strophe.util.js] <4794/Ra/yt.Strophe.log>:  Strophe: request errored, status: 502, number of errors: 2 Logger.js:155:26
XHRPOST
https://jitsi.monsite.com/http-bind?room=coucou
[HTTP/2 200  18ms]

2024-01-29T14:38:04.731Z [modules/xmpp/strophe.util.js] <4794/Ra/yt.Strophe.log>:  Strophe: BOSH-Connection failed: item-not-found BOSH-Connection failed: item-not-found Logger.js:155:26
2024-01-29T14:38:04.731Z [modules/xmpp/xmpp.js] <connectionHandler>:  (TIME) Strophe connfail[item-not-found]:	 38554
```

**Comment by saghul** [comment]
What do you see if you open the BOSH URL in your browser?

**Comment by LiloBzH** [comment]
https://jitsi.website.com/http-bind exist

```
It works! Now point your BOSH client to this URL to connect to Prosody.

For more information see [Prosody: Setting up BOSH](https://prosody.im/doc/setting_up_bosh).
```

**Comment by saghul** [comment]
That's odd, I have no idea what could go wrong there...

**Comment by LiloBzH** [comment]
:( I've been looking for several hours...

I don't understand either. Prosody doesn't seem to give an answer

**Comment by damencho** [comment]
Can you share the prosody logs after restarting?

**Comment by LiloBzH** [comment]
service prosody restart

and

cat /var/log/syslog | grep prosody


```
Jan 29 17:19:51 chouchen prosody[93851]: mod_posix                                                       #033[1;33mwarn#033[0m#011Received SIGTERM
Jan 29 17:19:51 chouchen prosody[93851]: startup                                                         #033[1minfo#033[0m#011Shutting down: Received SIGTERM
Jan 29 17:19:51 chouchen prosody[93851]: general                                                         #033[1minfo#033[0m#011Shutting down...
Jan 29 17:19:51 chouchen prosody[93851]: general                                                         #033[1minfo#033[0m#011Shutdown status: Cleaning up
Jan 29 17:19:51 chouchen prosody[93851]: general                                                         #033[1minfo#033[0m#011Shutdown complete
Jan 29 17:19:51 chouchen systemd[1]: prosody.service: Succeeded.
Jan 29 17:19:51 chouchen prosody[94599]: startup             #033[1minfo#033[0m#011Hello and welcome to Prosody version 0.11.9
Jan 29 17:19:51 chouchen prosody[94599]: startup             #033[1minfo#033[0m#011Prosody is using the select backend for connection handling
Jan 29 17:19:51 chouchen prosody[94599]: portmanager         #033[1minfo#033[0m#011Activated service 's2s' on [*]:5269, [::]:5269
Jan 29 17:19:51 chouchen prosody[94599]: breakout.jitsi.monsite.com:muc_domain_mapper  #033[1minfo#033[0m#011Loading mod_muc_domain_mapper for host lobby.jitsi.monsite.com!
Jan 29 17:19:51 chouchen prosody[94599]: breakout.jitsi.monsite.com:muc_domain_mapper  #033[1minfo#033[0m#011Loading mod_muc_domain_mapper for host breakout.jitsi.monsite.com!
Jan 29 17:19:51 chouchen prosody[94599]: breakout.jitsi.monsite.com:muc_domain_mapper  #033[1minfo#033[0m#011Loading mod_muc_domain_mapper for host speakerstats.jitsi.monsite.com!
Jan 29 17:19:51 chouchen prosody[94599]: speakerstats.jitsi.monsite.com:speakerstats_component  #033[1minfo#033[0m#011Starting speakerstats for conference.jitsi.monsite.com
Jan 29 17:19:51 chouchen prosody[94599]: speakerstats.jitsi.monsite.com:speakerstats_component  #033[1minfo#033[0m#011Breakout component loaded breakout.jitsi.monsite.com
Jan 29 17:19:51 chouchen prosody[94599]: speakerstats.jitsi.monsite.com:speakerstats_component  #033[1minfo#033[0m#011Hook to muc events on table: 0x55c5f37b8280
Jan 29 17:19:51 chouchen prosody[94599]: breakout.jitsi.monsite.com:muc_domain_mapper           #033[1minfo#033[0m#011Loading mod_muc_domain_mapper for host internal.auth.jitsi.monsite.com!
Jan 29 17:19:51 chouchen prosody[94599]: breakout.jitsi.monsite.com:muc_domain_mapper           #033[1minfo#033[0m#011Loading mod_muc_domain_mapper for host metadata.jitsi.monsite.com!
Jan 29 17:19:51 chouchen prosody[94599]: metadata.jitsi.monsite.com:room_metadata_component     #033[1minfo#033[0m#011Starting room metadata for conference.jitsi.monsite.com
Jan 29 17:19:51 chouchen prosody[94599]: metadata.jitsi.monsite.com:room_metadata_component     #033[1minfo#033[0m#011Hook to muc events on breakout.jitsi.monsite.com
Jan 29 17:19:51 chouchen prosody[94599]: breakout.jitsi.monsite.com:muc_domain_mapper           #033[1minfo#033[0m#011Loading mod_muc_domain_mapper for host avmoderation.jitsi.monsite.com!
Jan 29 17:19:51 chouchen prosody[94599]: avmoderation.jitsi.monsite.com:av_moderation_component  #033[1minfo#033[0m#011Starting av_moderation for conference.jitsi.monsite.com
Jan 29 17:19:51 chouchen prosody[94599]: avmoderation.jitsi.monsite.com:av_moderation_component  #033[1minfo#033[0m#011No muc component found, will listen for it: conference.jitsi.monsite.com
Jan 29 17:19:51 chouchen prosody[94599]: breakout.jitsi.monsite.com:muc_domain_mapper            #033[1minfo#033[0m#011Loading mod_muc_domain_mapper for host endconference.jitsi.monsite.com!
Jan 29 17:19:51 chouchen prosody[94599]: endconference.jitsi.monsite.com:end_conference          #033[1minfo#033[0m#011Starting end_conference for conference.jitsi.monsite.com
Jan 29 17:19:51 chouchen prosody[94599]: breakout.jitsi.monsite.com:muc_domain_mapper            #033[1minfo#033[0m#011Loading mod_muc_domain_mapper for host conferenceduration.jitsi.monsite.com!
Jan 29 17:19:51 chouchen prosody[94599]: conferenceduration.jitsi.monsite.com:conference_duration_component  #033[1minfo#033[0m#011Starting conference duration timer for conference.jitsi.monsite.com
Jan 29 17:19:51 chouchen prosody[94599]: conferenceduration.jitsi.monsite.com:conference_duration_component  #033[1minfo#033[0m#011No muc component found, will listen for it: conference.jitsi.monsite.com
Jan 29 17:19:51 chouchen prosody[94599]: breakout.jitsi.monsite.com:muc_domain_mapper                        #033[1minfo#033[0m#011Loading mod_muc_domain_mapper for host conference.jitsi.monsite.com!
Jan 29 17:19:51 chouchen prosody[94599]: speakerstats.jitsi.monsite.com:speakerstats_component               #033[1minfo#033[0m#011Conference component loaded conference.jitsi.monsite.com
Jan 29 17:19:51 chouchen prosody[94599]: conferenceduration.jitsi.monsite.com:conference_duration_component  #033[1minfo#033[0m#011Hook to muc events on conference.jitsi.monsite.com
Jan 29 17:19:51 chouchen prosody[94599]: avmoderation.jitsi.monsite.com:av_moderation_component              #033[1minfo#033[0m#011Hook to muc events on conference.jitsi.monsite.com
Jan 29 17:19:51 chouchen prosody[94599]: metadata.jitsi.monsite.com:room_metadata_component                  #033[1minfo#033[0m#011Hook to muc events on conference.jitsi.monsite.com
Jan 29 17:19:51 chouchen prosody[94599]: speakerstats.jitsi.monsite.com:speakerstats_component               #033[1minfo#033[0m#011Hook to muc events on table: 0x55c5f38e5f30
Jan 29 17:19:51 chouchen prosody[94599]: speakerstats.jitsi.monsite.com:speakerstats_component               #033[1minfo#033[0m#011Main muc service table: 0x55c5f39164d0
Jan 29 17:19:51 chouchen prosody[94599]: conference.jitsi.monsite.com:muc_domain_mapper                      #033[1minfo#033[0m#011Loading mod_muc_domain_mapper for host lobby.jitsi.monsite.com!
Jan 29 17:19:51 chouchen prosody[94599]: conference.jitsi.monsite.com:muc_domain_mapper                      #033[1minfo#033[0m#011Loading mod_muc_domain_mapper for host breakout.jitsi.monsite.com!
Jan 29 17:19:51 chouchen prosody[94599]: conference.jitsi.monsite.com:muc_domain_mapper                      #033[1minfo#033[0m#011Loading mod_muc_domain_mapper for host speakerstats.jitsi.monsite.com!
Jan 29 17:19:51 chouchen prosody[94599]: conference.jitsi.monsite.com:muc_domain_mapper                      #033[1minfo#033[0m#011Loading mod_muc_domain_mapper for host internal.auth.jitsi.monsite.com!
Jan 29 17:19:51 chouchen prosody[94599]: conference.jitsi.monsite.com:muc_domain_mapper                      #033[1minfo#033[0m#011Loading mod_muc_domain_mapper for host avmoderation.jitsi.monsite.com!
Jan 29 17:19:51 chouchen prosody[94599]: conference.jitsi.monsite.com:muc_domain_mapper                      #033[1minfo#033[0m#011Loading mod_muc_domain_mapper for host endconference.jitsi.monsite.com!
Jan 29 17:19:51 chouchen prosody[94599]: conference.jitsi.monsite.com:muc_domain_mapper                      #033[1minfo#033[0m#011Loading mod_muc_domain_mapper for host conference.jitsi.monsite.com!
Jan 29 17:19:51 chouchen prosody[94599]: conference.jitsi.monsite.com:muc_domain_mapper                      #033[1minfo#033[0m#011Loading mod_muc_domain_mapper for host conferenceduration.jitsi.monsite.com!
Jan 29 17:19:51 chouchen prosody[94599]: conference.jitsi.monsite.com:muc_domain_mapper                      #033[1minfo#033[0m#011Loading mod_muc_domain_mapper for host metadata.jitsi.monsite.com!
Jan 29 17:19:51 chouchen prosody[94599]: breakout.jitsi.monsite.com:muc_domain_mapper                        #033[1minfo#033[0m#011Loading mod_muc_domain_mapper for host focus.jitsi.monsite.com!
Jan 29 17:19:51 chouchen prosody[94599]: conference.jitsi.monsite.com:muc_domain_mapper                      #033[1minfo#033[0m#011Loading mod_muc_domain_mapper for host focus.jitsi.monsite.com!
Jan 29 17:19:51 chouchen prosody[94599]: breakout.jitsi.monsite.com:muc_domain_mapper                        #033[1minfo#033[0m#011Loading mod_muc_domain_mapper for host auth.jitsi.monsite.com!
Jan 29 17:19:51 chouchen prosody[94599]: conference.jitsi.monsite.com:muc_domain_mapper                      #033[1minfo#033[0m#011Loading mod_muc_domain_mapper for host auth.jitsi.monsite.com!
Jan 29 17:19:51 chouchen prosody[94599]: portmanager                                                     #033[1minfo#033[0m#011Activated service 'c2s' on [*]:5222, [::]:5222
Jan 29 17:19:51 chouchen prosody[94599]: portmanager                                                     #033[1minfo#033[0m#011Activated service 'legacy_ssl' on no ports
Jan 29 17:19:51 chouchen prosody[94599]: breakout.jitsi.monsite.com:muc_domain_mapper                        #033[1minfo#033[0m#011Loading mod_muc_domain_mapper for host jitsi.monsite.com!
Jan 29 17:19:51 chouchen prosody[94599]: conference.jitsi.monsite.com:muc_domain_mapper                      #033[1minfo#033[0m#011Loading mod_muc_domain_mapper for host jitsi.monsite.com!
Jan 29 17:19:51 chouchen prosody[94599]: jitsi.monsite.com:muc_lobby_rooms                                   #033[1minfo#033[0m#011Lobby component loaded lobby.jitsi.monsite.com
Jan 29 17:19:51 chouchen prosody[94599]: jitsi.monsite.com:room_destroy                                      #033[1minfo#033[0m#011loaded
Jan 29 17:19:51 chouchen prosody[94599]: jitsi.monsite.com:muc_breakout_rooms                                #033[1minfo#033[0m#011Breakout rooms component created breakout.jitsi.monsite.com
Jan 29 17:19:51 chouchen prosody[94599]: jitsi.monsite.com:muc_breakout_rooms                                #033[1minfo#033[0m#011Hook to muc events on breakout.jitsi.monsite.com
Jan 29 17:19:51 chouchen prosody[94599]: jitsi.monsite.com:muc_breakout_rooms                                #033[1minfo#033[0m#011Hook to muc events on conference.jitsi.monsite.com
Jan 29 17:19:51 chouchen prosody[94599]: portmanager                                                     #033[1minfo#033[0m#011Activated service 'http' on [*]:5280, [::]:5280
Jan 29 17:19:51 chouchen prosody[94599]: portmanager                                                     #033[1;31merror#033[0m#011Error binding encrypted port for https: No certificate present in SSL/TLS configuration for https port 5281
Jan 29 17:19:51 chouchen prosody[94599]: portmanager                                                     #033[1;31merror#033[0m#011Error binding encrypted port for https: No certificate present in SSL/TLS configuration for https port 5281
Jan 29 17:19:51 chouchen prosody[94599]: portmanager                                                     #033[1minfo#033[0m#011Activated service 'https' on no ports
Jan 29 17:19:53 chouchen prosody[94599]: c2s55c5f3a181c0                                                 #033[1minfo#033[0m#011Client connected
Jan 29 17:19:53 chouchen prosody[94599]: c2s55c5f3a181c0                                                 #033[1;33mwarn#033[0m#011No stream features to offer
Jan 29 17:19:53 chouchen prosody[94599]: c2s55c5f3a181c0                                                 #033[1minfo#033[0m#011Client disconnected: connection closed
Jan 29 17:19:53 chouchen prosody[94599]: c2s55c5f398e750                                                 #033[1minfo#033[0m#011Client connected
Jan 29 17:19:53 chouchen prosody[94599]: c2s55c5f398e750                                                 #033[1;33mwarn#033[0m#011No stream features to offer
Jan 29 17:19:53 chouchen prosody[94599]: c2s55c5f398e750                                                 #033[1minfo#033[0m#011Client disconnected: connection closed

```

**Comment by LiloBzH** [comment]
![2024-01-29_18-33-21_e2b2ac67-8412-4bbd-b8cd-53a4ffb25e03](https://github.com/jitsi/jitsi-meet/assets/4649466/9363efa7-60a8-4324-982f-38dd07ee0a44)

it's as if a connection with a service is not working

**Comment by saghul** [comment]
Can you check if prejoin is enabled? That's in config.js.

**Comment by LiloBzH** [comment]
![2024-01-29_19-02-46_d27f8bc8-719f-4925-9f5d-c3d7086cdbdc](https://github.com/jitsi/jitsi-meet/assets/4649466/6682c6a1-16dc-477b-b61c-28cc3794c4f8)


Try to connect i suppose

**Comment by LiloBzH** [comment]
so i found something.

my prosody conf is quite empty

`Include "conf.d/*.cfg.lua"`

I managed to find the conf file in an old backup and there are a lot of lines!

**Comment by LiloBzH** [comment]
and it works now

I had seen that the "prosody.cfg.lua" file only contained the INCLUDE but I thought that the conf had been moved to the conf.d...

Strange that this file is found without any conf during a new installation.

Anyway, thanks for the help and sorry :s

**Comment by MorganReid** [comment]
> and it works now
> 
> I had seen that the "prosody.cfg.lua" file only contained the INCLUDE but I thought that the conf had been moved to the conf.d...
> 
> Strange that this file is found without any conf during a new installation.
> 
> Anyway, thanks for the help and sorry :s

I encountered the same problem as you, how did you solve it? Manually modify` /etc/prosody/prosody.cfg.lua`?

**Comment by athenadever** [comment]
> so i found something.
> 
> my prosody conf is quite empty
> 
> `Include "conf.d/*.cfg.lua"`
> 
> I managed to find the conf file in an old backup and there are a lot of lines!

@LiloBzH Hi
Can you show me how to set prosody conf file?
My file has one line.
Thanks
