### ISSUE TITLE
Android 14 constantly asks to start recording/casting

### ISSUE THREAD

**Issue by mehtanitish875** [jitsi/jitsi-meet#14464]
I am using Jitsi version 8.6.1 in android. I am facing issue constantly asks to start recording/casting
Steps to reproduce:

1.Join two users in same room.
2.Share screen almost  30 minutes continuously then I am facing issue constantly asks to start recording/casting.

please suggest me how to fix following issue.

**Comment by saghul** [comment]
Please try SDK 9.0.0. SDK 8 didn't properly support targetting Android 14. SDK 9 does.

**Comment by mehtanitish875** [comment]
I tried with SDK 9.0.0 version but I still screen share is not stable with 9

**Comment by saghul** [comment]
Please share logs.

**Comment by mehtanitish875** [comment]
please check logs

     V  Inactivity, disconnecting from the service
2024-03-12 10:02:30.930  4795-5544  com.oney.W...bRTCModule com.cbc                              E  Error in uvc camera enumeration
                                                                                                    java.lang.IllegalArgumentException: com.cbc: Targeting U+ (version 34 and above) disallows creating or retrieving a PendingIntent with FLAG_MUTABLE, an implicit Intent within and without FLAG_NO_CREATE and FLAG_ALLOW_UNSAFE_IMPLICIT_INTENT for security reasons. To retrieve an already existing PendingIntent, use FLAG_NO_CREATE, however, to create a new PendingIntent with an implicit Intent use FLAG_IMMUTABLE.
                                                                                                    	at android.os.Parcel.createExceptionOrNull(Parcel.java:3061)
                                                                                                    	at android.os.Parcel.createException(Parcel.java:3041)
                                                                                                    	at android.os.Parcel.readException(Parcel.java:3024)
                                                                                                    	at android.os.Parcel.readException(Parcel.java:2966)
                                                                                                    	at android.app.IActivityManager$Stub$Proxy.getIntentSenderWithFeature(IActivityManager.java:6597)
                                                                                                    	at android.app.PendingIntent.getBroadcastAsUser(PendingIntent.java:757)
                                                                                                    	at android.app.PendingIntent.getBroadcast(PendingIntent.java:740)
                                                                                                    	at com.jiangdg.usb.USBMonitor.register(USBMonitor.java:181)
                                                                                                    	at com.jiangdg.ausbc.camera.CameraUvcStrategy.register(CameraUvcStrategy.kt:506)
                                                                                                    	at com.jiangdg.ausbc.camera.CameraUvcStrategy.<init>(CameraUvcStrategy.kt:66)
                                                                                                    	at com.oney.WebRTCModule.UVCCamera2Enumerator.getDeviceNames(UVCCamera2Enumerator.java:45)
                                                                                                    	at com.oney.WebRTCModule.GetUserMediaImpl.enumerateDevices(GetUserMediaImpl.java:147)
                                                                                                    	at com.oney.WebRTCModule.WebRTCModule.lambda$enumerateDevices$12$com-oney-WebRTCModule-WebRTCModule(WebRTCModule.java:787)
                                                                                                    	at com.oney.WebRTCModule.WebRTCModule$$ExternalSyntheticLambda15.run(Unknown Source:4)
                                                                                                    	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
                                                                                                    	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:644)
                                                                                                    	at java.lang.Thread.run(Thread.java:1012)
                                                                                                    Caused by: android.os.RemoteException: Remote stack trace:
                                                                                                    	at com.android.server.am.ActivityManagerService.getIntentSenderWithFeatureAsApp(ActivityManagerService.java:5333)
                                                                                                    	at com.android.server.am.ActivityManagerService.getIntentSenderWithFeature(ActivityManagerService.java:5276)
                                                                                                    	at android.app.IActivityManager$Stub.onTransact(IActivityManager.java:3266)
                                                                                                    	at com.android.server.am.ActivityManagerService.onTransact(ActivityManagerService.java:2763)
                                                                                                    	at android.os.Binder.execTransactInternal(Binder.java:1358)
2024-03-12 10:02:33.940  4795-5544  com.oney.W...bRTCModule com.cbc                              E  Error in uvc camera enumeration
                                                                                                    java.lang.IllegalArgumentException: com.cbc: Targeting U+ (version 34 and above) disallows creating or retrieving a PendingIntent with FLAG_MUTABLE, an implicit Intent within and without FLAG_NO_CREATE and FLAG_ALLOW_UNSAFE_IMPLICIT_INTENT for security reasons. To retrieve an already existing PendingIntent, use FLAG_NO_CREATE, however, to create a new PendingIntent with an implicit Intent use FLAG_IMMUTABLE.
                                                                                                    	at android.os.Parcel.createExceptionOrNull(Parcel.java:3061)
                                                                                                    	at android.os.Parcel.createException(Parcel.java:3041)
                                                                                                    	at android.os.Parcel.readException(Parcel.java:3024)
                                                                                                    	at android.os.Parcel.readException(Parcel.java:2966)
                                                                                                    	at android.app.IActivityManager$Stub$Proxy.getIntentSenderWithFeature(IActivityManager.java:6597)
                                                                                                    	at android.app.PendingIntent.getBroadcastAsUser(PendingIntent.java:757)
                                                                                                    	at android.app.PendingIntent.getBroadcast(PendingIntent.java:740)
                                                                                                    	at com.jiangdg.usb.USBMonitor.register(USBMonitor.java:181)
                                                                                                    	at com.jiangdg.ausbc.camera.CameraUvcStrategy.register(CameraUvcStrategy.kt:506)
                                                                                                    	at com.jiangdg.ausbc.camera.CameraUvcStrategy.<init>(CameraUvcStrategy.kt:66)
                                                                                                    	at com.oney.WebRTCModule.UVCCamera2Enumerator.getDeviceNames(UVCCamera2Enumerator.java:45)
                                                                                                    	at com.oney.WebRTCModule.GetUserMediaImpl.enumerateDevices(GetUserMediaImpl.java:147)
                                                                                                    	at com.oney.WebRTCModule.WebRTCModule.lambda$enumerateDevices$12$com-oney-WebRTCModule-WebRTCModule(WebRTCModule.java:787)
                                                                                                    	at com.oney.WebRTCModule.WebRTCModule$$ExternalSyntheticLambda15.run(Unknown Source:4)
                                                                                                    	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
                                                                                                    	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:644)
                                                                                                    	at java.lang.Thread.run(Thread.java:1012)
                                                                                                    Caused by: android.os.RemoteException: Remote stack trace:
                                                                                                    	at com.android.server.am.ActivityManagerService.getIntentSenderWithFeatureAsApp(ActivityManagerService.java:5333)
                                                                                                    	at com.android.server.am.ActivityManagerService.getIntentSenderWithFeature(ActivityManagerService.java:5276)
                                                                                                    	at android.app.IActivityManager$Stub.onTransact(IActivityManager.java:3266)
                                                                                                    	at com.android.server.am.ActivityManagerService.onTransact(ActivityManagerService.java:2763)
                                                                                                    	at android.os.Binder.execTransactInternal(Binder.java:1358)
2024-03-12 10:02:36.962  4795-5544  com.oney.W...bRTCModule com.cbc                              E  Error in uvc camera enumeration
                                                                                                    java.lang.IllegalArgumentException: com.cbc: Targeting U+ (version 34 and above) disallows creating or retrieving a PendingIntent with FLAG_MUTABLE, an implicit Intent within and without FLAG_NO_CREATE and FLAG_ALLOW_UNSAFE_IMPLICIT_INTENT for security reasons. To retrieve an already existing PendingIntent, use FLAG_NO_CREATE, however, to create a new PendingIntent with an implicit Intent use FLAG_IMMUTABLE.
                                                                                                    	at android.os.Parcel.createExceptionOrNull(Parcel.java:3061)
                                                                                                    	at android.os.Parcel.createException(Parcel.java:3041)
                                                                                                    	at android.os.Parcel.readException(Parcel.java:3024)
                                                                                                    	at android.os.Parcel.readException(Parcel.java:2966)
                                                                                                    	at android.app.IActivityManager$Stub$Proxy.getIntentSenderWithFeature(IActivityManager.java:6597)
                                                                                                    	at android.app.PendingIntent.getBroadcastAsUser(PendingIntent.java:757)
                                                                                                    	at android.app.PendingIntent.getBroadcast(PendingIntent.java:740)
                                                                                                    	at com.jiangdg.usb.USBMonitor.register(USBMonitor.java:181)
                                                                                                    	at com.jiangdg.ausbc.camera.CameraUvcStrategy.register(CameraUvcStrategy.kt:506)
                                                                                                    	at com.jiangdg.ausbc.camera.CameraUvcStrategy.<init>(CameraUvcStrategy.kt:66)
                                                                                                    	at com.oney.WebRTCModule.UVCCamera2Enumerator.getDeviceNames(UVCCamera2Enumerator.java:45)
                                                                                                    	at com.oney.WebRTCModule.GetUserMediaImpl.enumerateDevices(GetUserMediaImpl.java:147)
                                                                                                    	at com.oney.WebRTCModule.WebRTCModule.lambda$enumerateDevices$12$com-oney-WebRTCModule-WebRTCModule(WebRTCModule.java:787)
                                                                                                    	at com.oney.WebRTCModule.WebRTCModule$$ExternalSyntheticLambda15.run(Unknown Source:4)
                                                                                                    	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
                                                                                                    	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:644)
                                                                                                    	at java.lang.Thread.run(Thread.java:1012)
                                                                                                    Caused by: android.os.RemoteException: Remote stack trace:
                                                                                                    	at com.android.server.am.ActivityManagerService.getIntentSenderWithFeatureAsApp(ActivityManagerService.java:5333)
                                                                                                    	at com.android.server.am.ActivityManagerService.getIntentSenderWithFeature(ActivityManagerService.java:5276)
                                                                                                    	at android.app.IActivityManager$Stub.onTransact(IActivityManager.java:3266)
                                                                                                    	at com.android.server.am.ActivityManagerService.onTransact(ActivityManagerService.java:2763)
                                                                                                    	at android.os.Binder.execTransactInternal(Binder.java:1358)
2024-03-12 10:02:38.306  4795-5403  org.webrtc.Logging      com.cbc                              I  NetworkMonitorAutoDetect: handle: 2503076663309 capabilities changed: [ Transports: WIFI Capabilities: NOT_METERED&INTERNET&NOT_RESTRICTED&TRUSTED&NOT_VPN&VALIDATED&NOT_ROAMING&FOREGROUND&NOT_CONGESTED&NOT_SUSPENDED&NOT_VCN_MANAGED LinkUpBandwidth>=11716Kbps LinkDnBandwidth>=22456Kbps TransportInfo: <SSID: <unknown ssid>, BSSID: 02:00:00:00:00:00, MAC: 02:00:00:00:00:00, IP: /192.168.1.102, Security type: 2, Supplicant state: COMPLETED, Wi-Fi standard: 5, RSSI: -67, Link speed: 260Mbps, Tx Link speed: 260Mbps, Max Supported Tx Link speed: 866Mbps, Rx Link speed: 468Mbps, Max Supported Rx Link speed: 866Mbps, Frequency: 5180MHz, Net ID: -1, Metered hint: false, score: 60, isUsable: true, CarrierMerged: false, SubscriptionId: -1, IsPrimary: -1, Trusted: true, Restricted: false, Ephemeral: false, OEM paid: false, OEM private: false, OSU AP: false, FQDN: <none>, Provider friendly name: <none>, Requesting package name: <none><none>MLO Information: , Is TID-To-Link negotiation supported by the AP: false, AP MLD Address: <none>, AP MLO Link Id: <none>, AP MLO Affiliated links: <none>> SignalStrength: -67 UnderlyingNetworks: Null]
2024-03-12 10:02:39.551  4795-5400  ReactNativeJS           com.cbc                              I  rn-webrtc:pc:DEBUG 0 getStats +10s
2024-03-12 10:02:39.967  4795-5544  com.oney.W...bRTCModule com.cbc                              E  Error in uvc camera enumeration
                                                                                                    java.lang.IllegalArgumentException: com.cbc: Targeting U+ (version 34 and above) disallows creating or retrieving a PendingIntent with FLAG_MUTABLE, an implicit Intent within and without FLAG_NO_CREATE and FLAG_ALLOW_UNSAFE_IMPLICIT_INTENT for security reasons. To retrieve an already existing PendingIntent, use FLAG_NO_CREATE, however, to create a new PendingIntent with an implicit Intent use FLAG_IMMUTABLE.
                                                                                                    	at android.os.Parcel.createExceptionOrNull(Parcel.java:3061)
                                                                                                    	at android.os.Parcel.createException(Parcel.java:3041)
                                                                                                    	at android.os.Parcel.readException(Parcel.java:3024)
                                                                                                    	at android.os.Parcel.readException(Parcel.java:2966)
                                                                                                    	at android.app.IActivityManager$Stub$Proxy.getIntentSenderWithFeature(IActivityManager.java:6597)
                                                                                                    	at android.app.PendingIntent.getBroadcastAsUser(PendingIntent.java:757)
                                                                                                    	at android.app.PendingIntent.getBroadcast(PendingIntent.java:740)
                                                                                                    	at com.jiangdg.usb.USBMonitor.register(USBMonitor.java:181)
                                                                                                    	at com.jiangdg.ausbc.camera.CameraUvcStrategy.register(CameraUvcStrategy.kt:506)
                                                                                                    	at com.jiangdg.ausbc.camera.CameraUvcStrategy.<init>(CameraUvcStrategy.kt:66)
                                                                                                    	at com.oney.WebRTCModule.UVCCamera2Enumerator.getDeviceNames(UVCCamera2Enumerator.java:45)
                                                                                                    	at com.oney.WebRTCModule.GetUserMediaImpl.enumerateDevices(GetUserMediaImpl.java:147)
                                                                                                    	at com.oney.WebRTCModule.WebRTCModule.lambda$enumerateDevices$12$com-oney-WebRTCModule-WebRTCModule(WebRTCModule.java:787)
                                                                                                    	at com.oney.WebRTCModule.WebRTCModule$$ExternalSyntheticLambda15.run(Unknown Source:4)
                                                                                                    	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
                                                                                                    	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:644)
                                                                                                    	at java.lang.Thread.run(Thread.java:1012)
                                                                                                    Caused by: android.os.RemoteException: Remote stack trace:
                                                                                                    	at com.android.server.am.ActivityManagerService.getIntentSenderWithFeatureAsApp(ActivityManagerService.java:5333)
                                                                                                    	at com.android.server.am.ActivityManagerService.getIntentSenderWithFeature(ActivityManagerService.java:5276)
                                                                                                    	at android.app.IActivityManager$Stub.onTransact(IActivityManager.java:3266)
                                                                                                    	at com.android.server.am.ActivityManagerService.onTransact(ActivityManagerService.java:2763)
                                                                                                    	at android.os.Binder.execTransactInternal(Binder.java:1358)
2024-03-12 10:02:42.979  4795-5544  com.oney.W...bRTCModule com.cbc                              E  Error in uvc camera enumeration
                                                                                                    java.lang.IllegalArgumentException: com.cbc: Targeting U+ (version 34 and above) disallows creating or retrieving a PendingIntent with FLAG_MUTABLE, an implicit Intent within and without FLAG_NO_CREATE and FLAG_ALLOW_UNSAFE_IMPLICIT_INTENT for security reasons. To retrieve an already existing PendingIntent, use FLAG_NO_CREATE, however, to create a new PendingIntent with an implicit Intent use FLAG_IMMUTABLE.
                                                                                                    	at android.os.Parcel.createExceptionOrNull(Parcel.java:3061)
                                                                                                    	at android.os.Parcel.createException(Parcel.java:3041)
                                                                                                    	at android.os.Parcel.readException(Parcel.java:3024)
                                                                                                    	at android.os.Parcel.readException(Parcel.java:2966)
                                                                                                    	at android.app.IActivityManager$Stub$Proxy.getIntentSenderWithFeature(IActivityManager.java:6597)
                                                                                                    	at android.app.PendingIntent.getBroadcastAsUser(PendingIntent.java:757)
                                                                                                    	at android.app.PendingIntent.getBroadcast(PendingIntent.java:740)
                                                                                                    	at com.jiangdg.usb.USBMonitor.register(USBMonitor.java:181)
                                                                                                    	at com.jiangdg.ausbc.camera.CameraUvcStrategy.register(CameraUvcStrategy.kt:506)
                                                                                                    	at com.jiangdg.ausbc.camera.CameraUvcStrategy.<init>(CameraUvcStrategy.kt:66)
                                                                                                    	at com.oney.WebRTCModule.UVCCamera2Enumerator.getDeviceNames(UVCCamera2Enumerator.java:45)
                                                                                                    	at com.oney.WebRTCModule.GetUserMediaImpl.enumerateDevices(GetUserMediaImpl.java:147)
                                                                                                    	at com.oney.WebRTCModule.WebRTCModule.lambda$enumerateDevices$12$com-oney-WebRTCModule-WebRTCModule(WebRTCModule.java:787)
                                                                                                    	at com.oney.WebRTCModule.WebRTCModule$$ExternalSyntheticLambda15.run(Unknown Source:4)
                                                                                                    	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
                                                                                                    	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:644)
                                                                                                    	at java.lang.Thread.run(Thread.java:1012)
                                                                                                    Caused by: android.os.RemoteException: Remote stack trace:
                                                                                                    	at com.android.server.am.ActivityManagerService.getIntentSenderWithFeatureAsApp(ActivityManagerService.java:5333)
                                                                                                    	at com.android.server.am.ActivityManagerService.getIntentSenderWithFeature(ActivityManagerService.java:5276)
                                                                                                    	at android.app.IActivityManager$Stub.onTransact(IActivityManager.java:3266)
                                                                                                    	at com.android.server.am.ActivityManagerService.onTransact(ActivityManagerService.

**Comment by saghul** [comment]
Thanks, this is helpful.

**Comment by mehtanitish875** [comment]
please let me if you able to fix this

**Comment by saghul** [comment]
I could not reproduce the original issue. The tracebacks are due to UVC support, which I am fixing, but the permissions prompt problem I have been unable to reproduce.

**Comment by mehtanitish875** [comment]
Version 9.0.0 facing issue with screen share sometimes its working fine but some time showing black screen above shared logs related to black screen

**Comment by saghul** [comment]
I see nothing related to a black screen there, sorry. Perhaps things will be clearer once we get rid of the exception.
