### ISSUE TITLE
[Gradle] Can't build the prod version of app using Jitsi SDK 9.0.0 version

### ISSUE THREAD

**Issue by vadym-mytrenko-923** [jitsi/jitsi-meet#14517]
Hi! After we migrated to Jitsi SDK 9.0.0 version, we couldn't build the production (signed) version of the app. The debug builds work well.

Stack trace from build process error:
`* What went wrong:
Execution failed for task ':app:mergeQaNativeLibs'.
> Could not resolve all files for configuration ':app:qaRuntimeClasspath'.
   > Could not resolve com.facebook.react:react-android:0.72.9.
     Required by:
         project :app > org.jitsi.react:jitsi-meet-sdk:9.0.0
         project :app > org.jitsi.react:jitsi-meet-sdk:9.0.0 > com.facebook.react:react-native-amplitude:2.7.0-jitsi-16324891
         project :app > org.jitsi.react:jitsi-meet-sdk:9.0.0 > com.facebook.react:react-native-giphy:2.3.0-jitsi-16324891
         project :app > org.jitsi.react:jitsi-meet-sdk:9.0.0 > com.facebook.react:react-native-google-signin:10.1.0-jitsi-16324891
         project :app > org.jitsi.react:jitsi-meet-sdk:9.0.0 > com.facebook.react:react-native-async-storage:1.19.4-jitsi-16324891
         project :app > org.jitsi.react:jitsi-meet-sdk:9.0.0 > com.facebook.react:react-native-background-timer:2.4.1-jitsi-16324891
         project :app > org.jitsi.react:jitsi-meet-sdk:9.0.0 > com.facebook.react:react-native-calendar-events:2.2.0-jitsi-16324891
         project :app > org.jitsi.react:jitsi-meet-sdk:9.0.0 > com.facebook.react:react-native-community_clipboard:1.5.1-jitsi-16324891
         project :app > org.jitsi.react:jitsi-meet-sdk:9.0.0 > com.facebook.react:react-native-community_netinfo:11.1.0-jitsi-16324891
         project :app > org.jitsi.react:jitsi-meet-sdk:9.0.0 > com.facebook.react:react-native-default-preference:1.4.4-jitsi-16324891
         project :app > org.jitsi.react:jitsi-meet-sdk:9.0.0 > com.facebook.react:react-native-device-info:10.9.0-jitsi-16324891
         project :app > org.jitsi.react:jitsi-meet-sdk:9.0.0 > com.facebook.react:react-native-gesture-handler:2.9.0-jitsi-16324891
         project :app > org.jitsi.react:jitsi-meet-sdk:9.0.0 > com.facebook.react:react-native-get-random-values:1.9.0-jitsi-16324891
         project :app > org.jitsi.react:jitsi-meet-sdk:9.0.0 > com.facebook.react:react-native-immersive-mode:2.0.1-jitsi-16324891
         project :app > org.jitsi.react:jitsi-meet-sdk:9.0.0 > com.facebook.react:react-native-keep-awake:4.0.0-jitsi-16324891
         project :app > org.jitsi.react:jitsi-meet-sdk:9.0.0 > com.facebook.react:react-native-orientation-locker:1.6.0-jitsi-16324891
         project :app > org.jitsi.react:jitsi-meet-sdk:9.0.0 > com.facebook.react:react-native-pager-view:6.2.0-jitsi-16324891
         project :app > org.jitsi.react:jitsi-meet-sdk:9.0.0 > com.facebook.react:react-native-performance:5.0.0-jitsi-16324891
         project :app > org.jitsi.react:jitsi-meet-sdk:9.0.0 > com.facebook.react:react-native-safe-area-context:4.7.1-jitsi-16324891
         project :app > org.jitsi.react:jitsi-meet-sdk:9.0.0 > com.facebook.react:react-native-screens:3.24.0-jitsi-16324891
         project :app > org.jitsi.react:jitsi-meet-sdk:9.0.0 > com.facebook.react:react-native-slider:4.4.3-jitsi-16324891
         project :app > org.jitsi.react:jitsi-meet-sdk:9.0.0 > com.facebook.react:react-native-sound:0.11.2-jitsi-16324891
         project :app > org.jitsi.react:jitsi-meet-sdk:9.0.0 > com.facebook.react:react-native-splash-screen:3.3.0-jitsi-16324891
         project :app > org.jitsi.react:jitsi-meet-sdk:9.0.0 > com.facebook.react:react-native-svg:13.13.0-jitsi-16324891
         project :app > org.jitsi.react:jitsi-meet-sdk:9.0.0 > com.facebook.react:react-native-video:6.0.0-alpha.11-jitsi-16324891
         project :app > org.jitsi.react:jitsi-meet-sdk:9.0.0 > com.facebook.react:react-native-webrtc:118.0.2-jitsi-16324891
         project :app > org.jitsi.react:jitsi-meet-sdk:9.0.0 > com.facebook.react:react-native-webview:13.5.1-jitsi-16324891
      > No matching variant of com.facebook.react:react-android:0.72.9 was found. The consumer was configured to find a component for use during runtime, preferably optimized for Android, as well as attribute 'com.android.build.api.attributes.BuildTypeAttr' with value 'qa', attribute 'com.android.build.api.attributes.AgpVersionAttr' with value '8.1.1', attribute 'org.jetbrains.kotlin.platform.type' with value 'androidJvm' but:
          - Variant 'debugVariantDefaultApiPublication' capability com.facebook.react:react-android:0.72.9:
              - Incompatible because this component declares a component for use during compile-time, as well as attribute 'com.android.build.api.attributes.BuildTypeAttr' with value 'debug' and the consumer needed a component for use during runtime, as well as attribute 'com.android.build.api.attributes.BuildTypeAttr' with value 'qa'
              - Other compatible attributes:
                  - Doesn't say anything about com.android.build.api.attributes.AgpVersionAttr (required '8.1.1')
                  - Doesn't say anything about its target Java environment (preferred optimized for Android)
                  - Doesn't say anything about org.jetbrains.kotlin.platform.type (required 'androidJvm')
          - Variant 'debugVariantDefaultRuntimePublication' capability com.facebook.react:react-android:0.72.9 declares a component for use during runtime:
              - Incompatible because this component declares a component, as well as attribute 'com.android.build.api.attributes.BuildTypeAttr' with value 'debug' and the consumer needed a component, as well as attribute 'com.android.build.api.attributes.BuildTypeAttr' with value 'qa'
              - Other compatible attributes:
                  - Doesn't say anything about com.android.build.api.attributes.AgpVersionAttr (required '8.1.1')
                  - Doesn't say anything about its target Java environment (preferred optimized for Android)
                  - Doesn't say anything about org.jetbrains.kotlin.platform.type (required 'androidJvm')
          - Variant 'debugVariantDefaultSourcePublication' capability com.facebook.react:react-android:0.72.9 declares a component for use during runtime:
              - Incompatible because this component declares a component, as well as attribute 'com.android.build.api.attributes.BuildTypeAttr' with value 'debug' and the consumer needed a component, as well as attribute 'com.android.build.api.attributes.BuildTypeAttr' with value 'qa'
              - Other compatible attributes:
                  - Doesn't say anything about com.android.build.api.attributes.AgpVersionAttr (required '8.1.1')
                  - Doesn't say anything about its target Java environment (preferred optimized for Android)
                  - Doesn't say anything about org.jetbrains.kotlin.platform.type (required 'androidJvm')
          - Variant 'releaseVariantDefaultApiPublication' capability com.facebook.react:react-android:0.72.9:
              - Incompatible because this component declares a component for use during compile-time, as well as attribute 'com.android.build.api.attributes.BuildTypeAttr' with value 'release' and the consumer needed a component for use during runtime, as well as attribute 'com.android.build.api.attributes.BuildTypeAttr' with value 'qa'
              - Other compatible attributes:
                  - Doesn't say anything about com.android.build.api.attributes.AgpVersionAttr (required '8.1.1')
                  - Doesn't say anything about its target Java environment (preferred optimized for Android)
                  - Doesn't say anything about org.jetbrains.kotlin.platform.type (required 'androidJvm')
          - Variant 'releaseVariantDefaultRuntimePublication' capability com.facebook.react:react-android:0.72.9 declares a component for use during runtime:
              - Incompatible because this component declares a component, as well as attribute 'com.android.build.api.attributes.BuildTypeAttr' with value 'release' and the consumer needed a component, as well as attribute 'com.android.build.api.attributes.BuildTypeAttr' with value 'qa'
              - Other compatible attributes:
                  - Doesn't say anything about com.android.build.api.attributes.AgpVersionAttr (required '8.1.1')
                  - Doesn't say anything about its target Java environment (preferred optimized for Android)
                  - Doesn't say anything about org.jetbrains.kotlin.platform.type (required 'androidJvm')
          - Variant 'releaseVariantDefaultSourcePublication' capability com.facebook.react:react-android:0.72.9 declares a component for use during runtime:
              - Incompatible because this component declares a component, as well as attribute 'com.android.build.api.attributes.BuildTypeAttr' with value 'release' and the consumer needed a component, as well as attribute 'com.android.build.api.attributes.BuildTypeAttr' with value 'qa'
              - Other compatible attributes:
                  - Doesn't say anything about com.android.build.api.attributes.AgpVersionAttr (required '8.1.1')
                  - Doesn't say anything about its target Java environment (preferred optimized for Android)
                  - Doesn't say anything about org.jetbrains.kotlin.platform.type (required 'androidJvm')`
                  
Gradle version 8.0.0, Gradle Plugin version 8.1.1 (also reproducible for 7.4.2). 
Java 8, 11, 17 -- no matter which version is set.

Can't find the solution to build correctly, please help.

**Comment by saghul** [comment]
Do you have the jitpack maven repo enabled?

**Comment by vadym-mytrenko-923** [comment]
<img width="753" alt="image" src="https://github.com/jitsi/jitsi-meet/assets/159130206/cb437d65-71e4-4785-a2f6-ceda13a02e55">

Yes, we have.

**Comment by saghul** [comment]
Hum that's odd, that's where RN publishes their builds now...

**Comment by vadym-mytrenko-923** [comment]
Is some specific gradle/java version required for Jitsi SDK 9.0.0?

**Comment by saghul** [comment]
Not really...

**Comment by vadym-mytrenko-923** [comment]
Can you please check if the sample app with Jitsi 9.0.0 is building signed build correctly?  If yes, can you please share Gradle files and versions to compare with our app and find the discrepancy? Thank you in advance.

**Comment by vadym-mytrenko-923** [comment]
After a long investigation, found that it's not a Jitsi problem. We have 5 different named build types, but only debug and release were building. So moved build types to product flavors and all works well. Sorry :)

**Comment by saghul** [comment]
No worries, good to hear!

**Comment by Holofox** [comment]
Hello, @vadym-mytrenko-923! Can you show an example of what ultimately needs to be done to make it work?

I'm facing a similar problem:

<details>
  <summary>Logs</summary>

```
FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':jitsi_meet_flutter_sdk:generateProfileRFile'.
> Could not resolve all files for configuration ':jitsi_meet_flutter_sdk:profileCompileClasspath'.
   > Could not resolve com.facebook.react:react-android:0.72.9.
     Required by:
         project :jitsi_meet_flutter_sdk > org.jitsi.react:jitsi-meet-sdk:9.1.0
         project :jitsi_meet_flutter_sdk > com.facebook.react:react-native-amplitude:2.7.0-jitsi-16575664
         project :jitsi_meet_flutter_sdk > com.facebook.react:react-native-giphy:2.3.0-jitsi-16575664
         project :jitsi_meet_flutter_sdk > com.facebook.react:react-native-google-signin:10.1.0-jitsi-16575664
         project :jitsi_meet_flutter_sdk > com.facebook.react:react-native-async-storage:1.19.4-jitsi-16575664
         project :jitsi_meet_flutter_sdk > com.facebook.react:react-native-background-timer:2.4.1-jitsi-16575664
         project :jitsi_meet_flutter_sdk > com.facebook.react:react-native-calendar-events:2.2.0-jitsi-16575664
         project :jitsi_meet_flutter_sdk > com.facebook.react:react-native-community_clipboard:1.5.1-jitsi-16575664
         project :jitsi_meet_flutter_sdk > com.facebook.react:react-native-community_netinfo:11.1.0-jitsi-16575664
         project :jitsi_meet_flutter_sdk > com.facebook.react:react-native-default-preference:1.4.4-jitsi-16575664
         project :jitsi_meet_flutter_sdk > com.facebook.react:react-native-device-info:10.9.0-jitsi-16575664
         project :jitsi_meet_flutter_sdk > com.facebook.react:react-native-gesture-handler:2.9.0-jitsi-16575664
         project :jitsi_meet_flutter_sdk > com.facebook.react:react-native-get-random-values:1.9.0-jitsi-16575664
         project :jitsi_meet_flutter_sdk > com.facebook.react:react-native-immersive-mode:2.0.1-jitsi-16575664
         project :jitsi_meet_flutter_sdk > com.facebook.react:react-native-keep-awake:4.0.0-jitsi-16575664
         project :jitsi_meet_flutter_sdk > com.facebook.react:react-native-orientation-locker:1.6.0-jitsi-16575664
         project :jitsi_meet_flutter_sdk > com.facebook.react:react-native-pager-view:6.2.0-jitsi-16575664
         project :jitsi_meet_flutter_sdk > com.facebook.react:react-native-performance:5.0.0-jitsi-16575664
         project :jitsi_meet_flutter_sdk > com.facebook.react:react-native-safe-area-context:4.7.1-jitsi-16575664
         project :jitsi_meet_flutter_sdk > com.facebook.react:react-native-screens:3.24.0-jitsi-16575664
         project :jitsi_meet_flutter_sdk > com.facebook.react:react-native-slider:4.4.3-jitsi-16575664
         project :jitsi_meet_flutter_sdk > com.facebook.react:react-native-sound:0.11.2-jitsi-16575664
         project :jitsi_meet_flutter_sdk > com.facebook.react:react-native-splash-screen:3.3.0-jitsi-16575664
         project :jitsi_meet_flutter_sdk > com.facebook.react:react-native-svg:13.13.0-jitsi-16575664
         project :jitsi_meet_flutter_sdk > com.facebook.react:react-native-video:6.0.0-alpha.11-jitsi-16575664
         project :jitsi_meet_flutter_sdk > com.facebook.react:react-native-webrtc:118.0.3-jitsi-16575664
         project :jitsi_meet_flutter_sdk > com.facebook.react:react-native-webview:13.5.1-jitsi-16575664
      > No matching variant of com.facebook.react:react-android:0.72.9 was found. The consumer was configured to find an API of a component, preferably optimized for Android, as well as attribute 'com.android.build.api.attributes.BuildTypeAttr' with value 'profile', attribute 'com.android.build.api.attributes.AgpVersionAttr' with value '7.3.1', attribute 'org.jetbrains.kotlin.platform.type' with value 'androidJvm' but:
          - Variant 'debugVariantDefaultApiPublication' capability com.facebook.react:react-android:0.72.9 declares an API of a component:
              - Incompatible because this component declares a component, as well as attribute 'com.android.build.api.attributes.BuildTypeAttr' with value 'debug' and the consumer needed a component, as well as attribute 'com.android.build.api.attributes.BuildTypeAttr' with value 'profile'
              - Other compatible attributes:
                  - Doesn't say anything about com.android.build.api.attributes.AgpVersionAttr (required '7.3.1')
                  - Doesn't say anything about its target Java environment (preferred optimized for Android)
                  - Doesn't say anything about org.jetbrains.kotlin.platform.type (required 'androidJvm')
          - Variant 'debugVariantDefaultRuntimePublication' capability com.facebook.react:react-android:0.72.9 declares a runtime of a component:
              - Incompatible because this component declares a component, as well as attribute 'com.android.build.api.attributes.BuildTypeAttr' with value 'debug' and the consumer needed a component, as well as attribute 'com.android.build.api.attributes.BuildTypeAttr' with value 'profile'
              - Other compatible attributes:
                  - Doesn't say anything about com.android.build.api.attributes.AgpVersionAttr (required '7.3.1')
                  - Doesn't say anything about its target Java environment (preferred optimized for Android)
                  - Doesn't say anything about org.jetbrains.kotlin.platform.type (required 'androidJvm')
          - Variant 'debugVariantDefaultSourcePublication' capability com.facebook.react:react-android:0.72.9 declares a runtime of a component:
              - Incompatible because this component declares a component, as well as attribute 'com.android.build.api.attributes.BuildTypeAttr' with value 'debug' and the consumer needed a component, as well as attribute 'com.android.build.api.attributes.BuildTypeAttr' with value 'profile'
              - Other compatible attributes:
                  - Doesn't say anything about com.android.build.api.attributes.AgpVersionAttr (required '7.3.1')
                  - Doesn't say anything about its target Java environment (preferred optimized for Android)
                  - Doesn't say anything about org.jetbrains.kotlin.platform.type (required 'androidJvm')
          - Variant 'releaseVariantDefaultApiPublication' capability com.facebook.react:react-android:0.72.9 declares an API of a component:
              - Incompatible because this component declares a component, as well as attribute 'com.android.build.api.attributes.BuildTypeAttr' with value 'release' and the consumer needed a component, as well as attribute 'com.android.build.api.attributes.BuildTypeAttr' with value 'profile'
              - Other compatible attributes:
                  - Doesn't say anything about com.android.build.api.attributes.AgpVersionAttr (required '7.3.1')
                  - Doesn't say anything about its target Java environment (preferred optimized for Android)
                  - Doesn't say anything about org.jetbrains.kotlin.platform.type (required 'androidJvm')
          - Variant 'releaseVariantDefaultRuntimePublication' capability com.facebook.react:react-android:0.72.9 declares a runtime of a component:
              - Incompatible because this component declares a component, as well as attribute 'com.android.build.api.attributes.BuildTypeAttr' with value 'release' and the consumer needed a component, as well as attribute 'com.android.build.api.attributes.BuildTypeAttr' with value 'profile'
              - Other compatible attributes:
                  - Doesn't say anything about com.android.build.api.attributes.AgpVersionAttr (required '7.3.1')
                  - Doesn't say anything about its target Java environment (preferred optimized for Android)
                  - Doesn't say anything about org.jetbrains.kotlin.platform.type (required 'androidJvm')
          - Variant 'releaseVariantDefaultSourcePublication' capability com.facebook.react:react-android:0.72.9 declares a runtime of a component:
              - Incompatible because this component declares a component, as well as attribute 'com.android.build.api.attributes.BuildTypeAttr' with value 'release' and the consumer needed a component, as well as attribute 'com.android.build.api.attributes.BuildTypeAttr' with value 'profile'
              - Other compatible attributes:
                  - Doesn't say anything about com.android.build.api.attributes.AgpVersionAttr (required '7.3.1')
                  - Doesn't say anything about its target Java environment (preferred optimized for Android)
                  - Doesn't say anything about org.jetbrains.kotlin.platform.type (required 'androidJvm')

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 7s
Error: Gradle task assembleProfile failed with exit code 1
#0      throwToolExit (package:flutter_tools/src/base/common.dart:10:3)
#1      AndroidGradleBuilder.buildGradleApp (package:flutter_tools/src/android/gradle.dart:506:9)
<asynchronous suspension>
#2      AndroidGradleBuilder.buildApk (package:flutter_tools/src/android/gradle.dart:224:5)
<asynchronous suspension>
#3      AndroidDevice.startApp (package:flutter_tools/src/android/android_device.dart:581:7)
<asynchronous suspension>
#4      FlutterDevice.runCold (package:flutter_tools/src/resident_runner.dart:532:33)
<asynchronous suspension>
#5      ColdRunner.run (package:flutter_tools/src/run_cold.dart:57:28)
<asynchronous suspension>
#6      AppDomain.launch.<anonymous closure> (package:flutter_tools/src/commands/daemon.dart:801:9)
<asynchronous suspension>
#7      AppDomain.launch (package:flutter_tools/src/commands/daemon.dart:799:5)
<asynchronous suspension>
#8      RunCommand.runCommand (package:flutter_tools/src/commands/run.dart:709:15)
<asynchronous suspension>
#9      FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:1389:27)
<asynchronous suspension>
#10     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:153:19)
<asynchronous suspension>
#11     CommandRunner.runCommand (package:args/command_runner.dart:212:13)
<asynchronous suspension>
#12     FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:355:9)
<asynchronous suspension>
#13     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:153:19)
<asynchronous suspension>
#14     FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:295:5)
<asynchronous suspension>
#15     run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:119:9)
<asynchronous suspension>
#16     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:153:19)
<asynchronous suspension>
#17     main (package:flutter_tools/executable.dart:90:3)
<asynchronous suspension>
```

</details>

**Comment by vinay11sight** [comment]
Hello, I am also facing same issue with version 9.2.1.

```
Could not determine the dependencies of task ':sdkApp:compileDebugKotlin'.
> Could not resolve all files for configuration ':sdkApp:developmentRuntimeClasspath'.
   > Could not resolve com.facebook.react:react-android:0.72.9.
     Required by:
         project :sdkApp > org.jitsi.react:jitsi-meet-sdk:9.2.1
         project :sdkApp > org.jitsi.react:jitsi-meet-sdk:9.2.1 > com.facebook.react:react-native-amplitude:2.7.0-jitsi-17110821
         project :sdkApp > org.jitsi.react:jitsi-meet-sdk:9.2.1 > com.facebook.react:react-native-giphy:2.3.0-jitsi-17110821
         project :sdkApp > org.jitsi.react:jitsi-meet-sdk:9.2.1 > com.facebook.react:react-native-google-signin:10.1.0-jitsi-17110821
         project :sdkApp > org.jitsi.react:jitsi-meet-sdk:9.2.1 > com.facebook.react:react-native-async-storage:1.19.4-jitsi-17110821
         project :sdkApp > org.jitsi.react:jitsi-meet-sdk:9.2.1 > com.facebook.react:react-native-background-timer:2.4.1-jitsi-17110821
         project :sdkApp > org.jitsi.react:jitsi-meet-sdk:9.2.1 > com.facebook.react:react-native-calendar-events:2.2.0-jitsi-17110821
         project :sdkApp > org.jitsi.react:jitsi-meet-sdk:9.2.1 > com.facebook.react:react-native-community_clipboard:1.5.1-jitsi-17110821
         project :sdkApp > org.jitsi.react:jitsi-meet-sdk:9.2.1 > com.facebook.react:react-native-community_netinfo:11.1.0-jitsi-17110821
         project :sdkApp > org.jitsi.react:jitsi-meet-sdk:9.2.1 > com.facebook.react:react-native-default-preference:1.4.4-jitsi-17110821
         project :sdkApp > org.jitsi.react:jitsi-meet-sdk:9.2.1 > com.facebook.react:react-native-device-info:10.9.0-jitsi-17110821
         project :sdkApp > org.jitsi.react:jitsi-meet-sdk:9.2.1 > com.facebook.react:react-native-gesture-handler:2.9.0-jitsi-17110821
         project :sdkApp > org.jitsi.react:jitsi-meet-sdk:9.2.1 > com.facebook.react:react-native-get-random-values:1.9.0-jitsi-17110821
         project :sdkApp > org.jitsi.react:jitsi-meet-sdk:9.2.1 > com.facebook.react:react-native-immersive-mode:2.0.1-jitsi-17110821
         project :sdkApp > org.jitsi.react:jitsi-meet-sdk:9.2.1 > com.facebook.react:react-native-keep-awake:4.0.0-jitsi-17110821
         project :sdkApp > org.jitsi.react:jitsi-meet-sdk:9.2.1 > com.facebook.react:react-native-orientation-locker:1.6.0-jitsi-17110821
         project :sdkApp > org.jitsi.react:jitsi-meet-sdk:9.2.1 > com.facebook.react:react-native-pager-view:6.2.0-jitsi-17110821
         project :sdkApp > org.jitsi.react:jitsi-meet-sdk:9.2.1 > com.facebook.react:react-native-performance:5.0.0-jitsi-17110821
         project :sdkApp > org.jitsi.react:jitsi-meet-sdk:9.2.1 > com.facebook.react:react-native-safe-area-context:4.7.1-jitsi-17110821
         project :sdkApp > org.jitsi.react:jitsi-meet-sdk:9.2.1 > com.facebook.react:react-native-screens:3.24.0-jitsi-17110821
         project :sdkApp > org.jitsi.react:jitsi-meet-sdk:9.2.1 > com.facebook.react:react-native-slider:4.4.3-jitsi-17110821
         project :sdkApp > org.jitsi.react:jitsi-meet-sdk:9.2.1 > com.facebook.react:react-native-sound:0.11.2-jitsi-17110821
         project :sdkApp > org.jitsi.react:jitsi-meet-sdk:9.2.1 > com.facebook.react:react-native-splash-screen:3.3.0-jitsi-17110821
         project :sdkApp > org.jitsi.react:jitsi-meet-sdk:9.2.1 > com.facebook.react:react-native-svg:13.13.0-jitsi-17110821
         project :sdkApp > org.jitsi.react:jitsi-meet-sdk:9.2.1 > com.facebook.react:react-native-video:6.0.0-alpha.11-jitsi-17110821
         project :sdkApp > org.jitsi.react:jitsi-meet-sdk:9.2.1 > com.facebook.react:react-native-webrtc:118.0.6-jitsi-17110821
         project :sdkApp > org.jitsi.react:jitsi-meet-sdk:9.2.1 > com.facebook.react:react-native-webview:13.5.1-jitsi-17110821
      > No matching variant of com.facebook.react:react-android:0.72.9 was found. The consumer was configured to find a runtime of a component, preferably optimized for Android, as well as attribute 'com.android.build.api.attributes.BuildTypeAttr' with value 'development', attribute 'org.jetbrains.kotlin.platform.type' with value 'androidJvm' but:
          - Variant 'debugVariantDefaultApiPublication' capability com.facebook.react:react-android:0.72.9:
              - Incompatible because this component declares an API of a component, as well as attribute 'com.android.build.api.attributes.BuildTypeAttr' with value 'debug' and the consumer needed a runtime of a component, as well as attribute 'com.android.build.api.attributes.BuildTypeAttr' with value 'development'
              - Other compatible attributes:
                  - Doesn't say anything about its target Java environment (preferred optimized for Android)
                  - Doesn't say anything about org.jetbrains.kotlin.platform.type (required 'androidJvm')
          - Variant 'debugVariantDefaultRuntimePublication' capability com.facebook.react:react-android:0.72.9 declares a runtime of a component:
              - Incompatible because this component declares a component, as well as attribute 'com.android.build.api.attributes.BuildTypeAttr' with value 'debug' and the consumer needed a component, as well as attribute 'com.android.build.api.attributes.BuildTypeAttr' with value 'development'
              - Other compatible attributes:
                  - Doesn't say anything about its target Java environment (preferred optimized for Android)
                  - Doesn't say anything about org.jetbrains.kotlin.platform.type (required 'androidJvm')
          - Variant 'debugVariantDefaultSourcePublication' capability com.facebook.react:react-android:0.72.9 declares a runtime of a component:
              - Incompatible because this component declares a component, as well as attribute 'com.android.build.api.attributes.BuildTypeAttr' with value 'debug' and the consumer needed a component, as well as attribute 'com.android.build.api.attributes.BuildTypeAttr' with value 'development'
              - Other compatible attributes:
                  - Doesn't say anything about its target Java environment (preferred optimized for Android)
                  - Doesn't say anything about org.jetbrains.kotlin.platform.type (required 'androidJvm')
          - Variant 'releaseVariantDefaultApiPublication' capability com.facebook.react:react-android:0.72.9:
              - Incompatible because this component declares an API of a component, as well as attribute 'com.android.build.api.attributes.BuildTypeAttr' with value 'release' and the consumer needed a runtime of a component, as well as attribute 'com.android.build.api.attributes.BuildTypeAttr' with value 'development'
              - Other compatible attributes:
                  - Doesn't say anything about its target Java environment (preferred optimized for Android)
                  - Doesn't say anything about org.jetbrains.kotlin.platform.type (required 'androidJvm')
          - Variant 'releaseVariantDefaultRuntimePublication' capability com.facebook.react:react-android:0.72.9 declares a runtime of a component:
              - Incompatible because this component declares a component, as well as attribute 'com.android.build.api.attributes.BuildTypeAttr' with value 'release' and the consumer needed a component, as well as attribute 'com.android.build.api.attributes.BuildTypeAttr' with value 'development'
              - Other compatible attributes:
                  - Doesn't say anything about its target Java environment (preferred optimized for Android)
                  - Doesn't say anything about org.jetbrains.kotlin.platform.type (required 'androidJvm')
          - Variant 'releaseVariantDefaultSourcePublication' capability com.facebook.react:react-android:0.72.9 declares a runtime of a component:
              - Incompatible because this component declares a component, as well as attribute 'com.android.build.api.attributes.BuildTypeAttr' with value 'release' and the consumer needed a component, as well as attribute 'com.android.build.api.attributes.BuildTypeAttr' with value 'development'
              - Other compatible attributes:
                  - Doesn't say anything about its target Java environment (preferred optimized for Android)
                  - Doesn't say anything about org.jetbrains.kotlin.platform.type (required 'androidJvm')``
```
