### ISSUE TITLE
Camera not starting in the latest Jitsi Sdk 9.2.2 Android and iOS 

### ISSUE THREAD

**Issue by mdhanif-simformsolutions** [jitsi/jitsi-meet#14730]
### Description:
Unable to start camera in the latest sdk version 9.2.2 for Mobile (Android and iOS). I tried downgrading sdk version to 8.3.1 and it works.

### Steps to reproduce:

1. Start meeting
2. When meeting is connected try enable disable camera it doesn't work

### Expected behavior:

- Camera should be enable/disable as per user's input

### Actual behavior:

Camera is off and it prints below error in log:- 
`Session 0: Exception while stopping repeating: 
                                                                                                    android.hardware.camera2.CameraAccessException: CAMERA_ERROR (3): cancelRequest:630: Camera 1: Error clearing streaming request: Function not implemented (-38)`

### Server information:

- Jitsi Meet version: 9.2.2
- Operating System: Android Pixel 6A (Android 14)

**Comment by mdhanif-simformsolutions** [comment]
It seems to be working in the latest Jitsi App on Playstore, but not sure what is wrong with our side of implementation.

**Comment by saghul** [comment]
Can you please share the full `adb logcat` ?

**Comment by mdhanif-simformsolutions** [comment]
yes sure this is how it looks :- 
`Session 0: Exception while stopping repeating: 
android.hardware.camera2.CameraAccessException: CAMERA_ERROR (3): cancelRequest:630: Camera 1: Error clearing streaming request: Function not implemented (-38)
	at android.hardware.camera2.CameraManager.throwAsPublicException(CameraManager.java:1743)
	at android.hardware.camera2.impl.ICameraDeviceUserWrapper.cancelRequest(ICameraDeviceUserWrapper.java:92)
	at android.hardware.camera2.impl.CameraDeviceImpl.stopRepeating(CameraDeviceImpl.java:1366)
	at android.hardware.camera2.impl.CameraCaptureSessionImpl.close(CameraCaptureSessionImpl.java:579)
	at android.hardware.camera2.impl.CameraCaptureSessionImpl$2.onDisconnected(CameraCaptureSessionImpl.java:805)
	at android.hardware.camera2.impl.CameraDeviceImpl$7.run(CameraDeviceImpl.java:268)
	at android.os.Handler.handleCallback(Handler.java:959)
	at android.os.Handler.dispatchMessage(Handler.java:100)
	at android.os.Looper.loopOnce(Looper.java:232)
	at android.os.Looper.loop(Looper.java:317)
	at android.os.HandlerThread.run(HandlerThread.java:68)
Caused by: android.os.ServiceSpecificException: cancelRequest:630: Camera 1: Error clearing streaming request: Function not implemented (-38) (code 10)
	at android.os.Parcel.createExceptionOrNull(Parcel.java:3196)
	at android.os.Parcel.createException(Parcel.java:3166)
	at android.os.Parcel.readException(Parcel.java:3149)
	at android.os.Parcel.readException(Parcel.java:3091)
	at android.hardware.camera2.ICameraDeviceUser$Stub$Proxy.cancelRequest(ICameraDeviceUser.java:670)
	at android.hardware.camera2.impl.ICameraDeviceUserWrapper.cancelRequest(ICameraDeviceUserWrapper.java:90)
	at android.hardware.camera2.impl.CameraDeviceImpl.stopRepeating(CameraDeviceImpl.java:1366) 
	at android.hardware.camera2.impl.CameraCaptureSessionImpl.close(CameraCaptureSessionImpl.java:579) 
	at android.hardware.camera2.impl.CameraCaptureSessionImpl$2.onDisconnected(CameraCaptureSessionImpl.java:805) 
	at android.hardware.camera2.impl.CameraDeviceImpl$7.run(CameraDeviceImpl.java:268) 
	at android.os.Handler.handleCallback(Handler.java:959) 
	at android.os.Handler.dispatchMessage(Handler.java:100) 
	at android.os.Looper.loopOnce(Looper.java:232) 
	at android.os.Looper.loop(Looper.java:317) 
	at android.os.HandlerThread.run(HandlerThread.java:68) 
`

Just to mention again if I simply downgrade Version back to 8.3.1 It works perfectly fine on the same device.

**Comment by saghul** [comment]
Are you able to reproduce this with the sample app?

**Comment by mdhanif-simformsolutions** [comment]
No I am not, It works good in sample app

**Comment by mdhanif-simformsolutions** [comment]
It's not related to android though, I am having same issue in my iOS app with version number `9.2.2`
Older version works well in iOS as well.

**Comment by saghul** [comment]
Are you connecting to your own server? What versions are you running there? The problem could be that.

**Comment by mdhanif-simformsolutions** [comment]
Hi, yes here are the version details :- 
```
jicofo_1.0-1057-1
jitsi-meet-web_1.0.7658-1
jitsi-meet-prosody_1.0.7658-1
jitsi-meet-web-config_1.0.7658-1
jitsi-meet-turnserver_1.0.7658-1
jitsi-meet-tokens_1.0.7658-1
prosody_0.12.4-1
jitsi-videobridge2_2.3-61-g814bffd6-1
```

**Comment by saghul** [comment]
The config looks ok and has all the backwards compatibility flags there:

```
// Temporary backwards compatibility with old mobile clients.
config.flags = config.flags || {};
config.flags.sourceNameSignaling = true;
config.flags.sendMultipleVideoStreams = true;
config.flags.receiveMultipleVideoStreams = true;
```

I'm out of ideas here :-/

**Comment by mdhanif-simformsolutions** [comment]
Let me try downgrading few versions and check upto which version it works for me, from that maybe we can narrow down the issue

**Comment by mdhanif-simformsolutions** [comment]
@saghul So, I am able to use camera upto version 8.6.1 
Starting from Version 9.0 I am facing issue while starting camera

**Comment by saghul** [comment]
Alright so something is weird. Reviewing the conversation here you say it works with the sample app.

So let's look at how you integrate the SDK into your app.

**Comment by mdhanif-simformsolutions** [comment]
Okay, So currently I am using version `8.3.1`

and here's how we start meeting activity :- 

```
val serverURL: URL = try {
            URL(jitsiServerUrl)
        } catch (e: MalformedURLException) {
            e.printStackTrace()
            return
        }

val jitsiMeetUserInfo =  JitsiMeetUserInfo(
                bundleOf(
                    "displayName" to "Test",
                    "email" to "test@yopmail.com"
                )
            )
val defaultOptions = JitsiMeetConferenceOptions.Builder()
            .setServerURL(serverURL)
            .setToken("addTokenHere")
            .build()
JitsiMeet.setDefaultConferenceOptions(defaultOptions)

val jitsiMeetConferenceOptions = JitsiMeetConferenceOptions.Builder()
            .setUserInfo(jitsiMeetUserInfo)
            .build()
JitsiMeetActivity.launch(this, jitsiMeetConferenceOptions)
```

Let me know if you need any other specific details

**Comment by saghul** [comment]
I don't see the room being set, is that intentional? Also, how does your server URL look like?

**Comment by mdhanif-simformsolutions** [comment]
I don't understand by what you mean `room` here ? do you have any example what do we set ? 
Eg Server Url  :- `https://jitsi.com` 

Also I do set audio, video feature flags but I believe that will entirely remove `Video` button from my toolbar options.

**Comment by saghul** [comment]
In the conference options there is no call to seRoom. You need to specify which room to join.

Or did you miss that when copying the sample text over?

**Comment by mdhanif-simformsolutions** [comment]
Yes, I am sorry I missed that while copying sample text this is how it should look:- 
```
val defaultOptions = JitsiMeetConferenceOptions.Builder()
            .setRoom("roomIdHere")
            .setServerURL(serverURL)
            .setToken("addTokenHere")
            .build()
```

**Comment by saghul** [comment]
Ok, that does look ok. Can you please upload the smallest app that doesn't work for you? I don't know what else to suggest TBH.

**Comment by mdhanif-simformsolutions** [comment]
Yes, I'll try to do that asap

**Comment by mdhanif-simformsolutions** [comment]
Hello, just to update we did few changes in our config file and it's started working again. 
Thanks for all the help.

**Comment by sough** [comment]
> Hello, just to update we did few changes in our config file and it's started working again. Thanks for all the help.

hi, can you share your solution, coz we have the same issue?

**Comment by igorkulman** [comment]
> Hello, just to update we did few changes in our config file and it's started working again. Thanks for all the help.

Can you share the changes?
