### ISSUE TITLE
App crashes as soon a I join a meeting

### ISSUE THREAD

**Issue by Sankalp2114** [jitsi/jitsi-meet#14829]
### What happened?

when i create a new meeting it switches to a new screen and instantly crashes the app i get these logs in terminal 

### Platform

- [ ] Chrome (or Chromium based)
- [ ] Firefox
- [ ] Safari
- [ ] Other desktop browser
- [ ] Android browser
- [ ] iOS browser
- [ ] Electron app
- [X] Android mobile app
- [ ] iOS mobile app
- [ ] Custom app using a mobile SDK

### Browser / app / sdk version

4.0.0

### Relevant log output

```shell
D/JITSI_MEET_PLUGIN(10306): method: joinMeeting
D/JITSI_MEET_PLUGIN(10306): arguments: {videoMuted=true, subject=null, iosAppBarRGBAColor=null, serverURL=null, audioOnly=null, audioMuted=true, userDisplayName=Getscoped, userEmail=getscoped20@gmail.com, room=11418084, token=null, featureFlags={}}
D/JITSI_MEET_PLUGIN(10306): Joining Room: 11418084
D/JITSI_MEET_PLUGIN(10306): Server URL: https://meet.jit.si, https://meet.jit.si
D/OrientationModule(10306): onActivityPaused
W/System  (10306): Ignoring header X-Firebase-Locale because its value was null.
D/OrientationModule(10306): onActivityCreated
D/AndroidRuntime(10306): Shutting down VM
E/AndroidRuntime(10306): FATAL EXCEPTION: main
E/AndroidRuntime(10306): Process: com.example.meetsync, PID: 10306
E/AndroidRuntime(10306): java.lang.RuntimeException: Unable to start activity ComponentInfo{com.example.meetsync/com.gunschu.jitsi_meet.JitsiMeetPluginActivity}: java.lang.IllegalStateException: You need to use a Theme.AppCompat theme (or descendant) with this activity.
E/AndroidRuntime(10306):        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3449)
E/AndroidRuntime(10306):        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3601)
E/AndroidRuntime(10306):        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:85)
E/AndroidRuntime(10306):        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
E/AndroidRuntime(10306):        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
E/AndroidRuntime(10306):        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2066)
E/AndroidRuntime(10306):        at android.os.Handler.dispatchMessage(Handler.java:106)
E/AndroidRuntime(10306):        at android.os.Looper.loop(Looper.java:223)
E/AndroidRuntime(10306):        at android.app.ActivityThread.main(ActivityThread.java:7656)
E/AndroidRuntime(10306):        at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime(10306):        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
E/AndroidRuntime(10306):        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)
E/AndroidRuntime(10306): Caused by: java.lang.IllegalStateException: You need to use a Theme.AppCompat theme (or descendant) with this activity.
E/AndroidRuntime(10306):        at androidx.appcompat.app.AppCompatDelegateImpl.createSubDecor(AppCompatDelegateImpl.java:852)
E/AndroidRuntime(10306):        at androidx.appcompat.app.AppCompatDelegateImpl.ensureSubDecor(AppCompatDelegateImpl.java:815)
E/AndroidRuntime(10306):        at androidx.appcompat.app.AppCompatDelegateImpl.setContentView(AppCompatDelegateImpl.java:703)
E/AndroidRuntime(10306):        at androidx.appcompat.app.AppCompatActivity.setContentView(AppCompatActivity.java:195)
E/AndroidRuntime(10306):        at org.jitsi.meet.sdk.JitsiMeetActivity.onCreate(JitsiMeetActivity.java:103)
E/AndroidRuntime(10306):        at com.gunschu.jitsi_meet.JitsiMeetPluginActivity.onCreate(JitsiMeetPluginActivity.kt:92)
E/AndroidRuntime(10306):        at android.app.Activity.performCreate(Activity.java:8000)
E/AndroidRuntime(10306):        at android.app.Activity.performCreate(Activity.java:7984)
E/AndroidRuntime(10306):        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1309)
E/AndroidRuntime(10306):        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3422)
E/AndroidRuntime(10306):        ... 11 more
E/JitsiMeetSDK(10306): JitsiMeetUncaughtExceptionHandler FATAL ERROR
E/JitsiMeetSDK(10306): java.lang.RuntimeException: Unable to start activity ComponentInfo{com.example.meetsync/com.gunschu.jitsi_meet.JitsiMeetPluginActivity}: java.lang.IllegalStateException: You need to use a Theme.AppCompat theme (or descendant) with this activity.
E/JitsiMeetSDK(10306):  at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3449)
E/JitsiMeetSDK(10306):  at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3601)
E/JitsiMeetSDK(10306):  at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:85)
E/JitsiMeetSDK(10306):  at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
E/JitsiMeetSDK(10306):  at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
E/JitsiMeetSDK(10306):  at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2066)
E/JitsiMeetSDK(10306):  at android.os.Handler.dispatchMessage(Handler.java:106)
E/JitsiMeetSDK(10306):  at android.os.Looper.loop(Looper.java:223)
E/JitsiMeetSDK(10306):  at android.app.ActivityThread.main(ActivityThread.java:7656)
E/JitsiMeetSDK(10306):  at java.lang.reflect.Method.invoke(Native Method)
E/JitsiMeetSDK(10306):  at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
E/JitsiMeetSDK(10306):  at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)
E/JitsiMeetSDK(10306): Caused by: java.lang.IllegalStateException: You need to use a Theme.AppCompat theme (or descendant) with this activity.
E/JitsiMeetSDK(10306):  at androidx.appcompat.app.AppCompatDelegateImpl.createSubDecor(AppCompatDelegateImpl.java:852)
E/JitsiMeetSDK(10306):  at androidx.appcompat.app.AppCompatDelegateImpl.ensureSubDecor(AppCompatDelegateImpl.java:815)
E/JitsiMeetSDK(10306):  at androidx.appcompat.app.AppCompatDelegateImpl.setContentView(AppCompatDelegateImpl.java:703)
E/JitsiMeetSDK(10306):  at androidx.appcompat.app.AppCompatActivity.setContentView(AppCompatActivity.java:195)
E/JitsiMeetSDK(10306):  at org.jitsi.meet.sdk.JitsiMeetActivity.onCreate(JitsiMeetActivity.java:103)
E/JitsiMeetSDK(10306):  at com.gunschu.jitsi_meet.JitsiMeetPluginActivity.onCreate(JitsiMeetPluginActivity.kt:92)
E/JitsiMeetSDK(10306):  at android.app.Activity.performCreate(Activity.java:8000)
E/JitsiMeetSDK(10306):  at android.app.Activity.performCreate(Activity.java:7984)
E/JitsiMeetSDK(10306):  at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1309)
E/JitsiMeetSDK(10306):  at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3422)
E/JitsiMeetSDK(10306):  ... 11 more
E/JitsiMeetSDK(10306):
E/JitsiMeetSDK(10306): java.lang.RuntimeException: Unable to start activity ComponentInfo{com.example.meetsync/com.gunschu.jitsi_meet.JitsiMeetPluginActivity}: java.lang.IllegalStateException: You need to use a Theme.AppCompat theme (or descendant) with this activity.
E/JitsiMeetSDK(10306):  at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3449)
E/JitsiMeetSDK(10306):  at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3601)
E/JitsiMeetSDK(10306):  at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:85)
E/JitsiMeetSDK(10306):  at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
E/JitsiMeetSDK(10306):  at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
E/JitsiMeetSDK(10306):  at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2066)
E/JitsiMeetSDK(10306):  at android.os.Handler.dispatchMessage(Handler.java:106)
E/JitsiMeetSDK(10306):  at android.os.Looper.loop(Looper.java:223)
E/JitsiMeetSDK(10306):  at android.app.ActivityThread.main(ActivityThread.java:7656)
E/JitsiMeetSDK(10306):  at java.lang.reflect.Method.invoke(Native Method)
E/JitsiMeetSDK(10306):  at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
E/JitsiMeetSDK(1DK(10306):  at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
E/JitsiMeetSDK(10306):  at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)
E/JitsiMeetSDK(10306): Caused by: java.lang.IllegalStateException: You need to use a Theme.AppCompat theme (or descendant) with this activity.
E/JitsiMeetSDK(10306):  at androidx.appcompat.app.AppCompatDelegateImpl.createSubDecor(AppCompatDelegateImpl.java:852)
E/JitsiMeetSDK(10306):  at androidx.appcompat.app.AppCompatDelegateImpl.ensureSubDecor(AppCompatDelegateImpl.java:815)
E/JitsiMeetSDK(10306):  at androidx.appcompat.app.AppCompatDelegateImpl.setContentView(AppCompatDelegateImpl.java:703)
E/JitsiMeetSDK(10306):  at androidx.appcompat.app.AppCompatActivity.setContentView(AppCompatActivity.java:195)
E/JitsiMeetSDK(10306):  at org.jitsi.meet.sdk.JitsiMeetActivity.onCreate(JitsiMeetActivity.java:103)
E/JitsiMeetSDK(10306):  at com.gunschu.jitsi_meet.JitsiMeetPluginActivity.onCreate(JitsiMeetPluginActivity.kt:92)
E/JitsiMeetSDK(10306):  at android.app.Activity.performCreate(Activity.java:8000)
E/JitsiMeetSDK(10306):  at android.app.Activity.performCreate(Activity.java:7984)
E/JitsiMeetSDK(10306):  at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1309)
E/JitsiMeetSDK(10306):  at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3422)
E/JitsiMeetSDK(10306):  ... 11 more
I/Process (10306): Sending sign0306):  at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)
E/JitsiMeetSDK(10306): Caused by: java.lang.IllegalStateException: You need to use a Theme.AppCompat theme (or descendant) with this activity.
E/JitsiMeetSDK(10306):  at androidx.appcompat.app.AppCompatDelegateImpl.createSubDecor(AppCompatDelegateImpl.java:852)
E/JitsiMeetSDK(10306):  at androidx.appcompat.app.AppCompatDelegateImpl.ensureSubDecor(AppCompatDelegateImpl.java:815)
E/JitsiMeetSDK(10306):  at androidx.appcompat.app.AppCompatDelegateImpl.setContentView(AppCompatDelegateImpl.java:703)
E/JitsiMeetSDK(10306):  at androidx.appcompat.app.AppCompatActivity.setContentView(AppCompatActivity.java:195)
E/JitsiMeetSDK(10306):  at org.jitsi.meet.sdk.JitsiMeetActivity.onCreate(JitsiMeetActivity.java:103)
E/JitsiMeetSDK(10306):  at com.gunschu.jitsi_meet.JitsiMeetPluginActivity.onCreate(JitsiMeetPluginActivity.kt:92)
E/JitsiMeetSDK(10306):  at android.app.Activity.performCreate(Activity.java:8000)
E/JitsiMeetSDK(10306):  at android.app.Activity.performCreate(Activity.java:7984)
E/JitsiMeetSDK(10306):  at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1309)
E/JitsiMeetSDK(10306):  at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3422)
E/JitsiMeetSDK(10306):  ... 11 more
I/Process (10306): Sending signal. PID: 10306 SIG: 9
Lost connection to device.
```

### Reproducibility

- [ ] The problem is reproducible on meet.jit.si

### More details?

not hosting my own server and im using the latest version 4.0.0

**Comment by saghul** [comment]
What plugin are you using exactly? Can you please share a link? We don't have an SDK version 4.0.0, that was released many years ago.

**Comment by saghul** [comment]
That is not our plugin.

Please try this one: https://pub.dev/packages/jitsi_meet_flutter_sdk

**Comment by Sankalp2114** [comment]
will the same code i was using will work or i will need to make changes did the newer version change how things are done

**Comment by saghul** [comment]
Yes you will need to make changes.

Our version is different from the one that you are using. It's also officially maintained by us, the other package has gone 3 years without updates.

**Comment by Sankalp2114** [comment]
i created a new meeting using the latest sdk when i join a meeting it tells me that there is no moderator in the meeting is there a fix for this ?

**Comment by saghul** [comment]
If you are using meet.jit.si as the server (the default) then no, you need join after a moderator. You can sign up for jaas: jaas.8x8.vc or setup your own jitsi server too.

**Comment by Sankalp2114** [comment]
does jaas allow me to host meeting for a app or only through websites?

**Comment by saghul** [comment]
Both.
