### ISSUE TITLE
Animated node with tag (child) [3078] does not exist

### ISSUE THREAD

**Issue by jindongzhang** [jitsi/jitsi-meet#14855]
### What happened?

It looks like an exception occurred in ReactNative, an animation exception? Occasionally occurs when joining or leaving a meeting, not necessarily.

### Platform

- [ ] Chrome (or Chromium based)
- [ ] Firefox
- [ ] Safari
- [ ] Other desktop browser
- [ ] Android browser
- [ ] iOS browser
- [ ] Electron app
- [X] Android mobile app
- [ ] iOS mobile app
- [ ] Custom app using a mobile SDK

### Browser / app / sdk version

Android 9.2.2

### Relevant log output

```shell
FATAL EXCEPTION: main
                                                                                                    Process: cn.jon.meeting.debug, PID: 9531
                                                                                                    com.facebook.react.bridge.JSApplicationIllegalArgumentException: connectAnimatedNodes: Animated node with tag (child) [3078] does not exist
                                                                                                    	at com.facebook.react.animated.NativeAnimatedNodesManager.connectAnimatedNodes(NativeAnimatedNodesManager.java:364)
                                                                                                    	at com.facebook.react.animated.NativeAnimatedModule$16.execute(NativeAnimatedModule.java:777)
                                                                                                    	at com.facebook.react.animated.NativeAnimatedModule$ConcurrentOperationQueue.executeBatch(NativeAnimatedModule.java:171)
                                                                                                    	at com.facebook.react.animated.NativeAnimatedModule$3.execute(NativeAnimatedModule.java:365)
                                                                                                    	at com.facebook.react.uimanager.UIViewOperationQueue$UIBlockOperation.execute(UIViewOperationQueue.java:579)
                                                                                                    	at com.facebook.react.uimanager.UIViewOperationQueue$1.run(UIViewOperationQueue.java:915)
                                                                                                    	at com.facebook.react.uimanager.UIViewOperationQueue.flushPendingBatches(UIViewOperationQueue.java:1026)
                                                                                                    	at com.facebook.react.uimanager.UIViewOperationQueue.-$$Nest$mflushPendingBatches(Unknown Source:0)
                                                                                                    	at com.facebook.react.uimanager.UIViewOperationQueue$DispatchUIFrameCallback.doFrameGuarded(UIViewOperationQueue.java:1086)
                                                                                                    	at com.facebook.react.uimanager.GuardedFrameCallback.doFrame(GuardedFrameCallback.java:29)
                                                                                                    	at com.facebook.react.modules.core.ReactChoreographer$ReactChoreographerDispatcher.doFrame(ReactChoreographer.java:175)
                                                                                                    	at com.facebook.react.modules.core.ChoreographerCompat$FrameCallback$1.doFrame(ChoreographerCompat.java:85)
                                                                                                    	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1590)
                                                                                                    	at android.view.Choreographer.doCallbacks(Choreographer.java:1256)
                                                                                                    	at android.view.Choreographer.doFrame(Choreographer.java:1120)
                                                                                                    	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1542)
                                                                                                    	at android.os.Handler.handleCallback(Handler.java:966)
                                                                                                    	at android.os.Handler.dispatchMessage(Handler.java:110)
                                                                                                    	at android.os.Looper.loopOnce(Looper.java:205)
                                                                                                    	at android.os.Looper.loop(Looper.java:293)
                                                                                                    	at android.app.ActivityThread.loopProcess(ActivityThread.java:9934)
                                                                                                    	at android.app.ActivityThread.main(ActivityThread.java:9923)
                                                                                                    	at java.lang.reflect.Method.invoke(Native Method)
                                                                                                    	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:586)
                                                                                                    	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1240)
```

### Reproducibility

- [ ] The problem is reproducible on meet.jit.si

### More details?

There is a probability that this problem will occur when joining or leaving the meeting.

**Comment by saghul** [comment]
Alas this is a long-standing issue in React Native, not somethign we can solve here. Please follow https://github.com/facebook/react-native/issues/37267

**Comment by jindongzhang** [comment]
After submitting the issue, I realized that it was caused by ReactNative. Thank you very much!
