### ISSUE TITLE
Custom SDK: App crash when user try to join jitsi meeting

### ISSUE THREAD

**Issue by JagaranMaharjan** [jitsi/jitsi-meet#14995]
### What happened?

**App is crashing when users attempt to join a Jitsi meeting through a custom SDK.**

ARR file generated from branch: **mobile-24.3**

**Following steps was followed while generating sdk:**
1. Added openjdk 17
2. Clone project: https://github.com/jitsi/jitsi-meet.git [Checkout to branch: mobile-24.3]
3. Clone project: https://github.com/jitsi/jitsi-maven-repository
4. Run following command before running release-sdk.sh script
4.1. Gradle build on android [successful]
4.2. npm install
4.3. brew install jq
4.4. brew install maven
4.5. Run the script written on release-sdk.sh
5. Custom sdk generated successful
BUILD SUCCESSFUL in 2s
80 actionable tasks: 80 executed
~/Desktop/test/jitsi-meet/android/scripts
~/Desktop/jitsi/jitsi-maven-repository/releases ~/Desktop/test/jitsi-meet/android/scripts

While implementing custom sdk in project following changes was made:

**on android/build.gradle:**

buildscript {
    ext.kotlin_version = '1.7.21'
    repositories {
        maven {
            url file("$rootDir/jitsi_sdk")
        }
        google()
        jcenter()
        mavenCentral()
    }

    dependencies {
        classpath 'com.android.tools.build:gradle:8.0.1'
        classpath "org.jetbrains.kotlin:kotlin-gradle-plugin:$kotlin_version"
    }
}

rootProject.allprojects {
    repositories {
        maven {
            url file("$rootDir/jitsi_sdk")
        }
        google()
        mavenCentral()
        jcenter()
        maven {
            url 'https://jitpack.io'
        }
    }
}

dependencies {
    implementation "org.jetbrains.kotlin:kotlin-stdlib-jdk7:$kotlin_version"
    implementation('org.jitsi.react:jitsi-meet-sdk:+') {
        transitive = true
    }
}

**jitsi_sdk contains:**
<img width="379" alt="Screenshot 2024-08-09 at 23 45 23" src="https://github.com/user-attachments/assets/41b8fef0-2f98-4a5b-9eb1-6e3fb6a7746f">

### Platform

- [ ] Chrome (or Chromium based)
- [ ] Firefox
- [ ] Safari
- [ ] Other desktop browser
- [ ] Android browser
- [ ] iOS browser
- [ ] Electron app
- [X] Android mobile app
- [ ] iOS mobile app
- [X] Custom app using a mobile SDK

### Browser / app / sdk version

mobile-24.3

### Relevant log output

```shell
I/org.webrtc.Logging(23029): NativeLibrary: Loading native library: jingle_peerconnection_so
I/org.webrtc.Logging(23029): LibraryLoader: Loading library: jingle_peerconnection_so
I/org.webrtc.Logging(23029): PeerConnectionFactory: PeerConnectionFactory was initialized without an injected Loggable. Any existing Loggable will be deleted.
I/AudioEffect(23029): queryNumberEffects(): *numEffects = 16, ret = 0
I/org.webrtc.Logging(23029): WebRtcAudioManagerExternal: Sample rate is set to 48000 Hz
I/org.webrtc.Logging(23029): WebRtcAudioManagerExternal: Sample rate is set to 48000 Hz
I/org.webrtc.Logging(23029): JavaAudioDeviceModule: createAudioDeviceModule
I/org.webrtc.Logging(23029): JavaAudioDeviceModule: HW NS will be used.
I/org.webrtc.Logging(23029): JavaAudioDeviceModule: HW AEC will be used.
I/org.webrtc.Logging(23029): WebRtcAudioEffectsExternal: ctor@[name=create_react_context, id=48751]
I/org.webrtc.Logging(23029): WebRtcAudioRecordExternal: ctor@[name=create_react_context, id=48751]
I/org.webrtc.Logging(23029): WebRtcAudioTrackExternal: ctor@[name=create_react_context, id=48751]
D/com.oney.WebRTCModule.WebRTCModule(23029): Using video encoder factory: com.oney.WebRTCModule.webrtcutils.H264AndSoftwareVideoEncoderFactory
D/com.oney.WebRTCModule.WebRTCModule(23029): Using video decoder factory: com.oney.WebRTCModule.webrtcutils.H264AndSoftwareVideoDecoderFactory
W/AudioCapabilities(23029): Unsupported mime audio/x-adpcm-dvi-ima
W/AudioCapabilities(23029): Unsupported mime audio/x-adpcm-dvi-ima
W/AudioCapabilities(23029): Unsupported mime audio/x-adpcm-ms
W/AudioCapabilities(23029): Unsupported mime audio/x-adpcm-ms
W/AudioCapabilities(23029): Unsupported mime audio/alac
W/AudioCapabilities(23029): Unsupported mime audio/alac
W/AudioCapabilities(23029): Unsupported mime audio/ape
W/AudioCapabilities(23029): Unsupported mime audio/ape
W/VideoCapabilities(23029): Unrecognized profile/level 32768/256 for video/mp4v-es
W/VideoCapabilities(23029): Unrecognized profile/level 32768/256 for video/mp4v-es
W/VideoCapabilities(23029): Unsupported mime video/x-ms-wmv
W/VideoCapabilities(23029): Unsupported mime video/x-ms-wmv
I/GED     (23029): ged_boost_gpu_freq, level 100, eOrigin 2, final_idx 31, oppidx_max 31, oppidx_min 0
D/BLASTBufferQueue(23029): [SurfaceView[com.agnepal.ambitionguru/com.agnepal.ambitionguru.MainActivity]#1](f:0,a:1) destructor()
D/BufferQueueConsumer(23029): [SurfaceView[com.agnepal.ambitionguru/com.agnepal.ambitionguru.MainActivity]#1(BLAST Consumer)1](id:59f500000001,api:0,p:-1,c:23029) disconnect
I/org.webrtc.Logging(23029): WebRtcAudioRecordExternal: enableBuiltInAEC(true)
I/org.webrtc.Logging(23029): WebRtcAudioEffectsExternal: setAEC(true)
I/org.webrtc.Logging(23029): WebRtcAudioRecordExternal: enableBuiltInNS(true)
I/org.webrtc.Logging(23029): WebRtcAudioEffectsExternal: setNS(true)
I/org.webrtc.Logging(23029): PeerConnectionFactory: onNetworkThreadReady
I/org.webrtc.Logging(23029): PeerConnectionFactory: onWorkerThreadReady
I/org.webrtc.Logging(23029): PeerConnectionFactory: onSignalingThreadReady
D/BLASTBufferQueue(23029): [VRI[MainActivity]#0](f:0,a:1) destructor()
D/BufferQueueConsumer(23029): [VRI[MainActivity]#0(BLAST Consumer)0](id:59f500000000,api:0,p:-1,c:23029) disconnect
D/VRI[WrapperJitsiMeetActivity](23029): vri.reportNextDraw android.view.ViewRootImpl.handleResized:2315 android.view.ViewRootImpl.-$$Nest$mhandleResized:0 android.view.ViewRootImpl$ViewRootHandler.handleMessageImpl:6802 android.view.ViewRootImpl$ViewRootHandler.handleMessage:6771 android.os.Handler.dispatchMessage:106 
D/VRI[WrapperJitsiMeetActivity](23029): vri.reportNextDraw android.view.ViewRootImpl.performTraversals:3837 android.view.ViewRootImpl.doTraversal:3016 android.view.ViewRootImpl$TraversalRunnable.run:10510 android.view.Choreographer$CallbackRecord.run:1686 android.view.Choreographer$CallbackRecord.run:1695 
D/VRI[WrapperJitsiMeetActivity](23029): vri.Setup new sync=wmsSync-VRI[WrapperJitsiMeetActivity]#8
D/VRI[WrapperJitsiMeetActivity](23029): vri.reportDrawFinished
D/OrientationModule(23029): onActivityStopped
D/OrientationModule(23029): onActivitySaveInstanceState
W/unknown:ViewManagerPropertyUpdater(23029): Could not find generated setter for class com.facebook.react.views.drawer.ReactDrawerLayoutManager
W/unknown:ViewManagerPropertyUpdater(23029): Could not find generated setter for class com.facebook.react.uimanager.LayoutShadowNode
W/unknown:ViewManagerPropertyUpdater(23029): Could not find generated setter for class com.facebook.react.views.scroll.ReactHorizontalScrollViewManager
W/unknown:ViewManagerPropertyUpdater(23029): Could not find generated setter for class com.facebook.react.views.scroll.ReactHorizontalScrollContainerViewManager
W/unknown:ViewManagerPropertyUpdater(23029): Could not find generated setter for class com.facebook.react.views.progressbar.ReactProgressBarViewManager
W/unknown:ViewManagerPropertyUpdater(23029): Could not find generated setter for class com.facebook.react.views.progressbar.ProgressBarShadowNode
W/unknown:ViewManagerPropertyUpdater(23029): Could not find generated setter for class com.facebook.react.views.scroll.ReactScrollViewManager
W/unknown:ViewManagerPropertyUpdater(23029): Could not find generated setter for class com.facebook.react.views.switchview.ReactSwitchManager
W/unknown:ViewManagerPropertyUpdater(23029): Could not find generated setter for class com.facebook.react.views.switchview.ReactSwitchManager$ReactSwitchShadowNode
W/unknown:ViewManagerPropertyUpdater(23029): Could not find generated setter for class com.facebook.react.views.swiperefresh.SwipeRefreshLayoutManager
W/unknown:ViewManagerPropertyUpdater(23029): Could not find generated setter for class com.facebook.react.views.text.frescosupport.FrescoBasedReactTextInlineImageViewManager
W/unknown:ViewManagerPropertyUpdater(23029): Could not find generated setter for class com.facebook.react.views.text.frescosupport.FrescoBasedReactTextInlineImageShadowNode
W/unknown:ViewManagerPropertyUpdater(23029): Could not find generated setter for class com.facebook.react.views.image.ReactImageManager
W/unknown:ViewManagerPropertyUpdater(23029): Could not find generated setter for class com.facebook.react.views.modal.ReactModalHostManager
W/unknown:ViewManagerPropertyUpdater(23029): Could not find generated setter for class com.facebook.react.views.modal.ModalHostShadowNode
W/unknown:ViewManagerPropertyUpdater(23029): Could not find generated setter for class com.facebook.react.views.text.ReactRawTextManager
W/unknown:ViewManagerPropertyUpdater(23029): Could not find generated setter for class com.facebook.react.views.text.ReactRawTextShadowNode
W/unknown:ViewManagerPropertyUpdater(23029): Could not find generated setter for class com.facebook.react.views.textinput.ReactTextInputManager
W/unknown:ViewManagerPropertyUpdater(23029): Could not find generated setter for class com.facebook.react.views.textinput.ReactTextInputShadowNode
W/unknown:ViewManagerPropertyUpdater(23029): Could not find generated setter for class com.facebook.react.views.text.ReactTextViewManager
W/unknown:ViewManagerPropertyUpdater(23029): Could not find generated setter for class com.facebook.react.views.text.ReactTextShadowNode
W/unknown:ViewManagerPropertyUpdater(23029): Could not find generated setter for class com.facebook.react.views.view.ReactViewManager
W/unknown:ViewManagerPropertyUpdater(23029): Could not find generated setter for class com.facebook.react.views.text.ReactVirtualTextViewManager
W/unknown:ViewManagerPropertyUpdater(23029): Could not find generated setter for class com.facebook.react.views.text.ReactVirtualTextShadowNode
W/unknown:ViewManagerPropertyUpdater(23029): Could not find generated setter for class com.facebook.react.views.unimplementedview.ReactUnimplementedViewManager
W/unknown:ViewManagerPropertyUpdater(23029): Could not find generated setter for class com.reactnativepagerview.PagerViewViewManager
E/unknown:UIManagerModuleConstantsHelper(23029): Direct event name for 'RNCSlider' doesn't correspond to the naming convention, expected 'topEventName'->'onEventName', got 'topSlidingStart'->'onRNCSliderSlidingStart'
E/unknown:UIManagerModuleConstantsHelper(23029): Direct event name for 'RNCSlider' doesn't correspond to the naming convention, expected 'topEventName'->'onEventName', got 'topSlidingComplete'->'onRNCSliderSlidingComplete'
W/unknown:ViewManagerPropertyUpdater(23029): Could not find generated setter for class com.reactnativecommunity.slider.ReactSliderManager
W/unknown:ViewManagerPropertyUpdater(23029): Could not find generated setter for class com.reactnativecommunity.slider.ReactSliderManager$ReactSliderShadowNode
W/unknown:ViewManagerPropertyUpdater(23029): Could not find generated setter for class com.brentvatne.exoplayer.ReactExoplayerViewManager
W/unknown:ViewManagerPropertyUpdater(23029): Could not find generated setter for class com.reactnativecommunity.webview.RNCWebViewManager
W/unknown:ViewManagerPropertyUpdater(23029): Could not find generated setter for class com.oney.WebRTCModule.RTCVideoViewManager
W/unknown:ViewManagerPropertyUpdater(23029): Could not find generated setter for class com.swmansion.gesturehandler.react.RNGestureHandlerRootViewManager
W/unknown:ViewManagerPropertyUpdater(23029): Could not find generated setter for class com.swmansion.gesturehandler.react.RNGestureHandlerButtonViewManager
W/unknown:ViewManagerPropertyUpdater(23029): Could not find generated setter for class com.swmansion.rnscreens.ScreenContainerViewManager
W/unknown:ViewManagerPropertyUpdater(23029): Could not find generated setter for class com.swmansion.rnscreens.ScreenViewManager
W/unknown:ViewManagerPropertyUpdater(23029): Could not find generated setter for class com.swmansion.rnscreens.ModalScreenViewManager
W/unknown:ViewManagerPropertyUpdater(23029): Could not find generated setter for class com.swmansion.rnscreens.ScreenStackViewManager
W/unknown:ViewManagerPropertyUpdater(23029): Could not find generated setter for class com.swmansion.rnscreens.ScreenStackHeaderConfigViewManager
W/unknown:ViewManagerPropertyUpdater(23029): Could not find generated setter for class com.swmansion.rnscreens.ScreenStackHeaderSubviewManager
W/unknown:ViewManagerPropertyUpdater(23029): Could not find generated setter for class com.swmansion.rnscreens.SearchBarManager
W/unknown:ViewManagerPropertyUpdater(23029): Could not find generated setter for class com.th3rdwave.safeareacontext.SafeAreaProviderManager
W/unknown:ViewManagerPropertyUpdater(23029): Could not find generated setter for class com.th3rdwave.safeareacontext.SafeAreaViewManager
W/unknown:ViewManagerPropertyUpdater(23029): Could not find generated setter for class com.th3rdwave.safeareacontext.SafeAreaViewShadowNode
W/unknown:ViewManagerPropertyUpdater(23029): Could not find generated setter for class com.horcrux.svg.RenderableViewManager$DefsViewManager
W/unknown:ViewManagerPropertyUpdater(23029): Could not find generated setter for class com.horcrux.svg.VirtualViewManager$RenderableShadowNode
W/unknown:ViewManagerPropertyUpdater(23029): Could not find generated setter for class com.horcrux.svg.RenderableViewManager$MarkerManager
W/unknown:ViewManagerPropertyUpdater(23029): Could not find generated setter for class com.horcrux.svg.RenderableViewManager$ForeignObjectManager
W/unknown:ViewManagerPropertyUpdater(23029): Could not find generated setter for class com.horcrux.svg.RenderableViewManager$EllipseViewManager
W/unknown:ViewManagerPropertyUpdater(23029): Could not find generated setter for class com.horcrux.svg.RenderableViewManager$LineViewManager
W/unknown:ViewManagerPropertyUpdater(23029): Could not find generated setter for class com.horcrux.svg.RenderableViewManager$LinearGradientManager
W/unknown:ViewManagerPropertyUpdater(23029): Could not find generated setter for class com.horcrux.svg.RenderableViewManager$GroupViewManager
W/unknown:ViewManagerPropertyUpdater(23029): Could not find generated setter for class com.horcrux.svg.RenderableViewManager$TextViewManager
W/unknown:ViewManagerPropertyUpdater(23029): Could not find generated setter for class com.horcrux.svg.RenderableViewManager$ImageViewManager
W/unknown:ViewManagerPropertyUpdater(23029): Could not find generated setter for class com.horcrux.svg.RenderableViewManager$ClipPathViewManager
W/unknown:ViewManagerPropertyUpdater(23029): Could not find generated setter for class com.horcrux.svg.RenderableViewManager$RadialGradientManager
W/unknown:ViewManagerPropertyUpdater(23029): Could not find generated setter for class com.horcrux.svg.RenderableViewManager$MaskManager
W/unknown:ViewManagerPropertyUpdater(23029): Could not find generated setter for class com.horcrux.svg.RenderableViewManager$SymbolManager
W/unknown:ViewManagerPropertyUpdater(23029): Could not find generated setter for class com.horcrux.svg.RenderableViewManager$PatternManager
W/unknown:ViewManagerPropertyUpdater(23029): Could not find generated setter for class com.horcrux.svg.RenderableViewManager$RectViewManager
W/unknown:ViewManagerPropertyUpdater(23029): Could not find generated setter for class com.horcrux.svg.RenderableViewManager$TextPathViewManager
W/unknown:ViewManagerPropertyUpdater(23029): Could not find generated setter for class com.horcrux.svg.SvgViewManager
W/unknown:ViewManagerPropertyUpdater(23029): Could not find generated setter for class com.horcrux.svg.RenderableViewManager$PathViewManager
W/unknown:ViewManagerPropertyUpdater(23029): Could not find generated setter for class com.horcrux.svg.RenderableViewManager$UseViewManager
W/unknown:ViewManagerPropertyUpdater(23029): Could not find generated setter for class com.horcrux.svg.RenderableViewManager$CircleViewManager
W/unknown:ViewManagerPropertyUpdater(23029): Could not find generated setter for class com.horcrux.svg.RenderableViewManager$TSpanViewManager
W/unknown:ViewManagerPropertyUpdater(23029): Could not find generated setter for class com.giphyreactnativesdk.GiphyMediaViewManager
W/unknown:ViewManagerPropertyUpdater(23029): Could not find generated setter for class com.giphyreactnativesdk.GiphyGridViewManager
W/unknown:ViewManagerPropertyUpdater(23029): Could not find generated setter for class com.giphyreactnativesdk.GiphyVideoViewManager
W/unknown:ViewManagerPropertyUpdater(23029): Could not find generated setter for class com.reactnativegooglesignin.RNGoogleSigninButtonViewManager
E/AndroidRuntime(23029): FATAL EXCEPTION: mqt_js
E/AndroidRuntime(23029): Process: com.agnepal.ambitionguru, PID: 23029
E/AndroidRuntime(23029): java.lang.RuntimeException: com.facebook.react.devsupport.JSException: Unexpected token '?'
E/AndroidRuntime(23029): 	at com.facebook.react.bridge.DefaultJSExceptionHandler.handleException(DefaultJSExceptionHandler.java:20)
E/AndroidRuntime(23029): 	at com.facebook.react.devsupport.DisabledDevSupportManager.handleException(DisabledDevSupportManager.java:195)
E/AndroidRuntime(23029): 	at com.facebook.react.bridge.CatalystInstanceImpl.onNativeException(CatalystInstanceImpl.java:614)
E/AndroidRuntime(23029): 	at com.facebook.react.bridge.CatalystInstanceImpl.-$$Nest$monNativeException(Unknown Source:0)
E/AndroidRuntime(23029): 	at com.facebook.react.bridge.CatalystInstanceImpl$NativeExceptionHandler.handleException(CatalystInstanceImpl.java:632)
E/AndroidRuntime(23029): 	at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:40)
E/AndroidRuntime(23029): 	at android.os.Looper.loopOnce(Looper.java:222)
E/AndroidRuntime(23029): 	at android.os.Looper.loop(Looper.java:314)
E/AndroidRuntime(23029): 	at com.facebook.react.bridge.queue.MessageQueueThreadImpl$4.run(MessageQueueThreadImpl.java:234)
E/AndroidRuntime(23029): 	at java.lang.Thread.run(Thread.java:1012)
E/AndroidRuntime(23029): Caused by: com.facebook.react.devsupport.JSException: Unexpected token '?'
E/AndroidRuntime(23029): 	at com.facebook.jni.NativeRunnable.run(Native Method)
E/AndroidRuntime(23029): 	at android.os.Handler.handleCallback(Handler.java:958)
E/AndroidRuntime(23029): 	at android.os.Handler.dispatchMessage(Handler.java:99)
E/AndroidRuntime(23029): 	at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:29)
E/AndroidRuntime(23029): 	... 4 more
E/AndroidRuntime(23029): Caused by: com.facebook.jni.CppException: Unexpected token '?'
E/AndroidRuntime(23029): 
E/AndroidRuntime(23029): no stack
E/AndroidRuntime(23029): 	... 8 more
E/JitsiMeetSDK(23029): JitsiMeetUncaughtExceptionHandler FATAL ERROR
E/JitsiMeetSDK(23029): java.lang.RuntimeException: com.facebook.react.devsupport.JSException: Unexpected token '?'
E/JitsiMeetSDK(23029): 	at com.facebook.react.bridge.DefaultJSExceptionHandler.handleException(DefaultJSExceptionHandler.java:20)
E/JitsiMeetSDK(23029): 	at com.facebook.react.devsupport.DisabledDevSupportManager.handleException(DisabledDevSupportManager.java:195)
E/JitsiMeetSDK(23029): 	at com.facebook.react.bridge.CatalystInstanceImpl.onNativeException(CatalystInstanceImpl.java:614)
E/JitsiMeetSDK(23029): 	at com.facebook.react.bridge.CatalystInstanceImpl.-$$Nest$monNativeException(Unknown Source:0)
E/JitsiMeetSDK(23029): 	at com.facebook.react.bridge.CatalystInstanceImpl$NativeExceptionHandler.handleException(CatalystInstanceImpl.java:632)
E/JitsiMeetSDK(23029): 	at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:40)
E/JitsiMeetSDK(23029): 	at android.os.Looper.loopOnce(Looper.java:222)
E/JitsiMeetSDK(23029): 	at android.os.Looper.loop(Looper.java:314)
E/JitsiMeetSDK(23029): 	at com.facebook.react.bridge.queue.MessageQueueThreadImpl$4.run(MessageQueueThreadImpl.java:234)
E/JitsiMeetSDK(23029): 	at java.lang.Thread.run(Thread.java:1012)
E/JitsiMeetSDK(23029): Caused by: com.facebook.react.devsupport.JSException: Unexpected token '?'
E/JitsiMeetSDK(23029): 	at com.facebook.jni.NativeRunnable.run(Native Method)
E/JitsiMeetSDK(23029): 	at android.os.Handler.handleCallback(Handler.java:958)
E/JitsiMeetSDK(23029): 	at android.os.Handler.dispatchMessage(Handler.java:99)
E/JitsiMeetSDK(23029): 	at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:29)
E/JitsiMeetSDK(23029): 	... 4 more
E/JitsiMeetSDK(23029): Caused by: com.facebook.jni.CppException: Unexpected token '?'
E/JitsiMeetSDK(23029): 
E/JitsiMeetSDK(23029): no stack
E/JitsiMeetSDK(23029): 	... 8 more
E/JitsiMeetSDK(23029): 
E/JitsiMeetSDK(23029): java.lang.RuntimeException: com.facebook.react.devsupport.JSException: Unexpected token '?'
E/JitsiMeetSDK(23029): 	at com.facebook.react.bridge.DefaultJSExceptionHandler.handleException(DefaultJSExceptionHandler.java:20)
E/JitsiMeetSDK(23029): 	at com.facebook.react.devsupport.DisabledDevSupportManager.handleException(DisabledDevSupportManager.java:195)
E/JitsiMeetSDK(23029): 	at com.facebook.react.bridge.CatalystInstanceImpl.onNativeException(CatalystInstanceImpl.java:614)
E/JitsiMeetSDK(23029): 	at com.facebook.react.bridge.CatalystInstanceImpl.-$$Nest$monNativeException(Unknown Source:0)
E/JitsiMeetSDK(23029): 	at com.facebook.react.bridge.CatalystInstanceImpl$NativeExceptionHandler.handleException(CatalystInstanceImpl.java:632)
E/JitsiMeetSDK(23029): 	at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:40)
E/JitsiMeetSDK(23029): 	at android.os.Looper.loopOnce(Looper.java:222)
E/JitsiMeetSDK(23029): 	at android.os.Looper.loop(Looper.java:314)
E/JitsiMeetSDK(23029): 	at com.facebook.react.bridge.queue.MessageQueueThreadImpl$4.run(MessageQueueThreadImpl.java:234)
E/JitsiMeetSDK(23029): 	at java.lang.Thread.run(Thread.java:1012)
E/JitsiMeetSDK(23029): Caused by: com.facebook.react.devsupport.JSException: Unexpected token '?'
E/JitsiMeetSDK(23029): 	at com.facebook.jni.NativeRunnable.run(Native Method)
E/JitsiMeetSDK(23029): 	at android.os.Handler.handleCallback(Handler.java:958)
E/JitsiMeetSDK(23029): 	at android.os.Handler.dispatchMessage(Handler.java:99)
E/JitsiMeetSDK(23029): 	at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:29)
E/JitsiMeetSDK(23029): 	... 4 more
E/JitsiMeetSDK(23029): Caused by: com.facebook.jni.CppException: Unexpected token '?'
E/JitsiMeetSDK(23029): 
E/JitsiMeetSDK(23029): no stack
E/JitsiMeetSDK(23029): 	... 8 more
I/JitsiMeetSDK(23029): Using AudioDeviceHandlerConnectionService as the audio device handler
W/mqt_js  (23029): type=1400 audit(0.0:2838269): avc:  denied  { search } for  name="miuilog" dev="dm-52" ino=904 scontext=u:r:untrusted_app:s0:c158,c257,c512,c768 tcontext=u:object_r:data_log_file:s0 tclass=dir permissive=0 app=com.agnepal.ambitionguru
W/mqt_js  (23029): type=1400 audit(0.0:2838270): avc:  denied  { search } for  name="miuilog" dev="dm-52" ino=904 scontext=u:r:untrusted_app:s0:c158,c257,c512,c768 tcontext=u:object_r:data_log_file:s0 tclass=dir permissive=0 app=com.agnepal.ambitionguru
W/ScoutUtils(23029): Failed to mkdir /data/miuilog/stability/memleak/heapdump/
W/mqt_js  (23029): type=1400 audit(0.0:2838271): avc:  denied  { search } for  name="miuilog" dev="dm-52" ino=904 scontext=u:r:untrusted_app:s0:c158,c257,c512,c768 tcontext=u:object_r:data_log_file:s0 tclass=dir permissive=0 app=com.agnepal.ambitionguru
W/mqt_js  (23029): type=1400 audit(0.0:2838272): avc:  denied  { search } for  name="miuilog" dev="dm-52" ino=904 scontext=u:r:untrusted_app:s0:c158,c257,c512,c768 tcontext=u:object_r:data_log_file:s0 tclass=dir permissive=0 app=com.agnepal.ambitionguru
W/mqt_js  (23029): type=1400 audit(0.0:2838273): avc:  denied  { search } for  name="miuilog" dev="dm-52" ino=904 scontext=u:r:untrusted_app:s0:c158,c257,c512,c768 tcontext=u:object_r:data_log_file:s0 tclass=dir permissive=0 app=com.agnepal.ambitionguru
W/mqt_js  (23029): type=1400 audit(0.0:2838274): avc:  denied  { search } for  name="miuilog" dev="dm-52" ino=904 scontext=u:r:untrusted_app:s0:c158,c257,c512,c768 tcontext=u:object_r:data_log_file:s0 tclass=dir permissive=0 app=com.agnepal.ambitionguru
W/mqt_js  (23029): type=1400 audit(0.0:2838275): avc:  denied  { getattr } for  path="/data/miuilog" dev="dm-52" ino=904 scontext=u:r:untrusted_app:s0:c158,c257,c512,c768 tcontext=u:object_r:data_log_file:s0 tclass=dir permissive=0 app=com.agnepal.ambitionguru
I/Process (23029): Process is going to kill itself!
I/Process (23029): java.lang.Exception
I/Process (23029): 	at android.os.Process.killProcess(Process.java:1346)
I/Process (23029): 	at com.android.internal.os.RuntimeInit$KillApplicationHandler.uncaughtException(RuntimeInit.java:178)
I/Process (23029): 	at com.google.firebase.crashlytics.internal.common.CrashlyticsUncaughtExceptionHandler.uncaughtException(CrashlyticsUncaughtExceptionHandler.java:62)
I/Process (23029): 	at org.jitsi.meet.sdk.JitsiMeetUncaughtExceptionHandler.uncaughtException(JitsiMeetUncaughtExceptionHandler.java:48)
I/Process (23029): 	at org.chromium.base.JavaExceptionReporter.uncaughtException(chromium-TrichromeWebViewGoogle6432.aab-stable-653310333:31)
I/Process (23029): 	at com.facebook.internal.instrument.crashreport.CrashHandler.uncaughtException(CrashHandler.kt:31)
I/Process (23029): 	at java.lang.ThreadGroup.uncaughtException(ThreadGroup.java:1071)
I/Process (23029): 	at java.lang.ThreadGroup.uncaughtException(ThreadGroup.java:1066)
I/Process (23029): 	at java.lang.Thread.dispatchUncaughtException(Thread.java:2306)
I/Process (23029): Sending signal. PID: 23029 SIG: 9
Lost connection to device.
the Dart compiler exited unexpectedly.
```

### Reproducibility

- [ ] The problem is reproducible on meet.jit.si

**Comment by saghul** [comment]
What node / npm versions did you use?

**Comment by erengms** [comment]
same issue

**Comment by saghul** [comment]
Can you reproduce the problem with our SDK?

**Comment by JagaranMaharjan** [comment]
@erengms can you checkout to the commit head **815fa7c57151ac3cb47ae46247c6c26f32581f2b** and generate custom sdk. My issue was resloved from this commit head.
