### ISSUE TITLE
“You have been disconnected” message after second participant join

### ISSUE THREAD

**Issue by karolryska** [jitsi/jitsi-meet#15035]
### What happened?

In my self-hosted instance, when a video call is joined by a second participant for both of them, a “You have been disconnected” message appears.

Clicking "Rejoin now" or waiting sometimes works, sometimes not, and the same error continues. If it worked for one participant, reconnecting the second participant will again show a “no connection” message for the first participant, and so on and so forth.

![image](https://github.com/user-attachments/assets/4de4da66-e79b-4d3a-babc-b398cd66bf63)

### Platform

- [X] Chrome (or Chromium based)
- [ ] Firefox
- [ ] Safari
- [ ] Other desktop browser
- [ ] Android browser
- [ ] iOS browser
- [ ] Electron app
- [ ] Android mobile app
- [ ] iOS mobile app
- [ ] Custom app using a mobile SDK

### Browser / app / sdk version

Chrome 126.0.6478.114

### Relevant log output

```shell
Logger.js:155 2024-08-20T14:20:19.135Z [conference.js] <D$._onConferenceFailed>:  CONFERENCE FAILED: conference.videobridgeNotAvailable
Logger.js:155 2024-08-20T14:20:19.157Z [index.web] UnhandledPromiseRejection: Error: You have already left the conference StackTrace:  Error: You have already left the conference
    at Wh.leave (https://jitsi.counter-terrorism-ipu.org/libs/lib-jitsi-meet.min.js?v=8091:2:1037060)
    at D$._onConferenceFailed (https://jitsi.counter-terrorism-ipu.org/libs/app.bundle.min.js?v=8091:85:71910)
    at o.emit (https://jitsi.counter-terrorism-ipu.org/libs/lib-jitsi-meet.min.js?v=8091:2:353528)
    at o.emit (https://jitsi.counter-terrorism-ipu.org/libs/lib-jitsi-meet.min.js?v=8091:2:353585)
    at Es.onPresence (https://jitsi.counter-terrorism-ipu.org/libs/lib-jitsi-meet.min.js?v=8091:2:713190)
    at bs.onPresence (https://jitsi.counter-terrorism-ipu.org/libs/lib-jitsi-meet.min.js?v=8091:2:729679)
    at Handler.run (https://jitsi.counter-terrorism-ipu.org/libs/lib-jitsi-meet.min.js?v=8091:2:494840)
    at https://jitsi.counter-terrorism-ipu.org/libs/lib-jitsi-meet.min.js?v=8091:2:503251
    at Array.reduce (<anonymous>)
    at https://jitsi.counter-terrorism-ipu.org/libs/lib-jitsi-meet.min.js?v=8091:2:503175
    at Object.forEachChild (https://jitsi.counter-terrorism-ipu.org/libs/lib-jitsi-meet.min.js?v=8091:2:487602)
    at F.Connection._dataRecv (https://jitsi.counter-terrorism-ipu.org/libs/lib-jitsi-meet.min.js?v=8091:2:503111)
    at e._onRequestStateChange (https://jitsi.counter-terrorism-ipu.org/libs/lib-jitsi-meet.min.js?v=8091:2:521901)
JitsiConference.js:689 Uncaught (in promise) 
Error: You have already left the conference
    at Wh.leave (JitsiConference.js:689:15)
    at D$._onConferenceFailed (conference.js:322:18)
    at o.emit (events.js:153:5)
    at o.emit (events.js:158:7)
    at Es.onPresence (ChatRoom.js:797:39)
    at bs.onPresence (strophe.emuc.js:118:14)
    at Handler.run (strophe.umd.js:2507:33)
    at strophe.umd.js:3843:37
    at Array.reduce (<anonymous>)
    at strophe.umd.js:3840:49
    at Object.forEachChild (strophe.umd.js:1502:21)
    at F.Connection._dataRecv (strophe.umd.js:3838:25)
    at e._onRequestStateChange (strophe.umd.js:5311:19)
```

### Reproducibility

- [ ] The problem is reproducible on meet.jit.si

### More details?

Self-hosted

jitsi-meet-prosody/stable,now 1.0.8091-1 all [installed,automatic]
jitsi-meet-turnserver/stable,now 1.0.8091-1 all [installed,automatic]
jitsi-meet-web-config/stable,now 1.0.8091-1 all [installed,automatic]
jitsi-meet-web/stable,now 1.0.8091-1 all [installed,automatic]
jitsi-meet/stable,now 2.0.9646-1 all [installed]
jitsi-videobridge2/stable,now 2.3-160-g97a1f15b-1 all [installed,automatic]

**Comment by damencho** [comment]
> ```shell
> Logger.js:155 2024-08-20T14:20:19.135Z [conference.js] <D$._onConferenceFailed>:  CONFERENCE FAILED: conference.videobridgeNotAvailable
> ```

Have you tried restarting jvb? Does that fix it?

**Comment by karolryska** [comment]
Unfortunately, restarting jvb did not fix it. Do you have any other suggestions?

**Comment by damencho** [comment]
Share jvb logs as a starter.

**Comment by karolryska** [comment]
[jvb_logs.txt](https://github.com/user-attachments/files/16994972/jvb_logs.txt)

Here are the logs from when the error was reproduced

**Comment by damencho** [comment]
```
[hostname=localhost id=shard] MucClient.lambda$getConnectAndLoginCallable$9#660: Failed to login. Disconnecting to trigger a re-connect.
```
Apparently your jvb cannot connect to prosody. In the mean time your jicofo is connected. Share your jvb configs, masking any private information.
/etc/jitsi/videobridge/sip-communicator.properties and /etc/jitsi/videobridge/jvb.conf

**Comment by karolryska** [comment]
Here is the config

```
videobridge {
    http-servers {
        public {
            port = 9090
        }
    }
    websockets {
        enabled = true
        domain = "jitsi.***.org:443"
        tls = true
    }
}
```
