### ISSUE TITLE
Execution failed for task ':sdk:bundleReleaseJsAndAssets'. in version 2.0.9823

### ISSUE THREAD

**Issue by lxd551326** [jitsi/jitsi-meet#15313]
### What happened?

hi.
I can use Android Studio to directly run the app on my phone, but when I try to generate an APK, an error occurs. It says it can't find the Node environment, even though my Node environment is ready:
afish@afish-Legion-R9000P-ARX8:~/workspace/node_ws/jitsi-meet-stable-jitsi-meet_9823/android$ node -v
v20.18.0  

### Platform

- [ ] Chrome (or Chromium based)
- [ ] Firefox
- [ ] Safari
- [ ] Other desktop browser
- [ ] Android browser
- [ ] iOS browser
- [ ] Electron app
- [X] Android mobile app
- [ ] iOS mobile app
- [ ] Custom app using a mobile SDK

### Browser / app / sdk version

2.0.9823

### Relevant log output

```shell
FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':sdk:bundleReleaseJsAndAssets'.
> A problem occurred starting process 'command 'node''

* Try:
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.

* Exception is:
org.gradle.api.tasks.TaskExecutionException: Execution failed for task ':sdk:bundleReleaseJsAndAssets'.
	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.lambda$executeIfValid$1(ExecuteActionsTaskExecuter.java:142)
	at org.gradle.internal.Try$Failure.ifSuccessfulOrElse(Try.java:282)
	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeIfValid(ExecuteActionsTaskExecuter.java:140)
	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.execute(ExecuteActionsTaskExecuter.java:128)
	at org.gradle.api.internal.tasks.execution.CleanupStaleOutputsExecuter.execute(CleanupStaleOutputsExecuter.java:77)
	at org.gradle.api.internal.tasks.execution.FinalizePropertiesTaskExecuter.execute(FinalizePropertiesTaskExecuter.java:46)
	at org.gradle.api.internal.tasks.execution.ResolveTaskExecutionModeExecuter.execute(ResolveTaskExecutionModeExecuter.java:51)
	at org.gradle.api.internal.tasks.execution.SkipTaskWithNoActionsExecuter.execute(SkipTaskWithNoActionsExecuter.java:57)
	at org.gradle.api.internal.tasks.execution.SkipOnlyIfTaskExecuter.execute(SkipOnlyIfTaskExecuter.java:56)
	at org.gradle.api.internal.tasks.execution.CatchExceptionTaskExecuter.execute(CatchExceptionTaskExecuter.java:36)
	at org.gradle.api.internal.tasks.execution.EventFiringTaskExecuter$1.executeTask(EventFiringTaskExecuter.java:77)
	at org.gradle.api.internal.tasks.execution.EventFiringTaskExecuter$1.call(EventFiringTaskExecuter.java:55)
	at org.gradle.api.internal.tasks.execution.EventFiringTaskExecuter$1.call(EventFiringTaskExecuter.java:52)
	at org.gradle.internal.operations.DefaultBuildOperationRunner$CallableBuildOperationWorker.execute(DefaultBuildOperationRunner.java:204)
	at org.gradle.internal.operations.DefaultBuildOperationRunner$CallableBuildOperationWorker.execute(DefaultBuildOperationRunner.java:199)
	at org.gradle.internal.operations.DefaultBuildOperationRunner$2.execute(DefaultBuildOperationRunner.java:66)
	at org.gradle.internal.operations.DefaultBuildOperationRunner$2.execute(DefaultBuildOperationRunner.java:59)
	at org.gradle.internal.operations.DefaultBuildOperationRunner.execute(DefaultBuildOperationRunner.java:157)
	at org.gradle.internal.operations.DefaultBuildOperationRunner.execute(DefaultBuildOperationRunner.java:59)
	at org.gradle.internal.operations.DefaultBuildOperationRunner.call(DefaultBuildOperationRunner.java:53)
	at org.gradle.internal.operations.DefaultBuildOperationExecutor.call(DefaultBuildOperationExecutor.java:73)
	at org.gradle.api.internal.tasks.execution.EventFiringTaskExecuter.execute(EventFiringTaskExecuter.java:52)
	at org.gradle.execution.plan.LocalTaskNodeExecutor.execute(LocalTaskNodeExecutor.java:69)
	at org.gradle.execution.taskgraph.DefaultTaskExecutionGraph$InvokeNodeExecutorsAction.execute(DefaultTaskExecutionGraph.java:327)
	at org.gradle.execution.taskgraph.DefaultTaskExecutionGraph$InvokeNodeExecutorsAction.execute(DefaultTaskExecutionGraph.java:314)
	at org.gradle.execution.taskgraph.DefaultTaskExecutionGraph$BuildOperationAwareExecutionAction.execute(DefaultTaskExecutionGraph.java:307)
	at org.gradle.execution.taskgraph.DefaultTaskExecutionGraph$BuildOperationAwareExecutionAction.execute(DefaultTaskExecutionGraph.java:293)
	at org.gradle.execution.plan.DefaultPlanExecutor$ExecutorWorker.execute(DefaultPlanExecutor.java:420)
	at org.gradle.execution.plan.DefaultPlanExecutor$ExecutorWorker.run(DefaultPlanExecutor.java:342)
	at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:64)
	at org.gradle.internal.concurrent.ManagedExecutorImpl$1.run(ManagedExecutorImpl.java:48)
Caused by: org.gradle.process.internal.ExecException: A problem occurred starting process 'command 'node''
	at org.gradle.process.internal.DefaultExecHandle.execExceptionFor(DefaultExecHandle.java:241)
	at org.gradle.process.internal.DefaultExecHandle.setEndStateInfo(DefaultExecHandle.java:218)
	at org.gradle.process.internal.DefaultExecHandle.failed(DefaultExecHandle.java:370)
	at org.gradle.process.internal.ExecHandleRunner.run(ExecHandleRunner.java:87)
	at org.gradle.internal.operations.CurrentBuildOperationPreservingRunnable.run(CurrentBuildOperationPreservingRunnable.java:42)
	at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:64)
	at org.gradle.internal.concurrent.ManagedExecutorImpl$1.run(ManagedExecutorImpl.java:48)
Caused by: net.rubygrapefruit.platform.NativeException: Could not start 'node'
	at net.rubygrapefruit.platform.internal.DefaultProcessLauncher.start(DefaultProcessLauncher.java:27)
	at net.rubygrapefruit.platform.internal.WrapperProcessLauncher.start(WrapperProcessLauncher.java:36)
	at org.gradle.process.internal.ExecHandleRunner.startProcess(ExecHandleRunner.java:98)
	at org.gradle.process.internal.ExecHandleRunner.run(ExecHandleRunner.java:71)
	... 3 more
Caused by: java.io.IOException: Cannot run program "node" (in directory "/home/afish/workspace/node_ws/jitsi-meet-stable-jitsi-meet_9823"): error=2, 没有那个文件或目录
	at net.rubygrapefruit.platform.internal.DefaultProcessLauncher.start(DefaultProcessLauncher.java:25)
	... 6 more
Caused by: java.io.IOException: error=2, 没有那个文件或目录
	... 7 more


* Get more help at https://help.gradle.org

Deprecated Gradle features were used in this build, making it incompatible with Gradle 8.0.

You can use '--warning-mode all' to show the individual deprecation warnings and determine if they come from your own scripts or plugins.

See https://docs.gradle.org/7.5.1/userguide/command_line_interface.html#sec:command_line_warnings

Execution optimizations have been disabled for 1 invalid unit(s) of work during this build to ensure correctness.
Please consult deprecation warnings for more details.

BUILD FAILED in 5s
851 actionable tasks: 23 executed, 828 up-to-date
```

### Reproducibility

- [ ] The problem is reproducible on meet.jit.si

### More details?

when i modify :sdk:build.grale like this 
 commandLine(
                "/home/afish/.nvm/versions/node/v20.18.0/bin/node",
                "node_modules/react-native/scripts/bundle.js",
                "--platform", "android",
                "--dev", "${devEnabled}",
                "--reset-cache",
                "--entry-file", "index.android.js",
                "--bundle-output", jsBundleFile,
                "--assets-dest", resourcesDir)  
then had an orther error

/bin/sh: 1: npx: not found
node:internal/errors:984
  const err = new Error(message);
              ^

Error: Command failed: npx react-native config
/bin/sh: 1: npx: not found

    at genericNodeError (node:internal/errors:984:15)
    at wrappedFn (node:internal/errors:538:14)
    at checkExecSyncError (node:child_process:891:11)
    at execSync (node:child_process:963:15)
    at Command.handleAction (/home/afish/workspace/node_ws/jitsi-meet-stable-jitsi-meet_9823/node_modules/react-native/scripts/bundle.js:45:9)
    at Command.listener [as _actionHandler] (/home/afish/workspace/node_ws/jitsi-meet-stable-jitsi-meet_9823/node_modules/react-native/node_modules/commander/lib/command.js:482:17)
    at /home/afish/workspace/node_ws/jitsi-meet-stable-jitsi-meet_9823/node_modules/react-native/node_modules/commander/lib/command.js:1283:65
    at Command._chainOrCall (/home/afish/workspace/node_ws/jitsi-meet-stable-jitsi-meet_9823/node_modules/react-native/node_modules/commander/lib/command.js:1177:12)
    at Command._parseCommand (/home/afish/workspace/node_ws/jitsi-meet-stable-jitsi-meet_9823/node_modules/react-native/node_modules/commander/lib/command.js:1283:27)
    at Command.parse (/home/afish/workspace/node_ws/jitsi-meet-stable-jitsi-meet_9823/node_modules/react-native/node_modules/commander/lib/command.js:909:10) {
  status: 127,
  signal: null,
  output: [ null, '', '/bin/sh: 1: npx: not found\n' ],
  pid: 137317,
  stdout: '',
  stderr: '/bin/sh: 1: npx: not found\n'
}

Node.js v20.18.0

Command failed: npx react-native config

Execution failed for task ':sdk:bundleReleaseJsAndAssets'.
> Process 'command '/home/afish/.nvm/versions/node/v20.18.0/bin/node'' finished with non-zero exit value 1

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.

**Comment by saghul** [comment]
Do you have `npx` in your path?

**Comment by lxd551326** [comment]
yes npx version is 10.8.x.   I suspect that the exec launched by Gradle does not obtain the system environment variables, causing PATH to be ineffective. Even though I used the absolute path for node, if node uses npx internally, this would also result in npx not being found.

**Comment by lxd551326** [comment]
ok, I'll give it another try. I'll let you know if I have any results. Thanks for your help.

**Comment by lxd551326** [comment]
is ok. i use ubuntu system,just open android studio with terminal as ./studio . donot open with double click,thank you
