### ISSUE TITLE
when open and close  the jitsimeet repeatedly ,the app crash! 

### ISSUE THREAD

**Issue by rokon338** [jitsi/jitsi-meet#1708]
Hello,I am integration the project to my native app(android / iOS),when open and close  the jitsimeet repeatedly (not exit the app),the app crash!  it seems that camera memory not release。
there is the exception： 

java.lang.RuntimeException: setParameters failed
                                                                 at android.hardware.Camera.native_setParameters(Native Method)
                                                                 at android.hardware.Camera.setParameters(Camera.java:2586)
                                                                 at org.webrtc.Camera1Session.updateCameraParameters(Camera1Session.java:121)
                                                                 at org.webrtc.Camera1Session.create(Camera1Session.java:85)
                                                                 at org.webrtc.Camera1Capturer.createCameraSession(Camera1Capturer.java:34)
                                                                 at org.webrtc.CameraCapturer$5.run(CameraCapturer.java:289)
                                                                 at android.os.Handler.handleCallback(Handler.java:761)
                                                                 at android.os.Handler.dispatchMessage(Handler.java:98)
                                                                 at android.os.Looper.loop(Looper.java:156)
                                                                 at android.os.HandlerThread.run(HandlerThread.java:61)

**Comment by saghul** [comment]
How are you doing the integration? How are you closing jitsi meet?

**Comment by liqing338** [comment]
Thanks for your quick response ！

i am use  the  "react-native bundle" to generate the offline package file, then copy the native file about the 'sdk' and other native code to my native project，then i am modify some 'sdk' code to let the sdk load from the  offline package file，It works very well(both android &iOS)。

i am close the jistimeet with 'JitsiMeetActivity.finish()'

**Comment by saghul** [comment]
@rokon338 I see. We are in the early days of the SDK, and AFAIS we missed to properly tear down the React parts when the activity dies. We'll take a look, thanks for reporting!

**Comment by saghul** [comment]
Fixed in https://github.com/jitsi/jitsi-meet/commit/bfa5f4c95306fb127c5676153c6e2cd393218eec
