### ISSUE TITLE
Issue : Could not get BatchedBridge

### ISSUE THREAD

**Issue by klijojoseph** [jitsi/jitsi-meet#1743]
When i tried to run through android studio the application has installed in device and shows the below exception

Exception in native call from JS
                                                               com.facebook.react.devsupport.JSException: Could not get BatchedBridge, make sure your bundle is packaged correctly
                                                                   at com.facebook.react.bridge.queue.NativeRunnable.run(Native Method)
                                                                   at android.os.Handler.handleCallback(Handler.java:739)
                                                                   at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                   at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:31)
                                                                   at android.os.Looper.loop(Looper.java:148)
                                                                   at com.facebook.react.bridge.queue.MessageQueueThreadImpl$3.run(MessageQueueThreadImpl.java:196)
                                                                   at java.lang.Thread.run(Thread.java:818)
                                                                Caused by: com.facebook.jni.CppException: Could not get BatchedBridge, make sure your bundle is packaged correctly
                                                                   at com.facebook.react.bridge.queue.NativeRunnable.run(Native Method) 
                                                                   at android.os.Handler.handleCallback(Handler.java:739) 
                                                                   at android.os.Handler.dispatchMessage(Handler.java:95) 
                                                                   at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:31) 
                                                                   at android.os.Looper.loop(Looper.java:148) 
                                                                   at com.facebook.react.bridge.queue.MessageQueueThreadImpl$3.run(MessageQueueThreadImpl.java:196) 
                                                                   at java.lang.Thread.run(Thread.java:818)

**Comment by saghul** [comment]
Please update your Android Studio to the latest (3.0 beta4), follow the instructions in doc/mobile.md and open a new issue if you are still unable to get it working. Thanks!
