### ISSUE TITLE
bash-4.3# Exception in thread "main" java.lang.NoClassDefFoundError: org/jitsi/meet/OSGiBundleConfig

### ISSUE THREAD

**Issue by tiredofit** [jitsi/jitsi-meet#1843]
Alpine 3.6 - openjdk8, openjdk8-jre
Installing Jitsimeet manually as per instructions, yet when I run 
`./jvb.sh --host=localhost --domain=jitsi.example.com --port=5347 --secret=YOURSECRET1 `

````bash
bash-4.3# ./jvb.sh --host=localhost --domain=jitsi.example.com --port=5347 --secret=YOURSECRET1 &
[1] 27504
bash-4.3# Exception in thread "main" java.lang.NoClassDefFoundError: org/jitsi/meet/OSGiBundleConfig
	at java.lang.Class.getDeclaredMethods0(Native Method)
	at java.lang.Class.privateGetDeclaredMethods(Class.java:2625)
	at java.lang.Class.getMethod0(Class.java:2866)
	at java.lang.Class.getMethod(Class.java:1676)
	at sun.launcher.LauncherHelper.getMainMethod(LauncherHelper.java:494)
	at sun.launcher.LauncherHelper.checkAndLoadMain(LauncherHelper.java:486)
Caused by: java.lang.ClassNotFoundException: org.jitsi.meet.OSGiBundleConfig
	at java.net.URLClassLoader$1.run(URLClassLoader.java:359)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:348)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:347)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:425)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:308)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:358)
	... 6 more
^C
[1]+  Exit 1                  ./jvb.sh --host=localhost --domain=jitsi.example.com --port=5347 --secret=YOURSECRET1
````

Any advice?

**Comment by saghul** [comment]
Not the exact same issue, but we've seen others with Alpine: https://github.com/jitsi/jitsi-videobridge/issues/432

**Comment by tiredofit** [comment]
Looks like that issue is ahead of mine somehow. It does seem like there is an Alpine issue, even though I have GLIBC 2.25 installed. I decided to rebuild the Dockerfile under Debian:Jessie and it came out 400mb smaller :) As much as I stay away from Debian based images that's enough right there for me to say, maybe I should deviate from my all Alpine container approach on a case basis!

**Comment by saghul** [comment]
👍
