### ISSUE TITLE
Compiling the source code on Mac

### ISSUE THREAD

**Issue by trda** [jitsi/jitsi-meet#2035]
Hello, 

I have npm and node on my MAC. After downloading the source code, I ran "npm install" command. But I got the below error. 

/bin/sh: /Users/trda/Documents/Calismalar/Node: No such file or directory
child_process.js:515
    throw err;
    ^

Error: Command failed: /Users/trda/Documents/Calismalar/Node Calisamalari/GITHUB_DESTEK_PROJELER/jitsi-meet/node_modules/lib-jitsi-meet/get-version.sh
/bin/sh: /Users/trda/Documents/Calismalar/Node: No such file or directory

    at checkExecSyncError (child_process.js:472:13)
    at Object.execSync (child_process.js:512:13)
    at Object.<anonymous> (/Users/trda/Documents/Calismalar/Node Calisamalari/GITHUB_DESTEK_PROJELER/jitsi-meet/node_modules/lib-jitsi-meet/webpack.config.js:41:35)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
npm WARN eslint-plugin-mocha@2.0.0 requires a peer of eslint@^2.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN react-native@0.42.3 requires a peer of react@~15.4.1 but none is installed. You must install peer dependencies yourself.
npm WARN react-native-background-timer@1.3.0 requires a peer of react-native@>=0.47.0 but none is installed. You must install peer dependencies yourself.
npm WARN react-native-immersive@1.1.0 requires a peer of react-native@>=0.47.0 but none is installed. You must install peer dependencies yourself.

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! lib-jitsi-meet@0.0.0 postinstall: `webpack -p`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the lib-jitsi-meet@0.0.0 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/trda/.npm/_logs/2017-10-04T19_44_39_676Z-debug.log

**Comment by trda** [comment]
I just want to run web project, not mobile apps. How can I do this ?
