### ISSUE TITLE
"Conference focus not available" after more than 3 users are connected

### ISSUE THREAD

**Issue by syswipe** [jitsi/jitsi-meet#2088]
Hi! 
I try to use jitsi on ubuntu 16.04.3. Jitsi was installed using Quick Install guide. After installation SSL certs were changed from self-signed to valid ones. Also, domain names were replaced. No other changes to configuration files were made.
Now i observe strange behavior when i trying to start a test conference. First time all works as expected: video, audio and chat between two users works fine. But when we try to add the third one to the conference, it goes down and show us "conference focus.mydomain.com not available" message. After that, all conferences stop working. Jicofo restart saves us, but it works until we try to create another conference for three and more users.

Prosody shows no errors in log files. 
Jicofo exception is displayed while "Conference focus not available" message occurs:

```
Jicofo 2017-10-19 06:42:48.174 INFO: [66] org.jitsi.jicofo.xmpp.FocusComponent.handleConferenceIq().396 Focus request for room: TestConf@conference.mydomain.com
Jicofo 2017-10-19 06:42:48.175 INFO: [66] org.jitsi.jicofo.FocusManager.log() Created new focus for TestConf@conference.mydomain.com@auth.mydomain.com conferences count: 1 options:
    channelLastN: -1
    enableLipSync: true
    openSctp: true
    disableRtx: false
Jicofo 2017-10-19 06:42:48.176 INFO: [66] org.jitsi.jicofo.JitsiMeetConferenceImpl.log() Lip-sync enabled in TestConf@conference.mydomain.com
Jicofo 2017-10-19 06:42:48.176 INFO: [66] org.jitsi.jicofo.JitsiMeetConferenceImpl.log() Joining the room: TestConf@conference.mydomain.com
Jicofo 2017-10-19 06:42:48.176 SEVERE: [66] org.jitsi.jicofo.JitsiMeetConferenceImpl.log() Chat room already left!
Jicofo 2017-10-19 06:42:48.176 INFO: [66] org.jitsi.jicofo.FocusManager.log() Disposed conference for room: TestConf@conference.mydomain.com conference count: 0
Jicofo 2017-10-19 06:42:48.177 INFO: [66] org.jitsi.jicofo.FocusManager.log() Exception while trying to start the conference
java.lang.IllegalStateException: Not connected to server.
	at org.jivesoftware.smack.Connection.addConnectionListener(Connection.java:525)
	at org.jivesoftware.smackx.muc.RoomListenerMultiplexor.init(RoomListenerMultiplexor.java:135)
	at org.jivesoftware.smackx.muc.RoomListenerMultiplexor.getRoomMultiplexor(RoomListenerMultiplexor.java:67)
	at org.jivesoftware.smackx.muc.MultiUserChat.init(MultiUserChat.java:2025)
	at org.jivesoftware.smackx.muc.MultiUserChat.<init>(MultiUserChat.java:162)
	at org.jitsi.impl.protocol.xmpp.ChatRoomImpl.<init>(ChatRoomImpl.java:153)
	at org.jitsi.impl.protocol.xmpp.OperationSetMultiUserChatImpl.createChatRoom(OperationSetMultiUserChatImpl.java:107)
	at org.jitsi.impl.protocol.xmpp.OperationSetMultiUserChatImpl.findRoom(OperationSetMultiUserChatImpl.java:130)
	at org.jitsi.jicofo.JitsiMeetConferenceImpl.joinTheRoom(JitsiMeetConferenceImpl.java:438)
	at org.jitsi.jicofo.JitsiMeetConferenceImpl.start(JitsiMeetConferenceImpl.java:323)
	at org.jitsi.jicofo.FocusManager.conferenceRequest(FocusManager.java:343)
	at org.jitsi.jicofo.FocusManager.conferenceRequest(FocusManager.java:290)
	at org.jitsi.jicofo.xmpp.FocusComponent.handleConferenceIq(FocusComponent.java:416)
	at org.jitsi.jicofo.xmpp.FocusComponent.handleIQSetImpl(FocusComponent.java:254)
	at org.jitsi.xmpp.component.ComponentBase.handleIQSet(ComponentBase.java:360)
	at org.xmpp.component.AbstractComponent.processIQRequest(AbstractComponent.java:515)
	at org.xmpp.component.AbstractComponent.processIQ(AbstractComponent.java:289)
	at org.xmpp.component.AbstractComponent.processQueuedPacket(AbstractComponent.java:239)
	at org.xmpp.component.AbstractComponent.access$100(AbstractComponent.java:81)
	at org.xmpp.component.AbstractComponent$PacketProcessor.run(AbstractComponent.java:1051)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Jicofo 2017-10-19 06:42:48.177 SEVERE: [66] org.jitsi.jicofo.xmpp.FocusComponent.handleIQSetImpl().320 java.lang.IllegalStateException: Not connected to server.
java.lang.IllegalStateException: Not connected to server.
	at org.jivesoftware.smack.Connection.addConnectionListener(Connection.java:525)
	at org.jivesoftware.smackx.muc.RoomListenerMultiplexor.init(RoomListenerMultiplexor.java:135)
	at org.jivesoftware.smackx.muc.RoomListenerMultiplexor.getRoomMultiplexor(RoomListenerMultiplexor.java:67)
	at org.jivesoftware.smackx.muc.MultiUserChat.init(MultiUserChat.java:2025)
	at org.jivesoftware.smackx.muc.MultiUserChat.<init>(MultiUserChat.java:162)
	at org.jitsi.impl.protocol.xmpp.ChatRoomImpl.<init>(ChatRoomImpl.java:153)
	at org.jitsi.impl.protocol.xmpp.OperationSetMultiUserChatImpl.createChatRoom(OperationSetMultiUserChatImpl.java:107)
	at org.jitsi.impl.protocol.xmpp.OperationSetMultiUserChatImpl.findRoom(OperationSetMultiUserChatImpl.java:130)
	at org.jitsi.jicofo.JitsiMeetConferenceImpl.joinTheRoom(JitsiMeetConferenceImpl.java:438)
	at org.jitsi.jicofo.JitsiMeetConferenceImpl.start(JitsiMeetConferenceImpl.java:323)
	at org.jitsi.jicofo.FocusManager.conferenceRequest(FocusManager.java:343)
	at org.jitsi.jicofo.FocusManager.conferenceRequest(FocusManager.java:290)
	at org.jitsi.jicofo.xmpp.FocusComponent.handleConferenceIq(FocusComponent.java:416)
	at org.jitsi.jicofo.xmpp.FocusComponent.handleIQSetImpl(FocusComponent.java:254)
	at org.jitsi.xmpp.component.ComponentBase.handleIQSet(ComponentBase.java:360)
	at org.xmpp.component.AbstractComponent.processIQRequest(AbstractComponent.java:515)
	at org.xmpp.component.AbstractComponent.processIQ(AbstractComponent.java:289)
	at org.xmpp.component.AbstractComponent.processQueuedPacket(AbstractComponent.java:239)
	at org.xmpp.component.AbstractComponent.access$100(AbstractComponent.java:81)
	at org.xmpp.component.AbstractComponent$PacketProcessor.run(AbstractComponent.java:1051)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Jicofo 2017-10-19 06:42:48.177 WARNING: [66] org.jitsi.jicofo.xmpp.FocusComponent.processIQ() (serving component 'Jitsi Meet Focus') Unexpected exception while processing IQ stanza: <iq type="set" to="focus.mydomain.com" from="58246547-14d9-4e2e-be15-dcf8149f0c91@mydomain.com/8f91063c-cf6d-4af9-8734-ea5a0ad0f118" id="2b95f232-ee74-440a-8569-d61ec176402b:sendIQ"><conference xmlns="http://jitsi.org/protocol/focus" room="TestConf@conference.mydomain.com" machine-uid="a18e37affd902da3eeab36a59e92fea5"><property value="-1" name="channelLastN"/><property value="false" name="disableRtx"/><property value="true" name="enableLipSync"/><property value="true" name="openSctp"/></conference></iq>
java.lang.IllegalStateException: Not connected to server.
	at org.jivesoftware.smack.Connection.addConnectionListener(Connection.java:525)
	at org.jivesoftware.smackx.muc.RoomListenerMultiplexor.init(RoomListenerMultiplexor.java:135)
	at org.jivesoftware.smackx.muc.RoomListenerMultiplexor.getRoomMultiplexor(RoomListenerMultiplexor.java:67)
	at org.jivesoftware.smackx.muc.MultiUserChat.init(MultiUserChat.java:2025)
	at org.jivesoftware.smackx.muc.MultiUserChat.<init>(MultiUserChat.java:162)
	at org.jitsi.impl.protocol.xmpp.ChatRoomImpl.<init>(ChatRoomImpl.java:153)
	at org.jitsi.impl.protocol.xmpp.OperationSetMultiUserChatImpl.createChatRoom(OperationSetMultiUserChatImpl.java:107)
	at org.jitsi.impl.protocol.xmpp.OperationSetMultiUserChatImpl.findRoom(OperationSetMultiUserChatImpl.java:130)
	at org.jitsi.jicofo.JitsiMeetConferenceImpl.joinTheRoom(JitsiMeetConferenceImpl.java:438)
	at org.jitsi.jicofo.JitsiMeetConferenceImpl.start(JitsiMeetConferenceImpl.java:323)
	at org.jitsi.jicofo.FocusManager.conferenceRequest(FocusManager.java:343)
	at org.jitsi.jicofo.FocusManager.conferenceRequest(FocusManager.java:290)
	at org.jitsi.jicofo.xmpp.FocusComponent.handleConferenceIq(FocusComponent.java:416)
	at org.jitsi.jicofo.xmpp.FocusComponent.handleIQSetImpl(FocusComponent.java:254)
	at org.jitsi.xmpp.component.ComponentBase.handleIQSet(ComponentBase.java:360)
	at org.xmpp.component.AbstractComponent.processIQRequest(AbstractComponent.java:515)
	at org.xmpp.component.AbstractComponent.processIQ(AbstractComponent.java:289)
	at org.xmpp.component.AbstractComponent.processQueuedPacket(AbstractComponent.java:239)
	at org.xmpp.component.AbstractComponent.access$100(AbstractComponent.java:81)
	at org.xmpp.component.AbstractComponent$PacketProcessor.run(AbstractComponent.java:1051)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
J
```

> # java -version
> openjdk version "1.8.0_131"
> OpenJDK Runtime Environment (build 1.8.0_131-8u131-b11-2ubuntu1.16.04.3-b11)
> OpenJDK 64-Bit Server VM (build 25.131-b11, mixed mode)

**Comment by syswipe** [comment]
UPD: i tried Oracle Java 8u152 build - the same behavior.
full log in attachment
[jicofo.log](https://github.com/jitsi/jitsi-meet/files/1397574/jicofo.log)

**Comment by damencho** [comment]
This log file is missing the startup of jicofo. I suspect that you have also updated auth.your.domain certificate in prosody with wrong one(wrong I mean, with cn value that is not auth.your.domain) and jicofo fails to connect on startup.

If you are using this prosody instance only with jitsi-meet, there is no need to change certificates in prosody config, you only need it in web server config (jetty, nginx, apache), cause this is the world visible point of the deployment and is the only place that is terminating the https connections from clients.

**Comment by kevinscopy** [comment]
A bit of side question: Do I really have to have a live terminal running jicofo?

./jicofo.sh --host=localhost --domain=jitsi.example.com --secret=YOURSECRET2 --user_domain=auth.jitsi.example.com --user_name=focus --user_password=YOURSECRET3

Or is there a way to just make this always running without a live terminal? I get OP's error when I close my terminal. Running on DigitalOcean Ubuntu 14.

**Comment by damencho** [comment]
Are you running from source? The debian packages provide init.d scripts which take care of start/stop procedure and you do not need any terminal open.

**Comment by kevinscopy** [comment]
Hello. Thanks for your swift reply. I did the manual install:

https://github.com/jitsi/jitsi-meet/blob/master/doc/manual-install.md

as 

https://jitsi.org/downloads/ubuntu-debian-installations-instructions/

wasn't working for me. Do I have to re-install? Or is there a way to enable it?

**Comment by damencho** [comment]
Well, the preferred way is the quick install (the second link), not sure what was not working, but it should be straightforward.

The manual install is just some general steps how things work in the quick install, and the manual sometimes lack attention and some steps are outdated and with the manual install, there is no upgrade procedure which you will have when installing the debian packages.
You can, of course, copy the init scripts and modify them to work with your deployment, there are already in the source code.
