### ISSUE TITLE
integrating with existing native project

### ISSUE THREAD

**Issue by tanvir8269** [jitsi/jitsi-meet#2133]
Hi guys,
I am a newbie. I have an existing android app, written completely in java. Now I want to add a button in it. when user clicks on the button I want JitsiMeet Activity to start running. I tried using the android sdk. like i download the package, performed npm install then assembleRelease and publish sdk as mentioned in the README file. After that i added the .aar file to my native project as dependency. Now in my app, the onClick method of my button, I tried to start a new activity. which extends JitsiMeetActivity and so on. it compiles and my app runs. but when i click on the button the app crushes. What am I doing wrong? below is my log,

E/AndroidRuntime: FATAL EXCEPTION: main
	 Process: myorg.myapp, PID: 5147
	 java.lang.NoClassDefFoundError: Failed resolution of: Lcom/facebook/react/ReactInstanceManager;
		 at org.jitsi.meet.sdk.JitsiMeetView.initReactInstanceManager(JitsiMeetView.java:94)
		 at org.jitsi.meet.sdk.JitsiMeetView.<init>(JitsiMeetView.java:275)
		 at myorg.myapp.JoinRoom.onCreate(JoinRoom.java:26)
		 at android.app.Activity.performCreate(Activity.java:6092)
		 at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1112)
		 at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2499)
		 at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2626)
		 at android.app.ActivityThread.access$800(ActivityThread.java:181)
		 at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1473)
		 at android.os.Handler.dispatchMessage(Handler.java:111)
		 at android.os.Looper.loop(Looper.java:194)
		 at android.app.ActivityThread.main(ActivityThread.java:5655)
		 at java.lang.reflect.Method.invoke(Native Method)
		 at java.lang.reflect.Method.invoke(Method.java:372)
		 at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:959)
		 at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:754)
	  Caused by: java.lang.ClassNotFoundException: Didn't find class "com.facebook.react.ReactInstanceManager" on path: DexPathList[[zip file "/data/app/myorg.myapp-1/base.apk", zip file "/data/app/myorg.myapp-1/split_lib_dependencies_apk.apk", zip file "/data/app/myorg.myapp-1/split_lib_slice_0_apk.apk", zip file "/data/app/myorg.myapp-1/split_lib_slice_1_apk.apk", zip file "/data/app/myorg.myapp-1/split_lib_slice_2_apk.apk", zip file "/data/app/myorg.myapp-1/split_lib_slice_3_apk.apk", zip file "/data/app/myorg.myapp-1/split_lib_slice_4_apk.apk", zip file "/data/app/myorg.myapp-1/split_lib_slice_5_apk.apk", zip file "/data/app/myorg.myapp-1/split_lib_slice_6_apk.apk", zip file "/data/app/myorg.myapp-1/split_lib_slice_7_apk.apk", zip file "/data/app/myorg.myapp-1/split_lib_slice_8_apk.apk", zip file "/data/app/myorg.myapp-1/split_lib_slice_9_apk.apk"],nativeLibraryDirectories=[/vendor/lib64, /system/lib64]]
		 at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
		 at java.lang.ClassLoader.loadClass(ClassLoader.java:511)
		 at java.lang.ClassLoader.loadClass(ClassLoader.java:469)
		 at org.jitsi.meet.sdk.JitsiMeetView.initReactInstanceManager(JitsiMeetView.java:94) 
		 at org.jitsi.meet.sdk.JitsiMeetView.<init>(JitsiMeetView.java:275) 
		 at myorg.myapp.JoinRoom.onCreate(JoinRoom.java:26) 
		 at android.app.Activity.performCreate(Activity.java:6092) 
		 at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1112) 
		 at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2499) 
		 at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2626) 
		 at android.app.ActivityThread.access$800(ActivityThread.java:181) 
		 at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1473) 
		 at android.os.Handler.dispatchMessage(Handler.java:111) 
		 at android.os.Looper.loop(Looper.java:194) 
		 at android.app.ActivityThread.main(ActivityThread.java:5655) 
		 at java.lang.reflect.Method.invoke(Native Method) 
		 at java.lang.reflect.Method.invoke(Method.java:372) 
		 at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:959) 
		 at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:754) 
		Suppressed: java.lang.ClassNotFoundException: com.facebook.react.ReactInstanceManager
		 at java.lang.Class.classForName(Native Method)
		 at java.lang.BootClassLoader.findClass(ClassLoader.java:781)
		 at java.lang.BootClassLoader.loadClass(ClassLoader.java:841)
		 at java.lang.ClassLoader.loadClass(ClassLoader.java:504)
				... 17 more
	  Caused by: java.lang.NoClassDefFoundError: Class not found using the boot class loader; no stack available

**Comment by lyubomir** [comment]
`java.lang.NoClassDefFoundError: Failed resolution of: Lcom/facebook/react/ReactInstanceManager` suggests that you haven't bundled all your dependencies. You probably need to tell Gradle that sdk needs its `transitional` dependencies as well.

**Comment by tanvir8269** [comment]
@lyubomir thanks for the quick response. I overlooked the part where when using sdk for 3rd party app we must assemble and publish the 5 react module, the sdk depends on. In addition, we also need to copy the react-native archive to from "node_module/react-native/android" to the maven repo where all the react module was published(i.e. /path/to/maven/jitsi/jitsi-maven-repo/releases/com/fb/react ). anyway now its working properly in my app.

**Comment by sachinrkeche** [comment]
Hello Dear , @tanvir8269 I am having the same issue will you please explain it in more detail , i have issue while publishing the react module and got following error , when i fired this command in 
in  / android directory , 
./gradlew :react-native-webrtc:publish 

* What went wrong:
Execution failed for task ':react-native-webrtc:publishAarArchivePublicationToMaven2Repository'.
> Failed to publish publication 'aarArchive' to repository 'maven2'
   > Invalid publication 'aarArchive': artifact file does not exist: '/Users/arpitmakhija/Downloads/SachinWorkspace/JitsiIntegration/jitsi-meet/node_modules/react-native-webrtc/android/build/outputs/aar/react-native-webrtc-release.aar'

please help me out, Advance Thanks .

**Comment by XiaopingTan** [comment]
I am have the same issue, too

**Comment by tanvir8269** [comment]
checkout this write up https://github.com/jitsi/jitsi-meet/wiki/Adding-android-sdk-for-3rd-party-fully-native-project
