### ISSUE TITLE
host-unknown, host:localhost, port:5347

### ISSUE THREAD

**Issue by tcmalloc** [jitsi/jitsi-meet#2206]
JVB 2017-11-22 22:41:17.407 SEVERE: [18] org.jitsi.meet.ComponentMain.call().278 host-unknown, host:localhost, port:5347
org.xmpp.component.ComponentException: host-unknown
        at org.jivesoftware.whack.ExternalComponent.connect(ExternalComponent.java:243)
        at org.jivesoftware.whack.ExternalComponentManager.addComponent(ExternalComponentManager.java:242)
        at org.jivesoftware.whack.ExternalComponentManager.addComponent(ExternalComponentManager.java:222)
        at org.jitsi.meet.ComponentMain$3.call(ComponentMain.java:270)
        at org.jitsi.meet.ComponentMain$3.call(ComponentMain.java:255)
        at org.jitsi.retry.RetryStrategy$TaskRunner.run(RetryStrategy.java:193)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)

**Comment by damencho** [comment]
This is not jitsi-meet issue, but jicofo or jvb, this is not obvious from your report. Please provide more info, giving more details, if you want an answer to your questions.

The parameter that you pass as domain, that is used to create the component address:
focus.domain in case of jicofo, or jitsi-videobridge.domain 
and that component address is not configured in prosody for some reason.
