### ISSUE TITLE
simple jitsi setup?

### ISSUE THREAD

**Issue by bendavid42** [jitsi/jitsi-meet#2362]
I am admittedly pretty new to SIP. But I am pretty tech savvy with wide IT background. (networking, *nix/windows servers, java/sql, scripting, workstations, etc)  

Anyway I have an asterisk server (with a dialer running on top of it), and we have cisco 303 phones, and we normally just point them to the IP address of the Asterisk server and enter username and password, and that's it.  They work.  Jitsi, I am able to find place to enter my own proxy and user/pass... In cisco phones it tells if it's "registered" or not - not sure where to see that in Jitsi, I just see my status "online". 

I try to dial a number (for our server 8-1-###-###-#### to manual dial) and it says `Failed to create the call. 81########## could not be resolved to an internet address` more info link says....

```java.lang.IllegalArgumentException: 813363030236 could not be resolved to an internet address.
	at net.java.sip.communicator.impl.protocol.sip.ProtocolProviderServiceSipImpl.getIntendedDestination(ProtocolProviderServiceSipImpl.java:2592)
	at net.java.sip.communicator.impl.protocol.sip.ProtocolProviderServiceSipImpl.getOurSipAddress(ProtocolProviderServiceSipImpl.java:1854)
	at net.java.sip.communicator.impl.protocol.sip.ProtocolProviderServiceSipImpl.getOurSipAddress(ProtocolProviderServiceSipImpl.java:1831)
	at net.java.sip.communicator.impl.protocol.sip.SipMessageFactory.createInviteRequest(SipMessageFactory.java:773)
	at net.java.sip.communicator.impl.protocol.sip.SipMessageFactory.createInviteRequest(SipMessageFactory.java:878)
	at net.java.sip.communicator.impl.protocol.sip.CallSipImpl.invite(CallSipImpl.java:481)
	at net.java.sip.communicator.impl.protocol.sip.OperationSetBasicTelephonySipImpl.createOutgoingCall(OperationSetBasicTelephonySipImpl.java:199)
	at net.java.sip.communicator.impl.protocol.sip.OperationSetBasicTelephonySipImpl.createCall(OperationSetBasicTelephonySipImpl.java:141)
	at net.java.sip.communicator.service.protocol.media.AbstractOperationSetBasicTelephony.createCall(AbstractOperationSetBasicTelephony.java:122)
	at net.java.sip.communicator.impl.gui.main.call.CallManager.internalCall(CallManager.java:2715)
	at net.java.sip.communicator.impl.gui.main.call.CallManager.access$900(CallManager.java:60)
	at net.java.sip.communicator.impl.gui.main.call.CallManager$CreateCallThread.run(CallManager.java:2596)
```

to "login" to the dialer software, you dial *77, when I do that I get `"failed to create the call. sip:*77: missing hostname.`  more info link...

```
java.lang.IllegalArgumentException: 81########### could not be resolved to an internet address.
	at net.java.sip.communicator.impl.protocol.sip.ProtocolProviderServiceSipImpl.getIntendedDestination(ProtocolProviderServiceSipImpl.java:2592)
	at net.java.sip.communicator.impl.protocol.sip.ProtocolProviderServiceSipImpl.getOurSipAddress(ProtocolProviderServiceSipImpl.java:1854)
	at net.java.sip.communicator.impl.protocol.sip.ProtocolProviderServiceSipImpl.getOurSipAddress(ProtocolProviderServiceSipImpl.java:1831)
	at net.java.sip.communicator.impl.protocol.sip.SipMessageFactory.createInviteRequest(SipMessageFactory.java:773)
	at net.java.sip.communicator.impl.protocol.sip.SipMessageFactory.createInviteRequest(SipMessageFactory.java:878)
	at net.java.sip.communicator.impl.protocol.sip.CallSipImpl.invite(CallSipImpl.java:481)
	at net.java.sip.communicator.impl.protocol.sip.OperationSetBasicTelephonySipImpl.createOutgoingCall(OperationSetBasicTelephonySipImpl.java:199)
	at net.java.sip.communicator.impl.protocol.sip.OperationSetBasicTelephonySipImpl.createCall(OperationSetBasicTelephonySipImpl.java:141)
	at net.java.sip.communicator.service.protocol.media.AbstractOperationSetBasicTelephony.createCall(AbstractOperationSetBasicTelephony.java:122)
	at net.java.sip.communicator.impl.gui.main.call.CallManager.internalCall(CallManager.java:2715)
	at net.java.sip.communicator.impl.gui.main.call.CallManager.access$900(CallManager.java:60)
	at net.java.sip.communicator.impl.gui.main.call.CallManager$CreateCallThread.run(CallManager.java:2596)

```

Any direction would be greatly appreciated.  I have full root access to the servers, firewalls, workstations, etc.  I'm new to SIP, but not networking/firewalls/servers.  A point in the right direction is likely all that I need. 

Thanks!

**Comment by bendavid42** [comment]
p.s. in the cisco phones we do define a dial plan.  (i.e. the types of character strings that qualify as something to dial and how long to wait until we dial or wait for more digits if we have a match, etc, etc.... I don't see anything like that in jitsu, but maybe I am missing it, or maybe there is a default plan that I just need to abide by. 

Any direction would be greatly appreciated. I have full root access to the servers, firewalls, workstations, etc. I'm new to SIP, but not networking/firewalls/servers. A point in the right direction is likely all that I need.

Thanks!

**Comment by saghul** [comment]
I guess your problem relates either to the desktop client (jitsi/jitsi) or to jigasi, can you please open the issue on the appropriate repository? Cheers!
