### ISSUE TITLE
Others can not join my meet

### ISSUE THREAD

**Issue by TTTTTTTK** [jitsi/jitsi-meet#2384]
Everyone start a new meet with the same url will start a new meet and nobody can join 
UnhandledError: null Script: null Line: null Column: null StackTrace:  Error: Focus error, retry after 32000

**Comment by damencho** [comment]
Check your jicofo logs for errors.

**Comment by TTTTTTTK** [comment]
org.xmpp.component.ComponentException: not-authorized
	at org.jivesoftware.whack.ExternalComponent.connect(ExternalComponent.java:243)
	at org.jivesoftware.whack.ExternalComponentManager.addComponent(ExternalComponentManager.java:242)
	at org.jivesoftware.whack.ExternalComponentManager.addComponent(ExternalComponentManager.java:222)
	at org.jitsi.meet.ComponentMain$3.call(ComponentMain.java:270)
	at org.jitsi.meet.ComponentMain$3.call(ComponentMain.java:255)
	at org.jitsi.retry.RetryStrategy$TaskRunner.run(RetryStrategy.java:193)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Jicofo 2018-01-11 08:44:12.177 SEVERE: [30] org.jitsi.impl.protocol.xmpp.XmppProtocolProvider.log() Failed to connect/login: SASLError using SCRAM-SHA-1: not-authorized
org.jivesoftware.smack.sasl.SASLErrorException: SASLError using SCRAM-SHA-1: not-authorized
	at org.jivesoftware.smack.SASLAuthentication.authenticationFailed(SASLAuthentication.java:291)
	at org.jivesoftware.smack.tcp.XMPPTCPConnection$PacketReader.parsePackets(XMPPTCPConnection.java:1084)
	at org.jivesoftware.smack.tcp.XMPPTCPConnection$PacketReader.access$300(XMPPTCPConnection.java:982)
	at org.jivesoftware.smack.tcp.XMPPTCPConnection$PacketReader$1.run(XMPPTCPConnection.java:998)
	at java.lang.Thread.run(Thread.java:748)
Jicofo 2018-01-11 08:44:12.195 WARNING: [35] org.jivesoftware.smack.roster.Roster.processStanza() Roster not loaded while processing Presence Stanza [id=FsSqK-5,type=error,]
Jicofo 2018-01-11 08:44:16.716 SEVERE: [29] org.jitsi.meet.ComponentMain.call().278 not-authorized, host:localhost, port:5347
org.xmpp.component.ComponentException: not-authorized
	at org.jivesoftware.whack.ExternalComponent.connect(ExternalComponent.java:243)
	at org.jivesoftware.whack.ExternalComponentManager.addComponent(ExternalComponentManager.java:242)
	at org.jivesoftware.whack.ExternalComponentManager.addComponent(ExternalComponentManager.java:222)
	at org.jitsi.meet.ComponentMain$3.call(ComponentMain.java:270)
	at org.jitsi.meet.ComponentMain$3.call(ComponentMain.java:255)
	at org.jitsi.retry.RetryStrategy$TaskRunner.run(RetryStrategy.java:193)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Jicofo 2018-01-11 08:44:17.327 SEVERE: [30] org.jitsi.impl.protocol.xmpp.XmppProtocolProvider.log() Failed to connect/login: SASLError using SCRAM-SHA-1: not-authorized
org.jivesoftware.smack.sasl.SASLErrorException: SASLError using SCRAM-SHA-1: not-authorized
	at org.jivesoftware.smack.SASLAuthentication.authenticationFailed(SASLAuthentication.java:291)
	at org.jivesoftware.smack.tcp.XMPPTCPConnection$PacketReader.parsePackets(XMPPTCPConnection.java:1084)
	at org.jivesoftware.smack.tcp.XMPPTCPConnection$PacketReader.access$300(XMPPTCPConnection.java:982)
	at org.jivesoftware.smack.tcp.XMPPTCPConnection$PacketReader$1.run(XMPPTCPConnection.java:998)
	at java.lang.Thread.run(Thread.java:748)
Jicofo 2018-01-11 08:44:17.330 WARNING: [35] org.jivesoftware.smack.roster.Roster.processStanza() Roster not loaded while processing Presence Stanza [id=FsSqK-7,type=error,]
Jicofo 2018-01-11 08:44:21.702 SEVERE: [28] org.jitsi.xmpp.component.ComponentBase.run().589 Failed to send ping
java.lang.NullPointerException
	at org.xmpp.component.AbstractComponent.send(AbstractComponent.java:925)
	at org.jitsi.xmpp.component.ComponentBase.access$400(ComponentBase.java:36)
	at org.jitsi.xmpp.component.ComponentBase$PingTask.run(ComponentBase.java:577)
	at java.util.TimerThread.mainLoop(Timer.java:555)
	at java.util.TimerThread.run(Timer.java:505)
Jicofo 2018-01-11 08:44:21.719 SEVERE: [29] org.jitsi.meet.ComponentMain.call().278 not-authorized, host:localhost, port:5347
org.xmpp.component.ComponentException: not-authorized
	at org.jivesoftware.whack.ExternalComponent.connect(ExternalComponent.java:243)
	at org.jivesoftware.whack.ExternalComponentManager.addComponent(ExternalComponentManager.java:242)
	at org.jivesoftware.whack.ExternalComponentManager.addComponent(ExternalComponentManager.java:222)
	at org.jitsi.meet.ComponentMain$3.call(ComponentMain.java:270)
	at org.jitsi.meet.ComponentMain$3.call(ComponentMain.java:255)
	at org.jitsi.retry.RetryStrategy$TaskRunner.run(RetryStrategy.java:193)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Jicofo 2018-01-11 08:44:22.430 SEVERE: [36] org.jitsi.impl.protocol.xmpp.XmppProtocolProvider.log() Failed to connect/login: SASLError using SCRAM-SHA-1: not-authorized

**Comment by saghul** [comment]
> org.xmpp.component.ComponentException: not-authorized

Looks like jicofo is not properly authenticating with your prosody server. Check the password you configured on both.

**Comment by atb00ker** [comment]
(1) It is recommend to use services like pastebin, hastepin or github gist to send such log files or codes.
(2) These folders are a useful place to start looking for details:
  - /var/log/jitsi
  - /var/log/prosody
  - /etc/prosody
  - /etc/jitsi
**Note: I am not a developer or maintainer at jitsi, I am stuck myself and hence i know a little bit!**

**Comment by TTTTTTTK** [comment]
Thanks for your help @damencho @saghul @atb00ker

**Comment by TTTTTTTK** [comment]
I check the jicofo.log :
  org.xmpp.component.ComponentException: not-authorized
	at org.jivesoftware.whack.ExternalComponent.connect(ExternalComponent.java:243)
	at org.jivesoftware.whack.ExternalComponentManager.addComponent(ExternalComponentManager.java:242)
	at org.jivesoftware.whack.ExternalComponentManager.addComponent(ExternalComponentManager.java:222)
	at org.jitsi.meet.ComponentMain$3.call(ComponentMain.java:270)
	at org.jitsi.meet.ComponentMain$3.call(ComponentMain.java:255)
	at org.jitsi.retry.RetryStrategy$TaskRunner.run(RetryStrategy.java:193)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Jicofo 2018-01-24 03:56:24.274 SEVERE: [30] org.jitsi.impl.protocol.xmpp.XmppProtocolProvider.log() Failed to connect/login: SASLError using SCRAM-SHA-1: not-authorized
org.jivesoftware.smack.sasl.SASLErrorException: SASLError using SCRAM-SHA-1: not-authorized
	at org.jivesoftware.smack.SASLAuthentication.authenticationFailed(SASLAuthentication.java:291)
	at org.jivesoftware.smack.tcp.XMPPTCPConnection$PacketReader.parsePackets(XMPPTCPConnection.java:1084)
	at org.jivesoftware.smack.tcp.XMPPTCPConnection$PacketReader.access$300(XMPPTCPConnection.java:982)
	at org.jivesoftware.smack.tcp.XMPPTCPConnection$PacketReader$1.run(XMPPTCPConnection.java:998)
	at java.lang.Thread.run(Thread.java:748)
Jicofo 2018-01-24 03:56:24.283 WARNING: [36] org.jivesoftware.smack.roster.Roster.processStanza() Roster not loaded while processing Presence Stanza [id=qO2PI-5,type=error,]
Jicofo 2018-01-24 03:56:28.947 SEVERE: [29] org.jitsi.meet.ComponentMain.call().278 not-authorized, host:localhost, port:5347

what should i do to fix it .

**Comment by damencho** [comment]
Both component connection and client connection are not authorized. Check your /etc/jitsi/jicofo/config
Make sure JICOFO_SECRET is correct, you can check that in your prosody config search for component focus.your-domain-name.
Also, check that JICOFO_AUTH_PASSWORD is correct, this can be verified by looking into the prosody storage files: 
/var/lib/prosody/auth%2eyour-domain-name/accounts/focus.dat

**Comment by TTTTTTTK** [comment]
Now i can start a meet with two people , but when the third people join ,all screen will be black,no audio or video. 
If one quit ,it goes well again .
Here are logs.
[jicofo.log](https://github.com/jitsi/jitsi-meet/files/1662305/jicofo.log)
[jvb.log](https://github.com/jitsi/jitsi-meet/files/1662306/jvb.log)

**Comment by damencho** [comment]
Yep, you need to check my previous comment. Jicofo is not authorized when trying to connect?

**Comment by TTTTTTTK** [comment]
Can you tell me how to fix it ,which document should i modify .
I have tried to user same component_secret,but it did not work .

**Comment by damencho** [comment]
In /etc/jitsi/jicofo/config, check the value for JICOFO_AUTH_PASSWORD, should be the same as the password stored in /var/lib/prosody/auth%2eyour-domain-name/accounts/focus.dat. Restart jicofo.

**Comment by TTTTTTTK** [comment]
The  JICOFO_AUTH_PASSWORD is the same as the password stored in /var/lib/prosody/auth%2eyour-domain-name/accounts/focus.dat.
I tried ./jicofo.sh  ,but connection refused.
(    SEVERE: java.net.ConnectException: Connection refused (Connection refused), host:10.1.159.130, port:5347
org.xmpp.component.ComponentException: java.net.ConnectException: Connection refused (Connection refused)  )
Did do sth wrong?
[10.1.159.130-config.txt](https://github.com/jitsi/jitsi-meet/files/1666350/10.1.159.130-config.txt)

**Comment by bgrozev** [comment]
Make sure prosody is configured to listen on this address (10.1.159.130:5347). It may be only listening on localhost, in that case check the component_interface option in its config file.

**Comment by TTTTTTTK** [comment]
There is no error in the log ,but i still can not start a meet with more than two person.
（I installed the server behind the nat ）

**Comment by saghul** [comment]
@TTTTTTTK on the jvb logs I see all ICE checks failed, which is not surprising since your server is behind NAT. You'll need to configure ice4j in order for this work. Have a look at https://github.com/jitsi/ice4j/blob/master/doc/configuration.md#mapping-harvesters and add the harvester configuration into the sip-communicator.properties file for the jvb.

**Comment by TTTTTTTK** [comment]
What udp and tcp ports are needed ?
Or can you tell me the range of udp and tcp ports if i do not install the server behind NAT?

**Comment by damencho** [comment]
https://github.com/jitsi/jitsi-meet/blob/master/doc/quick-install.md#advanced-configuration

**Comment by TTTTTTTK** [comment]
Thank you,I have solved those problems.I think this is the best among the projects i had tested.
If i want to develop a project build on it ,what should i do to deal with the audio and video streams,the original streams is too hard for Network Bandwidth  ,MCU or SFU ,which is better ?
Can u give me some suggestions if i want to deploy cluster service?

**Comment by saghul** [comment]
@TTTTTTTK Please use the mailing list for such questions. I'm going to close this issue since you said it's now resolved.
