### ISSUE TITLE
java.lang.UnsatisfiedLinkError: dlopen failed: library "libjsc.so" not found [App Crashed]

### ISSUE THREAD

**Issue by tushar-patil-android** [jitsi/jitsi-meet#2389]
I used jitsi in my android application but got this error and app crashed "**java.lang.UnsatisfiedLinkError: dlopen failed: library "libjsc.so" not found**".

Please help me to solve this issue.

**Comment by tushar-patil-android** [comment]
Stacktrace - 

01-16 12:56:22.284 29992-30132/chat.rocket.android E/UncaughtException: java.lang.UnsatisfiedLinkError: dlopen failed: library "libjsc.so" not found
                                                                            at java.lang.Runtime.load0(Runtime.java:897)
                                                                            at java.lang.System.load(System.java:1505)
                                                                            at com.facebook.soloader.DirectorySoSource.loadLibraryFrom(DirectorySoSource.java:71)
                                                                            at com.facebook.soloader.DirectorySoSource.loadLibrary(DirectorySoSource.java:42)
                                                                            at com.facebook.soloader.SoLoader.loadLibraryBySoName(SoLoader.java:299)
                                                                            at com.facebook.soloader.SoLoader.loadLibrary(SoLoader.java:247)
                                                                            at com.facebook.react.bridge.ReactBridge.staticInit(ReactBridge.java:20)
                                                                            at com.facebook.react.bridge.NativeMap.<clinit>(NativeMap.java:21)
                                                                            at com.facebook.react.bridge.JSCJavaScriptExecutorFactory.create(JSCJavaScriptExecutorFactory.java:15)
                                                                            at com.facebook.react.ReactInstanceManager$4.run(ReactInstanceManager.java:833)
                                                                            at java.lang.Thread.run(Thread.java:761)

**Comment by saghul** [comment]
Do you happen to be using Google Analytics on your project too? See https://github.com/facebook/react-native/issues/4172

**Comment by vtnhondk** [comment]
![screen shot 2018-03-09 at 16 08 14](https://user-images.githubusercontent.com/11543501/37199406-1c006d64-23b4-11e8-8866-742acf6a69c8.png)
@tushar-patil-android  Have that files in your app ? If not using 
`node node_modules/react-native/local-cli/cli.js bundle 
--assets-dest $resourcesDir$ 
--bundle-output $jsBundleFile$ 
--dev --entry-file index.android.js 
--platform android 
--reset-cache `
to build and move that to your app assets.

**Comment by asnagni** [comment]
I'm having the same issue.

**Comment by ashtrisk** [comment]
Hey guys, I am getting the same issue. I have built one module of opencv into .so file myself. I am trying to load this in my project, but getting this error. Any solutions yet?
