### ISSUE TITLE
"jitsi_meet_transcribe" how to use the configuration

### ISSUE THREAD

**Issue by xiaoqge** [jitsi/jitsi-meet#2461]
"""It is now possible to use Jigasi as a transcriber in a Jitsi Meet room! You can normally dial Jigasi into a room by using the “Call SIP” button. This would create a bridge between the Jitsi Meet conference and a SIP endpoint. Instead of using a normal SIP URI, you can use jitsi_meet_transcribe. This will make Jigasi join as a transcriber instead of forwarding the audio to the SIP number. Note that using the “Call SIP” button to dial the transcriber into the room is only a temporary solution and will be replaced with a proper UI element."""

I read this document, I do not know how to get configuration, open speech-to-text? Please help me, give me a hint or reference, thank you

**Comment by xiaoqge** [comment]
# org.jitsi.jigasi.transcription.BASE_URL=http://localhost/
# org.jitsi.jigasi.transcription.PORT=-1

The meaning of these two parameters is the need to achieve their own services? I do not understand

**Comment by xiaoqge** [comment]
I executed APP.conference._room.dial ("jitsi_meet_transcribe") Now the state has been initialized, here is my log

jisti.log

```
Jicofo 2018-02-07 20:30:06.029 WARNING: [38] org.jitsi.protocol.xmpp.AbstractOperationSetJingle.processJingleIQ().345 unsupported action session-info
Jicofo 2018-02-07 20:30:06.291 INFO: [38] org.jitsi.jicofo.JitsiMeetConferenceImpl.log() Received sources from siptest@conference.v.123123.com/161703e8e8b Sources{ audio: [ssrc=2949136311 ] }@1276554518
Jicofo 2018-02-07 20:30:06.291 INFO: [38] org.jitsi.protocol.xmpp.AbstractOperationSetJingle.sendAddSourceIQ().455 Notify add SSRC siptest@conference.v.123123.com/7d488b56 SID: 1tln28j2s8uva Sources{ audio: [ssrc=2949136311 ] video: [] }@1276554518 source_Groups{ }@1019580015
Jicofo 2018-02-07 20:30:06.292 INFO: [38] org.jitsi.protocol.xmpp.AbstractOperationSetJingle.sendAddSourceIQ().455 Notify add SSRC siptest@conference.v.123123.com/74550a32 SID: 7af6ihnopjl4q Sources{ audio: [ssrc=2949136311 ] video: [] }@1276554518 source_Groups{ }@1019580015
Jicofo 2018-02-07 20:30:08.270 WARNING: [30] org.jivesoftware.smack.util.PacketParserUtils.parsePresence() Failed to parse extension element in Presence stanza: "java.lang.IllegalArgumentException: Namespace must not be null or empty" from: 'siptest@conference.v.123123.com/161703e8e8b id: '883Sx-7
```


jigasi.log

```
[2018-02-07 20:32:00.231 WARNING: [257] org.jitsi.jigasi.transcription.GoogleCloudTranscriptionService.log() Received an error from the Google Cloud API
io.grpc.StatusRuntimeException: INTERNAL: Connection closed with unknown cause
        at io.grpc.Status.asRuntimeException(Status.java:540)
        at io.grpc.stub.ClientCalls$StreamObserverToCallListenerAdapter.onClose(ClientCalls.java:392)
        at io.grpc.internal.ClientCallImpl.closeObserver(ClientCallImpl.java:428)
        at io.grpc.internal.ClientCallImpl.access$100(ClientCallImpl.java:76)
        at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl.close(ClientCallImpl.java:514)
        at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl.access$700(ClientCallImpl.java:431)
        at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl$1StreamClosed.runInContext(ClientCallImpl.java:546)
        at io.grpc.internal.ContextRunnable.run(ContextRunnable.java:52)
        at io.grpc.internal.SerializingExecutor$TaskRunner.run(SerializingExecutor.java:152)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)]
```

**Comment by rakibulinux** [comment]
> I executed APP.conference._room.dial ("jitsi_meet_transcribe") Now the state has been initialized, here is my log
How I can execute this? Is it any command? I try it on server but don't know how to execute this. Please help me to work on this.

**Comment by ManolisPapaspyropoulosAUEB** [comment]
anybody is able to anwer this??
how execute this command APP.conference._room.dial ("jitsi_meet_transcribe") ???

**Comment by damencho** [comment]
This goes in the js console.

**Comment by ManolisPapaspyropoulosAUEB** [comment]
Thanks for the quick reply!!
I am new to this, I have displayed the "cc" button but I do not see results on the screen when i clicked.
I have followed all the steps for the installation but unfortunately I am doing something wrong.

**Comment by ManolisPapaspyropoulosAUEB** [comment]
finally its work for me,thanks!
