### ISSUE TITLE
[Android ] Add Jitsi Meet View Into Layout XML

### ISSUE THREAD

**Issue by samk17cmutpm** [jitsi/jitsi-meet#2465]
Is that possible for us to add Jitsi Meet View Into Layout XML like this 
![add_into_view](https://user-images.githubusercontent.com/7029528/35966974-0a566d30-0cf2-11e8-9daf-7e50014cc01b.png)

**Comment by saghul** [comment]
I guess so, but you need to configure the view and call the load methods as you need. Are you running into any specific problems?

**Comment by samk17cmutpm** [comment]
Hi, When I wrote some thing like this 
view = (JitsiMeetView) findViewById(R.id.jitsi_meet_view);
The app crashed, What should I do for this case ???

**Comment by saghul** [comment]
Hum, I have never used it that way, can you please paste the backtrace?

**Comment by samk17cmutpm** [comment]
Hi, thanks a lot for quick response !!                                                                   
   Process: jp.co.neolab.calling, PID: 17774
                                                                      java.lang.RuntimeException: Unable to start activity ComponentInfo{jp.co.neolab.calling/com.neo_lab.calling.presentation.ui.jitsi_meet_conference.JitsiMeetActivity}: android.view.InflateException: Binary XML file line #0: Binary XML file line #0: Error inflating class org.jitsi.meet.sdk.JitsiMeetView
                                                                          at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2984)
                                                                          at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3045)
                                                                          at android.app.ActivityThread.-wrap14(ActivityThread.java)
                                                                          at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1642)
                                                                          at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                          at android.os.Looper.loop(Looper.java:154)
                                                                          at android.app.ActivityThread.main(ActivityThread.java:6776)
                                                                          at java.lang.reflect.Method.invoke(Native Method)
                                                                          at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1518)
                                                                          at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1408)
                                                                       Caused by: android.view.InflateException: Binary XML file line #0: Binary XML file line #0: Error inflating class org.jitsi.meet.sdk.JitsiMeetView
                                                                       Caused by: android.view.InflateException: Binary XML file line #0: Error inflating class org.jitsi.meet.sdk.JitsiMeetView
                                                                       Caused by: java.lang.NoSuchMethodException: <init> [class android.content.Context, interface android.util.AttributeSet]
                                                                          at java.lang.Class.getConstructor0(Class.java:2204)
                                                                          at java.lang.Class.getConstructor(Class.java:1683)
                                                                          at android.view.LayoutInflater.createView(LayoutInflater.java:625)
                                                                          at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:794)
                                                                          at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:734)
                                                                          at android.view.LayoutInflater.rInflate(LayoutInflater.java:865)
                                                                          at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:828)
                                                                          at android.view.LayoutInflater.inflate(LayoutInflater.java:525)
                                                                          at android.view.LayoutInflater.inflate(LayoutInflater.java:427)
                                                                          at android.view.LayoutInflater.inflate(LayoutInflater.java:378)
                                                                          at android.support.v7.app.AppCompatDelegateImplV9.setContentView(AppCompatDelegateImplV9.java:292)
                                                                          at android.support.v7.app.AppCompatActivity.setContentView(AppCompatActivity.java:140)
                                                                          at com.neo_lab.calling.presentation.ui.jitsi_meet_conference.JitsiMeetActivity.onCreate(JitsiMeetActivity.java:44)
                                                                          at android.app.Activity.performCreate(Activity.java:6956)
                                                                          at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1126)
                                                                          at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2927)
                                                                          at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3045)
                                                                          at android.app.ActivityThread.-wrap14(ActivityThread.java)
                                                                          at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1642)
                                                                          at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                          at android.os.Looper.loop(Looper.java:154)
                                                                          at android.app.ActivityThread.main(ActivityThread.java:6776)
                                                                          at java.lang.reflect.Method.invoke(Native Method)
                                                                          at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1518)
                                                                          at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1408)
02-08 19:51:36.907 17871-17871/? E/Zygote: v2
![stack_strace](https://user-images.githubusercontent.com/7029528/35973861-8eb74128-0d09-11e8-8470-ecea3e400197.png)

**Comment by saghul** [comment]
Looks like the SDK (and its dependencies, I guess) is not getting bundled correctly or something similar. How did you add the dependency in your project?

**Comment by samk17cmutpm** [comment]
![1](https://user-images.githubusercontent.com/7029528/35978504-86c0ae5a-0d18-11e8-929f-7ead0097ca81.png)
![2](https://user-images.githubusercontent.com/7029528/35978508-89d821cc-0d18-11e8-889b-81d29e403020.png)
![3](https://user-images.githubusercontent.com/7029528/35978516-8c44b100-0d18-11e8-8b6a-3fb579bede24.png)
![4](https://user-images.githubusercontent.com/7029528/35978521-8e4be20c-0d18-11e8-9f71-80da65d7d384.png)
![5](https://user-images.githubusercontent.com/7029528/35978524-90243c3c-0d18-11e8-9861-11563bd80a4b.png)
![6](https://user-images.githubusercontent.com/7029528/35978527-91f5e27c-0d18-11e8-9b98-c0ff8c93e454.png)
![7](https://user-images.githubusercontent.com/7029528/35978530-941c1b70-0d18-11e8-8c93-283f1c63c394.png)
![8](https://user-images.githubusercontent.com/7029528/35978534-95e3b95e-0d18-11e8-858f-3650ff98a714.png)
![9](https://user-images.githubusercontent.com/7029528/35978537-97e6af2c-0d18-11e8-8321-55666e522ba5.png)

**Comment by samk17cmutpm** [comment]
Did I do correctly ??

**Comment by saghul** [comment]
Can you please try to enable transitive dependencies? See https://github.com/jitsi/jitsi-meet/issues/2264#issuecomment-352486384

**Comment by tecnomics** [comment]
Load it programmatically 

  jitsiView = new JitsiMeetView(MainActivity.this);
  linearLayoutJitsi.addView(jitsiView);

**Comment by asad175** [comment]
Hi, I have added Jitsi meetviewprogramatically into my layout in this way, But my picture Jitsi meetview is fluctuating and camera is not able to focus properly it keeps on fluctuatiing. Can anyone help.

My Code
jitsiView = new JitsiMeetView(MainActivity.this);
relativeLayoutJitsi.addView(jitsiView);

**Comment by ravitejapuvvada** [comment]
@asad175 
I am also having same issue. Are you able to resolve it?

**Comment by ravitejapuvvada** [comment]
> Hi, I have added Jitsi meetviewprogramatically into my layout in this way, But my picture Jitsi meetview is fluctuating and camera is not able to focus properly it keeps on fluctuatiing. Can anyone help.
> 
> My Code
> jitsiView = new JitsiMeetView(MainActivity.this);
> relativeLayoutJitsi.addView(jitsiView);

I am having the same issue. Is something worked for you?

**Comment by asad175** [comment]
> > Hi, I have added Jitsi meetviewprogramatically into my layout in this way, But my picture Jitsi meetview is fluctuating and camera is not able to focus properly it keeps on fluctuatiing. Can anyone help.
> > My Code
> > jitsiView = new JitsiMeetView(MainActivity.this);
> > relativeLayoutJitsi.addView(jitsiView);
> 
> I am having the same issue. Is something worked for you?

Hi, Yes I have solved it, by using a Framelayout and giving it fixed height and width. Here I have already posted answer on Stackoverflow.
https://stackoverflow.com/a/62323195/5701085
