### ISSUE TITLE
[Android] I integrated JitsiMeet Sdk into my application, But sometimes the app crashed. Could some one help me out ?

### ISSUE THREAD

**Issue by samk17cmutpm** [jitsi/jitsi-meet#2534]
Fatal Exception: java.lang.NoClassDefFoundError: Failed resolution of: Lcom/google/devtools/build/android/desugar/runtime/ThrowableExtension;
       at org.webrtc.Logging.getStackTraceString(Logging.java:176)
       at org.webrtc.Logging.e(Logging.java:156)
       at org.webrtc.MediaCodecVideoDecoder$1.run(MediaCodecVideoDecoder.java:383)
       at java.lang.Thread.run(Thread.java:762)

**Comment by lyubomir** [comment]
If I remember it right, you need Java 1.8 source and target compatibility.

**Comment by paweldomas** [comment]
Yes, we have added that recently to be able to update WebRTC:
https://github.com/jitsi/jitsi-meet/blob/master/android/README.md#install
