### ISSUE TITLE
Jicofo SSL handshake problem type:question

### ISSUE THREAD

**Issue by tuncK** [jitsi/jitsi-meet#2768]
I recently installed the stable version of jitsi-meet on my server with the default configuration. Although the server itself binds to http/https ports and clients can connect to it through their browsers and can exchange XMPP messages, there is no video or audio exchange happening. So I figured out the below warning thrown by Jicofo in the log files.

When I installed jitsi-meet a year or so ago with more or less the same configuration, this was not an issue. So I am wondering what I could be doing wrong or whether it is a bug that needs to be fixed. Any help will be appreciated.

`Jicofo 2018-04-07 15:54:16.764 WARNING: [335] org.jivesoftware.smack.AbstractXMPPConnection.callConnectionClosedOnErrorListener() Connection XMPPTCPConnection[not-authenticated] (0) closed with error
javax.net.ssl.SSLHandshakeException: sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
	at sun.security.ssl.Alerts.getSSLException(Alerts.java:192)
	at sun.security.ssl.SSLSocketImpl.fatal(SSLSocketImpl.java:1964)
	at sun.security.ssl.Handshaker.fatalSE(Handshaker.java:328)
	at sun.security.ssl.Handshaker.fatalSE(Handshaker.java:322)
	at sun.security.ssl.ClientHandshaker.serverCertificate(ClientHandshaker.java:1614)
	at sun.security.ssl.ClientHandshaker.processMessage(ClientHandshaker.java:216)
	at sun.security.ssl.Handshaker.processLoop(Handshaker.java:1052)
	at sun.security.ssl.Handshaker.process_record(Handshaker.java:987)
	at sun.security.ssl.SSLSocketImpl.readRecord(SSLSocketImpl.java:1072)
	at sun.security.ssl.SSLSocketImpl.performInitialHandshake(SSLSocketImpl.java:1385)
	at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:1413)
	at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:1397)
	at org.jivesoftware.smack.tcp.XMPPTCPConnection.proceedTLSReceived(XMPPTCPConnection.java:798)
	at org.jivesoftware.smack.tcp.XMPPTCPConnection.access$1200(XMPPTCPConnection.java:150)
	at org.jivesoftware.smack.tcp.XMPPTCPConnection$PacketReader.parsePackets(XMPPTCPConnection.java:1055)
	at org.jivesoftware.smack.tcp.XMPPTCPConnection$PacketReader.access$300(XMPPTCPConnection.java:982)
	at org.jivesoftware.smack.tcp.XMPPTCPConnection$PacketReader$1.run(XMPPTCPConnection.java:998)
	at java.lang.Thread.run(Thread.java:748)
Caused by: sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
	at sun.security.validator.PKIXValidator.doBuild(PKIXValidator.java:397)
	at sun.security.validator.PKIXValidator.engineValidate(PKIXValidator.java:302)
	at sun.security.validator.Validator.validate(Validator.java:260)
	at sun.security.ssl.X509TrustManagerImpl.validate(X509TrustManagerImpl.java:324)
	at sun.security.ssl.X509TrustManagerImpl.checkTrusted(X509TrustManagerImpl.java:229)
	at sun.security.ssl.X509TrustManagerImpl.checkServerTrusted(X509TrustManagerImpl.java:124)
	at sun.security.ssl.ClientHandshaker.serverCertificate(ClientHandshaker.java:1596)
	... 13 more
Caused by: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
	at sun.security.provider.certpath.SunCertPathBuilder.build(SunCertPathBuilder.java:141)
	at sun.security.provider.certpath.SunCertPathBuilder.engineBuild(SunCertPathBuilder.java:126)
	at java.security.cert.CertPathBuilder.build(CertPathBuilder.java:280)
	at sun.security.validator.PKIXValidator.doBuild(PKIXValidator.java:392)
	... 19 more`

**Comment by damencho** [comment]
No this is not a bug. And this situation should be handled by the installers. So I'm interested, did you touch anything on your configs, how did you upgrade? Wondering why it can break...
So jicofo uses auth.domain prosody virtual host to connect, that host should be using an ssl cert now (check the prosody config, do you have that keys configured for that virtual host). And that cert should be added to the global trusted certs on the machine and that exception should not be an issue.
Will give you more details (what to check) later when I'm not on mobile :)

**Comment by tuncK** [comment]
Thank you for your help. I checked prosody and indeed it was also suffering from that problem. After purging and re-installing prosody, I think the problem is solved, but nore sure.

I did not do anything special to upgrade as far as I am aware. No change in configs. I just removed jitsi-meet and re-installed after a month or so. It continued to work without any apparent problems for a few hours and then I realised that it had stopped working with that error.

**Comment by pinkrickshaw** [comment]
Hello, our server has valid ssl and works with one of our android app greatly but when we clone our app with new package its shows the config not load error please help error shown below
"ReactNativeJS: 'Failed to load config from https://..server_url...../config.js?room=rahul', [TypeError: Network request failed]
07-13 16:26:01.334 3900-3949/com.vc.prd.confab E/unknown:React: console.error: "Failed to load config from https://..server_url...../config.js?room=rahul", {}, stack:
    <unknown>@401:2404
    <unknown>@489:602
    u@211:133
    <unknown>@211:919
    <unknown>@86:966
    callTimer@81:601
    callImmediatesPass@81:1746
    callImmediates@81:1862
    <unknown>@79:2436
    <unknown>@79:106
    value@79:2401
    <unknown>@79:1039
    <unknown>@79:106
    value@79:985
"

help is really appretiated this is android android client error when connect to private server
