### ISSUE TITLE
npm install failed, ubuntu 16.04, node v8.11.1, npm 5.6.0 , how to resove it , or which node version could work?

### ISSUE THREAD

**Issue by mxins** [jitsi/jitsi-meet#2786]
34301 verbose stack Error: git-validate@2.2.2 install: `node bin/install`
34301 verbose stack Exit status 1
34301 verbose stack     at EventEmitter.<anonymous> (/usr/local/lib/node-v8.11.1-linux-x64/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:285:16)
34301 verbose stack     at emitTwo (events.js:126:13)
34301 verbose stack     at EventEmitter.emit (events.js:214:7)
34301 verbose stack     at ChildProcess.<anonymous> (/usr/local/lib/node-v8.11.1-linux-x64/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
34301 verbose stack     at emitTwo (events.js:126:13)
34301 verbose stack     at ChildProcess.emit (events.js:214:7)
34301 verbose stack     at maybeClose (internal/child_process.js:925:16)
34301 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:209:5)
34302 verbose pkgid git-validate@2.2.2
34303 verbose cwd /root/jitsi-meet
34304 verbose Linux 4.4.0-117-generic
34305 verbose argv "/usr/local/lib/node-v8.11.1-linux-x64/bin/node" "/usr/bin/npm" "install"
34306 verbose node v8.11.1
34307 verbose npm  v5.6.0
34308 error code ELIFECYCLE
34309 error errno 1
34310 error git-validate@2.2.2 install: `node bin/install`
34310 error Exit status 1
34311 error Failed at the git-validate@2.2.2 install script.
34311 error This is probably not a problem with npm. There is likely additional logging output above.
34312 verbose exit [ 1, true ]

**Comment by mxins** [comment]
??
