### ISSUE TITLE
build failed, make error

### ISSUE THREAD

**Issue by mxins** [jitsi/jitsi-meet#2792]
ubuntu 16.04

root@xxx:~/jitsi-meet# make
./node_modules/.bin/webpack -p
/root/jitsi-meet/webpack.config.js:198
function devServerProxyBypass({ path }) {
                              ^

SyntaxError: Unexpected token {
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:374:25)
    at Object.Module._extensions..js (module.js:417:10)
    at Module.load (module.js:344:32)
    at Function.Module._load (module.js:301:12)
    at Module.require (module.js:354:17)
    at require (internal/module.js:12:17)
    at requireConfig (/root/jitsi-meet/node_modules/webpack/bin/convert-argv.js:97:18)
    at /root/jitsi-meet/node_modules/webpack/bin/convert-argv.js:104:17
    at Array.forEach (native)
Makefile:16: recipe for target 'compile' failed
make: *** [compile] Error 1

**Comment by damencho** [comment]
What is your node and npm versions? Did you run npm install before that?

**Comment by mxins** [comment]
@damencho [https://github.com/jitsi/jitsi-meet/issues/2786](url) , I try node v8.11.1, npm 5.6.0, npm install failed, which node and npm version could work?

**Comment by damencho** [comment]
Currently, I'm using node v8.9.1 and npm 5.6.0 and it works fine. That is strange. Maybe delete node_module run again npm install and then make, does that make a difference?
