### ISSUE TITLE
Hot to use a subdomain with jitsi?

### ISSUE THREAD

**Issue by tfraley** [jitsi/jitsi-meet#280]
Good day guys, 

I'm a bit confused as to how jitsi uses domains. 

What I would like to do..

I have a domain.net remote
I have a SubDomain  hangout.domain.net to a local server
I have port fowards set up to point to hangout.domain.net
44300 -> 443 & 10000-20000 -> 10000-20000

So outside url would be 

https://hangout.domain.net:44300

========================================

I've tried doing this a few different ways and really not sure where to go at this moment. 

What should hostname during jitsu be set to?
What should be in ubuntu /etc/hosts file?

Or am I trying to do something that is just not possible with jitsi?

**Comment by bgrozev** [comment]
The normal instructions assume that the server has a public IP address and no port forwarding is necessary. It should be possible to run the way you describe, with a couple of additional steps (and note that I might be missing something):

The videobridge needs to know the public address in order to advertise it. Since it doesn't use STUN, you need to do this manually by setting these properties:
org.jitsi.videobridge.NAT_HARVESTER_LOCAL_ADDRESS
org.jitsi.videobridge.NAT_HARVESTER_PUBLIC_ADDRESS

The 'bosh' variable defined in config.js needs to have its port match the one used by the clients, e.g.:
bosh: '//hangout.domain.net:44300/http-bind'

I don't think you need to change the domain anywhere. Just make sure that it resolves to your public address.

**Comment by tfraley** [comment]
@bgrozev 
Thanks for your help. 
I'm a little stumped as to where to manualy add the NET_HARVESTER properties.

**Comment by bgrozev** [comment]
/usr/share/jitsi-videobridge/.sip-communicator/sip-communicator.properties

**Comment by tfraley** [comment]
@bgrozev 

That's where I originally thought.. The files are there, but there is no content in the properties file itself. Is this how it should be ?

**Comment by bgrozev** [comment]
Yes, I think so.

**Comment by tfraley** [comment]
@bgrozev 

Still stumped. 

Ok this is what I did so far.

I edited /etc/nginx/sites-avaliable/hangout.lifewithtech.net.conf
proxy_pass      hangout.lifewithtech.net:44300/http-bind;

I edited /usr/share/jitsi-videobridge/.sip-communicator/sip-communicator.properties
empty file added the following 

org.jitsi.impl.neomedia.transform.srtp.SRTPCryptoContext.checkReplay=false

org.jitsi.videobridge.NAT\_HARVESTER\_LOCAL\_ADDRESS=<192.168.70.89>
org.jitsi.videobridge.NAT\_HARVESTER\_PUBLIC\_ADDRESS=<76.175.28.244>

org.jitsi.videobridge.TCP\_HARVESTER\_PORT=44300
org.jitsi.videobridge.TCP\_HARVESTER\_MAPPED\_PORT=443

============================

So, open chrome on to different machines here and try to connect there still not seeing each other

URL:   https://hangout.lifewithtech.net:44300/


Install was done via the quick install directions working off a fresh install right now with no changes


Thoughts?

**Comment by bgrozev** [comment]
> I edited /etc/nginx/sites-avaliable/hangout.lifewithtech.net.conf
> proxy_pass hangout.lifewithtech.net:44300/http-bind;

You should not change this file. You should edit /etc/jitsi/meet/something.js instead, and change the "bosh" line.

> org.jitsi.videobridge.NAT_HARVESTER_LOCAL_ADDRESS=<192.168.70.89>
> org.jitsi.videobridge.NAT_HARVESTER_PUBLIC_ADDRESS=<76.175.28.244>

The angle brackets are not actually in the file, right?


> org.jitsi.videobridge.TCP_HARVESTER_PORT=44300
> org.jitsi.videobridge.TCP_HARVESTER_MAPPED_PORT=443

This will do no harm, but it will not work either, without a second IP address (although, I believe this might soon change, judging by Lyubo's latest commit).

**Comment by tfraley** [comment]
@bgrozev 
Thank you again for helping me out with all this. 

Made the changes, now getting an error trying to load the webpage "oops something went wrong and we couldn't couldn't the conference"

I did a rollback of the VM (ie back to fresh install)

Then made the following changes/edits as suggested



/etc/jitsi/meet/hangout.homeip.net-config.js
	bosh: '//hangout.lifewithtech.net:44300/http-bind',

/usr/share/jitsi-videobridge/.sip-communicator/sip-communicator.properties
	org.jitsi.impl.neomedia.transform.srtp.SRTPCryptoContext.checkReplay=false
	org.jitsi.videobridge.NAT\_HARVESTER\_LOCAL\_ADDRESS=192.168.70.89
	org.jitsi.videobridge.NAT\_HARVESTER\_PUBLIC\_ADDRESS=76.175.28.244
	org.jitsi.videobridge.TCP\_HARVESTER\_PORT=44300
	org.jitsi.videobridge.TCP\_HARVESTER\_MAPPED\_PORT=443

**Comment by bgrozev** [comment]
Something seems to be wrong with the nginx configuration. It is supposed to proxy requests to "/http-bind" via port 5280, and it doesn't. Check the configuration, you should be able to access this page:
https://hangout.lifewithtech.net:44300/http-bind

and see something like this:
https://meet.jit.si/http-bind

**Comment by tfraley** [comment]
Ok
 It seems to work using internal doamin name but not with outside domain.

Inside:  https://hangout.homeip.net/http-bind
Outside: https://hangout.lifewithtech.net:44300/http-bind

Humm..  both resolve fine 

office:~ thomasfraley$ ping hangout.lifewithtech.net
PING hangout.lifewithtech.net (76.175.28.244): 56 data bytes
64 bytes from 76.175.28.244: icmp_seq=0 ttl=64 time=0.388 ms
[3]+  Stopped                 ping hangout.lifewithtech.net

office:~ thomasfraley$ ping hangout.homeip.net
PING hangout.homeip.net (192.168.70.89): 56 data bytes
64 bytes from 192.168.70.89: icmp_seq=0 ttl=64 time=1.013 ms
[4]+  Stopped                 ping hangout.homeip.net
office:~ thomasfraley$

**Comment by tfraley** [comment]
@bgrozev 
Ok
It seems to work using internal doamin name but not with outside domain.

Inside: https://hangout.homeip.net/http-bind
Outside: https://hangout.lifewithtech.net:44300/http-bind

Humm.. both resolve fine

office:~ thomasfraley$ ping hangout.lifewithtech.net
PING hangout.lifewithtech.net (76.175.28.244): 56 data bytes
64 bytes from 76.175.28.244: icmp_seq=0 ttl=64 time=0.388 ms
[3]+ Stopped ping hangout.lifewithtech.net

office:~ thomasfraley$ ping hangout.homeip.net
PING hangout.homeip.net (192.168.70.89): 56 data bytes
64 bytes from 192.168.70.89: icmp_seq=0 ttl=64 time=1.013 ms
[4]+ Stopped ping hangout.homeip.net
office:~ thomasfraley$

**Comment by bgrozev** [comment]
Do you have the "proxy" configuration for both domains in /etc/nginx/sites-enabled?

**Comment by tfraley** [comment]
Humm, 
So I only have two folders in there   default &  hangout.homeip.net.conf

should I duplicate hangout.homeip.net.conf and rename to hangout.lifewithtech.net.conf 

?

**Comment by tfraley** [comment]
OK, 

I did a apt-get purge jigasi jitsi-meet jicofo jitsi-videobridge 
and apt-get purge nginx 

Then did the quick install again. 

This time during the install when prompted for a host I used hangout.lifeiwthtech.net

Not working for the most part, but getting an 

Error, 
Jitsi Videobridge is currently unavailable. please try again later!

However seems to be working

-----------
https://hangout.lifewithtech.net:44300/

**Comment by xplicit** [comment]
Is there a documentation with complete descriptions of which ports should be forwarded by the NAT? 
Here https://github.com/jitsi/jitsi-meet/blob/master/doc/manual-install.md I see 80 and 5222, but at least 443 should be forrwarded too. Is 5347 (videobridge default) required for forwarding or it's used at the localhost only?

**Comment by xplicit** [comment]
`org.jitsi.videobridge.NAT_HARVESTER_LOCAL_ADDRESS=<Local.IP.Address>` should be an local address of the machine where jitsi-videobridge is installed or internal address of the NAT router?

`/etc/jitsi/videobridge` `JVB_HOSTNAME` setting should be a local address of machine with jitsi-videobridge or public address of the NAT?

**Comment by xplicit** [comment]
I see the same error "Jitsi Videobridge is currently unavailable" and the error in jvb.log

2015-04-07 13:29:35.465 INFO: [27] org.jitsi.videobridge.Videobridge.info() Created conference 8d70852855ac6d3b. The total number of conferences is now 1, channels 0, video streams 0.
2015-04-07 13:29:35.470 INFO: [27] org.jitsi.videobridge.Conference.info() Created content audio of conference 8d70852855ac6d3b. The total number of conferences is now 1, channels 0, video streams 0.
2015-04-07 13:29:35.948 INFO: [27] org.ice4j.ice.harvest.MultiplexingTcpHostHarvester.addLocalAddresses() Not using link-local address /fe80:0:0:0:221:5aff:feac:439c%2 for TCP candidates.
2015-04-07 13:29:35.950 SEVERE: [27] util.UtilActivator.uncaughtException().108 An uncaught exception occurred in thread=Thread[pool-2-thread-5,5,main] and message was: class org.ice4j.socket.DelegatingServerSocketChannel cannot access its superinterface sun.nio.ch.SelChImpl
java.lang.IllegalAccessError: class org.ice4j.socket.DelegatingServerSocketChannel cannot access its superinterface sun.nio.ch.SelChImpl
        at java.lang.ClassLoader.defineClass1(Native Method)
        at java.lang.ClassLoader.defineClass(ClassLoader.java:800)
        at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
        at java.net.URLClassLoader.defineClass(URLClassLoader.java:449)
        at java.net.URLClassLoader.access$100(URLClassLoader.java:71)
        at java.net.URLClassLoader$1.run(URLClassLoader.java:361)
        at java.net.URLClassLoader$1.run(URLClassLoader.java:355)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.net.URLClassLoader.findClass(URLClassLoader.java:354)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:425)
        at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:308)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:358)
        at java.lang.ClassLoader.defineClass1(Native Method)
        at java.lang.ClassLoader.defineClass(ClassLoader.java:800)
        at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
        at java.net.URLClassLoader.defineClass(URLClassLoader.java:449)
        at java.net.URLClassLoader.access$100(URLClassLoader.java:71)
        at java.net.URLClassLoader$1.run(URLClassLoader.java:361)
        at java.net.URLClassLoader$1.run(URLClassLoader.java:355)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.net.URLClassLoader.findClass(URLClassLoader.java:354)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:425)
        at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:308)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:358)
        at org.ice4j.ice.harvest.MultiplexingTcpHostHarvester.init(MultiplexingTcpHostHarvester.java:609)
        at org.ice4j.ice.harvest.MultiplexingTcpHostHarvester.<init>(MultiplexingTcpHostHarvester.java:247)
        at org.ice4j.ice.harvest.MultiplexingTcpHostHarvester.<init>(MultiplexingTcpHostHarvester.java:217)
        at org.ice4j.ice.harvest.MultiplexingTcpHostHarvester.<init>(MultiplexingTcpHostHarvester.java:198)
        at org.jitsi.videobridge.IceUdpTransportManager.initializeStaticHarvesters(IceUdpTransportManager.java:1732)
        at org.jitsi.videobridge.IceUdpTransportManager.appendVideobridgeHarvesters(IceUdpTransportManager.java:455)
        at org.jitsi.videobridge.IceUdpTransportManager.createIceAgent(IceUdpTransportManager.java:763)
        at org.jitsi.videobridge.IceUdpTransportManager.<init>(IceUdpTransportManager.java:335)
        at org.jitsi.videobridge.IceUdpTransportManager.<init>(IceUdpTransportManager.java:303)
        at org.jitsi.videobridge.Conference.getTransportManager(Conference.java:1139)
        at org.jitsi.videobridge.Channel.initialize(Channel.java:528)
        at org.jitsi.videobridge.RtpChannel.initialize(RtpChannel.java:876)
        at org.jitsi.videobridge.Content.createRtpChannel(Content.java:275)
        at org.jitsi.videobridge.Videobridge.handleColibriConferenceIQ(Videobridge.java:733)
        at org.jitsi.videobridge.Videobridge.handleColibriConferenceIQ(Videobridge.java:545)
        at org.jitsi.videobridge.xmpp.ComponentImpl.handleColibriConferenceIQ(ComponentImpl.java:209)
        at org.jitsi.videobridge.xmpp.ComponentImpl.handleIQRequest(ComponentImpl.java:380)
        at org.jitsi.videobridge.xmpp.ComponentImpl.handleIQ(ComponentImpl.java:311)
        at org.jitsi.videobridge.xmpp.ComponentImpl.handleIQ(ComponentImpl.java:263)
        at org.jitsi.videobridge.xmpp.ComponentImpl.handleIQGet(ComponentImpl.java:362)
        at org.xmpp.component.AbstractComponent.processIQRequest(AbstractComponent.java:511)
        at org.xmpp.component.AbstractComponent.processIQ(AbstractComponent.java:289)

**Comment by tfraley** [comment]
The Videobridge error has gone away, I think one of those other 5xxx ports did it. 

I've moved on to trying to get desktop sharing working lol..

thanks...

**Comment by bgrozev** [comment]
@xplicit This is unrelated. Please send a message to one of the mailing lists (e.g. dev@jitsi.org) and include the full logs.

**Comment by xplicit** [comment]
Answers to my questions:

Ports:  TCP: 80,443,5222 UDP: 10000-20000
`org.jitsi.videobridge.NAT_HARVESTER_LOCAL_ADDRESS`: local ip adress of the server, where conference is installed
`JVB_HOSTNAME` name of the conference host. If use IP it's a public ip address

exception trace: this exception occures with build 445 of jistsi-videobridge, I downgraded jitsi-videobridge to build 438 and error has gone.
