### ISSUE TITLE
Failed to send a message over a WebRTC data channel, disabling P2P and forcing H264 codec .

### ISSUE THREAD

**Issue by calamatitech** [jitsi/jitsi-meet#2886]
I deployed my own server using quick install, got and builded the lastest version of jitsi-meet web application, disabled the p2p feature to get control of video quality by hand.
The video conference works great between two Chrome, using the codec VP8.
If I enable the H264 codec, setting disableSimulcast=true, preferH264=true and disableH264=false, every time I try to establish a videoconference between two Chrome, on both workstations I get two blank screens, and a message concerning a netwok connection error.
In jicofo.log no errors, instead in jvb.log there are two message of kind "SEVERE".
JVB 2018-04-27 09:59:56.883 SEVERE: [151] org.jitsi.sctp4j.Sctp.log() Init'ing brian's patched usrsctp
=====>: org_jitsi_sctp4j_Sctp.c calling init
=====>: org_jitsi_sctp4j_Sctp.c about to set SCTP_DEBUG_ALL
=====>: org_jitsi_sctp4j_Sctp.c setting SCTP_DEBUG_ALL

JVB 2018-04-27 10:00:03.570 INFO: [166] org.jitsi.impl.neomedia.rtp.translator.RTCPFeedbackMessageSender.log() Sending a FIR to ssrc=2444735347 remainingRetries=0
JVB 2018-04-27 10:00:03.570 WARNING: [166] org.jitsi.impl.neomedia.rtp.translator.RTCPFeedbackMessageSender.log() Not sending an FIR because the stream RTP manager is null.
JVB 2018-04-27 10:00:05.870 INFO: [78] org.ice4j.ice.harvest.AbstractTcpListener.readFromChannel() Failed to handle TCP socket Socket[addr=/2.38.115.16,port=38662,localport=443]: End of stream!
Sctp send error: : Resource temporarily unavailable
JVB 2018-04-27 10:00:09.560 SEVERE: [151] org.jitsi.videobridge.EndpointMessageTransport.log() Failed to send a message over a WebRTC data channel (endpoint=d3039841): 
java.io.IOException: Failed to send the data at org.jits

If I comment the two directives concerning  H264, leaving disableSimulcaast=true, the videoconference is working fine. Attached jicofo.log and jvb.log
 
[jicofo.log](https://github.com/jitsi/jitsi-meet/files/1954765/jicofo.log)
[jvb.log](https://github.com/jitsi/jitsi-meet/files/1954766/jvb.log)

**Comment by robbmue** [comment]
Hi, did you ever fix this?

**Comment by alexandregaltier** [comment]
Same problem :
`JVB 2020-03-20 09:08:54.565 SEVERE: [45939] org.jitsi.videobridge.EndpointMessageTransport.log() Failed to send a message over a WebRTC data channel (endpoint=33d4f6c4):
java.io.IOException: Failed to send the data
        at org.jitsi.videobridge.WebRtcDataStream.sendString(WebRtcDataStream.java:175)
        at org.jitsi.videobridge.EndpointMessageTransport.sendMessage(EndpointMessageTransport.java:244)
        at org.jitsi.videobridge.EndpointMessageTransport.sendMessage(EndpointMessageTransport.java:221)
        at org.jitsi.videobridge.EndpointMessageTransport.sendMessage(EndpointMessageTransport.java:208)
        at org.jitsi.videobridge.EndpointMessageTransport.sendMessage(EndpointMessageTransport.java:405)
        at org.jitsi.videobridge.Endpoint.sendMessage(Endpoint.java:205)
        at org.jitsi.videobridge.Conference.sendMessage(Conference.java:357)
        at org.jitsi.videobridge.AbstractEndpointMessageTransport.sendMessageToEndpoints(AbstractEndpointMessageTransport.java:226)
        at org.jitsi.videobridge.AbstractEndpointMessageTransport.onClientEndpointMessage(AbstractEndpointMessageTransport.java:210)
        at org.jitsi.videobridge.AbstractEndpointMessageTransport.onJSONData(AbstractEndpointMessageTransport.java:123)
        at org.jitsi.videobridge.AbstractEndpointMessageTransport.onMessage(AbstractEndpointMessageTransport.java:411)
        at org.jitsi.videobridge.EndpointMessageTransport.onStringData(EndpointMessageTransport.java:388)
        at org.jitsi.videobridge.WebRtcDataStream.onStringMsg(WebRtcDataStream.java:140)
        at org.jitsi.videobridge.SctpConnection.processSctpPacket(SctpConnection.java:1006)
        at org.jitsi.videobridge.SctpConnection.lambda$onSctpPacket$2(SctpConnection.java:841)
        at org.jitsi.impl.osgi.framework.AsyncExecutor.runInThread(AsyncExecutor.java:122)
        at org.jitsi.impl.osgi.framework.AsyncExecutor.access$000(AsyncExecutor.java:28)
        at org.jitsi.impl.osgi.framework.AsyncExecutor$1.run(AsyncExecutor.java:231)
`

**Comment by vahem2lu** [comment]
Same error here.

**Comment by codebeginer** [comment]
I also faced this issue, but what I figured is when their is no participants in the conference other then you then this error appears.
