### ISSUE TITLE
Jitsi seems do not work with prosody 0.10

### ISSUE THREAD

**Issue by sileht** [jitsi/jitsi-meet#3052]
Hi, I just install jitsi-meet

I have this backtrace in log when I start a meeting and the meeting room doesn't work (nostream/noaudio/wierd message about room full with only one person)

It occurs only with prosody 0.10, I have downgrade to 0.9 and everything works fine.

(I use debian strech and stable repo, prosody 0.10 camefrom stretch-backports)

```
Jicofo 2018-05-26 11:55:11.302 SEVERE: [71] org.jitsi.jicofo.xmpp.FocusComponent.handleIQSetImpl().325 java.lang.IllegalArgumentException: The Resourcepart must not be null
java.lang.IllegalArgumentException: The Resourcepart must not be null
        at org.jxmpp.jid.impl.AbstractJid.requireNonNull(AbstractJid.java:243)
        at org.jxmpp.jid.impl.LocalDomainAndResourcepartJid.<init>(LocalDomainAndResourcepartJid.java:49)
        at org.jxmpp.jid.impl.JidCreate.fullFrom(JidCreate.java:335)
        at org.jivesoftware.smackx.muc.MultiUserChat.leave(MultiUserChat.java:741)
        at org.jitsi.impl.protocol.xmpp.ChatRoomImpl.leave(ChatRoomImpl.java:332)
        at org.jitsi.jicofo.JitsiMeetConferenceImpl.leaveTheRoom(JitsiMeetConferenceImpl.java:483)
        at org.jitsi.jicofo.JitsiMeetConferenceImpl.stop(JitsiMeetConferenceImpl.java:412)
        at org.jitsi.jicofo.JitsiMeetConferenceImpl.start(JitsiMeetConferenceImpl.java:369)
        at org.jitsi.jicofo.FocusManager.conferenceRequest(FocusManager.java:371)
        at org.jitsi.jicofo.FocusManager.conferenceRequest(FocusManager.java:320)
        at org.jitsi.jicofo.xmpp.FocusComponent.handleConferenceIq(FocusComponent.java:422)
        at org.jitsi.jicofo.xmpp.FocusComponent.handleIQSetImpl(FocusComponent.java:260)
        at org.jitsi.xmpp.component.ComponentBase.handleIQSet(ComponentBase.java:362)
        at org.xmpp.component.AbstractComponent.processIQRequest(AbstractComponent.java:515)
        at org.xmpp.component.AbstractComponent.processIQ(AbstractComponent.java:289)
        at org.xmpp.component.AbstractComponent.processQueuedPacket(AbstractComponent.java:239)
        at org.xmpp.component.AbstractComponent.access$100(AbstractComponent.java:81)
        at org.xmpp.component.AbstractComponent$PacketProcessor.run(AbstractComponent.java:1051)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)

```

Cheers,

**Comment by damencho** [comment]
I just tested it and the problem is that prosody 0.10 fails to load the muc component with the default prosody config we provide. 
https://github.com/jitsi/jitsi-meet/blob/master/doc/debian/jitsi-meet-prosody/prosody.cfg.lua-jvb.example#L29
If you change it to be `storage = "none"` it works. 
Not sure why storage null is missing as it is mentioned here: https://prosody.im/doc/storage.html
It works with prosody-trunk.
