### ISSUE TITLE
Client disconnected: ssl handshake failed

### ISSUE THREAD

**Issue by Sx3** [jitsi/jitsi-meet#3082]
I have installed jitsi meet latest stable on ubuntu 14.04 on Aws EC2
I can see myself in the screen but not the other participant audio or video is coming.
and I can see his audio and video is muted...same from his side too.

in the prosody.log I can see the error 

Jun 02 08:48:30 c2s28df6a0	info	Client connected
Jun 02 08:48:30 c2s28df6a0	info	Client disconnected: ssl handshake failed**

I have followed the Quik Install method.
Did anyone know a clue ?

**Comment by Sx3** [comment]
Jicofo 2018-06-02 09:01:02.257 WARNING: [603] org.jivesoftware.smack.AbstractXMPPConnection.callConnectionClosedOnErrorListener() Connection XMPPTCPConnection[not-authenticated] (0) closed with error
javax.net.ssl.SSLHandshakeException: sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
	at sun.security.ssl.Alerts.getSSLException(Alerts.java:192)
	at sun.security.ssl.SSLSocketImpl.fatal(SSLSocketImpl.java:1964)
	at sun.security.ssl.Handshaker.fatalSE(Handshaker.java:328)
	at sun.security.ssl.Handshaker.fatalSE(Handshaker.java:322)
	at sun.security.ssl.ClientHandshaker.serverCertificate(ClientHandshaker.java:1614)
	at sun.security.ssl.ClientHandshaker.processMessage(ClientHandshaker.java:216)
	at sun.security.ssl.Handshaker.processLoop(Handshaker.java:1052)
	at sun.security.ssl.Handshaker.process_record(Handshaker.java:987)
	at sun.security.ssl.SSLSocketImpl.readRecord(SSLSocketImpl.java:1072)
	at sun.security.ssl.SSLSocketImpl.performInitialHandshake(SSLSocketImpl.java:1385)
	at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:1413)
	at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:1397)
	at org.jivesoftware.smack.tcp.XMPPTCPConnection.proceedTLSReceived(XMPPTCPConnection.java:798)
	at org.jivesoftware.smack.tcp.XMPPTCPConnection.access$1200(XMPPTCPConnection.java:150)
	at org.jivesoftware.smack.tcp.XMPPTCPConnection$PacketReader.parsePackets(XMPPTCPConnection.java:1055)
	at org.jivesoftware.smack.tcp.XMPPTCPConnection$PacketReader.access$300(XMPPTCPConnection.java:982)
	at org.jivesoftware.smack.tcp.XMPPTCPConnection$PacketReader$1.run(XMPPTCPConnection.java:998)
	at java.lang.Thread.run(Thread.java:748)
Caused by: sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
	at sun.security.validator.PKIXValidator.doBuild(PKIXValidator.java:397)
	at sun.security.validator.PKIXValidator.engineValidate(PKIXValidator.java:302)
	at sun.security.validator.Validator.validate(Validator.java:260)
	at sun.security.ssl.X509TrustManagerImpl.validate(X509TrustManagerImpl.java:324)
	at sun.security.ssl.X509TrustManagerImpl.checkTrusted(X509TrustManagerImpl.java:229)
	at sun.security.ssl.X509TrustManagerImpl.checkServerTrusted(X509TrustManagerImpl.java:124)
	at sun.security.ssl.ClientHandshaker.serverCertificate(ClientHandshaker.java:1596)
	... 13 more
Caused by: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
	at sun.security.provider.certpath.SunCertPathBuilder.build(SunCertPathBuilder.java:141)
	at sun.security.provider.certpath.SunCertPathBuilder.engineBuild(SunCertPathBuilder.java:126)
	at java.security.cert.CertPathBuilder.build(CertPathBuilder.java:280)
	at sun.security.validator.PKIXValidator.doBuild(PKIXValidator.java:392)
	... 19 more

**Comment by damencho** [comment]
Can you check [this](https://github.com/jitsi/jitsi-meet/issues/3011#issuecomment-391107981), does any of those solve your problem?

**Comment by Sx3** [comment]
I have tried but no luck.
prosody show the below error when I start a video conference .the video came for few seconds and then stops.

Jun 04 06:47:33 general	info	Hello and welcome to Prosody version 0.9.1
Jun 04 06:47:33 general	info	Prosody is using the select backend for connection handling
Jun 04 06:47:33 portmanager	info	Activated service 'http' on [::]:5280, [*]:5280
Jun 04 06:47:33 portmanager	info	Activated service 'https' on [::]:5281, [*]:5281
Jun 04 06:47:33 portmanager	info	Activated service 'c2s' on [::]:5222, [*]:5222
Jun 04 06:47:33 portmanager	info	Activated service 'legacy_ssl' on no ports
Jun 04 06:47:33 portmanager	info	Activated service 's2s' on [::]:5269, [*]:5269
Jun 04 06:47:33 mod_posix	info	Prosody is about to detach from the console, disabling further console output
Jun 04 06:47:33 mod_posix	info	Successfully daemonized to PID 1662
Jun 04 06:47:33 portmanager	info	Activated service 'component' on [127.0.0.1]:5347, [::1]:5347
Jun 04 06:48:17 mod_bosh	info	New BOSH session, assigned it sid 'c348fbb4-4eb8-4f60-b1a2-480b15d4501e'
Jun 04 06:48:17 boshc348fbb4-4eb8-4f60-b1a2-480b15d4501e	info	Authenticated as 9f60e0e3-861d-45e3-8c5f-d387e384f271@connect.quikbox.com
Jun 04 06:48:19 focus.connect.quikbox.com:component	warn	Component not connected, bouncing error for: <iq id='43997c30-df38-4cbb-a667-2cfc6d18aaea:sendIQ' type='set' to='focus.connect.quikbox.com' from='9f60e0e3-861d-45e3-8c5f-d387e384f271@connect.quikbox.com/ae496adb-532b-4816-8219-fcd53c6bf517'>
Jun 04 06:48:20 focus.connect.quikbox.com:component	warn	Component not connected, bouncing error for: <iq id='14994c7a-cd39-4ccb-a15a-c24e486b3c38:sendIQ' type='set' to='focus.connect.quikbox.com' from='9f60e0e3-861d-45e3-8c5f-d387e384f271@connect.quikbox.com/ae496adb-532b-4816-8219-fcd53c6bf517'>

**Comment by damencho** [comment]
Is jicofo running at all?

**Comment by Sx3** [comment]
Prosody is running with PID 2079
yeah

**Comment by damencho** [comment]
is jicofo running? check its log file on startup for errors.

**Comment by Sx3** [comment]
in the path /var/log/jitsi
jicofo.log and jvb.log has nothing on them

**Comment by damencho** [comment]
ok, so maybe jicofo is not running. Do you see anything in the log file if you do /etc/init.d/jicofo restart?

**Comment by Sx3** [comment]
sudo service jicofo restart 
 /etc/init.d/jicofo restart 

both are not working 
/etc/init.d/jicofo: No such file or directory

**Comment by damencho** [comment]
Seems you don't have jicofo installed ... Did you already followed the https://github.com/jitsi/jitsi-meet/blob/master/doc/quick-install.md?

**Comment by Sx3** [comment]
I have already followed it and did several AWS EC2 instances..but no luck.

**Comment by damencho** [comment]
Is there a folder /usr/share/jicofo ?

**Comment by Sx3** [comment]
![image](https://user-images.githubusercontent.com/3599933/40933659-c4077a72-684f-11e8-93d8-0d6a9aa60fb7.png)

**Comment by damencho** [comment]
I have no idea, seems someone deleted whatever was installed there.

**Comment by Sx3** [comment]
Okay I will post the error of the fresh one ..going to install another instance now.

**Comment by Sx3** [comment]
[jicofo.log](https://github.com/jitsi/jitsi-meet/files/2069518/jicofo.log)
[jvb.log](https://github.com/jitsi/jitsi-meet/files/2069519/jvb.log)
[prosody.err.log](https://github.com/jitsi/jitsi-meet/files/2069521/prosody.err.log) - **edited the file name**
[prosody.log](https://github.com/jitsi/jitsi-meet/files/2069520/prosody.log)

Above are the logs I have for the fresh install.

**Comment by damencho** [comment]
You are using oracle java, is there a reason to not stick to default openjdk?

To make it work with oracle java, you can try to add to /etc/jitsi/jicofo/sip-communicator.properties
org.jitsi.jicofo.ALWAYS_TRUST_MODE_ENABLED=true
and restart jicofo.

**Comment by Sx3** [comment]
Yes I am using Oracle Java.also I have tried with openjdk too here are the logs when I use the openjdk
Okay I have installed openjdk now.

So currently I have.
AWS EC2 Ubuntu Server 14.04.5 LTS
Nginx v1.4.6
Openjdk 1.8.0_171

[prosody.log](https://github.com/jitsi/jitsi-meet/files/2071348/prosody.log)
[jicofo.log](https://github.com/jitsi/jitsi-meet/files/2071349/jicofo.log)
[jvb.log](https://github.com/jitsi/jitsi-meet/files/2071350/jvb.log)
[prosody.err.log](https://github.com/jitsi/jitsi-meet/files/2071352/prosody.err.log)

**Comment by Sx3** [comment]
yes I tried after adding
org.jitsi.jicofo.ALWAYS_TRUST_MODE_ENABLED=true
and restarting ...but same issue..

Now I have uninstalled oraclejdk and installed openjdk.
So I currently have..

Ubuntu 14.04.5 LTS on AWS EC2
Nginx v/1.4.6
OpenJDK 1.8.0_171

And followed the Quick Install method.Here are the log files.

[prosody.err.log](https://github.com/jitsi/jitsi-meet/files/2071376/prosody.err.log)
[prosody.log](https://github.com/jitsi/jitsi-meet/files/2071377/prosody.log)
[jicofo.log](https://github.com/jitsi/jitsi-meet/files/2071378/jicofo.log)
[jvb.log](https://github.com/jitsi/jitsi-meet/files/2071379/jvb.log)

What are the configurations of the server https://meet.jit.si/ is on ?

**Comment by Sx3** [comment]
yeah.I have opened the ports on AWS too. Thanks

**Comment by kutovoy** [comment]
I fixed such error by adding self signed ssl certificate to /etc/ssl/certs/java/cacerts file using the following cli command: 

keytool -import -alias jitsi_server_cert -keystore cacerts -file meet.yourdomain.crt

default password for cacerts on Ubuntu is changeit

may be this will help someone
