### ISSUE TITLE
Audio/Video missing after page reload in non-anonymous XMPP sessions

### ISSUE THREAD

**Issue by matthias-w** [jitsi/jitsi-meet#318]
I hosted the system on my local machine (Ubuntu 14.04, Nginx, Openfire) and try to use it in an existing web portal providing user credentials on video conference startup (extended app.bundle.js's XMPP.start merthod for that)

That works when setting up an initial conference with two participants. But as soon as a participant reloads or closes the browser window and restarts the conference (with the same credentials), the audio/video from his system is not shown on the opposite side, though the user is shown in the contact list.

Any idea what could  cause this issue?

Here are the browser logs from remote side where the audio/video is missing:

app.bundle.js:9570 stream ended MediaStream {}
app.bundle.js:9512 Remove whole user participant_john
app.bundle.js:10262 Last visible video no longer exists
app.bundle.js:10268 Fallback to local video...
app.bundle.js:8929 hover in msmith, video:  LocalVideo {videoSpanId: "localVideoContainer", container: span#localVideoContainer.videocontainer, VideoLayout: Object, flipX: true, peerJid: "35@conference.mydomain.com/msmith"…}
app.bundle.js:575 selected endpoint changed:  msmith
app.bundle.js:579 sending selected endpoint changed notification to the bridge:  msmith
app.bundle.js:14799 new ssrcs [Object, Object]
app.bundle.js:14366 modify sources done
app.bundle.js:14369 SDPs SDP {media: Array[3], session: "v=0
↵o=- 419517761181253285 3 IN IP4 127.0.0.1
↵s=…244e7a19d1 8d88e05e-96aa-4a08-978e-e84e306b2c00
↵", raw: "v=0
↵o=- 419517761181253285 3 IN IP4 127.0.0.1
↵s=…id:data
↵a=sctpmap:5000 webrtc-datachannel 1024
↵"} SDP {media: Array[3], session: "v=0
↵o=- 419517761181253285 4 IN IP4 127.0.0.1
↵s=…244e7a19d1 8d88e05e-96aa-4a08-978e-e84e306b2c00
↵", raw: "v=0
↵o=- 419517761181253285 4 IN IP4 127.0.0.1
↵s=…id:data
↵a=sctpmap:5000 webrtc-datachannel 1024
↵"}
app.bundle.js:14562 removal not necessary
app.bundle.js:14589 addition not necessary
app.bundle.js:9968 UI enable dominant speaker john john false
app.bundle.js:9968 UI enable dominant speaker Michael Smith (<span data-i18n="me">me</span>) msmith true
app.bundle.js:17470 entered 35@conference.mydomain.com/john Object {show: "", status: "", affiliation: "none", role: "participant", jid: "john@mydomain.com/1de694f4"…}
app.bundle.js:18492 Strophe: error: Cannot read property 'appendChild' of undefined
TypeError: Cannot read property 'appendChild' of undefined
    at RemoteVideo.setDisplayName (https://mydomain.com/conference/libs/app.bundle.js:9726:49)
    at Object.my.onDisplayNameChanged (https://mydomain.com/conference/libs/app.bundle.js:10678:75)
    at EventEmitter.onDisplayNameChanged (https://mydomain.com/conference/libs/app.bundle.js:3375:29)
    at EventEmitter.emit (https://mydomain.com/conference/libs/app.bundle.js:31529:33)
    at Object.Strophe.addConnectionPlugin.parsePresence (https://mydomain.com/conference/libs/app.bundle.js:17909:42)
    at Object.Strophe.addConnectionPlugin.onPresence (https://mydomain.com/conference/libs/app.bundle.js:17495:30)
    at Object.Strophe.Handler.run (https://mydomain.com/conference/libs/strophe/strophe.min.js:1:19636)
    at https://mydomain.com/conference/libs/strophe/strophe.min.js:1:27678
    at Object.Strophe.forEachChild (https://mydomain.com/conference/libs/strophe/strophe.min.js:1:10525)
    at Object.Strophe.Connection._dataRecv (https://mydomain.com/conference/libs/strophe/strophe.min.js:1:27466)Strophe.log @ app.bundle.js:18492Strophe.fatal @ strophe.min.js:1Strophe.Handler.run @ strophe.min.js:1(anonymous function) @ strophe.min.js:1Strophe.forEachChild @ strophe.min.js:1Strophe.Connection._dataRecv @ strophe.min.js:1Strophe.Bosh._onRequestStateChange @ strophe.min.js:1
app.bundle.js:18488 Strophe: Removing Strophe handlers due to uncaught exception: Cannot read property 'appendChild' of undefined
app.bundle.js:18007 on jingle source-add from 35@conference.mydomain.com/focus <iq xmlns=​"jabber:​client" id=​"tXY5H-2233" to=​"msmith@mydomain.com/​45d77251" from=​"35@conference.mydomain.com/​focus" type=​"set">​…​</iq>​
app.bundle.js:14243 addssrc 1436961146868
app.bundle.js:14244 ice connected
app.bundle.js:13491 REMOTE STREAM ADDED: [object MediaStream] - d5f04380-5335-4933-8621-ed7570a0f206
app.bundle.js:14880 associated jid 35@conference.mydomain.com/john 4100976476 null
app.bundle.js:9604 Uncaught TypeError: Cannot set property 'onclick' of undefinedRemoteVideo.addRemoteStreamElement @ app.bundle.js:9604my.onRemoteStreamAdded @ app.bundle.js:10304(anonymous function) @ app.bundle.js:3383EventEmitter.emit @ app.bundle.js:31526RTC.createRemoteStream @ app.bundle.js:889JingleSession.remoteStreamAdded @ app.bundle.js:14885peerconnection.onaddstream @ app.bundle.js:13492TraceablePeerConnection.peerconnection.onaddstream @ app.bundle.js:16251
app.bundle.js:13491 REMOTE STREAM ADDED: [object MediaStream] - 1adee03e-088c-4f24-a781-5cdf8e3b39c7
app.bundle.js:14880 associated jid 35@conference.mydomain.com/john 290188577 camera
app.bundle.js:9604 Uncaught TypeError: Cannot set property 'onclick' of undefinedRemoteVideo.addRemoteStreamElement @ app.bundle.js:9604my.onRemoteStreamAdded @ app.bundle.js:10304(anonymous function) @ app.bundle.js:3383EventEmitter.emit @ app.bundle.js:31526RTC.createRemoteStream @ app.bundle.js:889JingleSession.remoteStreamAdded @ app.bundle.js:14885peerconnection.onaddstream @ app.bundle.js:13492TraceablePeerConnection.peerconnection.onaddstream @ app.bundle.js:16251
app.bundle.js:14799 new ssrcs [Object, Object]
app.bundle.js:14297 modify sources done

**Comment by yanas** [comment]
Question moved to our dev mailing list here: http://lists.jitsi.org/pipermail/dev/2015-July/024680.html. We’re trying to keep all questions and discussions on the mailing list and only create issues for well identified problems. Please reopen with additional information after discussing it with a developer. Thanks!
