### ISSUE TITLE
Android application crashes and JITSI MEET external API

### ISSUE THREAD

**Issue by naveenpatidar** [jitsi/jitsi-meet#3200]
1. When I press the home button in an Android smartphone while video chat it gets crashed with the following error. 

**_java.lang.AssertionError
        at com.facebook.infer.annotation.Assertions.assertNotNull(Assertions.java:28)
        at com.facebook.react.ReactInstanceManager.onHostPause(ReactInstanceManager.java:567)
        at org.jitsi.meet.sdk.JitsiMeetView.onHostPause(JitsiMeetView.java:143)
        at evalvenow.pulse.MainActivity.onStop(MainActivity.java:139)_**

2. I need to customize parameters which are set by default in Jitsi Android SDK.
   e.g. Display name, FPS, frame size and so on which I can set in external meet API.

3.  I want to trigger the chat send button in external meet API from the different division in which iframe is not loaded. When I tried it results in the following error.

_**Uncaught DOMException: Blocked a frame with origin "http://localhost:4000" from accessing a cross-origin frame.
    at HTMLTextAreaElement.<anonymous> (http://localhost:4000/jitsi_video:48:93)**_

**Comment by lyubomir** [comment]
Could you please split the 3 subjects that you're talking about here into 3 different issues each with its own single subject?

**Comment by PaijoRX** [comment]
Hi, today I got this error:

```
java.lang.AssertionError
at com.facebook.infer.annotation.Assertions.assertNotNull(Assertions.java:28)
at com.facebook.react.ReactInstanceManager.onHostPause(ReactInstanceManager.java:567)
at org.jitsi.meet.sdk.JitsiMeetView.onHostPause(JitsiMeetView.java:143)
at evalvenow.pulse.MainActivity.onStop(MainActivity.java:139)
```

on function:

```
    @Override
    protected void onStop() {
        super.onStop();

       JitsiMeetView.onHostPause(this);
    }
```

My temporary solution is by comment this line JitsiMeetView.onHostPause(this);
