### ISSUE TITLE
When use quick install

### ISSUE THREAD

**Issue by WildDylan** [jitsi/jitsi-meet#3258]
```shell
Creating virtual environment...
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/virtualenv.py", line 2363, in <module>
    main()
  File "/usr/lib/python3/dist-packages/virtualenv.py", line 719, in main
    symlink=options.symlink)
  File "/usr/lib/python3/dist-packages/virtualenv.py", line 988, in create_environment
    download=download,
  File "/usr/lib/python3/dist-packages/virtualenv.py", line 918, in install_wheel
    call_subprocess(cmd, show_stdout=False, extra_env=env, stdin=SCRIPT)
  File "/usr/lib/python3/dist-packages/virtualenv.py", line 812, in call_subprocess
    % (cmd_desc, proc.returncode))
OSError: Command /opt/eff.org/certbot/venv/bin/python2.7 - setuptools pkg_resources pip wheel failed with error code 1
```

**Comment by damencho** [comment]
This is part of the let's encrypt script. You can search for more information at https://github.com/certbot/certbot

What is the OS and version you use?

Please in the future when you have questions or problems, before opening an issue, discuss them first on the community forum: https://community.jitsi.org as stated in the issues template, thank you.

**Comment by WildDylan** [comment]
Okey, fixed by apt-get install letsencrypt
