### ISSUE TITLE
[Android] Audio and Video Not Woking but View Loads

### ISSUE THREAD

**Issue by oschwartz10612** [jitsi/jitsi-meet#3353]
I am using the Andriod SDK in my app. 

I have a button that loads a meet view. Everything loads fine and connects, but the video and audio dont work. Pressing the onscreen buttons to enable them does nothing.

I had to disable libgnustl_shared.so because I was getting the 32/64bit error. Could this have something to do with it?

Any fixes?

Thanks,
Owen

**Comment by saghul** [comment]
> I had to disable libgnustl_shared.so because I was getting the 32/64bit error. Could this have something to do with it?

What problem were you getting exactly? Note that the SDK is built with React Native, which does not support 64bit builds as of yet.

**Comment by oschwartz10612** [comment]
Thank you for the reply! :}

I was getting this error: 
`java.lang.UnsatisfiedLinkError: dlopen failed: "/data/data/net.robotworksacademy.medicalauthentication/lib-main/libgnustl_shared.so" is 32-bit instead of 64-bit
                      at java.lang.Runtime.load0(Runtime.java:928)
                      at java.lang.System.load(System.java:1633)
                      at com.facebook.soloader.DirectorySoSource.loadLibraryFrom(DirectorySoSource.java:71)
                      at com.facebook.soloader.DirectorySoSource.loadLibrary(DirectorySoSource.java:42)
                      at com.facebook.soloader.SoLoader.loadLibraryBySoName(SoLoader.java:299)
                      at com.facebook.soloader.DirectorySoSource.loadLibraryFrom(DirectorySoSource.java:65)
                      at com.facebook.soloader.DirectorySoSource.loadLibrary(DirectorySoSource.java:42)
                      at com.facebook.soloader.SoLoader.loadLibraryBySoName(SoLoader.java:299)
                      at com.facebook.soloader.DirectorySoSource.loadLibraryFrom(DirectorySoSource.java:65)
                      at com.facebook.soloader.DirectorySoSource.loadLibrary(DirectorySoSource.java:42)
                      at com.facebook.soloader.SoLoader.loadLibraryBySoName(SoLoader.java:299)
                      at com.facebook.soloader.DirectorySoSource.loadLibraryFrom(DirectorySoSource.java:65)
                      at com.facebook.soloader.DirectorySoSource.loadLibrary(DirectorySoSource.java:42)
                      at com.facebook.soloader.SoLoader.loadLibraryBySoName(SoLoader.java:299)
                      at com.facebook.soloader.SoLoader.loadLibrary(SoLoader.java:247)
                      at com.facebook.react.bridge.ReactBridge.staticInit(ReactBridge.java:20)
                      at com.facebook.react.bridge.NativeMap.<clinit>(NativeMap.java:21)
                      at com.facebook.react.bridge.JSCJavaScriptExecutorFactory.create(JSCJavaScriptExecutorFactory.java:23)
                      at com.facebook.react.ReactInstanceManager$4.run(ReactInstanceManager.java:928)
                      at java.lang.Thread.run(Thread.java:764)`

I am developing in SDK 28 on a Pixel XL. I read online and here that the only real sulution for now was to disable all 64 bit files.

**Comment by saghul** [comment]
Are you building your app in 32 or 64 bit mode?

**Comment by oschwartz10612** [comment]
I was unaware that was an option. I would assume 64, but I am not sure. How would I go about changing it? I am relatively new to Andriod.

**Comment by saghul** [comment]
In your `app/build.gradle` file, add a section like this one: https://github.com/jitsi/jitsi-meet/blob/master/android/app/build.gradle#L18

**Comment by oschwartz10612** [comment]
Thank you! That worked, but the audio and video still will not work at all.

**Comment by saghul** [comment]
Do you see any logs at all? how are you loading a URL?

**Comment by oschwartz10612** [comment]
Unfortunately, I had to go to work. I will get you a log this afternoon, but I am aware that it will be the middle of the night for you. ;)

I am loading the URL with loadUrlString. I tried using the object and passing false to both mutes, but that didn't work.

**Comment by oschwartz10612** [comment]
I also tried to add the permissions to the manifest file for the camera and mic, but that didn't help either...

**Comment by oschwartz10612** [comment]
When I press the button for video I get
`08-08 15:31:32.708 4450-4522/net.robotworksacademy.medicalauthentication W/ReactNativeJS: '[modules/statistics/AnalyticsAdapter.js]', '<n>: ', 'Not sending an event, disposed.'`

A text file is attached with the full log.
[log.txt](https://github.com/jitsi/jitsi-meet/files/2271698/log.txt)

**Comment by oschwartz10612** [comment]
Do you need anything else?

**Comment by saghul** [comment]
Hey Owen, I had a look at the logs but I don't see anything that would explain why you get no camera access :-/

How does you manifest look like?

**Comment by oschwartz10612** [comment]
`<?xml version="1.0" encoding="utf-8"?>
<manifest xmlns:android="http://schemas.android.com/apk/res/android"
    package="net.robotworksacademy.medicalauthentication">

    <application
        android:allowBackup="true"
        android:icon="@mipmap/ic_launcher"
        android:label="@string/app_name"
        android:roundIcon="@mipmap/ic_launcher_round"
        android:supportsRtl="true"
        android:theme="@style/AppTheme">
        <activity android:name=".NotificationPannel">
            <intent-filter>
                <action android:name="android.intent.action.MAIN" />

                <category android:name="android.intent.category.LAUNCHER" />
            </intent-filter>
        </activity>
        <service android:name="org.eclipse.paho.android.service.MqttService" >
        </service>
        <service
            android:name=".MessageService"
            android:exported="false" />
    </application>



    <uses-permission android:name="android.permission.WAKE_LOCK" />
    <uses-permission android:name="android.permission.INTERNET" />
    <uses-permission android:name="android.permission.ACCESS_NETWORK_STATE" />
    <uses-permission android:name="android.permission.READ_PHONE_STATE" />
    <uses-permission android:name="android.permission.PROCESS_OUTGOING_CALLS" />
    <uses-permission android:name="android.permission.PROCESS_OUTGOING_CALLS" />


</manifest>`

**Comment by saghul** [comment]
You need the camera permission listed there, even in Android >= M.

**Comment by oschwartz10612** [comment]
I had the camera permission in there previously, but didn't work. Maybe it was the wrong one? What should it look like? Do I need one for the mic as well?

**Comment by oschwartz10612** [comment]
So I updated my manifest, but it didn't work. I found one of your files and used it as an example. It looks like this now:

`<?xml version="1.0" encoding="utf-8"?>
<manifest xmlns:android="http://schemas.android.com/apk/res/android"
    package="net.robotworksacademy.medicalauthentication">

    <uses-permission android:name="android.permission.WAKE_LOCK" />
    <uses-permission android:name="android.permission.INTERNET" />
    <uses-permission android:name="android.permission.ACCESS_NETWORK_STATE" />
    <uses-permission android:name="android.permission.READ_PHONE_STATE" />
    <uses-permission android:name="android.permission.PROCESS_OUTGOING_CALLS" />
    <uses-permission android:name="android.permission.PROCESS_OUTGOING_CALLS" />
    <uses-permission android:name="android.permission.BLUETOOTH" />
    <uses-permission android:name="android.permission.CAMERA" />
    <uses-permission android:name="android.permission.MODIFY_AUDIO_SETTINGS" />
    <uses-permission android:name="android.permission.RECORD_AUDIO" />
    <uses-permission android:name="android.permission.SYSTEM_ALERT_WINDOW" />
    <uses-permission android:name="android.permission.ACCESS_WIFI_STATE" />
    <uses-permission android:name="android.permission.WRITE_EXTERNAL_STORAGE"/>

    <uses-feature android:name="android.hardware.camera" />
    <uses-feature android:name="android.hardware.camera.autofocus" />
    <uses-feature android:glEsVersion="0x00020000" android:required="true"></uses-feature>

    <application
        android:allowBackup="true"
        android:icon="@mipmap/ic_launcher"
        android:label="@string/app_name"
        android:roundIcon="@mipmap/ic_launcher_round"
        android:supportsRtl="true"
        android:theme="@style/AppTheme">
        <activity android:name=".NotificationPannel">
            <intent-filter>
                <action android:name="android.intent.action.MAIN" />

                <category android:name="android.intent.category.LAUNCHER" />
            </intent-filter>
        </activity>
        <service android:name="org.eclipse.paho.android.service.MqttService" >
        </service>
        <service
            android:name=".MessageService"
            android:exported="false" />
    </application>
</manifest>`

Thank your for all of your help!

**Comment by saghul** [comment]
@oschwartz10612 Out of curiosity, how did you solve it? Sorry I couldn't be of more help.

**Comment by oschwartz10612** [comment]
I didn't, I just found another solution to my initial problem.

No problem, you were plenty of help! Thank you again!

**Comment by FaizalMalik** [comment]
@oschwartz10612  - Could you please tell me how did you fix the issue ? I am also facing the same issue.. Video consulting room is appearing and connecting .. but the video and audio is muted initally and i can't unmute ?

 ```
 Bundle config = new Bundle();
        config.putBoolean("startWithAudioMuted", false);
        config.putBoolean("startWithVideoMuted", false);
        Bundle urlObject = new Bundle();
        urlObject.putBundle("config", config);
        urlObject.putString("url", "https://jitsi_url");


        view.loadURLObject(urlObject);

/// tried both method

  view.loadURLString("https://jitsi_url");

```



My Manifest file. -- 
```

<manifest xmlns:android="http://schemas.android.com/apk/res/android"
    package="com.quikdr.app">

    <uses-permission android:name="android.permission.INTERNET" />
    <uses-permission android:name="android.permission.RECEIVE_SMS"/>
    <uses-permission android:name="android.permission.READ_EXTERNAL_STORAGE" />
    <uses-permission android:name="android.permission.WRITE_EXTERNAL_STORAGE" />
    <uses-permission android:name="android.permission.CAMERA" />
    <uses-feature android:name="android.hardware.camera" />
    <uses-feature android:name="android.hardware.camera.autofocus" />
```

**Comment by oschwartz10612** [comment]
I never solved the issue. I was still getting what you were getting. I ended up using another service and just having the app open it in the browser. 

It was just a prototype, so it didn't need to be perfect.

**Comment by FaizalMalik** [comment]
@oschwartz10612  - I used this and solved my issue - not sure why thier request permission call back not working automatically. So i manually added and working fine :)
```

@TargetApi(Build.VERSION_CODES.M)                                                                                          
 @Override                                                                                                                  
 public void requestPermissions(String[] permissions, int requestCode, PermissionListener listener) {                       
                                                                                                                            
     String[] PERMISSIONS = {                                                                                               
             Manifest.permission.RECORD_AUDIO,                                                                              
             android.Manifest.permission.CAMERA                                                                             
     };                                                                                                                     
                                                                                                                            
       this.requestPermissions(permissions,requestCode);                                                                    
                                                                                                                            
     if(!hasPermissions( PERMISSIONS)){                                                                                     
         ActivityCompat.requestPermissions(this, PERMISSIONS, PERMISSION_ALL);                                              
     }                                                                                                                      
                                                                                                                            
 }                                                                                                                          
 public boolean hasPermissions(String... permissions) {                                                                     
     if ( permissions != null) {                                                                                            
         for (String permission : permissions) {                                                                            
             if (ActivityCompat.checkSelfPermission(this, permission) != PackageManager.PERMISSION_GRANTED) {               
                 return false;                                                                                              
             }                                                                                                              
         }                                                                                                                  
     }                                                                                                                      
     return true;                                                                                                           
 }         
```

**Comment by oschwartz10612** [comment]
Great! Thanks for the update. I wish I knew this 4 months ago! I apologize I wasn't much help.

**Comment by ErsinDemirbas** [comment]
> @oschwartz10612 - I used this and solved my issue - not sure why thier request permission call back not working automatically. So i manually added and working fine :) (note: Need to call load url method on permission grand call back)
> 
> ```
> 
> @TargetApi(Build.VERSION_CODES.M)                                                                                          
>  @Override                                                                                                                  
>  public void requestPermissions(String[] permissions, int requestCode, PermissionListener listener) {                       
>                                                                                                                             
>      String[] PERMISSIONS = {                                                                                               
>              Manifest.permission.RECORD_AUDIO,                                                                              
>              android.Manifest.permission.CAMERA                                                                             
>      };                                                                                                                     
>                                                                                                                             
>        this.requestPermissions(permissions,requestCode);                                                                    
>                                                                                                                             
>      if(!hasPermissions( PERMISSIONS)){                                                                                     
>          ActivityCompat.requestPermissions(this, PERMISSIONS, PERMISSION_ALL);                                              
>      }                                                                                                                      
>                                                                                                                             
>  }                                                                                                                          
>  public boolean hasPermissions(String... permissions) {                                                                     
>      if ( permissions != null) {                                                                                            
>          for (String permission : permissions) {                                                                            
>              if (ActivityCompat.checkSelfPermission(this, permission) != PackageManager.PERMISSION_GRANTED) {               
>                  return false;                                                                                              
>              }                                                                                                              
>          }                                                                                                                  
>      }                                                                                                                      
>      return true;                                                                                                           
>  }         
> ```

Thanks a lot man this worked for me.
