### ISSUE TITLE
Could not load: libreactnativejni.so

### ISSUE THREAD

**Issue by carotkut94** [jitsi/jitsi-meet#3390]
I changed some of the code, in react native like Toolbox buttons, as I needed only 3 button and some stuff like that and tested the app by running react-native run-android and it worked fine, then I generated the aar file  for sdk and other dependencies by following the instructions given at https://github.com/jitsi/jitsi-meet/tree/master/android and added them into my project and build the project using gradle.
But whenever I run the app I am getting this error.

08-21 18:29:45.728 5862-5882/? E/SoLoader: Error when loading lib: dlopen failed: library "libjsc.so" not found
08-21 18:29:45.728 5862-5882/? E/SoLoader: Error when loading lib: dlopen failed: library "libjsc.so" not found

Could not load: libreactnativejni.so
08-21 18:29:45.729 5862-5882/? E/AndroidRuntime: FATAL EXCEPTION: Thread-2
    Process: com.death.sample, PID: 5862
    java.lang.UnsatisfiedLinkError: couldn't find DSO to load: libreactnativejni.so
        at com.facebook.soloader.SoLoader.doLoadLibraryBySoName(SoLoader.java:522)
        at com.facebook.soloader.SoLoader.loadLibraryBySoName(SoLoader.java:420)
        at com.facebook.soloader.SoLoader.loadLibrary(SoLoader.java:370)
        at com.facebook.soloader.SoLoader.loadLibrary(SoLoader.java:335)
        at com.facebook.react.bridge.ReactBridge.staticInit(ReactBridge.java:18)
        at com.facebook.react.bridge.NativeMap.<clinit>(NativeMap.java:19)
        at com.facebook.react.bridge.JSCJavaScriptExecutorFactory.create(JSCJavaScriptExecutorFactory.java:21)
        at com.facebook.react.ReactInstanceManager$5.run(ReactInstanceManager.java:912)
        at java.lang.Thread.run(Thread.java:764)

here is my app/build.gradle

apply plugin: 'com.android.application'

android {
    compileSdkVersion 28
    defaultConfig {
        applicationId "com.death.sample"
        minSdkVersion 19
        targetSdkVersion 28
        versionCode 1
        versionName "1.0"
        testInstrumentationRunner "android.support.test.runner.AndroidJUnitRunner"
        ndk {
            abiFilters "armeabi-v7a", "x86"
        }
        packagingOptions {
            // The project react-native does not provide 64-bit binaries at the
            // time of this writing. Unfortunately, packaging any 64-bit
            // binaries into the .apk will crash the app at runtime on 64-bit
            // platforms.
            exclude '/lib/mips64/**'
            exclude '/lib/arm64-v8a/**'
            exclude '/lib/x86_64/**'
        }
    }
    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
        }
    }
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }

}

dependencies {
    implementation fileTree(include: ['*.jar'], dir: 'libs')
    implementation 'com.android.support:appcompat-v7:28.0.0-rc01'
    implementation 'com.android.support.constraint:constraint-layout:1.1.2'
    testImplementation 'junit:junit:4.12'
    androidTestImplementation 'com.android.support.test:runner:1.0.2'
    androidTestImplementation 'com.android.support.test.espresso:espresso-core:3.0.2'
    implementation fileTree(include: ['*.aar'], dir: 'libs')
    implementation 'com.facebook.soloader:soloader:0.3.0'
}

if I downgrade the version of soloader library 0.1.0+ by using 
implementation 'com.facebook.soloader:soloader:0.1.0+'
then I am getting 

08-21 18:38:45.071 11014-11033/com.death.sample E/AndroidRuntime: FATAL EXCEPTION: Thread-2
    Process: com.death.sample, PID: 11014
    java.lang.UnsatisfiedLinkError: dlopen failed: library "libjsc.so" not found
        at java.lang.Runtime.load0(Runtime.java:928)
        at java.lang.System.load(System.java:1621)
        at com.facebook.soloader.DirectorySoSource.loadLibraryFrom(DirectorySoSource.java:71)
        at com.facebook.soloader.DirectorySoSource.loadLibrary(DirectorySoSource.java:42)
        at com.facebook.soloader.SoLoader.loadLibraryBySoName(SoLoader.java:299)
        at com.facebook.soloader.SoLoader.loadLibrary(SoLoader.java:247)
        at com.facebook.react.bridge.ReactBridge.staticInit(ReactBridge.java:18)
        at com.facebook.react.bridge.NativeMap.<clinit>(NativeMap.java:19)
        at com.facebook.react.bridge.JSCJavaScriptExecutorFactory.create(JSCJavaScriptExecutorFactory.java:21)
        at com.facebook.react.ReactInstanceManager$5.run(ReactInstanceManager.java:912)
        at java.lang.Thread.run(Thread.java:764)

any solution?

**Comment by carotkut94** [comment]
because if I don't have that dependency it gives me error for soloader
java.lang.NoClassDefFoundError: Failed resolution of: Lcom/facebook/soloader/SoLoader;
        at com.facebook.react.ReactInstanceManager.initializeSoLoaderIfNecessary(ReactInstanceManager.java:308)
        at com.facebook.react.ReactInstanceManager.<init>(ReactInstanceManager.java:212)
        at com.facebook.react.ReactInstanceManagerBuilder.build(ReactInstanceManagerBuilder.java:282)
        at org.jitsi.meet.sdk.ReactInstanceManagerHolder.initReactInstanceManager(ReactInstanceManagerHolder.java:144)
        at org.jitsi.meet.sdk.BaseReactView.<init>(BaseReactView.java:104)
        at org.jitsi.meet.sdk.JitsiMeetView.<init>(JitsiMeetView.java:107)
        at com.death.sample.MainActivity.onCreate(MainActivity.java:18)
        at android.app.Activity.performCreate(Activity.java:7041)
        at android.app.Activity.performCreate(Activity.java:7032)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1231)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2864)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2989)
        at android.app.ActivityThread.-wrap11(Unknown Source:0)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1688)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:164)
        at android.app.ActivityThread.main(ActivityThread.java:6753)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:482)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)
     Caused by: java.lang.ClassNotFoundException: Didn't find class "com.facebook.soloader.SoLoader" on path: DexPathList[[zip file "/data/app/com.death.sample-bbnxD4zXbN5eLJIibo1c3w==/base.apk"],nativeLibraryDirectories=[/data/app/com.death.sample-bbnxD4zXbN5eLJIibo1c3w==/lib/arm, /data/app/com.death.sample-bbnxD4zXbN5eLJIibo1c3w==/base.apk!/lib/armeabi-v7a, /system/lib, /vendor/lib]]
        at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:125)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:379)

and after those changes when I ran it using react-native run-android it ran 
![device-2018-08-21-190541](https://user-images.githubusercontent.com/17780580/44404783-44deaa00-a575-11e8-89b9-0cf9f697e3b6.png)

I just removed the add user and the last button and changed the logic about adding the people into the filmstrip below the controls. It worked fine and after testing I made the aar files for the dependencies and imported them into the android project and getting these errors

**Comment by carotkut94** [comment]
@saghul 

I lowered the compile and target sdk version to 26 but no changes, same issue

**Comment by saghul** [comment]
You can't just move the aar. You also need to all the dependencies like react native and the other native plugins. See the documentation on how to do this. The easiest is to use a maven repo where you publish all the artifacts. (the docs cover this)

**Comment by carotkut94** [comment]
![screen shot 2018-08-21 at 7 29 44 pm](https://user-images.githubusercontent.com/17780580/44406175-989ec280-a578-11e8-8fe1-e2b60f53b1ce.png)
I have added all the aar files which are required by the sdk as show in the above picture

**Comment by saghul** [comment]
That's not enough, there are other resource files which are also needed.

**Comment by carotkut94** [comment]
But these are the ones which are enlisted in the gradle of sdk module under Android project, and if I am going to host these dependencies on maven, then these are the aar files which are going to be bundled as transitive dependencies for sdk as written in readme
