### ISSUE TITLE
Getting - "Unfortunately, something went wrong", after that moderator conference is not accepting participants connections.

### ISSUE THREAD

**Issue by cheelibrahmaiah** [jitsi/jitsi-meet#3453]
Hi @saghul, @damencho 

I have installed JITSI-MEET in my dedicated servers, it was working very well & smooth.
Please check my list:
1. We are integrated Authentication for the conference- moderator was login as "Auth" VirtualHost using I am the Host Credentials, participants are login as "Guest" VirtualHost
2. For Recording JIBRI Python version integrated and we are manually recording the session using script files

For us jitsi meet working fine with recording, all of sudden (it is not often) Getting - "Unfortunately, something went wrong", after that conference not working., for temporary solution we are restart the services (jicofo, prosody, jitsi-videobridge) then it is working. 

Pls check and provide perminent solution for me.
Thanks & Regards,
Brahmaiah Cheeli.

**Comment by paweldomas** [comment]
Hi, in order to figure this out we'd need logs from the client (JS console logs) when this error appears and from Jicofo.

**Comment by cheelibrahmaiah** [comment]
Thanks for quick reply @paweldomas,
This issue not frequent, i am unable to get find the  

> client  (JS console logs)

i can manage to JVB and Jicofo logs

Please find below log files.


[jicofo.log](https://github.com/jitsi/jitsi-meet/files/2389207/jicofo.log)

JVB Log file link:
https://drive.google.com/open?id=1iEzzWIhV7KLZZRKFYdC2BJ8HE2v56FVv

**Comment by paweldomas** [comment]
I'm not sure if it's the main reason for problems, but it looks like something's wrong with Jibri MUC configuration. Looks like Jicofo is not able to join `JibriBrewery@internal.auth.liveclass.edvie.com`:
`Jicofo 2018-09-12 07:59:36.750 SEVERE: [26] org.jitsi.jicofo.xmpp.BaseBrewery.start().196 Failed to create room: JibriBrewery@internal.auth.liveclass.edvie.com
net.java.sip.communicator.service.protocol.OperationFailedException: Failed to join the room
        at org.jitsi.impl.protocol.xmpp.ChatRoomImpl.joinAs(ChatRoomImpl.java:298)
        at org.jitsi.impl.protocol.xmpp.ChatRoomImpl.join(ChatRoomImpl.java:209)
        at org.jitsi.jicofo.xmpp.BaseBrewery.start(BaseBrewery.java:190)
        at org.jitsi.jicofo.xmpp.BaseBrewery.maybeStart(BaseBrewery.java:141)
        at org.jitsi.jicofo.xmpp.BaseBrewery.registrationStateChanged(BaseBrewery.java:166)
        at org.jitsi.jicofo.ProtocolProviderHandler.registrationStateChanged(ProtocolProviderHandler.java:141)
        at net.java.sip.communicator.service.protocol.AbstractProtocolProviderService.fireRegistrationStateChanged(AbstractProtocolProviderService.java:187)
        at net.java.sip.communicator.service.protocol.AbstractProtocolProviderService.fireRegistrationStateChanged(AbstractProtocolProviderService.java:141)
        at org.jitsi.impl.protocol.xmpp.XmppProtocolProvider.notifyConnected(XmppProtocolProvider.java:345)
        at org.jitsi.impl.protocol.xmpp.XmppProtocolProvider.access$100(XmppProtocolProvider.java:62)
        at org.jitsi.impl.protocol.xmpp.XmppProtocolProvider$XmppConnectionListener.authenticated(XmppProtocolProvider.java:633)
        at org.jivesoftware.smack.AbstractXMPPConnection.callConnectionAuthenticatedListener(AbstractXMPPConnection.java:1263)
        at org.jivesoftware.smack.AbstractXMPPConnection.afterSuccessfulLogin(AbstractXMPPConnection.java:575)
        at org.jivesoftware.smack.tcp.XMPPTCPConnection.afterSuccessfulLogin(XMPPTCPConnection.java:379)
        at org.jivesoftware.smack.tcp.XMPPTCPConnection.loginInternal(XMPPTCPConnection.java:444)
        at org.jivesoftware.smack.AbstractXMPPConnection.login(AbstractXMPPConnection.java:494)
        at org.jitsi.impl.protocol.xmpp.XmppProtocolProvider.doConnect(XmppProtocolProvider.java:297)
        at org.jitsi.impl.protocol.xmpp.XmppProtocolProvider.access$000(XmppProtocolProvider.java:62)
        at org.jitsi.impl.protocol.xmpp.XmppProtocolProvider$1.call(XmppProtocolProvider.java:256)
        at org.jitsi.impl.protocol.xmpp.XmppProtocolProvider$1.call(XmppProtocolProvider.java:251)
        at org.jitsi.retry.RetryStrategy$TaskRunner.run(RetryStrategy.java:193)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
Caused by: org.jivesoftware.smack.XMPPException$XMPPErrorException: XMPP error reply received from internal.auth.liveclass.edvie.com: XMPPError: remote-server-not-found - cancel
        at org.jivesoftware.smack.XMPPException$XMPPErrorException.ifHasErrorThenThrow(XMPPException.java:131)
        at org.jivesoftware.smack.StanzaCollector.nextResultOrThrow(StanzaCollector.java:256)
        at org.jivesoftware.smack.StanzaCollector.nextResultOrThrow(StanzaCollector.java:208)
        at org.jivesoftware.smackx.disco.ServiceDiscoveryManager.discoverInfo(ServiceDiscoveryManager.java:542)
        at org.jivesoftware.smackx.disco.ServiceDiscoveryManager.discoverInfo(ServiceDiscoveryManager.java:508)
        at org.jivesoftware.smackx.disco.ServiceDiscoveryManager.supportsFeatures(ServiceDiscoveryManager.java:738)
        at org.jivesoftware.smackx.disco.ServiceDiscoveryManager.supportsFeatures(ServiceDiscoveryManager.java:734)
        at org.jivesoftware.smackx.disco.ServiceDiscoveryManager.supportsFeature(ServiceDiscoveryManager.java:730)
        at org.jivesoftware.smackx.muc.MultiUserChatManager.providesMucService(MultiUserChatManager.java:360)
        at org.jivesoftware.smackx.muc.MultiUserChat.enter(MultiUserChat.java:311)
        at org.jivesoftware.smackx.muc.MultiUserChat.createOrJoin(MultiUserChat.java:498)
        at org.jivesoftware.smackx.muc.MultiUserChat.createOrJoin(MultiUserChat.java:444)
        at org.jitsi.impl.protocol.xmpp.ChatRoomImpl.joinAs(ChatRoomImpl.java:240)
        ... 27 more
`
