### ISSUE TITLE
New installation of Jitsi-Meet with error ERR_CONNECTION_CLOSED

### ISSUE THREAD

**Issue by schub91** [jitsi/jitsi-meet#3512]
For several days we have tried to make a new installation of Jitsi-meet using the quick-install on two servers, using different distributions in Ubuntu from 16.04 to 18.04 as in Debian 8 or 9, everything is installed without major setbacks, but at the moment of trying to access the website of the video call https://miservidor.empresa.com I get the error ERR_CONNECTION_CLOSED

I have done tests in two different services with two different distributions, both in AWS and ServerHosh with all ports open and in some tests that I have done.

**Comment by damencho** [comment]
If you check jvb logs, do you see an error about not able to bind to port 443 cause port already i use? 
I spotted this problem on Wednesday, but didn't have time to work on it (personal issues), it needs a fix in ice4j.
Can you try installing nginx before installing jitsi-meet, this shoul be fine for now.

**Comment by schub91** [comment]
JVB 2018-10-05 21:20:39.396 INFO: [1] util.NetworkUtils.<clinit>().117 java.net.preferIPv6Addresses=null
JVB 2018-10-05 21:20:39.399 INFO: [1] util.NetworkUtils.<clinit>().118 java.net.preferIPv4Stack=null
SLF4J: Class path contains multiple SLF4J bindings.
SLF4J: Found binding in [jar:file:/usr/share/jitsi-videobridge/lib/slf4j-jdk14-1.7.7.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: Found binding in [jar:file:/usr/share/jitsi-videobridge/lib/slf4j-simple-1.6.1.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: See http://www.slf4j.org/codes.html#multiple_bindings for an explanation.
SLF4J: Actual binding is of type [org.slf4j.impl.JDK14LoggerFactory]
JVB 2018-10-05 21:20:39.917 INFO: [10] org.jitsi.service.libjitsi.LibJitsi.log() Successfully started LibJitsi using as implementation: org.jitsi.impl.libjitsi.LibJits$
JVB 2018-10-05 21:20:39.936 INFO: [10] impl.configuration.ConfigurationActivator.log() Using properties file configuration store.
JVB 2018-10-05 21:20:39.937 INFO: [10] org.jitsi.impl.configuration.ConfigurationServiceImpl.log() java.vendor=Oracle Corporation
JVB 2018-10-05 21:20:39.937 INFO: [10] org.jitsi.impl.configuration.ConfigurationServiceImpl.log() org.ice4j.ice.CONSENT_FRESHNESS_INTERVAL=3000
JVB 2018-10-05 21:20:39.937 INFO: [10] org.jitsi.impl.configuration.ConfigurationServiceImpl.log() sun.java.launcher=SUN_STANDARD
JVB 2018-10-05 21:20:39.938 INFO: [10] org.jitsi.impl.configuration.ConfigurationServiceImpl.log() org.ice4j.ice.harvest.AbstractUdpListener.SO_RCVBUF=10485760
JVB 2018-10-05 21:20:39.938 INFO: [10] org.jitsi.impl.configuration.ConfigurationServiceImpl.log() sun.management.compiler=HotSpot 64-Bit Tiered Compilers
JVB 2018-10-05 21:20:39.938 INFO: [10] org.jitsi.impl.configuration.ConfigurationServiceImpl.log() org.jitsi.impl.neomedia.transform.srtp.SRTPCryptoContext.checkReplay$
JVB 2018-10-05 21:20:39.938 INFO: [10] org.jitsi.impl.configuration.ConfigurationServiceImpl.log() os.name=Linux
JVB 2018-10-05 21:20:39.938 INFO: [10] org.jitsi.impl.configuration.ConfigurationServiceImpl.log() sun.boot.class.path=/usr/lib/jvm/java-8-openjdk-amd64/jre/lib/resour$
JVB 2018-10-05 21:20:39.938 INFO: [10] org.jitsi.impl.configuration.ConfigurationServiceImpl.log() java.util.logging.config.file=/etc/jitsi/videobridge/logging.propert$
JVB 2018-10-05 21:20:39.939 INFO: [10] org.jitsi.impl.configuration.ConfigurationServiceImpl.log() java.vm.specification.vendor=Oracle Corporation
JVB 2018-10-05 21:20:39.939 INFO: [10] org.jitsi.impl.configuration.ConfigurationServiceImpl.log() org.jitsi.service.neomedia.MediaService.ENABLE_H264_FORMAT=true
JVB 2018-10-05 21:20:39.939 INFO: [10] org.jitsi.impl.configuration.ConfigurationServiceImpl.log() java.runtime.version=1.8.0_181-8u181-b13-1~deb9u1-b13
JVB 2018-10-05 21:20:39.939 INFO: [10] org.jitsi.impl.configuration.ConfigurationServiceImpl.log() org.ice4j.ice.CONSENT_FRESHNESS_MAX_RETRANSMISSIONS=5
JVB 2018-10-05 21:20:39.939 INFO: [10] org.jitsi.impl.configuration.ConfigurationServiceImpl.log() org.jitsi.service.neomedia.VideoMediaStream.REQUEST_RETRANSMISSIONS=$
JVB 2018-10-05 21:20:39.940 INFO: [10] org.jitsi.impl.configuration.ConfigurationServiceImpl.log() user.name=jvb
JVB 2018-10-05 21:20:39.940 INFO: [10] org.jitsi.impl.configuration.ConfigurationServiceImpl.log() org.jitsi.impl.neomedia.rtp.ENABLE_AST_RBE=true
JVB 2018-10-05 21:20:39.940 INFO: [10] org.jitsi.impl.configuration.ConfigurationServiceImpl.log() net.java.sip.communicator.impl.configuration.USE_PROPFILE_CONFIG=true
JVB 2018-10-05 21:20:39.940 INFO: [10] org.jitsi.impl.configuration.ConfigurationServiceImpl.log() user.language=en
JVB 2018-10-05 21:20:39.949 INFO: [10] org.jitsi.impl.configuration.ConfigurationServiceImpl.log() org.jitsi.impl.neomedia.transform.csrc.SsrcTransformEngine.dropMuted$
JVB 2018-10-05 21:20:39.952 INFO: [10] org.jitsi.impl.configuration.ConfigurationServiceImpl.log() sun.boot.library.path=/usr/lib/jvm/java-8-openjdk-amd64/jre/lib/amd64
JVB 2018-10-05 21:20:39.953 INFO: [10] org.jitsi.impl.configuration.ConfigurationServiceImpl.log() net.java.sip.communicator.service.media.MIN_PORT_NUMBER=10001
JVB 2018-10-05 21:20:39.953 INFO: [10] org.jitsi.impl.configuration.ConfigurationServiceImpl.log() net.java.sip.communicator.packetlogging.PACKET_LOGGING_ENABLED=false
JVB 2018-10-05 21:20:39.953 INFO: [10] org.jitsi.impl.configuration.ConfigurationServiceImpl.log() org.jitsi.videobridge.rest=false
JVB 2018-10-05 21:20:39.953 INFO: [10] org.jitsi.impl.configuration.ConfigurationServiceImpl.log() java.version=1.8.0_181
JVB 2018-10-05 21:20:39.953 INFO: [10] org.jitsi.impl.configuration.ConfigurationServiceImpl.log() user.timezone=Etc/UTC
JVB 2018-10-05 21:20:39.954 INFO: [10] org.jitsi.impl.configuration.ConfigurationServiceImpl.log() sun.arch.data.model=64
JVB 2018-10-05 21:20:39.954 INFO: [10] org.jitsi.impl.configuration.ConfigurationServiceImpl.log() org.ice4j.ice.CONSENT_FRESHNESS_WAIT_INTERVAL=500
JVB 2018-10-05 21:20:39.954 INFO: [10] org.jitsi.impl.configuration.ConfigurationServiceImpl.log() java.endorsed.dirs=/usr/lib/jvm/java-8-openjdk-amd64/jre/lib/endorsed
JVB 2018-10-05 21:20:39.955 INFO: [10] org.jitsi.impl.configuration.ConfigurationServiceImpl.log() sun.cpu.isalist=
JVB 2018-10-05 21:20:39.955 INFO: [10] org.jitsi.impl.configuration.ConfigurationServiceImpl.log() sun.jnu.encoding=UTF-8

**Comment by deadmanIsARabbit** [comment]
I think I have the same error after i have updated via apt.

`java.net.BindException: Address already in use
        at sun.nio.ch.Net.bind0(Native Method)
        at sun.nio.ch.Net.bind(Net.java:433)
        at sun.nio.ch.Net.bind(Net.java:425)
        at sun.nio.ch.ServerSocketChannelImpl.bind(ServerSocketChannelImpl.java:223)
        at sun.nio.ch.ServerSocketAdaptor.bind(ServerSocketAdaptor.java:74)
        at org.ice4j.socket.MuxServerSocketChannelFactory.openAndBindServerSocketChannel(MuxServerSocketChannelFactory.java:261)
        at org.ice4j.socket.jdk8.MuxingServerSocketChannel.openAndBind(MuxingServerSocketChannel.java:295)
        at org.ice4j.socket.jdk8.MuxServerSocketChannel.openAndBind(MuxServerSocketChannel.java:64)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.ice4j.socket.MuxServerSocketChannelFactory.openAndBindMuxServerSocketChannel(MuxServerSocketChannelFactory.java:181)
        at org.jitsi.rest.MuxServerConnector.open(MuxServerConnector.java:170)
        at org.eclipse.jetty.server.AbstractNetworkConnector.doStart(AbstractNetworkConnector.java:80)
        at org.eclipse.jetty.server.ServerConnector.doStart(ServerConnector.java:236)
        at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68)
        at org.eclipse.jetty.server.Server.doStart(Server.java:366)
        at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68)
        at org.jitsi.rest.AbstractJettyBundleActivator.doStart(AbstractJettyBundleActivator.java:215)
        at org.jitsi.rest.AbstractJettyBundleActivator.start(AbstractJettyBundleActivator.java:566)
        at org.jitsi.impl.osgi.framework.BundleImpl.start(BundleImpl.java:307)
        at org.jitsi.impl.osgi.framework.launch.FrameworkImpl.startLevelChanged(FrameworkImpl.java:472)
        at org.jitsi.impl.osgi.framework.startlevel.FrameworkStartLevelImpl$Command.run(FrameworkStartLevelImpl.java:137)
        at org.jitsi.impl.osgi.framework.AsyncExecutor.runInThread(AsyncExecutor.java:122)
        at org.jitsi.impl.osgi.framework.AsyncExecutor.access$000(AsyncExecutor.java:28)
        at org.jitsi.impl.osgi.framework.AsyncExecutor$1.run(AsyncExecutor.java:231)
JVB 2018-10-09 09:40:49.387 WARNING: [10] org.eclipse.jetty.util.component.AbstractLifeCycle.setFailed() FAILED org.eclipse.jetty.server.Server@263ba25c: java.net.BindException: Address already in use
java.net.BindException: Address already in use
        at sun.nio.ch.Net.bind0(Native Method)
        at sun.nio.ch.Net.bind(Net.java:433)
        at sun.nio.ch.Net.bind(Net.java:425)
        at sun.nio.ch.ServerSocketChannelImpl.bind(ServerSocketChannelImpl.java:223)
        at sun.nio.ch.ServerSocketAdaptor.bind(ServerSocketAdaptor.java:74)
        at org.ice4j.socket.MuxServerSocketChannelFactory.openAndBindServerSocketChannel(MuxServerSocketChannelFactory.java:261)
        at org.ice4j.socket.jdk8.MuxingServerSocketChannel.openAndBind(MuxingServerSocketChannel.java:295)
        at org.ice4j.socket.jdk8.MuxServerSocketChannel.openAndBind(MuxServerSocketChannel.java:64)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.ice4j.socket.MuxServerSocketChannelFactory.openAndBindMuxServerSocketChannel(MuxServerSocketChannelFactory.java:181)
        at org.jitsi.rest.MuxServerConnector.open(MuxServerConnector.java:170)
        at org.eclipse.jetty.server.AbstractNetworkConnector.doStart(AbstractNetworkConnector.java:80)
        at org.eclipse.jetty.server.ServerConnector.doStart(ServerConnector.java:236)
        at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68)
        at org.eclipse.jetty.server.Server.doStart(Server.java:366)
        at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68)
        at org.jitsi.rest.AbstractJettyBundleActivator.doStart(AbstractJettyBundleActivator.java:215)
        at org.jitsi.rest.AbstractJettyBundleActivator.start(AbstractJettyBundleActivator.java:566)
        at org.jitsi.impl.osgi.framework.BundleImpl.start(BundleImpl.java:307)
        at org.jitsi.impl.osgi.framework.launch.FrameworkImpl.startLevelChanged(FrameworkImpl.java:472)
        at org.jitsi.impl.osgi.framework.startlevel.FrameworkStartLevelImpl$Command.run(FrameworkStartLevelImpl.java:137)
        at org.jitsi.impl.osgi.framework.AsyncExecutor.runInThread(AsyncExecutor.java:122)
        at org.jitsi.impl.osgi.framework.AsyncExecutor.access$000(AsyncExecutor.java:28)
        at org.jitsi.impl.osgi.framework.AsyncExecutor$1.run(AsyncExecutor.java:231)
JVB 2018-10-09 09:40:49.388 SEVERE: [10] org.jitsi.rest.AbstractJettyBundleActivator.doStart().222 Failed to initialize and/or start a new Jetty HTTP(S) server instance.
java.net.BindException: Address already in use
        at sun.nio.ch.Net.bind0(Native Method)
        at sun.nio.ch.Net.bind(Net.java:433)
        at sun.nio.ch.Net.bind(Net.java:425)
        at sun.nio.ch.ServerSocketChannelImpl.bind(ServerSocketChannelImpl.java:223)
        at sun.nio.ch.ServerSocketAdaptor.bind(ServerSocketAdaptor.java:74)
        at org.ice4j.socket.MuxServerSocketChannelFactory.openAndBindServerSocketChannel(MuxServerSocketChannelFactory.java:261)
        at org.ice4j.socket.jdk8.MuxingServerSocketChannel.openAndBind(MuxingServerSocketChannel.java:295)
        at org.ice4j.socket.jdk8.MuxServerSocketChannel.openAndBind(MuxServerSocketChannel.java:64)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.ice4j.socket.MuxServerSocketChannelFactory.openAndBindMuxServerSocketChannel(MuxServerSocketChannelFactory.java:181)
        at org.jitsi.rest.MuxServerConnector.open(MuxServerConnector.java:170)
        at org.eclipse.jetty.server.AbstractNetworkConnector.doStart(AbstractNetworkConnector.java:80)
        at org.eclipse.jetty.server.ServerConnector.doStart(ServerConnector.java:236)
        at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68)
        at org.eclipse.jetty.server.Server.doStart(Server.java:366)
        at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68)
        at org.jitsi.rest.AbstractJettyBundleActivator.doStart(AbstractJettyBundleActivator.java:215)
        at org.jitsi.rest.AbstractJettyBundleActivator.start(AbstractJettyBundleActivator.java:566)
        at org.jitsi.impl.osgi.framework.BundleImpl.start(BundleImpl.java:307)
        at org.jitsi.impl.osgi.framework.launch.FrameworkImpl.startLevelChanged(FrameworkImpl.java:472)
        at org.jitsi.impl.osgi.framework.startlevel.FrameworkStartLevelImpl$Command.run(FrameworkStartLevelImpl.java:137)
        at org.jitsi.impl.osgi.framework.AsyncExecutor.runInThread(AsyncExecutor.java:122)
        at org.jitsi.impl.osgi.framework.AsyncExecutor.access$000(AsyncExecutor.java:28)
        at org.jitsi.impl.osgi.framework.AsyncExecutor$1.run(AsyncExecutor.java:231)
JVB 2018-10-09 09:40:49.449 SEVERE: [10] org.jitsi.impl.osgi.framework.BundleImpl.start() Error starting bundle: org.jitsi.videobridge.rest.PublicRESTBundleActivator@7dae4d48
java.net.BindException: Address already in use
        at sun.nio.ch.Net.bind0(Native Method)
        at sun.nio.ch.Net.bind(Net.java:433)
        at sun.nio.ch.Net.bind(Net.java:425)
        at sun.nio.ch.ServerSocketChannelImpl.bind(ServerSocketChannelImpl.java:223)
        at sun.nio.ch.ServerSocketAdaptor.bind(ServerSocketAdaptor.java:74)
        at org.ice4j.socket.MuxServerSocketChannelFactory.openAndBindServerSocketChannel(MuxServerSocketChannelFactory.java:261)
        at org.ice4j.socket.jdk8.MuxingServerSocketChannel.openAndBind(MuxingServerSocketChannel.java:295)
        at org.ice4j.socket.jdk8.MuxServerSocketChannel.openAndBind(MuxServerSocketChannel.java:64)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.ice4j.socket.MuxServerSocketChannelFactory.openAndBindMuxServerSocketChannel(MuxServerSocketChannelFactory.java:181)
        at org.jitsi.rest.MuxServerConnector.open(MuxServerConnector.java:170)
        at org.eclipse.jetty.server.AbstractNetworkConnector.doStart(AbstractNetworkConnector.java:80)
        at org.eclipse.jetty.server.ServerConnector.doStart(ServerConnector.java:236)
        at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68)
        at org.eclipse.jetty.server.Server.doStart(Server.java:366)
        at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68)
        at org.jitsi.rest.AbstractJettyBundleActivator.doStart(AbstractJettyBundleActivator.java:215)
        at org.jitsi.rest.AbstractJettyBundleActivator.start(AbstractJettyBundleActivator.java:566)
        at org.jitsi.impl.osgi.framework.BundleImpl.start(BundleImpl.java:307)
        at org.jitsi.impl.osgi.framework.launch.FrameworkImpl.startLevelChanged(FrameworkImpl.java:472)
        at org.jitsi.impl.osgi.framework.startlevel.FrameworkStartLevelImpl$Command.run(FrameworkStartLevelImpl.java:137)
        at org.jitsi.impl.osgi.framework.AsyncExecutor.runInThread(AsyncExecutor.java:122)
        at org.jitsi.impl.osgi.framework.AsyncExecutor.access$000(AsyncExecutor.java:28)
        at org.jitsi.impl.osgi.framework.AsyncExecutor$1.run(AsyncExecutor.java:231)
JVB 2018-10-09 09:40:49.450 SEVERE: [10] org.jitsi.impl.osgi.framework.launch.FrameworkImpl.startLevelChanged() Error changing start level
org.osgi.framework.BundleException: BundleActivator.start
        at org.jitsi.impl.osgi.framework.BundleImpl.start(BundleImpl.java:327)
        at org.jitsi.impl.osgi.framework.launch.FrameworkImpl.startLevelChanged(FrameworkImpl.java:472)
        at org.jitsi.impl.osgi.framework.startlevel.FrameworkStartLevelImpl$Command.run(FrameworkStartLevelImpl.java:137)
        at org.jitsi.impl.osgi.framework.AsyncExecutor.runInThread(AsyncExecutor.java:122)
        at org.jitsi.impl.osgi.framework.AsyncExecutor.access$000(AsyncExecutor.java:28)
        at org.jitsi.impl.osgi.framework.AsyncExecutor$1.run(AsyncExecutor.java:231)
Caused by: java.net.BindException: Address already in use
        at sun.nio.ch.Net.bind0(Native Method)
        at sun.nio.ch.Net.bind(Net.java:433)
        at sun.nio.ch.Net.bind(Net.java:425)
        at sun.nio.ch.ServerSocketChannelImpl.bind(ServerSocketChannelImpl.java:223)
        at sun.nio.ch.ServerSocketAdaptor.bind(ServerSocketAdaptor.java:74)
        at org.ice4j.socket.MuxServerSocketChannelFactory.openAndBindServerSocketChannel(MuxServerSocketChannelFactory.java:261)
        at org.ice4j.socket.jdk8.MuxingServerSocketChannel.openAndBind(MuxingServerSocketChannel.java:295)
        at org.ice4j.socket.jdk8.MuxServerSocketChannel.openAndBind(MuxServerSocketChannel.java:64)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.ice4j.socket.MuxServerSocketChannelFactory.openAndBindMuxServerSocketChannel(MuxServerSocketChannelFactory.java:181)
        at org.jitsi.rest.MuxServerConnector.open(MuxServerConnector.java:170)
        at org.eclipse.jetty.server.AbstractNetworkConnector.doStart(AbstractNetworkConnector.java:80)
        at org.eclipse.jetty.server.ServerConnector.doStart(ServerConnector.java:236)
        at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68)
        at org.eclipse.jetty.server.Server.doStart(Server.java:366)
        at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68)
        at org.jitsi.rest.AbstractJettyBundleActivator.doStart(AbstractJettyBundleActivator.java:215)
        at org.jitsi.rest.AbstractJettyBundleActivator.start(AbstractJettyBundleActivator.java:566)
        at org.jitsi.impl.osgi.framework.BundleImpl.start(BundleImpl.java:307)
        ... 5 more
`

Is this what you have meant @damencho

**Comment by deadmanIsARabbit** [comment]
Okay I have found a workaround: 
In `/etc/jitsi/videobridge/sip-communicator.properties`
I had defined:

```
org.jitsi.videobridge.rest.jetty.tls.port=443 
org.jitsi.videobridge.TCP_HARVESTER_PORT=443
```

Changing the TCP_Harvester_Port to 4443 did the trick. Afterwards Jitsi Videobridge restarted succsessfully. 

```
org.jitsi.videobridge.rest.jetty.tls.port=443 
org.jitsi.videobridge.TCP_HARVESTER_PORT=4443
```
Maybe you want to try this aswell @schub91

**Comment by pdarcos** [comment]
I have the exact same problem as described here. Indeed changing to port 4443 temporarily solves the problem but that still means many people behind restrictive firewalls won't be able to join.

It seems ice4j can't bind to 443

**Comment by damencho** [comment]
We are aware of this problem and will be fixing it shortly, sorry for the inconvinience.

**Comment by pdarcos** [comment]
No worries. Thanks for the quick reply!

**Comment by schub91** [comment]
> Okay I have found a workaround:
> In `/etc/jitsi/videobridge/sip-communicator.properties`
> I had defined:
> 
> ```
> org.jitsi.videobridge.rest.jetty.tls.port=443 
> org.jitsi.videobridge.TCP_HARVESTER_PORT=443
> ```
> Changing the TCP_Harvester_Port to 4443 did the trick. Afterwards Jitsi Videobridge restarted succsessfully.
> 
> ```
> org.jitsi.videobridge.rest.jetty.tls.port=443 
> org.jitsi.videobridge.TCP_HARVESTER_PORT=4443
> ```
> Maybe you want to try this aswell @schub91

I try this solutions, not working!

**Comment by damencho** [comment]
One possible workaround is to set `org.jitsi.videobridge.rest.jetty.host=::` to be `org.jitsi.videobridge.rest.jetty.host=internal_ip_address` or `org.jitsi.videobridge.rest.jetty.host=external_ip_address` depends on the deployment. Use external ip address if that is available on the machine, otherwise use the internal one to which packets a forwarded. I think this should work.

**Comment by pdarcos** [comment]
Yes, that would work but then you need to deal with packet forwarding.
It's a workaround but ideally ice4j would bind to 443 like it did in the past.

Cheers

**Comment by damencho** [comment]
Like I said I think this is a workaround till the fix is made and I don't see what forwarding you need to do? 
Currently, tcp harvesters try to bind to all available ipaddresses (public or private) and jetty tries to bind to the all-address('::') after that and this fails. If you just make jetty bind to the address that is used by the harvester it will not fail as it will reuse the socket and everything should work. You just need to set the appropriate address, that will work (the public if any, or the private on which packets arrive).
And this is temporary workaround till we fix it and push it to stable.

**Comment by damencho** [comment]
No.

**Comment by damencho** [comment]
Upload and js console logs from such problem

**Comment by pdarcos** [comment]
I'll open issues in the community forum first. There are many separate ones.

**Comment by pdarcos** [comment]
Just tried to open the first and realised there's no option to upload logs

**Comment by pdarcos** [comment]
https://community.jitsi.org/t/latest-unstable-on-debian-9-connectivity-issues-even-when-on-same-lan/15339
