### ISSUE TITLE
Jigasi no longer working? no telephone icon

### ISSUE THREAD

**Issue by pdarcos** [jitsi/jitsi-meet#3522]
Hi guys,

I just updated my jitsi-meet install and I can no longer see the telephone icon like before.

Has this changed recently? It used to work fine and in the console I can see that it's registering the SIP account ok
Sip gateway enabled:  true

So what happened to the telephone icon and how can I re-enable dialing out through SIP?

Thanks

**Comment by damencho** [comment]
Do you have the plus sign in the toolbar? Can you enter the phone number and dial there?

**Comment by pdarcos** [comment]
I do have the plus sign.
I tried entering the SIP number with and without domain info but nothing happens.
Let me grab the jvb logs

So I take it the telephone icon is no longer an option like before?

**Comment by damencho** [comment]
It needs just to be the telephone number. Well jvb logs are not needed ... Check js console logs and maybe jicofo and jigasi logs.

**Comment by damencho** [comment]
I suspect jigasi have a problem

**Comment by pdarcos** [comment]
I think so too.
Jigasi logs show a bunch of errors:

2018-10-09 19:16:36.572 SEVERE: [10] impl.configuration.ConfigurationActivator.log() Error creating c lib instance for fixing file permissions

2018-10-09 19:16:36.781 INFO: [11] impl.dns.DnsUtilActivator.logDNSServers().293 Loading or Reloading resolver config, default DNS servers are: 213.133.98.98, 213.133.100.100, 213.133.99.99, 
2018-10-09 19:16:36.820 WARNING: [10] impl.sysactivity.SystemActivityNotifications.<clinit>().140 Failed to initialize native counterpart
java.lang.UnsatisfiedLinkError: /tmp/jna--1160142225/jna7525926458436943766.tmp: libgdk-x11-2.0.so.0: cannot open shared object file: No such file or directory

2018-10-09 19:16:37.267 SEVERE: [10] org.jitsi.impl.neomedia.device.DeviceConfiguration.log() Failed to register custom Renderer org.jitsi.impl.neomedia.jmfext.media.renderer.audio.PulseAudioRenderer with JMF.
java.lang.IllegalStateException: audioSystem
	at org.jitsi.impl.neomedia.jmfext.media.renderer.audio.PulseAudioRenderer.<init>(PulseAudioRenderer.java:155)

**Comment by pdarcos** [comment]
I'm running latest packages (Debian 9) from unstable repo

**Comment by damencho** [comment]
Those are unrelated and harmless.
Check logs of jicofo and jigasi, what are they on attempting a call. When nothing happens what are the js console logs

**Comment by pdarcos** [comment]
Ok, the jigasi logs seem to indicate a transport and certificate error.

2018-10-09 19:16:38.502 WARNING: [53] org.jitsi.jigasi.health.SipHealthPeriodicChecker.log() No health check started, no HEALTH_CHECK_SIP_URI prop.
2018-10-09 19:28:34.635 INFO: [99] impl.protocol.sip.SipLogger.logInfo().196 Info from the JAIN-SIP stack: Setting SIPMessage peerPacketSource to: /37.xx.xx.xx:5062
2018-10-09 19:28:34.642 SEVERE: [99] impl.protocol.sip.SipStackSharing.findTargetFor().922 no listeners
2018-10-09 19:28:34.642 SEVERE: [99] impl.protocol.sip.SipStackSharing.processRequest().709 couldn't find a ProtocolProviderServiceSipImpl to dispatch to
2018-10-09 19:32:02.795 WARNING: [87] org.jitsi.jigasi.xmpp.CallControl.checkAuthorized().262 Requests are not secured by JID filter!
2018-10-09 19:32:02.796 INFO: [87] org.jitsi.jigasi.xmpp.CallControl.handleDialIq().188 Got dial request fromnumber -> 1000 room: teste@conference.jitsi.mydomain.network
2018-10-09 19:32:02.906 INFO: [87] org.jitsi.jigasi.JvbConference.setXmppProvider().532 16659e2b95b@callcontrol.jitsi.mydomain.network will use ProtocolProviderServiceJabberImpl(16659e2b95b@jitsi.mydomain.network (Jabber))
2018-10-09 19:32:02.990 WARNING: [87] org.jitsi.xmpp.component.ComponentBase.verifyProcessingTime().540 PROCESSING TIME LIMIT EXCEEDED - it took 212ms to process: <iq type="set" to="callcontrol.jitsi.mydomain.network" from="focus@auth.jitsi.mydomain.network/focus6759951101" id="3cFrX-6043"><dial xmlns="urn:xmpp:rayo:1" to="1000" from="fromnumber"><header value="teste@conference.jitsi.mydomain.network" name="JvbRoomName"/></dial></iq>
2018-10-09 19:32:03.084 SEVERE: [104] impl.certificate.CertificateServiceImpl.verify().1064 Missing CertificateDialogService by default will not trust!
2018-10-09 19:32:03.085 INFO: [104] impl.certificate.CertificateServiceImpl.checkCertTrusted().832 Untrusted certificate
sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
	at sun.security.validator.PKIXValidator.doBuild(PKIXValidator.java:397)
	at sun.security.validator.PKIXValidator.engineValidate(PKIXValidator.java:302)

**Comment by pdarcos** [comment]
Thanks @damencho 

That fixed it. Working now!

**Comment by damencho** [comment]
Please in the future use community forum before opening new issues, thanks.
