### ISSUE TITLE
FATAL EXCEPTION: main，Android running flashback after successful compilation

### ISSUE THREAD

**Issue by 365323507** [jitsi/jitsi-meet#3531]
10-12 11:24:03.136 4646-4646/? E/AndroidRuntime: FATAL EXCEPTION: main
    Process: org.jitsi.meet, PID: 4646
    java.lang.RuntimeException: Unable to instantiate activity ComponentInfo{org.jitsi.meet/org.jitsi.meet.MainActivity}: java.lang.ClassNotFoundException: Didn't find class "org.jitsi.meet.MainActivity" on path: DexPathList[[zip file "/data/app/org.jitsi.meet-gD18FjR9EvxEgccAfIVCtQ==/base.apk", zip file "/data/app/org.jitsi.meet-gD18FjR9EvxEgccAfIVCtQ==/split_lib_directories_apk.apk", zip file "/data/app/org.jitsi.meet-gD18FjR9EvxEgccAfIVCtQ==/split_lib_resources_apk.apk"],nativeLibraryDirectories=[/data/app/org.jitsi.meet-gD18FjR9EvxEgccAfIVCtQ==/lib/arm, /data/app/org.jitsi.meet-gD18FjR9EvxEgccAfIVCtQ==/base.apk!/lib/armeabi-v7a, /data/app/org.jitsi.meet-gD18FjR9EvxEgccAfIVCtQ==/split_lib_directories_apk.apk!/lib/armeabi-v7a, /data/app/org.jitsi.meet-gD18FjR9EvxEgccAfIVCtQ==/split_lib_resources_apk.apk!/lib/armeabi-v7a, /system/lib, /system/vendor/lib]]
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2755)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2929)
        at android.app.ActivityThread.-wrap11(Unknown Source:0)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1618)
        at android.os.Handler.dispatchMessage(Handler.java:105)
        at android.os.Looper.loop(Looper.java:171)
        at android.app.ActivityThread.main(ActivityThread.java:6699)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:246)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:783)
     Caused by: java.lang.ClassNotFoundException: Didn't find class "org.jitsi.meet.MainActivity" on path: DexPathList[[zip file "/data/app/org.jitsi.meet-gD18FjR9EvxEgccAfIVCtQ==/base.apk", zip file "/data/app/org.jitsi.meet-gD18FjR9EvxEgccAfIVCtQ==/split_lib_directories_apk.apk", zip file "/data/app/org.jitsi.meet-gD18FjR9EvxEgccAfIVCtQ==/split_lib_resources_apk.apk"],nativeLibraryDirectories=[/data/app/org.jitsi.meet-gD18FjR9EvxEgccAfIVCtQ==/lib/arm, /data/app/org.jitsi.meet-gD18FjR9EvxEgccAfIVCtQ==/base.apk!/lib/armeabi-v7a, /data/app/org.jitsi.meet-gD18FjR9EvxEgccAfIVCtQ==/split_lib_directories_apk.apk!/lib/armeabi-v7a, /data/app/org.jitsi.meet-gD18FjR9EvxEgccAfIVCtQ==/split_lib_resources_apk.apk!/lib/armeabi-v7a, /system/lib, /system/vendor/lib]]
        at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:93)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
        at android.app.Instrumentation.newActivity(Instrumentation.java:1174)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2745)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2929) 
        at android.app.ActivityThread.-wrap11(Unknown Source:0) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1618) 
        at android.os.Handler.dispatchMessage(Handler.java:105) 
        at android.os.Looper.loop(Looper.java:171) 
        at android.app.ActivityThread.main(ActivityThread.java:6699) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:246) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:783) 
    	Suppressed: java.io.IOException: No original dex files found for dex location /data/app/org.jitsi.meet-gD18FjR9EvxEgccAfIVCtQ==/split_lib_resources_apk.apk
        at dalvik.system.DexFile.openDexFileNative(Native Method)
        at dalvik.system.DexFile.openDexFile(DexFile.java:353)
        at dalvik.system.DexFile.<init>(DexFile.java:100)
        at dalvik.system.DexFile.<init>(DexFile.java:74)
        at dalvik.system.DexPathList.loadDexFile(DexPathList.java:374)
        at dalvik.system.DexPathList.makeDexElements(DexPathList.java:337)
        at dalvik.system.DexPathList.<init>(DexPathList.java:157)
        at dalvik.system.BaseDexClassLoader.<init>(BaseDexClassLoader.java:65)
        at dalvik.system.PathClassLoader.<init>(PathClassLoader.java:64)
        at com.android.internal.os.PathClassLoaderFactory.createClassLoader(PathClassLoaderFactory.java:43)
        at android.app.ApplicationLoaders.getClassLoader(ApplicationLoaders.java:69)
        at android.app.ApplicationLoaders.getClassLoader(ApplicationLoaders.java:36)
        at android.app.LoadedApk.createOrUpdateClassLoaderLocked(LoadedApk.java:681)
        at android.app.LoadedApk.getClassLoader(LoadedApk.java:714)
        at android.app.LoadedApk.getResources(LoadedApk.java:941)
        at android.app.ContextImpl.createAppContext(ContextImpl.java:2254)
        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5757)
10-12 11:24:03.137 4646-4646/? E/AndroidRuntime:     at android.app.ActivityThread.-wrap1(Unknown Source:0)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1688)
        		... 6 more

**Comment by saghul** [comment]
> java.lang.RuntimeException: Unable to instantiate activity ComponentInfo{org.jitsi.meet/org.jitsi.meet.MainActivity}: java.lang.ClassNotFoundException: Didn't find class "org.jitsi.meet.MainActivity"

Something went very wrong with your build, as this is the main Activity. What steps did you follow?

**Comment by MeetDave324** [comment]
I also got the same error!!! Did you find any solution?
