### ISSUE TITLE
Jitsi meet Video conference UI customization Issue

### ISSUE THREAD

**Issue by SaraShafie1991** [jitsi/jitsi-meet#3570]
steps which i follow to customize jitsi meet on existing android application:-

1- clone project using git clone https://github.com/jitsi/jitsi-meet.git
2- perform cd jitsi-meet && npm install
3- put my android application in the android folder in jitsi-meet.
4- change my customization in React folder.
5- perform mkdir android/app/src/main/assets
6- perform react-native bundle --platform android --dev false --entry-file index.android.js --bundle-output android/app/src/main/assets/index.android.bundle --assets-dest android/app/src/main/res
7- perform react-native run-android

Result:
compiled done.
runtime error while i try to use jitsi meet.
runtime error :- 

    --------- beginning of crash
2018-10-25 09:58:02.028 7690-7981 E/AndroidRuntime: FATAL EXCEPTION: mqt_native_modules
    Process:, PID: 7690
    com.facebook.react.common.JavascriptException: undefined is not a function (evaluating 'o.addNetworkingHandler()'), stack:
    value@109:1238
    <unknown>@97:143
    v@2:1489
    d@2:949
    o@2:435
    <unknown>@72:1183
    get@34:352
    <unknown>@326:2780
    <unknown>@326:3281
    v@2:1489
    d@2:949
    o@2:435
    <unknown>@325:30
    v@2:1489
    d@2:949
    o@2:435
    <unknown>@324:163
    v@2:1489
    d@2:949
    o@2:435
    <unknown>@323:871
    v@2:1489
    d@2:949
    o@2:435
    <unknown>@322:1049
    v@2:1489
    d@2:949
    o@2:435
    <unknown>@320:240
    v@2:1489
    d@2:949
    o@2:435
    <unknown>@318:2900
    v@2:1489
    d@2:949
    o@2:435
    <unknown>@317:85
    v@2:1489
    d@2:949
    o@2:435
    <unknown>@316:552
    v@2:1489
    d@2:949
    o@2:435
    <unknown>@315:85
    v@2:1489
    d@2:949
    o@2:435
    <unknown>@13:109
    v@2:1489
    d@2:949
    o@2:435
    <unknown>@12:30
    v@2:1489
    d@2:879
    o@2:435
    global code@1310:4
    
        at com.facebook.react.modules.core.ExceptionsManagerModule.showOrThrowError(ExceptionsManagerModule.java:56)
        at com.facebook.react.modules.core.ExceptionsManagerModule.reportFatalException(ExceptionsManagerModule.java:40)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.facebook.react.bridge.JavaMethodWrapper.invoke(JavaMethodWrapper.java:374)
        at com.facebook.react.bridge.JavaModuleWrapper.invoke(JavaModuleWrapper.java:162)
        at com.facebook.react.bridge.queue.NativeRunnable.run(Native Method)
        at android.os.Handler.handleCallback(Handler.java:790)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:31)
        at android.os.Looper.loop(Looper.java:164)
        at com.facebook.react.bridge.queue.MessageQueueThreadImpl$3.run(MessageQueueThreadImpl.java:194)
        at java.lang.Thread.run(Thread.java:764)

Thanks in advance

**Comment by saghul** [comment]
Please ask this question in our community forum: https://community.jitsi.org/ -- we are trying to keep GitHub just for issues that affect Jitsi Meet itself.

**Comment by SaraShafie1991** [comment]
ok i'll post my issue on your community.

thanks in advance

**Comment by saghul** [comment]
Why not?

**Comment by SaraShafie1991** [comment]
can you tell me steps to post as i try but a message is appeared that i must mention at least 2 users or 10 users and i don't know anyone in that community.

**Comment by saghul** [comment]
You can mention @damencho and @saghul .
