### ISSUE TITLE
video not Show : Jitsi Meet quick install

### ISSUE THREAD

**Issue by pzqtinger** [jitsi/jitsi-meet#3578]
Using a quick installation in ubuntn 16.04.3, the web page can be accessed normally, but neither side enters the room to display video, nor local display. What's the problem? The firewall is closed (the firewall can't be accessed when the web page is open), and the log in / var / log / jitsi says access is denied. Is there any problem with the server configuration? Please enlighten me. Thank you.

org.xmpp.component.ComponentException: java.net.ConnectException: Connection refused (Connection refused)
        at org.jivesoftware.whack.ExternalComponent.connect(ExternalComponent.java:296)
        at org.jivesoftware.whack.ExternalComponentManager.addComponent(ExternalComponentManager.java:242)
        at org.jivesoftware.whack.ExternalComponentManager.addComponent(ExternalComponentManager.java:222)
        at org.jitsi.meet.ComponentMain$3.call(ComponentMain.java:315)
        at org.jitsi.meet.ComponentMain$3.call(ComponentMain.java:300)
        at org.jitsi.retry.RetryStrategy$TaskRunner.run(RetryStrategy.java:193)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
Caused by: java.net.ConnectException: Connection refused (Connection refused)
        at java.net.PlainSocketImpl.socketConnect(Native Method)
rg.xmpp.component.ComponentException: java.net.ConnectException: Connection refused (Connection refused)
        at org.jivesoftware.whack.ExternalComponent.connect(ExternalComponent.java:296)
        at org.jivesoftware.whack.ExternalComponentManager.addComponent(ExternalComponentManager.java:242)
        at org.jivesoftware.whack.ExternalComponentManager.addComponent(ExternalComponentManager.java:222)
        at org.jitsi.meet.ComponentMain$3.call(ComponentMain.java:315)
        at org.jitsi.meet.ComponentMain$3.call(ComponentMain.java:300)
        at org.jitsi.retry.RetryStrategy$TaskRunner.run(RetryStrategy.java:193)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
Caused by: java.net.ConnectException: Connection refused (Connection refused)
        at java.net.PlainSocketImpl.socketConnect(Native Method)

**Comment by pzqtinger** [comment]
[jvb.log](https://github.com/jitsi/jitsi-meet/files/2521463/jvb.log)

it is install log,Please help analyze.

**Comment by damencho** [comment]
Can you restart jvb, then jicofo and try again?
/etc/init.d/jitsi-videobridge restart
wait 10 seconds
/etc/init.d/jicofo restart
If that doesn't work upload both jicofo and jvb logs.

**Comment by pzqtinger** [comment]
[jicofo.log](https://github.com/jitsi/jitsi-meet/files/2521469/jicofo.log)
[jvb.log](https://github.com/jitsi/jitsi-meet/files/2521470/jvb.log)
The problem still exists when you retest it in the same way, but the log size hasn't changed, it's still the original log.

![1540616687 1](https://user-images.githubusercontent.com/34857924/47599825-e9072600-d9e8-11e8-9139-e532e5dcd9fb.jpg)
![1540616729 1](https://user-images.githubusercontent.com/34857924/47599830-020fd700-d9e9-11e8-8ff6-10b7bbd6705d.jpg)

**Comment by pzqtinger** [comment]
1、Also: This server does not serve auth.x.x.x.x ....
How does this default generation auto need to be removed?

Include "conf.d/*.cfg.lua"  Where is this heavy View reference?
 /etc/prosody/prosody.cfg.lua  ： It contains files generated during the installation of domain names.
![1540619965 1](https://user-images.githubusercontent.com/34857924/47600235-89ad1400-d9f0-11e8-8974-ec42c89926ef.jpg)

**Comment by damencho** [comment]
> How does this default generation auto need to be removed?
What do you mean?

Does file ` /etc/prosody/prosody.cfg.lua` contain `Include "conf.d/*.cfg.lua"`?

Are there any errors in prosody logs?
