### ISSUE TITLE
XMPPError: remote-server-not-found Jibri - Jisti Meet installation

### ISSUE THREAD

**Issue by andaralex** [jitsi/jitsi-meet#3622]
We have installed the Jitsi Meet and Jibri as per respective document in Ubuntu.

Jitsi Meet - https://github.com/jitsi/jitsi-meet/blob/master/doc/quick-install.md
Jibri - https://github.com/jitsi/jibri

But while enabled the recording and share screen options in the client browser we have error notification like "Recording start failed" and "Screen Sharing fails" respectively. Refer the attached screenshot for frontend error:

![image](https://user-images.githubusercontent.com/922142/49021228-29a8b980-f1b8-11e8-80d7-2ed1c517a2d1.png)

While checking in Ubuntu we got this error - **org.jivesoftware.smack.XMPPException$XMPPErrorException: XMPP error reply received from internal.auth.meet.<domainname>.net: XMPPError: remote-server-not-found - cancel**

**Comment by andaralex** [comment]
Error Log:

2018-11-27 08:35:29.675 INFO: [1] org.jitsi.jibri.api.xmpp.XmppApi.start() The trustAllXmppCerts config is enabled for this domain, all XMPP server provided certificates will be accepted
2018-11-27 08:35:30.117 INFO: [1] class org.jitsi.xmpp.mucclient.MucClient.connected() [prod environment: auth.<domain>@<domain>] Xmpp connection status: connected
2018-11-27 08:35:30.233 INFO: [1] class org.jitsi.xmpp.mucclient.MucClient.authenticated() [prod environment: auth.<domain>@<domain>] Xmpp connection status: authenticated (resume from previous? false)
2018-11-27 08:35:30.297 SEVERE: [1] org.jitsi.jibri.api.xmpp.XmppApi.start() Error connecting to xmpp environment: org.jivesoftware.smack.XMPPException$XMPPErrorException: XMPP error reply received from internal.auth.<domain>: XMPPError: remote-server-not-found - cancel
2018-11-27 08:35:30.366 WARNING: [1] org.glassfish.jersey.internal.inject.Providers.checkProviderRuntime() A provider org.jitsi.jibri.api.http.HttpApi registered in SERVER runtime does not implement any provider interfaces applicable in the SERVER runtime. Due to constraint configuration problems the provider org.jitsi.jibri.api.http.HttpApi will be ignored.

**Comment by bbaldino** [comment]
Are you sure the address of your xmpp server is configured correctly in jibri and that it's reachable by jibri?

**Comment by andaralex** [comment]
@bbaldino,

do you have any reference link, then it easy to help us to configure?

**Comment by andaralex** [comment]
@aaronkvanmeerten,

yes, actually we have configured this domain as per Jibri installation doc. 
The configured domain is internal.auth.<dnsname>

**Comment by aaronkvanmeerten** [comment]
ah ok, so you've just redacted it for these logs?
It does still seem like that's where the issue lies, as the log here indicates:
2018-11-27 08:35:30.297 SEVERE: [1] org.jitsi.jibri.api.xmpp.XmppApi.start() Error connecting to xmpp environment: org.jivesoftware.smack.XMPPException$XMPPErrorException: XMPP error reply received from internal.auth.: XMPPError: remote-server-not-found - cancel

I assume you've got something wrong with either the username/password combination, or else the IP address of the XMPP server isn't properly provided in the config.  
Here's a live example from meet.jit.si 's jibri:  All items in capitals are redacted

{
            // A friendly name for this environment which can be used
            //  for logging, stats, etc.
            "name": "meet-jit-si",
            // The hosts of the XMPP servers to connect to as part of
            //  this environment
            "xmpp_server_hosts": ["IP1", "IP2", "IP3", "IP4", "IP5", "IP6"],
            // The xmpp domain we'll connect to on the XMPP server
            "xmpp_domain": "meet.jit.si",
            // Jibri will login to the xmpp server as a privileged user
            "control_login": {
                // The domain to use for logging in
                "domain": "auth.meet.jit.si",
                // The credentials for logging in
                "username": "JIBRIUSER",
                "password": "JIBRIPASSWORD"
            },
            // Using the control_login information above, Jibri will join
            //  a control muc as a means of announcing its availability
            //  to provide services for a given environment
            "control_muc": {
                "domain": "internal.auth.meet.jit.si",
                "room_name": "JibriBrewery",
                "nickname": "UNIQUEJIBRINICKNAME123"
            },
            // All participants in a call join a muc so they can exchange
            //  information.  Jibri can be instructed to join a special muc
            //  with credentials to give it special abilities (e.g. not being
            //  displayed to other users like a normal participant)
            "call_login": {
                "domain": "RECORDERDOMAIN",
                "username": "RECORDERUSERNAME",
                "password": "RECORDERPASSWORD"
            },
            // When jibri gets a request to start a service for a room, the room
            //  jid will look like:
            //  roomName@optional.prefixes.subdomain.xmpp_domain
            // We'll build the url for the call by transforming that into:
            //  https://xmpp_domain/subdomain/roomName
            // So if there are any prefixes in the jid (like jitsi meet, which
            //  has its participants join a muc at conference.xmpp_domain) then
            //  list that prefix here so it can be stripped out to generate
            //  the call url correctly
            "room_jid_domain_string_to_strip_from_start": "conference.",
            // The amount of time, in minutes, a service is allowed to continue.
            //  Once a service has been running for this long, it will be
            //  stopped (cleanly).  A value of 0 means an indefinite amount
            //  of time is allowed
            "usage_timeout": "7260"
        }

**Comment by andaralex** [comment]
Yes, We have cross-checked multiple times. All the configurations are correctly configured.

Now we got the notification form JItsi as "Preparing for the record the call". But recording not start.

But in the server, we got an error:

8-11-29 07:41:33.467 INFO: [38] org.jitsi.jibri.JibriManager.startFileRecording() Starting a file recording with params: FileRecordingRequestParams(callParams=CallParams(callUrlInfo=CallUrlInfo(baseUrl=https://mobitutor.peopleelement.net, callName=qwsderf, urlParams=[])), sessionId=lvxyngizuuycnyss, callLoginParams=XmppCredentials(domain=recorder.mobitutor.peopleelement.net, username=jibri, password=jibrirecorderpass)) finalize script path: /etc/jitsi/jibri/finalize_recording.sh and recordings directory: /tmp/recordings
2018-11-29 07:41:35.686 INFO: [38] org.openqa.selenium.remote.ProtocolHandshake.createSession() Detected dialect: OSS
2018-11-29 07:41:35.732 FINE: [38] org.jitsi.jibri.capture.ffmpeg.FfmpegCapturer.<init>() Detected os as OS: LINUX
2018-11-29 07:41:35.739 INFO: [38] org.jitsi.jibri.service.impl.FileRecordingJibriService.<init>() Writing recording to /tmp/recordings/lvxyngizuuycnyss
2018-11-29 07:41:35.777 FINE: [38] org.jitsi.jibri.statsd.JibriStatsDClient.incrementCounter() Incrementing statsd counter: start:recording
2018-11-29 07:41:35.780 INFO: [38] org.jitsi.jibri.status.JibriStatusManager.log() Busy status has changed: IDLE -> BUSY
2018-11-29 07:41:35.781 INFO: [38] org.jitsi.jibri.api.xmpp.XmppApi.invoke() Jibri reports its status is now JibriStatus(busyStatus=BUSY, health=OverallHealth(healthStatus=HEALTHY, details={})), publishing presence to connection mobi tutor
2018-11-29 07:41:37.291 FINE: [38] org.jitsi.jibri.selenium.pageobjects.CallPage.visit() Visiting url https://mobitutor.peopleelement.net/qwsderf#config.iAmRecorder=true&config.externalConnectUrl=null&config.startWithAudioMuted=true&config.startWithVideoMuted=true&interfaceConfig.APP_NAME="Jibri"
2018-11-29 07:42:08.866 SEVERE: [38] org.jitsi.jibri.selenium.pageobjects.CallPage.visit() Timed out waiting for call page to load
2018-11-29 07:42:08.872 SEVERE: [38] org.jitsi.jibri.service.impl.FileRecordingJibriService.start() Selenium failed to join the call
2018-11-29 07:42:08.873 FINE: [38] org.jitsi.jibri.statsd.JibriStatsDClient.incrementCounter() Incrementing statsd counter: stop:recording
2018-11-29 07:42:08.873 INFO: [38] org.jitsi.jibri.JibriManager.stopService() Stopping the current service
2018-11-29 07:42:08.874 INFO: [38] org.jitsi.jibri.service.impl.FileRecordingJibriService.stop() Stopping capturer
2018-11-29 07:42:08.874 INFO: [38] org.jitsi.jibri.capture.ffmpeg.executor.FfmpegExecutor.stopFfmpeg() Stopping ffmpeg process
2018-11-29 07:42:08.875 INFO: [38] org.jitsi.jibri.capture.ffmpeg.executor.FfmpegExecutor.stopFfmpeg() Ffmpeg exited with value null
2018-11-29 07:42:08.876 INFO: [38] org.jitsi.jibri.service.impl.FileRecordingJibriService.stop() Quitting selenium
2018-11-29 07:42:08.890 INFO: [38] org.jitsi.jibri.service.impl.FileRecordingJibriService.stop() Participants in this recording: []
2018-11-29 07:42:09.048 INFO: [38] org.jitsi.jibri.selenium.JibriSelenium.leaveCallAndQuitBrowser() Got 12 log entries for type browser
2018-11-29 07:42:09.303 INFO: [38] org.jitsi.jibri.selenium.JibriSelenium.leaveCallAndQuitBrowser() Got 982 log entries for type driver
2018-11-29 07:42:09.550 INFO: [38] org.jitsi.jibri.selenium.JibriSelenium.leaveCallAndQuitBrowser() Got 0 log entries for type client
2018-11-29 07:42:09.551 INFO: [38] org.jitsi.jibri.selenium.JibriSelenium.leaveCallAndQuitBrowser() Leaving web call
2018-11-29 07:42:09.562 INFO: [38] org.jitsi.jibri.selenium.JibriSelenium.leaveCallAndQuitBrowser() Quitting chrome driver
2018-11-29 07:42:09.651 INFO: [38] org.jitsi.jibri.selenium.JibriSelenium.leaveCallAndQuitBrowser() Chrome driver quit
2018-11-29 07:42:09.652 INFO: [38] org.jitsi.jibri.service.impl.FileRecordingJibriService.stop() Finalizing the recording
2018-11-29 07:42:09.666 INFO: [38] org.jitsi.jibri.service.impl.FileRecordingJibriService.finalize() Recording finalize script finished with exit value 0
2018-11-29 07:42:09.667 INFO: [38] org.jitsi.jibri.status.JibriStatusManager.log() Busy status has changed: BUSY -> IDLE
2018-11-29 07:42:09.668 INFO: [38] org.jitsi.jibri.api.xmpp.XmppApi.invoke() Jibri reports its status is now JibriStatus(busyStatus=IDLE, health=OverallHealth(healthStatus=HEALTHY, details={})), publishing presence to connection mobi tutor
2018-11-29 07:42:09.670 FINE: [38] org.jitsi.jibri.statsd.JibriStatsDClient.incrementCounter() Incrementing statsd counter: error:recording
2018-11-29 07:42:09.670 INFO: [38] org.jitsi.jibri.api.xmpp.XmppApi.run() Sending start service response iq: <iq to='jibribrewery@internal.auth.mobitutor.peopleelement.net/focus' id='pw6UO-30' type='set'><jibri xmlns='http://jitsi.org/protocol/jibri' status='off' failure_reason='error'/></iq>

**Comment by bbaldino** [comment]
> 2018-11-29 07:41:37.291 FINE: [38] org.jitsi.jibri.selenium.pageobjects.CallPage.visit() Visiting url https://mobitutor.peopleelement.net/qwsderf#config.iAmRecorder=true&config.externalConnectUrl=null&config.startWithAudioMuted=true&config.startWithVideoMuted=true&interfaceConfig.APP_NAME="Jibri"
> 2018-11-29 07:42:08.866 SEVERE: [38] org.jitsi.jibri.selenium.pageobjects.CallPage.visit() Timed out waiting for call page to load

It looks like Jibri is unable to access your jitsi meet web server (or, at least, it took a very long time to load)

**Comment by andaralex** [comment]
Any idea about which port it's try to connect, we are running Jitsi and Jibri in seperate machine in AWS.

**Comment by andaralex** [comment]
@bbaldino ,
do you have any document for configuration, we have done as per their (Jitsi and Jibri installtion document), but facing problem.

**Comment by bbaldino** [comment]
This is just Jibri's selenium instance trying to access your meeting page (to join so it can capture the audio and video).  The url it's trying to hit is there in the log.  Basically the question is: from the machine which is running Jibri, can you open a browser and access your jitsi-meet url? (https://mobitutor.peopleelement.net/)

**Comment by alexis619** [comment]
@bbaldino  @andaralex @aaronkvanmeerten 

Hi All,

I am getting remote-server-not-found  error. I have attached my logs below. Please check the error and help me to solve the issue.

2018-12-07 11:31:36.877 INFO: [1] org.jitsi.jibri.api.xmpp.XmppApi.start() The trustAllXmppCerts config is enabled for this domain, all XMPP server provided certificates will be accepted
2018-12-07 11:31:37.683 INFO: [1] class org.jitsi.xmpp.mucclient.MucClient.connected() [prod environment: auth.new.mykensho.com@new.mykensho.com] Xmpp connection status: connected
2018-12-07 11:31:37.783 INFO: [1] class org.jitsi.xmpp.mucclient.MucClient.authenticated() [prod environment: auth.new.mykensho.com@new.mykensho.com] Xmpp connection status: authenticated (resume from previous? false)
2018-12-07 11:31:37.832 SEVERE: [1] org.jitsi.jibri.api.xmpp.XmppApi.start() Error connecting to xmpp environment: org.jivesoftware.smack.XMPPException$XMPPErrorException: XMPP error reply received from internal.auth.new.mykensho.com: XMPPError: remote-server-not-found - cancel
2018-12-07 11:31:37.911 WARNING: [1] org.glassfish.jersey.internal.inject.Providers.checkProviderRuntime() A provider org.jitsi.jibri.api.http.HttpApi registered in SERVER runtime does not implement any provider interfaces applicable in the SERVER runtime. Due to constraint configuration problems the provider org.jitsi.jibri.api.http.HttpApi will be ignored.

**Comment by aaronkvanmeerten** [comment]
It appears you are attempting to connect to the internal auth server which is normally only used as part of the username.  You should instead configure jibri to connect to the IP address of the server as specified in my example above.

**Comment by alexis619** [comment]
@aaronkvanmeerten @bbaldino Internal auth server problem solved. But can't able to record video. It shows all recorders are currently busy.

Please help me for recording the video

![jitsi-img](https://user-images.githubusercontent.com/45489319/49683587-a0fe1780-faed-11e8-81f9-3dc5454303e9.PNG)

**Comment by alexis619** [comment]
@bbaldino @aaronkvanmeerten  Now i can able to start recording and but with in fraction of seconds it shows recording failed to start
![recording starts](https://user-images.githubusercontent.com/45489319/49685125-cbf36600-fb03-11e8-8cc0-0ec0d15decc5.PNG)
![recording failed](https://user-images.githubusercontent.com/45489319/49685126-cdbd2980-fb03-11e8-902f-8ed9da25970f.PNG)

.

**Comment by aaronkvanmeerten** [comment]
Check the jibri logs. It's likely it couldn't connect the selenium chrome session.

**Comment by alexis619** [comment]
@aaronkvanmeerten @bbaldino I am attaching my jibri log file. 

Please suggest me how to solve this problem.

[log.0.txt](https://github.com/jitsi/jitsi-meet/files/2659635/log.0.txt)

**Comment by alexis619** [comment]
@aaronkvanmeerten @bbaldino  my jibri logs. Please me to figure out the issue.

######################

2018-12-08 12:01:14.212 INFO: [38] org.jitsi.jibri.status.JibriStatusManager.log() Busy status has changed: IDLE -> BUSY
2018-12-08 12:01:14.212 INFO: [38] org.jitsi.jibri.api.xmpp.XmppApi.invoke() Jibri reports its status is now JibriStatus(busyStatus=BUSY, health=OverallHealth(healthStatus=HEALTHY, details={})), publishing presence to connection prod environment
2018-12-08 12:01:15.870 FINE: [38] org.jitsi.jibri.selenium.pageobjects.CallPage.visit() Visiting url https://new.mykensho.com/lkl#config.iAmRecorder=true&config.externalConnectUrl=null&config.startWithAudioMuted=true&config.startWithVideoMuted=true&interfaceConfig.APP_NAME="Jibri"
2018-12-08 12:01:18.041 INFO: [38] org.jitsi.jibri.selenium.pageobjects.CallPage.visit() Waited 610 milliseconds for call page to load
2018-12-08 12:01:18.109 INFO: [38] org.jitsi.jibri.capture.ffmpeg.executor.FfmpegExecutor.launchFfmpeg() Starting ffmpeg with command ffmpeg -y -v info -f x11grab -draw_mouse 0 -r 30 -s 1280x720 -thread_queue_size 4096 -i :0.0+0,0 -f alsa -thread_queue_size 4096 -i hw:0,1,0 -acodec aac -strict -2 -ar 44100 -c:v libx264 -preset veryfast -profile:v main -level 3.1 -pix_fmt yuv420p -r 30 -crf 25 -g 60 -tune zerolatency -f mp4 /srv/recordings/zwngrwcelzwddbdt/lkl_2018-12-08-12-01-14.mp4 ([ffmpeg, -y, -v, info, -f, x11grab, -draw_mouse, 0, -r, 30, -s, 1280x720, -thread_queue_size, 4096, -i, :0.0+0,0, -f, alsa, -thread_queue_size, 4096, -i, hw:0,1,0, -acodec, aac, -strict, -2, -ar, 44100, -c:v, libx264, -preset, veryfast, -profile:v, main, -level, 3.1, -pix_fmt, yuv420p, -r, 30, -crf, 25, -g, 60, -tune, zerolatency, -f, mp4, /srv/recordings/zwngrwcelzwddbdt/lkl_2018-12-08-12-01-14.mp4])
2018-12-08 12:01:18.127 SEVERE: [38] org.jitsi.jibri.capture.ffmpeg.executor.FfmpegExecutor.isFfmpegHealthy() Ffmpeg is running but doesn't appear to be encoding:
2018-12-08 12:01:19.128 SEVERE: [38] org.jitsi.jibri.capture.ffmpeg.executor.FfmpegExecutor.isFfmpegHealthy() Ffmpeg exited with code 1.  Its most recent output was hw:0,1,0: Input/output error
2018-12-08 12:01:19.129 SEVERE: [38] org.jitsi.jibri.capture.ffmpeg.FfmpegCapturer.start() Ffmpeg already exited
2018-12-08 12:01:19.129 SEVERE: [38] org.jitsi.jibri.capture.ffmpeg.FfmpegCapturer.start() Ffmpeg started up but did not start encoding after 15 tries, giving up
2018-12-08 12:01:19.130 SEVERE: [38] org.jitsi.jibri.service.impl.FileRecordingJibriService.start() Capturer failed to start
2018-12-08 12:01:19.130 FINE: [38] org.jitsi.jibri.statsd.JibriStatsDClient.incrementCounter() Incrementing statsd counter: stop:recording
2018-12-08 12:01:19.130 INFO: [38] org.jitsi.jibri.JibriManager.stopService() Stopping the current service
2018-12-08 12:01:19.131 INFO: [38] org.jitsi.jibri.service.impl.FileRecordingJibriService.stop() Stopping capturer
2018-12-08 12:01:19.131 INFO: [38] org.jitsi.jibri.capture.ffmpeg.executor.FfmpegExecutor.stopFfmpeg() Stopping ffmpeg process
2018-12-08 12:01:19.137 INFO: [38] org.jitsi.jibri.capture.ffmpeg.executor.FfmpegExecutor.stopFfmpeg() Ffmpeg exited with value 1
2018-12-08 12:01:19.137 INFO: [38] org.jitsi.jibri.service.impl.FileRecordingJibriService.stop() Quitting selenium
2018-12-08 12:01:19.158 INFO: [38] org.jitsi.jibri.service.impl.FileRecordingJibriService.stop() Participants in this recording: []
2018-12-08 12:01:19.379 INFO: [38] org.jitsi.jibri.selenium.JibriSelenium.leaveCallAndQuitBrowser() Got 13 log entries for type browser
2018-12-08 12:01:19.529 INFO: [38] org.jitsi.jibri.selenium.JibriSelenium.leaveCallAndQuitBrowser() Got 495 log entries for type driver
2018-12-08 12:01:19.662 INFO: [38] org.jitsi.jibri.selenium.JibriSelenium.leaveCallAndQuitBrowser() Got 0 log entries for type client
2018-12-08 12:01:19.664 INFO: [38] org.jitsi.jibri.selenium.JibriSelenium.leaveCallAndQuitBrowser() Leaving web call
2018-12-08 12:01:19.984 INFO: [38] org.jitsi.jibri.selenium.JibriSelenium.leaveCallAndQuitBrowser() Quitting chrome driver
2018-12-08 12:01:20.076 INFO: [38] org.jitsi.jibri.selenium.JibriSelenium.leaveCallAndQuitBrowser() Chrome driver quit
2018-12-08 12:01:20.076 INFO: [38] org.jitsi.jibri.service.impl.FileRecordingJibriService.stop() Finalizing the recording
2018-12-08 12:01:20.077 SEVERE: [38] org.jitsi.jibri.service.impl.FileRecordingJibriService.finalize() Failed to run finalize script: java.io.IOException: Cannot run program "/path/to/finalize_recording.sh": error=2, No such file or directory with stack:
java.lang.ProcessBuilder.start(ProcessBuilder.java:1048)
org.jitsi.jibri.util.ProcessWrapper.start(ProcessWrapper.kt:79)
org.jitsi.jibri.service.impl.FileRecordingJibriService.finalize(FileRecordingJibriService.kt:235)
org.jitsi.jibri.service.impl.FileRecordingJibriService.stop(FileRecordingJibriService.kt:220)
org.jitsi.jibri.JibriManager.stopService(JibriManager.kt:241)
org.jitsi.jibri.JibriManager.startService(JibriManager.kt:225)
org.jitsi.jibri.JibriManager.startFileRecording(JibriManager.kt:135)
org.jitsi.jibri.api.xmpp.XmppApi.handleStartService(XmppApi.kt:290)
org.jitsi.jibri.api.xmpp.XmppApi.access$handleStartService(XmppApi.kt:72)
org.jitsi.jibri.api.xmpp.XmppApi$handleStartJibriIq$1.run(XmppApi.kt:203)
java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
java.util.concurrent.FutureTask.run(FutureTask.java:266)
java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
java.lang.Thread.run(Thread.java:748)

2018-12-08 12:01:20.081 INFO: [38] org.jitsi.jibri.status.JibriStatusManager.log() Busy status has changed: BUSY -> IDLE
2018-12-08 12:01:20.081 INFO: [38] org.jitsi.jibri.api.xmpp.XmppApi.invoke() Jibri reports its status is now JibriStatus(busyStatus=IDLE, health=OverallHealth(healthStatus=HEALTHY, details={})), publishing presence to connection prod environment
2018-12-08 12:01:20.082 FINE: [38] org.jitsi.jibri.statsd.JibriStatsDClient.incrementCounter() Incrementing statsd counter: error:recording
2018-12-08 12:01:20.086 INFO: [38] org.jitsi.jibri.api.xmpp.XmppApi.run() Sending start service response iq: <iq to='jibribrewery@internal.auth.new.mykensho.com/focus' id='sw1F1-171' type='set'><jibri xmlns='http://jitsi.org/protocol/jibri' status='off' failure_reason='error'/></iq>

**Comment by alexis619** [comment]
@aaronkvanmeerten @bbaldino @tomdee @andaralex 

Please see my above log and Help me for recording the video.

**Comment by bbaldino** [comment]
> 2018-12-08 12:01:19.128 SEVERE: [38] org.jitsi.jibri.capture.ffmpeg.executor.FfmpegExecutor.isFfmpegHealthy() Ffmpeg exited with code 1. Its most recent output was hw:0,1,0: Input/output error

Ffmpeg is unable to access the audio device, I think, so it's likely an alsa setup issue.  Did you follow all the [directions](https://github.com/jitsi/jibri#alsa-and-loopback-device) there?

**Comment by alexis619** [comment]
@bbaldino @aaronkvanmeerten 

Hi bbaldino , thanks for your reply.

I have followed all the steps except this command --> modprobe snd-aloop (getting error):

root@jibri:~#modprobe snd-aloop
modprobe: FATAL: Module snd-aloop not found in directory /lib/modules/4.4.0-1073-aws

I have followed all the steps except this command --> modprobe snd-aloop ()

Please suggest me how to install ALSA and Loopback Device.

Regards,
Alexis

**Comment by aaronkvanmeerten** [comment]
You probably need the kernel extras package specific to the type of kernel you have installed

**Comment by alexis619** [comment]
@bbaldino @aaronkvanmeerten 

I have installed and tried the specific kernel type, but then also it shows same error.

I have followed all the steps except this command --> modprobe snd-aloop (getting error):

root@jibri:~#modprobe snd-aloop
modprobe: FATAL: Module snd-aloop not found in directory /lib/modules/4.4.0-1073-aws

Please suggest me how to install ALSA and Loopback Device.

**Comment by abhijitnathwani** [comment]
Hi @alexis619 and everyone coming here with this error,

> modprobe: FATAL: Module snd-aloop not found in directory /lib/modules/4.4.0-1073-aws

For the above error, please change the kernel to `generic` instead of the `aws`. More steps here:
https://github.com/jitsi/jibri/issues/104#issue-322183843

Abhijit

**Comment by alexis619** [comment]
@bbaldino @aaronkvanmeerten, I am having my own jitsi server in Sydney region in aws. But person1 from australia and person2 from india tries to have desktop sharing and its works fine for 5 mins. And person1 in australia gets a bandwidth connectivity issue , please help me to rectify and solve the issue.

**Comment by alexis619** [comment]
@bbaldino @aaronkvanmeerten, how to add the secondary videobridge to the main  jitsi-meet server. Please help me to resolve this issue.

**Comment by richhamseth** [comment]
Hi, I launched jibri server I can see logs like this can any able to help with this
 
2020-06-16 08:16:00.161 INFO: [1] org.jitsi.jibri.Main.main() Jibri run with args [--config, /etc/jitsi/jibri/config.json]
2020-06-16 08:16:00.173 INFO: [1] org.jitsi.jibri.Main.main() Using config file /etc/jitsi/jibri/config.json
2020-06-16 08:16:00.173 INFO: [1] org.jitsi.jibri.Main.main() Using port 3333 for internal HTTP API
2020-06-16 08:16:00.173 INFO: [1] org.jitsi.jibri.Main.main() Using port 2222 for the HTTP API
2020-06-16 08:16:00.953 INFO: [1] org.jitsi.jibri.Main.loadConfig() Parsed config:
JibriConfig(recordingDirectory=/srv/recordings, singleUseMode=false, enabledStatsD=true, finalizeRecordingScriptPath=/path/to/finalize_recording.sh, xmppEnvironments=[XmppEnvironmentConfig(name=prod environment, xmppServerHosts=[video.live], xmppDomain=video.live, controlLogin=XmppCredentials(domain=auth.video.live, username=jibri, password=jibriauthpass), controlMuc=XmppMuc(domain=internal.auth.video.live, roomName=jibribrewery, nickname=jibri-nickname), sipControlMuc=null, callLogin=XmppCredentials(domain=recorder.video.live, username=recorder, password=jibrirecorderpass), stripFromRoomDomain=conference., usageTimeoutMins=0, trustAllXmppCerts=true)])
2020-06-16 08:16:01.553 WARNING: [1] org.glassfish.jersey.internal.inject.Providers.checkProviderRuntime() A provider org.jitsi.jibri.api.http.internal.InternalHttpApi registered in SERVER runtime does not implement any provider interfaces applicable in the SERVER runtime. Due to constraint configuration problems the provider org.jitsi.jibri.api.http.internal.InternalHttpApi will be ignored.
2020-06-16 08:16:01.844 INFO: [1] org.jitsi.jibri.api.xmpp.XmppApi.updatePresence() Jibri reports its status is now JibriStatus(busyStatus=IDLE, health=OverallHealth(healthStatus=HEALTHY, details={})), publishing presence to connections
2020-06-16 08:16:01.847 INFO: [1] org.jitsi.xmpp.mucclient.MucClientManager.log() Setting a presence extension: org.jitsi.xmpp.extensions.jibri.JibriStatusPacketExt@771158fb
2020-06-16 08:16:01.855 INFO: [1] org.jitsi.jibri.api.xmpp.XmppApi.start() Connecting to xmpp environment on video.live with config XmppEnvironmentConfig(name=prod environment, xmppServerHosts=[video.live], xmppDomain=video.live, controlLogin=XmppCredentials(domain=auth.video.live, username=jibri, password=jibriauthpass), controlMuc=XmppMuc(domain=internal.auth.video.live, roomName=jibribrewery, nickname=jibri-nickname), sipControlMuc=null, callLogin=XmppCredentials(domain=recorder.video.live, username=recorder, password=jibrirecorderpass), stripFromRoomDomain=conference., usageTimeoutMins=0, trustAllXmppCerts=true)
2020-06-16 08:16:01.856 INFO: [1] org.jitsi.jibri.api.xmpp.XmppApi.start() The trustAllXmppCerts config is enabled for this domain, all XMPP server provided certificates will be accepted
2020-06-16 08:16:01.883 WARNING: [19] org.jitsi.xmpp.mucclient.MucClient.log() Disabling certificate verification!
2020-06-16 08:16:01.973 WARNING: [1] org.glassfish.jersey.internal.inject.Providers.checkProviderRuntime() A provider org.jitsi.jibri.api.http.HttpApi registered in SERVER runtime does not implement any provider interfaces applicable in the SERVER runtime. Due to constraint configuration problems the provider org.jitsi.jibri.api.http.HttpApi will be ignored.
2020-06-16 08:16:02.452 INFO: [19] org.jitsi.xmpp.mucclient.MucClient.log() [MucClient id=video.live hostname=video.live] connected
2020-06-16 08:16:02.560 SEVERE: [19] org.jivesoftware.smack.AbstractXMPPConnection.callConnectionAuthenticatedListener() Exception in authenticated listener
java.lang.RuntimeException: org.jivesoftware.smack.XMPPException$XMPPErrorException: XMPP error reply received from jibribrewery@internal.auth.video.live/jibri-nickname: XMPPError: internal-server-error - wait
        at org.jitsi.xmpp.mucclient.MucClient$1.authenticated(MucClient.java:220)
        at org.jivesoftware.smack.AbstractXMPPConnection.callConnectionAuthenticatedListener(AbstractXMPPConnection.java:1297)
        at org.jivesoftware.smack.AbstractXMPPConnection.afterSuccessfulLogin(AbstractXMPPConnection.java:572)
        at org.jivesoftware.smack.tcp.XMPPTCPConnection.afterSuccessfulLogin(XMPPTCPConnection.java:379)
        at org.jivesoftware.smack.tcp.XMPPTCPConnection.loginInternal(XMPPTCPConnection.java:444)
        at org.jivesoftware.smack.AbstractXMPPConnection.login(AbstractXMPPConnection.java:491)
        at org.jivesoftware.smack.AbstractXMPPConnection.login(AbstractXMPPConnection.java:448)
        at org.jitsi.xmpp.mucclient.MucClient.initializeConnectAndJoin(MucClient.java:277)
        at org.jitsi.xmpp.mucclient.MucClientManager.lambda$addMucClient$0(MucClientManager.java:152)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
Caused by: org.jivesoftware.smack.XMPPException$XMPPErrorException: XMPP error reply received from jibribrewery@internal.auth.video.live/jibri-nickname: XMPPError: internal-server-error - wait
        at org.jivesoftware.smack.XMPPException$XMPPErrorException.ifHasErrorThenThrow(XMPPException.java:132)
        at org.jivesoftware.smack.StanzaCollector.nextResultOrThrow(StanzaCollector.java:263)
        at org.jivesoftware.smackx.muc.MultiUserChat.enter(MultiUserChat.java:355)
        at org.jivesoftware.smackx.muc.MultiUserChat.createOrJoin(MultiUserChat.java:498)
        at org.jivesoftware.smackx.muc.MultiUserChat.createOrJoin(MultiUserChat.java:444)
        at org.jitsi.xmpp.mucclient.MucClient$MucWrapper.join(MucClient.java:557)
        at org.jitsi.xmpp.mucclient.MucClient$MucWrapper.access$400(MucClient.java:486)
        at org.jitsi.xmpp.mucclient.MucClient.joinMucs(MucClient.java:301)
        at org.jitsi.xmpp.mucclient.MucClient.access$100(MucClient.java:47)
        at org.jitsi.xmpp.mucclient.MucClient$1.authenticated(MucClient.java:216)
        ... 11 more

**Comment by bbaldino** [comment]
@richhamseth I'd start a thread at community.jitsi.org

**Comment by aninditasadhukhan** [comment]
Hi @saghul @bbaldino @aaronkvanmeerten, Can you please help me on a error I am getting in jibri log.0.txt.
The BaseUrl should be baseUrl=https://xmppdemo.domain.com in my case but here it is "baseUrl=https://xmppdemo.domain.com/conference"

I have added below variable in .env file inside docker container
JIBRI_STRIP_DOMAIN_JID=conference.

Also when trying to start recording, it is showing 
 Focus request for room: testjibri@conference.conference.xmppdemo.domain.com

But it should be  Focus request for room: testjibri@conference.xmppdemo.domain.com

Please let me know how can I resolve this?
