### ISSUE TITLE
Let's Encrypt shell script strange error

### ISSUE THREAD

**Issue by kkar** [jitsi/jitsi-meet#3836]
By executing `/usr/share/jitsi-meet/scripts/install-letsencrypt-cert.sh` after entering my e-mail, i get the following error. Does anyone face the same issue?

```
root@h2782615:~# /usr/share/jitsi-meet/scripts/install-letsencrypt-cert.sh
-------------------------------------------------------------------------
This script will:
- Need a working DNS record pointing to this machine(for domain conference.think-free.net)
- Download certbot-auto from https://dl.eff.org to /usr/local/sbin
- Install additional dependencies in order to request Let’s Encrypt certificate
- If running with jetty serving web content, will stop Jitsi Videobridge
- Configure and reload nginx or apache2, whichever is used

You need to agree to the ACME server's Subscriber Agreement (https://letsencrypt.org/documents/LE-SA-v1.1.1-August-1-2016.pdf)
by providing an email address for important account notifications
Enter your email and press [ENTER]: cdoctor2015@gmail.com
Bootstrapping dependencies for Debian-based OSes... (you can skip this with --no-bootstrap)
OK:1 ftp://ftp.stratoserver.net/pub/linux/ubuntu bionic InRelease
OK:2 ftp://ftp.stratoserver.net/pub/linux/ubuntu bionic-updates InRelease
OK:3 ftp://ftp.stratoserver.net/pub/linux/ubuntu bionic-security InRelease
OK:4 https://download.jitsi.org stable/ InRelease
Paketlisten werden gelesen... Fertig
Paketlisten werden gelesen... Fertig
Abhängigkeitsbaum wird aufgebaut.
Statusinformationen werden eingelesen.... Fertig
augeas-lenses ist schon die neueste Version (1.10.1-2).
ca-certificates ist schon die neueste Version (20180409).
libaugeas0 ist schon die neueste Version (1.10.1-2).
libffi-dev ist schon die neueste Version (3.2.1-8).
python ist schon die neueste Version (2.7.15~rc1-1).
python-dev ist schon die neueste Version (2.7.15~rc1-1).
python-virtualenv ist schon die neueste Version (15.1.0+ds-1.1).
virtualenv ist schon die neueste Version (15.1.0+ds-1.1).
gcc ist schon die neueste Version (4:7.3.0-3ubuntu2.1).
libssl-dev ist schon die neueste Version (1.1.0g-2ubuntu4.3).
openssl ist schon die neueste Version (1.1.0g-2ubuntu4.3).
0 aktualisiert, 0 neu installiert, 0 zu entfernen und 0 nicht aktualisiert.
Creating virtual environment...
Installing Python packages...
Command "/opt/eff.org/certbot/venv/bin/python2.7 -u -c "import setuptools, tokenize;__file__='/tmp/pip-qAnz7G-build/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-LSxN4C-record/install-record.txt --single-version-externally-managed --compile --install-headers /opt/eff.org/certbot/venv/include/site/python2.7/wheel" failed with error code 1 in /tmp/pip-qAnz7G-build/
Traceback (most recent call last):
  File "/tmp/tmp.DTNS6OYQ5I/pipstrap.py", line 177, in <module>
    exit(main())
  File "/tmp/tmp.DTNS6OYQ5I/pipstrap.py", line 164, in main
    shell=True)
  File "/usr/lib/python2.7/subprocess.py", line 223, in check_output
    raise CalledProcessError(retcode, cmd, output=output)
subprocess.CalledProcessError: Command 'pip install --no-index --no-deps -U --no-cache-dir /tmp/pipstrap-TQyfq0/pip-9.0.1.tar.gz /tmp/pipstrap-TQyfq0/setuptools-29.0.1.tar.gz /tmp/pipstrap-TQyfq0/wheel-0.29.0.tar.gz' returned non-zero exit status 1
root@h2782615:~#
```

**Comment by JReming85** [comment]
First you might want to edit your email address out of there.

Second looks like pip is giving an error, is it installed and does it work?
