### ISSUE TITLE
No audio/video 

### ISSUE THREAD

**Issue by HKApitech** [jitsi/jitsi-meet#384]
Hi Everyone,

I've just installed Jitsi-meet on a new Debian server. When I start a new conference the chat works well and I can see participants' names but  I can't see or hear them (webcam and audio not working). I get this error "OperationFailedException: ICE failed" in /var/log/jitsi/jvb.log : 

2015-10-09 16:11:08.448 SEVERE: [102] util.UtilActivator.uncaughtException().119 An uncaught exception occurred in thread=Thread[org.jitsi.videobridge.SctpConnection-pool-5-thread-17,5,main] and message was: Could not initialize class org.jitsi.sctp4j.Sctp
java.lang.NoClassDefFoundError: Could not initialize class org.jitsi.sctp4j.Sctp
	at org.jitsi.videobridge.SctpConnection$1.run(SctpConnection.java:454)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1146)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:701)
2015-10-09 16:11:11.439 INFO: [103] org.ice4j.ice.Agent.setState() ICE state changed from Completed to Terminated
2015-10-09 16:11:11.439 INFO: [103] org.jitsi.videobridge.IceUdpTransportManager.info() ICE processing state of IceUdpTransportManager #476df8d0 (for channels dfa54c0c898fed9f 2e83ae9229ee9a0c c14abec1347d547)  of conference c0253feb801b55f5 changed from Completed to Terminated.
2015-10-09 16:11:13.748 INFO: [43] org.jitsi.videobridge.xmpp.ComponentImpl.info() RECV: <iq id="sbfxx-8713" type="result" to="jitsi-videobridge.gipsy-ida01.ida.melanie2.i2" from="gipsy-ida01.ida.melanie2.i2"/>
2015-10-09 16:11:14.499 INFO: [104] org.ice4j.ice.ConnectivityCheckClient.processTimeout() timeout for pair: 192.168.251.48:10012/udp/host -> 172.24.0.67:58019/udp/host (stream.RTP), failing.
2015-10-09 16:11:14.499 INFO: [104] org.ice4j.ice.ConnectivityCheckClient.updateCheckListAndTimerStates() CheckList will failed in a few seconds if nosucceeded checks come
2015-10-09 16:11:19.500 INFO: [105] org.ice4j.ice.ConnectivityCheckClient.run() CheckList for stream stream FAILED
2015-10-09 16:11:19.500 INFO: [105] org.ice4j.ice.Agent.checkListStatesUpdated() ICE state is FAILED
2015-10-09 16:11:19.500 INFO: [105] org.ice4j.ice.Agent.setState() ICE state changed from Running to Failed
2015-10-09 16:11:19.500 INFO: [105] org.jitsi.videobridge.IceUdpTransportManager.info() ICE processing state of IceUdpTransportManager #7b4b91c4 (for channels 5393a10082fcd105 bde10fdb24ac4564 193cd869cbf28e9)  of conference c0253feb801b55f5 changed from Running to Failed.
2015-10-09 16:11:19.500 INFO: [106] org.jitsi.videobridge.IceUdpTransportManager.info() Failed to connect IceUdpTransportManager: net.java.sip.communicator.service.protocol.OperationFailedException: ICE failed

Help please!

**Comment by HKApitech** [comment]
SOLVED.

Solution here:  http://lists.jitsi.org/pipermail/users/2015-September/010064.html
