### ISSUE TITLE
jitsi meet andriod craches with pre-build SDK 

### ISSUE THREAD

**Issue by yassineberradi** [jitsi/jitsi-meet#3933]
In my andriod app i used jitsi meet prebuild sdk, adding the following in the app/build.gradle:
allprojects {
    repositories {
        google()
        jcenter()
        maven {
            url "https://github.com/jitsi/jitsi-maven-repository/raw/master/releases"
        }
    }
}
//
dependencies {
    // (other dependencies)
    implementation ('org.jitsi.react:jitsi-meet-sdk:+') { transitive = true }
}
//
android {
    ...
    defaultConfig {
        ndk {
            abiFilters "armeabi-v7a", "x86"
        }
    }

tha app crashes with the following error:

 02-27 08:48:09.476 30284-30321/com.example.myapplication E/ReactNativeJS: Java exception in 'NativeModules'
    
    java.lang.NoClassDefFoundError: android.telecom.CallAudioState
02-27 08:48:09.496 30284-30321/com.example.myapplication E/ReactNativeJS: Module AppRegistry is not a registered callable module (calling runApplication)
02-27 08:48:09.500 30284-30322/com.example.myapplication E/AndroidRuntime: FATAL EXCEPTION: mqt_native_modules
    Process: com.example.myapplication, PID: 30284
    com.facebook.react.common.JavascriptException: Java exception in 'NativeModules'
    
    java.lang.NoClassDefFoundError: android.telecom.CallAudioState, stack:
    libcore.reflect.InternalNames.getClass@55
    java.lang.Class.getDexCacheType@479
    java.lang.reflect.ArtMethod.getDexCacheType@191
    java.lang.reflect.ArtMethod.getParameterTypes@136
    java.lang.reflect.Method.getParameterTypes@174
    java.lang.Class.getDeclaredMethods@772
    com.facebook.react.bridge.JavaModuleWrapper.findMethods@88
    com.facebook.react.bridge.JavaModuleWrapper.getMethodDescriptors@118
    android.os.Handler.handleCallback@739
    android.os.Handler.dispatchMessage@95
    com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage@29
    <unknown>@1043:340
    v@2:1483
    <unknown>@1042:276
    v@2:1483
    <unknown>@1041:194
    v@2:1483
    <unknown>@1040:85
    v@2:1483
    <unknown>@971:312
    v@2:1483
    <unknown>@970:85
    v@2:1483
    <unknown>@343:240
    v@2:1483
    <unknown>@12:184
    v@2:1483
    <unknown>@11:30
    v@2:1483
    d@2:866
    global code@1433:4
    
        at com.facebook.react.modules.core.ExceptionsManagerModule.showOrThrowError(ExceptionsManagerModule.java:54)
        at com.facebook.react.modules.core.ExceptionsManagerModule.reportFatalException(ExceptionsManagerModule.java:38)
        at java.lang.reflect.Method.invoke(Native Method)
        at java.lang.reflect.Method.invoke(Method.java:372)
        at com.facebook.react.bridge.JavaMethodWrapper.invoke(JavaMethodWrapper.java:372)
        at com.facebook.react.bridge.JavaModuleWrapper.invoke(JavaModuleWrapper.java:160)
        at com.facebook.react.bridge.queue.NativeRunnable.run(Native Method)
        at android.os.Handler.handleCallback(Handler.java:739)
        at android.os.Handler.dispatchMessage(Handler.java:95)
        at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:29)
        at android.os.Looper.loop(Looper.java:135)
        at com.facebook.react.bridge.queue.MessageQueueThreadImpl$3.run(MessageQueueThreadImpl.java:192)
        at java.lang.Thread.run(Thread.java:818)
02-27 08:48:09.891 30284-30284/com.example.myapplication D/ReactNative: ReactInstanceManager.detachViewFromInstance()
02-27 08:48:09.897 30284-30321/com.example.myapplication E/ReactNativeJS: Module AppRegistry is not a registered callable module (calling unmountApplicationComponentAtRootTag)
02-27 08:53:09.534 30284-30322/com.example.myapplication I/Process: Sending signal. PID: 30284 SIG: 9

**Comment by emilykag** [comment]
Same problem here. I solved it by downgrading jitsi to 1.16.0

**Comment by emilykag** [comment]
However please solve the issue. It happens in android 5

**Comment by saghul** [comment]
https://github.com/jitsi/jitsi-meet/issues/3940#issuecomment-473256771

**Comment by saghul** [comment]
Upodated the 1.21 artifacts with a fix.
