### ISSUE TITLE
[Android] [SDK 2.0] Impossible to leave conference room, Android TV app crash on leave or finish()

### ISSUE THREAD

**Issue by andres934** [jitsi/jitsi-meet#4116]
## Description
--- 2019-04-22 13:57:39.327 I/ReactNativeJS: '[__filename]', '<l>: ', 'redux state persisted. 720c45bab74b75b35aa402846f5ac3d7 -> 9bb768f3b644454cfdcef7a159a10c50'
2019-04-22 13:57:39.359 W/ReactNativeJS: '[__filename]', '<l>: ', 'PLAY_SOUND: no sound found for id: PARTICIPANT_LEFT_SOUND'
2019-04-22 13:57:39.370 E/ReactNativeJS: '[__filename]', '<l>: ', '_REMOVE_AUDIO_ELEMENT: no sound for id: PARTICIPANT_JOINED_SOUND'
2019-04-22 13:57:39.396 E/ReactNativeJS: '[__filename]', '<l>: ', '_REMOVE_AUDIO_ELEMENT: no sound for id: PARTICIPANT_LEFT_SOUND'
2019-04-22 13:57:39.399 E/ReactNativeJS: '[__filename]', '<l>: ', '_REMOVE_AUDIO_ELEMENT: no sound for id: INCOMING_MSG_SOUND'
2019-04-22 13:57:39.416 E/AndroidRuntime: FATAL EXCEPTION: mqt_native_modules
    Process: com.sivsa.omni, PID: 26208
    com.facebook.react.bridge.NoSuchKeyException: lineNumber
        at com.facebook.react.bridge.ReadableNativeMap.getValue(SourceFile:124)
        at com.facebook.react.bridge.ReadableNativeMap.getValue(SourceFile:128)
        at com.facebook.react.bridge.ReadableNativeMap.getInt(SourceFile:182)
        at com.facebook.react.util.JSStackTrace.format(SourceFile:28)
        at com.facebook.react.modules.core.ExceptionsManagerModule.reportSoftException(SourceFile:46)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.facebook.react.bridge.JavaMethodWrapper.invoke(SourceFile:372)
        at com.facebook.react.bridge.JavaModuleWrapper.invoke(SourceFile:158)
        at com.facebook.react.bridge.queue.NativeRunnable.run(Native Method)
        at android.os.Handler.handleCallback(Handler.java:789)
        at android.os.Handler.dispatchMessage(Handler.java:98)
        at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(SourceFile:29)
        at android.os.Looper.loop(Looper.java:164)
        at com.facebook.react.bridge.queue.MessageQueueThreadImpl$4.run(SourceFile:232)
        at java.lang.Thread.run(Thread.java:764)
2019-04-22 13:57:39.421 E/ReactNativeJS: '[__filename]', '<l>: ', '_REMOVE_AUDIO_ELEMENT: no sound for id: RECORDING_OFF_SOUND'
2019-04-22 13:57:39.424 E/ReactNativeJS: '[__filename]', '<l>: ', '_REMOVE_AUDIO_ELEMENT: no sound for id: RECORDING_ON_SOUND'

## Current behavior
--- Joining to conference perfectly, on trying to quit conference, using red quit button, using jitsiView.leave() or finish() programmatically, the app crash throwing the above logs

## Expected Behavior
--- Quit conference without crashing

## Possible Solution
--- No idea, already tried everything

## Steps to reproduce
--- in my case joining conference and then quiting manually (jitsiView.leave() or finish())

# Environment details
--- Nvidia shield Android Tv 8.0.0

**Comment by saghul** [comment]
Did you build the SDK yourself or are you using our maven repo?

**Comment by andres934** [comment]
i'm using the maven repo

**Comment by saghul** [comment]
Do you have a test repository I can try? (I'll have to use a simulator since I have no access to an Android TV device).

**Comment by andres934** [comment]
i already fixed that react bug, was a proguard issue, but now i'm getting error on getJitsiView(), is trying to return null when is not null (I'm using kotlin), could you maybe make that getJitsiView() a @Nullable? to be kotlin friendly :)

**Comment by saghul** [comment]
@andres934 Sure, I'd take a PR, are you up for writing one?

PS: I tested a sample app with an Android TV 8.0 simulator and it worked ok.
