### ISSUE TITLE
React-Native app crash from android

### ISSUE THREAD

**Issue by MeghsP** [jitsi/jitsi-meet#4269]
Hi,

I am using jitsi-meet to implement video conference in my react native app. I implement whole Android things for jitsi-meet in android and then accessing that code from react native. I didn't find any react native specific library of jitsi-meet. 

However, I found [react-native-jitsi-meet](https://www.npmjs.com/package/react-native-jitsi-meet) and also tried implementing that but no luck. [react-native-jitsi-meet](https://www.npmjs.com/package/react-native-jitsi-meet) is also giving me error which I posted [here](https://github.com/skrafft/react-native-jitsi-meet/issues/33). 

For testing purpose, I also made new android app(not react-native), added all the dependencies and permission as given in official document of jitsi-meet and everything works fine just for android.

Now I am accessing that same working code from my existing android app to react-native. Here again no luck and app is being crashed every time I call jitsi-meet classes. For my existing app, I have also posted issue [here](https://github.com/jitsi/jitsi-meet/issues/4265).

So I figured it out that it might have some issue with integration with react-native app.

Now for further testing, I have made new react-native app and what I am doing is implementing whole code in android and then accessing that code from react-native app. This again gives me error and my app is being crashed.

Here is the error:
`E/Parcel: Class not found when unmarshalling: org.jitsi.meet.sdk.JitsiMeetConferenceOptions
    java.lang.ClassNotFoundException: org.jitsi.meet.sdk.JitsiMeetConferenceOptions
        at java.lang.Class.classForName(Native Method)
        at java.lang.Class.forName(Class.java:453)
        at android.os.Parcel.readParcelableCreator(Parcel.java:2843)
        at android.os.Parcel.readParcelable(Parcel.java:2797)
        at android.os.Parcel.readValue(Parcel.java:2700)
        at android.os.Parcel.readArrayMapInternal(Parcel.java:3067)
        at android.os.BaseBundle.unparcel(BaseBundle.java:257)
        at android.os.BaseBundle.getString(BaseBundle.java:1086)
        at android.content.Intent.getStringExtra(Intent.java:7718)
        at com.android.server.am.ActivityStarter.startActivity(ActivityStarter.java:468)
        at com.android.server.am.ActivityStarter.startActivityLocked(ActivityStarter.java:419)
        at com.android.server.am.ActivityStarter.startActivityMayWait(ActivityStarter.java:1308)
        at com.android.server.am.ActivityManagerService.startActivityAsUser(ActivityManagerService.java:6147)
        at com.android.server.am.ActivityManagerService.startActivity(ActivityManagerService.java:5999)
        at android.app.IActivityManager$Stub.onTransact(IActivityManager.java:121)
        at com.android.server.am.ActivityManagerService.onTransact(ActivityManagerService.java:3955)
        at android.os.Binder.execTransact(Binder.java:682)
     Caused by: java.lang.ClassNotFoundException: org.jitsi.meet.sdk.JitsiMeetConferenceOptions
        at java.lang.Class.classForName(Native Method)
        at java.lang.BootClassLoader.findClass(ClassLoader.java:1355)
        at java.lang.BootClassLoader.loadClass(ClassLoader.java:1415)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
        at java.lang.Class.classForName(Native Method) 
        at java.lang.Class.forName(Class.java:453) 
        at android.os.Parcel.readParcelableCreator(Parcel.java:2843) 
        at android.os.Parcel.readParcelable(Parcel.java:2797) 
        at android.os.Parcel.readValue(Parcel.java:2700) 
        at android.os.Parcel.readArrayMapInternal(Parcel.java:3067) 
        at android.os.BaseBundle.unparcel(BaseBundle.java:257) 
        at android.os.BaseBundle.getString(BaseBundle.java:1086) 
        at android.content.Intent.getStringExtra(Intent.java:7718) 
        at com.android.server.am.ActivityStarter.startActivity(ActivityStarter.java:468) 
        at com.android.server.am.ActivityStarter.startActivityLocked(ActivityStarter.java:419) 
        at com.android.server.am.ActivityStarter.startActivityMayWait(ActivityStarter.java:1308) 
        at com.android.server.am.ActivityManagerService.startActivityAsUser(ActivityManagerService.java:6147) 
        at com.android.server.am.ActivityManagerService.startActivity(ActivityManagerService.java:5999) 
        at android.app.IActivityManager$Stub.onTransact(IActivityManager.java:121) 
        at com.android.server.am.ActivityManagerService.onTransact(ActivityManagerService.java:3955) 
        at android.os.Binder.execTransact(Binder.java:682) 
     Caused by: java.lang.NoClassDefFoundError: Class not found using the boot class loader; no stack trace available
`

```
E/ANDR-PERF-MPCTL: Invalid profile no. 0, total profiles 0 only
2019-05-24 17:52:00.651 5417-5821/? E/ANDR-PERF-JNI: com_qualcomm_qtiperformance_native_perf_io_prefetch_start
2019-05-24 17:52:00.652 5417-5821/? E/ANDR-IOP: IOP HAL: Received pkg_name = com.apitestdemo pid = 5166
2019-05-24 17:52:00.652 5417-5821/? E/ANDR-IOP: event data pool ran empty
2019-05-24 17:52:00.926 4151-4151/? E/audit: type=1400 audit(1558700520.918:20141): avc:  denied  { dac_override } for  pid=7033 comm="kworker/0:1" capability=1  scontext=u:r:kernel:s0 tcontext=u:r:kernel:s0 tclass=capability permissive=0 SEPF_SM-C900F_8.0.0_0017 audit_filtered
2019-05-24 17:52:00.998 5166-11687/com.apitestdemo E/ReactNativeJS: Application App has not been registered.
    
    Hint: This error often happens when you're running the packager (local dev server) from a wrong folder. For example you have multiple apps and the packager is still running for the app you were working on before.
    If this is the case, simply kill the old packager instance (e.g. close the packager terminal window) and start the packager in the correct app folder (e.g. cd into app folder and run 'npm start').
    
    This error can also happen due to a require() error during initialization or failure to call AppRegistry.registerComponent.
2019-05-24 17:52:01.013 5166-11688/com.apitestdemo E/AndroidRuntime: FATAL EXCEPTION: mqt_native_modules
    Process: com.apitestdemo, PID: 5166
    com.facebook.react.common.JavascriptException: Application App has not been registered.
    
    Hint: This error often happens when you're running the packager (local dev server) from a wrong folder. For example you have multiple apps and the packager is still running for the app you were working on before.
    If this is the case, simply kill the old packager instance (e.g. close the packager terminal window) and start the packager in the correct app folder (e.g. cd into app folder and run 'npm start').
    
    This error can also happen due to a require() error during initialization or failure to call AppRegistry.registerComponent.
    
    , stack:
    runApplication@327:1375
    value@25:3449
    <unknown>@25:960
    value@25:2703
    value@25:932
    
        at com.facebook.react.modules.core.ExceptionsManagerModule.showOrThrowError(ExceptionsManagerModule.java:54)
        at com.facebook.react.modules.core.ExceptionsManagerModule.reportFatalException(ExceptionsManagerModule.java:38)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.facebook.react.bridge.JavaMethodWrapper.invoke(JavaMethodWrapper.java:372)
        at com.facebook.react.bridge.JavaModuleWrapper.invoke(JavaModuleWrapper.java:158)
        at com.facebook.react.bridge.queue.NativeRunnable.run(Native Method)
        at android.os.Handler.handleCallback(Handler.java:789)
        at android.os.Handler.dispatchMessage(Handler.java:98)
        at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:29)
        at android.os.Looper.loop(Looper.java:164)
        at com.facebook.react.bridge.queue.MessageQueueThreadImpl$3.run(MessageQueueThreadImpl.java:192)
        at java.lang.Thread.run(Thread.java:764)

```

What I noticed till now is that it has some issue with Registry.registerComponent(). It requires some specific component there because I register my own app(component) in react native and my app is just working fine. Issue is only when I call jitsi-meet classes.

Here is the android code I am calling from react-native:

```
@ReactMethod
    public void initializeJitsi(final Callback callback) {
        Log.e("JitsiManager","initializeJitsi called");
        URL serverURL;
        try {
            serverURL = new URL("https://meet.jit.si");
        } catch (MalformedURLException e) {
            e.printStackTrace();
            throw new RuntimeException("Invalid server URL!");
        }
        JitsiMeetConferenceOptions defaultOptions
                = new JitsiMeetConferenceOptions.Builder()
                .setServerURL(serverURL)
                .setWelcomePageEnabled(true)
                .build();
        JitsiMeet.setDefaultConferenceOptions(defaultOptions);
        new Handler().postDelayed(new Runnable() {
            @Override
            public void run() {
                Log.e("JitsiManager","initializeJitsi launch called");
                JitsiMeetConferenceOptions options
                        = new JitsiMeetConferenceOptions.Builder()
                        .setRoom("MeghsP")
                        .build();
                JitsiMeetActivity.launch(getCurrentActivity(), options);
            }
        },5000);

    }

```
`
Here is my app level build.gradle:

```
apply plugin: "com.android.application"

import com.android.build.OutputFile

project.ext.react = [
    entryFile: "index.js"
]

apply from: "../../node_modules/react-native/react.gradle"

def enableSeparateBuildPerCPUArchitecture = false

def enableProguardInReleaseBuilds = false

android {
    compileSdkVersion rootProject.ext.compileSdkVersion
    buildToolsVersion '28.0.3'

    defaultConfig {
        applicationId "com.apitestdemo"
        minSdkVersion rootProject.ext.minSdkVersion
        targetSdkVersion rootProject.ext.targetSdkVersion
        versionCode 1
        versionName "1.0"
    }
    splits {
        abi {
            reset()
            enable enableSeparateBuildPerCPUArchitecture
            universalApk false  // If true, also generate a universal APK
            include "armeabi-v7a", "x86", "arm64-v8a"
        }
    }
    buildTypes {
        release {
            minifyEnabled enableProguardInReleaseBuilds
            proguardFiles getDefaultProguardFile("proguard-android.txt"), "proguard-rules.pro"
        }
    }
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }
    applicationVariants.all { variant ->
        variant.outputs.each { output ->
            def versionCodes = ["armeabi-v7a":1, "x86":2, "arm64-v8a": 3]
            def abi = output.getFilter(OutputFile.ABI)
            if (abi != null) {  // null for the universal-debug, universal-release variants
                output.versionCodeOverride =
                        versionCodes.get(abi) * 1048576 + defaultConfig.versionCode
            }
        }
    }
}

dependencies {
    implementation fileTree(dir: "libs", include: ["*.jar"])
    implementation "com.android.support:appcompat-v7:${rootProject.ext.supportLibVersion}"
    implementation ("com.facebook.react:react-native:0.58.3"){
        force = true
    }  // From node_modules
    implementation ('org.jitsi.react:jitsi-meet-sdk:2.+') {
        transitive = true
    }
}
task copyDownloadableDepsToLibs(type: Copy) {
    from configurations.compile
    into 'libs'
}`
```

Here is my project level build.gradle:

```
buildscript {
    ext {
        buildToolsVersion = "28.0.2"
        minSdkVersion = 21
        compileSdkVersion = 28
        targetSdkVersion = 27
        supportLibVersion = "28.0.0"
    }
    repositories {
        google()
        jcenter()
        maven { // <---- Add this block
            url "https://github.com/jitsi/jitsi-maven-repository/raw/master/releases"
        }
    }
    dependencies {
        classpath 'com.android.tools.build:gradle:3.2.1'
    }
}

allprojects {
    repositories {
        mavenLocal()
        google()
        jcenter()
        maven { // <---- Add this block
            url "https://github.com/jitsi/jitsi-maven-repository/raw/master/releases"
        }
        maven {
            // All of React Native (JS, Obj-C sources, Android binaries) is installed from npm
            url "$rootDir/../node_modules/react-native/android"
        }
    }
}

task wrapper(type: Wrapper) {
    gradleVersion = '4.7'
    distributionUrl = distributionUrl.replace("bin", "all")
}
````

Here is my Manifest file:
`<manifest xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:tools="http://schemas.android.com/tools"
    package="com.apitestdemo">

    <uses-permission android:name="android.permission.INTERNET" />
    <uses-permission android:name="android.permission.CAMERA" />
    <uses-permission android:name="android.permission.SYSTEM_ALERT_WINDOW" />
    <uses-permission android:name="android.permission.READ_EXTERNAL_STORAGE" />

    <uses-feature android:name="android.hardware.camera" />
    <uses-feature android:name="android.hardware.camera.autofocus" />

    <uses-permission android:name="android.permission.ACCESS_NETWORK_STATE" />
    <uses-permission android:name="android.permission.MODIFY_AUDIO_SETTINGS" />
    <uses-permission android:name="android.permission.RECORD_AUDIO" />
    <uses-permission android:name="android.permission.WAKE_LOCK" />
    <uses-permission android:name="android.permission.WRITE_EXTERNAL_STORAGE" />

    <application
        android:name=".MainApplication"
        android:icon="@mipmap/ic_launcher"
        android:label="@string/app_name"
        android:roundIcon="@mipmap/ic_launcher_round"
        android:theme="@style/AppTheme">
        <activity
            android:name=".MainActivity"
            android:configChanges="keyboard|keyboardHidden|orientation|screenSize"
            android:label="@string/app_name"
            android:windowSoftInputMode="adjustResize">
            <intent-filter>
                <action android:name="android.intent.action.MAIN" />
                <category android:name="android.intent.category.LAUNCHER" />
            </intent-filter>
        </activity>
        <activity android:name="com.facebook.react.devsupport.DevSettingsActivity" />
    </application>

</manifest>
`

Above code and error are from my test app.

By seeing error logs, I assume that it need some specific component to register or registered component is being mismatched because already registered component is for my app not for jitsi-meet. I might be wrong here, this is just my assumption. Also let me know if there is any implementation needed to integrate jitsi-meet into react-native app.

Please let me know what could be the possible solution for this issue. Any help would be appreciated.

**Comment by dhananjayharel** [comment]
I am also getting the same error...
java.lang.ClassNotFoundException: org.jitsi.meet.sdk.JitsiMeetConferenceOptions
I am was trying to compile own sdk jitsi app and use own library in my jitsi application.
I have followed the instructions given in [https://github.com/jitsi/jitsi-meet/tree/master/android](https://github.com/jitsi/jitsi-meet/tree/master/android)
Then published that to my local disk and using that as a library in maven entry of my build.gradle.
When I test it on my device the app launches but crashes after couple of seconds.
