### ISSUE TITLE
asset install (yarn/node) fails -- "error jitsi-meet/node_modules/lib-jitsi-meet: Command failed."

### ISSUE THREAD

**Issue by pgnd** [jitsi/jitsi-meet#4398]
building
```
	cd jitsi-meet
	git clean -xfd
	git reset --hard
		HEAD is now at 48285e8a fix(conference): Don't use this._room.
```

on
```
	lsb_release -rd
		Description:    openSUSE Leap 15.1
		Release:        15.1
```

with
```
	node -v && npm -v
		v12.5.0
		6.9.0
	yarn --version
		1.16.0
```

on assets install
```
	rm -f package-lock.json
	yarn install
		yarn install v1.16.0
		info No lockfile found.
		[1/5] Validating package.json...
		[2/5] Resolving packages...
		warning @atlaskit/avatar > @atlaskit/tooltip > @atlaskit/popper > react-popper > create-react-context > fbjs > core-js@1.2.7: core-js@<2.6.8 is no longer maintained. Please, upgrade to core-js@3 or at least to actual version of core-js@2.
		warning @atlaskit/button > @atlaskit/analytics-next-types@3.2.0: Typescript type definition files are now hosted directly from @atlaskit/analytics-next
		warning @atlaskit/dropdown-menu > @atlaskit/button > @atlaskit/analytics-next-types@3.2.0: Typescript type definition files are now hosted directly from @atlaskit/analytics-next
		warning css-loader > cssnano > autoprefixer > browserslist@1.7.7: Browserslist 2 could fail on reading Browserslist >3.0 config used in other tools.
		warning css-loader > cssnano > postcss-merge-rules > browserslist@1.7.7: Browserslist 2 could fail on reading Browserslist >3.0 config used in other tools.
		warning css-loader > cssnano > postcss-merge-rules > caniuse-api > browserslist@1.7.7: Browserslist 2 could fail on reading Browserslist >3.0 config used in other tools.
		warning css-loader > cssnano > postcss-merge-rules > postcss-selector-parser > flatten@1.0.2: I wrote this module a very long time ago; you should use something else.
		warning eslint > file-entry-cache > flat-cache > circular-json@0.3.3: CircularJSON is in maintenance only, flatted is its successor.
		[3/5] Fetching packages...
		info fsevents@1.2.9: The platform "linux" is incompatible with this module.
		info "fsevents@1.2.9" is an optional dependency and failed compatibility check. Excluding it from installation.
		[4/5] Linking dependencies...
		warning " > @atlaskit/inline-dialog@5.3.0" has incorrect peer dependency "react@15.6.0 - 16.2.0".
		warning " > @atlaskit/inline-dialog@5.3.0" has incorrect peer dependency "react-dom@15.6.0 - 16.2.0".
		warning "@atlaskit/inline-dialog > @atlaskit/layer@2.9.1" has incorrect peer dependency "react@15.6.0 - 16.2.0".
		warning "@atlaskit/inline-dialog > @atlaskit/theme@2.4.1" has incorrect peer dependency "react@15.6.0 - 16.2.0".
		warning " > react-native-fast-image@5.1.1" has unmet peer dependency "prop-types@*".
		warning " > react-native-google-signin@2.0.0" has unmet peer dependency "prop-types@^15.5.10".
		[5/5] Building fresh packages...
		[1/10] ⢀ core-js
		[2/10] ⢀ styled-components
		[3/10] ⢀ styled-components
		[6/10] ⢀ lib-jitsi-meet
		error /dev/test/jitsi-meet/node_modules/lib-jitsi-meet: Command failed.
		Exit code: 127
		Command: webpack -p
		Arguments:



```

and there it just sits, indefinitely ...

**Comment by saghul** [comment]
What directory are you running the install on, and as what user?

**Comment by pgnd** [comment]
as above, in the src checkout's top dir,
```
cd jitsi-meet
...
yarn install
```

Results are the same regardsless of exec user -- whether the src dir owner, or root.

**Comment by saghul** [comment]
Can you try npm instead of yarn?

**Comment by pgnd** [comment]
fails as well

```
npm install
	npm ERR! premature close
	
	npm ERR! A complete log of this run can be found in:
	npm ERR!     /home/pgnd/.npm/_logs/2019-07-09T14_47_12_278Z-debug.log

cat  /home/pgnd/.npm/_logs/2019-07-09T14_47_12_278Z-debug.log
	...
	25673 silly saveTree │ │ ├─┬ schema-utils@1.0.0
	25673 silly saveTree │ │ │ └─┬ ajv@6.6.1
	25673 silly saveTree │ │ │   ├── fast-deep-equal@2.0.1
	25673 silly saveTree │ │ │   └── json-schema-traverse@0.4.1
	25673 silly saveTree │ │ ├── serialize-javascript@1.4.0
	25673 silly saveTree │ │ ├── source-map@0.6.1
	25673 silly saveTree │ │ ├─┬ terser@3.11.0
	25673 silly saveTree │ │ │ ├── commander@2.17.1
	25673 silly saveTree │ │ │ └── source-map@0.6.1
	25673 silly saveTree │ │ ├─┬ webpack-sources@1.3.0
	25673 silly saveTree │ │ │ └── source-map@0.6.1
	25673 silly saveTree │ │ └── worker-farm@1.5.2
	25673 silly saveTree │ ├── watchpack@1.6.0
	25673 silly saveTree │ └── webpack-sources@1.3.0
	25673 silly saveTree └── xmldom@0.1.27
	25674 verbose stack Error: premature close
	25674 verbose stack     at PassThrough.onclose (/usr/local/node-v12.5.0-linux-x64/lib/node_modules/npm/node_modules/end-of-stream/index.js:47:67)
	25674 verbose stack     at PassThrough.emit (events.js:205:15)
	25674 verbose stack     at emitCloseNT (internal/streams/destroy.js:68:8)
	25674 verbose stack     at processTicksAndRejections (internal/process/task_queues.js:74:11)
	25675 verbose cwd /usr/local/src/jitsi-meet
	25676 verbose Linux 5.2.0-24.g580cec3-default
	25677 verbose argv "/usr/local/node-v12.5.0-linux-x64/bin/node" "/usr/local/nodejs/bin/npm" "install"
	25678 verbose node v12.5.0
	25679 verbose npm  v6.9.0
	25680 error premature close
	25681 verbose exit [ 1, true ]
```

**Comment by saghul** [comment]
Oh, the joy of the JavaScript ecosystem. Well, I don't know what to tell you TBH. I'm using Node 10 ATM without issues. It's all I can suggest.

**Comment by bd901029** [comment]
I have same issue. Anyone can help me? Thanks.

**Comment by saghul** [comment]
We don’t test with yarn, please use npm i
