### ISSUE TITLE
App crashes: java.lang.ClassNotFoundException: org.jitsi.meet.sdk.JitsiMeetConferenceOptions

### ISSUE THREAD

**Issue by dhananjayharel** [jitsi/jitsi-meet#4622]
## Description
After building own sdk when I use that in my app as a library then my app crashes with the following error:
java.lang.ClassNotFoundException: org.jitsi.meet.sdk.JitsiMeetConferenceOptions

I am was trying to compile own sdk jitsi app and use own library in my jitsi application.
I have followed the instructions given in [https://github.com/jitsi/jitsi-meet/tree/master/android](https://github.com/jitsi/jitsi-meet/tree/master/android)
Then published that to my local disk and using that as a library in maven entry of my build.gradle.
When I test it on my device the app launches but crashes after couple of seconds.

**Here is the java exception trace:**
Class not found when unmarshalling: org.jitsi.meet.sdk.JitsiMeetConferenceOptions
    java.lang.ClassNotFoundException: org.jitsi.meet.sdk.JitsiMeetConferenceOptions
        at java.lang.Class.classForName(Native Method)
        at java.lang.Class.forName(Class.java:453)
        at android.os.Parcel.readParcelableCreator(Parcel.java:2843)
        at android.os.Parcel.readParcelable(Parcel.java:2797)
        at android.os.Parcel.readValue(Parcel.java:2700)
        at android.os.Parcel.readArrayMapInternal(Parcel.java:3067)
        at android.os.BaseBundle.unparcel(BaseBundle.java:257)
        at android.os.BaseBundle.getString(BaseBundle.java:1086)
        at android.content.Intent.getStringExtra(Intent.java:7718)
        at com.android.server.am.ActivityStarter.startActivity(ActivityStarter.java:468)
        at com.android.server.am.ActivityStarter.startActivityLocked(ActivityStarter.java:419)
        at com.android.server.am.ActivityStarter.startActivityMayWait(ActivityStarter.java:1308)
        at com.android.server.am.ActivityManagerService.startActivityAsUser(ActivityManagerService.java:6061)
        at com.android.server.am.ActivityManagerService.startActivity(ActivityManagerService.java:5913)
        at android.app.IActivityManager$Stub.onTransact(IActivityManager.java:121)
        at com.android.server.am.ActivityManagerService.onTransact(ActivityManagerService.java:3874)
        at android.os.Binder.execTransact(Binder.java:682)
     Caused by: java.lang.ClassNotFoundException: org.jitsi.meet.sdk.JitsiMeetConferenceOptions
        at java.lang.Class.classForName(Native Method)
        at java.lang.BootClassLoader.findClass(ClassLoader.java:1355)
        at java.lang.BootClassLoader.loadClass(ClassLoader.java:1415)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
        at java.lang.Class.classForName(Native Method) 
        at java.lang.Class.forName(Class.java:453) 
        at android.os.Parcel.readParcelableCreator(Parcel.java:2843) 
        at android.os.Parcel.readParcelable(Parcel.java:2797) 
        at android.os.Parcel.readValue(Parcel.java:2700) 
        at android.os.Parcel.readArrayMapInternal(Parcel.java:3067) 
        at android.os.BaseBundle.unparcel(BaseBundle.java:257) 
        at android.os.BaseBundle.getString(BaseBundle.java:1086) 
        at android.content.Intent.getStringExtra(Intent.java:7718) 
        at com.android.server.am.ActivityStarter.startActivity(ActivityStarter.java:468) 
        at com.android.server.am.ActivityStarter.startActivityLocked(ActivityStarter.java:419) 
        at com.android.server.am.ActivityStarter.startActivityMayWait(ActivityStarter.java:1308) 
        at com.android.server.am.ActivityManagerService.startActivityAsUser(ActivityManagerService.java:6061) 
        at com.android.server.am.ActivityManagerService.startActivity(ActivityManagerService.java:5913) 
        at android.app.IActivityManager$Stub.onTransact(IActivityManager.java:121) 
        at com.android.server.am.ActivityManagerService.onTransact(ActivityManagerService.java:3874) 
        at android.os.Binder.execTransact(Binder.java:682) 

# Environment details:
Android studio - windows 7
SDK assembled in ubuntu using the instructions give was successfull.
then copied that repo into my windows machine.

---

**Comment by saghul** [comment]
Have you used the suggested proguard rules?

**Comment by TongaonkarYash** [comment]
Any solution for this? Facing same issue here

**Comment by MayukhaCheekati** [comment]
I am seeing the same issue. May i know the fix for it?
