### ISSUE TITLE
JitsiMeetExternalAPI is not defined

### ISSUE THREAD

**Issue by ramrami** [jitsi/jitsi-meet#4671]
I'm trying to embed Jitsi Meet in my application using Jitsi Meet API : 
```<script src='https://meet.jit.si/external_api.js'></script>```

But I get the error `JitsiMeetExternalAPI is not defined`, looks like it's not attached to the window object.

### Edit
I can find an object `JitsiMeetJS` but not `JitsiMeetExternalAPI`

**Comment by damencho** [comment]
Please, when having problems or questions use the community forum before opening new issues.

You better share your code. I just tested the [example](https://github.com/jitsi/jitsi-meet/blob/master/doc/examples/api.html) that comes with the [documentation](https://github.com/jitsi/jitsi-meet/blob/master/doc/api.md) and it works just fine. Check your code.

**Comment by p4535992** [comment]
Have you found a solution?

**Comment by ramrami** [comment]
I'm juste using : 

`window.JitsiMeetExternalAPI = window.JitsiMeetExternalAPI || window.exports.JitsiMeetExternalAPI;`

**Comment by developdeez** [comment]
@ramrami I found this:
https://meetrix.io/blog/webrtc/integrate-jitsi-meet-to-react-app.html

Were you able to successfully get jitsi integrated?

Seems the creator doesnt care about it being usable on webapp

**Comment by ramrami** [comment]
@developdeez Yes I was able to successfully get jitsi integrated in my meteor app. In my case, I had to get the `JitsiMeetExternalAPI ` object from `window.exports` instead of `window`.

**Comment by cacodepaula** [comment]
Hi!
I'm having the same problem, but I don't know which file to edit. Can someone help me?

Thanks!

ps.: I'm using Jitsi in Moodle.

Error: Uncaught ReferenceError: JitsiMeetExternalAPI is not defined

**Comment by Navi123456789** [comment]
<script src="https://meet.jit.si/external_api.js"></script>
    <script>
        const domain = "meet.jit.si";
        const options = {
          roomName: "JitsiMeetAPIExample",
          width: 700,
          height: 700,
          // parentNode: document.querySelector('#meet')
        };
        const api = new JitsiMeetExternalAPI(domain, options);
        console.log(api);
      </script>



ReferenceError: JitsiMeetExternalAPI is not defined
    at Object.<anonymous> (E:\kochar\Jitsi meet app\index.js:8:13)
    at Module._compile (internal/modules/cjs/loader.js:999:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
    at Module.load (internal/modules/cjs/loader.js:863:32)
    at Function.Module._load (internal/modules/cjs/loader.js:708:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:60:12)
    at internal/main/run_main_module.js:17:47

**Comment by priyankanit** [comment]
The method 'joinMeeting' isn't defined for the type 'JitsiMeet'.   I'm getting this error after adding the import 'package:jitsi_meet_flutter_sdk/jitsi_meet_flutter_sdk.dart but if I add package import 'package:jitsi_meet_fix/jitsi_meet.dart'; then I'm getting the error for JitsiMeet. kindly let me know if anyone has face this problem.
