### ISSUE TITLE
crash on android 6.0.1 Nexus 5

### ISSUE THREAD

**Issue by mt131** [jitsi/jitsi-meet#4722]
it is ok in android 8, 9
it crash on android 6.0.1 Nexus 5, sdk:2.3.2
see log:

10-08 11:09:50.207 3759-3860/net.jitsi.sdktest E/JitsiMeetSDK: JitsiMeetUncaughtExceptionHandler FATAL ERROR
    java.lang.NoSuchMethodError: No static method createEgl14([I)Lorg/webrtc/EglBase14; in class Lorg/webrtc/EglBase; or its super classes (declaration of 'org.webrtc.EglBase' appears in /data/app/net.jitsi.sdktest-1/base.apk:classes3.dex)
        at com.oney.WebRTCModule.EglUtils.getRootEglBase(EglUtils.java:35)
        at com.oney.WebRTCModule.EglUtils.getRootEglBaseContext(EglUtils.java:62)
        at com.oney.WebRTCModule.GetUserMediaImpl.createVideoTrack(GetUserMediaImpl.java:89)
        at com.oney.WebRTCModule.GetUserMediaImpl.getUserMedia(GetUserMediaImpl.java:165)
        at com.oney.WebRTCModule.WebRTCModule.lambda$getUserMedia$2$WebRTCModule(WebRTCModule.java:485)
        at com.oney.WebRTCModule.-$$Lambda$WebRTCModule$C_Gitx4KOYySlWXaI1K4M1yoJoA.run(lambda)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
        at java.lang.Thread.run(Thread.java:818)
    
    java.lang.NoSuchMethodError: No static method createEgl14([I)Lorg/webrtc/EglBase14; in class Lorg/webrtc/EglBase; or its super classes (declaration of 'org.webrtc.EglBase' appears in /data/app/net.jitsi.sdktest-1/base.apk:classes3.dex)
        at com.oney.WebRTCModule.EglUtils.getRootEglBase(EglUtils.java:35)
        at com.oney.WebRTCModule.EglUtils.getRootEglBaseContext(EglUtils.java:62)
        at com.oney.WebRTCModule.GetUserMediaImpl.createVideoTrack(GetUserMediaImpl.java:89)
        at com.oney.WebRTCModule.GetUserMediaImpl.getUserMedia(GetUserMediaImpl.java:165)
        at com.oney.WebRTCModule.WebRTCModule.lambda$getUserMedia$2$WebRTCModule(WebRTCModule.java:485)
        at com.oney.WebRTCModule.-$$Lambda$WebRTCModule$C_Gitx4KOYySlWXaI1K4M1yoJoA.run(lambda)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
        at java.lang.Thread.run(Thread.java:818)
    
    
    --------- beginning of crash
10-08 11:09:50.207 3759-3860/net.jitsi.sdktest E/AndroidRuntime: FATAL EXCEPTION: pool-3-thread-1
    Process: net.jitsi.sdktest, PID: 3759
    java.lang.NoSuchMethodError: No static method createEgl14([I)Lorg/webrtc/EglBase14; in class Lorg/webrtc/EglBase; or its super classes (declaration of 'org.webrtc.EglBase' appears in /data/app/net.jitsi.sdktest-1/base.apk:classes3.dex)
        at com.oney.WebRTCModule.EglUtils.getRootEglBase(EglUtils.java:35)
        at com.oney.WebRTCModule.EglUtils.getRootEglBaseContext(EglUtils.java:62)
        at com.oney.WebRTCModule.GetUserMediaImpl.createVideoTrack(GetUserMediaImpl.java:89)
        at com.oney.WebRTCModule.GetUserMediaImpl.getUserMedia(GetUserMediaImpl.java:165)
        at com.oney.WebRTCModule.WebRTCModule.lambda$getUserMedia$2$WebRTCModule(WebRTCModule.java:485)
        at com.oney.WebRTCModule.-$$Lambda$WebRTCModule$C_Gitx4KOYySlWXaI1K4M1yoJoA.run(lambda)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
        at java.lang.Thread.run(Thread.java:818)
10-08 11:09:50.220 194-297/? E/BufferQueueProducer: [net.jitsi.sdktest/org.jitsi.meet.sdk.JitsiMeetActivity] query: BufferQueue has been abandoned
10-08 11:09:50.221 194-460/? E/BufferQueueProducer: [net.jitsi.sdktest/org.jitsi.meet.sdk.JitsiMeetActivity] dequeueBuffer: BufferQueue has been abandoned
10-08 11:09:50.222 194-299/? E/BufferQueueProducer: [net.jitsi.sdktest/org.jitsi.meet.sdk.JitsiMeetActivity] dequeueBuffer: BufferQueue has been abandoned
10-08 11:09:50.830 202-3989/? E/ACDB-LOADER: Error: ACDB AudProc vol returned = -19
10-08 11:09:51.298 3997-4010/? E/bt_osi_config: config_new unable to open file '/etc/bluetooth/ble_stack.conf': No such file or directory
10-08 11:11:46.669 30462-1149/? E/AudioRecord-JNI: Error -4 during AudioRecord native read
10-08 11:11:46.721 30462-942/? E/AudioSource: Stop listening is called on already closed AudioSource
10-08 11:11:47.384 1916-1917/? E/ANDR-PERF-LOCK: Failed to apply optimization for resource: 4 level: 0
10-08 11:11:47.467 772-882/? E/native: do suspend true

**Comment by saghul** [comment]
Can you try lowering the Gradle plugin version to 3.4.2 ? We've seen failures with version 3.5.

**Comment by mt131** [comment]
http://prntscr.com/pgsqxt
I try lowering the Gradle plugin version to 3.4.2. But the button cannot click on android 6 Nexus 5

**Comment by saghul** [comment]
Do you see anything in logcat? That's very strange. In Jitsi Meet we are using version 3.3.2 of the plugin, maybe try that one?

**Comment by saghul** [comment]
Does that mean gradle 3.3 worked for you?

**Comment by mt131** [comment]
i add these line 
.setAudioMuted(false)
    .setVideoMuted(false)
    .setAudioOnly(false)
and grade 3.4.2 click button ok but the voice is delay, still checking

**Comment by mt131** [comment]
https://prnt.sc/ph8gp4
in android 8 and grade 3.4.2 only device ulefone the button is not ok, i try to reduce to grade 3.3.2 now

**Comment by mt131** [comment]
it is due to permission dialog not show!!!
