### ISSUE TITLE
Android SDK crashes when rotating screen during video call

### ISSUE THREAD

**Issue by calvinckho** [jitsi/jitsi-meet#4726]
*This Issue tracker is only for reporting bugs and tracking code related issues.*

Before posting, please make sure you check community.jitsi.org to see if the same or similar bugs have already been discussed.
General questions, installation help, and feature requests can also be posted to community.jitsi.org.

## Description
In video call, Android SDK crashes when rotating screen
---

## Current behavior
Rotating it in any direction will crash the app. Tried starting the call on both portrait and landscape. Then when rotating the screen, it crashes the SDK.
---

## Expected Behavior
It should rotate the call without any issue
---

## Possible Solution
---

## Steps to reproduce
Rotate the Android device screen during video call
---

# Environment details
2019-10-08 22:26:51.050 5803-5803/com.restvo.app E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.restvo.app, PID: 5803
    java.lang.RuntimeException: java.lang.reflect.InvocationTargetException
        at org.jitsi.meet.sdk.ListenerUtils.runListenerMethodOnUiThread(ListenerUtils.java:139)
        at org.jitsi.meet.sdk.ListenerUtils.access$000(ListenerUtils.java:35)
        at org.jitsi.meet.sdk.ListenerUtils$1.run(ListenerUtils.java:114)
        at android.os.Handler.handleCallback(Handler.java:790)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:164)
        at android.app.ActivityThread.main(ActivityThread.java:6494)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)
     Caused by: java.lang.reflect.InvocationTargetException
        at java.lang.reflect.Method.invoke(Native Method)
        at org.jitsi.meet.sdk.ListenerUtils.runListenerMethodOnUiThread(ListenerUtils.java:135)
        at org.jitsi.meet.sdk.ListenerUtils.access$000(ListenerUtils.java:35) 
        at org.jitsi.meet.sdk.ListenerUtils$1.run(ListenerUtils.java:114) 
        at android.os.Handler.handleCallback(Handler.java:790) 
        at android.os.Handler.dispatchMessage(Handler.java:99) 
        at android.os.Looper.loop(Looper.java:164) 
        at android.app.ActivityThread.main(ActivityThread.java:6494) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807) 
     **Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'org.jitsi.meet.sdk.JitsiMeetView org.jitsi.meet.sdk.JitsiMeetFragment.getJitsiView()' on a null object reference**
        at org.jitsi.meet.sdk.JitsiMeetActivity.getJitsiView(JitsiMeetActivity.java:105)
        at org.jitsi.meet.sdk.JitsiMeetActivity.leave(JitsiMeetActivity.java:121)
        at org.jitsi.meet.sdk.JitsiMeetActivity.finish(JitsiMeetActivity.java:94)
        at com.capacitor.jitsi.plugin.JitsiActivity$1.onConferenceTerminated(JitsiActivity.java:64)
        at java.lang.reflect.Method.invoke(Native Method) 
        at org.jitsi.meet.sdk.ListenerUtils.runListenerMethodOnUiThread(ListenerUtils.java:135) 
        at org.jitsi.meet.sdk.ListenerUtils.access$000(ListenerUtils.java:35) 
        at org.jitsi.meet.sdk.ListenerUtils$1.run(ListenerUtils.java:114) 
        at android.os.Handler.handleCallback(Handler.java:790) 
        at android.os.Handler.dispatchMessage(Handler.java:99) 
        at android.os.Looper.loop(Looper.java:164) 
        at android.app.ActivityThread.main(ActivityThread.java:6494) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807) 
---

**Comment by calvinckho** [comment]
I am using Jitsi SDK 1.21.0 for android

**Comment by saghul** [comment]
Hi there! That version is over a year old and many many things have changed since. Please update to version 2.X (2.3.2 at the time of thisd writing).

Note that APIs have changed (hence the major version bump) so you will need to adjust your code. Please hop on to our community if you have questions when migrating: https://community.jitsi.org/
