### ISSUE TITLE
HOW TO UNİNSTALL THİS JİTSİ COMPLETELY!

### ISSUE THREAD

**Issue by azamet90** [jitsi/jitsi-meet#4869]
```
/usr/share/jitsi-meet/scripts/install-letsencrypt-cert.sh
-------------------------------------------------------------------------
This script will:
- Need a working DNS record pointing to this machine(for domain azamet)
- Download certbot-auto from https://dl.eff.org to /usr/local/sbin
- Install additional dependencies in order to request Let’s Encrypt certificate
- If running with jetty serving web content, will stop Jitsi Videobridge
- Configure and reload nginx or apache2, whichever is used

You need to agree to the ACME server's Subscriber Agreement (https://letsencrypt.org/documents/LE-SA-v1.1.1-August-1-2016.pdf) 
by providing an email address for important account notifications
Enter your email and press [ENTER]: 
Bootstrapping dependencies for Debian-based OSes... (you can skip this with --no-bootstrap)
Aynı:  2 https://download.jitsi.org stable/ InRelease                         
Aynı:  1 http://mirrors.neusoft.edu.cn/kali kali-rolling InRelease
Paket listeleri okunuyor... Bitti
Paket listeleri okunuyor... Bitti
Bağımlılık ağacı oluşturuluyor       
Durum bilgisi okunuyor... Bitti      
augeas-lenses zaten en yeni sürümde (1.12.0-1).
ca-certificates zaten en yeni sürümde (20190110).
gcc zaten en yeni sürümde (4:9.2.1-3.1).
libaugeas0 zaten en yeni sürümde (1.12.0-1+b1).
libffi-dev zaten en yeni sürümde (3.2.1-9).
libssl-dev zaten en yeni sürümde (1.1.1d-2).
openssl zaten en yeni sürümde (1.1.1d-2).
python zaten en yeni sürümde (2.7.17-1).
python-dev zaten en yeni sürümde (2.7.17-1).
python-virtualenv zaten en yeni sürümde (15.1.0+ds-2).
virtualenv zaten en yeni sürümde (15.1.0+ds-2).
0 paket yükseltilecek, 0 yeni paket kurulacak, 0 paket kaldırılacak ve 0 paket yükseltilmeyecek.
Creating virtual environment...
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/virtualenv.py", line 2379, in <module>
    main()
  File "/usr/lib/python3/dist-packages/virtualenv.py", line 724, in main
    symlink=options.symlink)
  File "/usr/lib/python3/dist-packages/virtualenv.py", line 996, in create_environment
    download=download,
  File "/usr/lib/python3/dist-packages/virtualenv.py", line 926, in install_wheel
    call_subprocess(cmd, show_stdout=False, extra_env=env, stdin=SCRIPT)
  File "/usr/lib/python3/dist-packages/virtualenv.py", line 817, in call_subprocess
    % (cmd_desc, proc.returncode))
OSError: Command /opt/eff.org/certbot/venv/bin/python2.7 - setuptools pkg_resources pip wheel failed with error code 1
Traceback (most recent call last):
  File "<stdin>", line 27, in <module>
  File "<stdin>", line 19, in create_venv
  File "/usr/lib/python2.7/subprocess.py", line 190, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['virtualenv', '--no-site-packages', '--python', '/usr/bin/python2.7', '/opt/eff.org/certbot/venv']' returned non-zero exit status 1

```

trying to install it again for uninstalling completely but now works nothing!

**Comment by azamet90** [comment]
The process was aborted because too many errors were encountered.

**Comment by azamet90** [comment]
i think virus is more friendly huh?

**Comment by azamet90** [comment]
cannot uninstall jigasi, prosody !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!! why i install this why :D

**Comment by damencho** [comment]
Please when you have questions and problems use the community forum before opening new issues.

Have you tried this?
https://github.com/jitsi/jitsi-meet/blob/master/doc/quick-install.md#uninstall

**Comment by azamet90** [comment]
Yeah i was knowing that you will give me useless answer like that i decided to reinstall my linux again...

**Comment by liaquatali000** [comment]
sudo apt purge jigasi jitsi-meet jitsi-meet-web-config jitsi-meet-prosody jitsi-meet-turnserver jitsi-meet-web jicofo jitsi-videobridge2
