### ISSUE TITLE
Can't record

### ISSUE THREAD

**Issue by garthh** [jitsi/jitsi-meet#5087]
Hello,

I've followed the installation instruction, but, when I run "jibri", I get this error :

```
2020-02-21 13:49:35.093 INFOS: [20] org.jitsi.xmpp.mucclient.MucClient.log() [MucClient id=visioconf.portes-imaginaire.org hostname=visioconf.portes-imaginaire.org] connected
2020-02-21 13:49:35.134 GRAVE: [20] org.jitsi.xmpp.mucclient.MucClientManager.log() Failed to initialize and start a MucClient: 
org.jivesoftware.smack.sasl.SASLErrorException: SASLError using SCRAM-SHA-1: not-authorized
	at org.jivesoftware.smack.SASLAuthentication.authenticationFailed(SASLAuthentication.java:292)
	at org.jivesoftware.smack.tcp.XMPPTCPConnection$PacketReader.parsePackets(XMPPTCPConnection.java:1100)
	at org.jivesoftware.smack.tcp.XMPPTCPConnection$PacketReader.access$300(XMPPTCPConnection.java:1000)
	at org.jivesoftware.smack.tcp.XMPPTCPConnection$PacketReader$1.run(XMPPTCPConnection.java:1016)
	at java.lang.Thread.run(Thread.java:748)
```

When I try to record, this line is added to log

`2020-02-21 13:50:04.848 AVERTISSEMENT: [29] org.jivesoftware.smackx.ping.PingManager.pingServerIfNecessary() XMPPConnection was not authenticated`

Have you an idea ? I've tried to generate self-signed certs for "record..." avent "internal.auth..." with prosody (prosodyctl cert generate internal.auth.visioconf.portes-imaginaire.org), but, nothing more

**Comment by damencho** [comment]
Please use the community forum when having questions or problems before opening new issues.

The error you see means you try to login jibri with wrong password.
