### ISSUE TITLE
Error: While cleaned cache and reinstall

### ISSUE THREAD

**Issue by nileshmean** [jitsi/jitsi-meet#5099]
Looking for JS files in
   /var/react/jitsi-meet-stable 

Loading dependency graph, done.
error: bundling failed: Error: Unable to resolve module `lib-jitsi-meet/lib-jitsi-meet.min` from `react/features/base/lib-jitsi-meet/_.native.js`: lib-jitsi-meet/lib-jitsi-meet.min could not be found within the project.

If you are sure the module exists, try these steps:
 1. Clear watchman watches: watchman watch-del-all
 2. Delete node_modules: rm -rf node_modules and run yarn install
 3. Reset Metro's cache: yarn start --reset-cache
 4. Remove the cache: rm -rf /tmp/metro-*
    at ModuleResolver.resolveDependency (/var/react/jitsi-meet-stable/node_modules/metro/src/node-haste/DependencyGraph/ModuleResolution.js:186:15)
    at ResolutionRequest.resolveDependency (/var/react/jitsi-meet-stable/node_modules/metro/src/node-haste/DependencyGraph/ResolutionRequest.js:52:18)
    at DependencyGraph.resolveDependency (/var/react/jitsi-meet-stable/node_modules/metro/src/node-haste/DependencyGraph.js:282:16)
    at Object.resolve (/var/react/jitsi-meet-stable/node_modules/metro/src/lib/transformHelpers.js:267:42)
    at dependencies.map.result (/var/react/jitsi-meet-stable/node_modules/metro/src/DeltaBundler/traverseDependencies.js:426:31)
    at Array.map (<anonymous>)
    at resolveDependencies (/var/react/jitsi-meet-stable/node_modules/metro/src/DeltaBundler/traverseDependencies.js:423:18)
    at /var/react/jitsi-meet-stable/node_modules/metro/src/DeltaBundler/traverseDependencies.js:275:33
    at Generator.next (<anonymous>)
    at asyncGeneratorStep (/var/react/jitsi-meet-stable/node_modules/metro/src/DeltaBundler/traverseDependencies.js:87:24)
 BUNDLE  [android, dev] ./index.android.js ░░░░░░░░░░░░░░░░ 5.7% (40/258)::ffff:127.0.0.1 - - [02/Mar/2020:07:44:05 +0000] "GET /index.android.bundle?platform=android&dev=true&minify=false HTTP/1.1" 500 - "-" "okhttp/3.12.1"
 BUNDLE  [android, dev] ./index.android.js ░░░░░░░░░░░░░░░░ 5.7% (40/258), failed.

**Comment by saghul** [comment]
Can you try to use npm install instead of yarn? We don’t really test / support yarn.

**Comment by nileshmean** [comment]
I used NPM install. but not worked.

**Comment by saghul** [comment]
Does npm install succeed? Does the file exist after you run the command?

**Comment by l3d00m** [comment]
Closing as no further feedback was given, feel free to reopen with more details if it stil persists.
