### ISSUE TITLE
Android App Crashing with Custom Jitsi SDK

### ISSUE THREAD

**Issue by krishnaprakash94** [jitsi/jitsi-meet#5184]
E/SoLoader: couldn't find DSO to load: libhermes.so caused by: dlopen failed: library "libc++_shared.so" not found
E/AndroidRuntime: FATAL EXCEPTION: create_react_context
    Process: com.jitsi.app, PID: 6471
    java.lang.UnsatisfiedLinkError: couldn't find DSO to load: libhermes.so caused by: dlopen failed: library "libc++_shared.so" not found
        at com.facebook.soloader.SoLoader.doLoadLibraryBySoName(SoLoader.java:738)
        at com.facebook.soloader.SoLoader.loadLibraryBySoName(SoLoader.java:591)
        at com.facebook.soloader.SoLoader.loadLibrary(SoLoader.java:529)
        at com.facebook.soloader.SoLoader.loadLibrary(SoLoader.java:484)
        at com.facebook.hermes.reactexecutor.HermesExecutor.<clinit>(HermesExecutor.java:20)
        at com.facebook.hermes.reactexecutor.HermesExecutorFactory.create(HermesExecutorFactory.java:27)
        at com.facebook.react.ReactInstanceManager$5.run(ReactInstanceManager.java:952)
        at java.lang.Thread.run(Thread.java:764)
E/JitsiMeetSDK: JitsiMeetUncaughtExceptionHandler FATAL ERROR
    java.lang.UnsatisfiedLinkError: couldn't find DSO to load: libhermes.so caused by: dlopen failed: library "libc++_shared.so" not found
        at com.facebook.soloader.SoLoader.doLoadLibraryBySoName(SoLoader.java:738)
        at com.facebook.soloader.SoLoader.loadLibraryBySoName(SoLoader.java:591)
        at com.facebook.soloader.SoLoader.loadLibrary(SoLoader.java:529)
        at com.facebook.soloader.SoLoader.loadLibrary(SoLoader.java:484)
        at com.facebook.hermes.reactexecutor.HermesExecutor.<clinit>(HermesExecutor.java:20)
        at com.facebook.hermes.reactexecutor.HermesExecutorFactory.create(HermesExecutorFactory.java:27)
        at com.facebook.react.ReactInstanceManager$5.run(ReactInstanceManager.java:952)
        at java.lang.Thread.run(Thread.java:764)
    
    java.lang.UnsatisfiedLinkError: couldn't find DSO to load: libhermes.so caused by: dlopen failed: library "libc++_shared.so" not found
        at com.facebook.soloader.SoLoader.doLoadLibraryBySoName(SoLoader.java:738)
        at com.facebook.soloader.SoLoader.loadLibraryBySoName(SoLoader.java:591)
        at com.facebook.soloader.SoLoader.loadLibrary(SoLoader.java:529)
        at com.facebook.soloader.SoLoader.loadLibrary(SoLoader.java:484)
        at com.facebook.hermes.reactexecutor.HermesExecutor.<clinit>(HermesExecutor.java:20)
        at com.facebook.hermes.reactexecutor.HermesExecutorFactory.create(HermesExecutorFactory.java:27)
        at com.facebook.react.ReactInstanceManager$5.run(ReactInstanceManager.java:952)
        at java.lang.Thread.run(Thread.java:764)
D/miuisdk: current sdk level is 18
I/Process: Sending signal. PID: 6471 SIG: 9
Process 6471 terminated.

**Comment by krishnaprakash94** [comment]
Hi Saghul, can you revert back us regarding the app crash while using custom SDK.

**Comment by saghul** [comment]
Does your SDK include this? https://github.com/jitsi/jitsi-meet/blob/master/android/sdk/build.gradle#L37 what changes did you make to the SDK? Can you build our examples at https://github.com/jitsi/jitsi-meet-sdk-samples ?

**Comment by l3d00m** [comment]
Closing as no further feedback was given, feel free to reopen with more details if it still persists.

**Comment by rananajam1** [comment]
@krishnaprakash94 did you fix this?
