### ISSUE TITLE
Android setRoom & setAudioMuted Crashing

### ISSUE THREAD

**Issue by Faiyyaz** [jitsi/jitsi-meet#5249]
*This Issue tracker is only for reporting bugs and tracking code related issues.*

Before posting, please make sure you check community.jitsi.org to see if the same or similar bugs have already been discussed.
General questions, installation help, and feature requests can also be posted to community.jitsi.org.

## Description
---

Default room and audioMuted is not working.

## Current behavior
---

If i set room and audioMuted using methods then it crashes on start saying room is empty and crashes and if i keep only mute with welcome page enable then app runs fine but audio doesn't mute by default.

## Expected Behavior
---

It should set the default room and the audi should be on mute while calling.

## Possible Solution
---

Settings preference from native methods are not applying

## Steps to reproduce
---

1. Clone the repo
2. Replace initialize() code with the below code

```
Bundle b = new Bundle();
        b.putString("displayName", "Faiyyaz Khatri");
        JitsiMeetConferenceOptions defaultOptions
            = new JitsiMeetConferenceOptions.Builder()
                .setRoom("room")
                .setAudioMuted(true)
                .setUserInfo(new JitsiMeetUserInfo(b))
                .setServerURL(buildURL("https://meet.jit.si"))
                .setFeatureFlag("call-integration.enabled", false)
                .build();
        JitsiMeet.setDefaultConferenceOptions(defaultOptions);
```

# Environment details
---
Android 9
Realme 2 Pro

**Comment by Faiyyaz** [comment]
Attaching logs for better reference

```
E/AndroidRuntime: FATAL EXCEPTION: main
    Process: org.jitsi.meet, PID: 17688
    java.lang.RuntimeException: Unable to start activity ComponentInfo{org.jitsi.meet/org.jitsi.meet.MainActivity}: java.lang.RuntimeException: 'room' must be null in the default conference options
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3270)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3409)
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:83)
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2016)
        at android.os.Handler.dispatchMessage(Handler.java:107)
        at android.os.Looper.loop(Looper.java:214)
        at android.app.ActivityThread.main(ActivityThread.java:7356)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930)
     Caused by: java.lang.RuntimeException: 'room' must be null in the default conference options
        at org.jitsi.meet.sdk.JitsiMeet.setDefaultConferenceOptions(JitsiMeet.java:37)
        at org.jitsi.meet.MainActivity.initialize(MainActivity.java:99)
        at org.jitsi.meet.sdk.JitsiMeetActivity.onCreate(JitsiMeetActivity.java:71)
        at android.app.Activity.performCreate(Activity.java:7802)
        at android.app.Activity.performCreate(Activity.java:7791)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1299)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3245)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3409) 
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:83) 
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135) 
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2016) 
        at android.os.Handler.dispatchMessage(Handler.java:107) 
        at android.os.Looper.loop(Looper.java:214) 
        at android.app.ActivityThread.main(ActivityThread.java:7356) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930) 
E/JitsiMeetSDK: JitsiMeetUncaughtExceptionHandler FATAL ERROR
    java.lang.RuntimeException: Unable to start activity ComponentInfo{org.jitsi.meet/org.jitsi.meet.MainActivity}: java.lang.RuntimeException: 'room' must be null in the default conference options
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3270)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3409)
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:83)
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2016)
        at android.os.Handler.dispatchMessage(Handler.java:107)
        at android.os.Looper.loop(Looper.java:214)
        at android.app.ActivityThread.main(ActivityThread.java:7356)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930)
     Caused by: java.lang.RuntimeException: 'room' must be null in the default conference options
        at org.jitsi.meet.sdk.JitsiMeet.setDefaultConferenceOptions(JitsiMeet.java:37)
        at org.jitsi.meet.MainActivity.initialize(MainActivity.java:99)
        at org.jitsi.meet.sdk.JitsiMeetActivity.onCreate(JitsiMeetActivity.java:71)
        at android.app.Activity.performCreate(Activity.java:7802)
        at android.app.Activity.performCreate(Activity.java:7791)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1299)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3245)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3409) 
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:83) 
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135) 
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2016) 
        at android.os.Handler.dispatchMessage(Handler.java:107) 
        at android.os.Looper.loop(Looper.java:214) 
        at android.app.ActivityThread.main(ActivityThread.java:7356) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930) 
    
    java.lang.RuntimeException: Unable to start activity ComponentInfo{org.jitsi.meet/org.jitsi.meet.MainActivity}: java.lang.RuntimeException: 'room' must be null in the default conference options
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3270)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3409)
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:83)
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2016)
        at android.os.Handler.dispatchMessage(Handler.java:107)
        at android.os.Looper.loop(Looper.java:214)
        at android.app.ActivityThread.main(ActivityThread.java:7356)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930)
     Caused by: java.lang.RuntimeException: 'room' must be null in the default conference options
        at org.jitsi.meet.sdk.JitsiMeet.setDefaultConferenceOptions(JitsiMeet.java:37)
        at org.jitsi.meet.MainActivity.initialize(MainActivity.java:99)
        at org.jitsi.meet.sdk.JitsiMeetActivity.onCreate(JitsiMeetActivity.java:71)
        at android.app.Activity.performCreate(Activity.java:7802)
        at android.app.Activity.performCreate(Activity.java:7791)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1299)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3245)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3409) 
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:83) 
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135) 
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2016) 
        at android.os.Handler.dispatchMessage(Handler.java:107) 
        at android.os.Looper.loop(Looper.java:214) 
        at android.app.ActivityThread.main(ActivityThread.java:7356) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930) 
```

**Comment by saghul** [comment]
`Caused by: java.lang.RuntimeException: 'room' must be null in the default conference options`

You must not the room in the default options. Create a new options object to pass it to join() or JitsiMeetActivity.launch.

**Comment by Faiyyaz** [comment]
But in the example code there is no join option and the activity is extending JitsiMeetActivity itself so can you please provide code snippet on how to do it?

**Comment by saghul** [comment]
What example code are you looking at? Check this:! https://github.com/jitsi/jitsi-meet-sdk-samples
