### ISSUE TITLE
can it be that jitsi cofo does not support wild card certificates?

### ISSUE THREAD

**Issue by f1-outsourcing** [jitsi/jitsi-meet#5324]
Jicofo 2020-03-22 19:57:26.841 WARNING: [45] org.jivesoftware.smack.AbstractXMPPConnection.callConnectionClosedOnErrorListener() Connection XMPPTCPConnection[not-authenticated] (0) closed with error
java.security.cert.CertificateException: Hostname verification of certificate failed. Certificate does not authenticate auth.prosody.dev.marathon.mesos
     at org.jivesoftware.smack.tcp.XMPPTCPConnection.proceedTLSReceived(XMPPTCPConnection.java:820)
     at org.jivesoftware.smack.tcp.XMPPTCPConnection.access$1200(XMPPTCPConnection.java:151)
     at org.jivesoftware.smack.tcp.XMPPTCPConnection$PacketReader.parsePackets(XMPPTCPConnection.java:1071)
     at org.jivesoftware.smack.tcp.XMPPTCPConnection$PacketReader.access$300(XMPPTCPConnection.java:1000)
     at org.jivesoftware.smack.tcp.XMPPTCPConnection$PacketReader$1.run(XMPPTCPConnection.java:1016)
     at java.lang.Thread.run(Thread.java:748)
Jicofo 2020-03-22 19:57:31.903 INFO: [52] org.jivesoftware.smack.java7.XmppHostnameVerifier.verify() Certificate does not match hostname
java.security.cert.CertificateException: No subject alternative DNS name matching auth.prosody.dev.marathon.mesos found. Tried: *.dev.marathon.mesos,
     at org.jivesoftware.smack.java7.XmppHostnameVerifier.matchDns(XmppHostnameVerifier.java:159)
     at org.jivesoftware.smack.java7.XmppHostnameVerifier.match(XmppHostnameVerifier.java:105)
     at org.jivesoftware.smack.java7.XmppHostnameVerifier.verify(XmppHostnameVerifier.java:71)
     at org.jivesoftware.smack.tcp.XMPPTCPConnection.proceedTLSReceived(XMPPTCPConnection.java:819)
     at org.jivesoftware.smack.tcp.XMPPTCPConnection.access$1200(XMPPTCPConnection.java:151)
     at org.jivesoftware.smack.tcp.XMPPTCPConnection$PacketReader.parsePackets(XMPPTCPConnection.java:1071)
     at org.jivesoftware.smack.tcp.XMPPTCPConnection$PacketReader.access$300(XMPPTCPConnection.java:1000)
     at org.jivesoftware.smack.tcp.XMPPTCPConnection$PacketReader$1.run(XMPPTCPConnection.java:1016)
     at java.lang.Thread.run(Thread.java:748)

**Comment by damencho** [comment]
Please use the community forum when you have questions or problems before opening new issues.

How did you install? *.dev.marathon.mesos does not match auth.prosody.dev.marathon.mesos, as I can tell ... 
But anyway, so when you install Debian package for the prosody internal domains certs are autogenerated and auto-trusted on the same machine(added to the trust store of ubuntu/debian) in order jicofo when it connects to trust that cert ... All certs that are for internal prosody use are created with exact hostname, so I'm not sure where did you end up with a star certificate.

**Comment by f1-outsourcing** [comment]
Is there something like chat, that I can use? I have some questions about how to create own docker images and how the applications are connecting.

**Comment by damencho** [comment]
Use the community forum.
