### ISSUE TITLE
nullpointer in method org.jitsi.videobridge.stats.StatsManager$StatisticsPeriodicRunnable.run

### ISSUE THREAD

**Issue by TheB1gG** [jitsi/jitsi-meet#5648]
Hello,
my log gets spammed by this nullpointer every 5 seconds
```
2020-04-04 08:01:42.465 SEVERE: [15] RecurringRunnableExecutor.run#230: The invocation of the method org.jitsi.videobridge.stats.StatsManager$StatisticsPeriodicRunnable.run() threw an exception.
java.lang.NullPointerException
	at org.jitsi.xmpp.mucclient.MucClient.getMucsCount(MucClient.java:384)
	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
	at java.util.concurrent.ConcurrentHashMap$ValueSpliterator.forEachRemaining(ConcurrentHashMap.java:3566)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:482)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:472)
	at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:708)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.util.stream.IntPipeline.reduce(IntPipeline.java:479)
	at java.util.stream.IntPipeline.sum(IntPipeline.java:437)
	at org.jitsi.xmpp.mucclient.MucClientManager.getMucCount(MucClientManager.java:344)
	at org.jitsi.videobridge.stats.VideobridgeStatistics.generate0(VideobridgeStatistics.java:557)
	at org.jitsi.videobridge.stats.VideobridgeStatistics.generate(VideobridgeStatistics.java:158)
	at org.jitsi.videobridge.stats.StatsManager$StatisticsPeriodicRunnable.doRun(StatsManager.java:321)
	at org.jitsi.utils.concurrent.PeriodicRunnableWithObject.run(PeriodicRunnableWithObject.java:87)
	at org.jitsi.utils.concurrent.RecurringRunnableExecutor.run(RecurringRunnableExecutor.java:216)
	at org.jitsi.utils.concurrent.RecurringRunnableExecutor.runInThread(RecurringRunnableExecutor.java:292)
	at org.jitsi.utils.concurrent.RecurringRunnableExecutor.access$000(RecurringRunnableExecutor.java:36)
	at org.jitsi.utils.concurrent.RecurringRunnableExecutor$1.run(RecurringRunnableExecutor.java:328)
```

Everything works. So i just want to get rid of this spamming to maybe see something usefull in the logs.

Installation details
```
cat /etc/issue
Debian GNU/Linux 10 \n \l
uname -a
Linux server 4.19.0-6-amd64 #1 SMP Debian 4.19.67-2+deb10u2 (2019-11-11) x86_64 GNU/Linux
java -version
openjdk version "1.8.0_252-ea"
OpenJDK Runtime Environment (build 1.8.0_252-ea-8u252-b07-1-b07)
OpenJDK 64-Bit Server VM (build 25.252-b07, mixed mode)
dpkg -s jitsi-videobridge2 | grep Version
Version: 2.1-164-gfdce823f-1
```

**Comment by damencho** [comment]
Please use the community forum before opening new issues.

You better share your jvb sip-communicator.properties and config file. Mask any private info.

**Comment by TheB1gG** [comment]
cat /etc/jitsi/videobridge/sip-communicator.properties
```
org.ice4j.ice.harvest.DISABLE_AWS_HARVESTER=true
org.ice4j.ice.harvest.STUN_MAPPING_HARVESTER_ADDRESSES=meet-jit-si-turnrelay.jitsi.net:443
org.jitsi.videobridge.ENABLE_STATISTICS=true
org.jitsi.videobridge.STATISTICS_TRANSPORT=muc
org.jitsi.videobridge.xmpp.user.shard.HOSTNAME=localhost
org.jitsi.videobridge.xmpp.user.shard.DOMAIN=auth.meet.mydomain
org.jitsi.videobridge.xmpp.user.shard.USERNAME=jvb
org.jitsi.videobridge.xmpp.user.shard.PASSWORD=XXX
org.jitsi.videobridge.xmpp.user.shard.MUC_JIDS=JvbBrewery@internal.auth.meet.mydomain
org.jitsi.videobridge.xmpp.user.shard.MUC_NICKNAME=1a992141-54ec-4fa8-8836-d62e8ddfb141
org.ice4j.ice.harvest.ALLOWED_ADDRESSES=127.0.0.1;::1;publicipv4;publicipv6
org.jitsi.videobridge.ALLOWED_ADDRESSES=127.0.0.1;::1;publicipv4;publicipv6
org.mortbay.jetty.nio.SelectChannelConnector.Host=127.0.0.1;::1;publicipv4;publicipv6
org.jitsi.videobridge.xmpp.user.jvb2.HOSTNAME=127.0.0.1
```
cat /etc/jitsi/videobridge/config
```
# Jitsi Videobridge settings

# sets the XMPP domain (default: none)
JVB_HOSTNAME=meet.mydomain

# sets the hostname of the XMPP server (default: domain if set, localhost otherwise)
JVB_HOST=localhost

# sets the port of the XMPP server (default: 5275)
JVB_PORT=5347

# sets the shared secret used to authenticate to the XMPP server
JVB_SECRET=XXX

# extra options to pass to the JVB daemon
JVB_OPTS="--apis=,"


# adds java system props that are passed to jvb (default are for home and logging config file)
JAVA_SYS_PROPS="-Dnet.java.sip.communicator.SC_HOME_DIR_LOCATION=/etc/jitsi -Dnet.java.sip.communicator.SC_HOME_DIR_NAME=videobridge -Dnet.java.sip.communicator.SC_LOG_DIR_LOCATION=/var/log/jitsi -Djava.util.logging.config.file=/etc/jitsi/videobridge/logging.properties"
```

**Comment by niclasheu** [comment]
Change `org.jitsi.videobridge.ENABLE_STATISTICS` to `false`. That should do the trick.

**Comment by TheB1gG** [comment]
Thanks for the suggestion, but that causes as soon as 2 people join a meeting that they get to see "Unfortuantely, something went wrong"

**Comment by Echolon** [comment]
Hi,
If you have a question about Jitsi Meet that is not a bug report or feature request, please post it in https://community.jitsi.org

@damencho @saghul ok?

---
*I'm a community contributor and not directly affiliated with the Jitsi team.*
