### ISSUE TITLE
"Unfortunately something went wrong" when second user joins [SOLVED?]

### ISSUE THREAD

**Issue by richb-hanover** [jitsi/jitsi-meet#5696]
## Description

When a second user joins, both users see "Unfortunately something went wrong", and the browsers try to re-connect. Here's a screen shot:

<img width="887" alt="PastedGraphic-1" src="https://user-images.githubusercontent.com/1094930/78511196-cb56f800-7768-11ea-90e8-989c18393d50.png">

---

## Current behavior

See description above.

---

## Expected Behavior

Both browser should be able to connect into a session

---

## Possible Solution

unknown

---

## Steps to reproduce

I used the Quick Start procedure today to install Jitsi 2.10.5550 on a fresh Ubuntu 18.04 VPS.

As noted above, the problem I am seeing is that I can connect to my server and start a meeting. A second person can connect in from another computer to the same meeting (same meeting string). But when the second person clicks "Allow" to use camera/microphone, both computers display the message shown above.

---

# Environment details

`/usr/bin/jitsi --version` shows Jitsi 2.10.5550
Brand new Ubuntu 18.04 vps with full upgrades
I used Quick Start to install Jitsi

I checked /var/log/jitsi/jvb.log. Whether there is a connection in place or not, it displays the continuing succession of error messages shown below.

This may be related to #5557, which has similar log messages. Please let me know if I can provide additional troubleshooting information. Thanks.

```
deploy@atl3:~$ sudo tail -f /var/log/jitsi/jvb.log
2020-04-05 21:45:49.805 INFO: [18] Videobridge.createConference#326: create_conf, id=dded7e15cfbd88a3 gid=null logging=false
2020-04-05 21:45:49.815 INFO: [18] Health.doRun#294: Performed a successful health check in 10ms. Sticky failure: false
2020-04-05 21:45:52.752 INFO: [22] [hostname=localhost id=shard] MucClient.lambda$getConnectAndLoginCallable$7#648: Logging in.
2020-04-05 21:45:52.753 SEVERE: [22] RetryStrategy$TaskRunner.run#198: org.jivesoftware.smack.sasl.SASLErrorException: SASLError using SCRAM-SHA-1: not-authorized
org.jivesoftware.smack.sasl.SASLErrorException: SASLError using SCRAM-SHA-1: not-authorized
	at org.jivesoftware.smack.SASLAuthentication.authenticationFailed(SASLAuthentication.java:292)
	at org.jivesoftware.smack.tcp.XMPPTCPConnection$PacketReader.parsePackets(XMPPTCPConnection.java:1100)
	at org.jivesoftware.smack.tcp.XMPPTCPConnection$PacketReader.access$300(XMPPTCPConnection.java:1000)
	at org.jivesoftware.smack.tcp.XMPPTCPConnection$PacketReader$1.run(XMPPTCPConnection.java:1016)
	at java.base/java.lang.Thread.run(Thread.java:834)
2020-04-05 21:45:57.759 INFO: [22] [hostname=localhost id=shard] MucClient.lambda$getConnectAndLoginCallable$7#648: Logging in.
2020-04-05 21:45:57.759 SEVERE: [22] RetryStrategy$TaskRunner.run#198: org.jivesoftware.smack.sasl.SASLErrorException: SASLError using SCRAM-SHA-1: not-authorized
org.jivesoftware.smack.sasl.SASLErrorException: SASLError using SCRAM-SHA-1: not-authorized
	at org.jivesoftware.smack.SASLAuthentication.authenticationFailed(SASLAuthentication.java:292)
	at org.jivesoftware.smack.tcp.XMPPTCPConnection$PacketReader.parsePackets(XMPPTCPConnection.java:1100)
	at org.jivesoftware.smack.tcp.XMPPTCPConnection$PacketReader.access$300(XMPPTCPConnection.java:1000)
	at org.jivesoftware.smack.tcp.XMPPTCPConnection$PacketReader$1.run(XMPPTCPConnection.java:1016)
	at java.base/java.lang.Thread.run(Thread.java:834)
2020-04-05 21:45:59.815 INFO: [18] Videobridge.createConference#326: create_conf, id=e3b70b2317b091e5 gid=null logging=false
2020-04-05 21:45:59.831 INFO: [18] Health.doRun#294: Performed a successful health check in 16ms. Sticky failure: false
2020-04-05 21:46:02.765 INFO: [22] [hostname=localhost id=shard] MucClient.lambda$getConnectAndLoginCallable$7#648: Logging in.
2020-04-05 21:46:02.766 SEVERE: [22] RetryStrategy$TaskRunner.run#198: org.jivesoftware.smack.sasl.SASLErrorException: SASLError using SCRAM-SHA-1: not-authorized
org.jivesoftware.smack.sasl.SASLErrorException: SASLError using SCRAM-SHA-1: not-authorized
	at org.jivesoftware.smack.SASLAuthentication.authenticationFailed(SASLAuthentication.java:292)
	at org.jivesoftware.smack.tcp.XMPPTCPConnection$PacketReader.parsePackets(XMPPTCPConnection.java:1100)
	at org.jivesoftware.smack.tcp.XMPPTCPConnection$PacketReader.access$300(XMPPTCPConnection.java:1000)
	at org.jivesoftware.smack.tcp.XMPPTCPConnection$PacketReader$1.run(XMPPTCPConnection.java:1016)
	at java.base/java.lang.Thread.run(Thread.java:834)
2020-04-05 21:46:07.767 INFO: [22] [hostname=localhost id=shard] MucClient.lambda$getConnectAndLoginCallable$7#648: Logging in.
2020-04-05 21:46:07.767 SEVERE: [22] RetryStrategy$TaskRunner.run#198: org.jivesoftware.smack.sasl.SASLErrorException: SASLError using SCRAM-SHA-1: not-authorized
org.jivesoftware.smack.sasl.SASLErrorException: SASLError using SCRAM-SHA-1: not-authorized
	at org.jivesoftware.smack.SASLAuthentication.authenticationFailed(SASLAuthentication.java:292)
	at org.jivesoftware.smack.tcp.XMPPTCPConnection$PacketReader.parsePackets(XMPPTCPConnection.java:1100)
	at org.jivesoftware.smack.tcp.XMPPTCPConnection$PacketReader.access$300(XMPPTCPConnection.java:1000)
	at org.jivesoftware.smack.tcp.XMPPTCPConnection$PacketReader$1.run(XMPPTCPConnection.java:1016)
	at java.base/java.lang.Thread.run(Thread.java:834)
2020-04-05 21:46:09.832 INFO: [18] Videobridge.createConference#326: create_conf, id=b3de1bb9dfa51414 gid=null logging=false
2020-04-05 21:46:09.864 INFO: [18] Health.doRun#294: Performed a successful health check in 32ms. Sticky failure: false
^C
deploy@atl3:~$
```

**Comment by richb-hanover** [comment]
**Update:** It is working now. (That is to say, the second person connecting in operates.) Here are the changes I made:

```
sudo apt-get purge jigasi jitsi-meet jitsi-meet-web-config jitsi-meet-prosody jitsi-meet-turnserver jitsi-meet-web jicofo jitsi-videobridge2
sudo apt-get purge prosody
sudo apt autoremove
sudo apt-get -y install jitsi-meet
sudo /usr/share/jitsi-meet/scripts/install-letsencrypt-cert.sh
```
I'm not going to mark it as solved, but the behavior is different.

**Comment by xn--nding-jua** [comment]
@richb-hanover: Thank you for this solution. We faced the same problem but with the purging and reinstallation it worked. It seems, that something is not upgraded well to version 2.x - we used version 1.x before.

**Comment by richb-hanover** [comment]
Actually, a clean re-installation this morning changed its behavior. 

Is there a stable version that I could fall back to?  How would I install that version? Thanks.

**Comment by Echolon** [comment]
@richb-hanover Hi, thanks for reporting.
Is this issue solve or did you manage to solve it yourself?

**Comment by richb-hanover** [comment]
@Echolon  Thanks for checking in. It's working now - I don't know if the purge/autoremove/re-install steps I used (above) were the solution. (That's why I put a "?" in the title.)

I have updated to newer jitsi-meet &c and it's working.

**Comment by melvinman** [comment]
restarting jitsi video bridge worked for me.

**Comment by vishalkale1** [comment]
I am getting below error,

![Screenshot 2020-06-12 at 6 39 39 PM](https://user-images.githubusercontent.com/57800843/84510229-7e504e80-ace2-11ea-8518-1a8ae241b83c.png)

I tried this,

> sudo apt-get purge jigasi jitsi-meet jitsi-meet-web-config jitsi-meet-prosody jitsi-meet-turnserver jitsi-meet-web jicofo jitsi-videobridge2
> sudo apt-get purge prosody
> sudo apt autoremove
> sudo apt-get -y install jitsi-meet
> sudo /usr/share/jitsi-meet/scripts/install-letsencrypt-cert.sh

Didn't solve the problem.

Result of 'dpkg -l | grep jitsi'

> ii  jitsi-meet                             2.0.4627-1                                  all          WebRTC JavaScript video conferences
> ii  jitsi-meet-prosody                     1.0.4127-1                                  all          Prosody configuration for Jitsi Meet
> ii  jitsi-meet-turnserver                  1.0.4127-1                                  all          Configures coturn to be used with Jitsi Meet
> ii  jitsi-meet-web                         1.0.4127-1                                  all          WebRTC JavaScript video conferences
> ii  jitsi-meet-web-config                  1.0.4127-1                                  all          Configuration for web serving of Jitsi Meet
> ii  jitsi-videobridge2                     2.1-202-g5f9377b9-1                         all          WebRTC compatible Selective Forwarding Unit (SFU)

**Comment by richb-hanover** [comment]
> I am getting below error,

The original report (and response) was a long time ago - two months ago. The software has evolved a lot since then.

I would recommend opening a new issue to get more focused attention.
