### ISSUE TITLE
unable to integrate videobridge2

### ISSUE THREAD

**Issue by prabhatpankaj** [jitsi/jitsi-meet#5853]
## Current behavior

I followed the instruction https://github.com/jitsi/jitsi-meet/wiki/jitsi-meet-load-balancing-installation-Ubuntu-18.04-with-MUC-and-JID 

* on JVB server /etc/jitsi/videobridge/sip-communicator.properties

```
org.ice4j.ice.harvest.DISABLE_AWS_HARVESTER=true
org.ice4j.ice.harvest.STUN_MAPPING_HARVESTER_ADDRESSES=meet-jit-si-turnrelay.jitsi.net:443
org.jitsi.videobridge.ENABLE_STATISTICS=true
org.jitsi.videobridge.STATISTICS_TRANSPORT=muc
org.jitsi.videobridge.xmpp.user.shard.HOSTNAME=meet.aptence.com
org.jitsi.videobridge.xmpp.user.shard.DOMAIN=auth.meet.aptence.com
org.jitsi.videobridge.xmpp.user.shard.USERNAME=jvb
org.jitsi.videobridge.xmpp.user.shard.PASSWORD=abcdef
org.jitsi.videobridge.xmpp.user.shard.MUC_JIDS=JvbBrewery@internal.auth.meet.aptence.com
org.jitsi.videobridge.xmpp.user.shard.MUC_NICKNAME=990af9e4-4c9c-4532-924f-48e4cd9ae765
org.jitsi.videobridge.xmpp.user.shard.DISABLE_CERTIFICATE_VERIFICATION=true
```

* on JMS server /etc/jitsi/videobridge/sip-communicator.properties

```
org.ice4j.ice.harvest.DISABLE_AWS_HARVESTER=true
org.ice4j.ice.harvest.STUN_MAPPING_HARVESTER_ADDRESSES=meet-jit-si-turnrelay.jitsi.net:443
org.jitsi.videobridge.ENABLE_STATISTICS=true
org.jitsi.videobridge.STATISTICS_TRANSPORT=muc
org.jitsi.videobridge.xmpp.user.shard.HOSTNAME=meet.aptence.com
org.jitsi.videobridge.xmpp.user.shard.DOMAIN=auth.meet.aptence.com
org.jitsi.videobridge.xmpp.user.shard.USERNAME=jvb
org.jitsi.videobridge.xmpp.user.shard.PASSWORD=abcdef
org.jitsi.videobridge.xmpp.user.shard.MUC_JIDS=JvbBrewery@internal.auth.meet.aptence.com
org.jitsi.videobridge.xmpp.user.shard.MUC_NICKNAME=60fb4da5-d61b-473c-a83e-8f9a4f84a285

```

* for testing I disabled videobridge on JMS

```
/etc/init.d/jitsi-videobridge2 stop
```
## after doing these steps I am getting the timeout error.

```
2020-04-10 03:35:10.346 WARNING: [22] [hostname=meet.aptence.com id=shard] MucClient.lambda$getConnectAndLoginCallable$7#643: [MucClient id=shard hostname=meet.aptence.com] error connecting
org.jivesoftware.smack.SmackException$ConnectionException: The following addresses failed: 'meet.aptence.com:5222' failed because: meet.aptence.com/54.86.185.16 exception: java.net.SocketTimeoutException: connect timed out
	at org.jivesoftware.smack.SmackException$ConnectionException.from(SmackException.java:278)
	at org.jivesoftware.smack.tcp.XMPPTCPConnection.connectUsingConfiguration(XMPPTCPConnection.java:619)
	at org.jivesoftware.smack.tcp.XMPPTCPConnection.connectInternal(XMPPTCPConnection.java:902)
	at org.jivesoftware.smack.AbstractXMPPConnection.connect(AbstractXMPPConnection.java:383)
	at org.jitsi.xmpp.mucclient.MucClient.lambda$getConnectAndLoginCallable$7(MucClient.java:638)
	at org.jitsi.retry.RetryStrategy$TaskRunner.run(RetryStrategy.java:193)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
```

* in UI i am getting error as 
<img width="1081" alt="Screenshot 2020-04-10 at 8 43 15 AM" src="https://user-images.githubusercontent.com/20439273/78960100-a1a42500-7b0a-11ea-8c5c-dafd68578e1e.png">

**Comment by damencho** [comment]
> The following addresses failed: 'meet.aptence.com:5222' failed because: meet.aptence.com/54.86.185.16 exception: java.net.SocketTimeoutException: connect timed out

You need to allow the jvb to connect to the prosody server. There is a firewall that stops the connection to port 5222. Or prosody is not listening on that port (it can be listening on 5222 only on localhost...).

Please when you have questions or problems use the community forum before opening new issues.

**Comment by prabhatpankaj** [comment]
Thanks @damencho  my bad ..

It's working now.

**Comment by aurangi** [comment]
gusy i am getting the same issue , can anyone help me please

**Comment by prabhatpankaj** [comment]
> gusy i am getting the same issue , can anyone help me please

you may have to open port 5222 in your aws security group.
