### ISSUE TITLE
Authentication failed after installing JWT token plugin  - Token not getting passed

### ISSUE THREAD

**Issue by rohitcoder** [jitsi/jitsi-meet#5991]
Hi @saghul @damencho , I already posted this question on the community forum, after not getting any reply i am posting it here.

I am passing token like this

https://sub.website.com/fe?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJjb250ZXh0Ijp7InVzZXIiOnsibmFtZSI6IkpvaG4gRG9lIiwiZW1haWwiOiJqZG9lQGV4YW1wbGUuY29tIn19LCJzdWIiOiJjYWwiLCJyb29tIjoiKiIsImV4cCI6MTU5NTUwNjAwMH0.v0KD8tKKu7cZaSg6HnQNzJctG2SSeazrG_pZb3Z29NQ

I am getting this in my jicofo logs.

```
Jicofo 2020-04-14 12:24:06.599 INFO: [262] org.jitsi.impl.protocol.xmpp.XmppProtocolProvider.reconnectingIn().690 XMPP reconnecting in: 1
Jicofo 2020-04-14 12:24:07.600 INFO: [262] org.jitsi.impl.protocol.xmpp.XmppProtocolProvider.reconnectingIn().690 XMPP reconnecting in: 0
Jicofo 2020-04-14 12:24:07.600 INFO: [262] org.jitsi.impl.protocol.xmpp.XmppProtocolProvider.reconnectingIn().690 XMPP reconnecting in: 0
Jicofo 2020-04-14 12:24:07.676 INFO: [262] org.jitsi.jicofo.ProtocolProviderHandler.registrationStateChanged().144 XmppProtocolProvider(focus@auth.subdomain.website.com/focus18797246841 (Jabber)): RegistrationStateChangeEvent[ oldState=Unregistered; newState=RegistrationState=Registered; reasonCode=-1; reason=null]
Jicofo 2020-04-14 12:24:07.680 INFO: [262] org.jitsi.jicofo.xmpp.BaseBrewery.start().186 Joined brewery room: JvbBrewery@internal.auth.subdomain.website.com
Jicofo 2020-04-14 12:24:07.682 INFO: [262] org.jitsi.jicofo.ComponentsDiscovery.log() New component discovered: conference.subdomain.website.com, null
Jicofo 2020-04-14 12:24:07.683 INFO: [262] org.jitsi.jicofo.JitsiMeetServices.log() MUC component discovered: conference.subdomain.website.com
Jicofo 2020-04-14 12:24:07.683 INFO: [262] org.jitsi.jicofo.ComponentsDiscovery.log() New component discovered: auth.subdomain.website.com, Prosody(trunk nightly build 747 (2017-02-19, 428d4abee723),Linux)
Jicofo 2020-04-14 12:24:07.683 INFO: [262] org.jitsi.jicofo.JitsiMeetServices.log() Detected XMPP server version: Prosody(trunk nightly build 747 (2017-02-19, 428d4abee723),Linux)
Jicofo 2020-04-14 12:24:07.684 INFO: [262] org.jitsi.jicofo.ComponentsDiscovery.log() Services re-discovery interval: 30000
Jicofo 2020-04-14 12:24:07.686 INFO: [262] org.jitsi.jicofo.FocusManager.log() XMPP provider reg state: RegistrationState=Registered
Jicofo 2020-04-14 12:24:10.720 INFO: [27] org.jitsi.jicofo.xmpp.BaseBrewery.processInstanceStatusChanged().329 Added brewery instance: jvbbrewery@internal.auth.subdomain.website.com/78be7eae-ad05-45e7-b1ba-6e2ced97ded1
Jicofo 2020-04-14 12:24:10.720 WARNING: [27] org.jitsi.jicofo.bridge.BridgeSelector.log() No pub-sub node mapped for jvbbrewery@internal.auth.subdomain.website.com/78be7eae-ad05-45e7-b1ba-6e2ced97ded1
Jicofo 2020-04-14 12:24:10.721 INFO: [27] org.jitsi.jicofo.bridge.BridgeSelector.log() Added new videobridge: Bridge[jid=jvbbrewery@internal.auth.subdomain.website.com/78be7eae-ad05-45e7-b1ba-6e2ced97ded1, relayId=null, region=null, stress=0.00]
Jicofo 2020-04-14 12:24:10.722 INFO: [84] org.jitsi.jicofo.bridge.JvbDoctor.log() Scheduled health-check task for: jvbbrewery@internal.auth.subdomain.website.com/78be7eae-ad05-45e7-b1ba-6e2ced97ded1
Jicofo 2020-04-14 12:24:11.055 SEVERE: [244] org.jivesoftware.whack.ExternalComponentManager.error()
java.net.SocketException: Broken pipe (Write failed)
        at java.net.SocketOutputStream.socketWrite0(Native Method)
        at java.net.SocketOutputStream.socketWrite(SocketOutputStream.java:111)
        at java.net.SocketOutputStream.write(SocketOutputStream.java:155)
        at sun.nio.cs.StreamEncoder.writeBytes(StreamEncoder.java:221)
        at sun.nio.cs.StreamEncoder.implFlushBuffer(StreamEncoder.java:291)
        at sun.nio.cs.StreamEncoder.implFlush(StreamEncoder.java:295)
        at sun.nio.cs.StreamEncoder.flush(StreamEncoder.java:141)
        at java.io.OutputStreamWriter.flush(OutputStreamWriter.java:229)
        at java.io.BufferedWriter.flush(BufferedWriter.java:254)
        at org.dom4j.io.XMLWriter.flush(XMLWriter.java:272)
        at org.jivesoftware.whack.ExternalComponent.send(ExternalComponent.java:371)
        at org.jivesoftware.whack.ExternalComponentManager.sendPacket(ExternalComponentManager.java:269)
        at org.xmpp.component.AbstractComponent.send(AbstractComponent.java:925)
        at org.jitsi.xmpp.component.ComponentBase.access$400(ComponentBase.java:36)
        at org.jitsi.xmpp.component.ComponentBase$PingTask.run(ComponentBase.java:577)
        at java.util.TimerThread.mainLoop(Timer.java:555)
        at java.util.TimerThread.run(Timer.java:505)
Jicofo 2020-04-14 12:24:16.058 SEVERE: [267] org.jitsi.xmpp.component.ComponentBase.log() Ping timeout for ID: 56E40-15661
Jicofo 2020-04-14 12:24:37.686 INFO: [265] org.jitsi.jicofo.ComponentsDiscovery.log() New component discovered: focus.subdomain.website.com, null
                                                                                                                                                                      
```
#### This is my browser console output
![Screenshot 2020-04-14 at 6 17 27 PM](https://user-images.githubusercontent.com/17665703/79226550-38ab0d00-7e7c-11ea-9f9d-492d766da301.png)

These are my attached logs.

1. jvb logs - https://pastebin.com/raw/yLrrGTS6
2. Prosody logs - https://pastebin.com/raw/SVBmVAmr
3. Jicofo logs - https://pastebin.com/raw/82Y6jrhq

I am really tired of solving this issue since last 4 days.

**Comment by rohitcoder** [comment]
2 XHR requests (/http-bin) were passed during these authentication processes.

## These are the responses.
```xml
<?xml version="1.0" encoding="UTF-8"?>
<body xmlns="http://jabber.org/protocol/httpbind" xmlns:stream="http://etherx.jabber.org/streams" xmlns:xmpp="urn:xmpp:xbosh" xmpp:version="1.0" ver="1.6" inactivity="60" requests="2" polling="5" secure="true" hold="1" from="subdomain.website.com" authid="999bb2cd-3b1c-4afd-869c-a02e356b7d1f" wait="60" sid="999bb2cd-3b1c-4afd-869c-a02e356b7d1f">
   <stream:features xmlns="jabber:client">
      <mechanisms xmlns="urn:ietf:params:xml:ns:xmpp-sasl">
         <mechanism>ANONYMOUS</mechanism>
      </mechanisms>
      <c xmlns="http://jabber.org/protocol/caps" ver="jkcAvH/wXgiwnmVryEbWr4PerZs=" hash="sha-1" node="http://prosody.im" />
   </stream:features>
</body>
```

```xml
<?xml version="1.0" encoding="UTF-8"?>
<body xmlns="http://jabber.org/protocol/httpbind" xmlns:stream="http://etherx.jabber.org/streams" sid="999bb2cd-3b1c-4afd-869c-a02e356b7d1f">
   <failure xmlns="urn:ietf:params:xml:ns:xmpp-sasl">
      <not-allowed />
      <text>token required</text>
   </failure>
</body>
```

**Comment by josuah** [comment]
It looks like you do not have the "iss":, "aud": and all other fields except "exp": from https://github.com/jitsi/lib-jitsi-meet/blob/master/doc/tokens.md

I had the same issue and adding them did work for me.

It is highly confusing as there is an error message about a token missing, while it is there passed to jitsi-meet javascript browser client.

I suppose the token-based authentication is dropped from the javascript during negociation between the client and server rather than just on the client, during transmission, or just on the server, but I have no real idea just guessing !

**Comment by josuah** [comment]
As a separate error, just like the log message says, you may have to adapt the permission on the private key: `SSL/TLS: Failed to load '/etc/prosody/certs/localhost.key'` indicates that prosody (prosody user iirc) cannot read.

Try `su -l prosody -s /bin/bash` and then `cat /etc/prosody/certs/localhost.key` for instance.
