### ISSUE TITLE
Dependency on Python 2 due to outdated node-gyp

### ISSUE THREAD

**Issue by C0rn3j** [jitsi/jitsi-meet#6427]
`package-lock.json` has an old version of node-gyp, which is dependent on Python 2.

```
    "node-gyp": {
      "version": "3.8.0",
```

Python 2 has reached End of Life, so it'd be a good idea if jitsi-meet also built fine with Python 3.

```
gyp ERR! configure error 
gyp ERR! stack Error: Command failed: /usr/sbin/python -c import sys; print "%s.%s.%s" % sys.version_info[:3];
gyp ERR! stack   File "<string>", line 1
gyp ERR! stack     import sys; print "%s.%s.%s" % sys.version_info[:3];
gyp ERR! stack                       ^
gyp ERR! stack SyntaxError: invalid syntax
gyp ERR! stack 
gyp ERR! stack     at ChildProcess.exithandler (child_process.js:303:12)
gyp ERR! stack     at ChildProcess.emit (events.js:315:20)
gyp ERR! stack     at maybeClose (internal/child_process.js:1051:16)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:287:5)
gyp ERR! System Linux 5.6.7-arch1-1
gyp ERR! command "/usr/bin/node" "/home/c0rn3j/trizen/jitsi-meet-git/src/jitsi-meet-git/node_modules/node-gyp/bin/node-gyp.js" "rebuild" "--verbose" "--libsass_ext=" "--libsass_cflags=" "--libsass_ldflags=" "--libsass_library="
gyp ERR! cwd /home/c0rn3j/trizen/jitsi-meet-git/src/jitsi-meet-git/node_modules/node-sass
gyp ERR! node -v v14.0.0
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok 
```

Tested on Arch Linux with Python 3.8.2

**Comment by saghul** [comment]
Looks we need to update node-sass:

```
jitsi-meet@0.0.0 /Users/saghul/work/jitsi/jitsi-meet
└─┬ node-sass@4.13.1
  └── node-gyp@3.8.0
```

**Comment by saghul** [comment]
Actually, node-sass is the package that needs updating first: https://github.com/sass/node-sass/blob/aa193f6334e45ae065cc64d67498acfad9fad4d9/package.json#L67

I'd suggest you open an issue there.

**Comment by C0rn3j** [comment]
https://github.com/sass/node-sass/issues/2877
Seems like they already fixed that in the upcoming release

**Comment by C0rn3j** [comment]
As per https://github.com/sass/node-sass/issues/2877#issuecomment-645018985, there seems to be a replacement library that does not depend on Python 2.

https://sass-lang.com/dart-sass

**Comment by saghul** [comment]
Thanks for the heads up @C0rn3j ! I gave it a quick try on this branch https://github.com/jitsi/jitsi-meet/tree/replace-sass, but doesn't seem to be a drop-in replacement (or node-sass was more lenient with some stuff):

```
$ make deploy-css
./node_modules/.bin/sass css/main.scss css/all.bundle.css && \
	./node_modules/.bin/cleancss css/all.bundle.css > css/all.css ; \
	rm css/all.bundle.css
Error: Expected identifier.
  ╷
1 │ .jitsi-icon {
  │              ^
  ╵
  css/_meter.css 1:14  @import
  css/main.scss 92:9   root stylesheet
```

**Comment by C0rn3j** [comment]
Not stale
