### ISSUE TITLE
Failed to load class "org.slf4j.impl.StaticLoggerBinder"

### ISSUE THREAD

**Issue by jungle-boogie** [jitsi/jitsi-meet#65]
Brand new VPS:
# ./jitsivideo/jvb.sh --host=localhost --domain=chat.example.net --port=5347 --secret=emiljitsi

SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
Exception in thread "main" org.xmpp.component.ComponentException: host-unknown
        at org.jivesoftware.whack.ExternalComponent.connect(ExternalComponent.java:219)
        at org.jivesoftware.whack.ExternalComponentManager.addComponent(ExternalComponentManager.java:221)
        at org.jivesoftware.whack.ExternalComponentManager.addComponent(ExternalComponentManager.java:201)
        at org.jitsi.videobridge.Main.main(Main.java:173)

http://www.slf4j.org/codes.html#StaticLoggerBinder shows:
This error is reported when the org.slf4j.impl.StaticLoggerBinder class could not be loaded into memory. This happens when no appropriate SLF4J binding could be found on the class path. Placing one (and only one) of slf4j-nop.jar, slf4j-simple.jar, slf4j-log4j12.jar, slf4j-jdk14.jar or logback-classic.jar on the class path should solve the problem. 

Which do I need to load and where?

**Comment by mcharris** [comment]
I just wanted to leave my fix for this.
Looks like it was listening on host 127.0.0.1 and was rejecting the hostname localhost for me. I changed the flag --host to --host=127.0.0.1 and this fixed my issue. Hope this helps others.

**Comment by EyeInTheSky3000** [comment]
@mcharris :+1: that hint helps me a lot (adapted jicofo-config to 127.0.0.1)
