### ISSUE TITLE
LinearGradientPackage Class Not Found

### ISSUE THREAD

**Issue by GauravAndroidIS** [jitsi/jitsi-meet#6544]
Hey,

I have successfully build the sdk and now when i have imported the .aar file of jitsi meet sdk in an sample application and launching the video conference on MainActivity i am getting error LinearGradientPackage Class Not Found. I have checked that in sdk LinearGradientPackage is imported also. Please help me i am stuck and not able to move forward because of this

2020-05-03 03:12:07.560 8256-8256/? E/com.myvideocal: Unknown bits set in runtime_flags: 0x8000
2020-05-03 03:12:08.062 8256-8350/com.myvideocall E/Perf: Fail to get file list com.myvideocall
2020-05-03 03:12:08.062 8256-8350/com.myvideocall E/Perf: getFolderSize() : Exception_1 = java.lang.NullPointerException: Attempt to get length of null array
2020-05-03 03:12:08.062 8256-8350/com.myvideocall E/Perf: Fail to get file list com.myvideocall
2020-05-03 03:12:08.062 8256-8350/com.myvideocall E/Perf: getFolderSize() : Exception_1 = java.lang.NullPointerException: Attempt to get length of null array
2020-05-03 03:12:08.224 8256-8256/com.myvideocall E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.myvideocall, PID: 8256
    java.lang.NoClassDefFoundError: Failed resolution of: Lcom/BV/LinearGradient/LinearGradientPackage;
        at org.jitsi.meet.sdk.ReactInstanceManagerHolder.initReactInstanceManager(ReactInstanceManagerHolder.java:186)
        at org.jitsi.meet.sdk.BaseReactView.<init>(BaseReactView.java:114)
        at org.jitsi.meet.sdk.MyMeetView.<init>(MyMeetView.java:98)
        at org.jitsi.meet.sdk.MyMeetFragment.onCreateView(MyMeetFragment.java:53)
        at androidx.fragment.app.Fragment.performCreateView(Fragment.java:2600)
        at androidx.fragment.app.FragmentManagerImpl.ensureInflatedFragmentView(FragmentManagerImpl.java:1138)
        at androidx.fragment.app.FragmentManagerImpl.moveToState(FragmentManagerImpl.java:851)
        at androidx.fragment.app.FragmentManagerImpl.moveToState(FragmentManagerImpl.java:1133)
        at androidx.fragment.app.FragmentManagerImpl.addFragment(FragmentManagerImpl.java:1393)
        at androidx.fragment.app.FragmentManagerImpl.onCreateView(FragmentManagerImpl.java:3205)
        at androidx.fragment.app.FragmentController.onCreateView(FragmentController.java:134)
        at androidx.fragment.app.FragmentActivity.dispatchFragmentsOnCreateView(FragmentActivity.java:357)
        at androidx.fragment.app.FragmentActivity.onCreateView(FragmentActivity.java:336)
        at android.view.LayoutInflater.tryCreateView(LayoutInflater.java:1069)
        at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:997)
        at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:961)
        at android.view.LayoutInflater.rInflate(LayoutInflater.java:1123)
        at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:1084)
        at android.view.LayoutInflater.inflate(LayoutInflater.java:682)
        at android.view.LayoutInflater.inflate(LayoutInflater.java:534)
        at android.view.LayoutInflater.inflate(LayoutInflater.java:481)
        at com.android.internal.policy.PhoneWindow.setContentView(PhoneWindow.java:470)
        at android.app.Activity.setContentView(Activity.java:3342)
        at org.jitsi.meet.sdk.MyMeetActivity.onCreate(MyMeetActivity.java:68)
        at com.myvideocall.MainActivity.onCreate(MainActivity.kt:14)
        at android.app.Activity.performCreate(Activity.java:7820)
        at android.app.Activity.performCreate(Activity.java:7809)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1318)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3362)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3526)
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:83)
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2122)
        at android.os.Handler.dispatchMessage(Handler.java:107)
        at android.os.Looper.loop(Looper.java:214)
        at android.app.ActivityThread.main(ActivityThread.java:7695)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:516)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:950)
     Caused by: java.lang.ClassNotFoundException: Didn't find class "com.BV.LinearGradient.LinearGradientPackage" on path: DexPathList[[zip file "/data/app/com.myvideocall-ouD2sYC8dCIsXrZ5825usw==/base.apk"],nativeLibraryDirectories=[/data/app/com.myvideocall-ouD2sYC8dCIsXrZ5825usw==/lib/arm64, /data/app/com.myvideocall-ouD2sYC8dCIsXrZ5825usw==/base.apk!/lib/arm64-v8a, /system/lib64, /system/product/lib64]]
        at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:196)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
        at org.jitsi.meet.sdk.ReactInstanceManagerHolder.initReactInstanceManager(ReactInstanceManagerHolder.java:186) 
        at org.jitsi.meet.sdk.BaseReactView.<init>(BaseReactView.java:114) 
        at org.jitsi.meet.sdk.MyMeetView.<init>(MyMeetView.java:98) 
        at org.jitsi.meet.sdk.MyMeetFragment.onCreateView(MyMeetFragment.java:53) 
        at androidx.fragment.app.Fragment.performCreateView(Fragment.java:2600) 
        at androidx.fragment.app.FragmentManagerImpl.ensureInflatedFragmentView(FragmentManagerImpl.java:1138) 
        at androidx.fragment.app.FragmentManagerImpl.moveToState(FragmentManagerImpl.java:851) 
        at androidx.fragment.app.FragmentManagerImpl.moveToState(FragmentManagerImpl.java:1133) 
        at androidx.fragment.app.FragmentManagerImpl.addFragment(FragmentManagerImpl.java:1393) 
        at androidx.fragment.app.FragmentManagerImpl.onCreateView(FragmentManagerImpl.java:3205) 
        at androidx.fragment.app.FragmentController.onCreateView(FragmentController.java:134) 
        at androidx.fragment.app.FragmentActivity.dispatchFragmentsOnCreateView(FragmentActivity.java:357) 
        at androidx.fragment.app.FragmentActivity.onCreateView(FragmentActivity.java:336) 
        at android.view.LayoutInflater.tryCreateView(LayoutInflater.java:1069) 
        at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:997) 
        at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:961) 
        at android.view.LayoutInflater.rInflate(LayoutInflater.java:1123) 
        at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:1084) 
        at android.view.LayoutInflater.inflate(LayoutInflater.java:682) 
        at android.view.LayoutInflater.inflate(LayoutInflater.java:534) 
        at android.view.LayoutInflater.inflate(LayoutInflater.java:481) 
        at com.android.internal.policy.PhoneWindow.setContentView(PhoneWindow.java:470) 
        at android.app.Activity.setContentView(Activity.java:3342) 
        at org.jitsi.meet.sdk.MyMeetActivity.onCreate(MyMeetActivity.java:68) 
        at com.myvideocall.MainActivity.onCreate(MainActivity.kt:14) 
        at android.app.Activity.performCreate(Activity.java:7820) 
        at android.app.Activity.performCreate(Activity.java:7809) 
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1318) 
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3362) 
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3526) 
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:83) 
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135) 
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2122) 
        at android.os.Handler.dispatchMessage(Handler.java:107) 
        at android.os.Looper.loop(Looper.java:214) 
        at android.app.ActivityThread.main(ActivityThread.java:7695) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:516) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:950)

**Comment by saghul** [comment]
You need a lot more than the aar. You also need all other dependencies.

You can either use our maven repo or the helper script to deploy all dependence’s to your own repo, check the README on android/
