### ISSUE TITLE
Jigasi SIP bridge docker container problem

### ISSUE THREAD

**Issue by tayfundogdas** [jitsi/jitsi-meet#6625]
## Description
I am trying to use jigasi docker image version stable-4548 but when container spins up it gives below error. I think jigasi works like that

SIP packages <-> JMF (java media framework that depends on openjdk’s native libgdk for sound packages processing) processing <-> jitsi webrtc’s rtp channel so currently openjdk’s jmf implementation depends on libgdk is failing, anybody has fix for this? What do you think @saghul? I think you are doing docker things in project.

Jigasi 2020-05-06 18:09:35.526 WARNING: [10] impl.sysactivity.SystemActivityNotifications.().141 Failed to initialize native counterpart

java.lang.UnsatisfiedLinkError: /tmp/jna–1160142225/jna5123708535587887352.tmp: libgdk-x11-2.0.so.0: cannot open shared object file: No such file or directory

at java.lang.ClassLoader$NativeLibrary.load(Native Method)

at java.lang.ClassLoader.loadLibrary0(ClassLoader.java:1934)

at java.lang.ClassLoader.loadLibrary(ClassLoader.java:1817)

at java.lang.Runtime.load0(Runtime.java:809)

at java.lang.System.load(System.java:1088)

at org.jitsi.util.JNIUtils.loadLibrary(JNIUtils.java:96)

at org.jitsi.util.JNIUtils.loadLibrary(JNIUtils.java:37)

at net.java.sip.communicator.impl.sysactivity.SystemActivityNotifications.(SystemActivityNotifications.java:125)

at net.java.sip.communicator.impl.sysactivity.SystemActivityNotificationsServiceImpl.isSupported(SystemActivityNotificationsServiceImpl.java:606)

at net.java.sip.communicator.impl.sysactivity.SystemActivityNotificationsServiceImpl.start(SystemActivityNotificationsServiceImpl.java:143)

at net.java.sip.communicator.impl.sysactivity.SysActivityActivator.start(SysActivityActivator.java:70)

at org.jitsi.impl.osgi.framework.BundleImpl.start(BundleImpl.java:307)

at org.jitsi.impl.osgi.framework.launch.FrameworkImpl.startLevelChanged(FrameworkImpl.java:472)

at org.jitsi.impl.osgi.framework.startlevel.FrameworkStartLevelImpl$Command.run(FrameworkStartLevelImpl.java:137)

at org.jitsi.impl.osgi.framework.AsyncExecutor.runInThread(AsyncExecutor.java:122)

at org.jitsi.impl.osgi.framework.AsyncExecutor.access$000(AsyncExecutor.java:28)

at org.jitsi.impl.osgi.framework.AsyncExecutor$1.run(AsyncExecutor.java:231)

Jigasi 2020-05-06 18:09:35.640 SEVERE: [10] impl.sysactivity.NetworkManagerListenerImpl.().60 Cannot obtain dbus connection

org.freedesktop.dbus.exceptions.DBusException: Failed to connect to bus No such file or directory

at org.freedesktop.dbus.DBusConnection.(Unknown Source)

at org.freedesktop.dbus.DBusConnection.getConnection(Unknown Source)

at net.java.sip.communicator.impl.sysactivity.NetworkManagerListenerImpl.(NetworkManagerListenerImpl.java:56)

at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)

at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)

at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)

at java.lang.reflect.Constructor.newInstance(Constructor.java:423)

at java.lang.Class.newInstance(Class.java:442)

at net.java.sip.communicator.impl.sysactivity.SystemActivityNotificationsServiceImpl.getCurrentRunningManager(SystemActivityNotificationsServiceImpl.java:643)

at net.java.sip.communicator.impl.sysactivity.SystemActivityNotificationsServiceImpl.start(SystemActivityNotificationsServiceImpl.java:154)

at net.java.sip.communicator.impl.sysactivity.SysActivityActivator.start(SysActivityActivator.java:70)

at org.jitsi.impl.osgi.framework.BundleImpl.start(BundleImpl.java:307)

at org.jitsi.impl.osgi.framework.launch.FrameworkImpl.startLevelChanged(FrameworkImpl.java:472)

at org.jitsi.impl.osgi.framework.startlevel.FrameworkStartLevelImpl$Command.run(FrameworkStartLevelImpl.java:137)

at org.jitsi.impl.osgi.framework.AsyncExecutor.runInThread(AsyncExecutor.java:122)

at org.jitsi.impl.osgi.framework.AsyncExecutor.access$000(AsyncExecutor.java:28)

at org.jitsi.impl.osgi.framework.AsyncExecutor$1.run(AsyncExecutor.java:231)

Jigasi 2020-05-06 18:09:36.727 SEVERE: [10] org.jitsi.impl.neomedia.device.DeviceConfiguration.log() Failed to register custom Renderer org.jitsi.impl.neomedia.jmfext.media.renderer.audio.PulseAudioRenderer with JMF.

java.lang.IllegalStateException: audioSystem

at org.jitsi.impl.neomedia.jmfext.media.renderer.audio.PulseAudioRenderer.(PulseAudioRenderer.java:156)

at org.jitsi.impl.neomedia.jmfext.media.renderer.audio.PulseAudioRenderer.(PulseAudioRenderer.java:136)

at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)

at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)

at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)

at java.lang.reflect.Constructor.newInstance(Constructor.java:423)

at java.lang.Class.newInstance(Class.java:442)

at org.jitsi.impl.neomedia.device.DeviceConfiguration.registerCustomRenderers(DeviceConfiguration.java:1047)

at org.jitsi.impl.neomedia.device.DeviceConfiguration.(DeviceConfiguration.java:366)

at org.jitsi.impl.neomedia.MediaServiceImpl.(MediaServiceImpl.java:162)

at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)

at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)

at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)

at java.lang.reflect.Constructor.newInstance(Constructor.java:423)

at java.lang.Class.newInstance(Class.java:442)

at org.jitsi.impl.libjitsi.LibJitsiImpl$ServiceLock.initializeService(LibJitsiImpl.java:196)

at org.jitsi.impl.libjitsi.LibJitsiImpl$ServiceLock.getService(LibJitsiImpl.java:131)

at org.jitsi.impl.libjitsi.LibJitsiImpl.getService(LibJitsiImpl.java:91)

at org.jitsi.impl.libjitsi.LibJitsiOSGiImpl.getService(LibJitsiOSGiImpl.java:95)

at org.jitsi.service.libjitsi.LibJitsi.invokeGetServiceOnImpl(LibJitsi.java:172)

at org.jitsi.service.libjitsi.LibJitsi.getMediaService(LibJitsi.java:124)

at net.java.sip.communicator.impl.neomedia.NeomediaActivator.start(NeomediaActivator.java:391)

at org.jitsi.impl.osgi.framework.BundleImpl.start(BundleImpl.java:307)

at org.jitsi.impl.osgi.framework.launch.FrameworkImpl.startLevelChanged(FrameworkImpl.java:472)

at org.jitsi.impl.osgi.framework.startlevel.FrameworkStartLevelImpl$Command.run(FrameworkStartLevelImpl.java:137)

at org.jitsi.impl.osgi.framework.AsyncExecutor.runInThread(AsyncExecutor.java:122)

at org.jitsi.impl.osgi.framework.AsyncExecutor.access$000(AsyncExecutor.java:28)

at org.jitsi.impl.osgi.framework.AsyncExecutor$1.run(AsyncExecutor.java:231)

## Current behavior
openjdk's JMF implemantation that depens on native libgdk is failing.

## Expected Behavior
JMF works correctly

## Possible Solution
jigasi docker container depends on base-java container which includes openjdk-8-jre-headless needs to be changed with working JMF implementation in it.

## Steps to reproduce
Run jigasi container version stable-4548 and look the console logs.

# Environment details
docker + jigasi container version stable-4548

**Comment by damencho** [comment]
This is not JMF, but FMJ. You can ignore these exceptions. 

When you have questions or problems use the community forum before opening new issues.
If this is an issue at all it is not jitsi-meet one, it may be jigasi one or for docker-jitsi-meet repo.

**Comment by tayfundogdas** [comment]
@damencho sorry to put in wrong place, should I move this issue under jigasi or docker-jitsi-meet? Actually because of this exceptions entire jigasi component not working so basically not ignorable I think.

**Comment by damencho** [comment]
Nope, those exceptions are normal. 
Maybe describe what is not working and attach logs of not working sessions. 
I cannot decide where to put the issue before identifying it, that's why we want to discuss problems in the forum first before opening an issue.
