### ISSUE TITLE
Jitsi Meet Android SDK 2.8.2 - libhermes.so

### ISSUE THREAD

**Issue by StuStirling** [jitsi/jitsi-meet#6635]
## Description
I have integrated the Jitsi android SDK into my Android application. It works great during development but when I generate a release version which uses R8, it crashes when I try and open the `JitsiMeetActivity`. 

This is how include the SDK:

`implementation ('org.jitsi.react:jitsi-meet-sdk:2.8.2') { transitive = true }`

### Proguard
This is the proguard file I use taken from [here](https://github.com/jitsi/jitsi-meet/blob/master/android/app/proguard-rules.pro)

```groovy
# https://github.com/jitsi/jitsi-meet/blob/master/android/app/proguard-rules.pro

# React Native

# Keep our interfaces so they can be used by other ProGuard rules.
# See http://sourceforge.net/p/proguard/bugs/466/
-keep,allowobfuscation @interface com.facebook.proguard.annotations.DoNotStrip
-keep,allowobfuscation @interface com.facebook.proguard.annotations.KeepGettersAndSetters
-keep,allowobfuscation @interface com.facebook.common.internal.DoNotStrip

# Do not strip any method/class that is annotated with @DoNotStrip
-keep @com.facebook.proguard.annotations.DoNotStrip class *
-keep @com.facebook.common.internal.DoNotStrip class *
-keepclassmembers class * {
    @com.facebook.proguard.annotations.DoNotStrip *;
    @com.facebook.common.internal.DoNotStrip *;
}

-keepclassmembers @com.facebook.proguard.annotations.KeepGettersAndSetters class * {
  void set*(***);
  *** get*();
}

-keep class * extends com.facebook.react.bridge.JavaScriptModule { *; }
-keep class * extends com.facebook.react.bridge.NativeModule { *; }
-keepclassmembers,includedescriptorclasses class * { native <methods>; }
-keepclassmembers class *  { @com.facebook.react.uimanager.UIProp <fields>; }
-keepclassmembers class *  { @com.facebook.react.uimanager.annotations.ReactProp <methods>; }
-keepclassmembers class *  { @com.facebook.react.uimanager.annotations.ReactPropGroup <methods>; }

-dontwarn com.facebook.react.**
-keep,includedescriptorclasses class com.facebook.react.bridge.** { *; }

# okhttp

-keepattributes Signature
-keepattributes *Annotation*
-keep class okhttp3.** { *; }
-keep interface okhttp3.** { *; }
-dontwarn okhttp3.**

# okio

-keep class sun.misc.Unsafe { *; }
-dontwarn java.nio.file.*
-dontwarn org.codehaus.mojo.animal_sniffer.IgnoreJRERequirement
-keep class okio.** { *; }
-dontwarn okio.**

# WebRTC

-keep class org.webrtc.** { *; }
-dontwarn org.chromium.build.BuildHooksAndroid

# Jisti Meet SDK

-keep class org.jitsi.meet.** { *; }
-keep class org.jitsi.meet.sdk.** { *; }

# We added the following when we switched minifyEnabled on. Probably because we
# ran the app and hit problems...

-keep class com.facebook.react.bridge.CatalystInstanceImpl { *; }
-keep class com.facebook.react.bridge.ExecutorToken { *; }
-keep class com.facebook.react.bridge.JavaScriptExecutor { *; }
-keep class com.facebook.react.bridge.ModuleRegistryHolder { *; }
-keep class com.facebook.react.bridge.ReadableType { *; }
-keep class com.facebook.react.bridge.queue.NativeRunnable { *; }
-keep class com.facebook.react.devsupport.** { *; }

-dontwarn com.facebook.react.devsupport.**
-dontwarn com.google.appengine.**
-dontwarn com.squareup.okhttp.**
-dontwarn javax.servlet.**

# ^^^ We added the above when we switched minifyEnabled on.

# Rule to avoid build errors related to SVGs.
-keep public class com.horcrux.svg.** {*;}

# Hermes
-keep class com.facebook.hermes.unicode.** { *; }
```

## Current behavior
Crashing upon launch of the `JitsiMeetActivity`

```
2020-05-10 00:49:09.177 E/SoLoader: couldn't find DSO to load: libhermes.so caused by: com.facebook.jni.HybridData$Destructor
    
    --------- beginning of crash
2020-05-10 00:49:09.178 E/AndroidRuntime: FATAL EXCEPTION: create_react_context
    Process: com.padoq.android.develop, PID: 2341
    java.lang.UnsatisfiedLinkError: couldn't find DSO to load: libhermes.so caused by: com.facebook.jni.HybridData$Destructor
        at com.facebook.soloader.SoLoader.a(SoLoader.java:124)
        at com.facebook.soloader.SoLoader.a(SoLoader.java:62)
        at com.facebook.soloader.SoLoader.a(SoLoader.java:44)
        at com.facebook.soloader.SoLoader.a(SoLoader.java:29)
        at j.e.i.a.a.<clinit>(HermesExecutor.java:1)
        at j.e.i.a.b.create(HermesExecutorFactory.java:1)
        at j.e.m.l$b.run(ReactInstanceManager.java:10)
        at java.lang.Thread.run(Thread.java:919)
2020-05-10 00:49:09.178 E/JitsiMeetSDK: JitsiMeetUncaughtExceptionHandler FATAL ERROR
    java.lang.UnsatisfiedLinkError: couldn't find DSO to load: libhermes.so caused by: com.facebook.jni.HybridData$Destructor
        at com.facebook.soloader.SoLoader.a(SoLoader.java:124)
        at com.facebook.soloader.SoLoader.a(SoLoader.java:62)
        at com.facebook.soloader.SoLoader.a(SoLoader.java:44)
        at com.facebook.soloader.SoLoader.a(SoLoader.java:29)
        at j.e.i.a.a.<clinit>(HermesExecutor.java:1)
        at j.e.i.a.b.create(HermesExecutorFactory.java:1)
        at j.e.m.l$b.run(ReactInstanceManager.java:10)
        at java.lang.Thread.run(Thread.java:919)
    
    java.lang.UnsatisfiedLinkError: couldn't find DSO to load: libhermes.so caused by: com.facebook.jni.HybridData$Destructor
        at com.facebook.soloader.SoLoader.a(SoLoader.java:124)
        at com.facebook.soloader.SoLoader.a(SoLoader.java:62)
        at com.facebook.soloader.SoLoader.a(SoLoader.java:44)
        at com.facebook.soloader.SoLoader.a(SoLoader.java:29)
        at j.e.i.a.a.<clinit>(HermesExecutor.java:1)
        at j.e.i.a.b.create(HermesExecutorFactory.java:1)
        at j.e.m.l$b.run(ReactInstanceManager.java:10)
        at java.lang.Thread.run(Thread.java:919)
```

## Expected Behavior
The app does not crash when launching the `JitsiMeetActivity`

## Possible Solution
---

## Steps to reproduce
Follow the guide for integrating the SDK

# Environment details
Android Studio 3.6.3
Gradle Tools 3.6.3
Jitsi Meet Version 2.8.2

**Comment by saghul** [comment]
Does disabling R8 have any impact?

**Comment by StuStirling** [comment]
Thanks for the response @saghul

Yes, disabled R8 by changing the following values in my main module's `build.gradle` release build type then allows it to work.

```groovy
minifyEnabled false
shrinkResources false
```

**Comment by saghul** [comment]
I updated our sample apps here: https://github.com/jitsi/jitsi-meet-sdk-samples and couldn't repro the problem.

**Comment by StuStirling** [comment]
I also ran the updated sample without any issues... This led me to think it was my own proguard configurations conflicting with the jitsimeet proguard configurations. I copied over my proguard configurations into the sample project and it ran fine again...

I then ran through and each time it complained about missing classes, I added these to the proguard configuration. The SDK then worked in release:

```
-keep class com.facebook.jni.** { *; }
-keep class com.facebook.hermes.reactexecutor.HermesExecutor
-keep class com.facebook.react.modules.blob.BlobCollector
-keep class com.squareup.duktape.** { *; }
```

**Comment by saghul** [comment]
Interesting! Would you mind sending a PR addding those?
