### ISSUE TITLE
Runing jitsi-meet and video-bridge on same port 443

### ISSUE THREAD

**Issue by ips972** [jitsi/jitsi-meet#6807]
Hi Every one,

would really appreciate any help - really urgent.

I have been running installs and reinstall from every guide i could find.
I'm new to jitsi and its very important to me to be able to serve jitsi meet web and video on TCP/443
and not the UDP/10000.
the people i need connecting to the server run behind strict proxy that allow only TCP:80 or 443.
direct UDP/10000 through that or directly is not possible.
the server is behind NAT (FW holds the real world IP)

i installed a new ubuntu 19.10 and ran jitsi install guide with apt-get install
First install the Jitsi repository key onto your system:
wget -qO - https://download.jitsi.org/jitsi-key.gpg.key | sudo apt-key add -
Create a sources.list.d file with the repository:
sudo sh -c "echo 'deb https://download.jitsi.org stable/' > /etc/apt/sources.list.d/jitsi-stable.list"
Update your package list:
sudo apt-get -y update
Install the full suite:
sudo apt-get -y install jitsi-meet

All went fine. default server config runs great. (using my own certs)

Up to here server works fine.

i then used UFW to allow only port 443 and block UDP/10000

also tried changing the /etc/jitsi/meet/-config.js settings to disable UDP:

webrtcIceUdpDisable: true,

I disabled STUN servers and disabled P2P.

I've tried this guide: https://github.com/jitsi/jitsi-videobridge/blob/master/doc/http.md
but this doesn't work or I don't understand what needs to be changed in the sip properties.

but as soon as second party joins the test meeting both are thrown out with

if I bring back the installation sip.properties file from apt installation server works again.
(also reenable UDP 10000 in config.js)

I'm a real noob (sorry to say) to this and would really appreciate a fool proof guide.

the errors in JVB.log:
2020-05-17 20:14:04.111 SEVERE: [25] AbstractHealthCheckService.run#174: Health check failed in PT0S:
java.lang.Exception: No XMPP components
at org.jitsi.videobridge.health.Health.checkXmppConnection(Health.java:124)
at org.jitsi.videobridge.health.Health.performCheck(Health.java:203)
at org.jitsi.health.AbstractHealthCheckService.run(AbstractHealthCheckService.kt:144)
at org.jitsi.utils.concurrent.RecurringRunnableExecutor.run(RecurringRunnableExecutor.java:216)
at org.jitsi.utils.concurrent.RecurringRunnableExecutor.runInThread(RecurringRunnableExecutor.java:292)
at org.jitsi.utils.concurrent.RecurringRunnableExecutor.access$000(RecurringRunnableExecutor.java:36)
at org.jitsi.utils.concurrent.RecurringRunnableExecutor$1.run(RecurringRunnableExecutor.java:328)
2020-05-17 20:14:04.728 SEVERE: [29] ComponentMain.lambda$getConnectCallable$0#293: host-unknown, host:localhost, port:5347
org.xmpp.component.ComponentException: host-unknown
at org.jivesoftware.whack.ExternalComponent.connect(ExternalComponent.java:243)
at org.jivesoftware.whack.ExternalComponentManager.addComponent(ExternalComponentManager.java:242)
at org.jivesoftware.whack.ExternalComponentManager.addComponent(ExternalComponentManager.java:222)
at org.jitsi.meet.ComponentMain.lambda$getConnectCallable$0(ComponentMain.java:285)
at org.jitsi.retry.RetryStrategy$TaskRunner.run(RetryStrategy.java:193)
at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
at java.util.concurrent.FutureTask.run(FutureTask.java:266)
at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
at java.lang.Thread.run(Thread.java:748)

The errors I see in Jicofo jogs:
Jicofo 2020-05-17 19:54:25.875 WARNING: [69] org.jitsi.jicofo.bridge.BridgeSelectionStrategy.log() Failed to select initial bridge for participantRegion=null
Jicofo 2020-05-17 19:54:25.875 SEVERE: [69] org.jitsi.jicofo.JitsiMeetConferenceImpl.log() Can not invite participant -- no bridge available.
Jicofo 2020-05-17 19:54:25.875 WARNING: [69] org.jitsi.jicofo.bridge.BridgeSelectionStrategy.log() Failed to select initial bridge for participantRegion=null
Jicofo 2020-05-17 19:54:25.875 SEVERE: [69] org.jitsi.jicofo.JitsiMeetConferenceImpl.log() Can not invite participant -- no bridge available.

**Comment by luixxiul** [comment]
Did you try 4443/tcp?

https://jitsi.github.io/handbook/docs/devops-guide/devops-guide-quickstart#setup-and-configure-your-firewall

**Comment by damencho** [comment]
@ips972 Please do not post issues in all trackers. That will not increase the chance of someone answering, you will rather annoy people and not get an answer. And the tracker is not the place for questions, the correct location is the community forum.

**Comment by ips972** [comment]
> @ips972 Please do not post issues in all trackers. That will not increase the chance of someone answering, you will rather annoy people and not get an answer. And the tracker is not the place for questions, the correct location is the community forum.

I hear you, but Its urgent, wont happen again.. can you please point me to the solution to my problem?

**Comment by luixxiul** [comment]
@ips972 See https://github.com/jitsi/jitsi-meet/issues/6807#issuecomment-631625593

**Comment by ips972** [comment]
> Did you try 4443/tcp?
> 
> https://jitsi.github.io/handbook/docs/devops-guide/devops-guide-quickstart#setup-and-configure-your-firewall

port 4443 works and there is no problem using it through firewall that's configured to NAT it in from real ip to the servers Ip. 

BUT this is not the answer i'm looking for since the users coming in from restrictive proxy servers can only use tcp port 80 or 443 to leave their organizations using a browser that's proxy enabled. 

thats why UDP 10000 can't work either.. 

I really need a step by step guide to how to build this jitsi server to use only 443. 

i can use another solution where as the jitsi-meet + jicofo + prosody are on first server and video bridge (xmpp) server on second server and that way both running on separate servers and configured to use TCP/443 with out both services clashing.. 

but I can't find a single guide or procedure on how to build this setup as two separate servers.. (same goes to the situation where i want singe front end running meet and multiple back end servers with video bridge xmpp ... 

the documentation to this is really hard to get or hidden in the dark web :-)

**Comment by luixxiul** [comment]
Please consult with the forum https://community.jitsi.org here. There is no tailored documentation for your case.

**Comment by damencho** [comment]
> I really need a step by step guide to how to build this jitsi server to use only 443.

As I already answered you in the other thread in jvb repo, this is the default behavior on a clean install.

**Comment by damencho** [comment]
For completeness https://github.com/jitsi/jitsi-videobridge/issues/1263
