### ISSUE TITLE
RNCNetInfo.getCurrentState got 2 arguments, expected 3

### ISSUE THREAD

**Issue by baotoan1905** [jitsi/jitsi-meet#6812]
## Description
App Crash in android when start calling
---

## Current behavior
App Crash when start calling meeting
---

## Expected Behavior
Works fine without crash
---

## Possible Solution
---

## Steps to reproduce
---

# Environment details
react-native 0.61.5
jitsi meet sdk 2.8.0
Hermes enabled
---
Android exception
`E/AndroidRuntime: FATAL EXCEPTION: mqt_native_modules
    Process: com.awesomegroup.ngagerV2.debug, PID: 5673
    com.facebook.react.bridge.NativeArgumentsParseException: RNCNetInfo.getCurrentState got 2 arguments, expected 3
        at com.facebook.react.bridge.JavaMethodWrapper.invoke(JavaMethodWrapper.java:348)
        at com.facebook.react.bridge.JavaModuleWrapper.invoke(JavaModuleWrapper.java:150)
        at com.facebook.react.bridge.queue.NativeRunnable.run(Native Method)
        at android.os.Handler.handleCallback(Handler.java:873)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:26)
        at android.os.Looper.loop(Looper.java:214)
        at com.facebook.react.bridge.queue.MessageQueueThreadImpl$4.run(MessageQueueThreadImpl.java:225)
        at java.lang.Thread.run(Thread.java:764)
E/JitsiMeetSDK: JitsiMeetUncaughtExceptionHandler FATAL ERROR
    com.facebook.react.bridge.NativeArgumentsParseException: RNCNetInfo.getCurrentState got 2 arguments, expected 3
        at com.facebook.react.bridge.JavaMethodWrapper.invoke(JavaMethodWrapper.java:348)
        at com.facebook.react.bridge.JavaModuleWrapper.invoke(JavaModuleWrapper.java:150)
        at com.facebook.react.bridge.queue.NativeRunnable.run(Native Method)
        at android.os.Handler.handleCallback(Handler.java:873)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:26)
        at android.os.Looper.loop(Looper.java:214)
        at com.facebook.react.bridge.queue.MessageQueueThreadImpl$4.run(MessageQueueThreadImpl.java:225)
        at java.lang.Thread.run(Thread.java:764)
    
    com.facebook.react.bridge.NativeArgumentsParseException: RNCNetInfo.getCurrentState got 2 arguments, expected 3
        at com.facebook.react.bridge.JavaMethodWrapper.invoke(JavaMethodWrapper.java:348)
        at com.facebook.react.bridge.JavaModuleWrapper.invoke(JavaModuleWrapper.java:150)
        at com.facebook.react.bridge.queue.NativeRunnable.run(Native Method)
        at android.os.Handler.handleCallback(Handler.java:873)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:26)
        at android.os.Looper.loop(Looper.java:214)
        at com.facebook.react.bridge.queue.MessageQueueThreadImpl$4.run(MessageQueueThreadImpl.java:225)
        at java.lang.Thread.run(Thread.java:764)
D/AppCenterCrashes: Saving uncaught exception.`

**Comment by saghul** [comment]
Are you sing the SDK as is or building it yourself?

Can you reproduce it with the SDK samples?

**Comment by baotoan1905** [comment]
Hi saghul,
Thanks for replying,
Actually I'm using this package https://github.com/skrafft/react-native-jitsi-meet.
First I got an issue with hermes (which some guys from rocket chat asked), I followed discussion and upgrade jitsi sdk to 2.6.0, after upgrading, I get no more hermes issue, instead I got app crash issue whenever I call (JitsiMeet.call)
setTimeout(() => {
      const url = 'https://meet.jit.si/exemple';
      const userInfo = {
        displayName: 'User',
        email: 'user@example.com',
        avatar: 'https:/gravatar.com/avatar/abc123',
      };
      JitsiMeet.call(url, userInfo);
      /* You can also use JitsiMeet.audioCall(url) for audio only call */
      /* You can programmatically end the call with JitsiMeet.endCall() */
    }, 1000);
I'm using react native 0.61.5
Jitsi SDK 2.6.0( tried with 2.8.0 or 2.8.2 but same issue).
In my project, I'm also using netinfo. Not sure if it makes it conflict some how ?
Here is my package.json
`"@monterosa/react-native-parallax-scroll": "^1.0.4",
    "@react-native-community/art": "^1.2.0",
    "@react-native-community/async-storage": "^1.9.0",
    "@react-native-community/cameraroll": "^1.2.1",
    "@react-native-community/netinfo": "^5.5.1",
    "@react-native-community/push-notification-ios": "^1.1.1",
    "@react-native-community/slider": "^2.0.9",
    "@react-native-community/viewpager": "^3.3.0",
    "appcenter": "3.0.1",
    "appcenter-analytics": "3.0.1",
    "appcenter-crashes": "3.0.1",
    "color-convert": "^1.9.3",
    "create-react-class": "^15.6.2",
    "dateformat": "^2.0.0",
    "encodeurl": "^1.0.1",
    "expo-keep-awake": "^8.1.0",
    "i18next": "^19.0.1",
    "lodash": "^4.17.5",
    "lodash-node": "^3.10.2",
    "moment": "^2.22.2",
    "native-base": "^2.13.4",
    "ngager-icon": "github:ngager-group/ngager-icon#1.0.2",
    "prop-types": "^15.6.0",
    "pusher-js": "^5.1.1",
    "rc-form": "^2.2.0",
    "react": "16.11.0",
    "react-i18next": "^11.2.5",
    "react-native": "0.62.2",
    "react-native-autolink": "^1.1.1",
    "react-native-bambuser-broadcaster": "^0.0.17",
    "react-native-bambuser-player": "^0.0.18",
    "react-native-code-push": "^6.2.0",
    "react-native-collapsible": "0.10.0",
    "react-native-confetti": "0.0.6",
    "react-native-dash": "0.0.9",
    "react-native-document-picker": "^3.3.2",
    "react-native-draggable-flatlist": "^1.1.7",
    "react-native-exoplayer": "ngager-group/react-native-exoplayer",
    "react-native-fast-image": "^8.1.5",
    "react-native-gesture-handler": "^1.6.1",
    "react-native-image-picker": "^2.3.0",
    "react-native-jitsi-meet": "^2.1.1",
    "react-native-keyboard-aware-scroll-view": "^0.9.1",
    "react-native-keyboard-manager": "^4.0.13-16",
    "react-native-modal-datetime-picker": "^4.7.0",
    "react-native-modalbox": "^1.7.1",
    "react-native-navigation": "^6.6.2",
    "react-native-pdf": "^6.1.0",
    "react-native-photo-view": "ngager-group/react-native-photo-view",
    "react-native-progress": "^4.1.1",
    "react-native-push-notification": "ngager-group/react-native-push-notification",
    "react-native-reanimated": "^1.7.0",
    "react-native-router-flux": "^4.2.0",
    "react-native-screens": "^2.7.0",
    "react-native-snap-carousel": "^3.9.0",
    "react-native-spinkit": "^1.5.0",
    "react-native-star-rating": "^1.0.9",
    "react-native-svg": "^12.0.3",
    "react-native-svg-charts": "^5.3.0",
    "react-native-swipe-a-lot": "github:ngager-group/react-native-swipe-a-lot#master",
    "react-native-swipe-gestures": "^1.0.3",
    "react-native-swipe-list-view": "^2.0.0",
    "react-native-tab-view": "^2.13.0",
    "react-native-thumbnail": "github:ngager-group/react-native-thumbnail#v1.0.2",
    "react-native-triangle": "0.0.9",
    "react-native-unimodules": "^0.9.0",
    "react-native-vector-icons": "^6.6.0",
    "react-native-webview": "^8.1.2",
    "react-navigation": "^4.3.8",
    "react-redux": "^7.2.0",
    "redux": "^4.0.5",
    "redux-logger": "^3.0.6",
    "redux-persist": "^6.0.0",
    "redux-thunk": "^2.3.0",
    "resumablejs": "^1.1.0",
    "rn-fetch-blob": "^0.12.0",
    "victory-native": "^32.0.2"`

**Comment by baotoan1905** [comment]
Finally I fixed this issue,
By upgrade gradle to 3.5.2 `classpath 'com.android.tools.build:gradle:3.5.2'` and downgrade @react-native-community/netinfo to 5.0.0.
Hope it can help others.
