### ISSUE TITLE
Getting crashed only in signed build android when click on call button.

### ISSUE THREAD

**Issue by Rishu2505** [jitsi/jitsi-meet#6860]
In debug build everything is worked fine 
But in signed getting crashed when launch jisimeet Interface from react native 
Actually i use the @react method from react to use same sdk that given in handbook link in jitsi for android in debug everything is fine but signed apk give crash
com.facebook.react.common.JavascriptException: TypeError: Cannot read property 'Direction' of null, js engine: hermes, stack:

**Comment by bhavesh18** [comment]
![Screenshot 2020-05-26 at 5 14 45 PM](https://user-images.githubusercontent.com/22396203/82897695-a2d3c900-9f75-11ea-8887-7b1ab1809403.png)

App got crash in release mode!!

(HERE'S MY BUILD.GRADLE:APP CODE)

apply plugin: "com.android.application"
import com.android.build.OutputFile

/**
 * The react.gradle file registers a task for each build variant (e.g. bundleDebugJsAndAssets
 * and bundleReleaseJsAndAssets).
 * These basically call `react-native bundle` with the correct arguments during the Android build
 * cycle. By default, bundleDebugJsAndAssets is skipped, as in debug/dev mode we prefer to load the
 * bundle directly from the development server. Below you can see all the possible configurations
 * and their defaults. If you decide to add a configuration block, make sure to add it before the
 * `apply from: "../../node_modules/react-native/react.gradle"` line.
 *
 * project.ext.react = [
 *   // the name of the generated asset file containing your JS bundle
 *   bundleAssetName: "index.android.bundle",
 *
 *   // the entry file for bundle generation. If none specified and
 *   // "index.android.js" exists, it will be used. Otherwise "index.js" is
 *   // default. Can be overridden with ENTRY_FILE environment variable.
 *   entryFile: "index.android.js",
 *
 *   // https://facebook.github.io/react-native/docs/performance#enable-the-ram-format
 *   bundleCommand: "ram-bundle",
 *
 *   // whether to bundle JS and assets in debug mode
 *   bundleInDebug: false,
 *
 *   // whether to bundle JS and assets in release mode
 *   bundleInRelease: true,
 *
 *   // whether to bundle JS and assets in another build variant (if configured).
 *   // See http://tools.android.com/tech-docs/new-build-system/user-guide#TOC-Build-Variants
 *   // The configuration property can be in the following formats
 *   //         'bundleIn${productFlavor}${buildType}'
 *   //         'bundleIn${buildType}'
 *   // bundleInFreeDebug: true,
 *   // bundleInPaidRelease: true,
 *   // bundleInBeta: true,
 *
 *   // whether to disable dev mode in custom build variants (by default only disabled in release)
 *   // for example: to disable dev mode in the staging build type (if configured)
 *   devDisabledInStaging: true,
 *   // The configuration property can be in the following formats
 *   //         'devDisabledIn${productFlavor}${buildType}'
 *   //         'devDisabledIn${buildType}'
 *
 *   // the root of your project, i.e. where "package.json" lives
 *   root: "../../",
 *
 *   // where to put the JS bundle asset in debug mode
 *   jsBundleDirDebug: "$buildDir/intermediates/assets/debug",
 *
 *   // where to put the JS bundle asset in release mode
 *   jsBundleDirRelease: "$buildDir/intermediates/assets/release",
 *
 *   // where to put drawable resources / React Native assets, e.g. the ones you use via
 *   // require('./image.png')), in debug mode
 *   resourcesDirDebug: "$buildDir/intermediates/res/merged/debug",
 *
 *   // where to put drawable resources / React Native assets, e.g. the ones you use via
 *   // require('./image.png')), in release mode
 *   resourcesDirRelease: "$buildDir/intermediates/res/merged/release",
 *
 *   // by default the gradle tasks are skipped if none of the JS files or assets change; this means
 *   // that we don't look at files in android/ or ios/ to determine whether the tasks are up to
 *   // date; if you have any other folders that you want to ignore for performance reasons (gradle
 *   // indexes the entire tree), add them here. Alternatively, if you have JS files in android/
 *   // for example, you might want to remove it from here.
 *   inputExcludes: ["android/**", "ios/**"],
 *
 *   // override which node gets called and with what additional arguments
 *   nodeExecutableAndArgs: ["node"],
 *
 *   // supply additional arguments to the packager
 *   extraPackagerArgs: []
 * ]
 */

project.ext.react = [
    entryFile: "index.js" ,
    enableHermes: true,  // clean and rebuild if changing
]

apply from: "../../node_modules/react-native/react.gradle"
apply from: "../../node_modules/react-native-vector-icons/fonts.gradle"

/**
 * Set this to true to create two separate APKs instead of one:
 *   - An APK that only works on ARM devices
 *   - An APK that only works on x86 devices
 * The advantage is the size of the APK is reduced by about 4MB.
 * Upload all the APKs to the Play Store and people will download
 * the correct one based on the CPU architecture of their device.
 */
def enableSeparateBuildPerCPUArchitecture = false

/**
 * Run Proguard to shrink the Java bytecode in release builds.
 */
def enableProguardInReleaseBuilds = false

/**
 * The preferred build flavor of JavaScriptCore.
 *
 * For example, to use the international variant, you can use:
 * `def jscFlavor = 'org.webkit:android-jsc-intl:+'`
 *
 * The international variant includes ICU i18n library and necessary data
 * allowing to use e.g. `Date.toLocaleString` and `String.localeCompare` that
 * give correct results when using with locales other than en-US.  Note that
 * this variant is about 6MiB larger per architecture than default.
 */
def jscFlavor = 'org.webkit:android-jsc:+'

/**
 * Whether to enable the Hermes VM.
 *
 * This should be set on project.ext.react and mirrored here.  If it is not set
 * on project.ext.react, JavaScript will not be compiled to Hermes Bytecode
 * and the benefits of using Hermes will therefore be sharply reduced.
 */
def enableHermes = project.ext.react.get("enableHermes", false);

android {
    compileSdkVersion rootProject.ext.compileSdkVersion

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }

    defaultConfig {
        applicationId "com.thelifeline"
        minSdkVersion rootProject.ext.minSdkVersion
        targetSdkVersion rootProject.ext.targetSdkVersion
        versionCode 10
        versionName "1.0"
        multiDexEnabled true
    }
    splits {
        abi {
            reset()
            enable enableSeparateBuildPerCPUArchitecture
            universalApk false  // If true, also generate a universal APK
            include "armeabi-v7a", "x86", "arm64-v8a", "x86_64"
        }
    }
    signingConfigs {
        debug {
            storeFile file('debug.keystore')
            storePassword 'android'
            keyAlias 'androiddebugkey'
            keyPassword 'android'
        }
    }
    buildTypes {
        debug {
            signingConfig signingConfigs.debug
        }
        release {
            shrinkResources false
            // Caution! In production, you need to generate your own keystore file.
            // see https://facebook.github.io/react-native/docs/signed-apk-android.
            signingConfig signingConfigs.debug
            minifyEnabled enableProguardInReleaseBuilds
            proguardFiles getDefaultProguardFile("proguard-android.txt"), "proguard-rules.pro"
        }
    }

    packagingOptions {
        pickFirst 'lib/x86/libc++_shared.so'
        pickFirst 'lib/x86/libjsc.so'
        pickFirst 'lib/x86_64/libjsc.so'
        pickFirst 'lib/arm64-v8a/libjsc.so'
        pickFirst 'lib/arm64-v8a/libc++_shared.so'
        pickFirst 'lib/x86_64/libc++_shared.so'
        pickFirst 'lib/armeabi-v7a/libc++_shared.so'
        pickFirst 'lib/armeabi-v7a/libjsc.so'

        pickFirst "lib/armeabi-v7a/libc++_shared.so"
        pickFirst "lib/arm64-v8a/libc++_shared.so"
        pickFirst "lib/x86/libc++_shared.so"
        pickFirst "lib/x86_64/libc++_shared.so"

    }

    // applicationVariants are e.g. debug, release
    applicationVariants.all { variant ->
        variant.outputs.each { output ->
            // For each separate APK per architecture, set a unique version code as described here:
            // https://developer.android.com/studio/build/configure-apk-splits.html
            def versionCodes = ["armeabi-v7a": 1, "x86": 2, "arm64-v8a": 3, "x86_64": 4]
            def abi = output.getFilter(OutputFile.ABI)
            if (abi != null) {  // null for the universal-debug, universal-release variants
                output.versionCodeOverride =
                        versionCodes.get(abi) * 1048576 + defaultConfig.versionCode
            }

        }
    }
}

dependencies {
    implementation fileTree(dir: "libs", include: ["*.jar"])
    //noinspection GradleDynamicVersion
    implementation "com.facebook.react:react-native:+"  // From node_modules
    implementation 'com.android.support:multidex:1.0.3'
    implementation "androidx.swiperefreshlayout:swiperefreshlayout:1.0.0"
    implementation 'com.facebook.fresco:fresco:2.0.0'
    implementation 'com.facebook.fresco:animated-gif:2.0.0'

    implementation ('org.jitsi.react:jitsi-meet-sdk:2.8.0') {
        exclude group: 'com.facebook.react', module:'react-native-vector-icons'
        exclude group: 'com.facebook.react', module:'react-native-community-async-storage'
        exclude group: 'com.facebook.react', module:'react-native-linear-gradient'
        exclude group: 'com.facebook',module:'hermes'
        transitive = true
    }

    debugImplementation("com.facebook.flipper:flipper:${FLIPPER_VERSION}") {
      exclude group:'com.facebook.fbjni'
    }

    debugImplementation("com.facebook.flipper:flipper-network-plugin:${FLIPPER_VERSION}") {
        exclude group:'com.facebook.flipper'
    }

    debugImplementation("com.facebook.flipper:flipper-fresco-plugin:${FLIPPER_VERSION}") {
        exclude group:'com.facebook.flipper'
    }

    if (enableHermes) {
        def hermesPath = "../../node_modules/hermes-engine/android/";
        debugImplementation files(hermesPath + "hermes-debug.aar")
        releaseImplementation files(hermesPath + "hermes-release.aar")
    } else {
        implementation jscFlavor
    }
}

// Run this once to be able to run the application with BUCK
// puts all compile dependencies into folder libs for BUCK to use
task copyDownloadableDepsToLibs(type: Copy) {
    from configurations.compile
    into 'libs'
}

apply from: file("../../node_modules/@react-native-community/cli-platform-android/native_modules.gradle"); applyNativeModulesAppBuildGradle(project)

**Comment by saghul** [comment]
Can you please provide the full trace?

**Comment by bhavesh18** [comment]
![Screenshot 2020-05-26 at 5 38 29 PM](https://user-images.githubusercontent.com/22396203/82899040-ecbdae80-9f77-11ea-84d8-345e4d3ecb73.png)

I'm using SDK referring to https://jitsi.github.io/handbook/docs/dev-guide/dev-guide-android-sdk

Full trace:

2020-05-26 17:37:52.583 31819-31819/com.awesomeproject W/Settings: Setting device_provisioned has moved from android.provider.Settings.Secure to android.provider.Settings.Global.
2020-05-26 17:37:52.583 31819-31819/com.awesomeproject V/HiTouch_HiTouchSensor: User setup is finished.
2020-05-26 17:37:52.673 31819-31819/com.awesomeproject D/AwareBitmapCacher: handleInit switch not opened pid=31819
2020-05-26 17:37:52.705 31819-31898/com.awesomeproject V/AudioManager: playSoundEffect   effectType: 0
2020-05-26 17:37:52.705 31819-31898/com.awesomeproject V/AudioManager: querySoundEffectsEnabled...
2020-05-26 17:37:52.709 31819-31898/com.awesomeproject E/check--log--ABC--: ---00---true----false
2020-05-26 17:37:52.737 31819-31898/com.awesomeproject I/System.out: Greetings from Java
2020-05-26 17:37:52.738 31819-31897/com.awesomeproject I/ReactNativeJS: true Test false
2020-05-26 17:37:52.739 31819-31819/com.awesomeproject D/ZrHung.AppEyeUiProbe: stop checker.
2020-05-26 17:37:52.749 31819-31819/com.awesomeproject W/ActivityThread: handleWindowVisibility: no activity for token android.os.BinderProxy@1e42fc
2020-05-26 17:37:52.750 31819-31819/com.awesomeproject D/ZrHung.AppEyeUiProbe: notify runnable to start.
2020-05-26 17:37:52.751 31819-31819/com.awesomeproject V/ActivityThread: Skipping new config:{0.85 ?mcc?mnc [en_IN] ldltr sw360dp w360dp h709dp 480dpi nrml long hdr port finger -keyb/v/h -nav/h winConfig={ mBounds=Rect(0, 0 - 0, 0) mAppBounds=Rect(0, 90 - 1080, 2218) mWindowingMode=fullscreen mActivityType=undefined} nonFullScreen=0 suim:1 s.7}, config:{0.85 ?mcc?mnc [en_IN] ldltr sw360dp w360dp h709dp 480dpi nrml long hdr port finger -keyb/v/h -nav/h winConfig={ mBounds=Rect(0, 0 - 0, 0) mAppBounds=Rect(0, 90 - 1080, 2218) mWindowingMode=fullscreen mActivityType=undefined} nonFullScreen=0 suim:1 s.7} for app:com.awesomeproject
2020-05-26 17:37:52.757 31819-31819/com.awesomeproject V/ActivityThread: callActivityOnCreate
2020-05-26 17:37:52.758 31819-31819/com.awesomeproject E/check--log--ABC--: ---CD---
2020-05-26 17:37:52.759 31819-31819/com.awesomeproject E/check--log--ABC--: ---33---1225----true----false
2020-05-26 17:37:52.764 31819-31819/com.awesomeproject D/SoLoader: init exiting
2020-05-26 17:37:52.768 31819-31819/com.awesomeproject D/ReactNative: ReactInstanceManager.ctor()
2020-05-26 17:37:52.768 31819-31819/com.awesomeproject D/SoLoader: init exiting
2020-05-26 17:37:52.772 31819-31819/com.awesomeproject D/ReactNative: ReactInstanceManager.createReactContextInBackground()
2020-05-26 17:37:52.772 31819-31819/com.awesomeproject D/ReactNative: ReactInstanceManager.recreateReactContextInBackgroundInner()
2020-05-26 17:37:52.772 31819-31819/com.awesomeproject D/ReactNative: ReactInstanceManager.recreateReactContextInBackgroundFromBundleLoader()
2020-05-26 17:37:52.772 31819-31819/com.awesomeproject D/ReactNative: ReactInstanceManager.recreateReactContextInBackground()
2020-05-26 17:37:52.772 31819-31819/com.awesomeproject D/ReactNative: ReactInstanceManager.runCreateReactContextOnNewThread()
2020-05-26 17:37:52.773 31819-31953/com.awesomeproject D/SoLoader: About to load: libhermes.so
2020-05-26 17:37:52.773 31819-31953/com.awesomeproject D/SoLoader: libhermes.so not found on /data/data/com.awesomeproject/lib-main
2020-05-26 17:37:52.773 31819-31953/com.awesomeproject D/SoLoader: libhermes.so not found on /data/app/com.awesomeproject-23ktPvMjAiwgQAObwJEPPw==/lib/arm64
2020-05-26 17:37:52.773 31819-31953/com.awesomeproject D/SoLoader: libhermes.so not found on /vendor/lib
2020-05-26 17:37:52.773 31819-31953/com.awesomeproject D/SoLoader: libhermes.so not found on /system/lib
2020-05-26 17:37:52.775 31819-31953/com.awesomeproject E/SoLoader: couldn't find DSO to load: libhermes.so result: 0
2020-05-26 17:37:52.775 31819-31953/com.awesomeproject W/.awesomeprojec: Accessing hidden method Lcom/msic/qarth/PatchStore;->createDisableExceptionQarthFile(Ljava/lang/Throwable;)Z (blacklist, JNI)
2020-05-26 17:37:52.775 31819-31953/com.awesomeproject E/.awesomeprojec: [qarth_debug:]  get PatchStore::createDisableExceptionQarthFile method fail.
2020-05-26 17:37:52.778 31819-31819/com.awesomeproject I/HwPhoneWindow: updateLayoutParamsColor false mSpecialSet=false, mForcedNavigationBarColor=false, navigationBarColor=0, mNavBarShow=false, mIsFloating=false
2020-05-26 17:37:52.779 31819-31819/com.awesomeproject I/HwPhoneWindow: updateLayoutParamsColor true mSpecialSet=true, mForcedNavigationBarColor=false, navigationBarColor=fffcfcfc, mNavBarShow=false, mIsFloating=false
    
    --------- beginning of crash
2020-05-26 17:37:52.779 31819-31953/com.awesomeproject E/AndroidRuntime: FATAL EXCEPTION: create_react_context
    Process: com.awesomeproject, PID: 31819
    java.lang.UnsatisfiedLinkError: couldn't find DSO to load: libhermes.so result: 0
        at com.facebook.soloader.SoLoader.doLoadLibraryBySoName(SoLoader.java:825)
        at com.facebook.soloader.SoLoader.loadLibraryBySoName(SoLoader.java:673)
        at com.facebook.soloader.SoLoader.loadLibrary(SoLoader.java:611)
        at com.facebook.soloader.SoLoader.loadLibrary(SoLoader.java:559)
        at com.facebook.hermes.reactexecutor.HermesExecutor.<clinit>(HermesExecutor.java:20)
        at com.facebook.hermes.reactexecutor.HermesExecutorFactory.create(HermesExecutorFactory.java:29)
        at com.facebook.react.ReactInstanceManager$5.run(ReactInstanceManager.java:997)
        at java.lang.Thread.run(Thread.java:784)
2020-05-26 17:37:52.781 31819-31953/com.awesomeproject E/JitsiMeetSDK: JitsiMeetUncaughtExceptionHandler FATAL ERROR
    java.lang.UnsatisfiedLinkError: couldn't find DSO to load: libhermes.so result: 0
        at com.facebook.soloader.SoLoader.doLoadLibraryBySoName(SoLoader.java:825)
        at com.facebook.soloader.SoLoader.loadLibraryBySoName(SoLoader.java:673)
        at com.facebook.soloader.SoLoader.loadLibrary(SoLoader.java:611)
        at com.facebook.soloader.SoLoader.loadLibrary(SoLoader.java:559)
        at com.facebook.hermes.reactexecutor.HermesExecutor.<clinit>(HermesExecutor.java:20)
        at com.facebook.hermes.reactexecutor.HermesExecutorFactory.create(HermesExecutorFactory.java:29)
        at com.facebook.react.ReactInstanceManager$5.run(ReactInstanceManager.java:997)
        at java.lang.Thread.run(Thread.java:784)
    
    java.lang.UnsatisfiedLinkError: couldn't find DSO to load: libhermes.so result: 0
        at com.facebook.soloader.SoLoader.doLoadLibraryBySoName(SoLoader.java:825)
        at com.facebook.soloader.SoLoader.loadLibraryBySoName(SoLoader.java:673)
        at com.facebook.soloader.SoLoader.loadLibrary(SoLoader.java:611)
        at com.facebook.soloader.SoLoader.loadLibrary(SoLoader.java:559)
        at com.facebook.hermes.reactexecutor.HermesExecutor.<clinit>(HermesExecutor.java:20)
        at com.facebook.hermes.reactexecutor.HermesExecutorFactory.create(HermesExecutorFactory.java:29)
        at com.facebook.react.ReactInstanceManager$5.run(ReactInstanceManager.java:997)
        at java.lang.Thread.run(Thread.java:784)
2020-05-26 17:37:52.786 31819-31819/com.awesomeproject D/ActivityThread: add activity client record, r= ActivityRecord{a8895fb token=android.os.BinderProxy@1e42fc {com.awesomeproject/com.awesomeproject.jitsipkg.Jitsi}} token= android.os.BinderProxy@1e42fc
2020-05-26 17:37:52.797 31819-31819/com.awesomeproject D/ZrHung.AppEyeUiProbe: notify runnable to start.
2020-05-26 17:37:52.806 31819-31953/com.awesomeproject I/Process: Sending signal. PID: 31819 SIG: 9

**Comment by Mayank8290** [comment]
same issue with me

**Comment by Mayank8290** [comment]
> In debug build everything is worked fine
> But in signed getting crash when launch jisimeet Interface from react native
> Actually i use the @react method from react to use same sdk that given in handbook link https://jitsi.github.io/handbook/docs/dev-guide/dev-guide-android-sdk,
> in jitsi for android in debug everything is fine but signed apk give crash
> E/JitsiMeetSDK: JitsiMeetUncaughtExceptionHandler FATAL ERROR
> com.facebook.react.common.JavascriptException: TypeError: Cannot read property 'Direction' of null, js engine: hermes, stack:

did you found any solutions ?

**Comment by bahadirerdemm** [comment]
Did you found any solutions ?

**Comment by Mayank8290** [comment]
I am not using the socket.io library,  here is the minimal config of My project.

**React Native** 
"@react-native-community/masked-view": "^0.1.10",
"@react-navigation/material-bottom-tabs": "^5.2.9",
"@react-navigation/native": "^5.4.2",
"@react-navigation/stack": "^5.3.9",
"jsc-android": "^241213.1.0",
"lottie-ios": "^3.0.3",
"lottie-react-native": "^3.4.0",
"react": "16.11.0",
"react-native": "0.62.2",
"react-native-gesture-handler": "^1.6.1",
"react-native-jitsi-meet": "^2.1.1",
"react-native-safe-area-context": "^2.0.0",
"react-native-screens": "^2.8.0",
"react-native-vector-icons": "^6.6.0"

React Native Version 0.62.2
Hermes is disabled and same 2.4.0 sdk of jitsi meet .
Proguard is disabled

**Android Dependencies**
dependencies {
    implementation fileTree(dir: "libs", include: ["*.jar"])
    //noinspection GradleDynamicVersion

    implementation(project(':react-native-jitsi-meet')) {
        exclude group: 'com.facebook.react',module:'react-native-locale-detector'
        exclude group: 'com.facebook.react',module:'react-native-vector-icons'
        exclude group: 'com.facebook.react',module:'react-native-fetch-blob'
        exclude group: 'com.facebook.react',module:'react-native-push-notification'
    }

    implementation "com.facebook.react:react-native:+"  // From node_modules

    implementation "androidx.swiperefreshlayout:swiperefreshlayout:1.0.0"

    debugImplementation("com.facebook.flipper:flipper:${FLIPPER_VERSION}") {
      exclude group:'com.facebook.fbjni'
    }

    debugImplementation("com.facebook.flipper:flipper-network-plugin:${FLIPPER_VERSION}") {
        exclude group:'com.facebook.flipper'
    }

    debugImplementation("com.facebook.flipper:flipper-fresco-plugin:${FLIPPER_VERSION}") {
        exclude group:'com.facebook.flipper'
    }

    if (enableHermes) {
        def hermesPath = "../../node_modules/hermes-engine/android/";
        debugImplementation files(hermesPath + "hermes-debug.aar")
        releaseImplementation files(hermesPath + "hermes-release.aar")
    } else {
        implementation jscFlavor
    }
}

**Comment by adamthewan** [comment]
To those having a similar issue, this helped me:

https://github.com/skrafft/react-native-jitsi-meet/issues/117#issuecomment-636263779

Solution 2
