### ISSUE TITLE
The screen goes black when the meeting is on

### ISSUE THREAD

**Issue by wang94** [jitsi/jitsi-meet#6884]
Process: com.tianxiabuyi.prototype.xljkcj, PID: 30439
    java.lang.UnsatisfiedLinkError: couldn't find DSO to load: libhermes.so
        at com.facebook.soloader.SoLoader.doLoadLibraryBySoName(SoLoader.java:738)
        at com.facebook.soloader.SoLoader.loadLibraryBySoName(SoLoader.java:591)
        at com.facebook.soloader.SoLoader.loadLibrary(SoLoader.java:529)
        at com.facebook.soloader.SoLoader.loadLibrary(SoLoader.java:484)
        at com.facebook.hermes.reactexecutor.HermesExecutor.<clinit>(HermesExecutor.java:20)
        at com.facebook.hermes.reactexecutor.HermesExecutorFactory.create(HermesExecutorFactory.java:27)
        at com.facebook.react.ReactInstanceManager$5.run(ReactInstanceManager.java:952)
        at java.lang.Thread.run(Thread.java:764)
2020-05-27 17:06:08.889 30439-30811/com.tianxiabuyi.prototype.xljkcj E/JitsiMeetSDK: JitsiMeetUncaughtExceptionHandler FATAL ERROR

**Comment by luixxiul** [comment]
Please follow the template to provide more information on the issue.

````
### Description:

<!-- Please describe the bug clearly and concisely. -->

### Steps to reproduce:

1. <!-- Open '...' -->
2. <!-- Click on '...' -->
3. <!-- and so on... -->

### Expected behavior:

<!-- Please describe what should happen. -->

### Actual behavior:

<!-- Please describe what actually happens. -->
<!-- Please attach screenshot if possible. -->

### Server information:

- Jitsi Meet version:
- Operating System:

### Client information:

- Browser / app version:
- Operating System:

### Additional information:

<!-- Please provide additional information about the bug, if any. -->
````
