### ISSUE TITLE
Makefile:19: recipe for target 'compile' failed

### ISSUE THREAD

**Issue by rajalpathak** [jitsi/jitsi-meet#6976]
root@ip-172-31-49-127:/opt/jitsi-meet# make
./node_modules/.bin/webpack -p
/opt/jitsi-meet/node_modules/webpack-cli/bin/cli.js:93
                                throw err;
                                ^

ReferenceError: URL is not defined
    at Object.<anonymous> (/opt/jitsi-meet/webpack.config.js:45:33)
    at Module._compile (/opt/jitsi-meet/node_modules/v8-compile-cache/v8-compile-cache.js:192:30)
    at Object.Module._extensions..js (module.js:652:10)
    at Module.load (module.js:560:32)
    at tryModuleLoad (module.js:503:12)
    at Function.Module._load (module.js:495:3)
    at Module.require (module.js:585:17)
    at require (/opt/jitsi-meet/node_modules/v8-compile-cache/v8-compile-cache.js:161:20)
    at WEBPACK_OPTIONS (/opt/jitsi-meet/node_modules/webpack-cli/bin/utils/convert-argv.js:114:13)
    at requireConfig (/opt/jitsi-meet/node_modules/webpack-cli/bin/utils/convert-argv.js:116:6)
    at /opt/jitsi-meet/node_modules/webpack-cli/bin/utils/convert-argv.js:123:17
    at Array.forEach (<anonymous>)
    at module.exports (/opt/jitsi-meet/node_modules/webpack-cli/bin/utils/convert-argv.js:121:15)
    at yargs.parse (/opt/jitsi-meet/node_modules/webpack-cli/bin/cli.js:71:45)
    at Object.parse (/opt/jitsi-meet/node_modules/webpack-cli/node_modules/yargs/yargs.js:567:18)
    at /opt/jitsi-meet/node_modules/webpack-cli/bin/cli.js:49:8
    at Object.<anonymous> (/opt/jitsi-meet/node_modules/webpack-cli/bin/cli.js:366:3)
    at Module._compile (module.js:641:30)
    at Object.Module._extensions..js (module.js:652:10)
    at Module.load (module.js:560:32)
    at tryModuleLoad (module.js:503:12)
    at Function.Module._load (module.js:495:3)
    at Module.require (module.js:585:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/opt/jitsi-meet/node_modules/webpack/bin/webpack.js:156:2)
    at Module._compile (module.js:641:30)
    at Object.Module._extensions..js (module.js:652:10)
    at Module.load (module.js:560:32)
    at tryModuleLoad (module.js:503:12)
    at Function.Module._load (module.js:495:3)
Makefile:19: recipe for target 'compile' failed
make: *** [compile] Error 1
root@ip-172-31-49-127:/opt/jitsi-meet# Makefile:19: recipe for target 'compile' failed
Makefile:19:: command not found

**Comment by mdshohelrana** [comment]
Yes, I am facing same problem. have anyone to help us?

**Comment by coderlava** [comment]
Same problem facing here, URL not defiend in webpack-cli. Im still facing the problem also here after I installed the package using yarn intead of npm.

**Comment by coderlava** [comment]
Problem solved : 
`curl -sL https://deb.nodesource.com/setup_12.x | sudo -E bash -`
`sudo apt-get install -y nodejs`

make sure that installed nodejs is updated currently using version 12

**Comment by chenmiaojie03** [comment]
-DVERSION=\"`PYTHONPATH=. python -B bin/mn --version 2>&1`\" mnexec.c -o mnexec
cc: error: (most: No such file or directory
cc: error: recent: No such file or directory
cc: error: call: No such file or directory
cc: error: last):: No such file or directory
cc: error: File: No such file or directory
cc: error: "bin/mn",: No such file or directory
cc: error: line: No such file or directory
cc: error: 45,: No such file or directory
cc: error: in: No such file or directory
cc: error: <module>: No such file or directory
cc: error: from: No such file or directory
cc: error: mininet.examples.cluster: No such file or directory
cc: error: import: No such file or directory
cc: error: (: No such file or directory
cc: error: MininetCluster,: No such file or directory
cc: error: RemoteHost,: No such file or directory
cc: error: ImportError:: No such file or directory
cc: error: No: No such file or directory
cc: error: module: No such file or directory
cc: error: named: No such file or directory
cc: error: examples.cluster": No such file or directory
Makefile:50: recipe for target 'mnexec' failed
make: *** [mnexec] Error 1

**Comment by chenmiaojie03** [comment]
have anyone to help me？

**Comment by saghul** [comment]
Not sure what you're doing, but that doesn't look like the output of anything related to our build system.

**Comment by chenmiaojie03** [comment]
this problem happens when I install  mininet. 
bash mininet.sh

**Comment by saghul** [comment]
And how is that related to Jitsi Meet?

**Comment by chenmiaojie03** [comment]
Error when I run install.sh

**Comment by chenmiaojie03** [comment]
It‘s not related to Jitsi Meet

**Comment by chenmiaojie03** [comment]
If there's some problems in mnexec.c?

**Comment by saghul** [comment]
If it's not related to Jitsi Meet then please stop posting here, whatever this issue was about had nothing to do with what you're asking.

**Comment by chenmiaojie03** [comment]
the problem is similiar to landlord，is about install mininet
