### ISSUE TITLE
getJitsiView() is null when i am trying to destroy my activity 

### ISSUE THREAD

**Issue by rdonik** [jitsi/jitsi-meet#7105]
### Description:

 Caused by: java.lang.reflect.InvocationTargetException
        at java.lang.reflect.Method.invoke(Native Method)
        at org.jitsi.meet.sdk.ListenerUtils.runListenerMethodOnUiThread(ListenerUtils.java:135)
        at org.jitsi.meet.sdk.ListenerUtils.access$000(ListenerUtils.java:35) 
        at org.jitsi.meet.sdk.ListenerUtils$1.run(ListenerUtils.java:114) 
        at android.os.Handler.handleCallback(Handler.java:883) 
        at android.os.Handler.dispatchMessage(Handler.java:100) 
        at android.os.Looper.loop(Looper.java:237) 
        at android.app.ActivityThread.main(ActivityThread.java:7811) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1076) 
     Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'org.jitsi.meet.sdk.JitsiMeetView org.jitsi.meet.sdk.JitsiMeetFragment.getJitsiView()' on a null object reference
        at org.jitsi.meet.sdk.JitsiMeetActivity.getJitsiView(JitsiMeetActivity.java:110)
        at org.jitsi.meet.sdk.JitsiMeetActivity.leave(JitsiMeetActivity.java:126)
        at org.jitsi.meet.sdk.JitsiMeetActivity.finish(JitsiMeetActivity.java:99)
        at org.jitsi.meet.sdk.JitsiMeetActivity.onConferenceTerminated(JitsiMeetActivity.java:223)
        at java.lang.reflect.Method.invoke(Native Method) 
        at org.jitsi.meet.sdk.ListenerUtils.runListenerMethodOnUiThread(ListenerUtils.java:135) 
        at org.jitsi.meet.sdk.ListenerUtils.access$000(ListenerUtils.java:35) 
        at org.jitsi.meet.sdk.ListenerUtils$1.run(ListenerUtils.java:114) 
        at android.os.Handler.handleCallback(Handler.java:883) 
        at android.os.Handler.dispatchMessage(Handler.java:100) 
        at android.os.Looper.loop(Looper.java:237) 
        at android.app.ActivityThread.main(ActivityThread.java:7811) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1076) 

i extended JitsiMeetActivity, when my activity stop i want to finish call manually, that's why i'm calling **finish()** function. But you also have **super.finish()** function in **onConferenceTerminated**, so actually myActivity has already finished, that's why **getJitsiView()** is null in **leave()** function, please give me some hint to prevent crash in this case 

 override fun onStop() {
        super.onStop()
        finish()
    }

### Steps to reproduce:

1. 
2. 
3. 

### Server information:

- Jitsi Meet version: 2.8.2
- Operating System: android

### Client information:

- Browser / app version:
- Operating System:

**Comment by l3d00m** [comment]
Hi,
If you have a question about Jitsi Meet that is not a bug report or feature request, please post it in https://community.jitsi.org

---
*I'm a community contributor and not directly affiliated with the Jitsi team.*

**Comment by cinny007** [comment]
@rdonik Did you find anything? I am also facing the same issue.
