### ISSUE TITLE
lobby feature breaks dial-in functions

### ISSUE THREAD

**Issue by SriramScorp** [jitsi/jitsi-meet#7271]
I have configured dial-in feature and it was working well. I recently enabled the lobby feature which broke jigasi dial-in. Previously, jigasi was joining the correct conference room `myroom@conference.meet.example.com`, now jigasi tries to join `myroom@lobby.meet.example.com` and fails. Below are the relevant logs.

With lobby disabled:
> 2020-07-08 21:08:47.835 INFO: [178] org.jitsi.jigasi.SipGateway.incomingCallReceived().216 [ctx=15942227278341383354673] Incoming call received...
2020-07-08 21:08:48.838 INFO: [179] org.jitsi.jigasi.SipGatewaySession.run().1524 [ctx=15942227278341383354673] Wait thread cancelled
2020-07-08 21:08:48.839 INFO: [178] org.jitsi.jigasi.JvbConference.start().437 [ctx=15942227278341383354673] Starting JVB conference room: cafeteria
2020-07-08 21:08:48.845 INFO: [178] org.jitsi.jigasi.JvbConference.setXmppProvider().576 [ctx=15942227278341383354673] Using ProtocolProviderServiceJabberImpl(Jabber:60ca44a0@meet.example.com/60ca44a0)
2020-07-08 21:08:48.943 INFO: [182] impl.protocol.jabber.OperationSetBasicTelephonyJabberImpl.registrationStateChanged().127 Jingle : ON
2020-07-08 21:08:48.944 INFO: [182] org.jitsi.jigasi.JvbConference.registrationStateChanged().627 [ctx=15942227278341383354673] Registering XMPP.
2020-07-08 21:08:48.952 INFO: [182] impl.protocol.jabber.ProtocolProviderServiceJabberImpl.authenticated().2423 Authenticated: false
2020-07-08 21:08:48.956 INFO: [182] org.jitsi.jigasi.JvbConference.joinConferenceRoom().714 [ctx=15942227278341383354673] Joining JVB conference room: cafeteria
2020-07-08 21:08:49.013 INFO: [187] impl.protocol.jabber.ChatRoomJabberImpl.joined().1256 cafeteria@conference.meet.example.com/2d9fc696 has joined the cafeteria@conference.meet.example.com chat room.
2020-07-08 21:08:49.030 INFO: [187] impl.protocol.jabber.ChatRoomJabberImpl.joined().1256 cafeteria@conference.meet.example.com/focus has joined the cafeteria@conference.meet.example.com chat room.
2020-07-08 21:08:49.980 INFO: [200] impl.protocol.jabber.IceUdpTransportManager.createIceAgent().347 End gathering harvester within 585 ms

With lobby enabled:
> 2020-07-08 20:47:37.217 INFO: [78] org.jitsi.jigasi.SipGateway.incomingCallReceived().216 [ctx=15942214572052052461455] Incoming call received...
2020-07-08 20:47:37.229 INFO: [80] org.jitsi.jigasi.SipGatewaySession.run().1524 [ctx=15942214572052052461455] Wait thread cancelled
2020-07-08 20:47:37.246 INFO: [78] org.jitsi.jigasi.JvbConference.start().437 [ctx=15942214572052052461455] Starting JVB conference room: cafeteria
2020-07-08 20:47:37.334 INFO: [78] org.jitsi.jigasi.JvbConference.setXmppProvider().576 [ctx=15942214572052052461455] Using ProtocolProviderServiceJabberImpl(Jabber:17e0ba40@meet.example.com/17e0ba40)
2020-07-08 20:47:37.603 INFO: [82] impl.protocol.jabber.OperationSetBasicTelephonyJabberImpl.registrationStateChanged().127 Jingle : ON
2020-07-08 20:47:37.604 INFO: [82] org.jitsi.jigasi.JvbConference.registrationStateChanged().627 [ctx=15942214572052052461455] Registering XMPP.
2020-07-08 20:47:37.636 INFO: [82] impl.protocol.jabber.ProtocolProviderServiceJabberImpl.authenticated().2423 Authenticated: false
2020-07-08 20:47:37.648 INFO: [82] org.jitsi.jigasi.JvbConference.joinConferenceRoom().714 [ctx=15942214572052052461455] Joining JVB conference room: cafeteria
2020-07-08 20:47:37.800 SEVERE: [82] org.jitsi.jigasi.JvbConference.inviteFocus().1456 [ctx=15942214572052052461455] Could not invite the focus to the conference
org.jivesoftware.smack.XMPPException$XMPPErrorException: XMPP error reply received from focus.meet.example.com: XMPPError: internal-server-error - wait
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;        at org.jivesoftware.smack.XMPPException$XMPPErrorException.ifHasErrorThenThrow(XMPPException.java:132)
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;        at org.jivesoftware.smack.StanzaCollector.nextResultOrThrow(StanzaCollector.java:263)
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;        at org.jivesoftware.smack.StanzaCollector.nextResultOrThrow(StanzaCollector.java:214)
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;        at org.jitsi.jigasi.JvbConference.inviteFocus(JvbConference.java:1450)
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;        at org.jitsi.jigasi.JvbConference.joinConferenceRoom(JvbConference.java:793)
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;        at org.jitsi.jigasi.JvbConference.registrationStateChanged(JvbConference.java:606)
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;        at net.java.sip.communicator.service.protocol.AbstractProtocolProviderService.fireRegistrationStateChanged(AbstractProtocolProviderService.java:187)
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;        at net.java.sip.communicator.service.protocol.AbstractProtocolProviderService.fireRegistrationStateChanged(AbstractProtocolProviderService.java:141)
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;        at net.java.sip.communicator.impl.protocol.jabber.ProtocolProviderServiceJabberImpl.connectAndLogin(ProtocolProviderServiceJabberImpl.java:1389)
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;        at net.java.sip.communicator.impl.protocol.jabber.ProtocolProviderServiceJabberImpl.connectAndLogin(ProtocolProviderServiceJabberImpl.java:970)
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;        at net.java.sip.communicator.impl.protocol.jabber.ProtocolProviderServiceJabberImpl.initializeConnectAndLogin(ProtocolProviderServiceJabberImpl.java:795)
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;        at net.java.sip.communicator.impl.protocol.jabber.ProtocolProviderServiceJabberImpl.register(ProtocolProviderServiceJabberImpl.java:500)
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;        at org.jitsi.jigasi.util.RegisterThread.run(RegisterThread.java:59)
2020-07-08 20:47:37.824 WARNING: [89] impl.protocol.jabber.ChatRoomJabberImpl.processStanza().3133 Unable to handle packet: Presence Stanza [to=muqpnaf1gti7die3@meet.example.com/GHnS9c5N,from=cafeteria@lobby.meet.example.com/17e0ba40,id=5m17K-51,type=error,]
2020-07-08 20:47:37.824 SEVERE: [82] impl.protocol.jabber.ChatRoomJabberImpl.joinAs().743 Failed to join room cafeteria@lobby.meet.example.com with nickname: 17e0ba40
org.jivesoftware.smack.XMPPException$XMPPErrorException: XMPP error reply received from cafeteria@lobby.meet.example.com/17e0ba40: XMPPError: not-allowed - cancel
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;        at org.jivesoftware.smack.XMPPException$XMPPErrorException.ifHasErrorThenThrow(XMPPException.java:132)
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;        at org.jivesoftware.smack.StanzaCollector.nextResultOrThrow(StanzaCollector.java:263)
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;        at org.jivesoftware.smackx.muc.MultiUserChat.enter(MultiUserChat.java:347)
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;        at org.jivesoftware.smackx.muc.MultiUserChat.join(MultiUserChat.java:703)
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;        at org.jivesoftware.smackx.muc.MultiUserChat.join(MultiUserChat.java:595)
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;        at net.java.sip.communicator.impl.protocol.jabber.ChatRoomJabberImpl.joinAs(ChatRoomJabberImpl.java:665)
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;        at net.java.sip.communicator.impl.protocol.jabber.ChatRoomJabberImpl.joinAs(ChatRoomJabberImpl.java:778)
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;        at org.jitsi.jigasi.JvbConference.joinConferenceRoom(JvbConference.java:805)
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;        at org.jitsi.jigasi.JvbConference.registrationStateChanged(JvbConference.java:606)
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;        at net.java.sip.communicator.service.protocol.AbstractProtocolProviderService.fireRegistrationStateChanged(AbstractProtocolProviderService.java:187)
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;        at net.java.sip.communicator.service.protocol.AbstractProtocolProviderService.fireRegistrationStateChanged(AbstractProtocolProviderService.java:141)
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;        at net.java.sip.communicator.impl.protocol.jabber.ProtocolProviderServiceJabberImpl.connectAndLogin(ProtocolProviderServiceJabberImpl.java:1389)
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;        at net.java.sip.communicator.impl.protocol.jabber.ProtocolProviderServiceJabberImpl.connectAndLogin(ProtocolProviderServiceJabberImpl.java:970)
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;        at net.java.sip.communicator.impl.protocol.jabber.ProtocolProviderServiceJabberImpl.initializeConnectAndLogin(ProtocolProviderServiceJabberImpl.java:795)
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;        at net.java.sip.communicator.impl.protocol.jabber.ProtocolProviderServiceJabberImpl.register(ProtocolProviderServiceJabberImpl.java:500)
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;        at org.jitsi.jigasi.util.RegisterThread.run(RegisterThread.java:59)
2020-07-08 20:47:37.825 SEVERE: [82] org.jitsi.jigasi.JvbConference.joinConferenceRoom().843 [ctx=15942214572052052461455]net.java.sip.communicator.service.protocol.OperationFailedException: Failed to join room cafeteria@lobby.meet.example.com with nickname: 17e0ba40
net.java.sip.communicator.service.protocol.OperationFailedException: Failed to join room cafeteria@lobby.meet.example.com with nickname: 17e0ba40
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;        at net.java.sip.communicator.impl.protocol.jabber.ChatRoomJabberImpl.joinAs(ChatRoomJabberImpl.java:745)
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;        at net.java.sip.communicator.impl.protocol.jabber.ChatRoomJabberImpl.joinAs(ChatRoomJabberImpl.java:778)
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;        at org.jitsi.jigasi.JvbConference.joinConferenceRoom(JvbConference.java:805)
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;        at org.jitsi.jigasi.JvbConference.registrationStateChanged(JvbConference.java:606)
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;        at net.java.sip.communicator.service.protocol.AbstractProtocolProviderService.fireRegistrationStateChanged(AbstractProtocolProviderService.java:187)
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;        at net.java.sip.communicator.service.protocol.AbstractProtocolProviderService.fireRegistrationStateChanged(AbstractProtocolProviderService.java:141)
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;        at net.java.sip.communicator.impl.protocol.jabber.ProtocolProviderServiceJabberImpl.connectAndLogin(ProtocolProviderServiceJabberImpl.java:1389)
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;        at net.java.sip.communicator.impl.protocol.jabber.ProtocolProviderServiceJabberImpl.connectAndLogin(ProtocolProviderServiceJabberImpl.java:970)
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;        at net.java.sip.communicator.impl.protocol.jabber.ProtocolProviderServiceJabberImpl.initializeConnectAndLogin(ProtocolProviderServiceJabberImpl.java:795)
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;        at net.java.sip.communicator.impl.protocol.jabber.ProtocolProviderServiceJabberImpl.register(ProtocolProviderServiceJabberImpl.java:500)
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;        at org.jitsi.jigasi.util.RegisterThread.run(RegisterThread.java:59)
Caused by: org.jivesoftware.smack.XMPPException$XMPPErrorException: XMPP error reply received from cafeteria@lobby.meet.example.com/17e0ba40: XMPPError: not-allowed - cancel
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;        at org.jivesoftware.smack.XMPPException$XMPPErrorException.ifHasErrorThenThrow(XMPPException.java:132)
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;        at org.jivesoftware.smack.StanzaCollector.nextResultOrThrow(StanzaCollector.java:263)
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;        at org.jivesoftware.smackx.muc.MultiUserChat.enter(MultiUserChat.java:347)
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;        at org.jivesoftware.smackx.muc.MultiUserChat.join(MultiUserChat.java:703)
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;        at org.jivesoftware.smackx.muc.MultiUserChat.join(MultiUserChat.java:595)
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;        at net.java.sip.communicator.impl.protocol.jabber.ChatRoomJabberImpl.joinAs(ChatRoomJabberImpl.java:665)
        ... 10 more
2020-07-08 20:47:37.828 WARNING: [82] org.jitsi.jigasi.JvbConference.leaveConferenceRoom().934 [ctx=15942214572052052461455] MUC room is null
2020-07-08 20:47:37.828 INFO: [82] org.jitsi.jigasi.JvbConference.stop().536 [ctx=15942214572052052461455] Removing account Jabber:17e0ba40@meet.example.com/17e0ba40
2020-07-08 20:47:37.830 WARNING: [94] impl.protocol.jabber.ChatRoomJabberImpl.processStanza().3133 Unable to handle packet: Presence Stanza [to=muqpnaf1gti7die3@meet.example.com/GHnS9c5N,from=cafeteria@lobby.meet.example.com/17e0ba40,id=5m17K-55,type=error,]
2020-07-08 20:47:37.846 INFO: [82] impl.protocol.jabber.OperationSetBasicTelephonyJabberImpl.registrationStateChanged().134 Jingle : OFF
2020-07-08 20:47:37.859 INFO: [97] org.jitsi.jigasi.SipGatewaySession.sipCallEnded().616 [ctx=15942214572052052461455] Sip call ended: Call: id=15942214571301485791707 peers=0
2020-07-08 20:47:37.863 SEVERE: [97] org.jitsi.jigasi.AbstractGateway.notifyCallEnded().120 [ctx=15942214572052052461455] Call resource not exists for session.
2020-07-08 20:47:37.864 INFO: [97] org.jitsi.jigasi.SipGatewaySession.peerStateChanged().1491 null SIP peer state: Failed

**Comment by saghul** [comment]
I think the whitelist module should be used here, right @damencho ?

**Comment by SriramScorp** [comment]
I'm using the callcontrol component. Is it possible to whitelist a component? Or should I be using a virtualhost instead?

**Comment by SriramScorp** [comment]
Whilelisting the callcontrol domain fixed the issue. Thanks.

**Comment by damencho** [comment]
We are also working on adding lobby support to jigasi
