### ISSUE TITLE
Jitsi Picture In Picture Not Working <PIP> Android Sdk

### ISSUE THREAD

**Issue by rawars** [jitsi/jitsi-meet#7404]
@xrmx @nud @monkeydom @jcfischer 
### Description:
Good afternoon, I don't know if it's the medium, but I couldn't post in the jitsi forum, I can't find the option, I don't know if it's because I'm new to the forum, I don't know if you can lend me a hand, it turns out that I'm having  problems with the implementation of the sdk in Android, it turns out that I cannot access the PIP mode the console of Android studio shows me an error message that notifies me that the PIP mode cannot be accessed, I appreciate your help.

### Files:
[activity_main.pdf](https://github.com/jitsi/jitsi-meet/files/4973890/activity_main.pdf)
[MainActivity.java.pdf](https://github.com/jitsi/jitsi-meet/files/4973891/MainActivity.java.pdf)

### Steps to reproduce:

1. Create a project in android studio
2. extends FragmentActivity using as a guide https://github.com/jitsi/jitsi-meet/blob/1b6c5a714153b7186ac783e470ebd36633b3c7d0/android/sdk/src/main/java/org/jitsi/meet/sdk/JitsiMeetActivity.java
3. Compile on my phone and it shows the error

### Expected behavior:

That when minimizing it enters PIP mode and can return to full screen mode.-

### Actual behavior:
The console throws the following error while minimizing the application:
E/JitsiMeetSDK: Failed to enter PiP mode
    java.lang.RuntimeException: Failed to enter Picture-in-Picture
        at org.jitsi.meet.sdk.PictureInPictureModule.enterPictureInPicture(PictureInPictureModule.java:86)
        at org.jitsi.meet.sdk.JitsiMeetView.enterPictureInPicture(JitsiMeetView.java:133)
        at com.doctalkpaciente.app.MainActivity.onUserLeaveHint(MainActivity.java:102)
        at android.app.Activity.performUserLeaving(Activity.java:7189)
        at android.app.Instrumentation.callActivityOnUserLeaving(Instrumentation.java:1440)
        at android.app.ActivityThread.performUserLeavingActivity(ActivityThread.java:3950)
        at android.app.ActivityThread.handlePauseActivity(ActivityThread.java:3926)
        at android.app.ActivityThread.-wrap15(Unknown Source:0)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1649)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:164)
        at android.app.ActivityThread.main(ActivityThread.java:6647)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:811)

### Server information:
We are using the jitsi.is server, for this reason I do not know what operating system is running
- Jitsi Meet version: Jitsi.is
- Operating System: I guess the latest version

### Client information:

- Browser / app version: Android Studio4.0.1
- Operating System: MacOS Catalina 10.15.6

### Additional information:

I/org.webrtc.Logging: CameraStatistics: Camera fps: 11.
I/JitsiMeetSDK: PictureInPicture Entering Picture-in-Picture
E/JitsiMeetSDK: Failed to enter PiP mode
    java.lang.RuntimeException: Failed to enter Picture-in-Picture
        at org.jitsi.meet.sdk.PictureInPictureModule.enterPictureInPicture(PictureInPictureModule.java:86)
        at org.jitsi.meet.sdk.JitsiMeetView.enterPictureInPicture(JitsiMeetView.java:133)
        at com.doctalkpaciente.app.MainActivity.onUserLeaveHint(MainActivity.java:102)
        at android.app.Activity.performUserLeaving(Activity.java:7189)
        at android.app.Instrumentation.callActivityOnUserLeaving(Instrumentation.java:1440)
        at android.app.ActivityThread.performUserLeavingActivity(ActivityThread.java:3950)
        at android.app.ActivityThread.handlePauseActivity(ActivityThread.java:3926)
        at android.app.ActivityThread.-wrap15(Unknown Source:0)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1649)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:164)
        at android.app.ActivityThread.main(ActivityThread.java:6647)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:811)
    
    java.lang.RuntimeException: Failed to enter Picture-in-Picture
        at org.jitsi.meet.sdk.PictureInPictureModule.enterPictureInPicture(PictureInPictureModule.java:86)
        at org.jitsi.meet.sdk.JitsiMeetView.enterPictureInPicture(JitsiMeetView.java:133)
        at com.doctalkpaciente.app.MainActivity.onUserLeaveHint(MainActivity.java:102)
        at android.app.Activity.performUserLeaving(Activity.java:7189)
        at android.app.Instrumentation.callActivityOnUserLeaving(Instrumentation.java:1440)
        at android.app.ActivityThread.performUserLeavingActivity(ActivityThread.java:3950)
        at android.app.ActivityThread.handlePauseActivity(ActivityThread.java:3926)
        at android.app.ActivityThread.-wrap15(Unknown Source:0)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1649)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:164)
        at android.app.ActivityThread.main(ActivityThread.java:6647)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:811)

**Comment by KanwalKhan-20** [comment]
Can we resize the size of screen when it is in pip mode so that we can also see all the options?

**Comment by saghul** [comment]
No, the pip window is not resizable.
