### ISSUE TITLE
Health checks fail

### ISSUE THREAD

**Issue by rasos** [jitsi/jitsi-meet#7810]
We run several videobridges (version 2.1-351) on bare metal servers with Debian buster 10 and jvm 11.0.8+10-post-Debian-1deb10u1.

```
2020-09-30 09:20:02.153 SEVERE: [27] HealthChecker.run#172: Health check failed in PT22.922824S:
java.lang.Exception: Performing a health check took too long: PT22.922824S
        at org.jitsi.health.HealthChecker.run(HealthChecker.kt:157)
        at org.jitsi.utils.concurrent.RecurringRunnableExecutor.run(RecurringRunnableExecutor.java:216)
        at org.jitsi.utils.concurrent.RecurringRunnableExecutor.runInThread(RecurringRunnableExecutor.java:292)
        at org.jitsi.utils.concurrent.RecurringRunnableExecutor.access$000(RecurringRunnableExecutor.java:36)
        at org.jitsi.utils.concurrent.RecurringRunnableExecutor$1.run(RecurringRunnableExecutor.java:328)
```
At start-up we see

> 2020-09-30 09:20:03.753 WARNING: [1] org.glassfish.jersey.internal.inject.Providers.checkProviderRuntime: A provider org.jitsi.rest.Health registered in SERVER runtime does not implement any provider interfaces applicable in the SERVER runtime. Due to constraint configuration problems the provider org.jitsi.rest.Health will be ignored. 

A restart of the videobridge fixed the health check timeout. This never happened with previous versions of the videobridge.  Observing, if it will come back.

**Comment by tpo** [comment]
I'm seeing the same. Did you find out what the problem was @rasos ?

**Comment by rasos** [comment]
We don't have this issue anymore with  jitsi-videobridge2 version 2.1-508-gb24f756c-1 (which is not the very latest stable, upgrades pending).
