### ISSUE TITLE
App is getting crashed

### ISSUE THREAD

**Issue by ips-illuminz** [jitsi/jitsi-meet#7911]
Hello Guys,

I have cloned the fresh repo and installed the node modules by `npm i` command, but when i'm trying to debug the app in android device with the following command:

`react-native run-android`

The app is installing and showing first screen after entering the name and click on join meeting the app is getting crash and it never open until i force stopped that. Kindly look into this issue the app was working fine before we have to deliver this build today any help would be appreciated.

Thanks,
Inder

**Comment by saghul** [comment]
Please provide device logs. master is working fine for me here.

**Comment by ips-illuminz** [comment]
How can i provide you device logs, in the metro there is no error showing but when i'm opening app it's getting crashed without any printing log in terminal. I have tested with multiple devices but the issue is same.

**Comment by saghul** [comment]
You can use `adb logact` to get them. Or the logcat screen if you run the app in Android Studio.

**Comment by ips-illuminz** [comment]
Hi Guys,

The issue is same, i have cloned the fresh repo without any custom changes but the build is crashing again.
I'm attaching a link of adb logs please check that: https://we.tl/t-YEPUee9XWW

Thanks,
Inder

**Comment by saghul** [comment]
This is the error:

```
10-22 11:02:59.926  4977  5079 E AndroidRuntime: FATAL EXCEPTION: pool-4-thread-1
10-22 11:02:59.926  4977  5079 E AndroidRuntime: Process: org.jitsi.meet, PID: 4977
10-22 11:02:59.926  4977  5079 E AndroidRuntime: java.lang.NoSuchMethodError: No static method createEgl14([I)Lorg/webrtc/EglBase14; in class Lorg/webrtc/EglBase; or its super classes (declaration of 'org.webrtc.EglBase' appears in /data/app/org.jitsi.meet-P5W-3IXR0mvVSGeiuuoTGA==/base.apk!classes3.dex)
10-22 11:02:59.926  4977  5079 E AndroidRuntime: 	at com.oney.WebRTCModule.EglUtils.getRootEglBase(EglUtils.java:35)
10-22 11:02:59.926  4977  5079 E AndroidRuntime: 	at com.oney.WebRTCModule.EglUtils.getRootEglBaseContext(EglUtils.java:62)
10-22 11:02:59.926  4977  5079 E AndroidRuntime: 	at com.oney.WebRTCModule.GetUserMediaImpl.createVideoTrack(GetUserMediaImpl.java:93)
10-22 11:02:59.926  4977  5079 E AndroidRuntime: 	at com.oney.WebRTCModule.GetUserMediaImpl.getUserMedia(GetUserMediaImpl.java:180)
10-22 11:02:59.926  4977  5079 E AndroidRuntime: 	at com.oney.WebRTCModule.WebRTCModule.lambda$getUserMedia$2$WebRTCModule(WebRTCModule.java:485)
10-22 11:02:59.926  4977  5079 E AndroidRuntime: 	at com.oney.WebRTCModule.-$$Lambda$WebRTCModule$C_Gitx4KOYySlWXaI1K4M1yoJoA.run(Unknown Source:8)
10-22 11:02:59.926  4977  5079 E AndroidRuntime: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
10-22 11:02:59.926  4977  5079 E AndroidRuntime: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
10-22 11:02:59.926  4977  5079 E AndroidRuntime: 	at java.lang.Thread.run(Thread.java:919)
10-22 11:02:59.929  4977  5079 E JitsiMeetSDK: JitsiMeetUncaughtExceptionHandler FATAL ERROR
10-22 11:02:59.929  4977  5079 E JitsiMeetSDK: java.lang.NoSuchMethodError: No static method createEgl14([I)Lorg/webrtc/EglBase14; in class Lorg/webrtc/EglBase; or its super classes (declaration of 'org.webrtc.EglBase' appears in /data/app/org.jitsi.meet-P5W-3IXR0mvVSGeiuuoTGA==/base.apk!classes3.dex)
10-22 11:02:59.929  4977  5079 E JitsiMeetSDK: 	at com.oney.WebRTCModule.EglUtils.getRootEglBase(EglUtils.java:35)
10-22 11:02:59.929  4977  5079 E JitsiMeetSDK: 	at com.oney.WebRTCModule.EglUtils.getRootEglBaseContext(EglUtils.java:62)
10-22 11:02:59.929  4977  5079 E JitsiMeetSDK: 	at com.oney.WebRTCModule.GetUserMediaImpl.createVideoTrack(GetUserMediaImpl.java:93)
10-22 11:02:59.929  4977  5079 E JitsiMeetSDK: 	at com.oney.WebRTCModule.GetUserMediaImpl.getUserMedia(GetUserMediaImpl.java:180)
10-22 11:02:59.929  4977  5079 E JitsiMeetSDK: 	at com.oney.WebRTCModule.WebRTCModule.lambda$getUserMedia$2$WebRTCModule(WebRTCModule.java:485)
10-22 11:02:59.929  4977  5079 E JitsiMeetSDK: 	at com.oney.WebRTCModule.-$$Lambda$WebRTCModule$C_Gitx4KOYySlWXaI1K4M1yoJoA.run(Unknown Source:8)
10-22 11:02:59.929  4977  5079 E JitsiMeetSDK: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
10-22 11:02:59.929  4977  5079 E JitsiMeetSDK: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
10-22 11:02:59.929  4977  5079 E JitsiMeetSDK: 	at java.lang.Thread.run(Thread.java:919)
10-22 11:02:59.929  4977  5079 E JitsiMeetSDK: 
10-22 11:02:59.929  4977  5079 E JitsiMeetSDK: java.lang.NoSuchMethodError: No static method createEgl14([I)Lorg/webrtc/EglBase14; in class Lorg/webrtc/EglBase; or its super classes (declaration of 'org.webrtc.EglBase' appears in /data/app/org.jitsi.meet-P5W-3IXR0mvVSGeiuuoTGA==/base.apk!classes3.dex)
10-22 11:02:59.929  4977  5079 E JitsiMeetSDK: 	at com.oney.WebRTCModule.EglUtils.getRootEglBase(EglUtils.java:35)
10-22 11:02:59.929  4977  5079 E JitsiMeetSDK: 	at com.oney.WebRTCModule.EglUtils.getRootEglBaseContext(EglUtils.java:62)
10-22 11:02:59.929  4977  5079 E JitsiMeetSDK: 	at com.oney.WebRTCModule.GetUserMediaImpl.createVideoTrack(GetUserMediaImpl.java:93)
10-22 11:02:59.929  4977  5079 E JitsiMeetSDK: 	at com.oney.WebRTCModule.GetUserMediaImpl.getUserMedia(GetUserMediaImpl.java:180)
10-22 11:02:59.929  4977  5079 E JitsiMeetSDK: 	at com.oney.WebRTCModule.WebRTCModule.lambda$getUserMedia$2$WebRTCModule(WebRTCModule.java:485)
10-22 11:02:59.929  4977  5079 E JitsiMeetSDK: 	at com.oney.WebRTCModule.-$$Lambda$WebRTCModule$C_Gitx4KOYySlWXaI1K4M1yoJoA.run(Unknown Source:8)
10-22 11:02:59.929  4977  5079 E JitsiMeetSDK: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
10-22 11:02:59.929  4977  5079 E JitsiMeetSDK: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
10-22 11:02:59.929  4977  5079 E JitsiMeetSDK: 	at java.lang.Thread.run(Thread.java:919)
10-22 11:02:59.934  4201  5241 I DropBoxManagerService: add tag=data_app_crash isTagEnabled=true flags=0x2
```

I've seen more reports like this, but for the life of me, I don't know how to reproduce it even.

Can you try to add `android.enableDexingArtifactTransform.desugaring=false` to the `gradle.properties` file and see if that makes it go away?

**Comment by ips-illuminz** [comment]
Yes the issue has been resolved by enabling this option. I'm getting some warning while creating the native build for android, but it is working fine.

**Comment by saghul** [comment]
Good to know! I'm going to apply it in master then.

**Comment by saghul** [comment]
Landed on master. Cheers!
