### ISSUE TITLE
java.lang.NoSuchMethodError: No virtual method toString(Z)Ljava/lang/String; in class Lokhttp3/Cookie

### ISSUE THREAD

**Issue by Tzthaw** [jitsi/jitsi-meet#7935]
### Description:

 java.lang.NoSuchMethodError: No virtual method toString(Z)Ljava/lang/String; in class Lokhttp3/Cookie; or its super classes (declaration of 'okhttp3.Cookie' appears in /data/app/com.umg.telemedicine_doctor-b2wD7MHXhMin4zYeAsJAgA==/base.apk!classes4.dex)
        at okhttp3.JavaNetCookieJar.saveFromResponse(JavaNetCookieJar.java:45)
        at com.facebook.react.modules.network.ReactCookieJarContainer.saveFromResponse(ReactCookieJarContainer.java:36)
        at okhttp3.internal.http.HttpHeaders.receiveHeaders(HttpHeaders.kt:207)
        at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.kt:85)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:100)
        at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.kt:76)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:100)
        at okhttp3.internal.connection.RealCall.getResponseWithInterceptorChain$okhttp(RealCall.kt:197)
        at okhttp3.internal.connection.RealCall$AsyncCall.run(RealCall.kt:502)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:919)

### Expected behavior:

I call jitsi meet activity from my app but open and crush immediately.

### Actual behavior:

![image](https://user-images.githubusercontent.com/30310369/96559482-21455480-12e3-11eb-968c-4467f38cee7d.png)

### Server information:

- Jitsi Meet version: 2.10.0
- Operating System: Android 10

### Client information:

- Browser / app version:
- Operating System:

### Additional information:

okhttp version: 4.7.2
classpath "com.android.tools.build:gradle:4.0.1"
distributionUrl=https\://services.gradle.org/distributions/gradle-6.5-all.zip

**Comment by saghul** [comment]
As stated on the release notes (https://github.com/jitsi/jitsi-meet-release-notes/blob/master/CHANGELOG-MOBILE-SDKS.md#2100-2020-09-15) we (well, react native) use okhttp 3.12. You need to downgrade until react native decides to update to a more recent version or things will break.
