### ISSUE TITLE
Android crash when accessing options

### ISSUE THREAD

**Issue by SeveHo** [jitsi/jitsi-meet#8041]
### Description:

Hey, I am using the JitsiMeetSDK inside my react native project and everything works fine so far. But when a user clicks on the dotted options icon the application crashes with the following error:

```
	15:55:31.383	JitsiMeetSDK		JitsiMeetUncaughtExceptionHandler FATAL ERROR
com.facebook.react.bridge.JSApplicationIllegalArgumentException: Error while updating property 'tintColor' of a view managed by: RNSVGSvgView
	at com.facebook.react.uimanager.ViewManagersPropertyCache$PropSetter.updateViewProp(ViewManagersPropertyCache.java:102)
	at com.facebook.react.uimanager.ViewManagerPropertyUpdater$FallbackViewManagerSetter.setProperty(ViewManagerPropertyUpdater.java:136)
	at com.facebook.react.uimanager.ViewManagerPropertyUpdater.updateProps(ViewManagerPropertyUpdater.java:56)
	at com.facebook.react.uimanager.ViewManager.updateProperties(ViewManager.java:49)
	at com.facebook.react.uimanager.NativeViewHierarchyManager.createView(NativeViewHierarchyManager.java:270)
	at com.facebook.react.uimanager.UIViewOperationQueue$CreateViewOperation.execute(UIViewOperationQueue.java:186)
	at com.facebook.react.uimanager.UIViewOperationQueue$DispatchUIFrameCallback.dispatchPendingNonBatchedOperations(UIViewOperationQueue.java:1112)
	at com.facebook.react.uimanager.UIViewOperationQueue$DispatchUIFrameCallback.doFrameGuarded(UIViewOperationQueue.java:1083)
	at com.facebook.react.uimanager.GuardedFrameCallback.doFrame(GuardedFrameCallback.java:29)
	at com.facebook.react.modules.core.ReactChoreographer$ReactChoreographerDispatcher.doFrame(ReactChoreographer.java:175)
	at com.facebook.react.modules.core.ChoreographerCompat$FrameCallback$1.doFrame(ChoreographerCompat.java:85)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:947)
	at android.view.Choreographer.doCallbacks(Choreographer.java:761)
	at android.view.Choreographer.doFrame(Choreographer.java:693)
	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:935)
	at android.os.Handler.handleCallback(Handler.java:873)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:193)
	at android.app.ActivityThread.main(ActivityThread.java:6669)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
Caused by: java.lang.ClassCastException: java.lang.String cannot be cast to java.lang.Integer
	at com.facebook.react.uimanager.ViewManagersPropertyCache$BoxedIntPropSetter.getValueOrDefault(ViewManagersPropertyCache.java:321)
	at com.facebook.react.uimanager.ViewManagersPropertyCache$PropSetter.updateViewProp(ViewManagersPropertyCache.java:86)
	... 21 more

com.facebook.react.bridge.JSApplicationIllegalArgumentException: Error while updating property 'tintColor' of a view managed by: RNSVGSvgView
	at com.facebook.react.uimanager.ViewManagersPropertyCache$PropSetter.updateViewProp(ViewManagersPropertyCache.java:102)
	at com.facebook.react.uimanager.ViewManagerPropertyUpdater$FallbackViewManagerSetter.setProperty(ViewManagerPropertyUpdater.java:136)
	at com.facebook.react.uimanager.ViewManagerPropertyUpdater.updateProps(ViewManagerPropertyUpdater.java:56)
	at com.facebook.react.uimanager.ViewManager.updateProperties(ViewManager.java:49)
	at com.facebook.react.uimanager.NativeViewHierarchyManager.createView(NativeViewHierarchyManager.java:270)
	at com.facebook.react.uimanager.UIViewOperationQueue$CreateViewOperation.execute(UIViewOperationQueue.java:186)
	at com.facebook.react.uimanager.UIViewOperationQueue$DispatchUIFrameCallback.dispatchPendingNonBatchedOperations(UIViewOperationQueue.java:1112)
	at com.facebook.react.uimanager.UIViewOperationQueue$DispatchUIFrameCallback.doFrameGuarded(UIViewOperationQueue.java:1083)
	at com.facebook.react.uimanager.GuardedFrameCallback.doFrame(GuardedFrameCallback.java:29)
	at com.facebook.react.modules.core.ReactChoreographer$ReactChoreographerDispatcher.doFrame(ReactChoreographer.java:175)
	at com.facebook.react.modules.core.ChoreographerCompat$FrameCallback$1.doFrame(ChoreographerCompat.java:85)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:947)
	at android.view.Choreographer.doCallbacks(Choreographer.j
```

### Steps to reproduce:

1. Integrate the JitsiMeetSDK in your react native project
2. Create a conference call
3. Click on the options button

### Expected behavior:

The modal view for the different options should open.

### Actual behavior:

Fatal error and the application crashes.

<p align="center">
    <img src="https://user-images.githubusercontent.com/20375523/98258973-cc136f00-1f81-11eb-81bb-373bdad46466.gif" width="30%" />
</p>

### Client information:

- Android API 28
- JitsiMeetSDK 2.8.+ and 2.10.+
- React Native 0.63.2
(- react-native-svg 12.0.3)

**Comment by sernocturno** [comment]
#

> 
> ### Description:
> 
> Hey, I am using the JitsiMeetSDK inside my react native project and everything works fine so far. But when a user clicks on the dotted options icon the application crashes with the following error:
> 
> ```
> 	15:55:31.383	JitsiMeetSDK		JitsiMeetUncaughtExceptionHandler FATAL ERROR
> com.facebook.react.bridge.JSApplicationIllegalArgumentException: Error while updating property 'tintColor' of a view managed by: RNSVGSvgView
> 	at com.facebook.react.uimanager.ViewManagersPropertyCache$PropSetter.updateViewProp(ViewManagersPropertyCache.java:102)
> 	at com.facebook.react.uimanager.ViewManagerPropertyUpdater$FallbackViewManagerSetter.setProperty(ViewManagerPropertyUpdater.java:136)
> 	at com.facebook.react.uimanager.ViewManagerPropertyUpdater.updateProps(ViewManagerPropertyUpdater.java:56)
> 	at com.facebook.react.uimanager.ViewManager.updateProperties(ViewManager.java:49)
> 	at com.facebook.react.uimanager.NativeViewHierarchyManager.createView(NativeViewHierarchyManager.java:270)
> 	at com.facebook.react.uimanager.UIViewOperationQueue$CreateViewOperation.execute(UIViewOperationQueue.java:186)
> 	at com.facebook.react.uimanager.UIViewOperationQueue$DispatchUIFrameCallback.dispatchPendingNonBatchedOperations(UIViewOperationQueue.java:1112)
> 	at com.facebook.react.uimanager.UIViewOperationQueue$DispatchUIFrameCallback.doFrameGuarded(UIViewOperationQueue.java:1083)
> 	at com.facebook.react.uimanager.GuardedFrameCallback.doFrame(GuardedFrameCallback.java:29)
> 	at com.facebook.react.modules.core.ReactChoreographer$ReactChoreographerDispatcher.doFrame(ReactChoreographer.java:175)
> 	at com.facebook.react.modules.core.ChoreographerCompat$FrameCallback$1.doFrame(ChoreographerCompat.java:85)
> 	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:947)
> 	at android.view.Choreographer.doCallbacks(Choreographer.java:761)
> 	at android.view.Choreographer.doFrame(Choreographer.java:693)
> 	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:935)
> 	at android.os.Handler.handleCallback(Handler.java:873)
> 	at android.os.Handler.dispatchMessage(Handler.java:99)
> 	at android.os.Looper.loop(Looper.java:193)
> 	at android.app.ActivityThread.main(ActivityThread.java:6669)
> 	at java.lang.reflect.Method.invoke(Native Method)
> 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
> 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
> Caused by: java.lang.ClassCastException: java.lang.String cannot be cast to java.lang.Integer
> 	at com.facebook.react.uimanager.ViewManagersPropertyCache$BoxedIntPropSetter.getValueOrDefault(ViewManagersPropertyCache.java:321)
> 	at com.facebook.react.uimanager.ViewManagersPropertyCache$PropSetter.updateViewProp(ViewManagersPropertyCache.java:86)
> 	... 21 more
> 
> com.facebook.react.bridge.JSApplicationIllegalArgumentException: Error while updating property 'tintColor' of a view managed by: RNSVGSvgView
> 	at com.facebook.react.uimanager.ViewManagersPropertyCache$PropSetter.updateViewProp(ViewManagersPropertyCache.java:102)
> 	at com.facebook.react.uimanager.ViewManagerPropertyUpdater$FallbackViewManagerSetter.setProperty(ViewManagerPropertyUpdater.java:136)
> 	at com.facebook.react.uimanager.ViewManagerPropertyUpdater.updateProps(ViewManagerPropertyUpdater.java:56)
> 	at com.facebook.react.uimanager.ViewManager.updateProperties(ViewManager.java:49)
> 	at com.facebook.react.uimanager.NativeViewHierarchyManager.createView(NativeViewHierarchyManager.java:270)
> 	at com.facebook.react.uimanager.UIViewOperationQueue$CreateViewOperation.execute(UIViewOperationQueue.java:186)
> 	at com.facebook.react.uimanager.UIViewOperationQueue$DispatchUIFrameCallback.dispatchPendingNonBatchedOperations(UIViewOperationQueue.java:1112)
> 	at com.facebook.react.uimanager.UIViewOperationQueue$DispatchUIFrameCallback.doFrameGuarded(UIViewOperationQueue.java:1083)
> 	at com.facebook.react.uimanager.GuardedFrameCallback.doFrame(GuardedFrameCallback.java:29)
> 	at com.facebook.react.modules.core.ReactChoreographer$ReactChoreographerDispatcher.doFrame(ReactChoreographer.java:175)
> 	at com.facebook.react.modules.core.ChoreographerCompat$FrameCallback$1.doFrame(ChoreographerCompat.java:85)
> 	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:947)
> 	at android.view.Choreographer.doCallbacks(Choreographer.j
> ```
> 
> ### Steps to reproduce:
> 
>     1. Integrate the JitsiMeetSDK in your react native project
> 
>     2. Create a conference call
> 
>     3. Click on the options button
> 
> 
> ### Expected behavior:
> 
> The modal view for the different options should open.
> ### Actual behavior:
> 
> Fatal error and the application crashes.
> 
> <img alt="" width="30%" src="https://user-images.githubusercontent.com/20375523/98258973-cc136f00-1f81-11eb-81bb-373bdad46466.gif">
> ### Client information:
> 
>     * Android API 28
> 
>     * JitsiMeetSDK 2.8.+ and 2.10.+
> 
>     * React Native 0.63.2
>       (- react-native-svg 12.0.3)

same probem on flutter

**Comment by sernocturno** [comment]
here the log

`E/JitsiMeetSDK(10217): 	at com.facebook.react.uimanager.ViewManager.updateProperties(ViewManager.java:48)
E/JitsiMeetSDK(10217): 	at com.facebook.react.uimanager.NativeViewHierarchyManager.createView(NativeViewHierarchyManager.java:278)
E/JitsiMeetSDK(10217): 	at com.facebook.react.uimanager.UIViewOperationQueue$CreateViewOperation.execute(UIViewOperationQueue.java:179)
E/JitsiMeetSDK(10217): 	at com.facebook.react.uimanager.UIViewOperationQueue$DispatchUIFrameCallback.dispatchPendingNonBatchedOperations(UIViewOperationQueue.java:972)
E/JitsiMeetSDK(10217): 	at com.facebook.react.uimanager.UIViewOperationQueue$DispatchUIFrameCallback.doFrameGuarded(UIViewOper
I/Process (10217): Sending signal. PID: 10217 SIG: 9
Lost connection to device.
`

**Comment by saghul** [comment]
>     * React Native 0.63.2

We don't currently support that RN version. We use 0.61.5.
