### ISSUE TITLE
App is getting crashed when start meeting

### ISSUE THREAD

**Issue by ips-illuminz** [jitsi/jitsi-meet#8048]
Hey guys,
I have been using jitsi custom android build, before it was working fine but with the new build i'm getting the following error

`java.lang.NoSuchMethodError: No static method delimiterOffset(Ljava/lang/String;IILjava/lang/String;)I in class Lokhttp3/internal/Util; or its super classes (declaration of 'okhttp3.internal.Util' appears in /data/app/com.gigipo.dev-n0PJmb8OXxAoyXxVdYwooA==/base.apk!classes4.dex)`

Thanks,
Inder

**Comment by saghul** [comment]
I assume you are using the Android SDK. What version of okhttp are you using? It should be 3.12, if you move it past that things will break because that's the one we use internally.

**Comment by ips-illuminz** [comment]
Hi @saghul , I'm using the latest build, and generating android sdk from that. The okhttp version must be latest then, in the progaurd-rules.pro file the following version is mentioned: okhttp3.**

**Comment by saghul** [comment]
Any chance other dependencies on the project you are using the SDK on bump that dependency?

**Comment by ips-illuminz** [comment]
We are creating our own video chat application and i need to check with android team for all the dependencies but we are using Jitsi as a separate android sdk and using in our application. Before it was working fine and we are facing this issue from last month, sometimes one side video is getting off and audio is not coming, sometimes recording stops working. The issues are happening very frequently and now it's becoming headache for me. Because we have deployed everything according to jitsi, aws instances and lot of other dependencies are on it. Kindly help me out to solve this issue, your efforts will be very much appreciated. 
Thanks in advance for your help!

**Comment by MuthuShenll** [comment]
HI @saghul getting same exception like this
java.lang.NoClassDefFoundError: Failed resolution of: Lcom/oney/WebRTCModule/WebRTCModule$Options;

I have added `android.enableDexingArtifactTransform.desugaring=false` in `graddle.properties` file. but seems getting exception again

`  Caused by: java.lang.ClassNotFoundException: Didn't find class "com.oney.WebRTCModule.WebRTCModule$Options" on path: DexPathList[[zip file "/data/app/com.abcd.xyz-ivYMnkWAy5v75yBro2N0_Q==/base.apk"],nativeLibraryDirectories=[/data/app/com.abcd.xyz-ivYMnkWAy5v75yBro2N0_Q==/lib/arm64, /data/app/com.abcd.xyzr-ivYMnkWAy5v75yBro2N0_Q==/base.apk!/lib/arm64-v8a, /system/lib64, /system/product/lib64]]`

**Comment by MuthuShenll** [comment]
`E/AndroidRuntime: FATAL EXCEPTION: create_react_context
    Process: com.abcd.xyz PID: 20818
    java.lang.NoClassDefFoundError: Failed resolution of: Lcom/oney/WebRTCModule/WebRTCModule$Options;
        at org.jitsi.meet.sdk.ReactInstanceManagerHolder.createNativeModules(ReactInstanceManagerHolder.java:83)
        at org.jitsi.meet.sdk.ReactInstanceManagerHolder.access$000(ReactInstanceManagerHolder.java:48)
        at org.jitsi.meet.sdk.ReactInstanceManagerHolder$1.createNativeModules(ReactInstanceManagerHolder.java:204)
        at com.facebook.react.ReactPackageHelper.getNativeModuleIterator(ReactPackageHelper.java:41)
        at com.facebook.react.NativeModuleRegistryBuilder.processPackage(NativeModuleRegistryBuilder.java:41)
        at com.facebook.react.ReactInstanceManager.processPackage(ReactInstanceManager.java:1230)
        at com.facebook.react.ReactInstanceManager.processPackages(ReactInstanceManager.java:1201)
        at com.facebook.react.ReactInstanceManager.createReactContext(ReactInstanceManager.java:1134)
        at com.facebook.react.ReactInstanceManager.access$1000(ReactInstanceManager.java:125)
        at com.facebook.react.ReactInstanceManager$5.run(ReactInstanceManager.java:951)
        at java.lang.Thread.run(Thread.java:919)
     Caused by: java.lang.ClassNotFoundException: Didn't find class "com.oney.WebRTCModule.WebRTCModule$Options" on path: DexPathList[[zip file "/data/app/com.abcd.xyzr-ivYMnkWAy5v75yBro2N0_Q==/base.apk"],nativeLibraryDirectories=[/data/app/com.abcd.xyz-ivYMnkWAy5v75yBro2N0_Q==/lib/arm64, /data/app/com.abcd.xyz-ivYMnkWAy5v75yBro2N0_Q==/base.apk!/lib/arm64-v8a, /system/lib64, /system/product/lib64]]
        at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:196)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:312)`

**Comment by MuthuShenll** [comment]
I am using 
distributionUrl=https\://services.gradle.org/distributions/gradle-6.5-bin.zip
 classpath 'com.android.tools.build:gradle:4.0.2'

**Comment by ips-illuminz** [comment]
#8220

**Comment by 1433498251** [comment]
> `E/AndroidRuntime: FATAL EXCEPTION: create_react_context Process: com.abcd.xyz PID: 20818 java.lang.NoClassDefFoundError: Failed resolution of: Lcom/oney/WebRTCModule/WebRTCModule$Options; at org.jitsi.meet.sdk.ReactInstanceManagerHolder.createNativeModules(ReactInstanceManagerHolder.java:83) at org.jitsi.meet.sdk.ReactInstanceManagerHolder.access$000(ReactInstanceManagerHolder.java:48) at org.jitsi.meet.sdk.ReactInstanceManagerHolder$1.createNativeModules(ReactInstanceManagerHolder.java:204) at com.facebook.react.ReactPackageHelper.getNativeModuleIterator(ReactPackageHelper.java:41) at com.facebook.react.NativeModuleRegistryBuilder.processPackage(NativeModuleRegistryBuilder.java:41) at com.facebook.react.ReactInstanceManager.processPackage(ReactInstanceManager.java:1230) at com.facebook.react.ReactInstanceManager.processPackages(ReactInstanceManager.java:1201) at com.facebook.react.ReactInstanceManager.createReactContext(ReactInstanceManager.java:1134) at com.facebook.react.ReactInstanceManager.access$1000(ReactInstanceManager.java:125) at com.facebook.react.ReactInstanceManager$5.run(ReactInstanceManager.java:951) at java.lang.Thread.run(Thread.java:919) Caused by: java.lang.ClassNotFoundException: Didn't find class "com.oney.WebRTCModule.WebRTCModule$Options" on path: DexPathList[[zip file "/data/app/com.abcd.xyzr-ivYMnkWAy5v75yBro2N0_Q==/base.apk"],nativeLibraryDirectories=[/data/app/com.abcd.xyz-ivYMnkWAy5v75yBro2N0_Q==/lib/arm64, /data/app/com.abcd.xyz-ivYMnkWAy5v75yBro2N0_Q==/base.apk!/lib/arm64-v8a, /system/lib64, /system/product/lib64]] at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:196) at java.lang.ClassLoader.loadClass(ClassLoader.java:379) at java.lang.ClassLoader.loadClass(ClassLoader.java:312)`
I also encountered the same error. How did you solve it? Thank you very much
