### ISSUE TITLE
App is crashing on startup.

### ISSUE THREAD

**Issue by 1Ajay** [jitsi/jitsi-meet#8167]
--------- beginning of crash
2020-11-26 19:25:25.607 2251-2344/? E/AndroidRuntime: FATAL EXCEPTION: mqt_native_modules
Process: com.xxx.xxx, PID: 2251
com.facebook.react.common.JavascriptException: TypeError: null is not an object (evaluating ‘n.IsAndroid’), stack:
@831:84
v@2:1473
@434:422
v@2:1473
at com.facebook.react.modules.core.ExceptionsManagerModule.reportException(ExceptionsManagerModule.java:12)
at java.lang.reflect.Method.invoke(Native Method)
at com.facebook.react.bridge.JavaMethodWrapper.invoke(JavaMethodWrapper.java:18)
at com.facebook.react.bridge.JavaModuleWrapper.invoke(JavaModuleWrapper.java:2)
at com.facebook.react.bridge.queue.NativeRunnable.run(Native Method)
at android.os.Handler.handleCallback(Handler.java:883)
at android.os.Handler.dispatchMessage(Handler.java:100)
at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:1)
at android.os.Looper.loop(Looper.java:228)
at com.facebook.react.bridge.queue.MessageQueueThreadImpl$4.run(MessageQueueThreadImpl.java:8)
at java.lang.Thread.run(Thread.java:919)

**Comment by saghul** [comment]
Is this your app using the SDK or your own build of Jitsi Meet? In case it's the latter, what commit did you build? Do you have any changes?

Please put more effort into making a proper bug report, otherwise it's very hard to help you.

**Comment by 1Ajay** [comment]
Found a solution.
running this command and removing duplicate files in raw files. it's working fine.
**npx react-native bundle --platform android --dev false --entry-file index.js --bundle-output ./android/app/src/main/assets/index.android.bundle --assets-dest ./android/app/src/main/res/**
