### ISSUE TITLE
Debian 10 Buster: javax.net.ssl.SSLHandshakeException: PKIX path building failed in jicofo.log and jvb.log

### ISSUE THREAD

**Issue by boomshankerx** [jitsi/jitsi-meet#8243]
Debian 10.7.0 (Buster) 
adoptopenjdk-8-hotspot
Fresh install as per https://jitsi.github.io/handbook/docs/devops-guide/devops-guide-quickstart

Everything works out of the box except for the jicofo.log and jvb.log errors listed below causing no sound or video

Workaround:
`echo "org.jitsi.jicofo.ALWAYS_TRUST_MODE_ENABLED=true" >> /etc/jitsi/jicofo/sip-communicator.properties`
`echo "org.jitsi.videobridge.xmpp.user.shard.DISABLE_CERTIFICATE_VERIFICATION=true" >> /etc/jitsi/videobridge/sip-communicator.properties`

Is there a more correct solution to this problem?

# jicofo.log

Jicofo 2020-12-13 17:26:11.784 WARNING: [113] org.jivesoftware.smack.AbstractXMPPConnection.callConnectionClosedOnErrorListener() Connection XMPPTCPConnection[not-authenticated] (0) closed with error
javax.net.ssl.SSLHandshakeException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
        at sun.security.ssl.Alert.createSSLException(Alert.java:131)
        at sun.security.ssl.TransportContext.fatal(TransportContext.java:324)
        at sun.security.ssl.TransportContext.fatal(TransportContext.java:267)
        at sun.security.ssl.TransportContext.fatal(TransportContext.java:262)
        at sun.security.ssl.CertificateMessage$T12CertificateConsumer.checkServerCerts(CertificateMessage.java:654)
        at sun.security.ssl.CertificateMessage$T12CertificateConsumer.onCertificate(CertificateMessage.java:473)
        at sun.security.ssl.CertificateMessage$T12CertificateConsumer.consume(CertificateMessage.java:369)
        at sun.security.ssl.SSLHandshake.consume(SSLHandshake.java:377)
        at sun.security.ssl.HandshakeContext.dispatch(HandshakeContext.java:444)
        at sun.security.ssl.HandshakeContext.dispatch(HandshakeContext.java:422)
        at sun.security.ssl.TransportContext.dispatch(TransportContext.java:182)
        at sun.security.ssl.SSLTransport.decode(SSLTransport.java:149)
        at sun.security.ssl.SSLSocketImpl.decode(SSLSocketImpl.java:1143)
        at sun.security.ssl.SSLSocketImpl.readHandshakeRecord(SSLSocketImpl.java:1054)
        at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:394)
        at org.jivesoftware.smack.tcp.XMPPTCPConnection.proceedTLSReceived(XMPPTCPConnection.java:810)
        at org.jivesoftware.smack.tcp.XMPPTCPConnection.access$1200(XMPPTCPConnection.java:151)
        at org.jivesoftware.smack.tcp.XMPPTCPConnection$PacketReader.parsePackets(XMPPTCPConnection.java:1071)
        at org.jivesoftware.smack.tcp.XMPPTCPConnection$PacketReader.access$300(XMPPTCPConnection.java:1000)
        at org.jivesoftware.smack.tcp.XMPPTCPConnection$PacketReader$1.run(XMPPTCPConnection.java:1016)
        at java.lang.Thread.run(Thread.java:748)
Caused by: sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
        at sun.security.validator.PKIXValidator.doBuild(PKIXValidator.java:456)
        at sun.security.validator.PKIXValidator.engineValidate(PKIXValidator.java:323)
        at sun.security.validator.Validator.validate(Validator.java:271)
        at sun.security.ssl.X509TrustManagerImpl.validate(X509TrustManagerImpl.java:315)
        at sun.security.ssl.X509TrustManagerImpl.checkTrusted(X509TrustManagerImpl.java:223)
        at sun.security.ssl.X509TrustManagerImpl.checkServerTrusted(X509TrustManagerImpl.java:129)
        at sun.security.ssl.CertificateMessage$T12CertificateConsumer.checkServerCerts(CertificateMessage.java:638)
        ... 16 more
Caused by: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
        at sun.security.provider.certpath.SunCertPathBuilder.build(SunCertPathBuilder.java:141)
        at sun.security.provider.certpath.SunCertPathBuilder.engineBuild(SunCertPathBuilder.java:126)
        at java.security.cert.CertPathBuilder.build(CertPathBuilder.java:280)
        at sun.security.validator.PKIXValidator.doBuild(PKIXValidator.java:451)
        ... 22 more

# jvb.log

 2020-12-13 18:11:14.644 WARNING: [224] [hostname=localhost id=shard] MucClient$1.connectionClosedOnError#317: Closed on error:
11920 javax.net.ssl.SSLHandshakeException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
11921     at sun.security.ssl.Alert.createSSLException(Alert.java:131)
11922     at sun.security.ssl.TransportContext.fatal(TransportContext.java:324)
11923     at sun.security.ssl.TransportContext.fatal(TransportContext.java:267)
11924     at sun.security.ssl.TransportContext.fatal(TransportContext.java:262)
11925     at sun.security.ssl.CertificateMessage$T12CertificateConsumer.checkServerCerts(CertificateMessage.java:654)
11926     at sun.security.ssl.CertificateMessage$T12CertificateConsumer.onCertificate(CertificateMessage.java:473)
11927     at sun.security.ssl.CertificateMessage$T12CertificateConsumer.consume(CertificateMessage.java:369)
11928     at sun.security.ssl.SSLHandshake.consume(SSLHandshake.java:377)
11929     at sun.security.ssl.HandshakeContext.dispatch(HandshakeContext.java:444)
11930     at sun.security.ssl.HandshakeContext.dispatch(HandshakeContext.java:422)
11931     at sun.security.ssl.TransportContext.dispatch(TransportContext.java:182)
11932     at sun.security.ssl.SSLTransport.decode(SSLTransport.java:149)
11933     at sun.security.ssl.SSLSocketImpl.decode(SSLSocketImpl.java:1143)
11934     at sun.security.ssl.SSLSocketImpl.readHandshakeRecord(SSLSocketImpl.java:1054)
11935     at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:394)
11936     at org.jivesoftware.smack.tcp.XMPPTCPConnection.proceedTLSReceived(XMPPTCPConnection.java:810)
11937     at org.jivesoftware.smack.tcp.XMPPTCPConnection.access$1200(XMPPTCPConnection.java:151)
11938     at org.jivesoftware.smack.tcp.XMPPTCPConnection$PacketReader.parsePackets(XMPPTCPConnection.java:1071)
11939     at org.jivesoftware.smack.tcp.XMPPTCPConnection$PacketReader.access$300(XMPPTCPConnection.java:1000)
11940     at org.jivesoftware.smack.tcp.XMPPTCPConnection$PacketReader$1.run(XMPPTCPConnection.java:1016)
11941     at java.lang.Thread.run(Thread.java:748)
11942 Caused by: sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
11943     at sun.security.validator.PKIXValidator.doBuild(PKIXValidator.java:456)
11944     at sun.security.validator.PKIXValidator.engineValidate(PKIXValidator.java:323)
11945     at sun.security.validator.Validator.validate(Validator.java:271)
11946     at sun.security.ssl.X509TrustManagerImpl.validate(X509TrustManagerImpl.java:315)
11947     at sun.security.ssl.X509TrustManagerImpl.checkTrusted(X509TrustManagerImpl.java:223)
11948     at sun.security.ssl.X509TrustManagerImpl.checkServerTrusted(X509TrustManagerImpl.java:129)
11949     at sun.security.ssl.CertificateMessage$T12CertificateConsumer.checkServerCerts(CertificateMessage.java:638)
11950     ... 16 more
11951 Caused by: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
11952     at sun.security.provider.certpath.SunCertPathBuilder.build(SunCertPathBuilder.java:141)
11953     at sun.security.provider.certpath.SunCertPathBuilder.engineBuild(SunCertPathBuilder.java:126)
11954     at java.security.cert.CertPathBuilder.build(CertPathBuilder.java:280)
11955     at sun.security.validator.PKIXValidator.doBuild(PKIXValidator.java:451)
11956     ... 22 more

**Comment by damencho** [comment]
Please report it to adoptopenjdk and add a link as a reference. Based on their answer we may add a workaround till they fix it.

**Comment by boomshankerx** [comment]
I've confirmed that this issue is related to how adoptopenjdk currently does not handle  importing of CA certificates on Debian.
https://github.com/AdoptOpenJDK/openjdk-installer/issues/105

Installation of `ca-certificates-java` will fail to install while installing `adoptopenjdk-8-hotspot`  due to a cyclical dependency issue.

# Workarounds

## Manually import the certificate
`keytool -import -v -trustcacerts -alias auth.HOSTNAME -file /usr/local/share/ca-certificates/HOSTNAME.crt -keystore  /usr/lib/jvm/adoptopenjdk-8-hotspot-amd64/jre/lib/security/cacerts -keypass changeit -storepass changeit`

## Manually install `ca-certificates-java` and link cacerts
Manually installing `ca-certificates-java` and manually symlinking `/usr/lib/jvm/adoptopenjdk-8-hotspot-amd64/jre/lib/security/cacerts` to `/etc/ssl/certs/java/cacerts` may work.

`apt install ca-certificates-java`
`cd /usr/lib/jvm/adoptopenjdk-8-hotspot-amd64/jre/lib/security/`
`mv cacerts cacerts.old`
`ln -s /etc/ssl/certs/java/cacerts cacerts`
 
### Sources:
https://github.com/AdoptOpenJDK/openjdk-installer/issues/105
https://github.com/docker-library/openjdk/issues/327
http://rabexc.org/posts/certificates-not-working-java#comment-4099504075

**Comment by fweimer** [comment]
Is there a reason why the Debian's OpenJDK 11 isn't recommended over the AdoptOpenJDK build of OpenJDK 8? Debian's 11.0.9.1+1-1~deb10u2 build seems to work for me.

**Comment by boomshankerx** [comment]
https://community.jitsi.org/t/what-is-the-recommend-java-version/28955

**Comment by mdpdesign** [comment]
As for the workarounds..

In our case the symlink didn't work properly (`/usr/lib/jvm/adoptopenjdk-8-hotspot-amd64/jre/lib/security/` path doesn't exist, even after installing `ca-certificates-java`), we build our Jenkins image on top of the LTS Docker image delivered by Jenkins. We add our certificates to the system etc. but we do not modify any other Java related settings, until now.

When I checked `$JAVA_HOME` variable it was set to `/opt/java/openjdk` and Java was using this cert store: `/opt/java/openjdk/jre/lib/security/cacerts`.

So I symlinked `/etc/ssl/certs/java/cacerts` to `/opt/java/openjdk/jre/lib/security/cacerts` and that finally worked for us to resolve:

> javax.net.ssl.SSLHandshakeException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target

Maybe this helps someone.

**Comment by ryancdotorg** [comment]
It's probably better to do the following so that a later package update will not break things again (just happened to me):

```
sudo apt install ca-certificates-java
sudo dpkg-divert --divert /usr/lib/jvm/adoptopenjdk-8-hotspot-amd64/jre/lib/security/cacerts.dist --rename --local --add /usr/lib/jvm/adoptopenjdk-8-hotspot-amd64/jre/lib/security/cacerts
sudo ln -s /etc/ssl/certs/java/cacerts /usr/lib/jvm/adoptopenjdk-8-hotspot-amd64/jre/lib/security/cacerts
```

**Comment by saghul** [comment]
@ryancdotorg Mind making a PR adding that to the handbook here? https://jitsi.github.io/handbook/docs/devops-guide/devops-guide-quickstart

**Comment by ryancdotorg** [comment]
@saghul That'd be against the handbook repo?

**Comment by ryancdotorg** [comment]
@saghul Okay, cool. How about a short "If you're using AdoptOpenJDK 8..." section after "Generate a Let's Encrypt certificate"?

**Comment by saghul** [comment]
Sounds good!
