### ISSUE TITLE
F-Droid can't build - non-FOSS libs

### ISSUE THREAD

**Issue by licaon-kter** [jitsi/jitsi-meet#8353]
```
ERROR: Found usual suspect 'firebase' at node_modules/react-native-device-info/android/build.gradle
ERROR: Found usual suspect 'google.*play.*services' at node_modules/react-native-device-info/android/build.gradle
ERROR: Found unknown maven repo '$rootDir/../node_modules/react-native/android' at node_modules/react-native-device-info/android/build.gradle
```

An odd little dependency that blocks other apps too iirc, apparently without closed source Google Services apps can't just find out 2-3 properties about the device they run on. 🙁 

Can that be fenced off since it's used (only) by Amplitude tracking and we don't need that in F-Droid anyway?
```
2021-01-07 12:13:17,532 DEBUG: buildserver > error Unable to resolve module `react-native-device-info` from `node_modules/amplitude-js/amplitude.native.js`: react-native-device-info could not be found within the project.
2021-01-07 12:13:17,533 DEBUG: buildserver >
2021-01-07 12:13:17,533 DEBUG: buildserver > Error: Unable to resolve module `react-native-device-info` from `node_modules/amplitude-js/amplitude.native.js`: react-native-device-info could not be found within the project.
2021-01-07 12:13:17,533 DEBUG: buildserver > If you are sure the module exists, try these steps:
2021-01-07 12:13:17,533 DEBUG: buildserver >  1. Clear watchman watches: watchman watch-del-all
2021-01-07 12:13:17,533 DEBUG: buildserver >
2021-01-07 12:13:17,534 DEBUG: buildserver >  2. Delete node_modules: rm -rf node_modules and run yarn install
2021-01-07 12:13:17,534 DEBUG: buildserver > If you are sure the module exists, try these steps:
2021-01-07 12:13:17,534 DEBUG: buildserver >  3. Reset Metro's cache: yarn start --reset-cache
2021-01-07 12:13:17,534 DEBUG: buildserver >  1. Clear watchman watches: watchman watch-del-all
2021-01-07 12:13:17,534 DEBUG: buildserver >  4. Remove the cache: rm -rf /tmp/metro-*. Run CLI with --verbose flag for more details.
2021-01-07 12:13:17,535 DEBUG: buildserver >  2. Delete node_modules: rm -rf node_modules and run yarn install
2021-01-07 12:13:17,535 DEBUG: buildserver >  3. Reset Metro's cache: yarn start --reset-cache
2021-01-07 12:13:17,535 DEBUG: buildserver >  4. Remove the cache: rm -rf /tmp/metro-*
2021-01-07 12:13:17,535 DEBUG: buildserver >     at ModuleResolver.resolveDependency (/home/vagrant/build/org.jitsi.meet/node_modules/metro/src/node-haste/DependencyGraph/ModuleResolution.js:186:15)
2021-01-07 12:13:17,536 DEBUG: buildserver >     at ResolutionRequest.resolveDependency (/home/vagrant/build/org.jitsi.meet/node_modules/metro/src/node-haste/DependencyGraph/ResolutionRequest.js:52:18)
2021-01-07 12:13:17,536 DEBUG: buildserver >     at DependencyGraph.resolveDependency (/home/vagrant/build/org.jitsi.meet/node_modules/metro/src/node-haste/DependencyGraph.js:282:16)
2021-01-07 12:13:17,536 DEBUG: buildserver >     at Object.resolve (/home/vagrant/build/org.jitsi.meet/node_modules/metro/src/lib/transformHelpers.js:267:42)
2021-01-07 12:13:17,536 DEBUG: buildserver >     at dependencies.map.result (/home/vagrant/build/org.jitsi.meet/node_modules/metro/src/DeltaBundler/traverseDependencies.js:426:31)
2021-01-07 12:13:17,536 DEBUG: buildserver >     at Array.map (<anonymous>)
2021-01-07 12:13:17,537 DEBUG: buildserver >     at resolveDependencies (/home/vagrant/build/org.jitsi.meet/node_modules/metro/src/DeltaBundler/traverseDependencies.js:423:18)
2021-01-07 12:13:17,537 DEBUG: buildserver >     at /home/vagrant/build/org.jitsi.meet/node_modules/metro/src/DeltaBundler/traverseDependencies.js:275:33
2021-01-07 12:13:17,537 DEBUG: buildserver >     at Generator.next (<anonymous>)
2021-01-07 12:13:17,537 DEBUG: buildserver >     at asyncGeneratorStep (/home/vagrant/build/org.jitsi.meet/node_modules/metro/src/DeltaBundler/traverseDependencies.js:87:24)
2021-01-07 12:13:17,538 DEBUG: buildserver >
2021-01-07 12:13:17,538 DEBUG: buildserver > > Task :sdk:bundleReleaseJsAndAssets FAILED
```

**Comment by saghul** [comment]
Ah, bugger. It's kinda tricky but I think I have a way to make it work. Note that this is a false positive:

```
ERROR: Found usual suspect 'firebase' at node_modules/react-native-device-info/android/build.gradle
```

We don't use the firebase APIs at all, they are optional dependencies.

**Comment by licaon-kter** [comment]
I can remove that myself, yes, but now I'm testing a clean up version of https://github.com/jitsi/jitsi-meet/blob/master/react/features/analytics/handlers/amplitude/fixDeviceID.native.js#L2 z)

**Comment by saghul** [comment]
Fix in https://github.com/jitsi/jitsi-meet/pull/8357

Before:

```
$./gradlew :app:dependencies | grep -A5 react-native-device-info
|    +--- project :react-native-device-info
|    |    +--- com.facebook.react:react-native:+ -> 0.61.5-jitsi.2 (*)
|    |    +--- com.android.installreferrer:installreferrer:1.1.2
|    |    \--- com.google.android.gms:play-services-iid:17.0.0
|    |         +--- androidx.collection:collection:1.0.0 -> 1.1.0 (*)
|    |         +--- androidx.core:core:1.0.0 -> 1.3.0 (*)
--
```

After:

```
$./gradlew :app:dependencies | grep -A5 react-native-device-info
|    +--- project :react-native-device-info
|    |    +--- com.facebook.react:react-native:+ -> 0.61.5-jitsi.2 (*)
|    |    \--- com.android.installreferrer:installreferrer:1.1.2
|    +--- project :react-native-async-storage
|    |    \--- com.facebook.react:react-native:+ -> 0.61.5-jitsi.2 (*)
|    +--- project :react-native-background-timer
--
```

**Comment by licaon-kter** [comment]
Oh, I see, let me try that commit then

**Comment by licaon-kter** [comment]
@saghul Thanks for that command

Now, can you remove this non-FOSS dep too: `com.android.installreferrer:installreferrer`

**Comment by saghul** [comment]
> I can remove that myself, yes, but now I'm testing a clean up version of https://github.com/jitsi/jitsi-meet/blob/master/react/features/analytics/handlers/amplitude/fixDeviceID.native.js#L2 ;)

I'd rather you didn't mess with the source code. Yes, I know it's dead code anyway, but bugs can happen if code gets moved around, and I plan to use the device-info module for simplifying some other non-analytics code in the future.

**Comment by saghul** [comment]
> @saghul Thanks for that command
> 
> Now, can you remove this non-FOSS dep too: `com.android.installreferrer:installreferrer`

Let me check.

**Comment by licaon-kter** [comment]
> I'd rather you didn't mess with the source code.

Well I kept myself busy during the long )but failing) builds, that just seemed a clan way until you show up with the dev fix :)

**Comment by saghul** [comment]
I cannot remove `com.android.installreferrer:installreferrer` because it would fail at runtime. Unlike the ID providers the react-native-device-info library doesn't handle its non-existence gracefully.

How important is this?

Doing your trick with the source file would do the trick otherwise for now, but things would break if we use the package for other purposes. I'll open an issue on their repo.

**Comment by licaon-kter** [comment]
> How important is this?

If it's not FOSS... we can't build the app.

I'll try a testbuild

**Comment by saghul** [comment]
I see. I opened https://github.com/react-native-device-info/react-native-device-info/issues/1149 -- I think the fix is not very complex.

**Comment by licaon-kter** [comment]
I saw that that issue was fixed upstream, ping me when you have a PR for me to test here.

**Comment by saghul** [comment]
Sure thing, I plan to update the PR later tonight!

**Comment by saghul** [comment]
I tested the PR and works fine. It will land on master next week, but I merged it on the 20.6 release branch and  tagged `android-20.6.0-fdroid1` you should be able to build it off that tag. Let me know how it goes!

**Comment by licaon-kter** [comment]
```
2021-01-09 17:57:39,968 DEBUG: buildserver > > Task :react-native-immersive:generateReleaseBuildConfig
2021-01-09 17:57:39,968 DEBUG: buildserver > > Task :react-native-device-info:javaPreCompileRelease
2021-01-09 17:57:39,969 DEBUG: buildserver > 
2021-01-09 17:57:39,969 DEBUG: buildserver > > Task :react-native-device-info:compileReleaseJavaWithJavac FAILED
2021-01-09 17:57:39,969 DEBUG: buildserver > /home/vagrant/build/org.jitsi.meet/node_modules/react-native-device-info/android/src/main/java/com/learnium/RNDeviceInfo/RNDeviceModule.java:47: error: package com.google.android.gms.common does not exist
2021-01-09 17:57:39,969 DEBUG: buildserver > import com.google.android.gms.common.ConnectionResult;
2021-01-09 17:57:39,970 DEBUG: buildserver >                                     ^
2021-01-09 17:57:39,970 DEBUG: buildserver > /home/vagrant/build/org.jitsi.meet/node_modules/react-native-device-info/android/src/main/java/com/learnium/RNDeviceInfo/RNDeviceModule.java:48: error: package com.google.android.gms.common does not exist
2021-01-09 17:57:39,970 DEBUG: buildserver > import com.google.android.gms.common.GoogleApiAvailability;
2021-01-09 17:57:39,971 DEBUG: buildserver >                                     ^
2021-01-09 17:57:39,971 DEBUG: buildserver > /home/vagrant/build/org.jitsi.meet/node_modules/react-native-device-info/android/src/main/java/com/learnium/RNDeviceInfo/RNDeviceModule.java:507: error: cannot find symbol
2021-01-09 17:57:39,971 DEBUG: buildserver >     GoogleApiAvailability gms = GoogleApiAvailability.getInstance();
2021-01-09 17:57:39,971 DEBUG: buildserver >     ^
2021-01-09 17:57:39,972 DEBUG: buildserver >   symbol:   class GoogleApiAvailability
2021-01-09 17:57:39,972 DEBUG: buildserver >   location: class RNDeviceModule
2021-01-09 17:57:39,972 DEBUG: buildserver > /home/vagrant/build/org.jitsi.meet/node_modules/react-native-device-info/android/src/main/java/com/learnium/RNDeviceInfo/RNDeviceModule.java:507: error: cannot find symbol
2021-01-09 17:57:39,973 DEBUG: buildserver >     GoogleApiAvailability gms = GoogleApiAvailability.getInstance();
2021-01-09 17:57:39,973 DEBUG: buildserver >                                 ^
2021-01-09 17:57:39,973 DEBUG: buildserver >   symbol:   variable GoogleApiAvailability
2021-01-09 17:57:39,973 DEBUG: buildserver >   location: class RNDeviceModule
2021-01-09 17:57:39,974 DEBUG: buildserver > /home/vagrant/build/org.jitsi.meet/node_modules/react-native-device-info/android/src/main/java/com/learnium/RNDeviceInfo/RNDeviceModule.java:509: error: cannot find symbol
2021-01-09 17:57:39,974 DEBUG: buildserver >     return isGMS == ConnectionResult.SUCCESS;
2021-01-09 17:57:39,974 DEBUG: buildserver >                     ^
2021-01-09 17:57:39,975 DEBUG: buildserver >   symbol:   variable ConnectionResult
2021-01-09 17:57:39,975 DEBUG: buildserver >   location: class RNDeviceModule
2021-01-09 17:57:39,975 DEBUG: buildserver > /home/vagrant/build/org.jitsi.meet/node_modules/react-native-device-info/android/src/main/java/com/learnium/RNDeviceInfo/RNDeviceModule.java:522: error: cannot find symbol
2021-01-09 17:57:39,975 DEBUG: buildserver >       return isHMS == ConnectionResult.SUCCESS;
2021-01-09 17:57:39,976 DEBUG: buildserver >                       ^
2021-01-09 17:57:39,976 DEBUG: buildserver >   symbol:   variable ConnectionResult
2021-01-09 17:57:39,976 DEBUG: buildserver >   location: class RNDeviceModule
2021-01-09 17:57:39,977 DEBUG: buildserver > Note: /home/vagrant/build/org.jitsi.meet/node_modules/react-native-device-info/android/src/main/java/com/learnium/RNDeviceInfo/RNDeviceModule.java uses or overrides a deprecated API.
2021-01-09 17:57:39,977 DEBUG: buildserver > Note: Recompile with -Xlint:deprecation for details.
2021-01-09 17:57:39,977 DEBUG: buildserver > 6 errors
2021-01-09 17:57:39,977 DEBUG: buildserver > 
2021-01-09 17:57:39,978 DEBUG: buildserver > > Task :react-native-default-preference:bundleLibCompileToJarRelease
2021-01-09 17:57:39,978 DEBUG: buildserver > > Task :react-native-immersive:javaPreCompileRelease
2021-01-09 17:57:39,978 DEBUG: buildserver > > Task :react-native-calendar-events:bundleLibCompileToJarRelease
2021-01-09 17:57:39,978 DEBUG: buildserver > 
2021-01-09 17:57:39,979 DEBUG: buildserver > FAILURE: Build failed with an exception.
2021-01-09 17:57:39,979 DEBUG: buildserver > 
2021-01-09 17:57:39,979 DEBUG: buildserver > * What went wrong:
2021-01-09 17:57:39,980 DEBUG: buildserver > Execution failed for task ':react-native-device-info:compileReleaseJavaWithJavac'.
2021-01-09 17:57:39,980 DEBUG: buildserver > > Compilation failed; see the compiler error output for details.
2021-01-09 17:57:39,980 DEBUG: buildserver > 
```
I've added:
```
      - sed -E -i '/installreferrer/,+11d' ../../node_modules/react-native-device-info/android/build.gradle
```
...to be able to bypass the non-foss scanner

But it looks like either upstream or jitsi-meet needs to remove more stuff

**Comment by saghul** [comment]
Hum I'll test again but we explicitly exclude GMS and that library works well without it (local testing), I'll test the fdroid build process. Can you share the yaml code you're using for this release?

**Comment by saghul** [comment]
Ah I see the problem now, it's a simple fix thankfully.

**Comment by saghul** [comment]
https://github.com/react-native-device-info/react-native-device-info/pull/1156 should fix it, I'll pull the new release once it's merged upstream.

**Comment by saghul** [comment]
I just tagged `android-20.6.0-fdroid2`, with an updated devie-info (8.0.0) which no longer hard-depends on gms. Hopefully this is it!

**Comment by licaon-kter** [comment]
FYI https://gitlab.com/fdroid/fdroiddata/-/merge_requests/8115
