### ISSUE TITLE
The application is crashing as soon as I launch the jetsiactivity on my emulator

### ISSUE THREAD

**Issue by saifkhan7865** [jitsi/jitsi-meet#8362]
### Description:
As soon as I launch my application and start the meeting the application is just crashing

this is the error that I've noted
```
1-01-07 22:46:25.181 32119-32187/com.metafisa.vivideo E/AndroidRuntime: FATAL EXCEPTION: create_react_context
    Process: com.metafisa.vivideo, PID: 32119
    java.lang.BootstrapMethodError: Exception from call site #3 bootstrap method
        at com.oney.WebRTCModule.WebRTCModule.<init>(WebRTCModule.java:70)
        at org.jitsi.meet.sdk.ReactInstanceManagerHolder.createNativeModules(ReactInstanceManagerHolder.java:92)
        at org.jitsi.meet.sdk.ReactInstanceManagerHolder.access$000(ReactInstanceManagerHolder.java:48)
        at org.jitsi.meet.sdk.ReactInstanceManagerHolder$1.createNativeModules(ReactInstanceManagerHolder.java:204)
        at com.facebook.react.ReactPackageHelper.getNativeModuleIterator(ReactPackageHelper.java:41)
        at com.facebook.react.NativeModuleRegistryBuilder.processPackage(NativeModuleRegistryBuilder.java:41)
        at com.facebook.react.ReactInstanceManager.processPackage(ReactInstanceManager.java:1230)
        at com.facebook.react.ReactInstanceManager.processPackages(ReactInstanceManager.java:1201)
        at com.facebook.react.ReactInstanceManager.createReactContext(ReactInstanceManager.java:1134)
        at com.facebook.react.ReactInstanceManager.access$1000(ReactInstanceManager.java:125)
        at com.facebook.react.ReactInstanceManager$5.run(ReactInstanceManager.java:951)
        at java.lang.Thread.run(Thread.java:764)
     Caused by: java.lang.ClassCastException: Bootstrap method returned null
        at com.oney.WebRTCModule.WebRTCModule.<init>(WebRTCModule.java:70) 
        at org.jitsi.meet.sdk.ReactInstanceManagerHolder.createNativeModules(ReactInstanceManagerHolder.java:92) 
        at org.jitsi.meet.sdk.ReactInstanceManagerHolder.access$000(ReactInstanceManagerHolder.java:48) 
        at org.jitsi.meet.sdk.ReactInstanceManagerHolder$1.createNativeModules(ReactInstanceManagerHolder.java:204) 
        at com.facebook.react.ReactPackageHelper.getNativeModuleIterator(ReactPackageHelper.java:41) 
        at com.facebook.react.NativeModuleRegistryBuilder.processPackage(NativeModuleRegistryBuilder.java:41) 
        at com.facebook.react.ReactInstanceManager.processPackage(ReactInstanceManager.java:1230) 
        at com.facebook.react.ReactInstanceManager.processPackages(ReactInstanceManager.java:1201) 
        at com.facebook.react.ReactInstanceManager.createReactContext(ReactInstanceManager.java:1134) 
        at com.facebook.react.ReactInstanceManager.access$1000(ReactInstanceManager.java:125) 
        at com.facebook.react.ReactInstanceManager$5.run(ReactInstanceManager.java:951) 
        at java.lang.Thread.run(Thread.java:764) 
2021-01-07 22:46:25.193 32119-32187/com.metafisa.vivideo E/JitsiMeetSDK: JitsiMeetUncaughtExceptionHandler FATAL ERROR
    java.lang.BootstrapMethodError: Exception from call site #3 bootstrap method
        at com.oney.WebRTCModule.WebRTCModule.<init>(WebRTCModule.java:70)
        at org.jitsi.meet.sdk.ReactInstanceManagerHolder.createNativeModules(ReactInstanceManagerHolder.java:92)
        at org.jitsi.meet.sdk.ReactInstanceManagerHolder.access$000(ReactInstanceManagerHolder.java:48)
        at org.jitsi.meet.sdk.ReactInstanceManagerHolder$1.createNativeModules(ReactInstanceManagerHolder.java:204)
        at com.facebook.react.ReactPackageHelper.getNativeModuleIterator(ReactPackageHelper.java:41)
        at com.facebook.react.NativeModuleRegistryBuilder.processPackage(NativeModuleRegistryBuilder.java:41)
        at com.facebook.react.ReactInstanceManager.processPackage(ReactInstanceManager.java:1230)
        at com.facebook.react.ReactInstanceManager.processPackages(ReactInstanceManager.java:1201)
        at com.facebook.react.ReactInstanceManager.createReactContext(ReactInstanceManager.java:1134)
        at com.facebook.react.ReactInstanceManager.access$1000(ReactInstanceManager.java:125)
        at com.facebook.react.ReactInstanceManager$5.run(ReactInstanceManager.java:951)
        at java.lang.Thread.run(Thread.java:764)
     Caused by: java.lang.ClassCastException: Bootstrap method returned null
        at com.oney.WebRTCModule.WebRTCModule.<init>(WebRTCModule.java:70) 
        at org.jitsi.meet.sdk.ReactInstanceManagerHolder.createNativeModules(ReactInstanceManagerHolder.java:92) 
        at org.jitsi.meet.sdk.ReactInstanceManagerHolder.access$000(ReactInstanceManagerHolder.java:48) 
        at org.jitsi.meet.sdk.ReactInstanceManagerHolder$1.createNativeModules(ReactInstanceManagerHolder.java:204) 
        at com.facebook.react.ReactPackageHelper.getNativeModuleIterator(ReactPackageHelper.java:41) 
        at com.facebook.react.NativeModuleRegistryBuilder.processPackage(NativeModuleRegistryBuilder.java:41) 
        at com.facebook.react.ReactInstanceManager.processPackage(ReactInstanceManager.java:1230) 
        at com.facebook.react.ReactInstanceManager.processPackages(ReactInstanceManager.java:1201) 
        at com.facebook.react.ReactInstanceManager.createReactContext(ReactInstanceManager.java:1134) 
        at com.facebook.react.ReactInstanceManager.access$1000(ReactInstanceManager.java:125) 
        at com.facebook.react.ReactInstanceManager$5.run(ReactInstanceManager.java:951) 
        at java.lang.Thread.run(Thread.java:764) 
    
    java.lang.BootstrapMethodError: Exception from call site #3 bootstrap method
        at com.oney.WebRTCModule.WebRTCModule.<init>(WebRTCModule.java:70)
        at org.jitsi.meet.sdk.ReactInstanceManagerHolder.createNativeModules(ReactInstanceManagerHolder.java:92)
        at org.jitsi.meet.sdk.ReactInstanceManagerHolder.access$000(ReactInstanceManagerHolder.java:48)
        at org.jitsi.meet.sdk.ReactInstanceManagerHolder$1.createNativeModules(ReactInstanceManagerHolder.java:204)
        at com.facebook.react.ReactPackageHelper.getNativeModuleIterator(ReactPackageHelper.java:41)
        at com.facebook.react.NativeModuleRegistryBuilder.processPackage(NativeModuleRegistryBuilder.java:41)
        at com.facebook.react.ReactInstanceManager.processPackage(ReactInstanceManager.java:1230)
        at com.facebook.react.ReactInstanceManager.processPackages(ReactInstanceManager.java:1201)
        at com.facebook.react.ReactInstanceManager.createReactContext(ReactInstanceManager.java:1134)
        at com.facebook.react.ReactInstanceManager.access$1000(ReactInstanceManager.java:125)
        at com.facebook.react.ReactInstanceManager$5.run(ReactInstanceManager.java:951)
        at java.lang.Thread.run(Thread.java:764)
     Caused by: java.lang.ClassCastException: Bootstrap method returned null
        at com.oney.WebRTCModule.WebRTCModule.<init>(WebRTCModule.java:70) 
        at org.jitsi.meet.sdk.ReactInstanceManagerHolder.createNativeModules(ReactInstanceManagerHolder.java:92) 
        at org.jitsi.meet.sdk.ReactInstanceManagerHolder.access$000(ReactInstanceManagerHolder.java:48) 
        at org.jitsi.meet.sdk.ReactInstanceManagerHolder$1.createNativeModules(ReactInstanceManagerHolder.java:204) 
        at com.facebook.react.ReactPackageHelper.getNativeModuleIterator(ReactPackageHelper.java:41) 
        at com.facebook.react.NativeModuleRegistryBuilder.processPackage(NativeModuleRegistryBuilder.java:41) 
        at com.facebook.react.ReactInstanceManager.processPackage(ReactInstanceManager.java:1230) 
        at com.facebook.react.ReactInstanceManager.processPackages(ReactInstanceManager.java:1201) 
        at com.facebook.react.ReactInstanceManager.createReactContext(ReactInstanceManager.java:1134) 
        at com.facebook.react.ReactInstanceManager.access$1000(ReactInstanceManager.java:125) 
        at com.facebook.react.ReactInstanceManager$5.run(ReactInstanceManager.java:951) 
        at java.lang.Thread.run(Thread.java:764) 
```
please help and this is the code that is causing the error

```
JitsiMeetConferenceOptions options = new JitsiMeetConferenceOptions.Builder()
                        .setRoom(secretCodeBox.getText().toString())
                        .setWelcomePageEnabled(false)
                        .build();

                JitsiMeetActivity.launch(DashboardActivity.this, options);

```

### Steps to reproduce:

1. 
2. 
3. 

### Server information:

- Jitsi Meet version:
- Operating System:

### Client information:

- Browser / app version:
- Operating System:

**Comment by saifkhan7865** [comment]
As soon as I launch my application and start the meeting the application is just crashing

```
this is the error that I've noted
1-01-07 22:46:25.181 32119-32187/com.metafisa.vivideo E/AndroidRuntime: FATAL EXCEPTION: create_react_context
    Process: com.metafisa.vivideo, PID: 32119
    java.lang.BootstrapMethodError: Exception from call site #3 bootstrap method
        at com.oney.WebRTCModule.WebRTCModule.<init>(WebRTCModule.java:70)
        at org.jitsi.meet.sdk.ReactInstanceManagerHolder.createNativeModules(ReactInstanceManagerHolder.java:92)
        at org.jitsi.meet.sdk.ReactInstanceManagerHolder.access$000(ReactInstanceManagerHolder.java:48)
        at org.jitsi.meet.sdk.ReactInstanceManagerHolder$1.createNativeModules(ReactInstanceManagerHolder.java:204)
        at com.facebook.react.ReactPackageHelper.getNativeModuleIterator(ReactPackageHelper.java:41)
        at com.facebook.react.NativeModuleRegistryBuilder.processPackage(NativeModuleRegistryBuilder.java:41)
        at com.facebook.react.ReactInstanceManager.processPackage(ReactInstanceManager.java:1230)
        at com.facebook.react.ReactInstanceManager.processPackages(ReactInstanceManager.java:1201)
        at com.facebook.react.ReactInstanceManager.createReactContext(ReactInstanceManager.java:1134)
        at com.facebook.react.ReactInstanceManager.access$1000(ReactInstanceManager.java:125)
        at com.facebook.react.ReactInstanceManager$5.run(ReactInstanceManager.java:951)
        at java.lang.Thread.run(Thread.java:764)
     Caused by: java.lang.ClassCastException: Bootstrap method returned null
        at com.oney.WebRTCModule.WebRTCModule.<init>(WebRTCModule.java:70) 
        at org.jitsi.meet.sdk.ReactInstanceManagerHolder.createNativeModules(ReactInstanceManagerHolder.java:92) 
        at org.jitsi.meet.sdk.ReactInstanceManagerHolder.access$000(ReactInstanceManagerHolder.java:48) 
        at org.jitsi.meet.sdk.ReactInstanceManagerHolder$1.createNativeModules(ReactInstanceManagerHolder.java:204) 
        at com.facebook.react.ReactPackageHelper.getNativeModuleIterator(ReactPackageHelper.java:41) 
        at com.facebook.react.NativeModuleRegistryBuilder.processPackage(NativeModuleRegistryBuilder.java:41) 
        at com.facebook.react.ReactInstanceManager.processPackage(ReactInstanceManager.java:1230) 
        at com.facebook.react.ReactInstanceManager.processPackages(ReactInstanceManager.java:1201) 
        at com.facebook.react.ReactInstanceManager.createReactContext(ReactInstanceManager.java:1134) 
        at com.facebook.react.ReactInstanceManager.access$1000(ReactInstanceManager.java:125) 
        at com.facebook.react.ReactInstanceManager$5.run(ReactInstanceManager.java:951) 
        at java.lang.Thread.run(Thread.java:764) 
2021-01-07 22:46:25.193 32119-32187/com.metafisa.vivideo E/JitsiMeetSDK: JitsiMeetUncaughtExceptionHandler FATAL ERROR
    java.lang.BootstrapMethodError: Exception from call site #3 bootstrap method
        at com.oney.WebRTCModule.WebRTCModule.<init>(WebRTCModule.java:70)
        at org.jitsi.meet.sdk.ReactInstanceManagerHolder.createNativeModules(ReactInstanceManagerHolder.java:92)
        at org.jitsi.meet.sdk.ReactInstanceManagerHolder.access$000(ReactInstanceManagerHolder.java:48)
        at org.jitsi.meet.sdk.ReactInstanceManagerHolder$1.createNativeModules(ReactInstanceManagerHolder.java:204)
        at com.facebook.react.ReactPackageHelper.getNativeModuleIterator(ReactPackageHelper.java:41)
        at com.facebook.react.NativeModuleRegistryBuilder.processPackage(NativeModuleRegistryBuilder.java:41)
        at com.facebook.react.ReactInstanceManager.processPackage(ReactInstanceManager.java:1230)
        at com.facebook.react.ReactInstanceManager.processPackages(ReactInstanceManager.java:1201)
        at com.facebook.react.ReactInstanceManager.createReactContext(ReactInstanceManager.java:1134)
        at com.facebook.react.ReactInstanceManager.access$1000(ReactInstanceManager.java:125)
        at com.facebook.react.ReactInstanceManager$5.run(ReactInstanceManager.java:951)
        at java.lang.Thread.run(Thread.java:764)
     Caused by: java.lang.ClassCastException: Bootstrap method returned null
        at com.oney.WebRTCModule.WebRTCModule.<init>(WebRTCModule.java:70) 
        at org.jitsi.meet.sdk.ReactInstanceManagerHolder.createNativeModules(ReactInstanceManagerHolder.java:92) 
        at org.jitsi.meet.sdk.ReactInstanceManagerHolder.access$000(ReactInstanceManagerHolder.java:48) 
        at org.jitsi.meet.sdk.ReactInstanceManagerHolder$1.createNativeModules(ReactInstanceManagerHolder.java:204) 
        at com.facebook.react.ReactPackageHelper.getNativeModuleIterator(ReactPackageHelper.java:41) 
        at com.facebook.react.NativeModuleRegistryBuilder.processPackage(NativeModuleRegistryBuilder.java:41) 
        at com.facebook.react.ReactInstanceManager.processPackage(ReactInstanceManager.java:1230) 
        at com.facebook.react.ReactInstanceManager.processPackages(ReactInstanceManager.java:1201) 
        at com.facebook.react.ReactInstanceManager.createReactContext(ReactInstanceManager.java:1134) 
        at com.facebook.react.ReactInstanceManager.access$1000(ReactInstanceManager.java:125) 
        at com.facebook.react.ReactInstanceManager$5.run(ReactInstanceManager.java:951) 
        at java.lang.Thread.run(Thread.java:764) 
    
    java.lang.BootstrapMethodError: Exception from call site #3 bootstrap method
        at com.oney.WebRTCModule.WebRTCModule.<init>(WebRTCModule.java:70)
        at org.jitsi.meet.sdk.ReactInstanceManagerHolder.createNativeModules(ReactInstanceManagerHolder.java:92)
        at org.jitsi.meet.sdk.ReactInstanceManagerHolder.access$000(ReactInstanceManagerHolder.java:48)
        at org.jitsi.meet.sdk.ReactInstanceManagerHolder$1.createNativeModules(ReactInstanceManagerHolder.java:204)
        at com.facebook.react.ReactPackageHelper.getNativeModuleIterator(ReactPackageHelper.java:41)
        at com.facebook.react.NativeModuleRegistryBuilder.processPackage(NativeModuleRegistryBuilder.java:41)
        at com.facebook.react.ReactInstanceManager.processPackage(ReactInstanceManager.java:1230)
        at com.facebook.react.ReactInstanceManager.processPackages(ReactInstanceManager.java:1201)
        at com.facebook.react.ReactInstanceManager.createReactContext(ReactInstanceManager.java:1134)
        at com.facebook.react.ReactInstanceManager.access$1000(ReactInstanceManager.java:125)
        at com.facebook.react.ReactInstanceManager$5.run(ReactInstanceManager.java:951)
        at java.lang.Thread.run(Thread.java:764)
     Caused by: java.lang.ClassCastException: Bootstrap method returned null
        at com.oney.WebRTCModule.WebRTCModule.<init>(WebRTCModule.java:70) 
        at org.jitsi.meet.sdk.ReactInstanceManagerHolder.createNativeModules(ReactInstanceManagerHolder.java:92) 
        at org.jitsi.meet.sdk.ReactInstanceManagerHolder.access$000(ReactInstanceManagerHolder.java:48) 
        at org.jitsi.meet.sdk.ReactInstanceManagerHolder$1.createNativeModules(ReactInstanceManagerHolder.java:204) 
        at com.facebook.react.ReactPackageHelper.getNativeModuleIterator(ReactPackageHelper.java:41) 
        at com.facebook.react.NativeModuleRegistryBuilder.processPackage(NativeModuleRegistryBuilder.java:41) 
        at com.facebook.react.ReactInstanceManager.processPackage(ReactInstanceManager.java:1230) 
        at com.facebook.react.ReactInstanceManager.processPackages(ReactInstanceManager.java:1201) 
        at com.facebook.react.ReactInstanceManager.createReactContext(ReactInstanceManager.java:1134) 
        at com.facebook.react.ReactInstanceManager.access$1000(ReactInstanceManager.java:125) 
        at com.facebook.react.ReactInstanceManager$5.run(ReactInstanceManager.java:951) 
        at java.lang.Thread.run(Thread.java:764) 
```

please help and this is the code that is causing the error

```
JitsiMeetConferenceOptions options = new JitsiMeetConferenceOptions.Builder()
                        .setRoom(secretCodeBox.getText().toString())
                        .setWelcomePageEnabled(false)
                        .build();

                JitsiMeetActivity.launch(DashboardActivity.this, options);
```

**Comment by saghul** [comment]
Are you using proguard? Did you add the rules mentioned in the documentation?

**Comment by saifkhan7865** [comment]
Hello Yes I've just added the rules in the pro guard rules

```
# Add project specific ProGuard rules here.
# You can control the set of applied configuration files using the
# proguardFiles setting in build.gradle.
#
# For more details, see
#   http://developer.android.com/guide/developing/tools/proguard.html

# If your project uses WebView with JS, uncomment the following
# and specify the fully qualified class name to the JavaScript interface
# class:
#-keepclassmembers class fqcn.of.javascript.interface.for.webview {
#   public *;
#}

# Uncomment this to preserve the line number information for
# debugging stack traces.
#-keepattributes SourceFile,LineNumberTable

# If you keep the line number information, uncomment this to
# hide the original source file name.
#-renamesourcefileattribute SourceFile
-keep,allowobfuscation @interface com.facebook.proguard.annotations.DoNotStrip
-keep,allowobfuscation @interface com.facebook.proguard.annotations.KeepGettersAndSetters
-keep,allowobfuscation @interface com.facebook.common.internal.DoNotStrip

# Do not strip any method/class that is annotated with @DoNotStrip
-keep @com.facebook.proguard.annotations.DoNotStrip class *
-keep @com.facebook.common.internal.DoNotStrip class *
-keepclassmembers class * {
    @com.facebook.proguard.annotations.DoNotStrip *;
    @com.facebook.common.internal.DoNotStrip *;
}

-keepclassmembers @com.facebook.proguard.annotations.KeepGettersAndSetters class * {
  void set*(***);
  *** get*();
}

-keep class * extends com.facebook.react.bridge.JavaScriptModule { *; }
-keep class * extends com.facebook.react.bridge.NativeModule { *; }
-keepclassmembers,includedescriptorclasses class * { native <methods>; }
-keepclassmembers class *  { @com.facebook.react.uimanager.UIProp <fields>; }
-keepclassmembers class *  { @com.facebook.react.uimanager.annotations.ReactProp <methods>; }
-keepclassmembers class *  { @com.facebook.react.uimanager.annotations.ReactPropGroup <methods>; }

-dontwarn com.facebook.react.**
-keep,includedescriptorclasses class com.facebook.react.bridge.** { *; }

# okhttp

-keepattributes Signature
-keepattributes *Annotation*
-keep class okhttp3.** { *; }
-keep interface okhttp3.** { *; }
-dontwarn okhttp3.**

# okio

-keep class sun.misc.Unsafe { *; }
-dontwarn java.nio.file.*
-dontwarn org.codehaus.mojo.animal_sniffer.IgnoreJRERequirement
-keep class okio.** { *; }
-dontwarn okio.**

# WebRTC

-keep class org.webrtc.** { *; }
-dontwarn org.chromium.build.BuildHooksAndroid

# Jisti Meet SDK

-keep class org.jitsi.meet.** { *; }
-keep class org.jitsi.meet.sdk.** { *; }

# We added the following when we switched minifyEnabled on. Probably because we
# ran the app and hit problems...

-keep class com.facebook.react.bridge.CatalystInstanceImpl { *; }
-keep class com.facebook.react.bridge.ExecutorToken { *; }
-keep class com.facebook.react.bridge.JavaScriptExecutor { *; }
-keep class com.facebook.react.bridge.ModuleRegistryHolder { *; }
-keep class com.facebook.react.bridge.ReadableType { *; }
-keep class com.facebook.react.bridge.queue.NativeRunnable { *; }
-keep class com.facebook.react.devsupport.** { *; }

-dontwarn com.facebook.react.devsupport.**
-dontwarn com.google.appengine.**
-dontwarn com.squareup.okhttp.**
-dontwarn javax.servlet.**

# ^^^ We added the above when we switched minifyEnabled on.

# Rule to avoid build errors related to SVGs.
-keep public class com.horcrux.svg.** {*;}
```
These are the proguard rules that I've added but Still in the proguard rules file
I see that the IDE is throwing errors
![image](https://user-images.githubusercontent.com/60229505/104087563-a4dd6480-5286-11eb-8572-f1e0717c63fb.png)
Just like in the above image in the 59th line and 62 line and on many more places


but still it isn't working

**Comment by saifkhan7865** [comment]
This is the error that I'm **STILL** getting

```
FATAL EXCEPTION: create_react_context
    Process: com.metafisa.vivideo, PID: 591
    java.lang.BootstrapMethodError: Exception from call site #3 bootstrap method
        at com.oney.WebRTCModule.WebRTCModule.<init>(WebRTCModule.java:70)
        at org.jitsi.meet.sdk.ReactInstanceManagerHolder.createNativeModules(ReactInstanceManagerHolder.java:92)
        at org.jitsi.meet.sdk.ReactInstanceManagerHolder.access$000(ReactInstanceManagerHolder.java:48)
        at org.jitsi.meet.sdk.ReactInstanceManagerHolder$1.createNativeModules(ReactInstanceManagerHolder.java:204)
        at com.facebook.react.ReactPackageHelper.getNativeModuleIterator(ReactPackageHelper.java:41)
        at com.facebook.react.NativeModuleRegistryBuilder.processPackage(NativeModuleRegistryBuilder.java:41)
        at com.facebook.react.ReactInstanceManager.processPackage(ReactInstanceManager.java:1230)
        at com.facebook.react.ReactInstanceManager.processPackages(ReactInstanceManager.java:1201)
        at com.facebook.react.ReactInstanceManager.createReactContext(ReactInstanceManager.java:1134)
        at com.facebook.react.ReactInstanceManager.access$1000(ReactInstanceManager.java:125)
        at com.facebook.react.ReactInstanceManager$5.run(ReactInstanceManager.java:951)
        at java.lang.Thread.run(Thread.java:764)
     Caused by: java.lang.ClassCastException: Bootstrap method returned null
        at com.oney.WebRTCModule.WebRTCModule.<init>(WebRTCModule.java:70) 
        at org.jitsi.meet.sdk.ReactInstanceManagerHolder.createNativeModules(ReactInstanceManagerHolder.java:92) 
        at org.jitsi.meet.sdk.ReactInstanceManagerHolder.access$000(ReactInstanceManagerHolder.java:48) 
        at org.jitsi.meet.sdk.ReactInstanceManagerHolder$1.createNativeModules(ReactInstanceManagerHolder.java:204) 
        at com.facebook.react.ReactPackageHelper.getNativeModuleIterator(ReactPackageHelper.java:41) 
        at com.facebook.react.NativeModuleRegistryBuilder.processPackage(NativeModuleRegistryBuilder.java:41) 
        at com.facebook.react.ReactInstanceManager.processPackage(ReactInstanceManager.java:1230) 
        at com.facebook.react.ReactInstanceManager.processPackages(ReactInstanceManager.java:1201) 
        at com.facebook.react.ReactInstanceManager.createReactContext(ReactInstanceManager.java:1134) 
        at com.facebook.react.ReactInstanceManager.access$1000(ReactInstanceManager.java:125) 
        at com.facebook.react.ReactInstanceManager$5.run(ReactInstanceManager.java:951) 
        at java.lang.Thread.run(Thread.java:764) 
2021-01-09 14:27:55.348 591-679/com.metafisa.vivideo E/JitsiMeetSDK: JitsiMeetUncaughtExceptionHandler FATAL ERROR
    java.lang.BootstrapMethodError: Exception from call site #3 bootstrap method
        at com.oney.WebRTCModule.WebRTCModule.<init>(WebRTCModule.java:70)
        at org.jitsi.meet.sdk.ReactInstanceManagerHolder.createNativeModules(ReactInstanceManagerHolder.java:92)
        at org.jitsi.meet.sdk.ReactInstanceManagerHolder.access$000(ReactInstanceManagerHolder.java:48)
        at org.jitsi.meet.sdk.ReactInstanceManagerHolder$1.createNativeModules(ReactInstanceManagerHolder.java:204)
        at com.facebook.react.ReactPackageHelper.getNativeModuleIterator(ReactPackageHelper.java:41)
        at com.facebook.react.NativeModuleRegistryBuilder.processPackage(NativeModuleRegistryBuilder.java:41)
        at com.facebook.react.ReactInstanceManager.processPackage(ReactInstanceManager.java:1230)
        at com.facebook.react.ReactInstanceManager.processPackages(ReactInstanceManager.java:1201)
        at com.facebook.react.ReactInstanceManager.createReactContext(ReactInstanceManager.java:1134)
        at com.facebook.react.ReactInstanceManager.access$1000(ReactInstanceManager.java:125)
        at com.facebook.react.ReactInstanceManager$5.run(ReactInstanceManager.java:951)
        at java.lang.Thread.run(Thread.java:764)
     Caused by: java.lang.ClassCastException: Bootstrap method returned null
        at com.oney.WebRTCModule.WebRTCModule.<init>(WebRTCModule.java:70) 
        at org.jitsi.meet.sdk.ReactInstanceManagerHolder.createNativeModules(ReactInstanceManagerHolder.java:92) 
        at org.jitsi.meet.sdk.ReactInstanceManagerHolder.access$000(ReactInstanceManagerHolder.java:48) 
        at org.jitsi.meet.sdk.ReactInstanceManagerHolder$1.createNativeModules(ReactInstanceManagerHolder.java:204) 
        at com.facebook.react.ReactPackageHelper.getNativeModuleIterator(ReactPackageHelper.java:41) 
        at com.facebook.react.NativeModuleRegistryBuilder.processPackage(NativeModuleRegistryBuilder.java:41) 
        at com.facebook.react.ReactInstanceManager.processPackage(ReactInstanceManager.java:1230) 
        at com.facebook.react.ReactInstanceManager.processPackages(ReactInstanceManager.java:1201) 
        at com.facebook.react.ReactInstanceManager.createReactContext(ReactInstanceManager.java:1134) 
        at com.facebook.react.ReactInstanceManager.access$1000(ReactInstanceManager.java:125) 
        at com.facebook.react.ReactInstanceManager$5.run(ReactInstanceManager.java:951) 
        at java.lang.Thread.run(Thread.java:764) 
    
    java.lang.BootstrapMethodError: Exception from call site #3 bootstrap method
        at com.oney.WebRTCModule.WebRTCModule.<init>(WebRTCModule.java:70)
        at org.jitsi.meet.sdk.ReactInstanceManagerHolder.createNativeModules(ReactInstanceManagerHolder.java:92)
        at org.jitsi.meet.sdk.ReactInstanceManagerHolder.access$000(ReactInstanceManagerHolder.java:48)
        at org.jitsi.meet.sdk.ReactInstanceManagerHolder$1.createNativeModules(ReactInstanceManagerHolder.java:204)
        at com.facebook.react.ReactPackageHelper.getNativeModuleIterator(ReactPackageHelper.java:41)
        at com.facebook.react.NativeModuleRegistryBuilder.processPackage(NativeModuleRegistryBuilder.java:41)
        at com.facebook.react.ReactInstanceManager.processPackage(ReactInstanceManager.java:1230)
        at com.facebook.react.ReactInstanceManager.processPackages(ReactInstanceManager.java:1201)
        at com.facebook.react.ReactInstanceManager.createReactContext(ReactInstanceManager.java:1134)
        at com.facebook.react.ReactInstanceManager.access$1000(ReactInstanceManager.java:125)
        at com.facebook.react.ReactInstanceManager$5.run(ReactInstanceManager.java:951)
        at java.lang.Thread.run(Thread.java:764)
```
