### ISSUE TITLE
[ Android ] [ Emulator ] Phenotype API error. Event # byvc@ff13bebd, EventCode: 12 [CONTEXT service_id=51 ]

### ISSUE THREAD

**Issue by gouravrc** [jitsi/jitsi-meet#8398]
**System env**
System:
    OS: macOS Mojave 10.14.6
    CPU: (4) x64 Intel(R) Core(TM) i5-8210Y CPU @ 1.60GHz
    Memory: 75.00 MB / 8.00 GB
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 15.1.0 - /usr/local/bin/node
    Yarn: 1.22.10 - /usr/local/bin/yarn
    npm: 7.0.8 - /usr/local/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  SDKs:
    iOS SDK:
      Platforms: iOS 13.0, DriverKit 19.0, macOS 10.15, tvOS 13.0, watchOS 6.0
  IDEs:
    Android Studio: 3.5 AI-191.8026.42.35.5900203
    Xcode: 11.0/11A420a - /usr/bin/xcodebuild
  npmPackages:
    react: 16.9 => 16.9.0 
    react-native: github:jitsi/react-native#891986ec5ecaef65d1c8a7fe472f86cf84fe7551 => 0.61.5-jitsi.2 
  npmGlobalPackages:
    react-native-cli: 2.0.1

**Steps to reproduce**
1. ```npm start```
2. Run the application in the emulator.
3. Input any room name.
4. Press ```create/join``` button.

**Issue**

Suddenly the application is failing to connect to any rooms/url. I have tracked the issue in logcat. Below is what I am getting.

**EDIT 1**
I have downloaded a fresh source from GitHub. I am facing the same issue. Can you please check some recent PRs? It was working 2/3 days back.

**PS**
The issue is happening only in debug/dev mode. In Prod mode, it is working as expected.

> 2021-01-13 15:09:06.806 2675-3174/com.google.android.gms.persistent E/amvj: Phenotype API error. Event # byvc@ff13bebd, EventCode: 12 [CONTEXT service_id=51 ]
    amum: 29503
        at amvp.b(:com.google.android.gms@200414022@20.04.14 (040700-294335909):27)
        at amvj.a(:com.google.android.gms@200414022@20.04.14 (040700-294335909):91)
        at amvj.a(:com.google.android.gms@200414022@20.04.14 (040700-294335909):77)
        at aabf.run(:com.google.android.gms@200414022@20.04.14 (040700-294335909):7)
        at bkdt.run(:com.google.android.gms@200414022@20.04.14 (040700-294335909):2)
        at srw.b(:com.google.android.gms@200414022@20.04.14 (040700-294335909):14)
        at srw.run(:com.google.android.gms@200414022@20.04.14 (040700-294335909):2)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at sxw.run(:com.google.android.gms@200414022@20.04.14 (040700-294335909):0)
        at java.lang.Thread.run(Thread.java:919)
2021-01-13 15:09:06.829 2675-3174/com.google.android.gms.persistent E/AsyncOperation: serviceID=51, operation=GetCommittedConfigurationOperationCall
    OperationException[Status{statusCode=unknown status code: 29503, resolution=null}]
        at amvj.a(:com.google.android.gms@200414022@20.04.14 (040700-294335909):92)
        at amvj.a(:com.google.android.gms@200414022@20.04.14 (040700-294335909):77)
        at aabf.run(:com.google.android.gms@200414022@20.04.14 (040700-294335909):7)
        at bkdt.run(:com.google.android.gms@200414022@20.04.14 (040700-294335909):2)
        at srw.b(:com.google.android.gms@200414022@20.04.14 (040700-294335909):14)
        at srw.run(:com.google.android.gms@200414022@20.04.14 (040700-294335909):2)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at sxw.run(:com.google.android.gms@200414022@20.04.14 (040700-294335909):0)
        at java.lang.Thread.run(Thread.java:919)
2021-01-13 15:09:06.831 2675-3859/com.google.android.gms.persistent E/NetRec: [164] ajzf.a: Could not retrieve server token for package com.google.android.apps.gcs
    java.util.concurrent.ExecutionException: rmz: 29503: 
        at atjq.b(:com.google.android.gms@200414022@20.04.14 (040700-294335909):5)
        at atjq.a(:com.google.android.gms@200414022@20.04.14 (040700-294335909):23)
        at ajzf.a(:com.google.android.gms@200414022@20.04.14 (040700-294335909):1)
        at ajzf.a(:com.google.android.gms@200414022@20.04.14 (040700-294335909):4)
        at ajze.getHeaders(:com.google.android.gms@200414022@20.04.14 (040700-294335909):2)
        at com.android.volley.toolbox.HttpClientStack.performRequest(:com.google.android.gms@200414022@20.04.14 (040700-294335909):20)
        at sle.performRequest(:com.google.android.gms@200414022@20.04.14 (040700-294335909):1)
        at bme.executeRequest(:com.google.android.gms@200414022@20.04.14 (040700-294335909):1)
        at com.android.volley.toolbox.BasicNetwork.performRequest(:com.google.android.gms@200414022@20.04.14 (040700-294335909):10)
        at slf.performRequest(:com.google.android.gms@200414022@20.04.14 (040700-294335909):17)
        at com.android.volley.NetworkDispatcher.a(:com.google.android.gms@200414022@20.04.14 (040700-294335909):6)
        at com.android.volley.NetworkDispatcher.run(:com.google.android.gms@200414022@20.04.14 (040700-294335909):2)
     Caused by: rmz: 29503: 
        at rsm.a(:com.google.android.gms@200414022@20.04.14 (040700-294335909):4)
        at amux.b(:com.google.android.gms@200414022@20.04.14 (040700-294335909):3)
        at amvp.a(:com.google.android.gms@200414022@20.04.14 (040700-294335909):7)
        at aabf.run(:com.google.android.gms@200414022@20.04.14 (040700-294335909):15)
        at bkdt.run(:com.google.android.gms@200414022@20.04.14 (040700-294335909):2)
        at srw.b(:com.google.android.gms@200414022@20.04.14 (040700-294335909):14)
        at srw.run(:com.google.android.gms@200414022@20.04.14 (040700-294335909):2)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at sxw.run(:com.google.android.gms@200414022@20.04.14 (040700-294335909):0)
        at java.lang.Thread.run(Thread.java:919)
2021-01-13 15:09:06.831 2675-3859/com.google.android.gms.persistent W/NetRec: [164] ajzf.a: No server tokens extracted.
2021-01-13 15:09:07.651 10454-11199/org.jitsi.meet E/JitsiMeetSDK: [features/base/lib-jitsi-meet] Failed to load config from https://meet.jit.si/config.js Error(AbortError){"message":"Aborted"}
2021-01-13 15:09:07.655 10454-11199/org.jitsi.meet W/JitsiMeetSDK: [features/app] Failed to load config but there is no room, applying a fake one

![Screenshot_1610531117](https://user-images.githubusercontent.com/41228535/104435270-319f5f80-55b2-11eb-897b-bfc5d215b3f3.png)

**Comment by saghul** [comment]
Nothing in logcat suggests is a Jitsi related problem. The fact that config cannot be loaded in a timely manner (there is a 10 second timeout) suggests a network problem.

**Comment by gouravrc** [comment]
@saghul  Is there any way to increase the timeout?

**Comment by saghul** [comment]
No. If loading a simple JS file takes more than 10 seconds, forget about being able to have a video conference.
