### ISSUE TITLE
react-native-firebase-messaging in jitsi-meet crash when app in background

### ISSUE THREAD

**Issue by bhavesh18** [jitsi/jitsi-meet#8431]
npm package:
"@react-native-firebase/app": "^10.4.0",
"@react-native-firebase/messaging": "^10.4.1",
Reference: https://rnfirebase.io/messaging/usage

Scenario: I added firebase messaging in jitsi-meet and it's working fine on the foreground. When app goes to background it crashes with below error: 

Unable to start service io.invertase.firebase.messaging.ReactNativeFirebaseMessagingHeadlessService@c592dc0 with Intent { cmp=org.jitsinotification.meet/io.invertase.firebase.messaging.ReactNativeFirebaseMessagingHeadlessService (has extras) }: java.lang.ClassCastException: android.app.Application cannot be cast to com.facebook.react.ReactApplication
        at android.app.ActivityThread.handleServiceArgs(ActivityThread.java:3722)
        at android.app.ActivityThread.access$1700(ActivityThread.java:200)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1704)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:201)
        at android.app.ActivityThread.main(ActivityThread.java:6810)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:547)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:873)
     Caused by: java.lang.ClassCastException: android.app.Application cannot be cast to com.facebook.react.ReactApplication
        at com.facebook.react.HeadlessJsTaskService.getReactNativeHost(HeadlessJsTaskService.java:166)
        at com.facebook.react.HeadlessJsTaskService.startTask(HeadlessJsTaskService.java:97)
        at com.facebook.react.HeadlessJsTaskService.onStartCommand(HeadlessJsTaskService.java:48)
        at android.app.ActivityThread.handleServiceArgs(ActivityThread.java:3700)

<img width="1329" alt="Screenshot 2021-01-17 at 6 37 23 PM" src="https://user-images.githubusercontent.com/22396203/104843987-806f3100-58f3-11eb-9347-932bd9b94409.png">

**Comment by bhavesh18** [comment]
Got a reply from 'invertase/react-native-firebase'
https://github.com/invertase/react-native-firebase/issues/4802#issuecomment-763614269

**Comment by saghul** [comment]
We have diverged from the standard RN app structure because we use RN on the SDK part and not on the application part. I don't know a way around this TBH.

**Comment by iim-norse** [comment]
same problem,
somebody have solution ?

**Comment by iim-norse** [comment]
I find a fix (i am not android developer but its works for me)
added to` /android/app/src/main/AndroidManifest.xml`
`android:name=".MainApplication"`
so i have: 
 ```
<application
      android:name=".MainApplication"
      android:allowBackup="true"
      android:extractNativeLibs="true"
      android:icon="@mipmap/ic_launcher"
      android:label="@string/app_name"
      android:networkSecurityConfig="@xml/network_security_config"
      android:theme="@style/AppTheme">
    <meta-data
        android:name="android.content.APP_RESTRICTIONS"
        .....
```
and created file MainApplication.java
`/android/app/src/main/java/org/jitsi/meet/MainApplication.java`

```
package org.jitsi.meet;

import android.app.Application;
import android.content.Context;
import com.facebook.react.ReactApplication;
import com.facebook.react.ReactInstanceManager;
import com.facebook.react.ReactNativeHost;
import com.facebook.react.ReactPackage;
import com.facebook.soloader.SoLoader;
import java.lang.reflect.InvocationTargetException;
import java.util.List;
import java.util.ArrayList;
import java.util.Arrays;

public class MainApplication extends Application implements ReactApplication {
  @Override
  public void onCreate() {
    super.onCreate();
  }

  private final ReactNativeHost mReactNativeHost =
      new ReactNativeHost(this) {
        @Override
        public boolean getUseDeveloperSupport() {
          return BuildConfig.DEBUG;
        }

        @Override
        protected List<ReactPackage> getPackages() {
          List<ReactPackage> packages
            = new ArrayList<>(Arrays.asList(
                
              ));
          return packages;
        }

        @Override
        protected String getJSMainModuleName() {
          return "index";
        }
      };

  @Override
  public ReactNativeHost getReactNativeHost() {
    return mReactNativeHost;
  }
}
```
