### ISSUE TITLE
Latest Jitsi Crashing on Android 5.1

### ISSUE THREAD

**Issue by developerashish01** [jitsi/jitsi-meet#8667]
### Description:

Latest jitsi code's build is failing on Android 5.1

### Steps to reproduce:

1. Clone Jitsi from Master
2. build and run 
3. as soon as app launches, app gets crash

### Expected behavior:

It was also working fine 1 month ago. only failing below Android 6

### Actual behavior:

JitsiMeetSDK: JitsiMeetUncaughtExceptionHandler FATAL ERROR
    java.lang.NoClassDefFoundError: org.jitsi.meet.sdk.AudioDeviceHandlerGeneric$2
        at org.jitsi.meet.sdk.AudioDeviceHandlerGeneric.<init>(AudioDeviceHandlerGeneric.java:102)
        at org.jitsi.meet.sdk.AudioModeModule.setAudioDeviceHandler(AudioModeModule.java:227)
        at org.jitsi.meet.sdk.AudioModeModule.access$200(AudioModeModule.java:58)
        at org.jitsi.meet.sdk.AudioModeModule$2.run(AudioModeModule.java:214)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
        at java.lang.Thread.run(Thread.java:818)
    
    java.lang.NoClassDefFoundError: org.jitsi.meet.sdk.AudioDeviceHandlerGeneric$2
        at org.jitsi.meet.sdk.AudioDeviceHandlerGeneric.<init>(AudioDeviceHandlerGeneric.java:102)
        at org.jitsi.meet.sdk.AudioModeModule.setAudioDeviceHandler(AudioModeModule.java:227)
        at org.jitsi.meet.sdk.AudioModeModule.access$200(AudioModeModule.java:58)
        at org.jitsi.meet.sdk.AudioModeModule$2.run(AudioModeModule.java:214)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
        at java.lang.Thread.run(Thread.java:818)
FATAL EXCEPTION: pool-18-thread-1

    java.lang.NoClassDefFoundError: org.jitsi.meet.sdk.AudioDeviceHandlerGeneric$2
        at org.jitsi.meet.sdk.AudioDeviceHandlerGeneric.<init>(AudioDeviceHandlerGeneric.java:102)
        at org.jitsi.meet.sdk.AudioModeModule.setAudioDeviceHandler(AudioModeModule.java:227)
        at org.jitsi.meet.sdk.AudioModeModule.access$200(AudioModeModule.java:58)
        at org.jitsi.meet.sdk.AudioModeModule$2.run(AudioModeModule.java:214)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
        at java.lang.Thread.run(Thread.java:818)

TypeError: undefined is not an object (evaluating 'this.state.store.dispatch')
    
    This error is located at:
        in M
        in t
        in RCTView
        in RCTView
        in h
/unknown:ReactNative: TypeError: undefined is not an object (evaluating 'this.state.store.dispatch')
    
    This error is located at:
        in M
        in t
        in RCTView
        in RCTView
        in h, stack:
    value@926:906
    Ri@94:57222
    Ui@94:57947
    Di@94:60412
    Fl@94:76347
    Fl@-1
    unstable_runWithPriority@174:3915
    Dl@94:74615
    Dl@-1
    Pl@94:65839
    Pl@-1
    <unknown>@94:25495
    unstable_runWithPriority@174:3915
    sn@94:25442
    cn@94:25377
    kl@94:64831
    la@94:87813
    unmountComponentAtNode@94:90791
    unmountComponentAtNodeAndRemoveContainer@94:90909
    unmountApplicationComponentAtRootTag@341:1821
    value@36:3685
    <unknown>@36:841
    value@36:2939
    value@36:813
    value@-1
 E/JitsiMeetSDK: [features/app] Error(TypeError){"message":"undefined is not an object (evaluating 'this.state.store.dispatch')","stack":"value@index.android.bundle:926:906\nRi@index.android.bundle:94:57222\nUi@index.android.bundle:94:57947\nDi@index.android.bundle:94:60412\nFl@index.android.bundle:94:76347\nFl@[native code]\nunstable_runWithPriority@index.android.bundle:174:3915\nDl@index.android.bundle:94:74615\nDl@[native code]\nPl@index.android.bundle:94:65839\nPl@[native code]\nindex.android.bundle:94:25495\nunstable_runWithPriority@index.android.bundle:174:3915\nsn@index.android.bundle:94:25442\ncn@index.android.bundle:94:25377\nkl@index.android.bundle:94:64831\nla@index.android.bundle:94:87813\nunmountComponentAtNode@index.android.bundle:94:90791\nunmountComponentAtNodeAndRemoveContainer@index.android.bundle:94:90909\nunmountApplicationComponentAtRootTag@index.android.bundle:341:1821\nvalue@index.android.bundle:36:3685\nindex.android.bundle:36:841\nvalue@index.android.bundle:36:2939\nvalue@index.android.bundle:36:813\nvalue@[native code]"}

**Comment by saghul** [comment]
Jitsi Meet doesn't work on Android 5. 6 or higher is required. Nit sure how you built it, the minimum API level is 23.
