### ISSUE TITLE
Invalid "main" entry in babel, missing .js

### ISSUE THREAD

**Issue by licaon-kter** [jitsi/jitsi-meet#9030]
Debian Buster, arm64, nodejs 14.16.1, npm 7.9.0, HEAD (67ac48cac6c292d616729476e2515b8c1dff3711)

Can someone translate this error?
```
$ npm i && make
...
npm install --prefix resources/load-test && npm run build --prefix resources/load-test

up to date, audited 779 packages in 9s

4 vulnerabilities (2 low, 2 moderate)

To address all issues, run:
  npm audit fix

Run `npm audit` for details.

> jitsi-meet-load-test@0.0.0 build
> webpack -p

Hash: 8d3f3ffb98acbe386c94
Version: webpack 4.43.0
Child
    Hash: 8d3f3ffb98acbe386c94
    Time: 2057ms
    Built at: 17.04.2021 17:14:32
     2 assets
    Entrypoint load-test-participant = load-test-participant.min.js load-test-participant.min.map
    [0] ./load-test-participant.js 2.3 KiB {0} [built] [failed] [1 error]
    
    ERROR in ./load-test-participant.js
    Module build failed (from ./node_modules/babel-loader/lib/index.js):
    Error: [BABEL] /home/pi/jitsi/jitsi-meet/resources/load-test/load-test-participant.js: Cannot find module '/home/pi/jitsi/jitsi-meet/node_modules/@babel/core/node_modules/@babel/types/lib/index.js'. Please verify that the package.json has a valid "main" entry (While processing: "/home/pi/jitsi/jitsi-meet/node_modules/@babel/preset-react/lib/index.js$1")
        at tryPackage (internal/modules/cjs/loader.js:303:19)
        at Function.Module._findPath (internal/modules/cjs/loader.js:516:18)
        at Function.Module._resolveFilename (internal/modules/cjs/loader.js:867:27)
        at Function.Module._load (internal/modules/cjs/loader.js:725:27)
        at Module.require (internal/modules/cjs/loader.js:952:19)
        at require (/home/pi/jitsi/jitsi-meet/resources/load-test/node_modules/v8-compile-cache/v8-compile-cache.js:161:20)
        at _types (/home/pi/jitsi/jitsi-meet/node_modules/@babel/core/lib/index.js:164:40)
        at Object.get [as types] (/home/pi/jitsi/jitsi-meet/node_modules/@babel/core/lib/index.js:176:12)
        at /home/pi/jitsi/jitsi-meet/node_modules/@babel/plugin-transform-react-display-name/lib/index.js:65:46
        at /home/pi/jitsi/jitsi-meet/node_modules/@babel/helper-plugin-utils/lib/index.js:19:12
        at /home/pi/jitsi/jitsi-meet/resources/load-test/node_modules/@babel/core/lib/config/full.js:165:14
        at cachedFunction (/home/pi/jitsi/jitsi-meet/resources/load-test/node_modules/@babel/core/lib/config/caching.js:33:19)
        at loadPluginDescriptor (/home/pi/jitsi/jitsi-meet/resources/load-test/node_modules/@babel/core/lib/config/full.js:200:28)
        at /home/pi/jitsi/jitsi-meet/resources/load-test/node_modules/@babel/core/lib/config/full.js:69:20
        at Array.reduce (<anonymous>)
        at recurseDescriptors (/home/pi/jitsi/jitsi-meet/resources/load-test/node_modules/@babel/core/lib/config/full.js:67:38)
        at recurseDescriptors (/home/pi/jitsi/jitsi-meet/resources/load-test/node_modules/@babel/core/lib/config/full.js:94:27)
        at loadFullConfig (/home/pi/jitsi/jitsi-meet/resources/load-test/node_modules/@babel/core/lib/config/full.js:108:6)
        at /home/pi/jitsi/jitsi-meet/resources/load-test/node_modules/@babel/core/lib/transform.js:28:33
        at processTicksAndRejections (internal/process/task_queues.js:75:11)
make: *** [Makefile:25: compile-load-test] Error 2
```

**Comment by damencho** [comment]
Please when you have questions or problems use the community forum before opening new issues, thank you.

**Comment by licaon-kter** [comment]
Done https://community.jitsi.org/t/invalid-main-entry-in-babel-missing-js/97897

**Comment by saghul** [comment]
We develop and test on Node 12 / npm 6, I'd recommend you try with those first.

**Comment by licaon-kter** [comment]
I've switched to latest nodejs LTS from Buster provided 10 just to be up to date, since it was failing and asking for 12. :)

I'll try asap.

**Comment by licaon-kter** [comment]
Looks like it's going further with nodejs 12 and npm 6. Not a success yet as it oom-s along the way.

Thanks
