### ISSUE TITLE
RNCNetInfo.getCurrentState got 2 arguments, expected 3  FATAL EXCEPTION: mqt_native_modules 

### ISSUE THREAD

**Issue by TarekBaccari** [jitsi/jitsi-meet#9235]
i m using react-native-jitsi-meet 
when invoking the JitsiMeetView component , a crash is is accrued

**information 
react native 0.63.4
"@react-native-community/netinfo": "^5.9.5"
hermes disabled** 

> i tried to resolve the problem as indicated here (https://github.com/jitsi/jitsi-meet/issues/6812) but it doesn't work for me 

FATAL EXCEPTION: mqt_native_modules

com.facebook.react.bridge.NativeArgumentsParseException: RNCNetInfo.getCurrentState got 2 arguments, expected 3

FATAL EXCEPTION: mqt_native_modules
Process: com.diama, PID: 13246
com.facebook.react.bridge.NativeArgumentsParseException: RNCNetInfo.getCurrentState got 2 arguments, expected 3
	at com.facebook.react.bridge.JavaMethodWrapper.invoke(JavaMethodWrapper.java:349)
	at com.facebook.react.bridge.JavaModuleWrapper.invoke(JavaModuleWrapper.java:151)
	at com.facebook.react.bridge.queue.NativeRunnable.run(Native Method)
	at android.os.Handler.handleCallback(Handler.java:883)
	at android.os.Handler.dispatchMessage(Handler.java:100)
	at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:27)
	at android.os.Looper.loop(Looper.java:214)
	at com.facebook.react.bridge.queue.MessageQueueThreadImpl$4.run(MessageQueueThreadImpl.java:226)
	at java.lang.Thread.run(Thread.java:919)

**Comment by saghul** [comment]
> i m using react-native-jitsi-meet

We don't maintain that package. Please ask the maintainer.

**Comment by TarekBaccari** [comment]
> > i m using react-native-jitsi-meet
> 
> We don't maintain that package. Please ask the maintainer.

thanks
