### ISSUE TITLE
React Native Reanimated error : null is not an object _Reanimated module.default.createNode is not found, I tried manually linking the library and it gives the following 

### ISSUE THREAD

**Issue by Asad-Comm** [jitsi/jitsi-meet#9299]
### Description:

Error : error Linking "react-native-reanimated" failed. Run CLI with --verbose flag for more details.
Error: ENOENT: no such file or directory, open '/Users/asad/Desktop/jitsi-meet-stable-jitsi-meet_5870/android/app/src/main/java/org/jitsi/meet/MainApplication.java'
at Object.openSync (node:fs:505:3)
at Object.readFileSync (node:fs:401:35)
at applyPatch (/Users/asad/Desktop/jitsi-meet-stable-jitsi-meet_5870/node_modules/@react-native-community/cli-platform-android/build/link/patches/applyPatch.js:42:51)
at Object.registerNativeAndroidModule [as register] (/Users/asad/Desktop/jitsi-meet-stable-jitsi-meet_5870/node_modules/@react-native-community/cli-platform-android/build/link/registerNativeModule.js:34:27)
at /Users/asad/Desktop/jitsi-meet-stable-jitsi-meet_5870/node_modules/react-native/node_modules/@react-native-community/cli/build/commands/link/linkDependency.js:63:16
at Array.forEach ()
at linkDependency (/Users/asad/Desktop/jitsi-meet-stable-jitsi-meet_5870/node_modules/react-native/node_modules/@react-native-community/cli/build/commands/link/linkDependency.js:36:32)
at processTicksAndRejections (node:internal/process/task_queues:94:5)
at async Object.link [as func] (/Users/asad/Desktop/jitsi-meet-stable-jitsi-meet_5870/node_modules/react-native/node_modules/@react-native-community/cli/build/commands/link/link.js:107:5)
at async Command.handleAction (/Users/asad/Desktop/jitsi-meet-stable-jitsi-meet_5870/node_modules/react-native/node_modules/@react-native-community/cli/build/index.js:182:9)
Admins-Mac-mini-6:jitsi-meet-stable-jitsi-meet_5870 asad$ react-native link react-native-reanimated
(node:42695) Warning: Accessing non-existent property 'padLevels' of module exports inside circular dependency
(Use node --trace-warnings ... to show where the warning was created)
info iOS module "react-native-reanimated" is already linked
info Android module "react-native-reanimated" is already linked
Admins-Mac-mini-6:jitsi-meet-stable-jitsi-meet_5870 asad$ react-native unlink react-native-reanimated
info Unlinking "react-native-reanimated" iOS dependency
(node:42697) Warning: Accessing non-existent property 'padLevels' of module exports inside circular dependency
(Use node --trace-warnings ... to show where the warning was created)
error Something went wrong while unlinking. Reason Cannot read property 'find' of undefined. Run CLI with --verbose flag for more details.
TypeError: Cannot read property 'find' of undefined
at removeFromProjectReferences (/Users/asad/Desktop/jitsi-meet-stable-jitsi-meet_5870/node_modules/@react-native-community/cli-platform-ios/build/link/removeFromProjectReferences.js:30:53)
at removeProjectFromProject (/Users/asad/Desktop/jitsi-meet-stable-jitsi-meet_5870/node_modules/@react-native-community/cli-platform-ios/build/link/removeProjectFromProject.js:45:63)
at unregisterNativeModule (/Users/asad/Desktop/jitsi-meet-stable-jitsi-meet_5870/node_modules/@react-native-community/cli-platform-ios/build/link/unregisterNativeModule.js:99:54)
at Object.unregisterNativeModule [as unregister] (/Users/asad/Desktop/jitsi-meet-stable-jitsi-meet_5870/node_modules/@react-native-community/cli-platform-ios/build/link/common/unregisterNativeModule.js:42:41)
at /Users/asad/Desktop/jitsi-meet-stable-jitsi-meet_5870/node_modules/react-native/node_modules/@react-native-community/cli/build/commands/link/unlink.js:65:16
at Array.forEach ()
at unlinkDependency (/Users/asad/Desktop/jitsi-meet-stable-jitsi-meet_5870/node_modules/react-native/node_modules/@react-native-community/cli/build/commands/link/unlink.js:41:32)
at Object.unlink [as func] (/Users/asad/Desktop/jitsi-meet-stable-jitsi-meet_5870/node_modules/react-native/node_modules/@react-native-community/cli/build/commands/link/unlink.js:110:5)
at Command.handleAction (/Users/asad/Desktop/jitsi-meet-stable-jitsi-meet_5870/node_modules/react-native/node_modules/@react-native-community/cli/build/index.js:182:23)
at Command.listener (/Users/asad/Desktop/jitsi-meet-stable-jitsi-meet_5870/node_modules/commander/index.js:315:8)

### Steps to reproduce:

1. Add react navigation 5 and install the required libraries like gesture handler and reanimated
2. Gesture handler can be added as a package in ReactInstanceManagerHolder.java file in the android sdk successfully
3. But on adding the reanimated library its giving errors so i tried linking it and it gave the error mentioned in the description box.
4. Kindly help in adding react navigation to the project.

### Server information:

- Jitsi Meet version:
- Operating System:

### Client information:

- Browser / app version:
- Operating System:

**Comment by Asad-Comm** [comment]
Error : error Linking "react-native-reanimated" failed. Run CLI with --verbose flag for more details.
Error: ENOENT: no such file or directory, open '/Users/asad/Desktop/jitsi-meet-stable-jitsi-meet_5870/android/app/src/main/java/org/jitsi/meet/MainApplication.java'
    at Object.openSync (node:fs:505:3)
    at Object.readFileSync (node:fs:401:35)
    at applyPatch (/Users/asad/Desktop/jitsi-meet-stable-jitsi-meet_5870/node_modules/@react-native-community/cli-platform-android/build/link/patches/applyPatch.js:42:51)
    at Object.registerNativeAndroidModule [as register] (/Users/asad/Desktop/jitsi-meet-stable-jitsi-meet_5870/node_modules/@react-native-community/cli-platform-android/build/link/registerNativeModule.js:34:27)
    at /Users/asad/Desktop/jitsi-meet-stable-jitsi-meet_5870/node_modules/react-native/node_modules/@react-native-community/cli/build/commands/link/linkDependency.js:63:16
    at Array.forEach (<anonymous>)
    at linkDependency (/Users/asad/Desktop/jitsi-meet-stable-jitsi-meet_5870/node_modules/react-native/node_modules/@react-native-community/cli/build/commands/link/linkDependency.js:36:32)
    at processTicksAndRejections (node:internal/process/task_queues:94:5)
    at async Object.link [as func] (/Users/asad/Desktop/jitsi-meet-stable-jitsi-meet_5870/node_modules/react-native/node_modules/@react-native-community/cli/build/commands/link/link.js:107:5)
    at async Command.handleAction (/Users/asad/Desktop/jitsi-meet-stable-jitsi-meet_5870/node_modules/react-native/node_modules/@react-native-community/cli/build/index.js:182:9)
Admins-Mac-mini-6:jitsi-meet-stable-jitsi-meet_5870 asad$ react-native link react-native-reanimated
(node:42695) Warning: Accessing non-existent property 'padLevels' of module exports inside circular dependency
(Use `node --trace-warnings ...` to show where the warning was created)
info iOS module "react-native-reanimated" is already linked
info Android module "react-native-reanimated" is already linked
Admins-Mac-mini-6:jitsi-meet-stable-jitsi-meet_5870 asad$ react-native unlink react-native-reanimated
info Unlinking "react-native-reanimated" iOS dependency
(node:42697) Warning: Accessing non-existent property 'padLevels' of module exports inside circular dependency
(Use `node --trace-warnings ...` to show where the warning was created)
error Something went wrong while unlinking. Reason Cannot read property 'find' of undefined. Run CLI with --verbose flag for more details.
TypeError: Cannot read property 'find' of undefined
    at removeFromProjectReferences (/Users/asad/Desktop/jitsi-meet-stable-jitsi-meet_5870/node_modules/@react-native-community/cli-platform-ios/build/link/removeFromProjectReferences.js:30:53)
    at removeProjectFromProject (/Users/asad/Desktop/jitsi-meet-stable-jitsi-meet_5870/node_modules/@react-native-community/cli-platform-ios/build/link/removeProjectFromProject.js:45:63)
    at unregisterNativeModule (/Users/asad/Desktop/jitsi-meet-stable-jitsi-meet_5870/node_modules/@react-native-community/cli-platform-ios/build/link/unregisterNativeModule.js:99:54)
    at Object.unregisterNativeModule [as unregister] (/Users/asad/Desktop/jitsi-meet-stable-jitsi-meet_5870/node_modules/@react-native-community/cli-platform-ios/build/link/common/unregisterNativeModule.js:42:41)
    at /Users/asad/Desktop/jitsi-meet-stable-jitsi-meet_5870/node_modules/react-native/node_modules/@react-native-community/cli/build/commands/link/unlink.js:65:16
    at Array.forEach (<anonymous>)
    at unlinkDependency (/Users/asad/Desktop/jitsi-meet-stable-jitsi-meet_5870/node_modules/react-native/node_modules/@react-native-community/cli/build/commands/link/unlink.js:41:32)
    at Object.unlink [as func] (/Users/asad/Desktop/jitsi-meet-stable-jitsi-meet_5870/node_modules/react-native/node_modules/@react-native-community/cli/build/commands/link/unlink.js:110:5)
    at Command.handleAction (/Users/asad/Desktop/jitsi-meet-stable-jitsi-meet_5870/node_modules/react-native/node_modules/@react-native-community/cli/build/index.js:182:23)
    at Command.listener (/Users/asad/Desktop/jitsi-meet-stable-jitsi-meet_5870/node_modules/commander/index.js:315:8)
