### ISSUE TITLE
java.lang.AssertionError: Pausing an activity that is not the current activity, this is incorrect

### ISSUE THREAD

**Issue by nknr** [jitsi/jitsi-meet#9856]
### Description:

I have two activity where need to open jitsi-meet-view in both activities. App crash when I start second activity

> ava.lang.AssertionError: Pausing an activity that is not the current activity, this is incorrect! Current activity: ThirdActivity Paused activity: SecondSolutionActivity
at com.facebook.infer.annotation.Assertions.assertCondition(Assertions.java:72)
at com.facebook.react.ReactInstanceManager.onHostPause(ReactInstanceManager.java:511)
at org.jitsi.meet.sdk.JitsiMeetActivityDelegate.onHostPause(JitsiMeetActivityDelegate.java:124)
at org.jitsi.meet.sdk.JitsiMeetFragment.onStop(JitsiMeetFragment.java:78)
at androidx.fragment.app.Fragment.performStop(Fragment.java:3184)
at androidx.fragment.app.FragmentStateManager.stop(FragmentStateManager.java:640)
at androidx.fragment.app.FragmentStateManager.moveToExpectedState(FragmentStateManager.java:320)
at androidx.fragment.app.FragmentStore.moveToExpectedState(FragmentStore.java:112)
at androidx.fragment.app.FragmentManager.moveToState(FragmentManager.java:1647)
at androidx.fragment.app.FragmentManager.dispatchStateChange(FragmentManager.java:3128)
at androidx.fragment.app.FragmentManager.dispatchStop(FragmentManager.java:3096)
at androidx.fragment.app.FragmentController.dispatchStop(FragmentController.java:295)
at androidx.fragment.app.FragmentActivity.onStop(FragmentActivity.java:525)
at androidx.appcompat.app.AppCompatActivity.onStop(AppCompatActivity.java:252)
at android.app.Instrumentation.callActivityOnStop(Instrumentation.java:1375)
at android.app.Activity.performStop(Activity.java:7191)
at android.app.ActivityThread.performDestroyActivity(ActivityThread.java:4340)
at android.app.ActivityThread.handleDestroyActivity(ActivityThread.java:4401)
at android.app.ActivityThread.-wrap5(Unknown Source:0)
at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1649)
at android.os.Handler.dispatchMessage(Handler.java:106)
at android.os.Looper.loop(Looper.java:164)
at android.app.ActivityThread.main(ActivityThread.java:6494)
at java.lang.reflect.Method.invoke(Native Method)
at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)
2021-09-02 10:13:36.427 6967-6967/net.jitsi.sdktest E/JitsiMeetSDK: JitsiMeetUncaughtExceptionHandler FATAL ERROR

### Steps to reproduce:

1. join a room in the first activity and leave
2. start a new activity on button press from first activity

### Expected behavior:

Join room in the second activity

### Actual behavior:

App crash

### Server information:

- Jitsi Meet version:
- Operating System:

### Client information:

- Browser / app version: 3.7.0
- Operating System: Android

### Leave meeting

```
private fun getJitsiView(): JitsiMeetView? {
        val fragment =
            this.supportFragmentManager.findFragmentById(R.id.jitsiFragment) as? JitsiMeetFragment
        return fragment?.jitsiView
    }

    private fun leave() {
        if(!isRoomLeave) {
            val view = getJitsiView()
            view?.let {
                it.leave()
                it.dispose()
                //it.removeAllViews()
                //JitsiMeetActivityDelegate.onHostDestroy(this)
            }
        }
        //view?.leave() ?: JitsiMeetLogger.w("Cannot leave, view is null", *arrayOfNulls(0))
    }
```

#### Start new activity

```
fun launch(context: Context, options: JitsiMeetConferenceOptions) {
            val intent = Intent(context, SecondSolutionActivity::class.java)
            intent.action = ACTION_JITSI_MEET_CONFERENCE
            intent.putExtra(JITSI_MEET_CONFERENCE_OPTIONS, options)
            context.startActivity(intent)
        }

private fun getConferenceOptions(intent: Intent): JitsiMeetConferenceOptions? {
        if (ACTION_JITSI_MEET_CONFERENCE == intent.action) {
            return intent.getParcelableExtra<Parcelable>(JITSI_MEET_CONFERENCE_OPTIONS) as? JitsiMeetConferenceOptions
        }
        return null
    }

    fun onNewMeeting(view: View) {
        ThirdActivity.launch(this, getConferenceOptions(this.intent))
        finish()
    }
```

**Comment by saghul** [comment]
It's not possible to do that. Only one Activity at a time is supported.

**Comment by nknr** [comment]
I have also tried but not working.
```
fun onNewMeeting(view: View) {
        leave()
        ThirdActivity.launch(this, getConferenceOptions(this.intent))
        finish()
    }
```
